--AMOUNT VALUE NOT UPDATED
SELECT *, AMOUNT - EXTMERCH AS OVERS
FROM (
		SELECT 
		OH.TRANSACTIONDATE, 
		OH.COMMITDATE, --OH.RECORDTYPE, OH.STAGE, OH.TRANSACTIONTYPE,
		OH.TRANSACTIONNUMBER, 
		OD.LINENUMBER,
		IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QUANTITY, 
		ITM.ITEMCODE,
		OD.UNITPRICE,
		OD.UNITPRICE * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS EXTUNITPRICE,
		OD.HANDLINGCHARGEPERITEM,OD.TAGGINGCHARGEPERITEM, 
		(OD.UNITPRICE+ISNULL(OD.HANDLINGCHARGEPERITEM,0) +ISNULL(OD.TAGGINGCHARGEPERITEM,0)) * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS EXTMERCH,

		IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0))				-->THIS CODE REPLACES ISNULL(OD.FREIGHTRATEPERITEM, 0) 
		* IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS EXTFREIGHT,
		OD.AMOUNT,
		OD.FEESADDED, OD.FEESINCLUDED,
		OD.FEESADDED * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS EXTFEESADDED, 
		OD.FEESINCLUDED * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS EXTFEESINCLUDED,
		DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
		WHERE OH.STAGE != 'L'
		AND OH.RECORDTYPE = 'Z'
		AND OH.TRANSACTIONTYPE = 'I'
	) X
WHERE ROUND(EXTUNITPRICE,2) != ROUND(AMOUNT,2)
ORDER BY COMMITDATE






