--Brand Mgmt Fee Income
--and left(itm.ITEMCODE,6) = '005252'

--------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
--ROYALTY FEE INCOME
SELECT
*
FROM VW_RPT_ROYALTY_FEE_INCOME (NOLOCK)
WHERE COMPANYID = 'SB'
ORDER BY INVOICEDATE
*/
--CREATE OR ALTER VIEW [DBO].[VW_RPT_ROYALTY_FEE_INCOME]
--AS

SELECT 
	X.*, 
	X.QTYINVOICED + X.QTYMEMOED AS QTYTOTAL,
	X.LICENSERATE * (X.QTYINVOICED + X.QTYMEMOED) AS LICENSERATETOTAL,
	X.INTERDIVRATE * (X.QTYINVOICED + X.QTYMEMOED) AS INTERDIVRATETOTAL,
	X.SUBLICENSERATE * (X.QTYINVOICED + X.QTYMEMOED) AS SUBLICENSERATETOTAL
FROM (
		SELECT 
			CO.COMPANYID, CO.NAME AS COMPANYNAME, 
			WH.IDENTITYID AS WAREHOUSEID, WH.NAME AS WAREHOUSENAME, 
			OH.STAGE, OH.RECORDTYPE, 
			OH.TRANSACTIONDATE, OH.SHIPPINGDATE, OH.INVOICEDATE, 
			OH.TRANSACTIONTYPE, 
			OD.USERDEFINEDCODE_1 AS CREDITREASONCODE, 
			OD.USERDEFINEDREFERENCE_2 AS NETWORKTEXT, 
			IIF(OH.TRANSACTIONTYPE = 'I', OD.QUANTITYSHIPPED, 0) AS QTYINVOICED, 
			IIF(OH.TRANSACTIONTYPE IN ('C','J') AND LEFT(OD.USERDEFINEDCODE_1,2) = 'FC', OD.QUANTITYSHIPPED * -1, 0) AS QTYMEMOED, 
			IIF(OD.USERDEFINEDREFERENCE_2 LIKE '%NETWORK%', OD.QUANTITYSHIPPED, 0) AS QTYNETWORK, 
			ITM.USERDEFINEDCODE_16 AS LICPRIMARYHOLDER, 
			(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDERDESC, 
			ITM.ITEMCODE, ITM.REFERENCE_1 AS COMMONNAME, --NULLIF(ITM.USERDEFINEDREFERENCE_1,'') AS PATENT, 
			ITM.USERDEFINEDCODE_2 AS BRAND, 
			OD.R_FEES, 
			ITMP.PROFILECODE AS VARIETY, ITMP.DESCRIPTION VARIETYDESCRIPTION, 
			CNT.PRINTEDCONTAINERCODE, CNT.CONTAINERCODE, CNT.FREIGHTCLASSCODE, 
			J.MISCFEECODE, 
			J.LICENSERATE, 
			J.INTERDIVRATE, 
			J.SUBLICENSERATE, 
			J.EFFECTIVESTARTDATE, 
			J.HOLDERID, J.HOLDERNAME
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN  OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			LEFT JOIN (
					SELECT 
						U.MISCFEECODE, 
						U.VARIETY, U.FREIGHTCLASSCODE, 
						SUM(U.LICENSERATE) AS LICENSERATE,
						SUM(U.INTERDIVRATE) AS INTERDIVRATE,
						SUM(U.SUBLICENSERATE) AS SUBLICENSERATE,
						U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
					FROM ( 

							--LICENSE FEES IN GENERAL
							SELECT 
							FH.MISCFEECODE, 
							LEFT(FH.MISCFEECODE,6) AS VARIETY, 
							--SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),4) AS TEST,

							CASE SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),3)
								--WHEN '.1' THEN 'C008'
								WHEN '.1' THEN 'C010'
								WHEN '.2' THEN 'C020'
								WHEN '.3' THEN 'C030'
								WHEN '.4' THEN 'C040'
								WHEN '.5' THEN 'C050'
								WHEN '.7' THEN 'C070'
								WHEN '.10' THEN 'C100'
								WHEN '00' THEN '%'
							ELSE (	SELECT CNT.CONTAINERCODE 
									FROM IMCONTAINER CNT (NOLOCK)
									WHERE CNT.CONTAINERCODE = SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE)+1,0),3)
									) 
							END AS FREIGHTCLASSCODE, 
							FD.RATE AS LICENSERATE, 
							0 AS INTERDIVRATE, 
							0 AS SUBLICENSERATE, 
							FD.EFFECTIVESTARTDATE, 
							VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
							FROM IMFEESHEADER FH (NOLOCK)
							JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'License%'
							--LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
							JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
							WHERE FD.RECORDTYPE = 'R' 
							AND FD.RATE IS NOT NULL 
							--AND FP.PROFILECODE = 'SUBFEES'
							--AND VEND.IDENTITYID IN ('GRE087','LIC003')
							--AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'

							UNION ALL

							--VARIETY LEVEL INTERDIV
							SELECT 
							FH.MISCFEECODE, 
							LEFT(FH.MISCFEECODE,6) AS VARIETY, 
							'%' AS FREIGHTCLASSCODE, 
							0 AS LICENSERATE, 
							FD.RATE AS INTERDIVRATE, 
							0 AS SUBLICENSERATE, 
							FD.EFFECTIVESTARTDATE, 
							VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
							FROM IMFEESHEADER FH (NOLOCK)
							JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
							JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
							JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
							WHERE FD.RECORDTYPE = 'R' 
							AND FD.RATE IS NOT NULL 
							AND FP.PROFILECODE = 'SUBFEES'
							AND VEND.IDENTITYID IN ('GRE087','LIC003')
							AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'

							UNION ALL

							--VARIETY LEVEL SUBLICENSE
							SELECT 
							FH.MISCFEECODE, 
							LEFT(FH.MISCFEECODE,6) AS VARIETY, 
							'%' AS FREIGHTCLASSCODE, 
							0 AS LICENSERATE, 
							0 AS INTERDIVRATE, 
							FD.RATE AS SUBLICENSERATE, 
							FD.EFFECTIVESTARTDATE, 
							VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
							FROM IMFEESHEADER FH (NOLOCK)
							JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
							JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
							JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
							WHERE FD.RECORDTYPE = 'R' 
							AND FD.RATE IS NOT NULL 
							AND FP.PROFILECODE = 'SUBFEES'
							AND VEND.IDENTITYID IN ('GRE087','LIC003')
							AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'

							UNION ALL

							--CLASS LEVEL INTERDIV
							SELECT 
							FH.MISCFEECODE, 
							LEFT(FH.MISCFEECODE,6) AS VARIETY, 
							CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
								--WHEN '.1' THEN 'C008'
								WHEN '.1' THEN 'C010'
								WHEN '.2' THEN 'C020'
								WHEN '.3' THEN 'C030'
								WHEN '.4' THEN 'C040'
								WHEN '.5' THEN 'C050'
								WHEN '.7' THEN 'C070'
								WHEN '.10' THEN 'C100'
							ELSE NULL END AS FREIGHTCLASSCODE, 
							0 AS LICENSERATE, 
							FD.RATE AS INTERDIVRATE, 
							0 AS SUBLICENSERATE, 
							FD.EFFECTIVESTARTDATE, 
							VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
							FROM IMFEESHEADER FH (NOLOCK)
							JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
							JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
							JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
							WHERE FD.RECORDTYPE = 'R' 
							AND FD.RATE IS NOT NULL 
							AND FP.PROFILECODE = 'SUBFEES'
							AND VEND.IDENTITYID IN ('GRE087','LIC003')
							AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'

							UNION ALL

							--CLASS LEVEL SUBLICENSE
							SELECT 
							FH.MISCFEECODE, 
							LEFT(FH.MISCFEECODE,6) AS VARIETY, 
							CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
								--WHEN '.1' THEN 'C008'
								WHEN '.1' THEN 'C010'
								WHEN '.2' THEN 'C020'
								WHEN '.3' THEN 'C030'
								WHEN '.4' THEN 'C040'
								WHEN '.5' THEN 'C050'
								WHEN '.7' THEN 'C070'
								WHEN '.10' THEN 'C100'
							ELSE NULL END AS FREIGHTCLASSCODE, 
							0 AS LICENSERATE, 
							0 AS INTERDIVRATE, 
							FD.RATE AS SUBLICENSERATE, 
							FD.EFFECTIVESTARTDATE, 
							VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
							FROM IMFEESHEADER FH (NOLOCK)
							JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
							JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
							JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
							WHERE FD.RECORDTYPE = 'R' 
							AND FD.RATE IS NOT NULL 
							AND FP.PROFILECODE = 'SUBFEES'
							AND VEND.IDENTITYID IN ('GRE087','LIC003')
							AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'

					) U
					GROUP BY 	U.MISCFEECODE, U.VARIETY, U.FREIGHTCLASSCODE, U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
			) J ON J.VARIETY = ITMP.PROFILECODE AND (J.FREIGHTCLASSCODE IN (CNT.CONTAINERCODE, CNT.FREIGHTCLASSCODE) OR (J.FREIGHTCLASSCODE='C010' AND CNT.FREIGHTCLASSCODE='C008')) 
		WHERE OH.RECORDTYPE <> 'P' 
		AND LEFT(OH.TRANSACTIONNUMBER,2) != 'IC' --EXCLUDE INTERCOMPANY ORDERS 
		AND WH.IDENTITYID < '999' 
		AND J.EFFECTIVESTARTDATE <= OH.INVOICEDATE
) X 



--------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
SELECT 
	X.*, 
	X.QTYINVOICED + X.QTYMEMOED AS QTYTOTAL,
	X.LICENSERATE * (X.QTYINVOICED + X.QTYMEMOED) AS LICENSERATETOTAL,
	X.INTERDIVRATE * (X.QTYINVOICED + X.QTYMEMOED) AS INTERDIVRATETOTAL,
	X.SUBLICENSERATE * (X.QTYINVOICED + X.QTYMEMOED) AS SUBLICENSERATETOTAL
FROM (
		SELECT 
			CO.COMPANYID, CO.NAME AS COMPANYNAME, 
			WH.IDENTITYID AS WAREHOUSEID, WH.NAME AS WAREHOUSENAME, 
			OH.STAGE, OH.RECORDTYPE, 
			OH.TRANSACTIONDATE, OH.SHIPPINGDATE, OH.INVOICEDATE, 
			OH.TRANSACTIONTYPE, 
			OD.USERDEFINEDCODE_1 AS CREDITREASONCODE, 
			OD.USERDEFINEDREFERENCE_2 AS NETWORKTEXT, 
			IIF(OH.TRANSACTIONTYPE = 'I', OD.QUANTITYSHIPPED, 0) AS QTYINVOICED, 
			IIF(OH.TRANSACTIONTYPE IN ('C','J') AND LEFT(OD.USERDEFINEDCODE_1,2) = 'FC', OD.QUANTITYSHIPPED * -1, 0) AS QTYMEMOED, 
			IIF(OD.USERDEFINEDREFERENCE_2 LIKE '%NETWORK%', OD.QUANTITYSHIPPED, 0) AS QTYNETWORK, 
			ITM.USERDEFINEDCODE_16 AS LICPRIMARYHOLDER, 
			(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDERDESC, 
			ITM.ITEMCODE, ITM.REFERENCE_1 AS COMMONNAME, --NULLIF(ITM.USERDEFINEDREFERENCE_1,'') AS PATENT, 
			ITM.USERDEFINEDCODE_2 AS BRAND, 
			OD.R_FEES, 
			Z.VARIETY, Z.VARIETYDESCRIPTION, 
			Z.PRINTEDCONTAINERCODE, Z.FREIGHTCLASSCODE, 
			Z.MISCFEECODE, 
			Z.LICENSERATE, 
			Z.INTERDIVRATE, 
			Z.SUBLICENSERATE, 
			Z.EFFECTIVESTARTDATE, 
			Z.HOLDERID, Z.HOLDERNAME
					   			 		  
			--ITMP.PROFILECODE AS VARIETY, ITMP.DESCRIPTION VARIETYDESCRIPTION, 
			--CNT.PRINTEDCONTAINERCODE, 
			--FH.MISCFEECODE, 
			--FD.EFFECTIVESTARTDATE, 
			--FD.RATE AS LICENSERATE, 
			--VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 

		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN  OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 

			--JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
			--JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			--JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES 
			--JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.EFFECTIVESTARTDATE <= OH.INVOICEDATE AND FD.DESCRIPTION LIKE 'LICENSE%' 
			--JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 

			JOIN (
					SELECT 
						WH.IDENTITYID AS WAREHOUSEID, 
						ITM.ITEMCODE, 
						ITMP.PROFILECODE AS VARIETY, ITMP.DESCRIPTION VARIETYDESCRIPTION, 
						CNT.PRINTEDCONTAINERCODE, 
						CNT.FREIGHTCLASSCODE, J.FREIGHTCLASSCODE AS TEST, 
						J.MISCFEECODE, 
						J.LICENSERATE, 
						J.INTERDIVRATE, 
						J.SUBLICENSERATE, 
						J.EFFECTIVESTARTDATE, 
						J.HOLDERID, J.HOLDERNAME

					FROM IMITEM ITM (NOLOCK) 
					JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
					JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
					JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
					JOIN (
							--BRAND MANAGEMENT FEE CODES
							SELECT 
								U.MISCFEECODE, 
								U.VARIETY, U.FREIGHTCLASSCODE, 
								SUM(U.LICENSERATE) AS LICENSERATE,
								SUM(U.INTERDIVRATE) AS INTERDIVRATE,
								SUM(U.SUBLICENSERATE) AS SUBLICENSERATE,
								U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
							FROM ( 

									--LICENSE FEES IN GENERAL
									SELECT 
									--'LICENSE GENERAL' AS LEVEL, 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									--SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),4) AS TEST,
									CASE SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),3)
										--WHEN '.1' THEN 'C008'
										WHEN '.1' THEN 'C010'
										WHEN '.2' THEN 'C020'
										WHEN '.3' THEN 'C030'
										WHEN '.4' THEN 'C040'
										WHEN '.5' THEN 'C050'
										WHEN '.7' THEN 'C070'
										WHEN '.10' THEN 'C100'
										WHEN '00' THEN '%'
									ELSE (	SELECT CNT.CONTAINERCODE 
											FROM IMCONTAINER CNT (NOLOCK)
											WHERE CNT.CONTAINERCODE = SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE)+1,0),3)
											) 
									END AS FREIGHTCLASSCODE, 
									FD.RATE AS LICENSERATE, 
									0 AS INTERDIVRATE, 
									0 AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'License%'
									--LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									WHERE FD.RECORDTYPE = 'R' 
									AND FD.RATE IS NOT NULL 
									--AND FP.PROFILECODE = 'SUBFEES'
									--AND VEND.IDENTITYID IN ('GRE087','LIC003')
									--AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
									--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE
/*
									UNION ALL

									--VARIETY LEVEL INTERDIV
									SELECT 
									--'VARIETY INTERDIVISION' AS LEVEL, 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									'%' AS FREIGHTCLASSCODE, 
									0 AS LICENSERATE, 
									FD.RATE AS INTERDIVRATE, 
									0 AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
									JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									WHERE FD.RECORDTYPE = 'R' 
									AND FD.RATE IS NOT NULL 
									AND FP.PROFILECODE = 'SUBFEES'
									AND VEND.IDENTITYID IN ('GRE087','LIC003')
									AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
									--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

									UNION ALL

									--VARIETY LEVEL SUBLICENSE
									SELECT 
									--'VARIETY SUBLICENSE' AS LEVEL, 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									'%' AS FREIGHTCLASSCODE, 
									0 AS LICENSERATE, 
									0 AS INTERDIVRATE, 
									FD.RATE AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
									JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									WHERE FD.RECORDTYPE = 'R' 
									AND FD.RATE IS NOT NULL 
									AND FP.PROFILECODE = 'SUBFEES'
									AND VEND.IDENTITYID IN ('GRE087','LIC003')
									AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
									--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

									UNION ALL

									--CLASS LEVEL INTERDIV
									SELECT 
									--'CLASS INTERDIVISION' AS LEVEL, 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
										--WHEN '.1' THEN 'C008'
										WHEN '.1' THEN 'C010'
										WHEN '.2' THEN 'C020'
										WHEN '.3' THEN 'C030'
										WHEN '.4' THEN 'C040'
										WHEN '.5' THEN 'C050'
										WHEN '.7' THEN 'C070'
										WHEN '.10' THEN 'C100'
									ELSE NULL END AS FREIGHTCLASSCODE, 
									0 AS LICENSERATE, 
									FD.RATE AS INTERDIVRATE, 
									0 AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
									JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									WHERE FD.RECORDTYPE = 'R' 
									AND FD.RATE IS NOT NULL 
									AND FP.PROFILECODE = 'SUBFEES'
									AND VEND.IDENTITYID IN ('GRE087','LIC003')
									AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'
									--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

									UNION ALL

									--CLASS LEVEL SUBLICENSE
									SELECT 
									--'CLASS SUBLICENSE' AS LEVEL, 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
										--WHEN '.1' THEN 'C008'
										WHEN '.1' THEN 'C010'
										WHEN '.2' THEN 'C020'
										WHEN '.3' THEN 'C030'
										WHEN '.4' THEN 'C040'
										WHEN '.5' THEN 'C050'
										WHEN '.7' THEN 'C070'
										WHEN '.10' THEN 'C100'
									ELSE NULL END AS FREIGHTCLASSCODE, 
									0 AS LICENSERATE, 
									0 AS INTERDIVRATE, 
									FD.RATE AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
									JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									WHERE FD.RECORDTYPE = 'R' 
									AND FD.RATE IS NOT NULL 
									AND FP.PROFILECODE = 'SUBFEES'
									AND VEND.IDENTITYID IN ('GRE087','LIC003')
									AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'
									--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE
*/
							) U
							GROUP BY 	U.MISCFEECODE, U.VARIETY, U.FREIGHTCLASSCODE, U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
					) J ON J.VARIETY = ITMP.PROFILECODE AND (J.FREIGHTCLASSCODE IN (CNT.CONTAINERCODE, CNT.FREIGHTCLASSCODE) OR (J.FREIGHTCLASSCODE='C010' AND CNT.FREIGHTCLASSCODE='C008')) 
					WHERE WH.IDENTITYID < '999' 

			) Z ON Z.ITEMCODE = ITM.ITEMCODE AND Z.WAREHOUSEID = WH.IDENTITYID AND Z.EFFECTIVESTARTDATE <= OH.INVOICEDATE

		WHERE OH.RECORDTYPE <> 'P' 
		AND LEFT(OH.TRANSACTIONNUMBER,2) != 'IC' --EXCLUDE INTERCOMPANY ORDERS 
		AND WH.IDENTITYID < '999' 
) X 
*/

--------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
SELECT 
	WH.IDENTITYID AS WAREHOUSEID, 
	ITM.ITEMCODE, 
	ITMP.PROFILECODE AS VARIETY, 
	CNT.FREIGHTCLASSCODE, J.FREIGHTCLASSCODE AS TEST, 
	J.MISCFEECODE, 
	J.LICENSERATE, 
	J.INTERDIVRATE, 
	J.SUBLICENSERATE, 
	J.EFFECTIVESTARTDATE, 
	J.HOLDERID, J.HOLDERNAME

FROM IMITEM ITM (NOLOCK) 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
JOIN (
		--BRAND MANAGEMENT FEE CODES
		SELECT 
			U.MISCFEECODE, 
			U.VARIETY, U.FREIGHTCLASSCODE, 
			SUM(U.LICENSERATE) AS LICENSERATE,
			SUM(U.INTERDIVRATE) AS INTERDIVRATE,
			SUM(U.SUBLICENSERATE) AS SUBLICENSERATE,
			U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
		FROM ( 

				--LICENSE FEES IN GENERAL
				SELECT 
				--'LICENSE GENERAL' AS LEVEL, 
				FH.MISCFEECODE, 
				LEFT(FH.MISCFEECODE,6) AS VARIETY, 
				--SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),4) AS TEST,
				CASE SUBSTRING(FH.MISCFEECODE,CHARINDEX('.', FH.MISCFEECODE),3)
					--WHEN '.1' THEN 'C008'
					WHEN '.1' THEN 'C010'
					WHEN '.2' THEN 'C020'
					WHEN '.3' THEN 'C030'
					WHEN '.4' THEN 'C040'
					WHEN '.5' THEN 'C050'
					WHEN '.7' THEN 'C070'
					WHEN '.10' THEN 'C100'
					WHEN '00' THEN '%'
				ELSE (	SELECT CNT.CONTAINERCODE 
						FROM IMCONTAINER CNT (NOLOCK)
						WHERE CNT.CONTAINERCODE = SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE)+1,0),3)
						) 
				END AS FREIGHTCLASSCODE, 
				FD.RATE AS LICENSERATE, 
				0 AS INTERDIVRATE, 
				0 AS SUBLICENSERATE, 
				FD.EFFECTIVESTARTDATE, 
				VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
				FROM IMFEESHEADER FH (NOLOCK)
				JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'License%'
				--LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
				JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
				WHERE FD.RECORDTYPE = 'R' 
				AND FD.RATE IS NOT NULL 
				--AND FP.PROFILECODE = 'SUBFEES'
				--AND VEND.IDENTITYID IN ('GRE087','LIC003')
				--AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
				--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

				UNION ALL

				--VARIETY LEVEL INTERDIV
				SELECT 
				--'VARIETY INTERDIVISION' AS LEVEL, 
				FH.MISCFEECODE, 
				LEFT(FH.MISCFEECODE,6) AS VARIETY, 
				'%' AS FREIGHTCLASSCODE, 
				0 AS LICENSERATE, 
				FD.RATE AS INTERDIVRATE, 
				0 AS SUBLICENSERATE, 
				FD.EFFECTIVESTARTDATE, 
				VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
				FROM IMFEESHEADER FH (NOLOCK)
				JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
				JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
				JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
				WHERE FD.RECORDTYPE = 'R' 
				AND FD.RATE IS NOT NULL 
				AND FP.PROFILECODE = 'SUBFEES'
				AND VEND.IDENTITYID IN ('GRE087','LIC003')
				AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
				--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

				UNION ALL

				--VARIETY LEVEL SUBLICENSE
				SELECT 
				--'VARIETY SUBLICENSE' AS LEVEL, 
				FH.MISCFEECODE, 
				LEFT(FH.MISCFEECODE,6) AS VARIETY, 
				'%' AS FREIGHTCLASSCODE, 
				0 AS LICENSERATE, 
				0 AS INTERDIVRATE, 
				FD.RATE AS SUBLICENSERATE, 
				FD.EFFECTIVESTARTDATE, 
				VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
				FROM IMFEESHEADER FH (NOLOCK)
				JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
				JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
				JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
				WHERE FD.RECORDTYPE = 'R' 
				AND FD.RATE IS NOT NULL 
				AND FP.PROFILECODE = 'SUBFEES'
				AND VEND.IDENTITYID IN ('GRE087','LIC003')
				AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
				--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

				UNION ALL

				--CLASS LEVEL INTERDIV
				SELECT 
				--'CLASS INTERDIVISION' AS LEVEL, 
				FH.MISCFEECODE, 
				LEFT(FH.MISCFEECODE,6) AS VARIETY, 
				CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
					--WHEN '.1' THEN 'C008'
					WHEN '.1' THEN 'C010'
					WHEN '.2' THEN 'C020'
					WHEN '.3' THEN 'C030'
					WHEN '.4' THEN 'C040'
					WHEN '.5' THEN 'C050'
					WHEN '.7' THEN 'C070'
					WHEN '.10' THEN 'C100'
				ELSE NULL END AS FREIGHTCLASSCODE, 
				0 AS LICENSERATE, 
				FD.RATE AS INTERDIVRATE, 
				0 AS SUBLICENSERATE, 
				FD.EFFECTIVESTARTDATE, 
				VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
				FROM IMFEESHEADER FH (NOLOCK)
				JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
				JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
				JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
				WHERE FD.RECORDTYPE = 'R' 
				AND FD.RATE IS NOT NULL 
				AND FP.PROFILECODE = 'SUBFEES'
				AND VEND.IDENTITYID IN ('GRE087','LIC003')
				AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'
				--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

				UNION ALL

				--CLASS LEVEL SUBLICENSE
				SELECT 
				--'CLASS SUBLICENSE' AS LEVEL, 
				FH.MISCFEECODE, 
				LEFT(FH.MISCFEECODE,6) AS VARIETY, 
				CASE SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3)
					--WHEN '.1' THEN 'C008'
					WHEN '.1' THEN 'C010'
					WHEN '.2' THEN 'C020'
					WHEN '.3' THEN 'C030'
					WHEN '.4' THEN 'C040'
					WHEN '.5' THEN 'C050'
					WHEN '.7' THEN 'C070'
					WHEN '.10' THEN 'C100'
				ELSE NULL END AS FREIGHTCLASSCODE, 
				0 AS LICENSERATE, 
				0 AS INTERDIVRATE, 
				FD.RATE AS SUBLICENSERATE, 
				FD.EFFECTIVESTARTDATE, 
				VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
				FROM IMFEESHEADER FH (NOLOCK)
				JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Sublicense Fee1'
				JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
				JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
				WHERE FD.RECORDTYPE = 'R' 
				AND FD.RATE IS NOT NULL 
				AND FP.PROFILECODE = 'SUBFEES'
				AND VEND.IDENTITYID IN ('GRE087','LIC003')
				AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) != '.89'
				--ORDER BY FD.DESCRIPTION, FH.MISCFEECODE, FD.EFFECTIVESTARTDATE

		) U
		GROUP BY 	U.MISCFEECODE, U.VARIETY, U.FREIGHTCLASSCODE, U.EFFECTIVESTARTDATE, U.HOLDERID, U.HOLDERNAME
--) J ON J.VARIETY = ITMP.PROFILECODE AND (CNT.CONTAINERCODE = J.FREIGHTCLASSCODE OR CNT.FREIGHTCLASSCODE LIKE J.FREIGHTCLASSCODE) 
) J ON J.VARIETY = ITMP.PROFILECODE AND (J.FREIGHTCLASSCODE IN (CNT.CONTAINERCODE, CNT.FREIGHTCLASSCODE) OR (J.FREIGHTCLASSCODE='C010' AND CNT.FREIGHTCLASSCODE='C008')) 
WHERE WH.IDENTITYID < '999' 

*/
