		SELECT * FROM VW_RPT_ROYALTY_EXPENSE (NOLOCK)
		--WHERE ISNULL(LICENSERATE,0) != 0
--SELECT * FROM VW_RPT_ROYALTY_FEE_INCOME (NOLOCK)
WHERE ITEMCODE LIKE '003152.031.%'
ORDER BY ITEMCODE

--research scripts for ROYALTY_FEE_INCOME data

/*
									--VARIETY LEVEL INTERDIV
									SELECT 
									FH.MISCFEECODE, 
									LEFT(FH.MISCFEECODE,6) AS VARIETY, 
									'%' AS FREIGHTCLASSCODE, 
									0 AS LICENSERATE, 
									FD.RATE AS INTERDIVRATE, 
									0 AS SUBLICENSERATE, 
									FD.EFFECTIVESTARTDATE, 
									VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'Interdivision Fee1'
									left JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									--WHERE FD.RECORDTYPE = 'R' 
									--AND FD.RATE IS NOT NULL 
									--AND FP.PROFILECODE = 'SUBFEES'
									--AND VEND.IDENTITYID IN ('GRE087','LIC003')
									--AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) = '.89'
where MISCFEECODE = '003152.89'
*/
/*
		SELECT 
			CO.COMPANYID, CO.NAME AS COMPANYNAME, 
			WH.IDENTITYID AS WAREHOUSEID, WH.NAME AS WAREHOUSENAME, 
			OH.STAGE, OH.RECORDTYPE, 
			OH.TRANSACTIONDATE, OH.SHIPPINGDATE, OH.INVOICEDATE, 
			OH.TRANSACTIONTYPE, 
			OD.USERDEFINEDCODE_1 AS CREDITREASONCODE, 
			OD.USERDEFINEDREFERENCE_2 AS NETWORKTEXT, 
			IIF(OH.TRANSACTIONTYPE = 'I', OD.QUANTITYSHIPPED, 0) AS QTYINVOICED, 
			IIF(OH.TRANSACTIONTYPE IN ('C','J') AND LEFT(OD.USERDEFINEDCODE_1,2) = 'FC', OD.QUANTITYSHIPPED * -1, 0) AS QTYMEMOED, 
			IIF(OD.USERDEFINEDREFERENCE_2 LIKE '%NETWORK%', OD.QUANTITYSHIPPED, 0) AS QTYNETWORK, 
			ITM.USERDEFINEDCODE_16 AS LICPRIMARYHOLDER, 
			(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDERDESC, 
			ITM.ITEMCODE, ITM.REFERENCE_1 AS COMMONNAME, --NULLIF(ITM.USERDEFINEDREFERENCE_1,'') AS PATENT, 
			ITM.USERDEFINEDCODE_2 AS BRAND, 
			OD.R_FEES, 
			ITMP.PROFILECODE AS VARIETY, ITMP.DESCRIPTION VARIETYDESCRIPTION, 
			CNT.PRINTEDCONTAINERCODE, CNT.CONTAINERCODE, CNT.FREIGHTCLASSCODE, 
			FH.MISCFEECODE, 
			FD.RATE AS LICENSERATE, 
			0 AS INTERDIVRATE, 
			0 AS SUBLICENSERATE, 
			FD.EFFECTIVESTARTDATE, 
			VEND.IDENTITYID AS HOLDERID, VEND.NAME AS HOLDERNAME 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN  OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES 
			--DO WE ONLY PAY ROYALTEES AFTER THEY ARE INVOICED? 
			JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.EFFECTIVESTARTDATE <= OH.INVOICEDATE AND FD.DESCRIPTION LIKE 'LICENSE%' 
			JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
		WHERE OH.RECORDTYPE <> 'P' 
		AND LEFT(OH.TRANSACTIONNUMBER,2) != 'IC' --EXCLUDE INTERCOMPANY ORDERS 
		AND WH.IDENTITYID < '999' 
and itm.ITEMCODE = '003150.010.1'
*/
/*
--FeeCodes w/no profile:
SELECT *
FROM IMFEESHEADER FH (NOLOCK)
JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION = 'INTERDIVISION FEE1'
LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
WHERE FP.PROFILECODE IS NULL
AND SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) IN ('.89','.1','.2','.3','.4','.5','.7','.10')
*/
/*
--FeeCodes with different HOLDERIDs:
select 
FH.MISCFEECODE AS FEECODE89, FD.DESCRIPTION AS DESCRIPTION89, VEND.IDENTITYID AS HOLDERID89, 
FH2.MISCFEECODE, FD2.DESCRIPTION, VEND2.IDENTITYID AS HOLDERID
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID --AND FD.DESCRIPTION = 'Interdivision Fee1'
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									LEFT JOIN IMFEESHEADER FH2 (NOLOCK) on FH2.MISCFEECODE = LEFT(FH.MISCFEECODE,6)
									LEFT JOIN IMFEESDETAIL FD2 (NOLOCK) ON FD2.R_FEESHEADER = FH2.ROWID AND FD2.DESCRIPTION = 'License Fee1'
									LEFT JOIN IDMASTER VEND2 (NOLOCK) ON VEND2.ROWID = FD2.R_VENDOR 
where SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) in ('.89','.1','.2','.3','.4','.5','.7','.10')
AND VEND.IDENTITYID IN ('GRE087','LIC003')
--AND FH.MISCFEECODE = '003150.89'
--AND VEND.IDENTITYID != VEND2.IDENTITYID
ORDER BY FH.MISCFEECODE 
*/
/*
--FeeCodes with different EFFECTIVESTARTDATEs:
select 
FH.MISCFEECODE AS FEECODE89, FD.DESCRIPTION AS DESCRIPTION89, VEND.IDENTITYID AS HOLDERID89, FD.EFFECTIVESTARTDATE, 
FH2.MISCFEECODE, FD2.DESCRIPTION, VEND2.IDENTITYID AS HOLDERID, FD2.EFFECTIVESTARTDATE
									FROM IMFEESHEADER FH (NOLOCK)
									JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID --AND FD.DESCRIPTION = 'Interdivision Fee1'
									JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
									LEFT JOIN IMFEESHEADER FH2 (NOLOCK) on FH2.MISCFEECODE = LEFT(FH.MISCFEECODE,6)
									LEFT JOIN IMFEESDETAIL FD2 (NOLOCK) ON FD2.R_FEESHEADER = FH2.ROWID AND FD2.DESCRIPTION = 'License Fee1'
									LEFT JOIN IDMASTER VEND2 (NOLOCK) ON VEND2.ROWID = FD2.R_VENDOR 
where SUBSTRING(FH.MISCFEECODE,NULLIF(CHARINDEX('.', FH.MISCFEECODE),0),3) in ('.89','.1','.2','.3','.4','.5','.7','.10')
AND VEND.IDENTITYID IN ('GRE087','LIC003')
--AND FH.MISCFEECODE = '003150.89'
AND FD.EFFECTIVESTARTDATE != FD2.EFFECTIVESTARTDATE
ORDER BY FH.MISCFEECODE 
*/
/*
--fix feecodes with no profile:
SELECT FH.MISCFEECODE, FH.R_PROFILE, FP.PROFILECODE
FROM IMFEESHEADER FH (NOLOCK)
LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
WHERE FH.MISCFEECODE IN (
'007379.89', '006701.89', '007702.89', '005818.89', '003150.89', 
'008789.89', '008556.89', '005414.89', '008511.89', 
'008351.89', '003152.89', '005627.89', '007860.89') 

BEGIN TRAN
UPDATE IMFEESHEADER 
SET R_PROFILE = '504B94F2-652B-4AF0-BE47-EDFA4C06B945'
WHERE R_PROFILE IS NULL
AND MISCFEECODE IN (
'007379.89', '006701.89', '007702.89', '005818.89', --'003150.89', 
'008789.89', '008556.89', '005414.89', '008511.89', 
'008351.89', '003152.89', '005627.89', '007860.89')
SELECT FH.MISCFEECODE, FH.R_PROFILE, FP.PROFILECODE
FROM IMFEESHEADER FH (NOLOCK)
LEFT JOIN /*IMFEESDP*/IDDISCOUNTDP FP (NOLOCK) ON FP.ROWID = FH.R_PROFILE --R_PROFILE IN THE WRONG TABLE FOR NOW!!!
WHERE FH.MISCFEECODE IN (
'007379.89', '006701.89', '007702.89', '005818.89', '003150.89', 
'008789.89', '008556.89', '005414.89', '008511.89', 
'008351.89', '003152.89', '005627.89', '007860.89') 
--COMMIT
ROLLBACK TRAN
*/
