--Subsequent Receipts
--This query shows Cash Receipts for a date range that have been applied to invoices with another date range. Asked for by the Auditors.
SELECT
CUST.IDENTITYID AS CUSTOMERID, 
CUST.NAME AS CUSTOMERNAME, 
RP.CHECKNUMBER, 
RP.AMOUNT AS CHECKAMOUNT, 
RP.PAYMENTDATE, 
AH.TRANSACTIONNUMBER, 
AH.TRANSACTIONDATE, 
RD.AMOUNTAPPLIED 
FROM ARCASHRECEIPTSPAYMENTS RP (NOLOCK) 
JOIN ARCASHRECEIPTSHEADER RH (NOLOCK) ON RH.ROWID = RP.R_SOURCEID 
JOIN ARCASHRECEIPTSDETAIL RD (NOLOCK) ON RD.R_CASHRECEIPTSHEADER = RH.ROWID 
JOIN AROPENITEMHEADER AH (NOLOCK) ON AH.ROWID = RD.R_AROPENITEMHEADER 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = RH.R_CUSTOMER 
WHERE RP.PAYMENTDATE BETWEEN '09/01/2021' AND '11/30/2021'
AND AH.TRANSACTIONDATE < '08/31/2021'
ORDER BY 
CUST.IDENTITYID, 
RP.CHECKNUMBER, 
AH.TRANSACTIONNUMBER 
