------------------------------
-- FUNCTION: FN_ARTVERSION
-- REGARDLESS OF LENGTH
------------------------------
-- RETURNS THE ARTVERSION OF THE CUSTOMER ROWID AND DOCTYPE PASSED TO IT
------------------------------
-- DON TAYLOR @ 11/30/2020
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_ARTVERSION]
(	@CUSTROWID UNIQUEIDENTIFIER,
	@DOCTYPE VARCHAR(3)
)	RETURNS VARCHAR(30)
AS

BEGIN
	DECLARE @RESULT VARCHAR(30)
	DECLARE @DOCPOSITION INT
	DECLARE @DOCLENGTH INT
	--IF @CUSTROWID IS NULL 
	--	RETURN NULL
	IF @DOCTYPE IS NULL 
		SET @DOCTYPE = 'INV'
	--FIND STARTING POSITION BASED UPON @DOCTYPE
	SET @DOCPOSITION = (
						SELECT	CHARINDEX(@DOCTYPE, ICUST.OMDEFAULTREPORTFORMATS)
						FROM IDCUSTOMER ICUST (NOLOCK)
						WHERE ICUST.R_IDENTITY = @CUSTROWID
						)
	--IF ISNULL(@DOCPOSITION,0) = 0
	--	RETURN '{Not Defined}'--NULL
	--FIND TEXT LENGTH BASED UPON NEXT OCCURENCE OF COLON {:} CHARACTER IN STRING.
	SET @DOCLENGTH =
					(
					SELECT	CHARINDEX(':', SUBSTRING(ICUST.OMDEFAULTREPORTFORMATS, @DOCPOSITION, 30)+':')-1
					FROM IDCUSTOMER ICUST (NOLOCK)
					WHERE ICUST.R_IDENTITY = @CUSTROWID
					)
	--IF ISNULL(@DOCLENGTH,0) = 0
	--	RETURN '{Not Defined2}'--NULL
	--THIS ALLOWS THE REPORTNAMES TO BE VARIABLE LENGTH AS LONG AS THEY START WITH @DOCTYPE PREFIX
	IF @DOCTYPE = 'INV'
		SET @RESULT = 
			(
			SELECT	SUBSTRING(ICUST.OMDEFAULTREPORTFORMATS, @DOCPOSITION, @DOCLENGTH)
			FROM IDCUSTOMER ICUST (NOLOCK)
			WHERE ICUST.R_IDENTITY = @CUSTROWID
			AND	ICUST.OMINVOICEREPORTTYPE = 'C'
			) 
	IF @DOCTYPE = 'DEL'
		SET @RESULT = 
			(
			SELECT	SUBSTRING(ICUST.OMDEFAULTREPORTFORMATS, @DOCPOSITION, @DOCLENGTH)
			FROM IDCUSTOMER ICUST (NOLOCK)
			WHERE ICUST.R_IDENTITY = @CUSTROWID
			AND	ICUST.OMPICKINGSLIPREPORTTYPE = 'C'
			) 
	IF @DOCTYPE = 'ACK'
		SET @RESULT = 
			(
			SELECT	SUBSTRING(ICUST.OMDEFAULTREPORTFORMATS, @DOCPOSITION, @DOCLENGTH)
			FROM IDCUSTOMER ICUST (NOLOCK)
			WHERE ICUST.R_IDENTITY = @CUSTROWID
			AND	ICUST.OMORDERACKNREPORTTYPE = 'C'
			) 
	RETURN TRIM(ISNULL(@RESULT,'{Not Defined}'))
END
