------------------------------ 
-- FUNCTION: FN_DATE2YEAR 
------------------------------ 
-- RETURNS THE REPORT YEAR FROM THE DATE PARAMETER PASSED TO IT 
-- NULL DATE ASSUMES CURRENT DATE USING GETDATE() 
------------------------------ 
-- DON TAYLOR @ 05/08/2020 
------------------------------ 
-- EMBEDDED FN_YEAR2DATE() LOGIC TO REDUCE FUNCTION DAISY CHAINS @10/14/21-DT 
------------------------------ 
CREATE OR ALTER FUNCTION [DBO].[FN_DATE2YEAR] 
( @INDATE DATETIME 
) RETURNS INTEGER 
AS 
BEGIN 
	-- LOCAL PARAMETERS -- 
	DECLARE @RESULT		INTEGER 
	DECLARE @DATE		DATETIME 
	DECLARE @STARTDATE	DATETIME 
	IF @INDATE IS NULL  
		SET @INDATE = GETDATE() 

	BEGIN 
		/* EMBEDDED CODE SECTION */ 
		--GET NEXT YEAR'S STARTDATE BASED UPON THE YEAR OF THE PASSED DATE FIELD: 
		--FN_YEAR2DATE()+1 CODE: WE ARE PASSING NEXT YEAR VALUE, BE AWARE: 
		SET @DATE = '08/01/' + TRIM(STR(YEAR(@INDATE)))				--AUG 1ST DATE OF NEXT YEAR 
		SET @STARTDATE = DATEADD(D, 1-(DATEPART(DW, @DATE)), @DATE)	--START OF WEEK 1 

		-- CHOOSE CURRENT YEAR'S STARTDATE IF THIS DATE IS IN THE FUTURE: 
		IF @STARTDATE > @INDATE 
			BEGIN 
				--GET CURRENT YEAR'S STARTDATE BASED UPON THE YEAR OF THE PASSED DATE FIELD: 
				--FN_YEAR2DATE() CODE: 
				SET @DATE = '08/01/' + TRIM(STR(YEAR(@INDATE)-1))			--AUG 1ST DATE OF CURRENT YEAR 
				SET @STARTDATE = DATEADD(D, 1-(DATEPART(DW, @DATE)), @DATE)	--START OF WEEK 1 

			END 
		--ADD ONE YEAR TO STARTDATE TO GET THE YEAR OF THE ENDDATE: 
		SET @RESULT = YEAR(@STARTDATE)+1 
	END 
	RETURN @RESULT 
END 
----OLDCODE----
--		--GET NEXT YEAR'S STARTDATE BASED UPON THE YEAR OF THE PASSED DATE FIELD:
--		SET @STARTDATE = DBO.FN_YEAR2DATE(YEAR(@INDATE)+1)

--		-- CHOOSE CURRENT YEAR'S STARTDATE IF THIS DATE IS IN THE FUTURE:
--		SET @RESULT = YEAR(IIF(@STARTDATE>@INDATE,DBO.FN_YEAR2DATE(YEAR(@INDATE)),@STARTDATE))
--	END
--	RETURN @RESULT+1	--ADD ONE YEAR TO STARTDATE TO GET THE YEAR OF THE ENDDATE
--END
