------------------------------
-- FUNCTION: FN_DATE2YYYYMMDD
------------------------------
-- RETURNS THE FORMATTED DATE(YYYYMMDD) OF THE DATE PARAMETER PASSED TO IT
-- NULL DATE ASSUMES CURRENT DATE USING GETDATE()
------------------------------
-- DON TAYLOR @ 10/27/2022
------------------------------
CREATE OR ALTER   FUNCTION [dbo].[FN_DATE2YYYYMMDD]
( @INDATE DATETIME
) RETURNS CHAR(8)
AS
BEGIN
	DECLARE @RESULT VARCHAR(8)
	IF @INDATE IS NULL 
		SET @INDATE = GETDATE()

	SET @RESULT = 
				(
					RIGHT(STR(DATEPART(YYYY, @INDATE)),4) +
					RIGHT('0'+TRIM(STR(DATEPART(MONTH, @INDATE))),2) +
					RIGHT('0'+TRIM(STR(DATEPART(DAY, @INDATE))),2)
				)

	RETURN @RESULT
END
