------------------------------
-- FUNCTION: FN_DEMAND
-- 
-- FN_DEMAND(ITEMROWID,LOTROWID)
------------------------------
-- RETURNS THE DEMAND QTY FOR THE ITEMROWID,LOTROWID PARAMETERS PASSED TO IT
------------------------------
-- DON TAYLOR @ 05/20/2020
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_DEMAND]
(	@ITMROWID UNIQUEIDENTIFIER,
	@LOTROWID UNIQUEIDENTIFIER
) RETURNS BIGINT 
AS
BEGIN
	DECLARE @RESULT BIGINT 

	IF @ITMROWID IS NULL 
		RETURN NULL

	BEGIN
		IF @LOTROWID IS NOT NULL 
			BEGIN 
				SET @RESULT = 
				( 
					SELECT	OUT_ORDERED + OUT_SHIPPED + OUT_BACKORDER 
					FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
					WHERE	VLOT.R_ITEM = @ITMROWID 
					AND		VLOT.ROWID = @LOTROWID
				)
			END
	END
	RETURN ISNULL(@RESULT,0) 
END
