------------------------------
-- FUNCTION: FN_EDI_PO_CHANGES
------------------------------
-- FN_EDI_PO_CHANGES(TRANSACTIONNUMBER,[LINENUMBER/{NULL}=ALL],[A/D/O/P/Q/S/{NULL}=ALL])
------------------------------
-- RETURNS THE NUMBER OF POCHANGES FOR A TRANSACTIONNUMBER PASSED TO IT
-- OPTIONAL LINENUMBER OR NULL RETURNS ALL LINES
-- CHANGETYPES ARE:
--		<A>:ADD
--		<D>:DELETE
--		<O>:ORDER (BOTH PRICE AND QUANITY)
--		<P>:PRICE
--		<Q>:QUANTITY
--		<S>:SKU
--		{NULL} = ALL CHANGETYPES
--
-- NOTE: THIS FUNCTION FIRST ATTEMPTS TO FIND CHANGES TO POS WITH 'E' RECORDTYPES (CHANGE POS)
--		IF RESULT IS {NULL} [RECORDS DON'T EXIST YET] IT WILL RETURN CHANGES TO 'I' RECORDTYPES
------------------------------
-- DON TAYLOR @ 01/13/2023
------------------------------
CREATE OR ALTER FUNCTION [dbo].[FN_EDI_PO_CHANGES] 
(	@TRANSACTIONNUMBER CHAR(20), 
	@LINENUMBER INT, 
	@CHANGETYPE CHAR(10) 
) RETURNS INTEGER 
AS 
BEGIN 
	DECLARE @RESULT INTEGER 
	IF @LINENUMBER = 0 
		SET @LINENUMBER = NULL 
	IF @LINENUMBER IS NULL 
		BEGIN 	--SUM ALL LINES OF ORDER
			IF @CHANGETYPE = 'A'--ADD 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_ADD) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_ADD) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'D'--DELETE 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_DEL) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_DEL) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'O'--ORDER 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_PRICE+CHG_QTY) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_PRICE+CHG_QTY) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'P'--PRICE 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_PRICE) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_PRICE) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'Q'--QUANTITY 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_QTY) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_QTY) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'S'--SKU 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_SKU) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_SKU) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE IS NULL 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_ADD+CHG_LINE_DEL+CHG_PRICE+CHG_QTY+CHG_SKU) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						--AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_ADD+CHG_LINE_DEL+CHG_PRICE+CHG_QTY+CHG_SKU) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							--AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
		END 
	ELSE 
		BEGIN 	--SUM ONLY SELECTED LINE OF ORDER
			IF @CHANGETYPE = 'A'--ADD 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_ADD) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_ADD) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'D'--DELETE 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_DEL) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_DEL) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'O'--ORDER 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_PRICE+CHG_QTY) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_PRICE+CHG_QTY) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'P'--PRICE 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_PRICE) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_PRICE) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'Q'--QUANTITY 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_QTY) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_QTY) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE = 'S'--SKU 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_SKU) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_SKU) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
			IF @CHANGETYPE IS NULL 
				BEGIN
					SET @RESULT = 
					(	SELECT SUM(CHG_LINE_ADD+CHG_LINE_DEL+CHG_PRICE+CHG_QTY+CHG_SKU) 
						FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
						WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
						AND LINENUMBER = @LINENUMBER 
						AND PO_RECORDTYPE = 'E'
					) 
					IF @RESULT IS NULL
						SET @RESULT = 
						(	SELECT SUM(CHG_LINE_ADD+CHG_LINE_DEL+CHG_PRICE+CHG_QTY+CHG_SKU) 
							FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
							WHERE TRANSACTIONNUMBER = @TRANSACTIONNUMBER 
							AND LINENUMBER = @LINENUMBER 
							AND PO_RECORDTYPE = 'I'
						) 
				END
		END 
	RETURN ISNULL(@RESULT,0) 
END 
GO 


