------------------------------
-- FUNCTION: FN_EDI_CODE_DESCRIPTION
--
-- FN_EDI_CODE_DESCRIPTION(SEGMENT, CODEVALUE)
------------------------------
-- RETURNS THE DESCRIPTION OF THE SEGMENT AND CODEVALUE PASSED TO IT.
------------------------------
-- DON TAYLOR @ 2/21/2023
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_EDI_CODE_DESCRIPTION]
(	@SEGMENT	VARCHAR(5),	--	= 'ST01',
	@CODEVALUE	VARCHAR(6)	--	= '437'
) RETURNS VARCHAR(200)
AS
BEGIN
	DECLARE @RESULT VARCHAR(200)
	SET @RESULT = 
	( --GET DESCRIPTION OF CODEVALUE
		SELECT TOP 1
		TRIM(SUBSTRING(ELEC.DESCRIPTION,1,200)) 
		FROM EDSEGMENTDETAIL SEGD (NOLOCK) 
		JOIN EDELEMENTCODES ELEC (NOLOCK) ON ELEC.VERSIONID = SEGD.VERSIONID AND ELEC.DATAELEMENTNUM = SEGD.DATAELEMENTNUM
		WHERE TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE) LIKE @SEGMENT
		AND ELEC.CODEVALUE LIKE @CODEVALUE
	)
	RETURN @RESULT
END
