------------------------------
-- FUNCTION: FN_GETCONTACT
------------------------------
-- RETURNS THE CONTACT ROWID OF THE IDMASTER ROWID, IDTYPE AND IDPREFIX PASSED TO IT.
------------------------------
-- DON TAYLOR @ 08/16/2021
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_GETCONTACT]
(	@IDENTITYROWID UNIQUEIDENTIFIER,
	@IDTYPE VARCHAR(2),
	@IDPREFIX VARCHAR(3)
)	RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @RESULT  UNIQUEIDENTIFIER

	SET @RESULT = 
		(
--		SELECT TOP 1 CONT.ROWID	-->TEMPORARY PATCH FOR WHEN DUPLICATE CONTACTS EXIST
		SELECT CONT.ROWID
		FROM IDMASTER CONT (NOLOCK)
		JOIN IDRELATIONSHIPLINKS LCONT (NOLOCK) ON LCONT.R_IDMASTER = @IDENTITYROWID AND LCONT.IDMASTERTYPE = @IDTYPE AND LCONT.IDMEMBERTYPE = '22'
		WHERE CONT.ROWID = LCONT.R_IDMEMBER AND LEFT(CONT.IDENTITYID,2) = @IDPREFIX
		)
	RETURN @RESULT
END
/*
--TEST SCRIPT TO FIND OFFENDING C4 RECORD WITH A DUPLICATE CONTACT:
	--EXAMPLE: DBO.FN_GETCONTACT(CUST.ROWID,'01','C4')
SELECT * FROM (
	SELECT *, 
		(	SELECT COUNT(CONT.ROWID)
			FROM IDMASTER CONT (NOLOCK)
			JOIN IDRELATIONSHIPLINKS LCONT (NOLOCK) ON LCONT.R_IDMASTER = CUST.ROWID AND LCONT.IDMASTERTYPE = '01' AND LCONT.IDMEMBERTYPE = '22'
			WHERE CONT.ROWID = LCONT.R_IDMEMBER AND LEFT(CONT.IDENTITYID,2) = 'C4'
		) AS CNT
	FROM IDMASTER CUST (NOLOCK)
) X WHERE X.CNT > 1
*/
