------------------------------
-- FUNCTION: FN_LISTPRICE
------------------------------
-- RETURNS THE LISTPRICE OF THE ITEM BASED ON THE DATE AND QUANTITY BREAK PARAMETERS PASSED TO IT
-- NULL DATE ASSUMES CURRENT DATE USING GETDATE()
------------------------------
-- QUANTITY BREAK HAS BEEN DEPRECATED FROM THIS FUNCTION
------------------------------
-- DON TAYLOR @ 05/12/2020
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_LISTPRICE]
(	@ITMROWID UNIQUEIDENTIFIER,
	@INDATE DATETIME,
	@ITMQTY DECIMAL(29,10) = NULL
)	RETURNS DECIMAL(29,10)
AS
BEGIN
	DECLARE @RESULT  DECIMAL(29,10)
	IF @ITMROWID IS NULL 
		RETURN NULL
	IF @INDATE IS NULL 
		SET @INDATE = GETDATE()

	SET @RESULT = 
		(
		SELECT ROUND(ISNULL(
			(
			SELECT TOP 1 SUB.PRICELEVEL_A FROM IMPRICECODESSUBDETAIL SUB (NOLOCK)
			WHERE SUB.R_PRICECODEDETAIL = 
				(
				SELECT TOP 1 DTL.ROWID FROM IMPRICECODESDETAIL DTL (NOLOCK)
				WHERE DTL.R_PRICECODEHEADER = HDR.ROWID
				AND DTL.EFFECTIVEDATE <= @INDATE
				ORDER BY DTL.EFFECTIVEDATE DESC
				) 
			--ORDER BY ISNULL(@ITMQTY,0) DESC
			) 
--		, ITM.PRICELEVELA),4)
		, NULL),4)		--JOANNE ARE CONVINCED THAT ITM.PRICELEVELA IS NOT BEING USED. SO RETURN NULL HERE NOW. --01/16/23 DT
		FROM IMITEM ITM (NOLOCK)
		JOIN IMPRICECODESHEADER HDR (NOLOCK) ON HDR.ROWID = ITM.R_PRICETABLE
		WHERE ITM.ROWID = @ITMROWID
		)
	RETURN @RESULT
END
