------------------------------
-- FUNCTION: FN_MASTERCUSTOMER
------------------------------
-- RETURNS THE MASTERCUSTOMERROWID OF A CUSTOMERROWID PASSED TO IT
--
-- INCLUSIVE FLAG WILL COUNT THE MASTERCUSTOMER ITSELF AS 
-- INCLUDED IN THE GROUP OF ITS CHILDREN, THIS IS USED IN THE 
-- STATEMENT REPORT TO SUM THE BALANCE AS ONE TOTAL.
------------------------------
-- DON TAYLOR @ 07/15/2021
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_MASTERCUSTOMER]
(	@CUSTROWID UNIQUEIDENTIFIER,
	@INCLUSIVE VARCHAR
)	RETURNS UNIQUEIDENTIFIER--CHAR(12)
AS
BEGIN
	DECLARE @RESULT UNIQUEIDENTIFIER--CHAR(12)
	IF @CUSTROWID IS NULL 
		RETURN NULL

	IF @INCLUSIVE IS NULL
		SET @RESULT =	(--FIND MEMBERID, RETURN MASTERROWID
							SELECT MCUST.ROWID--TRIM(MCUST.IDENTITYID )
							FROM IDRELATIONSHIPLINKS MCLINK (NOLOCK) 
							JOIN IDMASTER MCUST (NOLOCK) ON MCUST.ROWID = MCLINK.R_IDMASTER
							WHERE MCLINK.R_IDMEMBER = @CUSTROWID
							AND MCLINK.IDMASTERTYPE = '01' 
							AND MCLINK.IDMEMBERTYPE = '01'
						)
	ELSE
		SET @RESULT =	(--FIND BOTH MASTER AND MEMBER IDS, RETURN MASTERROWID
							SELECT TOP 1 MCUST.ROWID--TRIM(MCUST.IDENTITYID )
							FROM IDRELATIONSHIPLINKS MCLINK (NOLOCK) 
							JOIN IDMASTER MCUST (NOLOCK) ON MCUST.ROWID = MCLINK.R_IDMASTER
							WHERE @CUSTROWID IN (MCLINK.R_IDMEMBER, MCLINK.R_IDMASTER)
							AND MCLINK.IDMASTERTYPE = '01' 
							AND MCLINK.IDMEMBERTYPE = '01'
						)
	RETURN @RESULT
END
