------------------------------
-- FUNCTION: FN_MCATTRIBUTES
------------------------------
-- RETURNS THE ATTRIBUTE VALUE BASED ON THE ITEM ROWID AND THE ATTRIBUTENAME PASSED TO IT
-- USES ALL OMREVIEWATTRIBUTES AND RETURNS VALUES FOUND IN THE MASTER CODE ATTRIBUTES:

--	NAME					DESCRIPTION
--	=====================	==============================================================
--	BypassLoc				Attribute: Do not pull from this location
--	DesigCust				IMTransAttribute: Customer Designator  
--	DesigItem				IMTransAttribute: Item Designator  
--	DesigLoc				IMTransAttribute: Location Desginator
--	Future Eval				Attribute: Future Evaluation date for this loc master code
--	Hold/Stop				Item/LotAttribute: Hold/Stop
--	HoldReasonNote			Item/LotAttribute: Hold Reason Note
--	Internal Spec			ItemAttribute:  Std-Spec,  GNC's internal standard measurement
--	InternalInventoryNote	Item/Lot Attribute: Internal Inventory Note
--	LastPltgDate			IMTransAttribute:  Last Planting Date
--	LastProdSchLine#		IMTransAttribute: Last Production Schedule LIne #
--	LastTransText			IMTransAttribute: LastTransaction Text
--	Location Note			Attribute:  Describes items at this loc master code
--	LocationPTN1			Attribute:  Location Specific PTN1
--	LocationPTN2			Attribute: Location Specific PTN2
--	LocHold					Attribute:  LocHold
--	LocNoteDate				Attribute:  Location Note Update Date
--	LrgPtrQty				IMTransAttribute: Large quantity threshold for PTR 
--	Pick Note				Cust/ItemAttribute: Pick Note for pullers per order
--	Priority				Attribute:  Priority 
--	PriSetBy				Attribute:  Priority set by
--	PriUpdate				Attribute:  Priority Update Date
--	PullTagNote1			Item/LotAttributePull Tag Note 1
--	PullTagNote2			Item/LotAttributePull Tag Note 2
--	QA Code					CustomerAttribute:  Quality Level 
--	Quality					ItemAttribute: Item Quality Code
--	Reverse Common			PC: Reverse Common Name
--	SalesNote				Item/Lot Attribute:Sales Note
--	Source					IMtransAttribute: Source
--	Special Puller			Item/LotAttribute: Puller Experience
--	Suspend					Item/LotAttribute: Pull Tag Supended 
--	SuspendTO				Item/LotAttribute: Pull Tag SupendTO 
--	TBD						Attribute: Minimum inventory usage percent for PTR exception
--	Trip					PC: Trip

------------------------------
-- DON TAYLOR @ 03/03/2021
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_MCATTRIBUTES]
(	@MCROWID UNIQUEIDENTIFIER,
	@ATTRIBUTENAME VARCHAR(20)
)	RETURNS VARCHAR(200)	--was using VARCHARMAX but that was overkill per JoAnne 3/30/23 - DT 
AS
BEGIN
	DECLARE @RESULT  VARCHAR(200)	--was using VARCHARMAX but that was overkill per JoAnne 3/30/23 - DT 
	IF @MCROWID IS NULL 
		RETURN NULL
	--DECLARE @QUANTITY DECIMAL

	----ADDED SPECIAL ATTRIBUTE 'AVAILABLE', USED TO CALCULATE ONHAND
	----NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	--IF @ATTRIBUTENAME = 'AVAILABLE'
	--	BEGIN
	--		SET @QUANTITY =
	--		ISNULL((SELECT MC.PRODUCTIONQUANTITY FROM OMREVIEWMASTERCODES MC (NOLOCK) WHERE MC.ROWID = @MCROWID),0)
	--		RETURN TRIM(STR(@QUANTITY,10,2))
	--	END

	----ADDED SPECIAL ATTRIBUTE 'IN SHIPPING', USED TO RETURN QTYSHIPPED @ MASTERCODE LEVEL
	--IF @ATTRIBUTENAME = 'IN SHIPPING'
	--	BEGIN
	--		SET @QUANTITY =
	--		ISNULL((SELECT SUM(COMMITTEDQUANTITY) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_MASTERCODE = @MCROWID),0)
	--		RETURN TRIM(STR(@QUANTITY,10,2))
	--	END

	----ADDED SPECIAL ATTRIBUTE 'PTR REVIEWED', USED TO CALCULATE ONHAND
	----NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	--IF @ATTRIBUTENAME = 'PTR REVIEWED'
	--	BEGIN
	--		SET @QUANTITY =
	--		(	ISNULL((SELECT SUM(COMMITTEDQUANTITY) 
	--					FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
	--					JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
	--					JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
	--					WHERE IA.R_MASTERCODE = @MCROWID AND OH.RECORDTYPE <> 'Z'
	--					),0)	
	--		)
	--		RETURN TRIM(STR(@QUANTITY,10,2))
	--	END

	----ADDED SPECIAL ATTRIBUTE 'ONHAND'
	----NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	--IF @ATTRIBUTENAME = 'ONHAND'
	--	BEGIN
	--	SET @QUANTITY =
	--		(
	--		--AVAILABLE: +
	--			ISNULL((SELECT MC.PRODUCTIONQUANTITY FROM OMREVIEWMASTERCODES MC (NOLOCK) WHERE MC.ROWID = @MCROWID),0) + 
	--		--PTR REVIEWED:
	--			(	ISNULL((SELECT SUM(COMMITTEDQUANTITY) 
	--						FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
	--						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
	--						JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
	--						WHERE IA.R_MASTERCODE = @MCROWID AND OH.RECORDTYPE <> 'Z'
	--						),0)	
	--			)
	--		)
	--	RETURN TRIM(STR(@QUANTITY,10,2))
	--	END
	SET @RESULT = 
		(
		SELECT TOP 1 MCA.VALUE
		FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
		JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE
		WHERE MCA.R_MASTERCODE = @MCROWID AND A.NAME = @ATTRIBUTENAME)
	--RETURN ISNULL(@RESULT,'')
	RETURN TRIM(@RESULT)
END

/* CODE TO TEST WHAT I AM DOING (VERY LONG RUNNING QUERY)
SELECT
ITM.ITEMCODE,
LOT.LOTCODE, LOC.LOCATIONCODE,
A.NAME,
MCA.VALUE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'BYPASSLOC') AS BYPASSLOC,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGCUST') AS DESIGCUST,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGITEM') AS DESIGITEM,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGLOC') AS DESIGLOC,
DBO.FN_MCATTRIBUTES(MC.ROWID,'FUTURE EVAL') AS FUTURE_EVAL,
DBO.FN_MCATTRIBUTES(MC.ROWID,'HOLD/STOP') AS HOLD_STOP,
DBO.FN_MCATTRIBUTES(MC.ROWID,'HOLDREASONNOTE') AS HOLDREASONNOTE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'INTERNAL SPEC') AS INTERNAL_SPEC,
DBO.FN_MCATTRIBUTES(MC.ROWID,'INTERNALINVENTORYNOTE') AS INTERNALINVENTORYNOTE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LASTPLTGDATE') AS LASTPLTGDATE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LASTPRODSCHLINE#') AS LASTPRODSCHLINENUMBER,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LASTTRANSTEXT') AS LASTTRANSTEXT,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCATION NOTE') AS LOCATION_NOTE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCATIONPTN1') AS LOCATIONPTN1,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCATIONPTN2') AS LOCATIONPTN2,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCHOLD') AS LOCHOLD,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCNOTEDATE') AS LOCNOTEDATE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LRGPTRQTY') AS LRGPTRQTY,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PICK NOTE') AS PICK_NOTE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PRIORITY') AS PRIORITY,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PRISETBY') AS PRISETBY,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PRIUPDATE') AS PRIUPDATE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PULLTAGNOTE1') AS PULLTAGNOTE1,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PULLTAGNOTE2') AS PULLTAGNOTE2,
DBO.FN_MCATTRIBUTES(MC.ROWID,'QA CODE') AS QA_CODE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'QUALITY') AS QUALITY,
DBO.FN_MCATTRIBUTES(MC.ROWID,'REVERSE COMMON') AS REVERSE_COMMON,
DBO.FN_MCATTRIBUTES(MC.ROWID,'SALESNOTE') AS SALESNOTE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'SPECIAL PULLER') AS SPECIAL_PULLER,
DBO.FN_MCATTRIBUTES(MC.ROWID,'SUSPEND') AS SUSPEND,
DBO.FN_MCATTRIBUTES(MC.ROWID,'SUSPENDTO') AS SUSPENDTO,
DBO.FN_MCATTRIBUTES(MC.ROWID,'TBD') AS TBD,
DBO.FN_MCATTRIBUTES(MC.ROWID,'TRIP') AS TRIP

FROM OMREVIEWMASTERCODES MC
JOIN IMITEM ITM ON ITM.ROWID = MC.R_ITEM
JOIN IMLOT LOT ON LOT.ROWID = MC.R_LOT
JOIN IMLOCATION LOC ON LOC.ROWID = MC.R_LOCATION
LEFT JOIN OMREVIEWMASTERCODEATTRIBUTES MCA ON MCA.R_MASTERCODE = MC.ROWID
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE

ORDER BY ITM.ITEMCODE, A.NAME
*/