------------------------------
-- FUNCTION: FN_MCATTRIBUTES_IA
------------------------------
--
--THIS IS USED IN THE FOLLOWING REPORTVIEWS:
--	VW_NEGATIVELOCATIONVIEW (ARGOS VIEW)
--	VW_RPT_AVAILABILITY_BY_LOCATION
--	VW_RPT_AVAILABILITY_BY_LOCATION_STATIC
--	VW_RPT_DRIVE_AROUND_MC
--	VW_RPT_GROWER_HOLDSTOP
--	VW_RPT_INVENTORY_BY_ITEM

-- RETURNS THE ATTRIBUTE VALUE BASED ON THE MASTERCODE ROWID AND THE ATTRIBUTENAME PASSED TO IT
-- ** THESE ARE SPECIAL INVENTORYASSIGNMENT ATTRIBUTES THAT ARE DIFFERENT FROM ALL THE REST**
-- RETURNS A NUMBER
------------------------------
-- DON TAYLOR @ 04/30/2022
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_MCATTRIBUTES_IA]
(	@MCROWID UNIQUEIDENTIFIER,
	@ATTRIBUTENAME VARCHAR(20)
)	RETURNS DECIMAL
AS
BEGIN
--	DECLARE @QUANTITY DECIMAL
--	DECLARE @RECTYPE VARCHAR(1)
	DECLARE @RESULT  DECIMAL
	IF @MCROWID IS NULL 
		RETURN NULL

	--ADDED SPECIAL ATTRIBUTE 'AVAILABLE', USED TO CALCULATE ONHAND
	--NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	IF @ATTRIBUTENAME = 'AVAILABLE'
		BEGIN
			SET @RESULT =
			ISNULL((SELECT MC.PRODUCTIONQUANTITY FROM OMREVIEWMASTERCODES MC (NOLOCK) WHERE MC.ROWID = @MCROWID),0)
			--RETURN TRIM(STR(@QUANTITY,10,2))
			RETURN @RESULT
		END

	--ADDED SPECIAL ATTRIBUTE 'IN SHIPPING', USED TO RETURN QTYSHIPPED @ MASTERCODE LEVEL
	IF @ATTRIBUTENAME = 'IN SHIPPING'
		BEGIN
			SET @RESULT =
			ISNULL((SELECT SUM(COMMITTEDQUANTITY) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_MASTERCODE = @MCROWID),0)
			--RETURN TRIM(STR(@QUANTITY,10,2))
			RETURN @RESULT
		END

	--ADDED SPECIAL ATTRIBUTE 'PTR REVIEWED', USED TO CALCULATE ONHAND
	--NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	IF @ATTRIBUTENAME = 'PTR REVIEWED'
		BEGIN
			SET @RESULT =
			(	ISNULL((SELECT SUM(COMMITTEDQUANTITY) 
						FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
						JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
						WHERE IA.R_MASTERCODE = @MCROWID AND OH.RECORDTYPE <> 'Z'
						),0)	
			)
			--RETURN TRIM(STR(@QUANTITY,10,2))
			RETURN @RESULT
		END

	--ADDED SPECIAL ATTRIBUTE 'ONHAND'
	--NOTE: ONHAND = AVAILABLE + PTR REVIEWED
	IF @ATTRIBUTENAME = 'ONHAND'
		BEGIN
		SET @RESULT =
			(
			--AVAILABLE: +
				ISNULL((SELECT MC.PRODUCTIONQUANTITY FROM OMREVIEWMASTERCODES MC (NOLOCK) WHERE MC.ROWID = @MCROWID),0) + 
			--PTR REVIEWED:
				(	ISNULL((SELECT SUM(COMMITTEDQUANTITY) 
							FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
							JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
							WHERE IA.R_MASTERCODE = @MCROWID AND OH.RECORDTYPE <> 'Z'
							),0)	
				)
			)
			--RETURN TRIM(STR(@QUANTITY,10,2))
			RETURN @RESULT
		END
	--SET @RESULT = 
	--	(
	--	SELECT TOP 1 MCA.VALUE
	--	FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
	--	JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE
	--	WHERE MCA.R_MASTERCODE = @MCROWID AND A.NAME = @ATTRIBUTENAME)
	----RETURN ISNULL(@RESULT,'')
	--RETURN TRIM(@RESULT)

	--NOTHING TO DO
	RETURN @RESULT
END
