------------------------------
-- FUNCTION: FN_ORDERFREIGHT
------------------------------
-- RETURNS THE ORDERFREIGHT OF THE ORDER ROWID AND CHARGECODE PASSED TO IT
------------------------------
-- DON TAYLOR @ 09/23/2020
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_ORDERFREIGHT]
(	@ORDERROWID UNIQUEIDENTIFIER,
	@CHARGECODE VARCHAR(10)
)	RETURNS DECIMAL(29,10)
AS
BEGIN
	DECLARE @RESULT  DECIMAL(29,10)
	IF @ORDERROWID IS NULL 
		RETURN NULL
	IF @CHARGECODE IS NULL 
		SET @CHARGECODE = '%'
	SET @RESULT = 
		(
		SELECT ROUND(SUM(AMOUNT),4) FROM OMFREIGHT FRT (NOLOCK)
		JOIN IDFREIGHTCHARGES CHG (NOLOCK) ON CHG.ROWID = FRT.R_CHARGECODE
		WHERE FRT.R_TRANSACTIONHEADER = @ORDERROWID
		AND CHG.CHARGECODE LIKE @CHARGECODE
		) 
	RETURN @RESULT
END
