------------------------------
-- FUNCTION: FN_ORDERVALUE
------------------------------
-- RETURNS THE CALCULATED ORDERVALUE OF THE OHROWID AND VALUELABEL PASSED TO IT
------------------------------
-- DON TAYLOR @ 09/23/2020
------------------------------
/*
--TESTBED QUERY:
SELECT
DBO.FN_ORDERVALUE(ROWID,'QUANTITYATSTAGE') AS ORDERQUANTITYATSTAGE,
DBO.FN_ORDERVALUE(ROWID,'LISTPRICE') AS ORDERLISTPRICE,
DBO.FN_ORDERVALUE(ROWID,'DISCOUNT') AS ORDERDISCOUNT,
DBO.FN_ORDERVALUE(ROWID,'UNITPRICE') AS ORDERUNITPRICE,
DBO.FN_ORDERVALUE(ROWID,'HANDLING') AS ORDERHANDLING,
DBO.FN_ORDERVALUE(ROWID,'TAGGING') AS ORDERTAGGING,
DBO.FN_ORDERVALUE(ROWID,'ITEMPRICE') AS ORDERITEMPRICE,
DBO.FN_ORDERVALUE(ROWID,'FREIGHT') AS ORDERFREIGHT,
DBO.FN_ORDERVALUE(ROWID,'LANDED') AS ORDERLANDED,
DBO.FN_ORDERVALUE(ROWID,'SALESTAX') AS ORDERSALESTAX,
DBO.FN_ORDERVALUE(ROWID,NULL) AS ORDERTOTAL
FROM OMTRANSACTIONHEADER OH WHERE OH.TRANSACTIONNUMBER = '10-11671'

*/
CREATE OR ALTER FUNCTION [DBO].[FN_ORDERVALUE]
(	@OHROWID UNIQUEIDENTIFIER,
	@VALUELABEL VARCHAR(20)
)	RETURNS DECIMAL(29,10)
AS
BEGIN
	DECLARE @RESULT  DECIMAL(29,10)
	IF @OHROWID IS NULL 
		RETURN NULL
	IF @VALUELABEL IS NULL 
		SET @VALUELABEL = 'TOTAL'
	BEGIN
		IF @VALUELABEL = 'QUANTITYATSTAGE'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'LISTPRICE'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
						DBO.FN_LISTPRICE(OD.R_ITEM,OH.SHIPPINGDATE,IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)))
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'DISCOUNT'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
							(	OD.UNITPRICE - 
								DBO.FN_LISTPRICE(	OD.R_ITEM,OH.SHIPPINGDATE,
													IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))
												)
							)
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'UNITPRICE'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
						OD.UNITPRICE
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'HANDLING'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
						OD.HANDLINGCHARGEPERITEM
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'TAGGING'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
						OD.TAGGINGCHARGEPERITEM
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'ITEMPRICE'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
							(	ISNULL(OD.UNITPRICE,0) + 
								ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
								ISNULL(OD.TAGGINGCHARGEPERITEM,0)
							)
						)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'FREIGHT'
			SET @RESULT = 
			(
				SELECT
					DBO.FN_ORDERFREIGHT(OH.ROWID, NULL)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				--JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'LANDED'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
							(	ISNULL(OD.UNITPRICE,0) + 
								ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
								ISNULL(OD.TAGGINGCHARGEPERITEM,0)
							)
						)	+ DBO.FN_ORDERFREIGHT(OH.ROWID,NULL)
							--+ DBO.FNOM_CALCULATETRANSTOTALS(OH.ROWID,'OUTSALESTAX')
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'SALESTAX'
			SET @RESULT = 
			(
				SELECT
					DBO.FNOM_CALCULATETRANSTOTALS(OH.ROWID,'OUTSALESTAX')
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				--JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
		IF @VALUELABEL = 'TOTAL'
			SET @RESULT = 
			(
				SELECT
					SUM	(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
							(	ISNULL(OD.UNITPRICE,0) + 
								ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
								ISNULL(OD.TAGGINGCHARGEPERITEM,0)
							)
						)	+ ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID,NULL),0)
							+ ISNULL(DBO.FNOM_CALCULATETRANSTOTALS(OH.ROWID,'OUTSALESTAX'),0)
				FROM OMTRANSACTIONHEADER OH (NOLOCK)
				LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
				WHERE OH.ROWID = @OHROWID
				GROUP BY OH.ROWID
			) 
	END
	RETURN @RESULT
END
