------------------------------
-- FUNCTION: FN_OMATTRIBUTES_OVERRIDES
------------------------------
-- RETURNS THE ATTRIBUTE VALUE BASED ON THE OMTRANSACTIONDETAIL ROWID, IMTRANSACTIONLOCATION ROWID AND THE ATTRIBUTENAME PASSED TO IT
-- ***ONLY RETURNS VALUE IF ISOVERRIDE = 1 FOR REPORTING ON CHECKERCOPY***
-- USES OMREVIEWTRANSACTIONDETAILATTRIBUTES:
-- SOURCE
-- DESIGCUST
-- DESIGITEM
-- DESIGLOC
--
--SELECT A.NAME FROM OMREVIEWATTRIBUTES A (NOLOCK)	--LIST OF ATTRIBUTES
--
-- IF IMTRANSACTIONLOCATION ROWID IS NULL THEN ITEM LEVEL ATTRIBUTES ARE RETURNED.
-- (I HAVE NO IDEA WHEN IT IS BEST TO PASS A NULL LOCATION BASED UPON THE ATTRIBUTE I AM ASKING FOR, MAYBE SOMEONE COULD GIVE ME A CLUE HERE)
------------------------------
-- DON TAYLOR @ 05/12/2020
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_OMATTRIBUTES_OVERRIDES]
(	@ODROWID UNIQUEIDENTIFIER,
	@ILROWID UNIQUEIDENTIFIER,
	@ATTRIBUTENAME VARCHAR(20)
)	RETURNS VARCHAR(200)	--was using VARCHARMAX but that was overkill per JoAnne 3/30/23 - DT 
AS
BEGIN
	DECLARE @RESULT  VARCHAR(200)	--was using VARCHARMAX but that was overkill per JoAnne 3/30/23 - DT 
	IF @ODROWID IS NULL 
		RETURN NULL
	IF @ILROWID IS NULL
		SET @RESULT = 
			(
			SELECT TOP 1 ODA.VALUE
			FROM OMREVIEWTRANSACTIONDETAILATTRIBUTES ODA (NOLOCK)
			JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = ODA.R_ATTRIBUTE
			--JOIN OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) ON IA.R_TRANSACTIONDETAIL = ODA.R_TRANSACTIONDETAIL AND IA.R_MASTERCODE = ODA.R_MASTERCODE
			--	AND IA.R_IMTRANSACTIONLOCATION = @ILROWID
			WHERE ODA.R_TRANSACTIONDETAIL = @ODROWID AND A.NAME = @ATTRIBUTENAME AND A.ISOVERRIDE=1)
	ELSE
		SET @RESULT = 
			(
			SELECT TOP 1 ODA.VALUE
			FROM OMREVIEWTRANSACTIONDETAILATTRIBUTES ODA (NOLOCK)
			JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = ODA.R_ATTRIBUTE
			JOIN OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) ON IA.R_TRANSACTIONDETAIL = ODA.R_TRANSACTIONDETAIL AND IA.R_MASTERCODE = ODA.R_MASTERCODE
				AND IA.R_IMTRANSACTIONLOCATION = @ILROWID
			WHERE ODA.R_TRANSACTIONDETAIL = @ODROWID AND A.NAME = @ATTRIBUTENAME AND A.ISOVERRIDE=1)

	--RETURN ISNULL(@RESULT,'')
	RETURN TRIM(@RESULT)
END
