------------------------------
-- FUNCTION: FN_ONHAND
-- 
-- FN_ONHAND(ITEMROWID,LOTROWID)
------------------------------
-- RETURNS THE ONHAND QTY FOR THE ITEMROWID,LOTROWID PARAMETERS PASSED TO IT
------------------------------
-- DON TAYLOR @ 03/13/2024
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_ONHAND]
(	@ITMROWID UNIQUEIDENTIFIER,
	@LOTROWID UNIQUEIDENTIFIER
) RETURNS BIGINT 
AS
BEGIN
	DECLARE @RESULT BIGINT 

	IF @ITMROWID IS NULL 
		RETURN NULL

	BEGIN
		IF @LOTROWID IS NOT NULL 
			BEGIN 
				SET @RESULT = 
				( 
					SELECT	ON_HAND 
					FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
					WHERE	VLOT.R_ITEM = @ITMROWID 
					AND		VLOT.ROWID = @LOTROWID
				)
			END
	END
	RETURN ISNULL(@RESULT,0) 
END
