------------------------------
-- FUNCTION: FN_PERIOD2SEASON
------------------------------
-- RETURNS THE SEASON LABEL FROM THE REPORT PERIOD PARAMETER PASSED TO IT
-- NULL PERIOD ASSUMES CURRENT PERIOD USING FN_DATE2PERIOD(GETDATE())
------------------------------
-- DON TAYLOR @ 05/08/2020
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_PERIOD2SEASON]
( @INPERIOD INTEGER
) RETURNS VARCHAR(6)
AS
BEGIN
	-- LOCAL PARAMETERS --
	DECLARE @RESULT	VARCHAR(6)
	IF @INPERIOD IS NULL 
		SET @INPERIOD = DBO.FN_DATE2PERIOD(GETDATE())

	BEGIN
		--Convert Period to Season and Return result
		IF @INPERIOD BETWEEN 1 AND 6
			SET @RESULT = 'FALL'
		IF @INPERIOD BETWEEN 7 AND 11
			SET @RESULT = 'SPRING'
		IF @INPERIOD BETWEEN 12 AND 14
			SET @RESULT = 'SUMMER'
		IF @INPERIOD IS NULL
			SET @RESULT = 'ERROR!'
	END
	RETURN @RESULT
END
