------------------------------ 
-- FUNCTION: FN_REMITTOADDRESS 
------------------------------ 
-- RETURNS THE HARDCODED (FOR NOW) REMIT-TO ADDRESS REQUESTED PART 
-- 'DUNN & BRADSTREET #03-299-2778' IS THE COMPANY DUNNS# 
------------------------------
-- FYI: OK ADDRESS IS:
--
--	28406 Hwy 82
--	Park Hill, OK 74451
--
----------------------------- 
-- DON TAYLOR @ 05/26/2023 --
----------------------------- 
CREATE OR ALTER FUNCTION [dbo].[FN_REMITTOADDRESS] 
( @VALUELABEL CHAR(20) 
) RETURNS VARCHAR(100) 
AS 
BEGIN 
	DECLARE @RESULT VARCHAR(100)

	--DEFINE THE PARTS OF THE REMIT-TO: 
	DECLARE 
		@REMITNAME CHAR(30)		= (SELECT NAME FROM ABCOMPANY (NOLOCK) WHERE COMPANYID = 'SB'), 
		@REMITDUNNS CHAR(30)	= 'Dunn & Bradstreet #03-299-2778', 
		@REMITADDRESS CHAR(20)	= 'Dept 960460', 
		@REMITCITY CHAR(20)		= 'Oklahoma City', 
		@REMITSTATE CHAR(2)		= 'OK', 
		@REMITZIP CHAR(10)		= '73196' 
	IF @VALUELABEL IS NULL 
		SET @VALUELABEL = 'ADDRESSMEMO' 
	BEGIN 
		IF @VALUELABEL = 'ADDRESSMEMO' 
			SET @RESULT = (	UPPER(@REMITNAME) + CHAR(13)+CHAR(10) + 
							UPPER(@REMITADDRESS) + CHAR(13)+CHAR(10) + 
							UPPER(@REMITCITY) + ', ' + UPPER(@REMITSTATE) + '  ' + UPPER(@REMITZIP) 
						) 
		IF @VALUELABEL = 'DUNNS' 
			SET @RESULT = (	UPPER(@REMITDUNNS) ) 
		IF @VALUELABEL = 'NAME' 
			SET @RESULT = (	UPPER(@REMITNAME) ) 
		IF @VALUELABEL = 'ADDRESS' 
			SET @RESULT = (	UPPER(@REMITADDRESS) ) 
		IF @VALUELABEL = 'CITY' 
			SET @RESULT = (	UPPER(@REMITCITY) ) 
		IF @VALUELABEL = 'STATE' 
			SET @RESULT = (	UPPER(@REMITSTATE) ) 
		IF @VALUELABEL = 'ZIP' 
			SET @RESULT = (	UPPER(@REMITZIP) ) 
	END 
	RETURN @RESULT 
END 
GO 



