------------------------------
-- FUNCTION: FN_SUPPLYROLLUP
--
-- FN_SUPPLYROLLUP(ITEMROWID,NUMERIC OR [PY/CY/NY/NULL=PY+CY],[X/Y/Z/F/S/U/F1..U3/NULL=FSU/%=ALL],[HSFILTER/NOFILTER=NULL],[INFLATED/NOTINFLATED=NULL])
------------------------------
-- RETURNS THE SUPPLY QTY FOR THE @LOTYEAR, @LOTSEASON PARAMETERS PASSED TO IT
--		USE NUMERIC UNLESS YOU LITERALLY WANT TO FORCE THE CALCULATION ALGORITHM:
--			NUMERIC @LOTYEAR WILL ROLLUP PY+CY FOR VALUES <= CURRENTYEAR, AND ROLLUP @LOTYEAR FOR ALL OTHERS
--			NULL @LOTYEAR WILL ROLLUP PY+CY REGARDLESS
------------------------------
-- DON TAYLOR @ 10/19/2021
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_SUPPLYROLLUP]
(	@ITMROWID UNIQUEIDENTIFIER,
	@LOTYEAR VARCHAR(2),
	@LOTSEASON VARCHAR(3), 
	@HSFILTER VARCHAR(1),
	@INFLATED VARCHAR = NULL
) RETURNS FLOAT
AS
BEGIN
	DECLARE @RESULT FLOAT
	DECLARE @CY VARCHAR(2)

	IF @ITMROWID IS NULL 
		RETURN NULL
	IF @LOTSEASON IS NULL
		SET @LOTSEASON = 'FSU'
	IF @HSFILTER IS NULL
		SET @HSFILTER = '%'
	SET @CY = TRIM(STR(DBO.FN_DATE2YEAR(NULL) % 100))
--	SET @CY = TRIM(STR(DBO.FN_SALEYEAR(NULL) % 100))
	IF @LOTYEAR IS NULL
		SET @LOTYEAR = @CY
	BEGIN
		IF @LOTSEASON = 'FSU'
			BEGIN --MULTIPLE LOTSEASON CALCULATIONS--FSU WITH WILDCARDS
				SET @RESULT =
				(
					SELECT 
						DBO.FN_SUPPLYROLLUP(@ITMROWID,@LOTYEAR,'F%',@HSFILTER,@INFLATED) +
						DBO.FN_SUPPLYROLLUP(@ITMROWID,@LOTYEAR,'S%',@HSFILTER,@INFLATED) +
						DBO.FN_SUPPLYROLLUP(@ITMROWID,@LOTYEAR,'U%',@HSFILTER,@INFLATED)
				)
			END
		ELSE
			BEGIN --SINGLE LOTSEASON CALCULATIONS--
				IF ISNUMERIC(@LOTYEAR) = 1
					BEGIN --NUMERIC VALUE PASSED AS @LOTYEAR
						IF @LOTYEAR <= @CY
							SET @RESULT = 
							( --COMBINED CURRENT/PREVIOUS YEARS
								SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
								FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
								JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
								WHERE	VLOT.R_ITEM = @ITMROWID 
								AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
								AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
								AND		SUBSTRING(VLOT.LOTCODE, 1, 2) <= @CY
							)
						ELSE
							SET @RESULT = 
							( --USE LOTYEAR VALUES ONLY
								SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
								FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
								JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
								WHERE	VLOT.R_ITEM = @ITMROWID 
								AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
								AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
								AND		SUBSTRING(VLOT.LOTCODE, 1, 2) = @LOTYEAR
							)
					END
--------------------------------------------------------------------------
				-- LITERAL VALUES PASSED AS @LOTYEAR
				IF @LOTYEAR = 'PY'
					SET @RESULT = 
					( --PREVIOUS YEAR
						SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
						FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
						JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
						WHERE	VLOT.R_ITEM = @ITMROWID 
						AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
						AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
						AND		SUBSTRING(VLOT.LOTCODE, 1, 2) < @CY 
					)
				IF @LOTYEAR = 'CY'
					SET @RESULT = 
					( --CURRENT YEAR
						SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
						FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
						JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
						WHERE	VLOT.R_ITEM = @ITMROWID 
						AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
						AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
						AND		SUBSTRING(VLOT.LOTCODE, 1, 2) = @CY
					)
				--IF @LOTYEAR IS NULL
				--	SET @RESULT = 
				--	( --COMBINED CURRENT/PREVIOUS YEARS
				--		SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
				--		FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				--		JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
				--		WHERE	VLOT.R_ITEM = @ITMROWID 
				--		AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
				--		AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
				--		AND		SUBSTRING(VLOT.LOTCODE, 1, 2) <= @CY
				--	)
				--IF @LOTYEAR = 'NY'
				--	SET @RESULT = 
				--	( --NEXT YEAR
				--		SELECT SUM(DBO.FN_SUPPLY(@ITMROWID, VLOT.ROWID, @INFLATED))
				--		FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				--		JOIN	IMLOT (NOLOCK) ON IMLOT.ROWID = VLOT.ROWID
				--		WHERE	VLOT.R_ITEM = @ITMROWID 
				--		AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') LIKE @HSFILTER
				--		AND		SUBSTRING(VLOT.LOTCODE,4,2) LIKE @LOTSEASON
				--		AND		SUBSTRING(VLOT.LOTCODE, 1, 2) = @CY + 1
				--	)
			END
	END
	RETURN ISNULL(@RESULT,0)
END
