------------------------------
-- FUNCTION: FN_SALESNOTE
------------------------------
-- RETURNS THE SALESNOTE BASED ON THE ITEM ROWID, LOT ROWID & DATE PARAMETERS PASSED TO IT
-- NULL DATE ASSUMES CURRENT DATE USING GETDATE()
------------------------------
-- DON TAYLOR @ 06/24/2020
------------------------------
--USING HOLDSTOPREASON FROM UDR_4
--USING SALESNOTE FROM UDR_7
--USING SALESNOTESTARTDATE FROM UDD_6
--USING SALESNOTEENDDATE FROM UDD_7
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_SALESNOTE]
(	@ITMROWID UNIQUEIDENTIFIER,
	@LOTROWID UNIQUEIDENTIFIER,
	@INDATE DATETIME
) RETURNS VARCHAR(103)
AS
BEGIN
	DECLARE @RESULT VARCHAR(103)

	IF @INDATE IS NULL
		SET @INDATE = GETDATE()
	IF @LOTROWID IS NOT NULL 
		SET @RESULT = 
		(
			--DON'T PREPEND HSREASON IF USING THIS FUNCTION, USE FN_SALESNOTEREASON INSTEAD.
			--SELECT	IIF(USERDEFINEDREFERENCE_7 IS NULL,
						--NULLIF(TRIM(USERDEFINEDREFERENCE_4) + ' / ', ' / '), 
						--NULLIF(TRIM(USERDEFINEDREFERENCE_4) + ' / ', ' / ') + USERDEFINEDREFERENCE_7)
			SELECT	USERDEFINEDREFERENCE_7
			FROM	IMLOT (NOLOCK)
			WHERE	IMLOT.ROWID = @LOTROWID
			AND		IMLOT.R_ITEM = @ITMROWID
			--RULE: STARTDATE IS REQUIRED, DO NOT OVERRIDE NULL WITH A VALID DATEVALUE
			--AND		@INDATE BETWEEN IMLOT.USERDEFINEDDATE_6 AND ISNULL(IMLOT.USERDEFINEDDATE_7, '12/31/9999')
			--BETTER RULE: THERE ARE NO RULES
			AND		@INDATE BETWEEN ISNULL(IMLOT.USERDEFINEDDATE_6, '01/01/1900') AND ISNULL(IMLOT.USERDEFINEDDATE_7, '12/31/9999')
		)
	RETURN @RESULT
END
