------------------------------
-- FUNCTION: FN_SUPPLY
-- 
-- FN_SUPPLY(ITEMROWID,LOTROWID)
------------------------------
-- RETURNS THE SUPPLY QTY FOR THE ITEMROWID,LOTROWID PARAMETERS PASSED TO IT
------------------------------
-- DON TAYLOR @ 05/20/2020
------------------------------
-- ADDED @INFLATED PARAMETER
-- DEDUCT LOTS ON STOP SHIP (HOLDSTOP CODE: S)
------------------------------
CREATE OR ALTER   FUNCTION [DBO].[FN_SUPPLY]
(	@ITMROWID UNIQUEIDENTIFIER,
	@LOTROWID UNIQUEIDENTIFIER,
	@INFLATED VARCHAR = NULL
) RETURNS FLOAT 
AS
BEGIN
	DECLARE @RESULT FLOAT 

	IF @ITMROWID IS NULL 
		RETURN NULL
	BEGIN
		IF @LOTROWID IS NOT NULL 
			BEGIN 
				SET @RESULT = 
				( 
					SELECT	ISNULL(NETAVAILABLE,0) + ISNULL(OUT_ORDERED,0) + ISNULL(OUT_SHIPPED,0) + ISNULL(OUT_BACKORDER,0) 
					FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
					WHERE	VLOT.R_ITEM = @ITMROWID 
					AND		VLOT.ROWID = @LOTROWID
					AND		ISNULL(VLOT.USERDEFINEDCODE_3,'') <> 'S'--DEDUCT LOTS ON STOP SHIP
				)
			END
	END
	--INFLATE THE VALUE IF REQUESTED.
	IF @INFLATED IS NULL
		RETURN ISNULL(@RESULT,0) 
	ELSE
		BEGIN
			SET @RESULT = 
				(
					@RESULT * (1+(
					(
						SELECT	ISNULL(IMLOT.OVERSELLPERCENTAGE, 0)
						FROM	IMLOT (NOLOCK) 
						WHERE	IMLOT.R_ITEM = @ITMROWID 
						AND		IMLOT.ROWID = @LOTROWID
					)
					/100))
				)

		END
	RETURN ISNULL(ROUND(@RESULT,0),0) 
END
