------------------------------
-- FUNCTION: FN_SHIPPEDBYCYCLE
------------------------------
-- RETURNS THE SHIPPED QTY FOR THE @YEAR AND @SEASON PARAMETER PASSED TO IT
-- QUANTITIES ARE DETERMINED USING DATERANGES STORED IN IMSEASONCODE TABLE
-- NULL @YEAR DEFAULTS TO CURRENT DIGIT SALEYEAR
-- NULL @SEASON DEFAULTS TO ALL SEASONS (%)
------------------------------
-- DON TAYLOR @ 05/12/2020
------------------------------
-- CONVERTED @RESULT TO BIGINT DATATYPE
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_SHIPPEDBYCYCLE]
(	@ITMROWID UNIQUEIDENTIFIER,
	@YEAR	VARCHAR(2),
	@SEASON VARCHAR(3)
) RETURNS BIGINT
AS
BEGIN
	DECLARE @RESULT BIGINT
	DECLARE @STARTDATE DATE
	DECLARE @ENDDATE DATE

	--BAIL ON NULL ROWID.
	IF @ITMROWID IS NULL 
		RETURN 0
	--STORE CURRENT 2-DIGIT YEAR TO SPEED UP PROCESSING TIME
	IF @YEAR IS NULL
		SET @YEAR = STR(DBO.FN_SALEYEAR(NULL)%100,2)
	IF @SEASON IS NULL
		SET @SEASON = '%'
	--CALCULATE.
	SET @RESULT = 
	( 
		--CALCULATE USING DATERANGES STORED IN IMSEASONCODE TABLE:
		SELECT ISNULL(SUM(OD.QUANTITYSHIPPED), 0)
		FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
		JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
		--JOIN ITEM AND WAREHOUSE TO LOOKUP IMSEASONCODE START/END DATES.
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		LEFT JOIN IMSEASONCODE SC (NOLOCK) ON SC.SEASONCODE LIKE @YEAR+'.'+STR(WH.IDENTITYID,2)+'.'+@SEASON
		WHERE OD.R_ITEM = @ITMROWID
		AND OH.INVOICEDATE BETWEEN SC.STARTDATE AND SC.ENDDATE
		AND OH.RECORDTYPE = 'Z'
	)
	RETURN ISNULL(@RESULT,0)
END
--SELECT * FROM IMSEASONCODE SC (NOLOCK) WHERE SC.SEASONCODE LIKE '22.10.%'--GETDATE() BETWEEN SC.STARTDATE AND SC.ENDDATE
