------------------------------
-- FUNCTION: FN_STAGESORT
------------------------------
-- RETURNS THE DESCRIPTIVE NAME OF THE STAGE FLAG WITH A SORTORDER APPENDED TO IT
-- PARAMETER ADDED: @MODULE {IM/OM}
-- USES DATA FROM ABFLAGFIELD TABLE NOW
------------------------------
-- DON TAYLOR @ 06/02/2020
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_STAGESORT]
(	@STAGE CHAR(1),
	@MODULE CHAR(2)
) RETURNS VARCHAR(21)
AS
BEGIN
	DECLARE @RESULT VARCHAR(21)
	DECLARE @SORT	VARCHAR(3)
	DECLARE	@LENGTH	INT
	IF @STAGE IS NULL 
		RETURN NULL
	IF @MODULE IS NULL
		SET @MODULE = 'OM'
	SET @SORT =
		(
			SELECT TRIM(STR(CHARINDEX(FF.FLAGVALUE,'LQPFNASC')))
			FROM ABFLAGFIELD FF (NOLOCK) WHERE FF.FIELDNAME LIKE 'STAGE' AND LEFT(FF.TABLENAME,2) = @MODULE
			AND FF.FLAGVALUE = @STAGE
		)
	SET @LENGTH = 
		(
			SELECT CHARINDEX(' -',FF.FLAGDESCRIPTION)
			FROM ABFLAGFIELD FF (NOLOCK) WHERE FF.FIELDNAME LIKE 'STAGE' AND LEFT(FF.TABLENAME,2) = @MODULE
			AND FF.FLAGVALUE = @STAGE
		)
	SET @RESULT = 
		(
			SELECT @SORT+'. '+LEFT(FF.FLAGDESCRIPTION,@LENGTH)
			FROM ABFLAGFIELD FF (NOLOCK) WHERE FF.FIELDNAME LIKE 'STAGE' AND LEFT(FF.TABLENAME,2) = @MODULE
			AND FF.FLAGVALUE = @STAGE
		)
	RETURN @RESULT
END
GO
/*
^THIS CODE WAS REPLACED WITH THE CODE ABOVE^
CREATE OR ALTER FUNCTION [DBO].[FN_STAGESORT]
( @STAGE CHAR(1)
) RETURNS VARCHAR(12)
AS
BEGIN
	DECLARE @RESULT VARCHAR(12)
	IF @STAGE IS NULL 
		RETURN NULL
	SET @RESULT = 
		(
			SELECT SUBSTRING('0. Inactive 1. Canceled 2. Quote    3. Plan     4. Future   5. Pending  6. Assigned 7. Picked   8. Completed',	
						1+(CHARINDEX(@STAGE,'ILQPFNASC')-1)*12, 12)
			--The IM Stage descriptions are slightly different:
			--SELECT SUBSTRING('0. Inactive 1. Canceled 2. Quote    3. Plan     4. Future   5. Pending  6. Assigned 7. Received 8. Completed',	
			--			1+(CHARINDEX(@STAGE,'ILQPFNASC')-1)*12, 12)
		)
	RETURN @RESULT
END
GO
*/

