------------------------------
-- FUNCTION: FN_SHIPPEDBYSEASON	* * * DON'T THINK THIS IS BEING USED NOW...USING SHIPPEDBYCYCLE INSTEAD * * *
------------------------------
-- RETURNS THE SHIPPED QTY FOR THE @YEAR AND @SEASON PARAMETER PASSED TO IT
-- QUANTITIES ARE DETERMINED BY LOTCODES
-- NULL @YEAR DEFAULTS TO CURRENT DIGIT SALEYEAR
-- NULL @SEASON DEFAULTS TO ALL SEASONS (%)
------------------------------
-- DON TAYLOR @ 05/12/2020
------------------------------
-- CONVERTED @RESULT TO BIGINT DATATYPE
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_SHIPPEDBYSEASON]
(	@ITMROWID UNIQUEIDENTIFIER,
	@YEAR	VARCHAR(2),
	@SEASON VARCHAR(3)
) RETURNS BIGINT
AS
BEGIN
	DECLARE @RESULT BIGINT

	--BAIL ON NULL ROWID.
	IF @ITMROWID IS NULL 
		RETURN 0
	--STORE CURRENT 2-DIGIT YEAR TO SPEED UP PROCESSING TIME
	IF @YEAR IS NULL
		SET @YEAR = STR(DBO.FN_SALEYEAR(NULL)%100,2)
	IF @SEASON IS NULL
		SET @SEASON = '%'
	--CALCULATE.
	SET @RESULT = 
	( 
		SELECT ISNULL(SUM(OD.QUANTITYSHIPPED), 0)
		FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
		JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
		LEFT OUTER JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT
		WHERE OD.R_ITEM = @ITMROWID
		AND SUBSTRING(LOT.LOTCODE,4,2) LIKE @SEASON
		AND LEFT(LOT.LOTCODE,2) = @YEAR--DBO.FN_SALEYEAR(NULL) % 100
		AND OH.RECORDTYPE = 'Z'
	)
	RETURN ISNULL(@RESULT,0)
END
