------------------------------ 
-- FUNCTION: FN_WHITELIST 
------------------------------ 
-- REMOVES SPECIAL CHARACTERS FROM TEXT BASED ON THE LEVEL DESIRED
-- DEFAULT - REMOVES THE ENTIRE LIST
-- 
----------------------------- 
-- DON TAYLOR @ 05/26/2023 --
----------------------------- 

CREATE OR ALTER FUNCTION [dbo].[FN_WHITELIST] 
( @INPUT VARCHAR(200) 
) RETURNS VARCHAR(200) 
AS 
BEGIN 
--DECLARE @INPUT VARCHAR(200) = (SELECT TOP 1 DESCRIPTION_1 FROM IMITEM ITM (NOLOCK) WHERE ITM.ITEMCODE LIKE '003158%')
	DECLARE @RESULT VARCHAR(200)
	SET @RESULT = @INPUT 
	--REMOVE ASCII CODES: 33-47
	SET @RESULT = REPLACE(@RESULT, CHAR(33), '')	-- REPLACE !
	SET @RESULT = REPLACE(@RESULT, CHAR(34), '')	-- REPLACE "
	SET @RESULT = REPLACE(@RESULT, CHAR(35), '')	-- REPLACE #
	SET @RESULT = REPLACE(@RESULT, CHAR(36), '')	-- REPLACE $
	SET @RESULT = REPLACE(@RESULT, CHAR(37), '')	-- REPLACE %
	SET @RESULT = REPLACE(@RESULT, CHAR(38), '')	-- REPLACE &
	SET @RESULT = REPLACE(@RESULT, CHAR(39), '')	-- REPLACE '
	SET @RESULT = REPLACE(@RESULT, CHAR(40), '')	-- REPLACE (
	SET @RESULT = REPLACE(@RESULT, CHAR(41), '')	-- REPLACE )
	SET @RESULT = REPLACE(@RESULT, CHAR(42), '')	-- REPLACE *
	SET @RESULT = REPLACE(@RESULT, CHAR(43), '')	-- REPLACE +
	SET @RESULT = REPLACE(@RESULT, CHAR(44), '')	-- REPLACE ,
	SET @RESULT = REPLACE(@RESULT, CHAR(45), '')	-- REPLACE -
	SET @RESULT = REPLACE(@RESULT, CHAR(46), '')	-- REPLACE .
	SET @RESULT = REPLACE(@RESULT, CHAR(47), '')	-- REPLACE /

	--REMOVE ASCII CODES: 58-64
	SET @RESULT = REPLACE(@RESULT, CHAR(58), '')	-- REPLACE :
	SET @RESULT = REPLACE(@RESULT, CHAR(59), '')	-- REPLACE ;
	SET @RESULT = REPLACE(@RESULT, CHAR(60), '')	-- REPLACE <
	SET @RESULT = REPLACE(@RESULT, CHAR(61), '')	-- REPLACE =
	SET @RESULT = REPLACE(@RESULT, CHAR(62), '')	-- REPLACE >
	SET @RESULT = REPLACE(@RESULT, CHAR(63), '')	-- REPLACE ?
	SET @RESULT = REPLACE(@RESULT, CHAR(64), '')	-- REPLACE @

	--REMOVE ASCII CODES: 91-96
	SET @RESULT = REPLACE(@RESULT, CHAR(91), '')	-- REPLACE [
	SET @RESULT = REPLACE(@RESULT, CHAR(92), '')	-- REPLACE \
	SET @RESULT = REPLACE(@RESULT, CHAR(93), '')	-- REPLACE ]
	SET @RESULT = REPLACE(@RESULT, CHAR(94), '')	-- REPLACE ^
	SET @RESULT = REPLACE(@RESULT, CHAR(95), '')	-- REPLACE _
	SET @RESULT = REPLACE(@RESULT, CHAR(96), '')	-- REPLACE `

	--REMOVE ASCII CODES: 153 AND 174
	SET @RESULT = REPLACE(@RESULT, CHAR(153), '')	-- REPLACE ™
	SET @RESULT = REPLACE(@RESULT, CHAR(174), '')	-- REPLACE ®

	--REMOVE ANY REMAINING DOUBLE SPACES
	SET @RESULT = REPLACE(@RESULT, CHAR(32)+CHAR(32), '')	-- REPLACE DBLSPACES

	--SELECT @INPUT, @RESULT 
	RETURN @RESULT
END
