------------------------------
-- FUNCTION: FN_YEAR2DATE
------------------------------
-- RETURNS THE STARTDATE OF A REPORT YEAR FROM THE YEAR PARAMETER PASSED TO IT
-- NULL YEAR ASSUMES CURRENT REPORT YEAR USING FN_DATE2YEAR(GETDATE())
------------------------------
-- DON TAYLOR @ 05/08/2020
------------------------------
CREATE OR ALTER FUNCTION [DBO].[FN_YEAR2DATE]
( @INYEAR INTEGER
) RETURNS DATETIME
AS
BEGIN
	-- LOCAL PARAMETERS --
	DECLARE @RESULT	DATETIME
	DECLARE @DATE DATETIME

	IF @INYEAR IS NULL 
		SET @INYEAR = DBO.FN_DATE2YEAR(GETDATE())

	BEGIN
		--AUGUST 1ST IS ALWAYS IN WEEK 1
		SET @DATE = '08/01/' + TRIM(STR(@INYEAR-1)) 
		--DETERMINE DATE OF BEGINNING OF WEEK 1
		SET @RESULT = DATEADD(D, 1-(DATEPART(DW, @DATE)), @DATE) 
	END
	RETURN @RESULT
END
