--AR Monthend AgingbySalesrep_short
SELECT --*, 
	SALESREPID, SALESREPNAME, 
	CUSTOMERIDENTITYID, CUSTOMERNAME, 
	CUSTOMERADDRESS_1, CUSTOMERADDRESS_2, CUSTOMERCITY, CUSTOMERCITY, CUSTOMERSTATE, CUSTOMERZIP, 
	TERMSDESCRIPTION, 
	CONSIGNEEID, CONSIGNEENAME, 
	TRANSACTIONTYPE,TRANSACTIONTYPEDESCRIPTION,TRANSACTIONNUMBER, DESCRIPTION, 
	TRANSACTIONDATE, TRANSACTIONDUEDATE, TRANSACTIONAMOUNT, PAYMENT, BALANCE, 
	PERIODDAYSDUE, CURRENTDAYSDUE, 
	IIF(PERIODDAYSDUE <= 0, BALANCE, 0.00) AS BUCKET1, 
	IIF(PERIODDAYSDUE BETWEEN 1 AND 30, BALANCE, 0.00) AS BUCKET2, 
	IIF(PERIODDAYSDUE BETWEEN 31 AND 60, BALANCE, 0.00) AS BUCKET3, 
	IIF(PERIODDAYSDUE BETWEEN 61 AND 90, BALANCE, 0.00) AS BUCKET4, 
	IIF(PERIODDAYSDUE BETWEEN 91 AND 120, BALANCE, 0.00) AS BUCKET5, 
	IIF(PERIODDAYSDUE > 120, BALANCE, 0.00) AS BUCKET6 
FROM VW_RPT_STATEMENT (NOLOCK) 
WHERE RECORDTYPE = 'U' 
order by SALESREPID, CUSTIDENTITYID, TRANSACTIONDUEDATE

--AR Monthend AgingbySalesrep_fulldump
SELECT *, 
	IIF(PERIODDAYSDUE <= 0, BALANCE, 0.00) AS BUCKET1, 
	IIF(PERIODDAYSDUE BETWEEN 1 AND 30, BALANCE, 0.00) AS BUCKET2, 
	IIF(PERIODDAYSDUE BETWEEN 31 AND 60, BALANCE, 0.00) AS BUCKET3, 
	IIF(PERIODDAYSDUE BETWEEN 61 AND 90, BALANCE, 0.00) AS BUCKET4, 
	IIF(PERIODDAYSDUE BETWEEN 91 AND 120, BALANCE, 0.00) AS BUCKET5, 
	IIF(PERIODDAYSDUE > 120, BALANCE, 0.00) AS BUCKET6 
FROM VW_RPT_STATEMENT (NOLOCK) 
WHERE RECORDTYPE = 'U' 
order by SALESREPID, CUSTIDENTITYID, TRANSACTIONDUEDATE

