--LowesOrdersAndCreditswithWOnumbers
SELECT 
WH.IDENTITYID AS WAREHOUSEID, 
CUST.IDENTITYID AS CUSTOMERID, 
OH.RECORDTYPE, 
OH.TRANSACTIONNUMBER, 
OH.TRANSACTIONTYPE,
OH.TRANSACTIONDATE, 
OH.INVOICEDATE, 
OH.USERDEFINEDREFERENCE_4 AS WO,
IIF(OH.TRANSACTIONTYPE='I', 1, -1) * DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL 

FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
WHERE CUST.IDENTITYID = '10037'

ORDER BY 
WH.IDENTITYID, 
OH.TRANSACTIONTYPE, 
OH.TRANSACTIONNUMBER