--PAYMENT_HISTORY
SELECT 
	WH.COMPANYID, 
	WH.IDENTITYID AS WAREHOUSEID, WH.NAME AS WAREHOUSENAME, 
	CUST.IDGROUP AS GROUPID, 
	CUST.IDENTITYID AS CUSTOMERID, CUST.NAME AS CUSTOMERNAME, 
	CONS.IDENTITYID AS CONSIGNEEID, CONS.NAME AS CONSIGNEENAME, 
	OH.TRANSACTIONNUMBER, OH.TRANSACTIONTYPE, OH.RECORDTYPE, 
	DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL, OH.TRANSACTIONDATE, OH.TRANSACTIONDUEDATE, 
	CRD.AMOUNTAPPLIED, ARPAY.PAYMENTDATE, 
	CRH.FISCALPERIOD, CRH.FISCALYEAR, CRH.CONTROLAMOUNT, CRH.OPENCREDITAMOUNT, ARPAY.CHECKNUMBER
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 

JOIN AROPENITEMHEADER AH (NOLOCK) ON AH.R_SOURCEID = OH.ROWID 
JOIN ARCASHRECEIPTSDETAIL CRD (NOLOCK) ON CRD.R_AROPENITEMHEADER = AH.ROWID 
JOIN ARCASHRECEIPTSHEADER CRH (NOLOCK) ON CRH.ROWID = CRD.R_CASHRECEIPTSHEADER
JOIN ARCASHRECEIPTSPAYMENTS ARPAY (NOLOCK) ON ARPAY.R_ARCASHRECEIPTSHEADER = CRH.ROWID 

WHERE OH.RECORDTYPE = 'Z' 
AND CUST.IDENTITYID = '10043' 
ORDER BY 
	CUST.IDGROUP, CUST.IDENTITYID, CONS.IDENTITYID, OH.TRANSACTIONDATE, ARPAY.PAYMENTDATE, ARPAY.CHECKNUMBER 


