--PROJECT REPORT BY DEPARTMENT
-- FOR DOMINIC SAETHER

--STOLEN FROM VW_RPT_GP_DEPT_HOURS_BY_JOBCODE AND VW_RPT_GP_DEPT_DOLLARS_BY_JOBCODE
--MINUS THE COLUMNS THAT RADEAN WANTED
SELECT 'SB' AS COMPANYID, 
	WAREHOUSE, DEPARTMENT, DEPTDESC, 
	JOBCODE, JOBDESC, 
	CAST (CHECKDATE AS DATE) AS CHECKDATE, PAYROLCD, 
	SUM(HOURS) AS HOURS, 
	SUM(DOLLARS) AS DOLLARS
FROM (
	SELECT 
	IIF(LEFT(GP.DEPRTMNT,1)='3', '60', LEFT(GP.DEPRTMNT,1)+'0') WAREHOUSE, 
	GP.DEPRTMNT AS DEPARTMENT, GP.DEPTDESC, 
	GP.JOBTITLE AS JOBCODE, GP.JOBDESC, 
	GP.UNTSTOPY AS HOURS, 
	GP.UPRTRXAM AS DOLLARS, 
	GP.CHEKDATE AS CHECKDATE, 
	GP.PAYROLCD 
	FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor GP (NOLOCK) 
) X
WHERE WAREHOUSE = '40'

GROUP BY 
	WAREHOUSE, 
	DEPARTMENT, 
	DEPTDESC, 
	JOBCODE, 
	JOBDESC, 
	CHECKDATE, 
	PAYROLCD 
