--CARRYOVERS NEEDING MOVED TO SY2024 --BY LOTCODE
SELECT 
	WHID, LOTYEAR, LOTCODE, 
	COUNT(*) AS ITEMCOUNT,
	SUM(IN_BACKORDER) AS IN_BACKORDER, 
	SUM(IN_FUTURE) AS IN_FUTURE, 
	SUM(IN_ORDERED) AS IN_ORDERED, 
	SUM(IN_RECEIVING) AS IN_RECEIVING, 
	SUM(IN_UNAVAILABLE) AS IN_UNAVAILABLE, 
	SUM(ON_HAND) AS ON_HAND, 
	SUM(AVAILABLE) AS AVAILABLE, 
	SUM(NETAVAILABLE) AS NETAVAILABLE, 
	SUM(OUT_BACKORDER) AS OUT_BACKORDER, 
	SUM(OUT_FUTURE) AS OUT_FUTURE, 
	SUM(OUT_ORDERED) AS OUT_ORDERED, 
	SUM(OUT_SHIPPED) AS OUT_SHIPPED, 
	SUM(OUT_UNAVAILABLE) AS OUT_UNAVAILABLE
FROM (	SELECT 
			WH.IDENTITYID AS WHID, ITM.ITEMCODE, 
			LEFT(LOTCODE,2) AS LOTYEAR, LOTCODE, 
			V.IN_BACKORDER, V.IN_FUTURE, V.IN_ORDERED, V.IN_RECEIVING, V.IN_UNAVAILABLE, 
			V.ON_HAND, V.AVAILABLE, V.NETAVAILABLE, 
			V.OUT_BACKORDER, V.OUT_FUTURE, V.OUT_ORDERED, V.OUT_SHIPPED, V.OUT_UNAVAILABLE
		FROM VW_IMLOTVIEW2 V (NOLOCK) 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = V.R_ITEM 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
		WHERE LEFT(LOTCODE,2) < 23
		AND (	V.IN_BACKORDER >0 OR V.IN_FUTURE >0 OR V.IN_ORDERED >0 OR V.IN_RECEIVING >0 OR V.IN_UNAVAILABLE >0 OR 
				V.ON_HAND >0 OR V.AVAILABLE >0 OR V.NETAVAILABLE >0 OR 
				V.OUT_BACKORDER >0 OR V.OUT_FUTURE >0 OR V.OUT_ORDERED >0 OR V.OUT_SHIPPED >0 OR V.OUT_UNAVAILABLE >0 )
		--AND (	V.IN_BACKORDER >0 OR V.IN_FUTURE >0 OR V.IN_ORDERED >0 OR 
		--		V.IN_RECEIVING >0 OR V.IN_UNAVAILABLE >0 OR V.NETAVAILABLE >0 OR 	
		--		V.ON_HAND >0 OR V.OUT_BACKORDER >0 OR V.OUT_FUTURE >0 OR 
		--		V.OUT_ORDERED >0 OR V.OUT_SHIPPED >0 OR V.OUT_UNAVAILABLE >0 )
) X
GROUP BY WHID, LOTYEAR, LOTCODE
ORDER BY WHID, LOTYEAR, LOTCODE
----------------------------------------------------

--OLD CARRYOVER RECORDS BY ITEM--WAS:745--LATEST:740
		SELECT 
			WH.IDENTITYID AS WHID, ITM.ITEMCODE, 
			LEFT(LOTCODE,2) AS LOTYEAR, LOTCODE, 
			V.IN_BACKORDER, V.IN_FUTURE, V.IN_ORDERED, V.IN_RECEIVING, V.IN_UNAVAILABLE, 
			V.ON_HAND, V.AVAILABLE, V.NETAVAILABLE, 
			V.OUT_BACKORDER, V.OUT_FUTURE, V.OUT_ORDERED, V.OUT_SHIPPED, V.OUT_UNAVAILABLE
		FROM VW_IMLOTVIEW2 V (NOLOCK) 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = V.R_ITEM 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
		WHERE LEFT(LOTCODE,2) < 23
		AND (	V.IN_BACKORDER >0 OR V.IN_FUTURE >0 OR V.IN_ORDERED >0 OR V.IN_RECEIVING >0 OR V.IN_UNAVAILABLE >0 OR 
				V.ON_HAND >0 OR V.AVAILABLE >0 OR V.NETAVAILABLE >0 OR 
				V.OUT_BACKORDER >0 OR V.OUT_FUTURE >0 OR V.OUT_ORDERED >0 OR V.OUT_SHIPPED >0 OR V.OUT_UNAVAILABLE >0 )
		ORDER BY WH.IDENTITYID, V.LOTCODE, ITM.ITEMCODE

