--Saad Duplicate Mastercode Query

SELECT 
dbo.fn_getidentityid(itm.r_warehouse) as warehouse,
ITM.ITEMCODE, itm.DESCRIPTION_1 as commonname, LOT.LOTCODE, LOC.LOCATIONCODE, 
DBO.FN_MCATTRIBUTES(M.ROWID,'Source') AS SOURCE, 
DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigItem') AS DESIGITEM, 
DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigCust') AS DESIGCUST, 
DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigLoc') AS DESIGLOC,
M.PRODUCTIONQUANTITY,
----vv--ADDITIONAL FIELDS ELLEN ASKED FOR--------------------------------
	DBO.FN_MCATTRIBUTES(M.ROWID,'Priority') AS Priority, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'PriSetBy') AS PriSetBy, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'PriUpdate') AS PriUpdate, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'Location Note') AS Location_Note, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LocNoteDate') AS LocNoteDate, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LocationPTN1') AS LocationPTN1, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LocationPTN2') AS LocationPTN2, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LastProdSchLine#') AS LastProdSchLine#, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LastTransText') AS LastTransText, 
	DBO.FN_MCATTRIBUTES(M.ROWID,'LastPltgDate') AS LastPltgDate, 
----^^--ADDITIONAL FIELDS ELLEN ASKED FOR--------------------------------
M.LASTUPDATEDATETIME,
M.LASTUPDATEUSERID
FROM OMREVIEWMASTERCODES M (NOLOCK)
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = M.R_ITEM
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = M.R_LOT 
JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = M.R_LOCATION

WHERE ISNULL(CONVERT(VARCHAR(38), M.R_ITEM), '') + ISNULL(CONVERT(VARCHAR(38), M.R_LOT), '') + ISNULL(CONVERT(VARCHAR(38), M.R_LOCATION), '') + ISNULL(DBO.FN_MCATTRIBUTES(M.ROWID,'Source'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigItem'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigCust'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(M.ROWID, 'DesigLoc'), '|')
IN 
(
SELECT 
ISNULL(CONVERT(VARCHAR(38), MC.R_ITEM), '') + ISNULL(CONVERT(VARCHAR(38), MC.R_LOT), '') + ISNULL(CONVERT(VARCHAR(38), MC.R_LOCATION), '') + ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'Source'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust'), '|') + ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc'), '|')
FROM OMREVIEWMASTERCODES MC (NOLOCK)
GROUP BY MC.R_ITEM, MC.R_LOT, MC.R_LOCATION, 
DBO.FN_MCATTRIBUTES(MC.ROWID,'Source'), 
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem') , 
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust'), 
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc')
HAVING COUNT(*) > 1
)
ORDER BY dbo.fn_getidentityid(itm.r_warehouse),ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE,
SOURCE, 
DESIGITEM, 
DESIGCUST, 
DESIGLOC 
