--USE [ABECAS_CUST_GNC_STRESSTEST]
--GO

--/****** Object:  View [dbo].[VW_RPT_ITEMLOTMASTERCODE]    Script Date: 6/28/2021 2:18:26 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO




CREATE OR ALTER VIEW [dbo].[VW_RPT_ITEMLOTMASTERCODE]
AS
SELECT
ROWID,
COMPANYID,
SHIPPERCODE,  
ITEMCODE, 
ALPHA   ,   
PLANTGROUP, 
GENUS      ,
SIZE       ,
PULLERRESPONSIBILITY ,
VARIETY    ,
QUALITY    ,
COMMONNAME  ,                                                                                                                                                                                                                                               
FIELDTAGCOLOR, 
GRADELABELCOLOR, 
SPECIFICATION ,
QUALITYORDER ,
SEASONYEAR ,
SPECPULLER ,
SUSPEND    ,
HSSTART     ,            
HS         ,
HSREASON    ,                                       
INVENTORYNOTE,                                      
SNSTART       ,          
SALESNOTE      ,                                    
PENDINGRECEIPTS ,                        
BACKORDERRECEIPTS,                       
INRECEIVING       ,                      
HSREASONSTART      ,     
HSREASONEND         ,    
INSTART              ,   
INEND                 ,  
F1,
S1,
U1,
F2,
S2,
U2,
F3,
S3,
U3,
LEFTTOSELL             ,                 
LOTCODE              ,
LOCATIONCODE         ,
SOURCE                ,                                                                                                                                                                                   
DESIGCUST              ,                                                                                                                                                                                  
DESIGITEM               ,                                                                                                                                                                                 
DESIGLOC                 ,                                                                                                                                                                                
PRIORITY                  ,                                                                                                                                                                               
ONHAND                     ,             
SHIPPINGQUANTITY            ,            
FUTUREEVAL                   ,                                                                                                                                                                            
LOCATIONNOTE                  ,                                                                                                                                                                           
LOCNOTEDATE                    ,                                                                                                                                                                          
BYPASSLOCATION                   ,   
LOCATIONPTN1,
LOCATIONPTN2,                                                                                                                                                                     
PTNOTE1,               
MCTYPE ,
SORT
FROM
(
SELECT  IMITEM.ROWID , IMITEM.COMPANYID, WH.IDENTITYID AS SHIPPERCODE,IMITEM.ITEMCODE,LOC.CLASSCODE AS ALPHA,
PC.PRODUCTCATEGORYCODE  AS PLANTGROUP,CI.DESCRIPTION_1  AS GENUS,LOT.CLASSCODE AS SIZE,
IMITEM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY,DP.PROFILECODE AS VARIETY,
IMITEM.SUBCLASSCODE AS QUALITY,IMITEM.REFERENCE_1 AS COMMONNAME, 
IMITEM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,IMITEM.USERDEFINEDCODE_11 AS GRADELABELCOLOR,
IMITEM.SPECIFICATIONCODE AS SPECIFICATION,

CASE 
WHEN IMITEM.SUBCLASSCODE ='1' THEN '1'
WHEN IMITEM.SUBCLASSCODE ='2' THEN '2'
WHEN IMITEM.SUBCLASSCODE ='3' THEN '3'
WHEN IMITEM.SUBCLASSCODE ='4' THEN '4'
WHEN IMITEM.SUBCLASSCODE ='0' THEN '5'
END AS QUALITYORDER,
LOT.USERDEFINEDCODE_6 AS SEASONYEAR,
LOT.USERDEFINEDCODE_4 AS SPECPULLER,
CASE WHEN LOT.USERDEFINEDCODE_5 = 'SUSPEND' THEN 'Y' ELSE LOT.USERDEFINEDCODE_5 END AS SUSPEND,
LOT.USERDEFINEDDATE_1 AS HSSTART,LOT.USERDEFINEDCODE_3 AS HS,
LOT.USERDEFINEDREFERENCE_4 AS HSREASON,LOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE,
LOT.USERDEFINEDDATE_6 AS SNSTART,LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
LOT.IN_ORDERED AS PENDINGRECEIPTS, LOT.IN_BACKORDER AS BACKORDERRECEIPTS, 
LOT.IN_RECEIVING AS INRECEIVING,
LOT.USERDEFINEDDATE_4 AS HSREASONSTART,LOT.USERDEFINEDDATE_5 AS HSREASONEND,
LOT.USERDEFINEDDATE_8 AS INSTART,LOT.USERDEFINEDDATE_9 AS INEND,


CASE WHEN LOT.USERDEFINEDCODE_10 ='F1' THEN LOT.NETAVAILABLE ELSE 0 END AS F1,
CASE WHEN LOT.USERDEFINEDCODE_10 ='S1' THEN LOT.NETAVAILABLE ELSE 0 END AS S1,
CASE WHEN LOT.USERDEFINEDCODE_10 ='U1' THEN LOT.NETAVAILABLE ELSE 0 END AS U1,
CASE WHEN LOT.USERDEFINEDCODE_10 ='F2' THEN LOT.NETAVAILABLE ELSE 0 END AS F2,
CASE WHEN LOT.USERDEFINEDCODE_10 ='S2' THEN LOT.NETAVAILABLE ELSE 0 END AS S2,
CASE WHEN LOT.USERDEFINEDCODE_10 ='U2' THEN LOT.NETAVAILABLE ELSE 0 END AS U2,
CASE WHEN LOT.USERDEFINEDCODE_10 ='F3' THEN LOT.NETAVAILABLE ELSE 0 END AS F3,
CASE WHEN LOT.USERDEFINEDCODE_10 ='S3' THEN LOT.NETAVAILABLE ELSE 0 END AS S3,
CASE WHEN LOT.USERDEFINEDCODE_10 ='U3' THEN LOT.NETAVAILABLE ELSE 0 END AS U3,

CASE 
WHEN LOT.USERDEFINEDCODE_10 ='F1' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='S1' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='U1' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='F2' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='S2' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='U2' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='F3' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='S3' THEN LOT.NETAVAILABLE
WHEN LOT.USERDEFINEDCODE_10 ='U3' THEN LOT.NETAVAILABLE ELSE 0
END AS LEFTTOSELL,
LOT.LOTCODE,
LOC.LOCATIONCODE, 
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='SOURCE' AND MCA.R_MASTERCODE=MC.ROWID ),'')
NULL AS SOURCE,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='DESIGCUST' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS DESIGCUST,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='DESIGITEM' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS DESIGITEM,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='DESIGLOC' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS DESIGLOC,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS PRIORITY,
--ISNULL(MC.PRODUCTIONQUANTITY,0) 
NULL AS ONHAND,
--ISNULL((SELECT SUM(ISNULL(IA.COMMITTEDQUANTITY,0)) FROM OMREVIEWINVENTORYASSIGNMENT IA
--LEFT JOIN OMTRANSACTIONDETAIL D ON D.ROWID =IA.R_TRANSACTIONDETAIL 
--WHERE D.RECORDTYPE='R' AND IA.R_MASTERCODE=MC.ROWID),0) 
NULL AS SHIPPINGQUANTITY,
--AVAILABLE = ONHAND - SHIPPING
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='FUTURE EVAL' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS FUTUREEVAL,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='LOCATION NOTE' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS LOCATIONNOTE,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='LOCNOTEDATE' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS LOCNOTEDATE,
--ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
--LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
--WHERE A.NAME ='BYPASSLOC' AND MCA.R_MASTERCODE=MC.ROWID ),'') 
NULL AS BYPASSLOCATION,
NULL AS LOCATIONPTN1,
NULL AS LOCATIONPTN2,
LOT.USERDEFINEDREFERENCE_1 AS PTNOTE1,
'LOT' AS MCTYPE,
 LOT.LOTCODE AS SORT

FROM IMITEM 
LEFT JOIN VW_IMLOTVIEW LOT ON LOT.R_ITEM= IMITEM.ROWID
LEFT JOIN OMREVIEWMASTERCODES MC ON MC.R_LOT=LOT.ROWID
LEFT JOIN IMITEMDP DP ON DP.ROWID = IMITEM.R_PROFILE
LEFT JOIN IMLOCATION LOC ON LOC.ROWID=MC.R_LOCATION
LEFT JOIN IDCODES CD ON CD.CODE = LOC.CLASSCODE AND CD.CODETYPE='26'
LEFT JOIN IDCODES CI ON CI.CODE = IMITEM.USERDEFINEDCODE_1 AND CI.CODETYPE = '11'
LEFT JOIN IDMASTER WH ON WH.ROWID = IMITEM.R_WAREHOUSE
LEFT JOIN IMPRODUCTCATEGORY PC ON PC.ROWID =IMITEM.R_PRODUCTCATEGORY

UNION ALL
SELECT  IMITEM.ROWID , IMITEM.COMPANYID, WH.IDENTITYID AS SHIPPERCODE,IMITEM.ITEMCODE,LOC.CLASSCODE AS ALPHA,
PC.PRODUCTCATEGORYCODE  AS PLANTGROUP,CI.DESCRIPTION_1 AS GENUS,LOT.CLASSCODE AS SIZE,
IMITEM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY,DP.PROFILECODE AS VARIETY,
IMITEM.SUBCLASSCODE AS QUALITY,IMITEM.REFERENCE_1 AS COMMONNAME, 
IMITEM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,IMITEM.USERDEFINEDCODE_11 AS GRADELABELCOLOR,
IMITEM.SPECIFICATIONCODE AS SPECIFICATION,

CASE 
WHEN IMITEM.SUBCLASSCODE ='1' THEN '1'
WHEN IMITEM.SUBCLASSCODE ='2' THEN '2'
WHEN IMITEM.SUBCLASSCODE ='3' THEN '3'
WHEN IMITEM.SUBCLASSCODE ='4' THEN '4'
WHEN IMITEM.SUBCLASSCODE ='0' THEN '5'
END AS QUALITYORDER,
LOT.USERDEFINEDCODE_6 AS SEASONYEAR,
LOT.USERDEFINEDCODE_4 AS SPECPULLER,
CASE WHEN LOT.USERDEFINEDCODE_5 = 'SUSPEND' THEN 'Y' ELSE LOT.USERDEFINEDCODE_5 END AS SUSPEND,
LOT.USERDEFINEDDATE_1 AS HSSTART,LOT.USERDEFINEDCODE_3 AS HS,
LOT.USERDEFINEDREFERENCE_4 AS HSREASON,LOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE,
LOT.USERDEFINEDDATE_6 AS SNSTART,LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
LOT.IN_ORDERED AS PENDINGRECEIPTS, LOT.IN_BACKORDER AS BACKORDERRECEIPTS, 
LOT.IN_RECEIVING AS INRECEIVING,
LOT.USERDEFINEDDATE_4 AS HSREASONSTART,LOT.USERDEFINEDDATE_5 AS HSREASONEND,
LOT.USERDEFINEDDATE_8 AS INSTART,LOT.USERDEFINEDDATE_9 AS INEND,

--CASE 
--WHEN LOT.USERDEFINEDCODE_10 ='F1' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='S1' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='U1' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='F2' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='S2' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='U2' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='F3' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='S3' THEN LOT.NETAVAILABLE
--WHEN LOT.USERDEFINEDCODE_10 ='U3' THEN LOT.NETAVAILABLE ELSE 0
--END AS 
0 AS F1,
0 AS S1,
0 AS U1,
0 AS F2,
0 AS S2,
0 AS U2,
0 AS F3,
0 AS S3,
0 AS U3,
1 AS LEFTTOSELL,
LOT.LOTCODE,LOC.LOCATIONCODE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='SOURCE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS SOURCE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGCUST' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGCUST,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGITEM' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGITEM,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGLOC' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGLOC,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS PRIORITY,
ISNULL(OMREVIEWMASTERCODES.PRODUCTIONQUANTITY,0) AS ONHAND,
ISNULL((SELECT SUM(ISNULL(IA.COMMITTEDQUANTITY,0)) FROM OMREVIEWINVENTORYASSIGNMENT IA
LEFT JOIN OMTRANSACTIONDETAIL D ON D.ROWID =IA.R_TRANSACTIONDETAIL 
WHERE D.RECORDTYPE='R' AND IA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID),0) AS SHIPPINGQUANTITY,
--AVAILABLE = ONHAND - SHIPPING
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='FUTURE EVAL' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS FUTUREEVAL,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATION NOTE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONNOTE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCNOTEDATE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCNOTEDATE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='BYPASSLOC' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS BYPASSLOCATION,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATIONPTN1' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONPTN1,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATIONPTN2' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONPTN2,
LOT.USERDEFINEDREFERENCE_1 AS PTNOTE1,
'MC' AS MCTYPE,
LOC.LOCATIONCODE AS SORT

FROM OMREVIEWMASTERCODES --IMITEM 
JOIN IMITEM ON IMITEM.ROWID = OMREVIEWMASTERCODES.R_ITEM
JOIN VW_IMLOTVIEW LOT ON LOT.ROWID = OMREVIEWMASTERCODES.R_LOT  --ITEMIMITEM.ROWID
--LEFT JOIN OMREVIEWMASTERCODES MC ON MC.R_LOT=LOT.ROWID
LEFT JOIN IMITEMDP DP ON DP.ROWID = IMITEM.R_PROFILE
LEFT JOIN IMLOCATION LOC ON LOC.ROWID=OMREVIEWMASTERCODES.R_LOCATION
LEFT JOIN IDCODES CD ON CD.CODE = LOC.CLASSCODE AND CD.CODETYPE='26'
LEFT JOIN IDCODES CI ON CI.CODE = IMITEM.USERDEFINEDCODE_1 AND CI.CODETYPE='11'
LEFT JOIN IDMASTER WH ON WH.ROWID = IMITEM.R_WAREHOUSE
LEFT JOIN IMPRODUCTCATEGORY PC ON PC.ROWID =IMITEM.R_PRODUCTCATEGORY
) AS ITEMVIEW WHERE LEFTTOSELL <> 0
GO

