--USE [ABECAS_CUST_GNC_TEST]
--GO

--/****** Object:  View [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]    Script Date: 11/2/2020 6:18:59 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

ALTER VIEW [dbo].[VW_AVAILABLELOADSLISTINGVIEW]
AS


SELECT TRIPNO,CONVERT(DATE,PLANSTART) AS TRIPDATE,FORMAT(PLANSTART,'hh:mm') AS TRIPTIME,
ISNULL(H.MILESUNLOADED,0) + ISNULL(H.MILESLOADED ,0) AS TOTALMILES, 
H.STATUS,
ISNULL((SELECT TOP 1 SPOPENITEMS.RATE FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = H.ROWID AND FC.CHARGECODE ='RATE/MILE'),0) AS RATEPERMILE ,
ISNULL((SELECT SUM(AMOUNT) FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = H.ROWID AND FC.CHARGECODE ='RATE/MILE'),0) AS TOTALRATEPERMILE ,
ISNULL((SELECT SUM(AMOUNT) FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = H.ROWID AND FC.CHARGECODE ='DROPPAY'),0) AS TOTALSTOPPAY  ,
ISNULL((SELECT SUM(AMOUNT) FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = H.ROWID ),0) AS FREIGHTEXP,
D.DELSTOPNO AS STOPNO,CV.CONSIGNEECITY,CV.CONSIGNEESTATE,
C.IDENTITYID AS CARRIERCODE,SP.NAME SALESPERSONNAME ,SP.IDENTITYID SALESPERSONCODE,OMTH.COMMENT AS ORDERSHIPPINGINSTR,
H.COMPANYID,SV.ShipperIdentityID  AS SHIPPERCODE,SV.SHIPPERNAME AS SHIPPERNAME,
SV.SHIPPERCITY AS SHIPPERCITY,SV.SHIPPERSTATE AS SHIPPERSTATE,SV.SHIPPERZIP ,
SV.ShipperAddress_1  AS SHIPPERADDRESS,SV.SHIPPERTELEPHONE_1 ,SV.SHIPPERTELEPHONE_2,
SV.SHIPPERPAGER_2 AS DISPATCHERPHONENO
FROM FMTRIPHEADER H (NOLOCK)
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_TRIPHEADER = H.ROWID
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID= D.R_FMDISPATCHOBJECT 
LEFT JOIN OMTRANSACTIONHEADER OMTH (NOLOCK) ON OMTH.ROWID=DO.R_SOURCEID
LEFT JOIN VW_IDCONSIGNEEVIEW CV (NOLOCK) ON CV.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE
LEFT JOIN VW_IDSHIPPERVIEW SV (NOLOCK) ON SV.SHIPPERMASTERROWID= H.R_ORIGIN
LEFT JOIN IDMASTER C (NOLOCK) ON C.ROWID = H.R_CARRIER
LEFT JOIN IDMASTER SP ON SP.ROWID = OMTH.R_SALESPERSON_1
WHERE H.RECORDTYPE <>'P'

GO
