--USE [ABECAS_CUST_GNC_TEST]
--GO
ALTER VIEW VW_BLOCKPRIORIRTYSCREENVIEW
AS

SELECT WH.IDENTITYID AS DIVISION,ITEM.ITEMCODE,LOT.LOTCODE,CNT.CONTAINERCODE AS CONTAINER, CNT.PRINTEDCONTAINERCODE AS CONTAINERCODE,
ITEM.REFERENCE_1 AS COMMONNAME,
ISNULL((SELECT VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS PRIORITY,
LOT.USERDEFINEDCODE_3 AS HOLDSTOP, ISNULL(LOT.USERDEFINEDDATE_1,'') AS DATESTART,
ISNULL(DATEDIFF(day, LOT.USERDEFINEDDATE_1,getdate() ),0) AS DAYONHS,LOC.SUBCLASSCODE AS GROWER,
LOC.LOCATIONCODE ,
ISNULL((SELECT VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='SOURCE' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS SOURCE,
ISNULL((SELECT VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGCUST' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGCUSTOMER,
ISNULL((SELECT VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGITEM' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGITEM,
ISNULL((SELECT VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGLOC' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGLOCATION,
ISNULL(MC.PRODUCTIONQUANTITY,0) AS QTY,ISNULL(ITEM.PRICELEVELA,0) AS EXTENDEDLIST,
ITEM.SPECIFICATIONCODE AS STANDARDSPEC,ISNULL(CONVERT(DATE,LOT.USERDEFINEDDATE_6),'') AS NOTEBEGINDATE,
LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,C.DESCRIPTION_1 AS GROWERNAME
FROM IMITEM ITEM (NOLOCK) 
LEFT JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON  MC.R_ITEM = ITEM.ROWID
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID= MC.R_LOT
LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID=MC.R_LOCATION 
LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID=ITEM.R_CONTAINERCODE
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITEM.R_WAREHOUSE
LEFT JOIN IMCODES C (NOLOCK) ON C.CODE=LOC.SUBCLASSCODE AND C.CODETYPE='27'

GO