

--/****** Object:  View [dbo].[VW_CROPRELEASEREPORT]    Script Date: 6/14/2021 5:56:48 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


---HEADER
CREATE OR ALTER VIEW [dbo].[VW_CROPRELEASEREPORT]
AS
---SYSTEM
SELECT IMITEM.ITEMCODE,
IMITEM.REFERENCE_1 AS COMMONNAME, 
LOT.USERDEFINEDCODE_6 AS SALESYEAR ,
CT.CONTAINERSORT as CONTAINERSORT,
S.IDENTITYID AS SHIPPERCODE,
IPC.PRODUCTCATEGORYCODE AS PLANTGORUP,
IMITEM.SUBCLASSCODE AS QUALITY,
IMITEM.CLASSCODE AS CONTAINER,
IMITEM.USERDEFINEDCODE_1 AS GENUS,
LOT.LOTCODE,
IMITEM.COMPANYID AS COMPANYID,
IMITEM.REFERENCE_5 AS VARIETYSORT,


(SELECT TOP 1 PRICELEVEL_A FROM IMPRICECODESSUBDETAIL (NOLOCK)
JOIN IMPRICECODESDETAIL (NOLOCK) ON IMPRICECODESSUBDETAIL.R_PRICECODEDETAIL = IMPRICECODESDETAIL.ROWID
AND IMPRICECODESDETAIL.R_PRICECODEHEADER = IMITEM.R_PRICETABLE
WHERE IMPRICECODESDETAIL.EFFECTIVEDATE <= GETDATE()
ORDER BY IMPRICECODESDETAIL.EFFECTIVEDATE DESC) AS PRICELEVELA,

(SELECT ISNULL(SUM(ISNULL(D.QUANTITY,0)),0) FROM IMTRANSACTIONDETAIL D (NOLOCK)
JOIN IMTRANSACTIONHEADER H (NOLOCK) ON H.ROWID = D.R_TRANSACTIONHEADER
WHERE D.R_ITEM = IMITEM.ROWID AND D.R_LOT = LOT.ROWID 
--AND D.USERDEFINEDCODE_1 = 'NCRELEASE' AND H.RECORDTYPE = 'Z'
AND D.USERDEFINEDCODE_1 IN ('NCRELEASE','NEWCROPREV') AND H.RECORDTYPE = 'Z'
and d.quantity > 0
) AS NCR_IN,

(SELECT ISNULL(SUM(ISNULL(D.QUANTITY,0)),0) FROM IMTRANSACTIONDETAIL D (NOLOCK)
JOIN IMTRANSACTIONHEADER H (NOLOCK) ON H.ROWID = D.R_TRANSACTIONHEADER
WHERE D.R_ITEM = IMITEM.ROWID AND D.R_LOT = LOT.ROWID 
--AND D.USERDEFINEDCODE_1 = 'NCRELEASE' AND H.RECORDTYPE = 'Z'
AND D.USERDEFINEDCODE_1 IN ('NCRELEASE','NEWCROPREV') AND H.RECORDTYPE = 'Z'
and d.quantity < 0
) AS NCR_OUT,


(SELECT ISNULL(SUM(ISNULL(OMREVIEWINVENTORYASSIGNMENT.COMMITTEDQUANTITY,0)),0)
FROM OMREVIEWINVENTORYASSIGNMENT  (NOLOCK)
JOIN OMREVIEWMASTERCODES (NOLOCK) ON OMREVIEWMASTERCODES.ROWID = OMREVIEWINVENTORYASSIGNMENT.R_MASTERCODE 
JOIN OMREVIEWMASTERCODEATTRIBUTES (NOLOCK) ON OMREVIEWMASTERCODES.ROWID = OMREVIEWMASTERCODEATTRIBUTES.R_MASTERCODE
AND OMREVIEWMASTERCODEATTRIBUTES.R_ATTRIBUTE = (SELECT ROWID FROM OMREVIEWATTRIBUTES (NOLOCK) WHERE NAME = 'DESIGITEM')
AND OMREVIEWMASTERCODEATTRIBUTES.VALUE = '='
JOIN IMTRANSACTIONLOCATION (NOLOCK) ON IMTRANSACTIONLOCATION.ROWID = OMREVIEWINVENTORYASSIGNMENT.R_IMTRANSACTIONLOCATION
JOIN OMTRANSACTIONDETAIL (NOLOCK) ON OMTRANSACTIONDETAIL.ROWID = IMTRANSACTIONLOCATION.R_TRANSACTIONDETAIL
JOIN OMTRANSACTIONHEADER (NOLOCK) ON OMTRANSACTIONDETAIL.R_TRANSACTIONHEADER = OMTRANSACTIONHEADER.ROWID
WHERE OMTRANSACTIONHEADER.RECORDTYPE = 'Z' 
AND OMREVIEWMASTERCODES.R_ITEM = IMITEM.ROWID AND OMREVIEWMASTERCODES.R_LOT = LOT.ROWID 
AND OMTRANSACTIONHEADER.INVOICEDATE BETWEEN CONVERT(VARCHAR(4),CONVERT(INTEGER,LOT.USERDEFINEDCODE_6)-1)+'-08-01' AND LOT.USERDEFINEDCODE_6+'-07-31' ) AS UNITSHIPPED


FROM IMITEM (NOLOCK) 
  JOIN IMLOT LOT (NOLOCK) ON IMITEM.ROWID = LOT.R_ITEM
  JOIN IMPRODUCTCATEGORY IPC (NOLOCK) ON IPC.ROWID= IMITEM.R_PRODUCTCATEGORY
  LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = IMITEM.R_WAREHOUSE
  LEFT JOIN IMCONTAINER CT (NOLOCK) on CT.ROWID = IMITEM.R_CONTAINERCODE
 
GO


