--TESTING THE VIEW FOR CHANGES MADE:
--SELECT * FROM VW_DAILYSHIPPINGSCHEDULEEXCELVIEW WHERE LOADNUMBER = 'T10529'
--SELECT * FROM VW_DAILYSHIPPINGSCHEDULEEXCELVIEW WHERE R_TRAILER IS NOT NULL
--SELECT * FROM fmtripheader WHERE tripno = 'T10529'

--SELECT LOADDATE, LOADNUMBER, TRANSACTIONNUMBER, MERCHANDISETOTAL, STOPMERCHANDISETOTAL FROM VW_DAILYSHIPPINGSCHEDULEEXCELVIEW WHERE SHIPPERCODE = '10' AND LOADDATE BETWEEN '04/07/2024' AND '04/13/2024' ORDER BY LOADNUMBER

CREATE OR ALTER VIEW [dbo].[VW_DAILYSHIPPINGSCHEDULEEXCELVIEW]
AS
SELECT 
WH.IDENTITYID AS SHIPPERCODE, 
TH.TRIPNO AS LOADNUMBER, 
TH.PLANSTART AS LOADDATE, 
ISNULL(TH.USERDEFINEDCODE_2,'') AS DOCKNUMBER, 
ISNULL(CARR.NAME,'') AS TRUCKINGCOMPANY, 
TD.DELSTOPNO AS DROPNUMBER, 
TH.STATUS, 
'DONT KNOW' AS SHIPCARRIERDESCRIPTION, 
VCONS.CONSIGNEENAME AS CUSTOMERNAME, 
VCONS.CONSIGNEEADDRESS_1 AS ADDRESS, 
VCONS .CONSIGNEESTATE AS STATE, 
TH.COMMENT AS SPECIALINSTRUCTIONS, 
TRIM(REPLACE(SUBSTRING(OH.COMMENT,1,200),CHAR(13)+CHAR(10), '') ) AS SHIPPINGINSTRUCTIONS, 
ISNULL(PART.IDENTITYID,'') AS SALESPERSON, 
OH.TRANSACTIONNUMBER, 
(	SELECT ISNULL(SUM(ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0))),0) 
	FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
	LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=OD.R_TRANSACTIONHEADER 
	LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= OH.ROWID 
	LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_FMDISPATCHOBJECT = DO.ROWID 
	LEFT JOIN FMTRIPHEADER (NOLOCK) ON FMTRIPHEADER.ROWID  = TD.R_TRIPHEADER 
	WHERE TH.ROWID = FMTRIPHEADER.ROWID 
	) AS MERCHANDISETOTAL, 
	--------------------------
	--DBO.FN_ORDERVALUE(OH.ROWID,'UNITPRICE') AS STOPMERCHANDISETOTAL2, --ALTERNATE WAY TO GET STOPMERCHTOTAL
	--------------------------
(	SELECT ISNULL(SUM(ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0))),0) 
	FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
	WHERE OD.R_TRANSACTIONHEADER = OH.ROWID
	) AS STOPMERCHANDISETOTAL, 
(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) 
	FROM OMFREIGHT FRT (NOLOCK) 
	LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=FRT.R_TRANSACTIONHEADER 
	LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= OH.ROWID 
	LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_FMDISPATCHOBJECT = DO.ROWID 
	LEFT JOIN FMTRIPHEADER (NOLOCK) ON FMTRIPHEADER.ROWID  = TD.R_TRIPHEADER 
	WHERE TH.ROWID = FMTRIPHEADER.ROWID 
	) AS FREIGHTCHARGEAMOUNT, 
(	SELECT ISNULL(SUM(ISNULL(FMDISPATCHOBJECT.WEIGHTORDERED,0)),0) 
	FROM FMDISPATCHOBJECT (NOLOCK) 
	LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_FMDISPATCHOBJECT = FMDISPATCHOBJECT.ROWID 
	LEFT JOIN FMTRIPHEADER (NOLOCK) ON FMTRIPHEADER.ROWID = TD.R_TRIPHEADER 
	WHERE TH.ROWID = FMTRIPHEADER.ROWID 
	) AS ORDERWEIGHT, 
(	SELECT ISNULL(SUM(ISNULL(FMDISPATCHOBJECT.CUBESORDERED,0)),0) 
	FROM FMDISPATCHOBJECT (NOLOCK) 
	LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_FMDISPATCHOBJECT = FMDISPATCHOBJECT.ROWID 
	LEFT JOIN FMTRIPHEADER (NOLOCK) ON FMTRIPHEADER.ROWID = TD.R_TRIPHEADER 
	WHERE TH.ROWID = FMTRIPHEADER.ROWID 
	) AS ORDERVOLUME, 
	--CASE WH.IDENTITYID
	--	WHEN 10 THEN ICONS.USERDEFINEDREFERENCE_8
	--	WHEN 20 THEN ICONS.USERDEFINEDREFERENCE_9
	--	WHEN 40 THEN ICONS.USERDEFINEDREFERENCE_10
	--	WHEN 60 THEN ICONS.USERDEFINEDREFERENCE_11
	--	ELSE NULL
	--END AS LOADINSTRUCTIONS,	--PERMSHIPNOTES 
	ICONS.COMMENT AS GENLOADINSTR, --PERMSHIPNOTES AKA GENLOADINSTR PER SC 
	--NEW FIELDS ADDED AT REQUEST OF TREE	--01/17/23 DT 
	(SELECT EQUIPMENTID FROM IDEQUIPMENT EQ (NOLOCK) WHERE EQ.ROWID = TH.R_TRAILER) AS TRAILERNUMBER, 
	TH.TRAILERREFERENCE, 
	TRIM(REPLACE(SUBSTRING(TH.COMMENT,1,200),CHAR(13)+CHAR(10), '') ) AS TRIPNOTES, 
	VCONS.CONSIGNEEIDENTITYID, 
	VCONS.CONSIGNEENAME, 
	VCONS.CONSIGNEEADDRESS_1, 
	VCONS.CONSIGNEEADDRESS_2, 
	VCONS.CONSIGNEECITY, 
	VCONS.CONSIGNEESTATE, 
	VCONS.CONSIGNEEZIP, 
	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ) AS ALTSHIPCOMMENT,	--ALTSHIPCOMMENT 
	NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-') AS SHIPTOTELEPHONE_1		--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
FROM FMTRIPHEADER TH (NOLOCK)
LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_TRIPHEADER = TH.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID= TD.R_FMDISPATCHOBJECT
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER 
LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = TH.R_CARRIER
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=DO.R_SOURCEID
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = DO.R_CONSIGNEE
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1



WHERE TH.RECORDTYPE <>'P'
