--USE [ABECAS_CUST_GNC_TEST]
--GO
CREATE OR ALTER VIEW [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]
AS
SELECT 
TH.TRIPNO,
TH.PLANSTART, CAST (TH.PLANSTART AS DATE) AS DATESORT, 
TH.ACTUALSTART, 
DO.TRACKINGNUMBER,
TH.STATUS, 
TH.USERDEFINEDCODE_2 AS DOCKNUMBER, 
TD.DELSTOPNO, 
VCONS.CONSIGNEEIDENTITYID, 
VCONS.CONSIGNEENAME, 
ISNULL(DO.WEIGHTORDERED,0) AS WEIGHTORDERED, 
ISNULL(DO.CUBESORDERED,0) AS VOLUME, 
VCONS.CONSIGNEECITY, 
VCONS.CONSIGNEESTATE, 
TH.EQUIPMENT AS TRUCKTYPE, 
CARR.IDENTITYID AS CARRIERCODE, 
CARR.NAME AS CARRIERNAME, 
PART.NAME SALESPERSONNAME, 
PART.IDENTITYID SALESPERSONCODE, 
OH.COMMENT AS ORDERSHIPPINGINSTR, 
TH.COMPANYID, 
TH.COMMENT AS TRIPNOTE, 
VCONS.CONSIGNEECOMMENT, 
VCONS.CONSIGNEEMASTERCOMMENT, 
WH.IDENTITYID AS SHIPPERCODE, 
ICONS.USERDEFINEDCODE_11 AS QACODE, 
TRAIL.DESCRIPTION AS GNCTRAILERNO, --REPLACES: TRAIL.EQUIPMENTID AS GNCTRAILERNO, 
TRUCK.DESCRIPTION AS GNCTRUCKNO, 
TH.TRUCKREFERENCE AS CONTRACTTRUCKNO, 
TH.TRAILERREFERENCE AS CONTRACTTRAILERNO, 
DRIV.NAME AS GNCDRIVER, --REPLACES: DRIV.IDENTITYID AS GNCDRIVER, 
TH.DRIVERREFERENCE, 
TH.USERDEFINEDREFERENCE_1 AS CONTRACTDRIVER, 
TH.USERDEFINEDREFERENCE_2 AS DRIVERPHONE, 
CASE WH.IDENTITYID
	WHEN 10 THEN ICONS.USERDEFINEDREFERENCE_8
	WHEN 20 THEN ICONS.USERDEFINEDREFERENCE_9
	WHEN 40 THEN ICONS.USERDEFINEDREFERENCE_10
	WHEN 60 THEN ICONS.USERDEFINEDREFERENCE_11
	ELSE NULL
END AS LOADINTSTRUCTIONS,	--PERMSHIPNOTES, 
--VCONS.CONSIGNEEUSERDEFINEDREF_7 AS CONSIGNEESHIPNOTE,
--VCONS.CONSIGNEEDIRECTIONS AS DRIVERDIRECTIONS,
TD.COMMENT AS STOPNOTES 
FROM FMTRIPHEADER TH (NOLOCK) 
LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_TRIPHEADER = TH.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID= TD.R_FMDISPATCHOBJECT 
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=DO.R_SOURCEID 
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY=DO.R_CONSIGNEE 
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE 
LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = TH.R_CARRIER 
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER 
LEFT JOIN IDMASTER DRIV (NOLOCK) ON DRIV.ROWID = TH.R_DRIVER 
LEFT JOIN IDEQUIPMENT TRAIL (NOLOCK) ON TRAIL.ROWID=TH.R_TRAILER 
LEFT JOIN IDEQUIPMENT TRUCK (NOLOCK) ON TRUCK.ROWID=TH.R_TRUCK 
WHERE TH.RECORDTYPE<>'P' 

