--USE [ABECAS_CUST_GNC_TEST] 
--GO

--/****** Object:  View [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]    Script Date: 11/2/2020 6:18:59 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

ALTER VIEW [dbo].[VW_FREIGHTPROFITBYCUSTOMERVIEW]
AS

SELECT H.PLANSTART ,H.ACTUALSTART,S.IDENTITYID AS SHIPPERCODE,S.NAME AS SHIPPERNAME,H.TRIPNO, 
 ISNULL(CONS.CONSIGNEEUSERDEFINEDCODE_3,'') AS CUSTOMERTYPE,'1' AS DROPCOUNT,ISNULL(CUST.CustomerUserDefinedCode_8,'N') AS CUSTOMERGROUP,
 H.STATUS,
(SELECT  ISNULL(SUM(ISNULL(FMDISPATCHOBJECT.CUBESORDERED,0)),0) FROM FMDISPATCHOBJECT (NOLOCK)
LEFT JOIN FMTRIPDETAIL (NOLOCK) ON FMTRIPDETAIL.R_FMDISPATCHOBJECT = FMDISPATCHOBJECT.ROWID
LEFT JOIN FMTRIPHEADER (NOLOCK) ON FMTRIPHEADER.ROWID=FMTRIPDETAIL.R_TRIPHEADER
WHERE FMTRIPHEADER .ROWID =H.ROWID )AS TOTALVOLUME,
ISNULL(DO.CUBESORDERED,0)  AS VOLUME,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
WHERE SPOPENITEMS.R_SOURCEID = H.ROWID ) AS TOTALFREIGHTEXPENSE,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID=F.R_TRANSACTIONHEADER
WHERE DO.R_SOURCEID= TH.ROWID AND D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = H.ROWID) AS FREIGHTREVENUE
-- FREIGHTEXPENSE = (VOLUME / TOTALVOLUME) * TOTALFREIGHTEXPENSE

-- AVG FREIGHT PROFIT / DROPCOUNT
FROM FMTRIPHEADER H (NOLOCK)
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_TRIPHEADER = H.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID =D.R_FMDISPATCHOBJECT 
LEFT JOIN VW_IDCUSTOMERVIEW  CUST (NOLOCK) ON CUST.CUSTOMERMASTERROWID =DO.R_CUSTOMER 
LEFT JOIN VW_IDCONSIGNEEVIEW  CONS (NOLOCK) ON CONS.CONSIGNEEMASTERROWID =DO.R_CONSIGNEE 
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID=H.R_ORIGIN 
WHERE H.RECORDTYPE <>'P'
GROUP BY 
CONS.CONSIGNEEUSERDEFINEDCODE_3 ,H.ROWID ,H.STATUS,H.PLANSTART ,H.ACTUALSTART,S.IDENTITYID,S.NAME,H.TRIPNO,
DO.R_SOURCEID,D.R_FMDISPATCHOBJECT,DO.ROWID, D.R_TRIPHEADER  ,D.ROWID,CUST.CustomerUserDefinedCode_8,DO.CUBESORDERED
GO
