--USE [ABECAS_CUST_GNC_TEST] 
--GO

--/****** Object:  View [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]    Script Date: 11/2/2020 6:18:59 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

ALTER VIEW [dbo].[VW_FREIGHTPROFITBYDROPVIEW]
AS

SELECT CONVERT(DATE,FMTRIPHEADER.PLANSTART) AS TRIPDATE, FMTRIPHEADER.TRIPNO AS TRIPNUMBER,ISNULL(FMTRIPHEADER.EQUIPMENT,'') AS TRUCKTYPE,
FMTRIPHEADER.STATUS ,FMTRIPHEADER.ACTUALSTART,S.IDENTITYID AS SHIPPERCODE, S.NAME AS SHIPPERNAME,
ISNULL(FMTRIPHEADER.MILESLOADED,0) as LOADEDMILES,
--New Miles field added per DJ request - DT 6/29/21
	(	SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='RATE/MILE') AS TOTALLOADEDMILES,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='RATE/MILE') AS LOADEDMILESEXPENSE ,
--LOADED RATE/MILE = LOADEDMILESEXPENSE/LOADEDMILES

--Change calculation for STOPCOUNT per DJ request - DT 6/29/21
--(SELECT COUNT(KEYSEQUENCE) FROM FMTRIPDETAIL D (NOLOCK) WHERE D.R_TRIPHEADER= FMTRIPHEADER.ROWID) AS STOPCOUNT, 
	(SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
	LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
	WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='DROPPAY') AS STOPCOUNT, 

(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='DROPPAY') AS TOTALSTOPPAY  ,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='DHFEE') AS DEADHEADEXP,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER .ROWID AND FC.CHARGECODE ='FSMILES') AS FSCEXPENSE  ,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='RTMILES') AS RETURNMILESEXP,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='ADJUST') AS COSTADJUSTMENT, 
(SELECT ISNULL(SUM(ISNULL(HEADER.MILESUNLOADED,0) + ISNULL(HEADER.MILESLOADED,0)),0) 
FROM FMTRIPHEADER HEADER (NOLOCK) WHERE HEADER.ROWID = FMTRIPHEADER.ROWID )  AS TOTALMILES, 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID ) AS TOTALFREIGHTEXPENSE,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID=F.R_TRANSACTIONHEADER
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= TH.ROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = D.R_TRIPHEADER 
WHERE H.ROWID=FMTRIPHEADER.ROWID) AS TOTALFREIGHTREVENUE,
--FREIGHTPROFIT = FREIGHTREVENUEV - FREIGHTEXPENSE
(SELECT TOP 1 CV.CONSIGNEECITY FROM VW_IDCONSIGNEEVIEW  CV (NOLOCK) 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = CV.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
ORDER BY D.DELSTOPNO DESC) AS DESTINATIONCITY,
(SELECT TOP 1 CV.CONSIGNEESTATE  FROM VW_IDCONSIGNEEVIEW  CV (NOLOCK) 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = CV.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
ORDER BY D.DELSTOPNO DESC) AS LASTSTATE,
ISNULL(D.DELSTOPNO,0) AS STOPNUMBER, ISNULL(CV.CONSIGNEEIDENTITYID,'') AS CUSTOMER,ISNULL(CV.CONSIGNEENAME,'') AS CUSTOMERNAME,
ISNULL(CV.CONSIGNEECITY,'') AS CITY, ISNULL(CV.CONSIGNEESTATE,'') AS STATE,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
WHERE TH.ROWID=F.R_TRANSACTIONHEADER) AS FREIGHTREVENUE,
(SELECT ISNULL(SUM(ISNULL(CUBESORDERED,0)),0) FROM FMDISPATCHOBJECT DO (NOLOCK)
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID=D.R_TRIPHEADER
WHERE H.ROWID =FMTRIPHEADER.ROWID )AS TOTALVOLUME,
ISNULL(CUBESORDERED,0)  AS VOLUME
-- FREIGHTEXPENSE = VOLUME / TOTALVOLUME) * TOTALFREIGHTEXPENSE

-- FREIGHTPROFIT = FREIGHTREVENUE - FREIGHTEXPENSE
FROM FMTRIPHEADER (NOLOCK) 

LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_TRIPHEADER = FMTRIPHEADER.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID = D.R_FMDISPATCHOBJECT 
LEFT JOIN VW_IDCONSIGNEEVIEW CV (NOLOCK) ON CV.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE 
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID = DO.R_SOURCEID 
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = FMTRIPHEADER.R_ORIGIN
WHERE FMTRIPHEADER.RECORDTYPE <>'P'
GO
