--USE [ABECAS_CUST_GNC_TEST] 
--GO

--/****** Object:  View [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]    Script Date: 11/2/2020 6:18:59 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

CREATE OR ALTER VIEW [dbo].[VW_FREIGHTPROFITBYTRIPVIEW]
AS
SELECT FORMAT(FMTRIPHEADER.PLANSTART,'M/d/yy') AS TRIPDATE, FMTRIPHEADER.TRIPNO,FMTRIPHEADER.ACTUALSTART,
ISNULL(FMTRIPHEADER.EQUIPMENT,'') AS TRUCKTYPE,FMTRIPHEADER.STATUS,S.IDENTITYID AS SHIPPERCODE,S.NAME AS SHIPPERNAME,
(SELECT TOP 1 CV.CONSIGNEECITY FROM VW_IDCONSIGNEEVIEW  CV (NOLOCK)
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = CV.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
ORDER BY D.DELSTOPNO DESC) AS DESTINATIONCITY,
(SELECT TOP 1 CV.CONSIGNEESTATE  FROM VW_IDCONSIGNEEVIEW  CV (NOLOCK) 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = CV.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
ORDER BY D.DELSTOPNO DESC) AS LASTSTATE,
FC.CHARGECODE AS CHARGETYPE,SO.BASIS AS MILESBASIS,FC.DESCRIPTION AS MILESBASISTYPE,
ISNULL(SO.RATE,0) AS RATE ,ISNULL(SO.AMOUNT,0) AS AMOUNT,
ISNULL(FMTRIPHEADER.MILESUNLOADED,0) + ISNULL(FMTRIPHEADER.MILESLOADED,0) AS TOTALMILES,

----RATE EXT. = RATEPERMILE * TOTALMILES
-- FREIGHTEXPENSE = TOTAL OF ALL CHARGECODES

(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID=F.R_TRANSACTIONHEADER
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= TH.ROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID AND D.R_TRIPHEADER = FMTRIPHEADER.ROWID
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = D.R_TRIPHEADER 
WHERE H.ROWID=FMTRIPHEADER.ROWID) AS FREIGHTREVENUE

--FREIGHTPROFIT = FREIGHTREVENUE - FREIGHTEXPENSE


FROM FMTRIPHEADER (NOLOCK) 
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID=FMTRIPHEADER.R_ORIGIN
LEFT JOIN SPOPENITEMS SO (NOLOCK) ON SO.R_SOURCEID=FMTRIPHEADER.ROWID
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SO.R_FREIGHTCHARGE 
WHERE FMTRIPHEADER.RECORDTYPE <>'P'
GO
