--USE [ABECAS_CUST_GNC_TEST]
--GO

--/****** Object:  View [dbo].[VW_DAILYSHIPPINGSHEDULEDETAILVIEW]    Script Date: 11/2/2020 6:18:59 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

CREATE OR ALTER VIEW [dbo].[VW_HIREDTRUCKPAYMENTVIEW]
AS
SELECT 
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
WH.IDENTITYID AS WAREHOUSEID, 
WH.NAME AS WAREHOUSENAME, 
TH.TRIPNO, 
TH.PLANSTART, 
OBJ.TRACKINGNUMBER, 
TH.STATUS, 
TH.EQUIPMENT AS TRUCKTYPE, 
--CARR.IDENTITYID AS CARRIERCODE, 
CARR.NAME AS CARRIERNAME, 
TH.USERDEFINEDCODE_2 AS DOCKNUMBER, 
TRAIL.EQUIPMENTID AS GNCTRAILERNO, 
--TH.MILESUNLOADED, 
--TH.MILESLOADED, 
TRUCK.DESCRIPTION  AS GNCTRUCKNO, 
TH.TRUCKREFERENCE AS CONTRACTTRUCKNO, 
TH.TRAILERREFERENCE AS CONTRACTTRAILERNO, 
DRIV.IDENTITYID AS GNCDRIVER, 
TH.DRIVERREFERENCE, 
TH.USERDEFINEDREFERENCE_1 AS CONTRACTDRIVER, 
TH.USERDEFINEDREFERENCE_2 AS DRIVERPHONE, 
(SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RATE/MILE') AS TOTALLOADEDMILES, 
(SELECT TOP 1 ISNULL(SPOI.RATE,0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RATE/MILE') AS RATEPERMILE , 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RATE/MILE') AS EXTRATE , 
(SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RTMILES') AS TOTALRTMILES, 
(SELECT TOP 1 ISNULL(SPOI.RATE,0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RTMILES') AS RTNRATEPERMILE, 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RTMILES') AS EXTRTMILES, 
(SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='FSMILES') AS FSMILES, 
(SELECT TOP 1 ISNULL(SPOI.RATE,0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='FSMILES') AS FSMILESRATE, 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='FSMILES') AS EXTFSMILES, 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='DROPPAY') AS STOPPAY  , 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='DHFEE') AS DHFEE, 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='ADJUST') AS COSTADJUSTMENT  , 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS SPOI (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOI.R_FREIGHTCHARGE 
WHERE SPOI.R_SOURCEID = TH.ROWID ) AS FREIGHTEXPENSE , 
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0) ),0) FROM SPOPENITEMS SPOI (NOLOCK) 
WHERE SPOI.TRANSACTIONNUMBER = TH.TRIPNO 
AND SPOI.STATUS='Z' AND SPOI.TRANSACTIONTYPE IN ('A','P')) AS ADVANCE, 
--BALANCEDUE = FREIGHTEXPENSE - ADVANCE 
CONVERT(VARCHAR(255), TH.COMMENT) AS SPECIALINSTRUCTIONS, 
TD.DELSTOPNO AS STOPNUMBER, 
VCONS.CONSIGNEEIDENTITYID, 
VCONS.CONSIGNEENAME, 
CONVERT(VARCHAR(255),ISNULL(TD.COMMENT,'')) AS STOPNOTE, 
TRIM(VCONS.CONSIGNEEADDRESS_1) AS CONSIGNEEADDRESS_1, 
TRIM(VCONS.CONSIGNEEADDRESS_2) AS CONSIGNEEADDRESS_2, 
VCONS.CONSIGNEECITY, 
VCONS.CONSIGNEESTATE, 
VCONS.CONSIGNEEZIP, 
ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPPHONE 
		NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
	) AS CONSIGNEETELEPHONE_1,
OBJ.WEIGHTORDERED AS WEIGHT, 
OBJ.CUBESORDERED AS VOLUME, 
OH.TRANSACTIONNUMBER, 
CONT.IDENTITYID, 
CONT.NAME 

FROM FMTRIPHEADER TH (NOLOCK) 
LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_TRIPHEADER = TH.ROWID 
LEFT JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = TD.R_FMDISPATCHOBJECT 
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID 
LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = TH.R_CARRIER 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TH.R_ORIGIN 
LEFT JOIN IDMASTER DRIV (NOLOCK) ON DRIV.ROWID = TH.R_DRIVER 
LEFT JOIN IDEQUIPMENT TRAIL (NOLOCK) ON TRAIL.ROWID = TH.R_TRAILER 
LEFT JOIN IDEQUIPMENT TRUCK (NOLOCK) ON TRUCK.ROWID = TH.R_TRUCK 
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE 
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
LEFT JOIN IDMASTER CONT (NOLOCK) ON CONT.ROWID = DBO.FN_GETCONTACT(OH.R_SHIPPER,'02','C5')
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
WHERE TH.RECORDTYPE <>'P' 
