--USE [ABECAS_CUST_GNC_STRESSTEST]
--GO

--/****** Object:  View [dbo].[VW_ITEMINQUIRYMASTERCODES]    Script Date: 6/24/2021 12:37:18 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

CREATE OR ALTER VIEW [dbo].[VW_ITEMINQUIRYMASTERCODES]
AS 
SELECT LOT.LOTCODE,
ISNULL(LOC.LOCATIONCODE,'') AS LOCATIONCODE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='SOURCE' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS SOURCE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGCUST' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGCUST,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGITEM' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGITEM,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='DESIGLOC' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS DESIGLOC,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS PRIORITY,
ISNULL(SUM(ISNULL(MC.PRODUCTIONQUANTITY,0)),0) AS ONHAND,
ISNULL((SELECT SUM(ISNULL(IA.COMMITTEDQUANTITY,0)) FROM OMREVIEWINVENTORYASSIGNMENT IA
LEFT JOIN OMTRANSACTIONDETAIL D ON D.ROWID =IA.R_TRANSACTIONDETAIL 
WHERE D.RECORDTYPE='R' AND IA.R_MASTERCODE=MC.ROWID),0) AS SHIPPINGQUANTITY,
--AVAILABLE = ONHAND - SHIPPING
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATION NOTE' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS LOCATIONNOTE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='BYPASSLOC' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS BYPASSLOCATION,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATIONPTN2' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS LOCATIONPTN2,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCATIONPTN1' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS LOCATIONPTN1,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCNOTEDATE' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS LOCNOTEDATE,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='LOCHOLD' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS LOCHOLD,
ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA
LEFT JOIN OMREVIEWATTRIBUTES A ON A.ROWID = MCA.R_ATTRIBUTE 
WHERE A.NAME ='FUTURE EVAL' AND MCA.R_MASTERCODE=MC.ROWID ),'') AS FUTUREEVAL,
LOT.R_ITEM,LOT.USERDEFINEDCODE_6
FROM OMREVIEWMASTERCODES MC

LEFT JOIN IMLOT LOT ON MC.R_LOT = LOT.ROWID 
LEFT JOIN IMLOCATION LOC ON LOC.ROWID=MC.R_LOCATION 
GROUP BY LOT.LOTCODE,LOC.LOCATIONCODE,MC.ROWID,LOT.R_ITEM,LOT.USERDEFINEDCODE_6
GO


