-- NEGATIVE LOCATION REPORT	--BY ARGOS
/*
SELECT * 
FROM VW_NEGATIVELOCATIONVIEW 
WHERE PTR_ONHAND - PTR_REVIEWED < 0
AND WAREHOUSEID = '10'
--AND ITEMCODE = '006640.010.1'
ORDER BY WAREHOUSEID, PLANTGROUP, VARIETYSORTNAME, CONTAINERSORT, QUALITY
*/

CREATE OR ALTER VIEW [dbo].[VW_NEGATIVELOCATIONVIEW] 
AS 
SELECT 
CO.COMPANYID, 
CO.NAME AS COMPANYNAME, 
WH.IDENTITYID AS WAREHOUSEID, 
WH.NAME AS WAREHOUSENAME, 
LOT.USERDEFINEDCODE_6 AS SALEYEAR, 
ITM.REFERENCE_1 AS COMMONNAME, 
--ITM.DESCRIPTION_1 AS COMMONNAME2, 
ITM.ITEMCODE, 
PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
ITM.REFERENCE_5 AS VARIETYSORTNAME, 
CNT.CONTAINERSORT, 
ITM.SUBCLASSCODE AS QUALITY, 
CNT.PRINTEDCONTAINERCODE, 
ITM.CLASSCODE AS CONTAINERSIZE, 
LOT.LOTCODE, 
LOC.LOCATIONCODE AS LOCATION, 
LOT.USERDEFINEDCODE_3 AS HOLDSTOP, 
ITM.USERDEFINEDCODE_2 AS BRAND, 
ITM.USERDEFINEDCODE_12 AS [BRAND POT], 
--APPLY BRAND/POT DISPLAY LOGIC:
IIF	(	ISNULL(NULLIF(ITM.USERDEFINEDCODE_12, 'NONE'), '') = '', 
		ISNULL(ITM.USERDEFINEDCODE_2, ''), 
		ITM.USERDEFINEDCODE_12) AS BRANDTEXT, 
ITM.PRICELEVELA, 
(	SELECT ISNULL(SUM(ISNULL(COMMITTEDQUANTITY,0)),0) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
	LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL 
	LEFT JOIN IMTRANSACTIONLOCATION T_LOC (NOLOCK) ON T_LOC.ROWID=IA.R_IMTRANSACTIONLOCATION 
	WHERE IA.R_MASTERCODE = MC.ROWID AND OD.RECORDTYPE='R')	AS PTR_REVIEWED, 
DBO.FN_MCATTRIBUTES_IA(MC.ROWID,'ONHAND') AS PTR_ONHAND,	--SPECIAL ATTRIBUTE
--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'ONHAND') AS NUMERIC) AS PTR_ONHAND,	--SPECIAL ATTRIBUTE
DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigCust') AS DesigCust,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigItem') AS DesigItem,
DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigLoc') AS DesigLoc, 
ISNULL(MC.STATUS,'A') AS MCSTATUS	--IS MASTERCODE ACTIVE OR NOT
FROM OMREVIEWMASTERCODES MC (NOLOCK) 
	LEFT JOIN IMITEM ITM (NOLOCK) ON MC.R_ITEM = ITM.ROWID 
	LEFT JOIN IMLOCATION LOC (NOLOCK) ON MC.R_LOCATION =  LOC.ROWID 
	LEFT JOIN IMLOT LOT (NOLOCK) ON MC.R_LOT = LOT.ROWID 
	LEFT JOIN IDMASTER WH (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID 
	LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID=ITM.R_PRODUCTCATEGORY 
	LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID=ITM.R_CONTAINERCODE 
--	LEFT JOIN IDMASTER WH_LOCATION (NOLOCK) ON (LOC.R_WAREHOUSE = WH_LOCATION.ROWID) 
--	LEFT JOIN IDMASTER ITEM_WH (NOLOCK) ON (ITM.R_WAREHOUSE = ITEM_WH.ROWID) 
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
