--DEPRECATED: USE VW_RPT_ORDER_BREAKDOWN INSTEAD

--ORDERS WITH HOLDSHIP
--REPS WITH HOLDSHIP

/*
SELECT 
* 
FROM VW_ORDERSWITHHOLDSTOPSHIPVIEW (NOLOCK)
WHERE SHIPPERCODE = '10'
*/

CREATE OR ALTER VIEW [dbo].[VW_ORDERSWITHHOLDSTOPSHIPVIEW]
AS
SELECT 
	S.IDENTITYID AS SHIPPERCODE,
	OH.RECORDTYPE,
	CONS.IDENTITYID AS CONSIGNEECODE,
	CONS.NAME,
	OH.TRANSACTIONNUMBER ORDERNUMBER,
	--SP.IDENTITYID AS SALESREPCODE,
	PART.IDENTITYID AS SALESREPID,
	PART.NAME AS SALESREPNAME,
	OH.SHIPPINGDATE AS REQUESTDATE,
	OH.USERDEFINEDCODE_1 AS REQUESTTYPE, 
	CASE 
		WHEN OH.STAGE='A' THEN 'Assigned'
		WHEN OH.STAGE ='N' THEN 'Pending' 
		WHEN OH.STAGE ='C' THEN 'Completed'
		WHEN OH.STAGE ='S' THEN 'Picked'
		END AS STAGE,
	OH.USERDEFINEDCODE_2 AS STEP,
	(	SELECT DESCRIPTION_2 
		FROM OMCODES (NOLOCK) 
		WHERE CODETYPE='03' 
		AND CODE=OH.USERDEFINEDCODE_2 
		) AS STEPDESCRIPTION_2,
	CASE 
		WHEN OH.CREDITSTATUSREVIEW ='N' THEN 'N/A'
		WHEN OH.CREDITSTATUSREVIEW ='A' THEN 'Approved'
		WHEN OH.CREDITSTATUSREVIEW ='R' THEN 'Required'
		END AS CREDITSTATUSREVIEW,
	OH.REVIEWSTAGE AS PTRREVIEWSTAGE,
	FR.CODE AS PRICESCHEDULE,
	OH.PURCHASEORDERNUMBER,
	CASE 
		WHEN OD.QUANTITYSHIPPED=NULL OR OD.QUANTITYSHIPPED=0 THEN OD.QUANTITYORDERED 
		ELSE OD.QUANTITYSHIPPED 
		END AS QUANTITY, 
	ITEM.ITEMCODE,
	ITEM.DESCRIPTION_1 AS ITEMDESCRIPTION,
	OD.COMMENT AS PICKNOTE,
	ITEM.CLASSCODE AS CONTAINERSIZE,
	ITEM.REFERENCE_1 AS COMMONNAME,
	LOT.USERDEFINEDREFERENCE_4 AS HOLDREASON,
	LOT.LOTCODE AS LOT,
	LOT.USERDEFINEDCODE_3 AS HOLDSTOP,
	LOT.USERDEFINEDDATE_1 AS HS_BEGINDATE,
	LOT.USERDEFINEDDATE_2 AS HS_ENDDATE,
	LOT.USERDEFINEDDATE_4 AS H_REASONBEGIN,
	LOT.USERDEFINEDDATE_5 AS H_REASONEND,
	LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
	CASE 
		WHEN OH.STAGE='A' AND OH.USERDEFINEDCODE_2 ='SHIPPABLE'  THEN '1'
		WHEN OH.STAGE='N' AND OH.USERDEFINEDCODE_2 ='WAITING' THEN '2'
		WHEN OH.STAGE='N' AND OH.USERDEFINEDCODE_2 ='RESERVE' THEN '3'
		ELSE '4' END AS STAGESTEPSORT

FROM OMTRANSACTIONHEADER OH (NOLOCK)
LEFT JOIN OMTRANSACTIONDETAIL  OD (NOLOCK) ON OD.R_TRANSACTIONHEADER =OH.ROWID 
LEFT JOIN IMITEM ITEM (NOLOCK) ON ITEM.ROWID = OD.R_ITEM
LEFT JOIN IMLOT LOT (NOLOCK) ON OD.R_LOT = LOT.ROWID
LEFT JOIN IMPRODUCTCATEGORY IPC (NOLOCK) ON IPC.ROWID= ITEM.R_PRODUCTCATEGORY
--LEFT JOIN IDMASTER SP (NOLOCK) ON SP.ROWID = OH.R_SALESPERSON_1
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = OH.R_FMSHIPPER
LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
LEFT JOIN IDCONSIGNEESHIPPERZONE CSZ (NOLOCK) ON CSZ.R_SHIPPER =OH.R_FMSHIPPER AND CSZ.R_CONSIGNEE =OH.R_SHIPPER
LEFT JOIN IMFREIGHTRATETABLE FR (NOLOCK) ON FR.ROWID = CSZ .R_PRICESCHEDULE 
LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID=ITEM.R_CONTAINERCODE
WHERE LOT.USERDEFINEDCODE_3 IN('H','S')
AND OH.RECORDTYPE !='Z'
GO
