--USE [ABECAS_CUST_GNC_TEST]
--GO

--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO
/* TESTING THE VIEW:
select TRIPDATE, TRIPNO, TRIPVALUES--* 
from VW_SHIPPINGSUMMARYVIEW
where shippercode = '10'
and cast(tripdate as date) between '2024-04-07' and '2024-04-13'
AND TRIPNO = 'T19665'
--and trucktype = 'XVAN'
order by TRIPNO
*/

CREATE OR ALTER VIEW [dbo].[VW_SHIPPINGSUMMARYVIEW]
AS
SELECT ISNULL(FMTRIPHEADER.EQUIPMENT ,'')AS TRUCKTYPE,FMTRIPHEADER.TRIPNO,
CONVERT(DATE,FMTRIPHEADER.PLANSTART) AS TRIPDATE,FMTRIPHEADER.STATUS,
1 as TRIPCOUNT,
--This was counting Stops and s/b counting trips:
--(SELECT COUNT(KEYSEQUENCE) FROM FMTRIPDETAIL D (NOLOCK) WHERE D.R_TRIPHEADER= FMTRIPHEADER.ROWID) AS TRIPCOUNT,
(SELECT ISNULL(SUM(ISNULL(HEADER.MILESUNLOADED,0) + ISNULL(HEADER.MILESLOADED,0)),0) 
FROM FMTRIPHEADER HEADER (NOLOCK) WHERE HEADER.ROWID = FMTRIPHEADER.ROWID )  AS TOTALMILES,
--New Miles field added per DJ request - DT 6/29/21
	(	SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = FMTRIPHEADER.ROWID AND FC.CHARGECODE ='RATE/MILE') AS TOTALLOADEDMILES,
--(SELECT SUM(ISNULL(OD.UNITPRICE,0) * ISNULL(OD.QUANTITYSHIPPED,0)) FROM OMTRANSACTIONDETAIL TD (NOLOCK)
(SELECT ISNULL(SUM(ISNULL(TD.AMOUNT,0)),0) FROM OMTRANSACTIONDETAIL TD (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID=TD.R_TRANSACTIONHEADER
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= TH.ROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID 
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = D.R_TRIPHEADER 
WHERE H.ROWID =FMTRIPHEADER.ROWID) TRIPVALUES,
--SHIPPERCODE WAS PULLING FROM FMTRIPHEADER.R_ORIGIN WHICH IS WRONG, S/B PULLING FROM FPDISPATCHOBJECT.R_SHIPPER - DT 3/16/22
		(	SELECT TOP 1 TRIM(IDENTITYID) FROM FMTRIPDETAIL TD (NOLOCK)
			LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID = TD.R_FMDISPATCHOBJECT
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER
			WHERE TD.R_TRIPHEADER = FMTRIPHEADER.ROWID
		) AS SHIPPERCODE,
		(	SELECT TOP 1 NAME FROM FMTRIPDETAIL TD (NOLOCK)
			LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID = TD.R_FMDISPATCHOBJECT
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER
			WHERE TD.R_TRIPHEADER = FMTRIPHEADER.ROWID
		) AS SHIPPERNAME,
--TRIM(S.IDENTITYID) AS SHIPPERCODE,S.NAME AS SHIPPERNAME,
(SELECT ISNULL(SUM(ISNULL(FMDISPATCHOBJECT.WEIGHTORDERED,0)),0) FROM FMDISPATCHOBJECT (NOLOCK)  
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = FMDISPATCHOBJECT.ROWID 
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID = D.R_TRIPHEADER 
WHERE H.ROWID =FMTRIPHEADER.ROWID ) AS TRIPWEIGHT,
(SELECT ISNULL(SUM(ISNULL(FMDISPATCHOBJECT.CUBESORDERED,0)),0) FROM FMDISPATCHOBJECT (NOLOCK)
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = FMDISPATCHOBJECT.ROWID 
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = D.R_TRIPHEADER 
WHERE H.ROWID =FMTRIPHEADER.ROWID ) AS TRIPVOLUME,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = SPOPENITEMS.R_SOURCEID 
WHERE H.ROWID =FMTRIPHEADER.ROWID  ) AS GROSSRATE ,
(SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER TH (NOLOCK) ON TH.ROWID=F.R_TRANSACTIONHEADER
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= TH.ROWID
LEFT JOIN FMTRIPDETAIL D (NOLOCK) ON D.R_FMDISPATCHOBJECT = DO.ROWID 
LEFT JOIN FMTRIPHEADER H (NOLOCK) ON H.ROWID  = D.R_TRIPHEADER 
WHERE H.ROWID=FMTRIPHEADER.ROWID) AS FREIGHTREVENUE
FROM FMTRIPHEADER (NOLOCK) 
--LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = FMTRIPHEADER.R_ORIGIN -->WRONG LINK TO GET SHIPPERCODE
WHERE FMTRIPHEADER.RECORDTYPE <>'P'
GO


