/*
--TRUCK SHIPPING MANIFEST (ARGOS ART REPORT)
SELECT * FROM VW_TRUCKSHIPPINGMANIFESTVIEW (NOLOCK)
WHERE 1=1 AND TRIPNO = 'T14066'--'T06087'--'T06805'--
ORDER BY WAREHOUSEID, TRIPNO, DELSTOPNO
*/
CREATE OR ALTER   VIEW [dbo].[VW_TRUCKSHIPPINGMANIFESTVIEW]
AS

--NEW CODE ELIMINATES FMDISPATCHOBJECTCONTENTS FROM THE VIEW WHICH WAS CAUSING ISSUES.
SELECT *, 
	--PARSE ITEMCOUNTS INTO 10 DIFFERENT CONTAINERCLASS COLUMNS 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 1, QTYATSTAGE, 0) AS CNTCT, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 2, QTYATSTAGE, 0) AS CNT6INCH, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 3, QTYATSTAGE, 0) AS CNT1GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 4, QTYATSTAGE, 0) AS CNT2GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 5, QTYATSTAGE, 0) AS CNT3GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 6, QTYATSTAGE, 0) AS CNT5GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 7, QTYATSTAGE, 0) AS CNT7GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 8, QTYATSTAGE, 0) AS CNT10GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 9, QTYATSTAGE, 0) AS CNT15GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 10, QTYATSTAGE, 0) AS CNT25GAL, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 11, QTYATSTAGE, 0) AS CNTWHIP, 
	IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 0, QTYATSTAGE, 0) AS CNTOTHER 
FROM ( 
		SELECT 
			CO.COMPANYID,
			CO.NAME AS COMPANYNAME,
			WH.IDENTITYID AS WAREHOUSEID,
			WH.NAME AS WAREHOUSENAME,
			HDR.RECORDTYPE,
			HDR.STATUS ,
			CARR.NAME AS CARRIERNAME,
			HDR.USERDEFINEDCODE_2 AS DOCKNUMBER,
			S.IDENTITYID AS SHIPPERCODE,S.NAME AS SHIPPERNAME,
			HDR.EQUIPMENT AS TRUCKTYPE,
			HDR.PLANSTART AS TRIPDATE,
			HDR.COMMENT AS SPECIALINSTRUCTIONS,      --THIS MAY BE WRONG.
			ITM.NETWEIGHTQUANTITY * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS ESTIMATEDWEIGHT, 
			ITM.UNITVOLUMEQUANTITY * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS ESTIMATEDVOLUME, 
			(	SELECT	LEFT(IDADDRESS.TELEPHONE_1,8) + '-' + 
						RIGHT(IDADDRESS.TELEPHONE_1, LEN(IDADDRESS.TELEPHONE_1)-LEN(LEFT(IDADDRESS.TELEPHONE_1,8))) 
				FROM IDRELATIONSHIPLINKS  (NOLOCK) 
				JOIN IDMASTER  (NOLOCK) ON IDMASTER.ROWID = IDRELATIONSHIPLINKS.R_IDMEMBER AND IDMASTER.IDENTITYID LIKE 'C5%'
				JOIN IDTYPESLINKS  (NOLOCK) ON IDTYPESLINKS.R_IDENTITY = IDMASTER.ROWID
				JOIN IDADDRESS  (NOLOCK) ON IDADDRESS.ROWID = IDTYPESLINKS.R_ADDRESS
				WHERE IDRELATIONSHIPLINKS.R_IDMASTER = OH.R_SHIPPER --VCONS.CONSIGNEEMASTERROWID [USING ORIGINAL CONSIGNEEID TO GET THE ORIGINAL CONSIGNEE'S SHIPTOPHONE]
				) AS SHIPTOPHONNUMBER,
			HDR.TRIPNO, 
			DTL.DELSTOPNO, 
			OBJ.TRACKINGNUMBER, 
			ITM.ITEMCODE, 
			ICONS.USERDEFINEDCODE_11 AS QUALITYASSURANCECODE,
			IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
			(	SELECT TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') )
				FROM IDSYNONYMS ALTSHIP (NOLOCK) 
				WHERE ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO
				) AS ALTSHIPTELEPHONE_1, 
			VCONS.CONSIGNEEIDENTITYID,
			VCONS.CONSIGNEENAME,
			VCONS.CONSIGNEEADDRESSMEMO,
			VCONS.CONSIGNEEADDRESS_1,
			TRIM(VCONS.CONSIGNEEADDRESS_2) AS CONSIGNEEADDRESS_2, 
			RTRIM(VCONS.CONSIGNEECITY)+', '+VCONS.CONSIGNEESTATE+'  '+VCONS.CONSIGNEEZIP AS CONSIGNEECITYSTATEZIP,
			VCONS.CONSIGNEETELEPHONE_1,

			--STOPNOTES CHANGING FROM DTL.COMMENT TO DTL.UDR4 + UDR5:
			--NULLIF(ISNULL(TRIM(REPLACE(SUBSTRING(DTL.COMMENT,1,50),CHAR(13)+CHAR(10),'')),'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,'  ') AS STOPNOTES, 
			NULLIF(ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,' ') AS STOPNOTES, 

			TR.DESCRIPTION AS GNCTRAILERNO,--REPLACES: TR.EQUIPMENTID AS GNCTRAILERNO,
			HDR.MILESUNLOADED,HDR.MILESLOADED ,
			TK.DESCRIPTION  AS GNCTRUCKNO,HDR.TRUCKREFERENCE AS CONTRACTTRUCKNO,
			HDR.TRAILERREFERENCE AS CONTRACTTRAILERNO,
			DR.NAME AS GNCDRIVER,--REPLACES: DR.IDENTITYID AS GNCDRIVER,
			HDR.DRIVERREFERENCE, HDR.USERDEFINEDREFERENCE_1 AS CONTRACTDRIVER,
			HDR.USERDEFINEDREFERENCE_2 AS DRIVERPHONE,VCONS.CONSIGNEEDIRECTIONS AS DIRECTIONS,
			VCONS.CONSIGNEEUSERDEFINEDREFERENCE_7 AS CONSDELNOTE,
			CNT.CONTAINERCLASS, 
			IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QTYATSTAGE, 
			NULL AS ADDONDATE    --DON'T KNOW WHERE THIS LIVES.
		FROM FMTRIPHEADER HDR (NOLOCK) 
		JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID 
		JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT 
		JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID			--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
		JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID	--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
		JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OBJ.R_SHIPPER 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.ConsigneeMasterRowID = OBJ.R_CONSIGNEE 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.ConsigneeMasterRowID 
		LEFT OUTER JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
		LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = HDR.R_ORIGIN
		LEFT JOIN IDMASTER DR (NOLOCK) ON DR.ROWID = HDR.R_DRIVER 
		LEFT JOIN IDEQUIPMENT TR (NOLOCK) ON TR.ROWID=HDR.R_TRAILER
		LEFT JOIN IDEQUIPMENT TK (NOLOCK) ON TK.ROWID=HDR.R_TRUCK
		WHERE HDR.RECORDTYPE <>'P'
	) X
--WHERE TRIPNO = 'T06808'
--ORDER BY
--		TRIPNO,
--		DELSTOPNO,
--		TRACKINGNUMBER,
--		ITEMCODE

/* 
--OLD CODE
SELECT 
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
HDR.RECORDTYPE,
HDR.STATUS ,
CARR.NAME AS CARRIERNAME,
HDR.USERDEFINEDCODE_2 AS DOCKNUMBER,
S.IDENTITYID AS SHIPPERCODE,S.NAME AS SHIPPERNAME,
HDR.EQUIPMENT AS TRUCKTYPE,
--ISNULL(HDR.ACTUALSTART,HDR.PLANSTART) AS TRIPDATE,
HDR.PLANSTART AS TRIPDATE,
HDR.COMMENT AS SPECIALINSTRUCTIONS,      --THIS MAY BE WRONG.
ITM.NETWEIGHTQUANTITY * CONT.ITEMS AS ESTIMATEDWEIGHT,
ITM.UNITVOLUMEQUANTITY * CONT.ITEMS AS ESTIMATEDVOLUME,
--CONT.GROSSWEIGHT,  --OR NETWEIGHT COULD BE SUBSTITUTED.
--CONT.CUBES,
(SELECT LEFT(IDADDRESS.TELEPHONE_1,8) + '-' + 
		RIGHT(IDADDRESS.TELEPHONE_1, LEN(IDADDRESS.TELEPHONE_1)-LEN(LEFT(IDADDRESS.TELEPHONE_1,8))) 
FROM IDRELATIONSHIPLINKS
JOIN IDMASTER ON IDMASTER.ROWID = IDRELATIONSHIPLINKS.R_IDMEMBER AND IDMASTER.IDENTITYID LIKE 'C5%'
JOIN IDTYPESLINKS ON IDTYPESLINKS.R_IDENTITY = IDMASTER.ROWID
JOIN IDADDRESS ON IDADDRESS.ROWID = IDTYPESLINKS.R_ADDRESS
WHERE IDRELATIONSHIPLINKS.R_IDMASTER = VCONS.CONSIGNEEMASTERROWID) AS SHIPTOPHONNUMBER,
HDR.TRIPNO,
DTL.DELSTOPNO,
OBJ.TRACKINGNUMBER,
ICONS.USERDEFINEDCODE_11 AS QUALITYASSURANCECODE,
VCONS.CONSIGNEEIDENTITYID,
VCONS.CONSIGNEENAME,
VCONS.CONSIGNEEADDRESSMEMO,
VCONS.CONSIGNEEADDRESS_1,
RTRIM(VCONS.CONSIGNEECITY)+', '+VCONS.CONSIGNEESTATE+'  '+VCONS.CONSIGNEEZIP AS CONSIGNEECITYSTATEZIP,
VCONS.CONSIGNEETELEPHONE_1,
DTL.COMMENT AS DROPNOTES, --THIS MAY BE WRONG.
TR.DESCRIPTION AS GNCTRAILERNO,--REPLACES: TR.EQUIPMENTID AS GNCTRAILERNO,
HDR.MILESUNLOADED,HDR.MILESLOADED ,
TK.DESCRIPTION  AS GNCTRUCKNO,HDR.TRUCKREFERENCE AS CONTRACTTRUCKNO,
HDR.TRAILERREFERENCE AS CONTRACTTRAILERNO,
DR.NAME AS GNCDRIVER,--REPLACES: DR.IDENTITYID AS GNCDRIVER,
HDR.DRIVERREFERENCE, HDR.USERDEFINEDREFERENCE_1 AS CONTRACTDRIVER,
HDR.USERDEFINEDREFERENCE_2 AS DRIVERPHONE,VCONS.CONSIGNEEDIRECTIONS AS DIRECTIONS,
VCONS.CONSIGNEEUSERDEFINEDREFERENCE_7 AS CONSDELNOTE,
--PARSE ITEMCOUNTS INTO 10 DIFFERENT CONTAINERCLASS COLUMNS
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 1 THEN CONT.ITEMS ELSE 0 END AS CNTCT,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 2 THEN CONT.ITEMS ELSE 0 END AS CNTQTS,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 3 THEN CONT.ITEMS ELSE 0 END AS CNT1GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 4 THEN CONT.ITEMS ELSE 0 END AS CNT2GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 5 THEN CONT.ITEMS ELSE 0 END AS CNT3GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 6 THEN CONT.ITEMS ELSE 0 END AS CNT5GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 7 THEN CONT.ITEMS ELSE 0 END AS CNT7GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 8 THEN CONT.ITEMS ELSE 0 END AS CNT10GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 9 THEN CONT.ITEMS ELSE 0 END AS CNT15GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 10 THEN CONT.ITEMS ELSE 0 END AS CNT25GAL,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 11 THEN CONT.ITEMS ELSE 0 END AS CNTWHIP,
CASE WHEN ISNULL(CHARINDEX(CNT.CONTAINERCLASS, '..CT QTS#1 #2 #3 #5 #7 #10#15#25WH '),0)/3 = 0 THEN CONT.ITEMS ELSE 0 END AS CNTOTHER,
CONT.ITEMS,NULL AS ADDONDATE    --DON'T KNOW WHERE THIS LIVES.
FROM FMTRIPHEADER HDR (NOLOCK)

JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT
LEFT OUTER JOIN FMDISPATCHOBJECTCONTENTS CONT (NOLOCK) ON CONT.R_FMDISPATCHOBJECT = OBJ.ROWID
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID
LEFT OUTER JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OBJ.R_SHIPPER
LEFT OUTER JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = CONT.CONTENTSID AND ITM.R_WAREHOUSE = WH.ROWID
LEFT OUTER JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
LEFT OUTER JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE
LEFT OUTER JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.CONSIGNEEMASTERROWID
LEFT OUTER JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = HDR.R_ORIGIN
LEFT JOIN IDMASTER DR (NOLOCK) ON DR.ROWID = HDR.R_DRIVER 
LEFT JOIN IDEQUIPMENT TR (NOLOCK) ON TR.ROWID=HDR.R_TRAILER
LEFT JOIN IDEQUIPMENT TK (NOLOCK) ON TK.ROWID=HDR.R_TRUCK
WHERE HDR.RECORDTYPE <>'P'
AND TRIPNO = 'T06808'

ORDER BY
		TRIPNO,
		DELSTOPNO,
		TRACKINGNUMBER--,		ITEMCODE
*/



