--TEMPLATE: EDI35-820-ACE HARDWARE

--EDI35_820_HEADER (Create Ace Hardware 812 Email Header Record)

DECLARE
@IDGROUP VARCHAR(10)= '35'			,
@ST01	VARCHAR(3)	= '820'			,	--DOCTYPE
@BPR01	VARCHAR(2)	= 'I'			, --REMITINFOONLY
@BPR02	VARCHAR(18)	= '3062'		,	--CHECKAMOUNT 
@BPR03	VARCHAR(1)	= 'C'			, --CREDITDEBITFLAG
@BPR04	VARCHAR(3)	= 'DZC'			, --ACHORCHECK [DZC,CHK]
@BPR05	VARCHAR(10)	= 'CCP'			, --CCPFORMAT
@BPR06	VARCHAR(2)	= '01'			, --ROUTEID
@BPR07	VARCHAR(12)	= '999999999'	, --BANKID
@REFEF01 VARCHAR(3)	= 'EF'			, --TYPEEF
@REFEF02 VARCHAR(30)= '222222'		, --PMTNUMBER
@REFEF03 VARCHAR(80)= 'IF ANY QUESTIONS, CALL (630)990-6669', --CONTACT
@REFIA01 VARCHAR(3)	= 'IA'			, --TYPEIA
@REFIA02 VARCHAR(30)= '12345'		, --VENDOR
@REFIA03 VARCHAR(80)= 'IF ANY QUESTIONS, CALL (630)990-6669', --CONTACT
@DTM01	VARCHAR(3)	= '097'			, --DATETYPE
@DTM02	VARCHAR(8)	= '19980215'	,	--CHECKDATE
@N102	VARCHAR(60)	= 'GREENLEAF'	,	--VENDORNAME
@ENT02	VARCHAR(2)	= '01'			, --ISDUNNS
@ENT03	VARCHAR(80)	= '006928311'	 --DUNNS

/*
DECLARE @ROWID UNIQUEIDENTIFIER
SET @ROWID = NEWID() 

--POPULATE GNC_EDI_EMAILHEADER:
INSERT INTO GNC_EDI_EMAILHEADER 
*/
SELECT 
	--@ROWID AS ROWID, 
	GETDATE() AS CREATIONDATETIME, 
	'N' AS EMAILSENTFLAG, 
	@ST01 AS DOCTYPE, 
	EDI.IDGROUP, 
	EDI.VENDOR, 
	EDI.WAREHOUSEID, 

	@REFEF01 + '-' + @REFEF02 AS TRANSACTIONNUMBER, --ACH PAYMENT NUMBER 
	'DUNNS:'+@ENT03 AS PONUMBER, -- DUNNS
	'BANK#'+@BPR07 AS STORENUMBER, --BANKID 
	@DTM02 AS DATETIME, --CHECKDATE 
	IIF(@BPR04='CHK','CHECK', IIF(@BPR03='C','ACH PAYMENT', 'ACH CHARGEBACK')) AS ACTION, --CHECK OR ACH PAYMENT/CHARGEBACK 
	@REFEF01+'-'+@REFEF02+':'+@REFEF03 AS REFERENCE, -- 
	'$'+@BPR02 AS RESULT, --CHECKAMT 
	@BPR05+'-'+@BPR06+'-BANK:'+@BPR07 AS IDENTIFIERS, --CCP/ROUTE/BANKID 
	'PAY: VENDOR '+@REFIA02+'-'+@N102 AS SUBJECT --PAY VENDOR 
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID = '99'--LEFT(@BCD07,2) --DERIVE TRANSACTIONNUMBER FROM BCD07 WHEN MULTIPLE VENDORS ARE CREATED FOR ACE IN THE FUTURE. FOR NOW WHID = 99

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
--EDI535_820_DETAIL (Create Ace Hardware 820 Email Detail Record)

DECLARE 
@IDGROUP VARCHAR(10)= '535'			,
@ST01	VARCHAR(3)	= '820'			,	--DOCTYPE
@RMR01	VARCHAR(3)	= 'CR', --CRDB
@RMR02	VARCHAR(30)	= '10-55106', --INVOICENUMBER
@RMR04	VARCHAR(18)	= '30.62', --NETAMOUNT
@RMR05	VARCHAR(18)	= '32.25', --GROSSAMOUNT
@RMR06	VARCHAR(18)	= '1.63', --DISCOUNTAMOUNT
@REFMC02  VARCHAR(30)	= '0745054', --MICROFILMNUMBER
@REFSM02  VARCHAR(30)	= '4532', --STORENUMBER
@REFVV02  VARCHAR(30)	= '0160284', --VOUCHERNUMBER
@DTMINV02 VARCHAR(8)	= '19980815', --INVOICEDATE [003]
@DTMPO02  VARCHAR(8)	= '19980927' --PROCESSDATE [097]

DECLARE @REMAILHEADER VARCHAR(38)
SET @REMAILHEADER = (	SELECT TOP 1 ROWID 
			FROM GNC_EDI_EMAILHEADER (NOLOCK) 
			ORDER BY CREATIONDATETIME DESC)

SELECT @REMAILHEADER AS REMAILHEADER	-->TEST THE LOOKUPDEFINITION:

--POPULATE GNC_EDI_EMAILDETAIL:
--INSERT INTO GNC_EDI_EMAILDETAIL 
SELECT 
	@REMAILHEADER AS R_EMAILHEADER, 
	@ST01 AS DOCTYPE, 
	@IDGROUP AS IDGROUP, 
	EDI.WAREHOUSEID AS WAREHOUSEID,
	@RMR02 AS TRANSACTIONUMBER, 
	(	SELECT OH.PURCHASEORDERNUMBER 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		WHERE OH.TRANSACTIONNUMBER = @RMR02
		) AS PONUMBER, 
	@REFSM02 AS STORENUMBER,
	(SELECT COUNT(*) FROM GNC_EDI_EMAILDETAIL CNT (NOLOCK) WHERE CNT.R_EMAILHEADER = @REMAILHEADER)+1 AS LINENUMBER, --COUNT MESSAGELINES.
	'ST#'+ @REFSM02 + ' DATE:'+ @DTMINV02 + ' INVOICE:'+ @RMR02 + 
	' MICROFILM:'+ @REFMC02 + ' VOUCHER:' + @REFVV02 + ' PROCDATE:' + @DTMPO02 + 
	' AMOUNT: ('+ @RMR05 + ' - ' + @RMR06 + ')= $' + @RMR04 
	AS DETAIL
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID =	LEFT(@RMR02,2)

