--TEMPLATE: EDI35-812-ACE HARDWARE

--EDI35_812_HEADER (Create Ace Hardware 812 Email Header Record)

DECLARE
@IDGROUP VARCHAR(10)= '35'				,
@ST01	VARCHAR(3)	= '812'				,	--DOCTYPE
@BCD01 VARCHAR(8)	= '20100826'		,	--CDADJUSTDATE
@BCD02 VARCHAR(22)	= '1234567891'		,	--CDADJUSTNUMBER
@BCD03 VARCHAR(2)	= 'T'				,	--CRADJUSTACTION
@BCD04 VARCHAR(15)	= '11361'			,	--NETAMOUNT
@BCD05 VARCHAR(1)	= 'C'				,	--CDFLAGCODE
@BCD07 VARCHAR(20)	= '10-60593'		,	--INVOICENUMBER
@BCD10 VARCHAR(50)	= '51923'			,	--PURCHASEORDERNUMBER
@SAC01 VARCHAR(1)	= 'C'				,	--A=ALLOWANCE, C=CHARGE
@SAC02 VARCHAR(4)	= 'C310'			,	--C310=DISCOUNT
@SAC05 VARCHAR(15)	= '227'				,	--TOTAL DISCOUNT AMOUNT
@N102 VARCHAR(60)	= 'ware corporation',	--SHIPTONAME
@N301 VARCHAR(35)	= '2200 KENSINGTON COURT'	,	--SHIPTOADDRESS1
@N401 VARCHAR(20)	= 'OAK BROOK'				,	--SHIPTOCITY
@N402 VARCHAR(2)	= 'IL'						,	--SHIPTOSTATE
@N403 VARCHAR(10)	= '60521'					,	--SHIPTOZIP
@N405 VARCHAR(3)	= 'US'							--SHIPTOCOUNTRY
/*
DECLARE @ROWID UNIQUEIDENTIFIER
SET @ROWID = NEWID() 

--POPULATE GNC_EDI_EMAILHEADER:
INSERT INTO GNC_EDI_EMAILHEADER 
*/
SELECT 
	--@ROWID AS ROWID, 
	GETDATE() AS CREATIONDATETIME, 
	'N' AS EMAILSENTFLAG, 
	@ST01 AS DOCTYPE, 
	EDI.IDGROUP, 
	EDI.VENDOR, 
	EDI.WAREHOUSEID, 
	@BCD07 AS TRANSACTIONNUMBER, 
	@BCD10 AS PONUMBER, 
	(	SELECT ICONS.USERDEFINEDREFERENCE_2  
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		WHERE OH.TRANSACTIONNUMBER = @BCD07
		) AS STORENUMBER, 
	@BCD01 AS DATETIME, 
	@BCD03 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD03',@BCD03) AS ACTION, 
	@BCD02 AS REFERENCE, 
	@BCD05 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD05',@BCD05) + ' TOTAL AMOUNT = $' + @BCD04  + 
	' (' + @SAC02 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('SAC02',@SAC02) + ' = $' + @SAC05 + ')'AS RESULT, 
	@BCD07 + ' - ' + @BCD10 AS INDENTIFIERS, 
	NULL AS SUBJECT --ACE DOESN'T SEND THIS
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID = '99'--LEFT(@BCD07,2) --DERIVE TRANSACTIONNUMBER FROM BCD07 WHEN MULTIPLE VENDORS ARE CREATED FOR ACE IN THE FUTURE. FOR NOW WHID = 99

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
--EDI535_812_DETAIL (Create Ace Hardware 812 Email Detail Record)

DECLARE 
@IDGROUP VARCHAR(10)= '535'			,
@ST01	VARCHAR(3)	= '812'			,	--DOCTYPE
@CDD01 VARCHAR(2)	= 'CS'			,	--ADJREASON	
@CDD02 VARCHAR(1)	= 'C'			,	--CDFLAG 
@CDD07 VARCHAR(10)	= '1'			,	--CDQTY
@CDD11 VARCHAR(17)	= '113.61'		,	--CDPRICE
@LIN01 VARCHAR(10)	= '1'			,	--PO_LINENUMBER
@LIN03 VARCHAR(48)	= '2222222'		,	--PO_ALTERNATESKU
@LIN05 VARCHAR(48)	= ''			,	--UPCNO (NOT SENT)
@LIN07 VARCHAR(48)	= ''			,	--ITEMCODE (NOT SENT)
@N902 VARCHAR(50)	= 'ware table lamp'	--DESCRIPTION

DECLARE @REMAILHEADER VARCHAR(38)
SET @REMAILHEADER = (	SELECT TOP 1 ROWID 
			FROM GNC_EDI_EMAILHEADER (NOLOCK) 
			ORDER BY CREATIONDATETIME DESC)

DECLARE @TRANSACTIONNUMBER VARCHAR(20)
SET @TRANSACTIONNUMBER = (	SELECT TOP 1 TRANSACTIONNUMBER 
			FROM GNC_EDI_EMAILHEADER (NOLOCK) 
			ORDER BY CREATIONDATETIME DESC)

SELECT @REMAILHEADER AS REMAILHEADER	-->TEST THE LOOKUPDEFINITION:

--POPULATE GNC_EDI_EMAILDETAIL:
--INSERT INTO GNC_EDI_EMAILDETAIL 
SELECT 
	@REMAILHEADER AS R_EMAILHEADER, 
	@ST01 AS DOCTYPE, 
	@IDGROUP AS IDGROUP, 
	EDI.WAREHOUSEID AS WAREHOUSEID,
	@TRANSACTIONNUMBER AS TRANSACTIONUMBER, 
	(	SELECT OH.PURCHASEORDERNUMBER 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		WHERE OH.TRANSACTIONNUMBER = @TRANSACTIONNUMBER
		) AS PONUMBER, 
	(	SELECT ICONS.USERDEFINEDREFERENCE_2  
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		WHERE OH.TRANSACTIONNUMBER = @TRANSACTIONNUMBER
		) AS STORENUMBER, 
	@LIN01 AS LINENUMBER,
	@CDD01 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('CDD01',@CDD01) + ' ' + 
	DBO.FN_EDI_CODE_DESCRIPTION('CDD02',@CDD02) + ' ' + 
	@CDD07 + ' EA @ $' + @CDD11 + ' LINE#: ' + @LIN01 + 
	' SKU:' + @LIN03 + ' UPC:' + @LIN05 + ' ITEM:' + @LIN07 + 
	+ ' --> ' + IIF(ISNULL(@N902,'') = '', '', ' ('+@N902+')') 
	
	AS DETAIL
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID =	LEFT(@TRANSACTIONNUMBER,2)

