TEMPLATE: EDI535-812

--EDI535_812_HEADER (Create Rural King 812 Email Header Record)
/*
DECLARE
@IDGROUP VARCHAR(10)= '535'				,
@ST01	VARCHAR(3)	= '812'				,	--DOCTYPE
@BCD01 VARCHAR(8)	= '20230216'		,	--CDADJUSTDATE
@BCD02 VARCHAR(22)	= '998877665'		,	--CDADJUSTNUMBER
@BCD03 VARCHAR(2)	= 'T'				,	--CRADJUSTACTION
@BCD04 VARCHAR(15)	= '31903'			,	--NETAMOUNT
@BCD05 VARCHAR(1)	= 'C'				,	--CDFLAGCODE
@BCD07 VARCHAR(20)	= '10-45775'		,	--INVOICENUMBER
@BCD10 VARCHAR(50)	= 'POB1X80156'		,	--PURCHASEORDERNUMBER
-->NEED TO LOOK INTO CREDITNOTEREQUEST ON THE 810 MAP
@BCD12 VARCHAR(2)	= 'CR'				,	--TRANSACTIONTYPECODE
@BCD13 VARCHAR(3)	= 'PD'				,	--REFERENCEIDQUALIFIER
@BCD14 VARCHAR(50)	= '12345'			,	--CDADJUSTNUMBER/DEALNUMBER
@N902 VARCHAR(50)	= '80156'			,	--PO_VENDOR
@SAC01 VARCHAR(1)	= 'C'				,	--A=ALLOWANCE, C=CHARGE
@SAC02 VARCHAR(4)	= 'H850'			,	--H850=TAX
@SAC05 VARCHAR(15)	= '2783'			,	--TOTAL TAX AMOUNT
@N102 VARCHAR(60)	= 'RURALKING #99'	,	--SHIPTONAME
@N104 VARCHAR(20)	= '99'				,	--STORENUMBER USE:RIGHT('00'+TRIM(@N104),4)
@N301 VARCHAR(35)	= '9525 COLLINS RD'	,	--SHIPTOADDRESS1
@N401 VARCHAR(20)	= 'COLLINSVILLE'	,	--SHIPTOCITY
@N402 VARCHAR(2)	= 'IL'				,	--SHIPTOSTATE
@N403 VARCHAR(10)	= '62234'				--SHIPTOZIP
*/
DECLARE @ROWID UNIQUEIDENTIFIER
SET @ROWID = NEWID() 

--POPULATE GNC_EDI_EMAILHEADER:
INSERT INTO GNC_EDI_EMAILHEADER 
SELECT 
	@ROWID AS ROWID, 
	GETDATE() AS CREATIONDATETIME, 
	'N' AS EMAILSENTFLAG, 
	@ST01 AS DOCTYPE, 
	EDI.IDGROUP, 
	EDI.WAREHOUSEID, 
	SUBSTRING(@BCD02,4,20) AS TRANSACTIONNUMBER,--@BCD07 AS TRANSACTIONNUMBER, 
	(	SELECT OH.PURCHASEORDERNUMBER 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		WHERE OH.TRANSACTIONNUMBER = SUBSTRING(@BCD02,4,20)--@BCD07 
		) AS PONUMBER, 
	(	SELECT ICONS.USERDEFINEDREFERENCE_2  
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		WHERE OH.TRANSACTIONNUMBER = SUBSTRING(@BCD02,4,20)--@BCD07 
		) AS STORENUMBER, 
	@BCD01 AS DATETIME, 
	@BCD03 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD03',@BCD03) AS ACTION, 
	@BCD02 AS REFERENCE, 
	@BCD05 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD05',@BCD05) + ' TOTAL AMOUNT = $' + @BCD04  + 
	' (' + @SAC02 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('SAC02',@SAC02) + ' = $' + @SAC05 + ')'AS RESULT, 
	@BCD07 + ' - ' + @BCD10 AS INDENTIFIERS, 
	@BCD12 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD12',@BCD12) + ' ' + 
	@BCD13 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('BCD13',@BCD13) + ': ' +  @BCD14 AS SUBJECT
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID = '10' 

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
--EDI535_812_DETAIL (Create Rural King 812 Email Detail Record)
/*
DECLARE 
@IDGROUP VARCHAR(10)= '535'			,
@ST01	VARCHAR(3)	= '812'			,	--DOCTYPE
@CDD01 VARCHAR(2)	= 'A5'			,	--ADJREASON	
@CDD02 VARCHAR(1)	= 'C'			,	--CDFLAG 
@CDD07 VARCHAR(10)	= '4'			,	--CDQTY
@CDD11 VARCHAR(17)	= '18.20'		,	--CDPRICE
@CDD14 VARCHAR(264) = 'BECAUSE'		,	--CDMESSAGE
@LIN01 VARCHAR(10)	= '1'			,	--PO_LINENUMBER
@LIN03 VARCHAR(48)	= '801560155'	,	--PO_ALTERNATESKU
@LIN05 VARCHAR(48)	= '008776142313',	--UPCNO
@LIN07 VARCHAR(48)	= '001884.031.1',	--ITEMCODE
@N902ZZ VARCHAR(50)	= ''			,	--DESCRIPTION
@N903LI VARCHAR(45)	= 'Defective Units Received'	,	--COMMENTS
@SAC01 VARCHAR(1)	= 'A'			,	--A=ALLOWANCE, C=CHARGE
@SAC02 VARCHAR(4)	= 'D240'		,	--SERVICECODE	(D240=FREIGHT...)
@SAC05 VARCHAR(15)	= '2783'		,	--SACAMOUNT
@SAC08 VARCHAR(9)	= '1.25'		,	--SACRATE
@SAC15 VARCHAR(80)	= 'FREIGHT'			--SACDESCRIPTION
*/
DECLARE @REMAILHEADER VARCHAR(38)
SET @REMAILHEADER = (	SELECT TOP 1 ROWID 
			FROM GNC_EDI_EMAILHEADER (NOLOCK) 
			ORDER BY CREATIONDATETIME DESC)

DECLARE @TRANSACTIONNUMBER VARCHAR(20)
SET @TRANSACTIONNUMBER = (	SELECT TOP 1 TRANSACTIONNUMBER 
			FROM GNC_EDI_EMAILHEADER (NOLOCK) 
			ORDER BY CREATIONDATETIME DESC)

SELECT @REMAILHEADER AS REMAILHEADER	-->TEST THE LOOKUPDEFINITION:

--POPULATE GNC_EDI_EMAILDETAIL:
INSERT INTO GNC_EDI_EMAILDETAIL 
SELECT 
	@REMAILHEADER AS R_EMAILHEADER, 
	@ST01 AS DOCTYPE, 
	@IDGROUP AS IDGROUP, 
	EDI.WAREHOUSEID AS WAREHOUSEID,
	@TRANSACTIONNUMBER AS TRANSACTIONUMBER, 
	(	SELECT OH.PURCHASEORDERNUMBER 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		WHERE OH.TRANSACTIONNUMBER = @TRANSACTIONNUMBER
		) AS PONUMBER, 
	(	SELECT ICONS.USERDEFINEDREFERENCE_2  
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		WHERE OH.TRANSACTIONNUMBER = @TRANSACTIONNUMBER
		) AS STORENUMBER, 
	@LIN01 AS LINENUMBER,
	@CDD01 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('CDD01',@CDD01) + ' ' + 
	DBO.FN_EDI_CODE_DESCRIPTION('CDD02',@CDD02) + ' ' + 
	@CDD07 + ' EA @ $' + @CDD11 + ' LINE#: ' + @LIN01 + 
	' SKU:' + @LIN03 + ' UPC:' + @LIN05 + ' ITEM:' + @LIN07 + 
	IIF(ISNULL(@SAC02,'')='', '', 
		' (' + @SAC02 + ' - ' + DBO.FN_EDI_CODE_DESCRIPTION('SAC02',@SAC02) + ' ' + 
		--@SAC15 + ' ' + 
		DBO.FN_EDI_CODE_DESCRIPTION('SAC01',@SAC01) + ' $' + 
		@SAC05 + ' @RATE:' + @SAC08 + ')' ) 
	+ ' --> ' + 	@N903LI + IIF(ISNULL(@N902ZZ,'') = '', '', ' ('+@N902ZZ+')') 
	
	AS DETAIL
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE EDI.IDGROUP = @IDGROUP
AND EDI.WAREHOUSEID =	LEFT(@TRANSACTIONNUMBER,2)

