--PRICESCHEDULE CONSIGNEE SALESREP FOR SANDRA
SELECT
	WH.IDENTITYID AS WAREHOUSEID, 
	PSH.PRICESCHEDULECODE, PSH.DESCRIPTION, 
	CONS.IDENTITYID AS CONSIGNEEID, CONS.NAME AS CONSIGNEENAME, 
	PART.IDENTITYID AS SALESREPID, PART.NAME AS SALESREPNAME
FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) 
JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = SZ.R_PRICESCHEDULE 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = SZ.R_SHIPPER 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = SZ.R_CONSIGNEE 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT
ORDER BY 
	WH.IDENTITYID, 
	PSH.PRICESCHEDULECODE, PART.IDENTITYID  
