--HISTORICAL PLANTED OR SHIFTED BY FISCALYEAR
SELECT 
	WAREHOUSEID, FISCALYEAR, TRANSACTIONCODE, ePLANTCODE, CONTAINERCODE, SUM(QUANTITY) AS QUANITITY
FROM (
		--INSIGHT DATA
		SELECT
			WH.IDENTITYID AS WAREHOUSEID, 
			DATEPART(YEAR, DATEADD(MONTH,4,TH.TRANSACTIONDATE)) AS FISCALYEAR, 
			TD.USERDEFINEDCODE_1 AS TRANSACTIONCODE, 
			TH.REFERENCE AS ePLANTCODE, 
			CNT.CONTAINERCODE, 
			(TD.QUANTITY) AS QUANTITY
		FROM IMTRANSACTIONHEADER TH (NOLOCK) 
		JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE TD.USERDEFINEDCODE_1 IN ('Plant','Shift.IN') 
		AND WH.IDENTITYID = '20'
		AND TH.TRANSACTIONDATE BETWEEN '9/1/2017' AND '8/31/2023'

		UNION ALL

		--ePLANT DATA
		SELECT
			WH.IDENTITYID AS WAREHOUSEID, 
			DATEPART(YEAR, DATEADD(MONTH,4,HIST.TRANSACTIONDATE)) AS FISCALYEAR, 
			'' AS TRANSACTIONCODE, 
			HIST.TRANSACTIONREASONCODE AS ePLANTCODE, 
			CNT.CONTAINERCODE, 
			(HIST.ADJUSTMENTQUANTITY) AS QUANTITY

		FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
		JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
		JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		WHERE HIST.TRANSACTIONREASONCODE IN ('02','61') 
		AND WH.IDENTITYID = '20'
		AND HIST.TRANSACTIONDATE BETWEEN '9/1/2017' AND '8/31/2023'
	) U
GROUP BY WAREHOUSEID, FISCALYEAR, TRANSACTIONCODE, ePLANTCODE, CONTAINERCODE
ORDER BY WAREHOUSEID, FISCALYEAR, TRANSACTIONCODE, ePLANTCODE, CONTAINERCODE