--OrdersWithoutLots
SELECT 
	OH.TRANSACTIONNUMBER, OH.TRANSACTIONDATE, 
	OH.RECORDTYPE, OH.TRANSACTIONTYPE, OH.STAGE, 
	OD.LINENUMBER, ITM.ITEMCODE, LOT.LOTCODE
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT
WHERE OH.RECORDTYPE NOT IN ('P','I','E')
AND OH.TRANSACTIONTYPE = 'I'
AND OH.STAGE !='L'
--AND OH.STAGE NOT IN ('L','F')
AND LOT.LOTCODE IS NULL

