USE [ABECAS_GNC_PROD]
GO

/****** Object:  Trigger [dbo].[XMASCEXPENVELOPE_UPDATE]    Script Date: 10/3/2024 9:13:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE OR ALTER     TRIGGER [dbo].[XMASCEXPENVELOPE_UPDATE] ON [dbo].[XMASCEXPENVELOPE]
FOR UPDATE
AS
SET NOCOUNT ON

DECLARE
  @SYS_DATETIME DATETIME,
  @SYS_USER CHAR(50)
-- SET SYSTEM VARIABLES
SET @SYS_DATETIME = GETDATE()
SET @SYS_DATETIME = DATEADD(MS,(-1) * (DATEPART(MS, @SYS_DATETIME) % 10), @SYS_DATETIME)
SET @SYS_USER = SUBSTRING(RTRIM(SYSTEM_USER), PATINDEX('%\%', RTRIM(SYSTEM_USER))+1, 50)

UPDATE XMDOCUMENT
SET [FILENAME] =	--Update FILENAME with GNC required info. --07/02/21 DT
	CASE 
		WHEN CHARINDEX('855',MAPPINGID) > 0 THEN 'EP855_' +
			ISNULL((SELECT TRIM(IDGROUP) FROM IDMASTER WHERE ROWID = OH.R_CUSTOMER) + '_' + 
			ISNULL(OH.PURCHASEORDERNUMBER,'_____') + 
			IIF(OH.STAGE='L', 'CA', IIF(OH.EDITRANSMITFLAG = 'Y', 'CH', 'PO')), '') + 
			'_'
		WHEN CHARINDEX('810',MAPPINGID) > 0 THEN 'EP810_' 
		ELSE 'ExportDataFile_' 
	END +
CONVERT(VARCHAR(20),GETDATE(),112) + REPLACE(CONVERT(VARCHAR(12),GETDATE(),114),':','') + '.TXT',
LASTUPDATEDATETIME = @SYS_DATETIME,
LASTUPDATEUSERID = @SYS_USER
FROM INSERTED
JOIN XMDOCUMENT ON XMDOCUMENT.ROWID = INSERTED.R_DOCUMENT
LEFT OUTER JOIN XMASCEXPMAPDEF ON XMASCEXPMAPDEF.ROWID = INSERTED.R_ASCEXPMAPDEF
LEFT OUTER JOIN OMTRANSACTIONHEADER OH ON OH.ROWID = INSERTED.R_SOURCE
WHERE XMDOCUMENT.DIRECTION = 1
  AND XMDOCUMENT.DOCUMENTTYPE = 2
  AND XMDOCUMENT.[STATUS] = 0
  AND ISNULL(XMDOCUMENT.[FILENAME], '') = ''

SET NOCOUNT ON
GO

ALTER TABLE [dbo].[XMASCEXPENVELOPE] ENABLE TRIGGER [XMASCEXPENVELOPE_UPDATE]
GO


