SELECT DISTINCT TD.USERDEFINEDCODE_1
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
WHERE TD.USERDEFINEDCODE_1 = 'RECEIPT'

--COMPARING CYvPY IMTRANSACTION UNITS BY CODE_TYPE FOR PRODUCTION ANALYSIS FOR DONNY
--(USES CODE FROM VW_RPT_GP_LABORGROUP_PRODUCTION_ANALYSIS)

SELECT 
	WAREHOUSEID, 
	--ITEMCODE, CONTAINERCODE, SHIPPINGCLASSIFICATIONCODE, 
	CODE_TYPE,
	SUM(CY_UNITS) AS CY_YTD_UNITS,
	SUM(PY_UNITS) AS PY_YTD_UNITS
FROM (
	SELECT 
		'PY' AS YTD,
		TH.COMMITDATE,
		WH.IDENTITYID AS WAREHOUSEID, 
		ITM.ITEMCODE, CNT.CONTAINERCODE,
		TD.USERDEFINEDCODE_1 AS CODE_TYPE, 
		CNT.SHIPPINGCLASSIFICATIONCODE,
		(ISNULL(TD.QUANTITY,0)) AS CY_UNITS,
		0 AS PY_UNITS 
	FROM IMTRANSACTIONHEADER TH (NOLOCK) 
	JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
	AND (
		TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
		OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
		)
	--AND WH.IDENTITYID = '10'--WAREHOUSE 
	AND TH.COMMITDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE()))		--START-OF-CURRENTYEAR
	AND TH.COMMITDATE <= (	GETDATE() -					--TODAY
							(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
							)

	---------
	UNION ALL
	---------
	
	SELECT 
		'PY' AS YTD,
		TH.COMMITDATE,
		WH.IDENTITYID AS WAREHOUSEID, 
		ITM.ITEMCODE, CNT.CONTAINERCODE, 
		TD.USERDEFINEDCODE_1 AS CODE_TYPE,  
		CNT.SHIPPINGCLASSIFICATIONCODE, 
		0 AS CY_UNITS, 
		(ISNULL(TD.QUANTITY,0)) AS PY_UNITS 
	FROM IMTRANSACTIONHEADER TH (NOLOCK) 
	JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
	AND (
		TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
		OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
		)
	AND TH.COMMITDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1)	--START-OF-PREVIOUSYEAR
	AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
							)
) X
--WHERE WAREHOUSEID = '10'
GROUP BY
	WAREHOUSEID, 
	--ITEMCODE, CONTAINERCODE, SHIPPINGCLASSIFICATIONCODE, 
	CODE_TYPE
ORDER BY 
	WAREHOUSEID, 
	--ITEMCODE, CONTAINERCODE, SHIPPINGCLASSIFICATIONCODE, 
	CODE_TYPE
