--new funtion: DATE2SEASON

--F1	fn_YEAR2DATE()
--S1	12/1/YY
--U1	5/1/YY
--U2	6/15/YY
--U3	7/31/YY
--XYZ	7/31/YY

--Given a date, determine the SEASONCODE it belongs to:
--SELECT * FROM IMSEASONCODE SEA (NOLOCK) 
/*
AVAILABILITY_BY_LOCATION
AVAILABILITY_BY_LOCATION_STATIC
EDI_PO_NEW
INVENTORY_STATUS_CROPYEAR
INVENTORY_STATUS_QUANTITY
INVENTORY_STATUS_QUANTITY_STATIC
LEFT_TO_SELL
WEBSITE_AVAILABILITY
FN_SHIPPEDBYCYCLE


Notes on Reports using IMSEASONCODE table
----------------------------------------- 
LEFT_TO_SELL
                to calculate which season to use for: CURRENTSEASONSALESNOTEROLLUP
INVENTORY_STATUS_QUANTITY
                to calculate which season to use for: Current Supply and Demand values
AVAILABILITY_BY_LOCATION
                to select which LotYear/LotSeason to display for CurrentSeason, CurrentSeason+1, CurrentSeason+2
WEBSITE_AVAILABILITY
                to calculate CURRENT SEASON INFLATED LTS
EDI_PO_NEW
                to calculate the expected PROFILE to use for incoming EDI PO documents.

These are all based off of Start/End dates compared to current system date. If U2/U3 records do not exist neither will the data results.

INVENTORY_STATUS_CROPYEAR
                no longer uses IMSEASONCODE/ commented out
*/
--21.10.F1
SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.F1' AS SEASONCODE, 
DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, 
TRIM(STR(X.YR)) + '-12-01 00:00:00.000' AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.S1' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-12-01 00:00:00.000' AS STARTDATE, 
TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U1' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, 
TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U2' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, 
TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE ---WAS 07-31
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U3' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, ---WAS 07-31
DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.X' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, ---WAS 07-31
DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.Y' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, ---WAS 07-31
DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

UNION ALL

SELECT TRIM(STR(X.YR)) AS YEAR, 
RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.Z' AS SEASONCODE, 
TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, --WAS -07-31
DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
FROM (SELECT 2008+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

/*
------------------------------ 
-- FUNCTION: FN_DATE2SEASON 
------------------------------ 
-- RETURNS THE REPORT SEASON FROM THE DATE PARAMETER PASSED TO IT 
-- NULL DATE ASSUMES CURRENT DATE USING GETDATE() 
------------------------------ 
-- DON TAYLOR @ 12/11/2024 
------------------------------ 
-- EMBEDDED FN_YEAR2DATE() & FN_DATE2YEAR() LOGIC TO REDUCE FUNCTION DAISY CHAINS @10/14/21-DT 
------------------------------ 
CREATE OR ALTER FUNCTION [DBO].[FN_DATE2SEASON] 
( @INDATE DATETIME 
) RETURNS CHAR(20) 
AS 
BEGIN 

	-- LOCAL PARAMETERS -- 
	DECLARE @DATE		DATETIME 
	DECLARE @STARTDATE	DATETIME 
	DECLARE @YEAR		INTEGER 
	DECLARE @RESULT		CHAR(20) 
	IF @INDATE IS NULL 
		SET @INDATE = GETDATE() 
	SET @YEAR = DBO.FN_DATE2YEAR(@INDATE) 
	BEGIN 
			


	END 
	RETURN @RESULT 
END 
*/