
select distinct
			TRIM(WH.IDENTITYID) AS WAREHOUSEID,
			TRIM(WH.NAME) AS WAREHOUSENAME,
			LEFT(VLOT.LOTCODE,2) + 2000 AS SALEYEAR,
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			ITM.REFERENCE_1 AS COMMONNAME,
			--TRIM(VLOT.LOTCODE) AS LOTCODE,
			TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE
			
			--DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			--VLOT.OVERSELLPERCENTAGE,
			--VLOT.ON_HAND
			--VLOT.IN_RECEIVING,
			--VLOT.OUT_SHIPPED,
			--VLOT.OUT_UNAVAILABLE,
			--VLOT.AVAILABLE


		FROM --(SELECT DBO.FN_SALEYEAR(NULL)%100 AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW
			OMREVIEWMASTERCODES MC (NOLOCK)
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
			LEFT OUTER JOIN VW_IMLOTVIEW VLOT (NOLOCK) ON VLOT.ROWID = MC.R_LOT
			LEFT OUTER JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1	AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'--NOT LIKE 'TAG%'
ORDER BY
	WAREHOUSEID, SALEYEAR, ITEMCODE, COMMONNAME, LOCATIONCODE
