/*
SELECT NATIONALACCOUNT, CUSTOMERNUMBER, GROUPNAME, 
--						IIF	(NATIONALACCOUNT = 'Y', 
							--TRY TWICE TO GET MAJORGROUPNAME, FIRST BY CONSIGNEES PARENT CUSTOMERID, THEN BY CUSTOMER W/O CONSIGNEES TO INCLUDE TAGAWA (829574)
							ISNULL(
									(	SELECT TOP 1 CUST.REFERENCE2 
										FROM IDMASTER CONS (NOLOCK) 
										JOIN IDRELATIONSHIPLINKS LCONS (NOLOCK) ON LCONS.R_IDMEMBER = CONS.ROWID AND LCONS.IDMEMBERTYPE = '02' 
										JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = LCONS.R_IDMASTER 
										WHERE CONS.IDENTITYID = CUSTOMERNUMBER), 
									(	SELECT TOP 1 CUST.REFERENCE2 
										FROM IDMASTER CUST (NOLOCK) 
--I guess this fixes the customers like TAGAWA when other IDTYPES are defined for the customerid:
join IDTYPESLINKS link (nolock) on link.R_IDENTITY = cust.rowid and link.idtype = '01'
										WHERE CUST.IDENTITYID = CUSTOMERNUMBER) 
--								),
--							NULL) AS MAJORGROUPNAME, 
) AS MAJORGRPNAME
FROM GOALS_GROUP (NOLOCK)
WHERE SALEYEAR = 2024 
*/


--FIX GOALS_GROUP DATA WITH WRONG GROUPNAME
-------------------------------------------
SELECT *,  
	( 
		SELECT CUST.REFERENCE2 
		FROM IDMASTER CUST (NOLOCK) 
		--I guess this fixes the customers like TAGAWA when other IDTYPES are defined for the customerid:
		join IDTYPESLINKS link (nolock) on link.R_IDENTITY = cust.rowid and link.idtype = '01'
		WHERE CUST.IDENTITYID = CUSTOMERNUMBER
	)
FROM GOALS_GROUP (NOLOCK)
WHERE GROUPNUMBER = 355

BEGIN TRAN
UPDATE GOALS_GROUP 
SET GROUPNAME = ( 
		SELECT CUST.REFERENCE2 
		FROM IDMASTER CUST (NOLOCK) 
		--I guess this fixes the customers like TAGAWA when other IDTYPES are defined for the customerid:
		join IDTYPESLINKS link (nolock) on link.R_IDENTITY = cust.rowid and link.idtype = '01'
		WHERE CUST.IDENTITYID = CUSTOMERNUMBER
	)
FROM GOALS_GROUP 
WHERE GROUPNAME = 'Accounts Payables'
	
SELECT *,  
	( 
		SELECT CUST.REFERENCE2 
		FROM IDMASTER CUST (NOLOCK) 
		--I guess this fixes the customers like TAGAWA when other IDTYPES are defined for the customerid:
		join IDTYPESLINKS link (nolock) on link.R_IDENTITY = cust.rowid and link.idtype = '01'
		WHERE CUST.IDENTITYID = CUSTOMERNUMBER
	)
FROM GOALS_GROUP (NOLOCK)
WHERE GROUPNUMBER = 355

COMMIT--ROLLBACK TRAN

-----------------------------------------------------
--FIX GOALS_GROUP DATA WITH CUSTOMER# SETUP AS GROUP#
-----------------------------------------------------
SELECT *,
(	SELECT CUST.IDGROUP 
	FROM IDMASTER CUST (NOLOCK)
	JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
	WHERE CUST.IDENTITYID = GOALS_GROUP.GROUPNUMBER
	) AS REALGRP 
FROM GOALS_GROUP (NOLOCK)
WHERE SALEYEAR = 2024 

BEGIN TRAN
UPDATE GOALS_GROUP 
SET 
	CUSTOMERNUMBER = GROUPNUMBER,
	GROUPNUMBER = (	
		SELECT CUST.IDGROUP 
		FROM IDMASTER CUST (NOLOCK)
		JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
		WHERE CUST.IDENTITYID = GOALS_GROUP.GROUPNUMBER
	)
FROM GOALS_GROUP 
WHERE SALEYEAR = 2024

SELECT *,
(	SELECT CUST.IDGROUP 
	FROM IDMASTER CUST (NOLOCK)
	JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
	WHERE CUST.IDENTITYID = GOALS_GROUP.GROUPNUMBER
	) AS REALGRP 
FROM GOALS_GROUP (NOLOCK)
WHERE SALEYEAR = 2024 

--COMMIT--
ROLLBACK TRAN
