--FrtZoneCalculations_10-99533-9
select oh.TRANSACTIONNUMBER,
IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QUANTITYATSTAGE,
od.FREIGHTRATEPERITEM,
oh.R_ZONEFREIGHTRATEOVERRIDE, PSH.R_ZONE, 
zoncod.CODE, zoncod.DESCRIPTION,
DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE') AS FRTZONE,
(SELECT DESCRIPTION FROM IDFREIGHTCHARGES (NOLOCK) WHERE CHARGECODE LIKE 'FRTZONE') AS FRTZONE_TEXT,
DBO.FN_ORDERFREIGHT(OH.ROWID, NULL) AS FRTTOTAL,
NULLIF(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE') - 
IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,
	(SELECT NULLIF(SUM(ISNULL(OD2.FREIGHTRATEPERITEM,0) * ISNULL(OD2.QUANTITYSHIPPED,0)),0) 
	FROM OMTRANSACTIONDETAIL OD2 (NOLOCK) WHERE OD2.R_TRANSACTIONHEADER = OH.ROWID),
	(SELECT NULLIF(SUM(ISNULL(OD2.FREIGHTRATEPERITEM,0) * ISNULL(OD2.QUANTITYORDERED,0)),0) 
	FROM OMTRANSACTIONDETAIL OD2 (NOLOCK) WHERE OD2.R_TRANSACTIONHEADER = OH.ROWID)),0) AS MINIMUMFREIGHT_ADJ,
1
from OMTRANSACTIONHEADER OH (NOLOCK)
LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = VCONS.CONSIGNEEMASTERROWID AND SZ.R_SHIPPER = WH.ROWID
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, VCONS.CONSIGNEER_PRICESCHEDULE)
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
LEFT JOIN RTZONETABLECODES ZONCOD (NOLOCK) ON ZONCOD.ROWID = ISNULL(ISNULL(OH.R_ZONEFREIGHTRATEOVERRIDE, PSH.R_ZONE), SZ.R_ZONE)
where oh.TRANSACTIONNUMBER = '10-99533-9'