--IP ORDER RECORDS FROM ePLANT
SELECT 
IPH.INVENTORYPURCHASENUMBER, IPH.IPRELEASENUMBER, 
IPH.DIVISIONNUMBER, IPH.ORDERNUMBER, IPH.RELEASENUMBER,
IPH.SALEYEAR, IPH.SHIPPINGDIVISIONNUMBER, IPH.ALTERNATESHIPPINGDIVISION, 
IPH.UNLOADDATE, 
IPD.ITEMNUMBER, IPD.LINENUMBER, IPD.QUANTITYORDERED, 
IPD.PLANTINGTEXT, IPD.PLANTINGSCHEDULELINE, IPD.ACTUALPLANTEDDATE
  FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
  JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
ORDER BY
IPH.SALEYEAR, IPH.DIVISIONNUMBER, IPH.UNLOADDATE

--QUANTITY SUBTOTALS BY YEAR BY DIVISION:
SELECT 
IPH.SALEYEAR, IPH.DIVISIONNUMBER, 
--IPH.UNLOADDATE, 
SUM(IPD.QUANTITYORDERED) AS TOTALQTY 

  FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
  JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
WHERE IPH.SALEYEAR > 2017
GROUP BY 
IPH.SALEYEAR, IPH.DIVISIONNUMBER
ORDER BY
IPH.SALEYEAR, IPH.DIVISIONNUMBER

