--LABORGROUP_PRODUCTION_6YEAR NOTES

--SELECT COUNT(*) FROM GNC_ITEM_TRANSACTION_FULL	--6991202	--6284008	--5,399,551
--SELECT 6991202 - 6959080, 6959080 - 6284008
--ERROR ON LAST EXCEL AT ROW:675072 ONWARD
--SELECT * FROM GNC_ITEM_TRANSACTION_FULL WHERE TRANSACTIONID = 11438106

SELECT 
B.MAXID, 
B.SOFAR, B.GOAL, 
B.SOFAR/B.GOAL*100 AS PERCENT_COMPLETE
FROM (	
		SELECT 
			MAX(TRANSACTIONID) AS MAXID, 
			COUNT(*) AS SOFAR,
			CAST (893895 + 891985 + 909459 + 876303 + 946972 + 880937 + 884457 + 707194	AS numeric(12,2)) AS GOAL, 	--6991202
			893895 + 891985 + 909459 + 876303 + 946972 + 880937 + 884457 + 707194
			AS TEST
		FROM GNC_ITEM_TRANSACTION_FULL
	 )	B

--------------------------------------------------------------------------------------------------------------------------------------------------------
--INJECTION CODE FOR PRODUCTION REPORT ePLANT ADDONS:
--STOLE THIS CODE TO SEE IF THE GNC_ TABLES ARE BAD DATA...APPARENTLY THEY ARE BOTH INCOMPLETE!!!!!
						--(	
							SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0) )--*(ISNULL(CNT.VOLUME,.01)/615.99))
	--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST
	--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
	--FROM GNC_ITEM_TRANSACTION HIST (NOLOCK) 
	FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK)
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (   TRIM(HIST.TRANSACTIONREASONCODE) IN ('02','07','61')--,'25','26','60') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								)--OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)) 
					AND HIST.DIVISIONNUMBER = '10'
					AND HIST.TRANSACTIONDATE BETWEEN '06/23/2018' and '06/22/2019'


SELECT (DATEPART(DW,GETDATE())%7) AS SAT,
DATEDIFF(DAY, DBO.FN_YEAR2DATE(NULL), GETDATE()-(DATEPART(DW,GETDATE())%7)) AS DAYS,
(GETDATE() -	DBO.FN_YEAR2DATE(NULL) + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) - (DATEPART(DW,GETDATE())%7)) - (7*52) AS FROMDATE, 
GETDATE() -	DBO.FN_YEAR2DATE(NULL) + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) - (DATEPART(DW,GETDATE())%7) AS TODATE 
--SAT	DAYS	FROMDATE				TODATE
--3		328		2018-06-23 13:06:59.283	2019-06-22 13:06:59.283



--------------------------------------------------------------------------------------------------------------------------------------------------------

--INJECTION CODE FOR SHIPPING REPORT ePLANT ADDONS:
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT

