--SELECT * FROM (

--CURRENT WEEKLY TOTALS:
SELECT 'CurrWeekTotals' AS YEARTEXT, 
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS CY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS CY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--WEEK DATERANGE: 
					AND TH.COMMITDATE >= (	GETDATE() -				--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -6						--RANGE: 1 WEEK
					AND TH.COMMITDATE <= (	GETDATE() -				--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
GROUP BY WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--UNION ALL
-----------------------------------------------------------------------------------------------

--CURRENT YTD TOTALS:
SELECT 'CurrYTDTotals' AS YEARTEXT, 
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS CY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS CY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--YTD DATERANGE: 
					AND TH.COMMITDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE()))		--START-OF-CURRENTYEAR
					AND TH.COMMITDATE <= (	GETDATE() -					--TODAY
											(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
											)
GROUP BY WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--UNION ALL
-----------------------------------------------------------------------------------------------

--CURRENT 52WEEK TOTALS:
SELECT 'Curr52WkTotals' AS YEARTEXT, 
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS CY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS CY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--52WEEK DATERANGE: 
					AND TH.COMMITDATE >= (	GETDATE() -					--TODAY
											(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
											) -(7*52)					--RANGE: 52 WEEKS
					AND TH.COMMITDATE <= (	GETDATE() -					--TODAY
											(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
											)
GROUP BY WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--UNION ALL
-----------------------------------------------------------------------------------------------

--PREVIOUS WEEKLY TOTALS:
SELECT 
'PrevWeekTotals' AS YEARTEXT,
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS LY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS LY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--WEEK DATERANGE: 
					AND TH.COMMITDATE >= (	GETDATE() -										--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -6												--RANGE: 1 WEEK
					AND TH.COMMITDATE <= (	GETDATE() -										--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
GROUP BY
WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY 
WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--UNION ALL
-----------------------------------------------------------------------------------------------

--PREVIOUS YTD TOTALS:
SELECT 
'PrevYTDTotals' AS YEARTEXT,
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS LY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS LY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--YTD DATERANGE: 
					AND TH.COMMITDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1)	--START-OF-PREVIOUSYEAR
					AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
											(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
											)
GROUP BY
WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY 
WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--UNION ALL
-----------------------------------------------------------------------------------------------

--PREVIOUS 52WEEKS TOTALS:
SELECT 
'Prev52WkTotals' AS YEARTEXT,
WH.IDENTITYID AS WAREHOUSEID, 
TD.USERDEFINEDCODE_1 AS CODE,
SUM(ISNULL(TD.QUANTITY,0)) AS LY_UNITS,
SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS LY_EQUIVUNITS
FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN','Receipt')	--CODES TO FILTER PER DJ 10/20/23
AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
--AND WH.IDENTITYID = WAREHOUSE 
--52WEEK DATERANGE: 
					AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
											(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
											) -(7*52)											--RANGE: 52 WEEKS
					AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
											DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
											(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
											)
GROUP BY
WH.IDENTITYID, TD.USERDEFINEDCODE_1
ORDER BY 
WH.IDENTITYID, TD.USERDEFINEDCODE_1

-----------------------------------------------------------------------------------------------
--) X