--SCRIPT: AAA-RECALC-UNCOMMITTEDITEMAMOUNTS
SELECT 
	OH.RECORDTYPE, OH.STAGE, OH.FMTRIPNUMBER, OH.TRANSACTIONNUMBER, OD.LINENUMBER, ITM.ITEMCODE, 
	IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QTYATSTAGE, 
	oh.DEFAULTDETAILDISCOUNT, oh.DISCOUNTTYPE, od.DISCOUNTPERCENT, 
	dbo.FN_LISTPRICE(itm.ROWID,oh.SHIPPINGDATE,null) as listprice, 
	ISNULL(OD.UNITPRICE,0) AS UNITPRICE, 
	ISNULL(OD.HANDLINGCHARGEPERITEM,0) AS HANDLINGPRICE, 
	ISNULL(OD.TAGGINGCHARGEPERITEM,0) AS TAGGINGCHARGE, 
	IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) * 
		(	ISNULL(OD.UNITPRICE,0) + 
			ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
			ISNULL(OD.TAGGINGCHARGEPERITEM,0) 
		) AS CORRECTVALUE, 
	[DBO].FNOM_GETDETAILAMOUNTEXT	(	OD.COMPANYID, OD.R_TRANSACTIONHEADER, NULL, OD.UNITPRICE, 
										IIF(CHARINDEX(OH.STAGE,'A;S;C') > 0, ISNULL(OD.QUANTITYSHIPPED,0), ISNULL(OD.QUANTITYORDERED,0)), 
										0, OD.FOREIGNFEESADDED, OD.ARTRADEDISCOUNTFLAG, 'P', OD.HANDLINGCHARGEPERITEM, OD.TAGGINGCHARGEPERITEM
									) AS SAADVALUE,
	OD.AMOUNT

FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
WHERE [DBO].FNOM_GETDETAILAMOUNTEXT	(	OD.COMPANYID, OD.R_TRANSACTIONHEADER, NULL, OD.UNITPRICE, 
										IIF(CHARINDEX(OH.STAGE,'A;S;C') > 0, ISNULL(OD.QUANTITYSHIPPED,0), ISNULL(OD.QUANTITYORDERED,0)), 
										0, OD.FOREIGNFEESADDED, OD.ARTRADEDISCOUNTFLAG, 'P', OD.HANDLINGCHARGEPERITEM, OD.TAGGINGCHARGEPERITEM
									) <> ROUND(OD.AMOUNT,2) 
AND OH.RECORDTYPE != 'Z' 
ORDER BY RECORDTYPE, STAGE, FMTRIPNUMBER, TRANSACTIONNUMBER, LINENUMBER
------- 
/*
dependencies
------------
SPOM_STAGECHANGE
	SPOM_BUILDDETAILFROMITEMKITT
	SPOM_COMMIT
	SPOM_CREATESALESORDERS
	SPOM_DECREMENTDETAILQUANTITY
	SPOM_IMPORTXML
	SPOM_REPLICATEORDERS
	SPOM_UPDATEORDERSTAGE
SPOM_UPDATEPRICEONORDERS
SPOM_UPDATEPRICINGONOMDETAIL

depend on FNOM_GETDETAILAMOUNTEXT
--------------
FNOM_GETDETAILAMOUNT]
	OMTRANSACTIONHEADER]
	ACBATCH]
	FAFUND]
	IDSYNONYMS]
	OMCOMMITHISTORY]
	OMTRANSACTIONHEADER_AUDIT]
	POORDERHEADER]
		POOrderDetail]
			CAACTIVITY]
				CAACTIVITY]
			POORDERDETAILRATE]
				PORECEIPTSDETAIL]
					fnAC_CalculateExchangeRate]
						ACCURRENCY]
							ACACCOUNT]
								ABLAYOUT]
								ACACCOUNTDP]
							ACEXCHANGERATE]
								ACExchangeRateDetails]
				[IMSERIALNUMBER]
					IMITEM]
						...
				OMTRANSACTIONDETAIL]
					...
	RTZONETABLECODES]
*/