/* Sams Tagging Amounts for David Brandt */
SELECT 
	CUSTOMERID, CONSIGNEEID, TRANSACTIONNUMBER, TRANSACTIONDATE, TRANSACTIONTYPE, REVSIGN, 
	SUM(TAGGINGAMT*REVSIGN) AS TAGGINGAMT, SUM(ORDERTOTAL*REVSIGN) AS ORDERTOTAL
FROM (
	SELECT 
		CUST.IDENTITYID AS CUSTOMERID, 
		CONS.IDENTITYID AS CONSIGNEEID, 
		OH.TRANSACTIONNUMBER, 
		OH.TRANSACTIONDATE, 
		OH.TRANSACTIONTYPE, 
		IIF(OH.TRANSACTIONTYPE = 'I', 1, -1) AS REVSIGN,	--REVERSE THE SIGN FOR ADJUSTMENTS AND CREDITS
		DBO.FN_ORDERVALUE(OH.ROWID,'TAGGING') AS TAGGINGAMT,
		DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL

	FROM OMTRANSACTIONHEADER OH (NOLOCK) 
	JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
	JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
	WHERE OH.RECORDTYPE = 'Z'
	--AND CUST.IDENTITYID = '10356'
) X
WHERE ISNULL(TAGGINGAMT,0) !=0
GROUP BY 	CUSTOMERID, CONSIGNEEID, TRANSACTIONNUMBER, TRANSACTIONDATE, TRANSACTIONTYPE, REVSIGN 
ORDER BY TRANSACTIONDATE