--SALESREP OVERRIDE TRANSACTIONS
SELECT 
	OH.RECORDTYPE, 
	WH.IDENTITYID AS WHID, 
	OH.TRANSACTIONNUMBER, 
	OH.TRANSACTIONDATE, 
	DBO.FN_DATE2YEAR(OH.TRANSACTIONDATE) AS REPORTYEAR, 
	DBO.FN_DATE2PERIOD(OH.TRANSACTIONDATE) AS REPORTPERIOD, 
	DBO.FN_DATE2WEEK(OH.TRANSACTIONDATE) AS REPORTWEEK, 
	ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS NATLACCT, 
	CUST.IDGROUP AS CUSTGROUP, 
	CUST.IDENTITYID AS CUSTOMERID, CUST.NAME AS CUSTOMERNAME, 
	CONS.IDENTITYID AS CONSIGNEEID, CONS.NAME AS CONSIGNEENAME, 
	ICONS.USERDEFINEDCODE_12 AS TERRITORY, 
	ACONS.CITY, ACONS.STATE, 
	PART.IDENTITYID AS OVERRIDEREPID, 
	PART.NAME AS OVERRIDEREPNAME, 
	IPART.IDENTITYID AS CURRENTREPID, 
	IPART.NAME AS CURRENTREPNAME, 
	DBO.FN_ORDERVALUE(OH.ROWID, NULL) AS ORDERTOTAL
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
JOIN IDADDRESS ACONS (NOLOCK) ON ACONS.ROWID = CONS.R_DEFAULTADDRESS
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1 
JOIN IDMASTER IPART (NOLOCK) ON IPART.ROWID = ICONS.R_PARTICIPANT 
WHERE PART.IDENTITYID != IPART.IDENTITYID
AND OH.RECORDTYPE NOT IN ('P','I','E')
ORDER BY OH.TRANSACTIONDATE 
