--Tracking Credit_Debits for Landon
/*
select * from VW_RPT_SQL_ACTUALS
where REPORTGROUP = 2 and REPORTLINE = 3
order by WAREHOUSEID, SALEYEAR, TRANSACTIONDATE
*/
--2.3 Credit & Debit Memos
SELECT
2 AS REPORTGROUP,
3 AS REPORTLINE,
'Credit & Debit Memos' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
oh.TRANSACTIONNUMBER, 
-1*(OD.UNITPRICE*OD.QUANTITYSHIPPED) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE<>'I' --EXCLUDING ORDERS/INVOICES (CREDIT MEMOS ONLY)
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,3)<>'VIP' --EXCLUDING VIP CREDIT MEMOS
-----------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^-----------------
-- VIP CREDITS ARE DONE IN THE AR MODULE NOW WITH A TRANSACTIONNUMBER STARTING WITH 'VIP' --
-- STILL FILTERING OUT 'VIP' TRANSACTIONS IN OM MODULE EVEN THOUGH THEY SHOULDN'T EXIST   --
--------------------------------------------------------------------------------------------
order by WH.IDENTITYID, OH.INVOICEDATE
