SELECT * FROM (
SELECT OH.RECORDTYPE, OH.STAGE, OH.TRANSACTIONDATE, OH.TRANSACTIONNUMBER, ITM.ITEMCODE, IL.R_TRANSACTIONDETAIL, COUNT(*) AS SUBLOCCNT

FROM OMTRANSACTIONHEADER OH (NOLOCK)
	LEFT OUTER JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
	LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
	LEFT OUTER JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
	WHERE OH.RECORDTYPE NOT IN ('P','I','E')
	AND OH.STAGE NOT IN  ('L','C')
	--AND oh.TRANSACTIONNUMBER = '20-97885'
GROUP BY OH.RECORDTYPE, OH.STAGE, OH.TRANSACTIONDATE, OH.TRANSACTIONNUMBER, ITM.ITEMCODE, IL.R_TRANSACTIONDETAIL
) X
WHERE SUBLOCCNT > 1
ORDER BY RECORDTYPE, STAGE, TRANSACTIONDATE, TRANSACTIONNUMBER, ITEMCODE, R_TRANSACTIONDETAIL


/*
select 
oh.TRANSACTIONNUMBER, OH.RECORDTYPE, OH.STAGE, OH.TRANSACTIONDATE, 
itm.ITEMCODE, 
il.rowid, il.LASTUPDATEDATETIME, il.LASTUPDATEUSERID, R_TRANSACTIONDETAIL, il.R_ITEM, il.R_LOT, il.R_LOCATION, il.R_WAREHOUSE, il.OUT_SHIPPED, il.OUT_BACKORDER

FROM OMTRANSACTIONHEADER OH (NOLOCK)
	LEFT OUTER JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
	LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
--	LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = IL.R_LOCATION
	LEFT OUTER JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
where 1=1--transactionnumber = '10-90759-14'
and oh.TRANSACTIONNUMBER = '20-97885'
and itemcode = '006449.031.1'
*/