--LIST AVAILABLE ITEMS INSTOCK
SELECT  
WHID, --PLANTGROUP, SORTNAMEVARIETY, 
ITEMCODE, COMMONNAME, SIZE, LISTPRICE, LTS 
FROM (
		SELECT * 
		FROM (
				SELECT *, DBO.FN_SUPPLYROLLUP(ITMROWID,NULL,NULL,NULL,'I') - DBO.FN_DEMANDROLLUP(ITMROWID,NULL,NULL,NULL) AS LTS 
				FROM (
						SELECT * 
						FROM (
								SELECT 
									WH.IDENTITYID AS WHID,
									PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
									ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
									ITM.ITEMCODE, 
									ITM.REFERENCE_1 AS COMMONNAME, 
									CNT.PRINTEDCONTAINERCODE AS SIZE, 
									DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
									ITM.ROWID AS ITMROWID
								FROM IMITEM ITM (NOLOCK) 
								JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
								JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
								LEFT OUTER JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
								LEFT OUTER JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
								WHERE ITM.STATUS = 'A'
								AND WH.IDENTITYID IN ('10', '20', '40', '60') 
							) T --TEST PRICES
					) P --ONLY PRICED ITEMS
				WHERE ISNULL(LISTPRICE, 0) > 0
			) V --VALIDATE LTS 
	) X --ONLY INSTOCK ITEMS
WHERE LTS > 0
--AND ITEMCODE IN ('004832.031.1', '000360.030.1', '004657.021.1', '004657.031.1', '008118.070.1', '000824.070.1')

ORDER BY WHID, PLANTGROUP, SORTNAMEVARIETY, ITEMCODE 
