--RodsOrder
SELECT CUST.IDENTITYID AS CUSTID, OH.RECORDTYPE, TRIM(OH.FMTRIPNUMBER) + '.' + TRIM(STR(OH.FMPUSTOPNUMBER)) AS TRIPSTOP, oh.SHIPPINGDATE AS SHIPDATE, 
(		SELECT TOP 1 FMCODES.DESCRIPTION_1 
		FROM FMTRIPHEADER TH (NOLOCK)
		JOIN FMCODES (NOLOCK) ON FMCODES.CODETYPE = '52' AND FMCODES.CODE = TH.USERDEFINEDCODE_2 
		WHERE TH.TRIPNO = OH.FMTRIPNUMBER 
) AS DOCK, 
OH.TRANSACTIONNUMBER, OH.USERDEFINEDREFERENCE_3 AS ORDEREDBY, 
OD.LINENUMBER, ITM.ITEMCODE, ITM.REFERENCE_1 AS COMMONNAME, OD.QUANTITYSHIPPED, 
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS UNITPRICE, OD.AMOUNT, 
DBO.FN_ORDERVALUE(OH.ROWID,'QUANTITYATSTAGE') AS ITEMCOUNT,
DBO.FN_ORDERVALUE(OH.ROWID,'LANDED') AS ORDERMERCH,
DBO.FN_ORDERVALUE(OH.ROWID,'SALESTAX') AS ORDERSALESTAX,
DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
WHERE CUST.IDENTITYID = '52211' 
AND OH.TRANSACTIONNUMBER = '10-80088'--'10-78893' 
ORDER BY OH.TRANSACTIONDATE DESC 

