--SiteOneEDIErrors
select 
oh.TRANSACTIONNUMBER, oh.PURCHASEORDERNUMBER, 
od.LINENUMBER, itm.ITEMCODE, psh.PRICESCHEDULECODE, psd.ALTERNATESKU
from OMTRANSACTIONHEADER oh (nolock) 
join OMTRANSACTIONDETAIL od (nolock) on od.R_TRANSACTIONHEADER = oh.rowid 
join imitem itm (nolock) on itm.rowid = od.R_ITEM 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = ICONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID 
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 
where oh.TRANSACTIONNUMBER in (
'20-72949-29         ',
'40-72941-34         ')

