--ePLANT SHIPPED OUT OF NEW CROP FOR ELLEN
SELECT 
	GNC.DIVISIONNUMBER, 
	GNC.SALEYEAR, 
	GNC.TRANSACTIONDATE, 
	GNC.ITEMNUMBER, 
	(	SELECT ITM.REFERENCE_1 
		FROM IMITEM ITM (NOLOCK)
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		WHERE ITM.ITEMCODE = GNC.ITEMNUMBER
		AND WH.IDENTITYID = GNC.DIVISIONNUMBER
		) AS COMMONNAME, 
	GNC.TOLOCATION, 
	GNC.TRANSACTIONREASONCODE, 
	GNC.ADJUSTMENTQUANTITY 
FROM GNC_ITEM_TRANSACTION GNC (NOLOCK) 
WHERE GNC.DIVISIONNUMBER = '10' 
AND GNC.SALEYEAR = '2021' 
AND SUBSTRING(GNC.TOLOCATION,20,1) = '=' 
AND GNC.TRANSACTIONREASONCODE = '5' 
ORDER BY 
	GNC.ITEMNUMBER, 
	GNC.TOLOCATION 
