/* LOTS2CLEAR FOR ELLEN */
SELECT *
FROM VW_RPT_HOLDSTOP_ITEMLOT V (NOLOCK)
WHERE LOTYEAR < 23 AND ON_HAND = 0 AND 
(		PULLTAGSUSPEND IS NOT NULL 
	OR	SUSPENDTO IS NOT NULL 
	OR	SPECIALPULLER IS NOT NULL 
	OR	PULLTAGNOTE1 IS NOT NULL 
	OR	PULLTAGNOTE2 IS NOT NULL 
	OR	HOLDSTOPCODE IS NOT NULL 
	OR	HOLDSTOPSTARTDATE IS NOT NULL 
	OR	HOLDSTOPENDDATE IS NOT NULL 
	OR	HOLDSTOPREASON IS NOT NULL 
	OR	HSREASONSTARTDATE IS NOT NULL 
	OR	HSREASONENDDATE IS NOT NULL 
	OR	INVENTORYNOTE IS NOT NULL 
	OR	INVNOTESTARTDATE IS NOT NULL 
	OR	INVNOTEENDDATE IS NOT NULL 
	OR	SALESNOTE IS NOT NULL 
	OR	SALESNOTESTARTDATE IS NOT NULL 
	OR	SALESNOTEENDDATE IS NOT NULL 
)
ORDER BY
WAREHOUSEID, LOTYEAR, GNC_ITEMSORT
