--LOT_ITEM_WH_DATES
SELECT 
	WH.IDENTITYID AS WAREHOUSEID, 
	ITM.ITEMCODE, 
	LOT.LOTCODE, 
	SEA.STARTDATE AS SEASON_STARTDATE, 
	SEA.ENDDATE AS SEASON_ENDDATE,
	LOT.DATEINTRODUCED AS LOT_DATEINTRODUCED,
	LOT.DATEAVAILABLE AS LOT_DATEAVAILABLE,
	LOT.DATEEXPIRATION AS LOT_DATEEXPIRATION
FROM IMLOT LOT (NOLOCK)
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = LOT.R_ITEM
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	JOIN IMSEASONCODE SEA (NOLOCK) ON	LEFT(SEA.SEASONCODE, 3) + RIGHT(SEA.SEASONCODE,2) = LOT.LOTCODE 
									AND SUBSTRING(SEA.SEASONCODE, 4, 2) = WH.IDENTITYID
WHERE WH.IDENTITYID = '40'
