/*
NEWCROPRELEASEDANDINVOICED4CAITLIN
--alternatively she can use SalesOnCommandEXCEL report to get this:
SELECT *
FROM VW_RPT_SALES_ON_COMMAND (NOLOCK)
WHERE TRANSACTIONTYPE = 'I'
and warehouseid = '40'
and descriptorcode like '%=%'
and recordtype = 'Z'

*/
SELECT 
WH.IDENTITYID AS WAREHOUSEID, 
WH.NAME AS WAREHOUSENAME, 
OH.RECORDTYPE, 
OH.TRANSACTIONTYPE, 
OH.TRANSACTIONNUMBER, 
OH.INVOICEDATE, 
OD.LINENUMBER, 
ITM.ITEMCODE, ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigItem'),'') AS DESIGITEM, 
ITM.REFERENCE_1 AS COMMONNAME, 
OD.QUANTITYSHIPPED, 
ISNULL(OD.UNITPRICE,0) + ISNULL(OD.HANDLINGCHARGEPERITEM,0) + ISNULL(OD.TAGGINGCHARGEPERITEM,0) AS ITEMPRICE, 
OD.FREIGHTRATEPERITEM AS ITEMFREIGHT, 
OD.AMOUNT AS EXTMERCH, 
OD.EFFECTIVEFREIGHT, 
ISNULL(OD.AMOUNT,0) + ISNULL(OD.EFFECTIVEFREIGHT,0) AS EXTCOST 

FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER

WHERE WH.IDENTITYID = '40'
AND ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigItem'),'') = '='
AND OH.RECORDTYPE = 'Z'