--script to fix groupname in GOALS_GROUP uploads
SELECT goal.*, 
--CUST.IDENTITYID AS CUSTOMERID,
--CUST.NAME AS CUSTOMERNAME,
--CUST.IDGROUP AS GROUPID,
GRP.DESCRIPTION_1 AS GROUPNAME--, 
--ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS NATLACCT
FROM GOALS_GROUP goal (nolock) 
join IDMASTER CUST (NOLOCK) on cust.identityid = goal.CUSTOMERNUMBER
--JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'
where goal.GROUPNAME != grp.DESCRIPTION_1
--and goal.SALEYEAR = '2025' --and goal.GROUPNUMBER in ('456','435','532')
ORDER BY saleyear, IDGROUP

begin tran

update GOALS_GROUP 
set GROUPNAME = grp.description_1
FROM GOALS_GROUP goal (nolock) 
join IDMASTER CUST (NOLOCK) on cust.identityid = goal.CUSTOMERNUMBER
--JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'
where goal.GROUPNAME != grp.DESCRIPTION_1
--and goal.SALEYEAR = '2025' --and goal.GROUPNUMBER in ('456','435','532')

SELECT goal.*, 
--CUST.IDENTITYID AS CUSTOMERID,
--CUST.NAME AS CUSTOMERNAME,
--CUST.IDGROUP AS GROUPID,
GRP.DESCRIPTION_1 AS GROUPNAME--, 
--ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS NATLACCT
FROM GOALS_GROUP goal (nolock) 
join IDMASTER CUST (NOLOCK) on cust.identityid = goal.CUSTOMERNUMBER
--JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'
where goal.GROUPNAME != grp.DESCRIPTION_1
--and goal.SALEYEAR = '2025' --and goal.GROUPNUMBER in ('456','435','532')

ORDER BY saleyear, IDGROUP

--commit--
rollback tran