/*	RUNTIME 0:38
--63 Grower Hold Stop/Grower Hold Stop EXCEL
SELECT * 
FROM VW_RPT_GROWER_HOLDSTOP (NOLOCK) 
WHERE ISACTIVE IS NOT NULL 
--

-- 63 Grower Hold Stop - Loc Sort
SELECT * 
----, TRIM(LOCATIONCODE) + TRIM(LOTCODE) + SOURCE + ISNULL(DESIGICL,'') AS MC_LOCATIONSORT --This was the original spec
FROM VW_RPT_GROWER_HOLDSTOP (NOLOCK) 
WHERE ISACTIVE IS NOT NULL
--

----------------------------------------
-- 63 Grower Hold Stop - Inv Evaluator
SELECT *, 
NULLIF(ISNULL(LOCATIONNOTE,''),'') + ' [' + ISNULL(LOCNOTEDATE,'') + ']' AS LOCNOTETEXT, 
TRIM(SUBSTRING(
	IIF(SEASONCODE = 'F1' OR F1_LTS = 0,'','/F1:'+TRIM(STR(F1_LTS)))+
	IIF(SEASONCODE = 'S1' OR S1_LTS = 0,'','/S1:'+TRIM(STR(S1_LTS)))+
	IIF(SEASONCODE = 'U1' OR U1_LTS = 0,'','/U1:'+TRIM(STR(U1_LTS)))+
	IIF(SEASONCODE = 'U2' OR U2_LTS = 0,'','/U2:'+TRIM(STR(U2_LTS)))+
	IIF(SEASONCODE = 'U3' OR U3_LTS = 0,'','/U3:'+TRIM(STR(U3_LTS)))+
	IIF(SEASONCODE = 'X' OR X_LTS = 0,'','/X:'+TRIM(STR(X_LTS)))+
	IIF(SEASONCODE = 'Y' OR Y_LTS = 0,'','/Y:'+TRIM(STR(Y_LTS)))+
	IIF(SEASONCODE = 'Z' OR Z_LTS = 0,'','/Z:'+TRIM(STR(Z_LTS))) 
	,2,100)) AS OTHERSEASONS
FROM VW_RPT_GROWER_HOLDSTOP (NOLOCK) 
WHERE ISACTIVE IS NOT NULL
--

----------------------------------------

-- Hold Stop DAILY by Item
SELECT * 
FROM VW_RPT_GROWER_HOLDSTOP (NOLOCK) 
WHERE ISACTIVE IS NOT NULL
AND ( 
	HSREASONSTARTDATE = CAST (GETDATE()-1 AS DATE) 
	OR HOLDSTOPSTARTDATE = CAST (GETDATE()-1 AS DATE) 
	) 
--

--Grower Hold Stop DAILY (used by Task Agent Daily to email to a list of users)
SELECT * 
FROM VW_RPT_GROWER_HOLDSTOP (NOLOCK) 
WHERE ISACTIVE IS NOT NULL 
AND HOLDSTOPSTARTDATE = CAST (GETDATE()-1 AS DATE) 
order by 
warehouseid, growercode, 
isactive, mc_locationsort
--AND ( 
--	HSREASONSTARTDATE = CAST (GETDATE()-1 AS DATE) 
--	OR HOLDSTOPSTARTDATE = CAST (GETDATE()-1 AS DATE) 
--	) 
--
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_GROWER_HOLDSTOP]
AS
SELECT 
	--IIF(HSREASONSTARTDATE > HOLDSTOPSTARTDATE, 'REASON', SUBSTRING('HOLD  STOP  ',1+(CHARINDEX(HOLDSTOPCODE,'HS')-1)*6, 6)) AS BREAKTEXT, 
	SUBSTRING(BREAKSORT,3,6) AS BREAKTEXT,
	TRIM(LOCATIONCODE) + SOURCE + ISNULL(DESIGICL,'') AS MC_LOCATIONSORT, 
	*
FROM	(
		SELECT 
			CO.COMPANYID,
			CO.NAME AS COMPANYNAME,
			ITM.RECORDTYPE,
			NULLIF(ISNULL(LOT.USERDEFINEDCODE_3,''),'') AS ISACTIVE,

			IIF(LOT.USERDEFINEDDATE_4 > LOT.USERDEFINEDDATE_1, 
					'3.REASON', 
					SUBSTRING('1.HOLD  2.STOP  ',1+(CHARINDEX(LOT.USERDEFINEDCODE_3,'HS')-1)*8, 8)) 
					AS BREAKSORT, 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
			TRIM(WH.IDENTITYID) AS WAREHOUSEID,
			TRIM(WH.NAME) AS WAREHOUSENAME,
			LOC.SUBCLASSCODE AS GROWERCODE,
			GROW.DESCRIPTION_1 AS GROWERNAME,
			ITM.USERDEFINEDCODE_1 AS GENUSCODE,
			GEN.DESCRIPTION_1 AS GENUSNAME,
			SUBSTRING(PGC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
			ITM.REFERENCE_5 AS SORTNAME,--VARIETY,
			CNT.CONTAINERSORT,
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
			CNT.CONTAINERCODE,
			TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,
			CNT.PRINTEDCONTAINERCODE AS CONTSIZE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.DESCRIPTION_1 AS SHORTCOMMON,
			ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			ITM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY, 
			TRIM(ITM.SPECIFICATIONCODE) AS ITEMSPEC,
			ITM.USERDEFINEDCODE_2 AS BRAND, 
			ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
			TRIM(LOT.LOTCODE) AS LOTCODE,
			LEFT(LOT.LOTCODE,2) AS LOTYEAR,
			SUBSTRING(LOT.LOTCODE,4,4) AS LOTSEASON,
			TRIM(LOT.USERDEFINEDCODE_10) AS SEASONCODE, 
			LOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
			LOT.USERDEFINEDDATE_1 AS HOLDSTOPSTARTDATE,
			LOT.USERDEFINEDDATE_2 AS HOLDSTOPENDDATE,
			DATEDIFF(D, LOT.USERDEFINEDDATE_1, GETDATE()) AS DAYSONHS,
			LOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
			LOT.USERDEFINEDDATE_4 AS HSREASONSTARTDATE,
			LOT.USERDEFINEDDATE_5 AS HSREASONENDDATE,
			LOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE,
			LOT.USERDEFINEDDATE_8 AS INVNOTESTARTDATE,
			LOT.USERDEFINEDDATE_9 AS INVNOTEENDDATE,
			LEFT(LOC.LOCATIONCODE,1) AS BLOCKALPHA,
			TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGCUST') AS DESIGCUST,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGITEM') AS DESIGITEM,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGLOC') AS DESIGLOC,
			--CONCATENATE DESIGNATORS TO FIT AS ELLEN WANTS:
			NULLIF(
				ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem'),'')+'.'+
				ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust'),'')+'.'+
				ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc'),''),
				'..') AS DesigICL,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'PRIORITY') AS PRIORITY,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCNOTEDATE') AS LOCNOTEDATE,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCATION NOTE') AS LOCATIONNOTE,
------------------------------------------------------------------
--ADDITIONAL FIELDS FOR THE INV EVALUATOR VERSION OF THIS REPORT
------------------------------------------------------------------
			DBO.FN_MCATTRIBUTES(MC.ROWID,'SuspendTo') AS SUSPENDTO, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'Special Puller') AS SPECIALPULLER, 
			DBO.FN_SALESNOTE(ITM.ROWID,LOT.ROWID,NULL) AS FNSALESNOTE,
			LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
			ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'LocationPTN1'), ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'PullTagNote1'), LOT.USERDEFINEDREFERENCE_1)) AS PULLTAGNOTE1, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LocationPTN1') AS LOCPULLTAGNOTE1,
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				AS SEASONLTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'F1%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'F1%', NULL) AS F1_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'S1%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'S1%', NULL) AS S1_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U1%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U1%', NULL) AS U1_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U2%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U2%', NULL) AS U2_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U3%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'U3%', NULL) AS U3_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'X%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'X%', NULL) AS X_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'Y%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'Y%', NULL) AS Y_LTS, 
			DBO.FN_SUPPLYROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'Z%', NULL, NULL) - DBO.FN_DEMANDROLLUP(MC.R_ITEM, LEFT(LOT.LOTCODE,2), 'Z%', NULL) AS Z_LTS, 
------------------------------------------------------------------
			--(SELECT SUM(COMMITTEDQUANTITY) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_MASTERCODE = MC.ROWID) AS INSHIPQUANTITY
			DBO.FN_MCATTRIBUTES_IA(MC.ROWID,'IN SHIPPING') AS INSHIPQUANTITY,	--SPECIAL ATTRIBUTE
			--DBO.FN_MCATTRIBUTES(MC.ROWID,'IN SHIPPING') AS INSHIPQUANTITY,	--SPECIAL ATTRIBUTE
			MC.PRODUCTIONQUANTITY AS QUANTITY,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL)*MC.PRODUCTIONQUANTITY AS EXTLISTPRICE

		FROM OMREVIEWMASTERCODES MC (NOLOCK)
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT
		LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
		JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
		LEFT JOIN IMCODES GROW (NOLOCK) ON GROW.CODE = LOC.SUBCLASSCODE AND GROW.CODETYPE = '27'
		JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE ITM.RECORDTYPE <> 'P'
		AND MC.PRODUCTIONQUANTITY <> 0	--QUANTITY FIELD FROM OMREVIEWMASTERCODES TABLE
		--AND LOC.SUBCLASSCODE IS NOT NULL	--GROWERCODE
		--AND LOT.USERDEFINEDCODE_3 IS NOT NULL	--HOLDSTOPCODE
		) X