/*
--64 GROWER THROWAWAY (SEVERAL VERSIONS)
SELECT *
FROM VW_RPT_GROWER_THROWAWAY (NOLOCK)
WHERE ISTHROWAWAY = 'Y'

--64 INVENTORY TRANSACTIONS EXCEL
SELECT *
FROM VW_RPT_GROWER_THROWAWAY (NOLOCK)
WHERE --COMPANYID = 'SB'
--AND 
WAREHOUSEID = '60'
--AND TRANSACTIONDATE BETWEEN '08/01/2021' AND '07/30/2022'

REPORT VERSIONS					PB	SUBTOTAL/SORT
------------------------------	---	---------------
INVENTORY TRANSACTIONS EXCEL		GNC_ITEMSORT
GROWER THROWAWAYS				NO	GNC_ITEMSORT
GROWER THROWAWAY BY ITEM		YES	GROWER/GNC_ITEMSORT
GROWER THROWAWAY BY GENUS		YES	GROWER/GENUS
GROWER THROWAWAY BY LOCATION	YES	GROWER/LOCATION
123456789012345678901234567890
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_GROWER_THROWAWAY]
AS
SELECT	
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	TH.RECORDTYPE,
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
	--Temporary override to include more records for Testing Purposes:
	'Y' AS ISTHROWAWAY,
	--IIF(LEFT(TD.USERDEFINEDCODE_1,1)='T', 'Y', NULL) AS ISTHROWAWAY,
	LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE,
	TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUP,
	TRIM(ITM.ITEMCODE) AS ITEMCODE,
	CNT.CONTAINERCODE,
	CNT.PRINTEDCONTAINERCODE,
	CNT.CONTAINERSORT,
	TRIM(ITM.SUBCLASSCODE) AS QUALITY,
	ITM.REFERENCE_1 AS COMMONNAME,
	ITM.REFERENCE_2 AS BOTANICALNAME,
	ITM.USERDEFINEDCODE_2 AS BRAND,
	ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
	TD.QUANTITY,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,TD.QUANTITY) AS LISTPRICE,
	TD.QUANTITY * DBO.FN_LISTPRICE(ITM.ROWID,NULL,TD.QUANTITY) AS EXTLISTPRICE,
	TH.MODULE AS PROGRAMMODULE,
	TH.TRANSACTIONTYPE,
	TR.DESCRIPTION_2 AS TRANSCODELINK,	--(LINK TO ePLANT)
	TRIM(TD.USERDEFINEDCODE_1) AS TRANSCODE,
	TR.DESCRIPTION_1 AS TRANSCODEDESC,
	TD.USERDEFINEDREFERENCE_2 AS TRANSTEXT,
	TD.USERDEFINEDREFERENCE_1 AS PLANTSCHEDLINE,
	TH.TRANSACTIONDATE,
	TH.REFERENCE,
	TH.DESCRIPTION AS PROFILEDESCRIPTION,
	TH.STAGE,
	TH.STATUS,
	TRIM(LOT.LOTCODE) AS LOTCODE,
	LOT.USERDEFINEDCODE_6 AS SALEYEAR,
	LOT.USERDEFINEDCODE_10 AS SEASON,
	TD.USERDEFINEDCODE_2 AS SOURCE,
	LOC.CLASSCODE AS ALPHA,
	TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE,
	TD.USERDEFINEDCODE_4 AS ITEMDESIG,
	TD.USERDEFINEDCODE_3 AS CUSTDESIG,
	TD.USERDEFINEDCODE_5 AS LOCDESIG,
	TRIM(ITMDP.PROFILECODE) AS VARIETYCODE,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	ITM.USERDEFINEDCODE_1 AS GENUS,
	GEN.DESCRIPTION_1 AS GENUSNAME,
	TRIM(WH.IDENTITYID) AS WAREHOUSEID,
	TRIM(WH.NAME) AS WAREHOUSENAME,
	LOC.SUBCLASSCODE AS GROWER,
	GROW.DESCRIPTION_1 AS GROWERNAME,
	LOC.USERDEFINEDCODE_1 AS GROWER2,
	TD.CREATIONUSERID,
	DBO.FN_DATE2PERIOD(TH.TRANSACTIONDATE) AS TRANSACTIONPERIOD,
	DBO.FN_DATE2WEEK(TH.TRANSACTIONDATE) AS TRANSACTIONWEEK,
	RIGHT('0'+TRIM(STR(DBO.FN_DATE2PERIOD(TH.TRANSACTIONDATE)))+TRIM(STR(DBO.FN_DATE2WEEK(TH.TRANSACTIONDATE))),3) AS TRANSACTIONPERIODWEEK
FROM IMTRANSACTIONHEADER TH (NOLOCK)
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID
JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = TD.ROWID
JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM
JOIN IMITEMDP ITMDP (NOLOCK) ON ITMDP.ROWID = ITM.R_PROFILE
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = TH.COMPANYID
LEFT JOIN IMCODES TR (NOLOCK) ON TR.CODE = TD.USERDEFINEDCODE_1 AND TR.CODETYPE = '21'		--TRANSCODEDESC&LINK
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
LEFT JOIN IMCODES GROW (NOLOCK) ON GROW.CODE = LOC.SUBCLASSCODE AND GROW.CODETYPE = '27'	--GROWERNAME
WHERE TH.RECORDTYPE = 'Z'
--ORDER BY
--		TH.TRANSACTIONDATE
--		LOC.SUBCLASSCODE,		--GROWER
--		PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE	--GNCSORT
--		ITM.USERDEFINEDCODE_1	--GENUS
--		LOC.LOCATIONCODE		--LOCATION
