--LAST UPDATE: CASTING TRANSACTIONDATE[DATETIME] AS DATE -- DT 5/10/22

--ISN'T THERE OVERRIDE LOGIC TO CONSIDER FOR OH.SALESPERSON_1? THIS C/B AN ISSUE LATER. DT 9/17/21
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_ACTUALS]
AS
--1.1 Shipments
SELECT
1 AS REPORTGROUP,
1 AS REPORTLINE,
'Shipments' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
--(OD.UNITPRICE*OD.QUANTITYSHIPPED) AS AMOUNT, 
(ISNULL(DBO.FN_LISTPRICE(ITM.ROWID,OH.INVOICEDATE,NULL),0) * OD.QUANTITYSHIPPED) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
LEFT JOIN IDMASTER VIA (NOLOCK) ON VIA.ROWID = OH.R_SHIPVIA
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS
AND /*OH.R_SHIPVIA=VIA.ROWID AND */ISNULL(VIA.NAME,'') <> 'Drive-In' -- EXCLUDING DRIVE-INS

UNION ALL

--1.2 Drive-Ins
SELECT
1 AS REPORTGROUP,
2 AS REPORTLINE,
'Drive-Ins' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
--(OD.UNITPRICE*OD.QUANTITYSHIPPED) AS AMOUNT
(ISNULL(DBO.FN_LISTPRICE(ITM.ROWID,OH.INVOICEDATE,NULL),0) * OD.QUANTITYSHIPPED) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
LEFT JOIN IDMASTER VIA (NOLOCK) ON VIA.ROWID = OH.R_SHIPVIA
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS
AND /*OH.R_SHIPVIA=VIA.ROWID AND*/ ISNULL(VIA.NAME,'') = 'Drive-In' --DRIVE-INS ONLY

UNION ALL

--2.3 Credit & Debit Memos
SELECT
2 AS REPORTGROUP,
3 AS REPORTLINE,
'Credit & Debit Memos' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
-1*(OD.UNITPRICE*OD.QUANTITYSHIPPED) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE<>'I' --EXCLUDING ORDERS/INVOICES (CREDIT MEMOS ONLY)
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,3)<>'VIP' --EXCLUDING VIP CREDIT MEMOS
-----------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^-----------------
-- VIP CREDITS ARE DONE IN THE AR MODULE NOW WITH A TRANSACTIONNUMBER STARTING WITH 'VIP' --
-- STILL FILTERING OUT 'VIP' TRANSACTIONS IN OM MODULE EVEN THOUGH THEY SHOULDN'T EXIST   --
--------------------------------------------------------------------------------------------

UNION ALL

--2.4 VIP Credit Memo
SELECT
2 AS REPORTGROUP,
4 AS REPORTLINE,
'VIP Credit Memo' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(AH.COMMITDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(AH.COMMITDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(AH.COMMITDATE) AS PERIOD,
DBO.FN_DATE2WEEK(AH.COMMITDATE) AS WEEK,
AH.COMMITDATE, 
--CAST(AH.COMMITDATE AS DATE) AS TRANSACTIONDATE, 
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
-1*AD.AMOUNT AS AMOUNT
FROM AROPENITEMHEADER AH (NOLOCK)
JOIN AROPENITEMDETAIL AD (NOLOCK) ON AD.R_AROPENITEM = AH.ROWID
JOIN AROPENITEMDP AHP (NOLOCK) ON AHP.ROWID = AH.R_PROFILE--<<ADDED TO GET WAREHOUSE BASED OFF OF PROFILECODE
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = AH.R_CUSTOMER--OH.R_SHIPPER WAS CONSIGNEE ROWID NOW USING CUSTOMER ROWID INSTEAD
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = AH.R_CUSTOMER--OH.R_SHIPPER WAS CONSIGNEE ROWID NOW USING CUSTOMER ROWID INSTEAD
JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = SUBSTRING(AHP.PROFILECODE,6,2)--GETS WAREHOUSE BASED OFF OF PROFILECODE POS 6&7: IE:'VIPCM10'

--VIP'S ARE THE ONLY REPORTLINE THAT DOESN'T CONSIDER SALESREP OVERRIDES BECAUSE THEY ARE DONE IN THE AR MODULE AND ARE GIVEN TO THE CONSIGNEE AT YEAREND:
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT--THIS WORKS AS LONG AS CUSTOMER IS IT'S OWN CONSIGNEE
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = AH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'--THIS WORKS AS LONG AS CUSTOMER IS IT'S OWN CONSIGNEE
WHERE AH.RECORDTYPE<>'P' --INCLUDING ALL AR RECORDS EXCEPT PROFILE RECORDS
AND AH.TRANSACTIONTYPE<>'I' --EXCLUDING ORDERS/INVOICES (CREDIT MEMOS ONLY)
AND SUBSTRING(AH.TRANSACTIONNUMBER,1,3)='VIP' --VIP CREDIT MEMOS ONLY

UNION ALL

--3.6 Discounts
SELECT
3 AS REPORTGROUP,
6 AS REPORTLINE,
'Discounts' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
-- -1*(OD.UNITPRICE*OD.QUANTITYSHIPPED*ISNULL(OD.DISCOUNTPERCENT/100,0)) AS AMOUNT
(-1*(ISNULL(DBO.FN_LISTPRICE(ITM.ROWID,OH.INVOICEDATE,NULL),0)-OD.UNITPRICE)*OD.QUANTITYSHIPPED) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS
--AND ISNULL(OD.DISCOUNTPERCENT,0)<>0 --DISCOUNTED ITEMS ONLY

UNION ALL

--4.10 Freight
SELECT
4 AS REPORTGROUP,
10 AS REPORTLINE,
'Freight' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
--ISNULL(OD.EFFECTIVEFREIGHT,0) AS AMOUNT
ISNULL(FRT.AMOUNT,0) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
--JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN OMFREIGHT FRT (NOLOCK) ON FRT.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY

UNION ALL

--4.11 Handling
SELECT
4 AS REPORTGROUP,
11 AS REPORTLINE,
'Handling' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
ISNULL(OD.HANDLINGCHARGEPERITEM,0)*ISNULL(OD.QUANTITYSHIPPED,0) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY

UNION ALL

--4.12 Service Chg
SELECT
4 AS REPORTGROUP,
12 AS REPORTLINE,
'Service Chg' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
ISNULL(OD.TAGGINGCHARGEPERITEM,0)*ISNULL(OD.QUANTITYSHIPPED,0) AS AMOUNT
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY

UNION ALL

--5.14 Inter-Company Gross
SELECT
5 AS REPORTGROUP,
14 AS REPORTLINE,
'Inter-Company Gross' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
--(OD.UNITPRICE*OD.QUANTITYSHIPPED) AS AMOUNT
DBO.FN_LISTPRICE(ITM.ROWID,OH.INVOICEDATE,NULL) * OD.QUANTITYSHIPPED AS AMOUNT 
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
--JOIN IDMASTER VIA (NOLOCK) ON VIA.ROWID = OH.R_SHIPVIA --THIS WAS ELIMINATING ALL INTERCOMPANY RECORDS 10/27/21 DT 
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
--AND OH.TRANSACTIONTYPE='I' 
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)='IC' --INTERCOMPANY ORDERS ONLY

UNION ALL

--5.15 Inter-Company Net
SELECT
5 AS REPORTGROUP,
15 AS REPORTLINE,
'Inter-Company Net' AS REPORTLINEDESC,
DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS SALEYEAR,
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(OH.INVOICEDATE)) AS SEASON,
DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS PERIOD,
DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS WEEK,
OH.INVOICEDATE AS TRANSACTIONDATE,
--CAST(OH.INVOICEDATE AS DATE) AS TRANSACTIONDATE,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
ICUST.USERDEFINEDCODE_8 AS NATIONALACCOUNT,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
ICONS.USERDEFINEDCODE_3 AS CUSTOMERTYPE,
CTYP.DESCRIPTION_1 AS CUSTOMERTYPEDESC,
CONS.IDENTITYID AS CUSTOMERNUMBER,
CONS.NAME AS CUSTOMERNAME,
--(OD.UNITPRICE*OD.QUANTITYSHIPPED*(1-ISNULL(OD.DISCOUNTPERCENT/100,0))) AS AMOUNT
OD.UNITPRICE * OD.QUANTITYSHIPPED AS AMOUNT 
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT)
--JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT	--SALESPERSON OVERRIDES WERE NOT IMPLEMENTED UNTIL 11/17/2021 DT
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
--LEFT JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
JOIN IDCODES CTYP (NOLOCK) ON CTYP.CODE = ICONS.USERDEFINEDCODE_3 AND CTYP.CODETYPE = '74'
--JOIN IDMASTER VIA (NOLOCK) ON VIA.ROWID = OH.R_SHIPVIA --THIS WAS ELIMINATING ALL INTERCOMPANY RECORDS 10/27/21 DT 
WHERE OH.RECORDTYPE='Z' --COMMITTED RECORDS ONLY
--AND OH.TRANSACTIONTYPE='I' 
AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)='IC' --INTERCOMPANY ORDERS ONLY



