--LAST UPDATE: CASTING TRANSACTIONDATE[DATETIME] AS DATE -- DT 5/10/22

/*
SELECT * 
FROM VW_RPT_SQL_GOALS (NOLOCK)
WHERE AMOUNT <> 0
--AND SALEYEAR = 2021
--AND PERIOD <= 3
AND SALESREPID = 'S07'

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_GOALS]
AS
--Goals
SELECT
G.REPORTGROUP, 
G.REPORTLINE, 
G.REPORTLINEDESC,
CAST(G.SALEYEAR AS INT) AS SALEYEAR, 
G.SEASON, 
G.SYPERIOD AS PERIOD, 
G.WEEK, 
G.TRANSACTIONDATE, 
--CAST(G.TRANSACTIONDATE AS DATE) AS TRANSACTIONDATE, 
CAST(G.DIVISIONNUMBER AS CHAR(12)) AS WAREHOUSEID, 
G.DIVISIONNAME AS WAREHOUSENAME, 
G.NATIONALACCOUNT,
ISNULL(PART.IDENTITYID, 'S00') AS SALESREPID,
ISNULL(PART.NAME, 'Adjustments') AS SALESREPNAME,
G.CUSTOMERTYPE, 
G.CUSTOMERTYPEDESC, 
G.CUSTOMERNUMBER, 
G.CUSTOMERNAME, 
G.AMOUNT 
FROM GOALS_REP_NEW G (NOLOCK)
LEFT JOIN IDMASTER PART (NOLOCK) ON TRIM(PART.IDENTITYID) = 'S'+ RIGHT('0'+TRIM(STR(G.SALESREPIDCUST)),2)
