--74 INVOICE (MULTIPLE VERSIONS - THIS IS VERSION:M7)
/*
SELECT
VW_RPT_INVOICE.*
FROM VW_RPT_INVOICE (NOLOCK)
--Needed by Insight to run report from the OMScreens:
JOIN OMTRANSACTIONHEADER (NOLOCK) ON OMTRANSACTIONHEADER.ROWID = VW_RPT_INVOICE.OHROWID
WHERE VW_RPT_INVOICE.RECORDTYPE <> 'P'
and VW_RPT_INVOICE.transactionnumber = '40-15484CM'--10-16421'--20-12959'
INVOICE VERSIONS:
SELECT C.CODE,C.DESCRIPTION_1,C.DESCRIPTION_2,COMMENT FROM IDCODES C (NOLOCK) WHERE C.CODETYPE='3E' ORDER BY CAST(C.CODE AS INT)
#	Description							Sort			Steve's Msg
-------------------------------------------------------------------------------------------------------------------------
1	List Merch Frt/Oth Tot Ext			PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
2	No List Merch Frt/Oth Tot Ext		PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
3	List Landed Ext						PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
4	No List Landed Ext					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
5	List Merch ExtMerch					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
6	No List Landed Ext GT Only			PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVOICE]
AS
SELECT *, 
(	SELECT	SUM(
				IIF(
					CHARINDEX(OH.STAGE,'A;S;C')>0,
					ISNULL(OD.QUANTITYSHIPPED,0),
					ISNULL(OD.QUANTITYORDERED,0)
					)
				) 
	FROM OMTRANSACTIONHEADER OH (NOLOCK)
	JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
	WHERE OH.TRANSACTIONNUMBER = VW_RPT_OM_VERSION_MASTER.TRANSACTIONNUMBER
	AND OD.UNITPRICE = VW_RPT_OM_VERSION_MASTER.UNITPRICE
	AND ITM.ITEMCODE = VW_RPT_OM_VERSION_MASTER.ITEMCODE
)	AS ITEMQTYROLLUP, 

--BECAUSE USERS WERE USING THE WRONG REPORT AND COMPLAINING:
--IIF(ISINVOICE IS NULL,'DRAFT INVOICE', 'INVOICE') AS INVOICETEXT
IIF(ISINVOICE IS NULL,IIF(ISCREDITDEBIT IS NULL, 'DRAFT INVOICE', 'PLEASE USE CREDITDEBIT REPORT FOR THIS DOCUMENT'), 'INVOICE') AS INVOICETEXT
FROM VW_RPT_OM_VERSION_MASTER (NOLOCK) 
WHERE RECORDTYPE <> 'P'

