/* RUNTIME- 1:35--1:00 
--73 Crop Value EXCEL [NEW VERSION FOR STEVE/ELLEN] 
-- 
--	SOLDCROP NOW CALCULATED AS (DEMANDROLLUP + [CURRENTYEAR]SHIPPEDBYCYCLE) 
--	SALEABLECROP NOW CALCULATED AS ([FSU]SUPPLYROLLUP + [CURRENTYEAR]SHIPPEDBYCYCLE) 
--	SHIPPEDBYCYCLE IS FOR CURRENTYEAR SHIPMENTS ONLY SO 
--		PY CALCULATIONS ARE SIMPLY THE SUPPLYROLLUP QUANTITY. 
-- 

SELECT * 
FROM VW_RPT_CROP_VALUE_EXCEL (NOLOCK) 
WHERE SUPPLY + DEMAND + ISNULL(SUPPLYONSTOP, 0) <> 0 
---------------------------------- 
AND WAREHOUSEID = '10'	--RUNTIME- 0:43--0:26 
ORDER BY WAREHOUSEID, GNC_ITEMSORT, LOTSEASON, LOTYEAR	--RUNTIME- 0:53 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_CROP_VALUE_EXCEL] 
AS 
SELECT 
	*, 
	IIF	(CHARINDEX(SUBSTRING(LOTCODE,4,1),'FSU')>0, 
		S_iSUPPLY + S_SHIPPEDBYCYCLE, 0 
		) AS S_iSALEABLECROP, 
	IIF	(CHARINDEX(SUBSTRING(LOTCODE,4,1),'FSU')>0, 
		S_SUPPLY + S_SHIPPEDBYCYCLE, 0 
		) AS S_SALEABLECROP, 
	S_DEMAND + S_SHIPPEDBYCYCLE AS S_SOLDCROP, 
	IIF	(CHARINDEX(SUBSTRING(LOTCODE,4,1),'FSU')>0, 
		A_iSUPPLY + A_SHIPPEDBYCYCLE, 0 
		) AS A_iSALEABLECROP, 
	IIF	(CHARINDEX(SUBSTRING(LOTCODE,4,1),'FSU')>0, 
		A_SUPPLY + A_SHIPPEDBYCYCLE, 0 
		) AS A_SALEABLECROP, 
	A_DEMAND + A_SHIPPEDBYCYCLE AS A_SOLDCROP 
FROM ( 
	SELECT 
		*, 
		iSUPPLY - DEMAND AS iLTS, 
		SUPPLY - DEMAND AS LTS, 
		DBO.FN_SUPPLYROLLUP(ITMROWID, LEFT(LOTCODE,2), LOTSEASON, NULL, 'I') AS S_iSUPPLY, 
		DBO.FN_SUPPLYROLLUP(ITMROWID, LEFT(LOTCODE,2), LOTSEASON, NULL, NULL) AS S_SUPPLY, 
		DBO.FN_DEMANDROLLUP(ITMROWID, LEFT(LOTCODE,2), LOTSEASON, NULL) AS S_DEMAND, 
		--ANOTHER WAY TO DO THE TWO LINES ABOVE USING THE 10BUCKET FUNCTIONS: 
		--DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_9', LOTROWID, ITMROWID) AS SEASON_SUPPLY, 
		--DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_7', LOTROWID, ITMROWID) AS SEASON_DEMAND, 
		DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_1', LOTROWID, ITMROWID) AS si_LTS, 
		DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_2', LOTROWID, ITMROWID) AS s_LTS, 
		DBO.FN_SUPPLYROLLUP(ITMROWID, LEFT(LOTCODE,2), NULL, NULL, 'I') AS A_iSUPPLY, 
		DBO.FN_SUPPLYROLLUP(ITMROWID, LEFT(LOTCODE,2), NULL, NULL, NULL) AS A_SUPPLY, 
		DBO.FN_DEMANDROLLUP(ITMROWID, LEFT(LOTCODE,2), NULL, NULL) AS A_DEMAND, 
		DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_3', LOTROWID, ITMROWID) AS ai_LTS, 
		DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_4', LOTROWID, ITMROWID) AS a_LTS, 
		IIF(CY = LOTYEAR%100,	--SHIPPEDBYCYCLE IS FOR CURRENTYEAR SHIPMENTS ONLY 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,TRIM(STR(CY)),LOTSEASON), 0) AS SHIPPEDBYCYCLE, 
		IIF(CY = LOTYEAR%100,	--SHIPPEDBYCYCLE IS FOR CURRENTYEAR SHIPMENTS ONLY 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,TRIM(STR(CY)),LEFT(LOTSEASON,1)+'%'), 0) AS S_SHIPPEDBYCYCLE, 
		IIF(CY = LOTYEAR%100,	--SHIPPEDBYCYCLE IS FOR CURRENTYEAR SHIPMENTS ONLY 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,TRIM(STR(CY)),NULL), 0) AS A_SHIPPEDBYCYCLE 
	FROM ( 
		SELECT 
			DBO.FN_SALEYEAR(NULL)%100 AS CY, 
			LOT.ROWID AS LOTROWID, 
			ITM.ROWID AS ITMROWID, 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT, 
			---------------------- 
			CO.COMPANYID, 
			TRIM(CO.NAME) AS COMPANYNAME, 
			TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
			TRIM(WH.NAME) AS WAREHOUSENAME, 
			LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			CNT.CONTAINERSORT, 
			TRIM(ITM.SUBCLASSCODE) AS QUALITY, 
			TRIM(ITM.ITEMCODE) AS ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			LOT.USERDEFINEDCODE_6 AS LOTYEAR, 
			LOT.USERDEFINEDCODE_10 AS LOTSEASON, 
			LOT.LOTCODE, 
			LOT.USERDEFINEDCODE_3 AS HOLDSTOP, 
			--SINCE STOPSHIPS ARE ELIMINATED FROM SUPPLY BY DESIGN, CALCULATE SEPARATELY: 
			IIF(LOT.USERDEFINEDCODE_3='S', 
				(	ISNULL(LOT.NETAVAILABLE,0) + 
					ISNULL(LOT.OUT_ORDERED,0) + 
					ISNULL(LOT.OUT_SHIPPED,0) + 
					ISNULL(LOT.OUT_BACKORDER,0) 
					), NULL) AS SUPPLYONSTOP, 
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
			DBO.FN_SUPPLY(ITM.ROWID, LOT.ROWID, 'I') AS iSUPPLY, 
			DBO.FN_SUPPLY(ITM.ROWID, LOT.ROWID, NULL) AS SUPPLY, 
			DBO.FN_DEMAND(ITM.ROWID, LOT.ROWID) AS DEMAND 
		FROM 
			IMITEM ITM (NOLOCK) 
			JOIN IMLOT LOT (NOLOCK) ON LOT.R_ITEM = ITM.ROWID	--ELIMINATE UNASSIGNED LOTS WITH JOIN 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID 
		WHERE ITM.RECORDTYPE = 'R' 
		AND WH.IDENTITYID IN ('10', '20', '40', '60') 
		) X 
	) Y 
