/*
--71 Inventory Status - Cropyear
SELECT * 
FROM VW_RPT_INVENTORY_STATUS_CROPYEAR (NOLOCK) 
WHERE LOTYEAR >= SALEYEAR
and itemcode in ('000152.070.1','000156.070.1')

ORDER BY WAREHOUSEID, PLANTGROUP, SORTNAME, CONTAINERSORT, QUALITY
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVENTORY_STATUS_CROPYEAR]
AS
SELECT	
	*,
	IIF(SY0 = LOTYEAR, LISTPRICE, NULL) AS LIST0,
	IIF(SY0 = LOTYEAR, ONHAND, 0) AS ONHAND0,
	IIF(SY0 = LOTYEAR, LISTPRICE * ONHAND, NULL) AS EXTLIST0,
	IIF(SY1 = LOTYEAR, LISTPRICE, NULL) AS LIST1,
	IIF(SY1 = LOTYEAR, ONHAND, 0) AS ONHAND1,
	IIF(SY1 = LOTYEAR, LISTPRICE * ONHAND, NULL) AS EXTLIST1,
	IIF(SY2 = LOTYEAR, LISTPRICE, NULL) AS LIST2,
	IIF(SY2 = LOTYEAR, ONHAND, 0) AS ONHAND2,
	IIF(SY2 = LOTYEAR, LISTPRICE * ONHAND, NULL) AS EXTLIST2,
	IIF(SY3 = LOTYEAR, LISTPRICE, NULL) AS LIST3,
	IIF(SY3 = LOTYEAR, ONHAND, 0) AS ONHAND3,
	IIF(SY3 = LOTYEAR, LISTPRICE * ONHAND, NULL) AS EXTLIST3
FROM	(
		SELECT
			YR.CURR AS SALEYEAR,
			IIF(SUBSTRING(VLOT.LOTCODE,4,1) IN ('F','S','U'), 'Y', NULL) AS ISFSUONLY,
			CO.COMPANYID,
			CO.NAME AS COMPANYNAME,
			ITM.RECORDTYPE,
			ITM.ROWID AS ITMROWID,
			WH.IDENTITYID AS WAREHOUSEID, 
			WH.NAME AS WAREHOUSENAME,
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
			LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE,
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
			--ITM.REFERENCE_5 AS SORTNAME,--VARIETY,
			--CNT.CONTAINERSORT,
			--ITM.SUBCLASSCODE AS QUALITY,
			ITM.ITEMCODE,
			CNT.PRINTEDCONTAINERCODE AS CONTSIZE,
			ITM.REFERENCE_1 AS COMMONNAME,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			CURR AS SY0, CURR+1 AS SY1, CURR+2 AS SY2, CURR+3 AS SY3,
			LEFT(VLOT.LOTCODE,2) AS LOTYEAR,
			VLOT.ON_HAND AS ONHAND,
			ISNULL(VLOT.USERDEFINEDCODE_3,'') AS HOLDSTOP
		FROM (SELECT DBO.FN_SALEYEAR(NULL)%100 AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW
			IMITEM ITM (NOLOCK)
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
			--NO LONGER NEEDED:
			--JOIN IMSEASONCODE SEA (NOLOCK) ON SUBSTRING(SEA.SEASONCODE,4,2) = WH.IDENTITYID
			--AND GETDATE() BETWEEN SEA.STARTDATE AND SEA.ENDDATE
		WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999' 
		--AND SUBSTRING(VLOT.LOTCODE, 4, 1) IN ('F','S', 'U') 
		AND VLOT.ON_HAND > 0
		) X 
