/*	RUNTIME- 0:08 
--QIV3WITHGROWERS

SELECT * 
FROM VW_RPT_QIV3WITHGROWERS (NOLOCK) 
WHERE COMPANYID = 'SB' 
----------------------
ORDER BY 
	TRANSACTIONDATE DESC, 
	GNC_ITEMSORT, 
	LOTYEAR, 
	LOTSEASON, 
	LOCATIONCODE 

*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_QIV3WITHGROWERS] 
AS 
SELECT 
	'SB' AS COMPANYID, 
	GNC_ITEMSORT, 
	LOTYEAR, 
	LOTSEASON, 
	LOCATIONCODE, 
	TRANSACTIONDATE, 
	CAL_MONTH, 
	CAL_YEAR, 
	SALEYEAR, 
	REPORTYEAR, 
	REPORTPERIOD, 
	REPORTWEEK, 
	PLANTGROUPCODE, 
	COMMONNAME, 
	SORTNAMEVARIETY, 
	ITEMCODE, 
	GENUSCODE, 
	GENUSNAME, 
	VARIETY, 
	QUALITY, 
	WAREHOUSEID, 
	CONTAINERCODE, 
	PRINTEDCONTAINERCODE, 
	TRTYPE, 
	(	SELECT GROW.CODE 
		FROM IMCODES GROW (NOLOCK) 
		WHERE GROW.DESCRIPTION_1 = U.GROWERNAME 
		AND GROW.CODETYPE = '27'	--GROWERNAME 
		) AS GROWERID, 
	GROWERNAME, 
	GROWERBLOCK, 
	TRANSCODELINK, 
	TRCODE, 
	TRDESC, 
	QUANTITY, 
	HISTLISTPRICE, 
	LISTPRICE 
FROM	( 
		SELECT 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+TRIM(ITM.SUBCLASSCODE) AS GNC_ITEMSORT, 
			--TRIM(LOT.LOTCODE) AS LOTCODE, 
			LOT.USERDEFINEDCODE_6 AS LOTYEAR, 
			LOT.USERDEFINEDCODE_10 AS LOTSEASON, 
			TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE, 
			CAST (TH.TRANSACTIONDATE AS DATE) AS TRANSACTIONDATE, 
			DATENAME(MONTH, TH.TRANSACTIONDATE) AS CAL_MONTH, 
			DATEPART(YEAR, TH.TRANSACTIONDATE) AS CAL_YEAR, 
			DBO.FN_SALEYEAR(TH.TRANSACTIONDATE) AS SALEYEAR, 
			DBO.FN_DATE2YEAR(TH.TRANSACTIONDATE) AS REPORTYEAR, 
			DBO.FN_DATE2PERIOD(TH.TRANSACTIONDATE) AS REPORTPERIOD, 
			DBO.FN_DATE2WEEK(TH.TRANSACTIONDATE) AS REPORTWEEK, 
			LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			TRIM(ITM.ITEMCODE) AS ITEMCODE, 
			TRIM(GEN.CODE) AS GENUSCODE, 
			GEN.DESCRIPTION_1 AS GENUSNAME, 
			TRIM(ITMDP.PROFILECODE) AS VARIETY, 
			TRIM(ITM.SUBCLASSCODE) AS QUALITY, 
			TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
			CNT.CONTAINERCODE, 
			CNT.PRINTEDCONTAINERCODE, 
			'THROWAWAYS' AS TRTYPE, 
			--GROW.CODE AS GROWERID,	--NOT PASSING THIS FIELD FROM ePLANT SO INSIGHT MUST FILL THIS HOLE IN THE FINAL PASS 
			GROW.DESCRIPTION_1 AS GROWERNAME, 
			LEFT(LOC.LOCATIONCODE,4) AS GROWERBLOCK, 
			TR.DESCRIPTION_2 AS TRANSCODELINK,	--(LINK TO ePLANT) 
			TRIM(TR.CODE) AS TRCODE, 
			TR.DESCRIPTION_1 AS TRDESC, 
			TD.QUANTITY, 
			DBO.FN_LISTPRICE(ITM.ROWID,TH.TRANSACTIONDATE, NULL) AS HISTLISTPRICE,	--LISTPRICE BASED ON TRANSACTIONDATE 
			DBO.FN_LISTPRICE(ITM.ROWID, NULL, NULL) AS LISTPRICE					--LISTPRICE BASED ON CURRENT DATE 
		FROM IMTRANSACTIONHEADER TH (NOLOCK) 
			JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
			JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = TD.ROWID 
			JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
			JOIN IMITEMDP ITMDP (NOLOCK) ON ITMDP.ROWID = ITM.R_PROFILE 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
			JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = TH.COMPANYID 
			JOIN IMCODES TR (NOLOCK) ON TR.CODE = TD.USERDEFINEDCODE_1 AND TR.CODETYPE = '21'		--TRANSCODEDESC&LINK 
			JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
			JOIN IMCODES GROW (NOLOCK) ON GROW.CODE = LOC.SUBCLASSCODE AND GROW.CODETYPE = '27'		--GROWERNAME 
		WHERE TH.RECORDTYPE = 'Z' 
		AND TR.DESCRIPTION_2 LIKE 'T%'
		AND WH.IDENTITYID IN ('10','20','40','60') 

		UNION ALL 

		SELECT 
			* 
		FROM GNC_QIV3WITHGROWERS ePLANT (NOLOCK) 
		) U 
