/*	* * * * * UNIFIED LEFT TO SELL * * * * *
--71 LEFT TO SELL BY ITEM REPORT (90,91,175)
--RUNTIME: 4:18
SELECT *
FROM VW_RPT_LEFT_TO_SELL (NOLOCK)
WHERE RECORDTYPE <> 'P'
AND FSU_SUPPLY + FSU_DEMAND <> 0

--71 INFLATED LEFT TO SELL BY ITEM REPORT (90,91,175)
--RUNTIME: 4:53
SELECT *
FROM VW_RPT_LEFT_TO_SELL (NOLOCK)
WHERE RECORDTYPE <> 'P'
AND FSU_SUPPLY + FSU_DEMAND <> 0

--91 SEASONAL LEFT TO SELL BY ITEM REPORT
--RUNTIME: 2:59
SELECT *
FROM VW_RPT_LEFT_TO_SELL (NOLOCK)
WHERE RECORDTYPE <> 'P'
AND FSU_iSUPPLY + FSU_DEMAND <> 0
-----------------------------------------------------------------
-- For external use viewable by the customer.
-- Therefore all inflated values are not designated as inflated,
-- and oversell percentage is not displayed.
-----------------------------------------------------------------
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_LEFT_TO_SELL]
AS
SELECT --TOTAL RUNTIME:2:04 (NIIICE)
	U.COMPANYID,
	U.COMPANYNAME,
	U.RECORDTYPE,
	U.WAREHOUSEID,
	U.WAREHOUSENAME,
	U.SHIPPERADDRESSMEMO,
	U.SHIPPERADDRESS_1,
	U.SHIPPERCITY,
	U.SHIPPERSTATE,
	U.SHIPPERZIP,
	U.SHIPPERPHONE,
	U.SHIPPERFAX,
	U.SALEYEAR,
	U.QUALITY,
	U.PLANTGROUP,
	LEFT(U.PLANTGROUP,3) AS PLANTGROUPCODE,
	U.GENUSCODE, 
	U.GENUSNAME, 
	U.SORTNAMEVARIETY,
	U.CONTAINERSORT,
	U.PATENTNUMBER,
	-----------
	--LINEONE--
	-----------
	U.ITEMCODE,
	U.PRINTEDCONTAINERCODE,
	U.GRADEMEASURE,
	U.COMMONNAME,
	U.COMMONNAMEPATENT,
	U.BOTANICALPATENT, 
	U.BRAND,
	U.BRANDPOTREQ,
	U.HZ,
	U.LISTPRICE,
	U.PY_F_SUPPLY - U.PY_F_DEMAND AS PY_FALL_LTS,
	U.CY_F_SUPPLY - U.CY_F_DEMAND AS CY_FALL_LTS,
	(U.PY_F_SUPPLY + U.CY_F_SUPPLY) - (U.PY_F_DEMAND + U.CY_F_DEMAND) AS FALL_LTS,
	U.PY_S_SUPPLY - U.PY_S_DEMAND AS PY_SPRING_LTS,
	U.CY_S_SUPPLY - U.CY_S_DEMAND AS CY_SPRING_LTS,
	(U.PY_S_SUPPLY + U.CY_S_SUPPLY) - (U.PY_S_DEMAND + U.CY_S_DEMAND) AS SPRING_LTS,
	U.PY_U_SUPPLY - U.PY_U_DEMAND AS PY_SUMMER_LTS,
	U.CY_U_SUPPLY - U.CY_U_DEMAND AS CY_SUMMER_LTS,
	(U.PY_U_SUPPLY + U.CY_U_SUPPLY) - (U.PY_U_DEMAND + U.CY_U_DEMAND) AS SUMMER_LTS,

	(U.PY_F_SUPPLY + U.PY_S_SUPPLY + U.PY_U_SUPPLY) - (U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND) AS PY_FSU_LTS,
	(U.CY_F_SUPPLY + U.CY_S_SUPPLY + U.CY_U_SUPPLY) - (U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND) AS CY_FSU_LTS,
	(U.PY_F_SUPPLY + U.PY_S_SUPPLY + U.PY_U_SUPPLY + U.CY_F_SUPPLY + U.CY_S_SUPPLY + U.CY_U_SUPPLY) - 
	(U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND + U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND) AS FSU_LTS,
	(	(U.PY_F_SUPPLY + U.PY_S_SUPPLY + U.PY_U_SUPPLY + U.CY_F_SUPPLY + U.CY_S_SUPPLY + U.CY_U_SUPPLY) - 
		(U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND + U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND)
	) * U.LISTPRICE AS EXT_FSU_LTS,
	---------------------------
	--LINEONE INFLATED VALUES--
	---------------------------
	U.PY_F_iSUPPLY - U.PY_F_DEMAND AS PY_FALL_iLTS,
	U.CY_F_iSUPPLY - U.CY_F_DEMAND AS CY_FALL_iLTS,
	(U.PY_F_iSUPPLY + U.CY_F_iSUPPLY) - (U.PY_F_DEMAND + U.CY_F_DEMAND) AS FALL_iLTS,
	U.PY_S_iSUPPLY - U.PY_S_DEMAND AS PY_SPRING_iLTS,
	U.CY_S_iSUPPLY - U.CY_S_DEMAND AS CY_SPRING_iLTS,
	(U.PY_S_iSUPPLY + U.CY_S_iSUPPLY) - (U.PY_S_DEMAND + U.CY_S_DEMAND) AS SPRING_iLTS,
	U.PY_U_iSUPPLY - U.PY_U_DEMAND AS PY_SUMMER_iLTS,
	U.CY_U_iSUPPLY - U.CY_U_DEMAND AS CY_SUMMER_iLTS,
	(U.PY_U_iSUPPLY + U.CY_U_iSUPPLY) - (U.PY_U_DEMAND + U.CY_U_DEMAND) AS SUMMER_iLTS,

	(U.PY_F_iSUPPLY + U.PY_S_iSUPPLY + U.PY_U_iSUPPLY) - (U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND) AS PY_FSU_iLTS,
	(U.CY_F_iSUPPLY + U.CY_S_iSUPPLY + U.CY_U_iSUPPLY) - (U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND) AS CY_FSU_iLTS,
	(	(U.PY_F_iSUPPLY + U.PY_S_iSUPPLY + U.PY_U_iSUPPLY + U.CY_F_iSUPPLY + U.CY_S_iSUPPLY + U.CY_U_iSUPPLY) -	
		(U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND + U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND)
	) AS FSU_iLTS,
	(	(U.PY_F_iSUPPLY + U.PY_S_iSUPPLY + U.PY_U_iSUPPLY + U.CY_F_iSUPPLY + U.CY_S_iSUPPLY + U.CY_U_iSUPPLY) - 
		(U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND + U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND)
	) * U.LISTPRICE AS EXT_FSU_iLTS,
	-----------
	--LINETWO--
	-----------
	U.PY_F_SUPPLY_HS - U.PY_F_DEMAND_HS AS PY_FALL_LTS_H,
	U.CY_F_SUPPLY_HS - U.CY_F_DEMAND_HS AS CY_FALL_LTS_H,
	U.PY_S_SUPPLY_HS - U.PY_S_DEMAND_HS AS PY_SPRING_LTS_H,
	U.CY_S_SUPPLY_HS - U.CY_S_DEMAND_HS AS CY_SPRING_LTS_H,
	U.PY_U_SUPPLY_HS - U.PY_U_DEMAND_HS AS PY_SUMMER_LTS_H,
	U.CY_U_SUPPLY_HS - U.CY_U_DEMAND_HS AS CY_SUMMER_LTS_H,
	---------------------------
	--LINETWO INFLATED VALUES--
	---------------------------
	U.PY_F_iSUPPLY_HS - U.PY_F_DEMAND_HS AS PY_FALL_iLTS_H,
	U.CY_F_iSUPPLY_HS - U.CY_F_DEMAND_HS AS CY_FALL_iLTS_H,
	U.PY_S_iSUPPLY_HS - U.PY_S_DEMAND_HS AS PY_SPRING_iLTS_H,
	U.CY_S_iSUPPLY_HS - U.CY_S_DEMAND_HS AS CY_SPRING_iLTS_H,
	U.PY_U_iSUPPLY_HS - U.PY_U_DEMAND_HS AS PY_SUMMER_iLTS_H,
	U.CY_U_iSUPPLY_HS - U.CY_U_DEMAND_HS AS CY_SUMMER_iLTS_H,
	---------------------------
	--LINETWO SEASONAL VALUES--
	---------------------------
	(U.PY_F_iSUPPLY_HS + U.CY_F_iSUPPLY_HS) - (U.PY_F_DEMAND_HS + U.CY_F_DEMAND_HS) AS FALL_iLTS_H,
	(U.PY_S_iSUPPLY_HS + U.CY_S_iSUPPLY_HS) - (U.PY_S_DEMAND_HS + U.CY_S_DEMAND_HS) AS SPRING_iLTS_H,
	(U.PY_U_iSUPPLY_HS + U.CY_U_iSUPPLY_HS) - (U.PY_U_DEMAND_HS + U.CY_U_DEMAND_HS) AS SUMMER_iLTS_H,
	(	(U.PY_F_iSUPPLY_HS + U.PY_S_iSUPPLY_HS + U.PY_U_iSUPPLY_HS + U.CY_F_iSUPPLY_HS + U.CY_S_iSUPPLY_HS + U.CY_U_iSUPPLY_HS) - 
		(U.PY_F_DEMAND_HS + U.PY_S_DEMAND_HS + U.PY_U_DEMAND_HS + U.CY_F_DEMAND_HS + U.CY_S_DEMAND_HS + U.CY_U_DEMAND_HS)
	) AS FSU_iLTS_H,
	-------------
	--LINETHREE--
	-------------
	(U.PY_F_SUPPLY + U.CY_F_SUPPLY) AS FALL_SUPPLY,
	(U.PY_F_DEMAND + U.CY_F_DEMAND) AS FALL_DEMAND,
	(U.PY_S_SUPPLY + U.CY_S_SUPPLY) AS SPRING_SUPPLY,
	(U.PY_S_DEMAND + U.CY_S_DEMAND) AS SPRING_DEMAND,
	(U.PY_U_SUPPLY + U.CY_U_SUPPLY) AS SUMMER_SUPPLY,
	(U.PY_U_DEMAND + U.CY_U_DEMAND) AS SUMMER_DEMAND,
	(U.PY_F_SUPPLY + U.PY_S_SUPPLY + U.PY_U_SUPPLY + U.CY_F_SUPPLY + U.CY_S_SUPPLY + U.CY_U_SUPPLY) AS FSU_SUPPLY,
	(U.PY_F_DEMAND + U.PY_S_DEMAND + U.PY_U_DEMAND + U.CY_F_DEMAND + U.CY_S_DEMAND + U.CY_U_DEMAND) AS FSU_DEMAND,
	-----------------------------
	--LINETHREE INFLATED VALUES--
	-----------------------------
	(U.PY_F_iSUPPLY + U.CY_F_iSUPPLY) AS FALL_iSUPPLY,
	(U.PY_S_iSUPPLY + U.CY_S_iSUPPLY) AS SPRING_iSUPPLY,
	(U.PY_U_iSUPPLY + U.CY_U_iSUPPLY) AS SUMMER_iSUPPLY,
	(U.PY_F_iSUPPLY + U.PY_S_iSUPPLY + U.PY_U_iSUPPLY + U.CY_F_iSUPPLY + U.CY_S_iSUPPLY + U.CY_U_iSUPPLY) AS FSU_iSUPPLY,

	-----------------------------
	--LINETHREE SEASONAL VALUES--
	-----------------------------
	(	SELECT DBO.FN_SALESNOTEROLLUP(U.ITEMROWID, 'CY', SUBSTRING(SEAS.SEASONCODE,7,2)) 
		FROM IMSEASONCODE SEAS (NOLOCK)
		WHERE GETDATE() BETWEEN SEAS.STARTDATE AND SEAS.ENDDATE
		AND SUBSTRING(SEAS.SEASONCODE,4,2) = U.WAREHOUSEID
	) AS CURRENTSEASONSALESNOTEROLLUP,
	IIF	(	(U.PY_F_SUPPLY+U.CY_F_SUPPLY+U.PY_S_SUPPLY+U.CY_S_SUPPLY+U.PY_U_SUPPLY+U.CY_U_SUPPLY) = 0, 0,
			(U.PY_F_iSUPPLY+U.CY_F_iSUPPLY+U.PY_S_iSUPPLY+U.CY_S_iSUPPLY+U.PY_U_iSUPPLY+U.CY_U_iSUPPLY)/
			(U.PY_F_SUPPLY+U.CY_F_SUPPLY+U.PY_S_SUPPLY+U.CY_S_SUPPLY+U.PY_U_SUPPLY+U.CY_U_SUPPLY)-1
		) AS FSU_OVERSELLAVG
FROM	
	(	SELECT	--TOTAL RUNTIME FOR ALL VERSIONS: 23:21 BEFORE RESTRUCTURING (THIS WILL NOT DO)
			CO.COMPANYID,
			TRIM(CO.NAME) AS COMPANYNAME,
			ITM.RECORDTYPE,
			ITM.ROWID AS ITEMROWID,
			WH.IDENTITYID AS WAREHOUSEID, 
			TRIM(WH.NAME) AS WAREHOUSENAME,
			VWH.SHIPPERADDRESSMEMO,
			VWH.SHIPPERADDRESS_1,
			TRIM(VWH.SHIPPERCITY) AS SHIPPERCITY,
			TRIM(VWH.SHIPPERSTATE) AS SHIPPERSTATE,
			VWH.SHIPPERZIP,
			ISNULL(NULLIF(VWH.SHIPPERTELEPHONE_1,''), COADD.TELEPHONE_1) AS SHIPPERPHONE,
			ISNULL(NULLIF(VWH.SHIPPERFAX_1,''), COADD.FAX_1) AS SHIPPERFAX,
			DBO.FN_SALEYEAR(NULL) AS SALEYEAR,
			ITM.SUBCLASSCODE AS QUALITY,
			PC.PRODUCTCATEGORYCODE AS PLANTGROUP,
			ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
			GEN.DESCRIPTION_1 AS GENUSNAME, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY,
			CNT.CONTAINERSORT,
			ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
			-----------
			--LINEONE--
			-----------
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			CNT.PRINTEDCONTAINERCODE,
			ITM.USERDEFINEDREFERENCE_2 AS GRADEMEASURE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.REFERENCE_1 + ' ' + ISNULL(ITM.USERDEFINEDREFERENCE_1, '') AS COMMONNAMEPATENT,
			ITM.REFERENCE_2 + ' ' + ISNULL(ITM.USERDEFINEDREFERENCE_1, '') AS BOTANICALPATENT, 
			ITM.USERDEFINEDCODE_2 AS BRAND,
			ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
			ITM.USERDEFINEDCODE_18 AS HZ,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','F%',NULL,'I')	AS PY_F_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','F%',NULL,NULL)	AS PY_F_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','F%',NULL)		AS PY_F_DEMAND,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F%',NULL,'I')	AS CY_F_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F%',NULL,NULL)	AS CY_F_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','F%',NULL)		AS CY_F_DEMAND,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','S%',NULL,'I')	AS PY_S_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','S%',NULL,NULL)	AS PY_S_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','S%',NULL)		AS PY_S_DEMAND,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S%',NULL,'I')	AS CY_S_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S%',NULL,NULL)	AS CY_S_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','S%',NULL)		AS CY_S_DEMAND,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','U%',NULL,'I')	AS PY_U_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','U%',NULL,NULL)	AS PY_U_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','U%',NULL)		AS PY_U_DEMAND,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U%',NULL,'I')	AS CY_U_iSUPPLY, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U%',NULL,NULL)	AS CY_U_SUPPLY, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','U%',NULL)		AS CY_U_DEMAND,
			-----------
			--LINETWO--
			-----------
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','F%','H','I')	AS PY_F_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','F%','H',NULL)	AS PY_F_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','F%','H')		AS PY_F_DEMAND_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F%','H','I')	AS CY_F_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F%','H',NULL)	AS CY_F_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','F%','H')		AS CY_F_DEMAND_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','S%','H','I')	AS PY_S_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','S%','H',NULL)	AS PY_S_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','S%','H')		AS PY_S_DEMAND_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S%','H','I')	AS CY_S_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S%','H',NULL)	AS CY_S_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','S%','H')		AS CY_S_DEMAND_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','U%','H','I')	AS PY_U_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'PY','U%','H',NULL)	AS PY_U_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'PY','U%','H')		AS PY_U_DEMAND_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U%','H','I')	AS CY_U_iSUPPLY_HS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U%','H',NULL)	AS CY_U_SUPPLY_HS, 
			DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','U%','H')		AS CY_U_DEMAND_HS
		FROM IMITEM ITM (NOLOCK)
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			LEFT OUTER JOIN VW_IDSHIPPERVIEW VWH (NOLOCK) ON VWH.SHIPPERMASTERROWID = ITM.R_WAREHOUSE
			LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
			LEFT OUTER JOIN IDADDRESS COADD (NOLOCK) ON COADD.ROWID = CO.R_DEFAULTADDRESS
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE =  '11' --GENUS
		WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'
	) U