/* RUNTIME- 2:47 
--73 INVENTORY STATUS5 - THIS IS OUTDATED NOW.
--
--	SOLDCROP NOW CALCULATED AS (DEMANDROLLUP + SHIPPEDBYSEASON)
--	SALEABLECROP NOW CALCULATED AS (SUPPLYROLLUP + SHIPPEDBYSEASON)

SELECT * 
FROM VW_RPT_INVENTORY_STATUS (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVENTORY_STATUS]
AS
SELECT
	YR.CURR,	--SAVE YR.CURR TO BE USED IN FN_SHIPPEDBYSEASON() REPEATEDLY.
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	ITM.RECORDTYPE,
	WH.IDENTITYID AS WAREHOUSE, 
	WH.NAME AS WAREHOUSENAME,
	VITM.SUBCLASSCODE AS QUALITY,
	SUBSTRING(PC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
	VITM.ITEMCODE,
	--HOLDSTOP IS AT LOT LEVEL NOT AT ITEM LEVEL.
	--GRADEMEASURE IS NOT SETUP YET.
	ITM.REFERENCE_1 AS COMMONNAME,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'Y%',NULL,NULL) AS SHIFTSUPPLY,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'Z%',NULL,NULL) AS PROPSUPPLY,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'X%',NULL,NULL) AS CULLSSUPPLY,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'F%',NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'F%') AS FALLSALEABLE,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'S%',NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'S%') AS SPRINGSALEABLE,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'U%',NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'U%') AS SUMMERSALEABLE,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,NULL,NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,NULL) AS TOTALSALEABLE,
	DBO.FN_DEMANDROLLUP(ITM.ROWID,YR.CURR,NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,NULL) AS TOTALSOLD,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,NULL,NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,NULL,NULL) AS TOTALLTS,
	DBO.FN_DEMANDROLLUP(ITM.ROWID,YR.CURR,'F%',NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'F%') AS FALLSOLD,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'F%',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F%',NULL) AS FALLLTS,
	DBO.FN_DEMANDROLLUP(ITM.ROWID,YR.CURR,'S%',NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'S%') AS SPRINGSOLD,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'S%',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S%',NULL) AS SPRINGLTS,
	DBO.FN_DEMANDROLLUP(ITM.ROWID,YR.CURR,'U%',NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'U%') AS SUMMERSOLD,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,'U%',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U%',NULL) AS SUMMERLTS,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'F%') AS FSHIPPED,
	DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'S%') AS SSHIPPED,
	DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,'U%') AS USHIPPED,
	(DBO.FN_SUPPLYROLLUP(ITM.ROWID,YR.CURR,NULL,NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,NULL)) 
		* DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS TOTALSALEABLEVALUE,
	(DBO.FN_DEMANDROLLUP(ITM.ROWID,YR.CURR,NULL,NULL) + DBO.FN_SHIPPEDBYSEASON(ITM.ROWID,YR.CURR,NULL)) 
		* DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS TOTALSOLDVALUE
FROM (SELECT TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW
	IMITEM ITM (NOLOCK)
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY
	JOIN VW_IMITEMVIEW VITM (NOLOCK) ON VITM.R_WAREHOUSE = ITM.R_WAREHOUSE AND VITM.ITEMCODE = ITM.ITEMCODE
WHERE ITM.RECORDTYPE = 'R' 
AND WH.IDENTITYID IN ('10', '20', '30', '40')
--AND VITM.ITEMCODE IN ('000090.008.1','000507.070.1','000154.050.1')
--AND VITM.ITEMCODE = '000090.008.1'-- VITM.AVAILABLE <> 0
/*ORDER BY
		WH.IDENTITYID, 
		ITM.ITEMCODE
*/
