--46 SEASONCODE_GNC
/*
SELECT *
FROM VW_RPT_SEASONCODE_GNC SEA (NOLOCK)
WHERE 1=1

---------------------------------------------------------------------------------------
----Testing what is:
and
SUBSTRING(SEA.SEASONCODE,4,2) in ('10', '20', '40', '60') AND GETDATE()+1 BETWEEN SEA.STARTDATE AND SEA.ENDDATE

--Testing what was:
SELECT *
FROM IMSEASONCODE SEA (NOLOCK)
WHERE SUBSTRING(SEA.SEASONCODE,4,2) in ('10', '20', '40', '60') AND GETDATE()+1 BETWEEN SEA.STARTDATE AND SEA.ENDDATE

Test comparison with IMSEASONCODE table: SELECT * FROM IMSEASONCODE SEA (NOLOCK)


Recapitulation of IMSEASONCODE with STATIC dates applying toward LOT.DATEAVAILABLE
Instead of the dates that GNC is using in the IMSEASONCODE table for Order Profiles.
This replacement will be selectively used in reports in order to get the results they are expecting.
*/

/*
REPORTS/FUNCTIONS AFFECTED:
-----------------
AVAILABILITY_BY_LOCATION			Changed	Ellen notified<<<<<<<<=====added TOTALSUPPLY field use WHID=10
AVAILABILITY_BY_LOCATION_STATIC		Changed	Ellen notified<<<<<<<<=====added TOTALSUPPLY field use WHID=10
EDI_PO_NEW							No change needed for PROFILE determination.
INVENTORY_STATUS_QUANTITY			Validated	Harrison Cook volunteered, use WHID=20 Before/After and send to him 
INVENTORY_STATUS_QUANTITY_STATIC	Validated	Harrison Cook volunteered, use WHID=20 Before/After and send to him 
LEFT_TO_SELL						Changed	Ellen notified<<<<<<<<=====
WEBSITE_AVAILABILITY				Validated	Landon Cramer researched and confirmed
FN_SHIPPEDBYCYCLE					Changed
	CROP_VALUE			Uses FN_SHIPPEDBYCYCLE	Ellen notified<<<<<<<<=====
	CROP_VALUE_EXCEL	NOT ATTACHED TO A REPORT ANYMORE
	CROP_VALUE_LOT		Uses FN_SHIPPEDBYCYCLE	Ellen notified<<<<<<<<=====

Notes on Reports using IMSEASONCODE table
----------------------------------------- 
AVAILABILITY_BY_LOCATION
                to select which LotYear/LotSeason to display for CurrentSeason, CurrentSeason+1, CurrentSeason+2
EDI_PO_NEW
                to calculate the expected PROFILE to use for incoming EDI PO documents.
INVENTORY_STATUS_QUANTITY
                to calculate which season to use for: Current Supply and Demand values
LEFT_TO_SELL
                to calculate which season to use for: CURRENTSEASONSALESNOTEROLLUP
WEBSITE_AVAILABILITY
                to calculate CURRENT SEASON INFLATED LTS
CROP VALUE RPTS
				Uses FN_SHIPPEDBYCYCLE to get seasonal totals.
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_SEASONCODE_GNC]
AS

SELECT *
FROM	(
	--WAREHOUSEID 10:
	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.F1' AS SEASONCODE, DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.S1' AS SEASONCODE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

			SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.U1' AS SEASONCODE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.U2' AS SEASONCODE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.U3' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.X' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.Y' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.10.Z' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

	--WAREHOUSEID 20:
	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.F1' AS SEASONCODE, DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.S1' AS SEASONCODE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.U1' AS SEASONCODE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.U2' AS SEASONCODE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.U3' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.X' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.Y' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.20.Z' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

	--WAREHOUSEID 40:
	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.F1' AS SEASONCODE, DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.S1' AS SEASONCODE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.U1' AS SEASONCODE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.U2' AS SEASONCODE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.U3' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.X' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.Y' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.40.Z' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

	--WAREHOUSEID 60:
	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.F1' AS SEASONCODE, DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.S1' AS SEASONCODE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.U1' AS SEASONCODE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.U2' AS SEASONCODE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.U3' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.X' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.Y' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

		UNION ALL

		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.60.Z' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
		FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	----GENERIC WHID 99:
	--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.F1' AS SEASONCODE, DBO.FN_YEAR2DATE(X.YR) AS STARTDATE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.S1' AS SEASONCODE, TRIM(STR(X.YR-1)) + '-12-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--		SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U1' AS SEASONCODE, TRIM(STR(X.YR)) + '-05-01 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U2' AS SEASONCODE, TRIM(STR(X.YR)) + '-06-15 00:00:00.000' AS STARTDATE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.U3' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.X' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.Y' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X

	--	UNION ALL

	--	SELECT RIGHT('00'+TRIM(STR(X.YR%100)),2) + '.99.Z' AS SEASONCODE, TRIM(STR(X.YR)) + '-07-25 00:00:00.000' AS STARTDATE, DBO.FN_YEAR2DATE(X.YR+1) AS ENDDATE 
	--	FROM (SELECT TOP 20 YEAR(GETDATE())-10+ROW_NUMBER() OVER(ORDER BY NUMBER) AS YR FROM MASTER..spt_values (NOLOCK)) X
) U
