/* IMPORTANT!!!! NEVER NEVER NEVER DELETE THIS VIEW UNLESS YOU FIX VW_RPT_CUST_BOOK TO NOT RELY UPON IT!!!!!!! 
-- RUNTIME- 1:18 
--83 Item Listing 
SELECT * 
FROM VW_RPT_ITEM_LISTING (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_ITEM_LISTING] 
AS 
SELECT 
CO.COMPANYID, 
CO.NAME AS COMPANYNAME, 
WH.IDENTITYID AS WAREHOUSEID, 
WH.NAME AS WAREHOUSENAME, 
WH.ROWID AS WAREHOUSE_ROWID, 
ITM.ROWID AS ITEM_ROWID, 
ITM.RECORDTYPE, 
ITM.ITEMCODE, 
(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE, 
CNT.CONTAINERCODE, 
ITM.SUBCLASSCODE AS QUALITYCODE, 
CNT.PRINTEDCONTAINERCODE, 
ITM.STATUS, 
ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER, 
ITM.REFERENCE_1 AS COMMONNAME, 
ITM.REFERENCE_2 AS BOTANICALNAME, 
ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
SUBSTRING(PGC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE, 
CNT.CONTAINERSORT, 
ITM.ITEMSUPCCODE, 
PGC.DESCRIPTION AS PLANTGROUPDESCRIPTION, 
ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
GEN.DESCRIPTION_1 AS GENUSNAME, 
ITM.DESCRIPTION_2 AS ABBREVBOTANICALNAME, 
ITM.REFERENCE_3 AS REVERSECOMMONNAME, 
ITM.USERDEFINEDCODE_7 AS EXPOSURE, 
ITM.USERDEFINEDCODE_5 AS HARDINESSZONE, 
ITM.USERDEFINEDCODE_6 AS PROP, 
'' AS GROWTHHABITS, --UNKNOWN AT THIS TIME 
ITM.REFERENCE_4 AS TAGDESCRIPTION, 
'' AS CATALOGDESCRIPTION,	--UNKNOWN AT THIS TIME 
--{NULL} LOTYEAR FORCES LTS TO CY+PY ROLLUP: 
DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F%',NULL) AS LTS_F, 
DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S%',NULL) AS LTS_S, 
DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U%',NULL) AS LTS_U, 
DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,NULL,NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,NULL,NULL) AS LTS_FSU, 
ITM.SPECIFICATIONCODE AS GRADEMEAS, 
ITM.USERDEFINEDCODE_17 AS BRAND, 
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
ITM.ARTRADEDISCOUNTFLAG AS NETPRICED 
FROM IMITEM ITM (NOLOCK) 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
LEFT OUTER JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
LEFT OUTER JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
WHERE WH.IDENTITYID < '999'--IN ('10', '20', '40', '60') 
--ORDER BY 
--		WH.IDENTITYID, 
--		ITM.REFERENCE_5, 
--		PGC.PRODUCTCATEGORYCODE, 
--		CNT.CONTAINERSORT, 
--		ITM.ITEMSUPCCODE 
