/*  
--VW_RPT_GNC_FUTURECROPPLANTINGSCHEDULE 

SELECT * 
FROM VW_RPT_GNC_FUTURECROPPLANTINGSCHEDULE (NOLOCK) 
WHERE COMPANYID = 'SB'
ORDER BY PSITEMNUMBER

*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_GNC_FUTURECROPPLANTINGSCHEDULE] 
AS 
--IMPORT DATA 
	SELECT 
		ITM.ROWID AS ITMROWID, 
		WH.COMPANYID, 
		'R' AS RECORDTYPE, 
		WH.IDENTITYID AS WAREHOUSEID, 
		--TRIM(STR(FPS.SCHEDULEYEAR%100))+'.'+REPLACE(FPS.PLANTINGSCHEDULELINE,',','') AS PLANTINGSCHEDULELINE, 
		---------------------------------
		DBO.FN_DATE2YEAR(NULL)%100 AS CY, 
		FPS.SCHEDULEYEAR%100 AS SY, 
		FPS.SCHEDULEYEAR, 
		TRIM(REPLACE(FPS.PLANTINGSCHEDULELINE,',','')) AS PSID, 
		TRIM(FPS.PSITEMNUMBER) AS PSITEMNUMBER, 
		ITM.REFERENCE_1 AS PSCOMMONNAME, 
		ITM.REFERENCE_5 AS PSSORTNAMEVARIETY, 
		TRIM(ITM.SUBCLASSCODE) AS QUALITY, 
		LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE, 
		-----------------------
		FPS.SALESEASON, 
		FPS.TOTALCROPQTY, 
		--0 AS SHIFTQTY, 0 AS PROPSTOCKQTY,
		FPS.SHIFTQTY, 
		FPS.PROPSTOCKQTY, 
		--FPS.TARGETCOMPLETEDATE, 
		IIF(FPS.TARGETCOMPLETEDATE < GETDATE(), 1, 0) AS MULTCOMP, --USE: MULTCOMP * [QTY] TO SET [COMPLETEDQTY]
		IIF(FPS.TARGETCOMPLETEDATE < GETDATE(), 0, 1) AS MULTPART, --USE: MULTPART * [QTY] TO SET [PARTIALQTY]
		FPS.PROJECTCODE, 
		FPS.UPLOADDATE, 
		------------------------
		DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) * POWER(GNC.LISTFACTOR, FPS.SCHEDULEYEAR - DBO.FN_DATE2YEAR(NULL) ) AS TARGETPRICE 

FROM GNC_FUTURECROPPLANTINGSCHEDULE FPS (NOLOCK) 
	--THEY WILL COMPLICATE THE FUTURE PRICES BY WANTING TO EMBED A PRICEFILE TO DETERMINE FUTURE YEAR PRICES WITHOUT SETTING UP PRICES IN INSIGHT...BUT JUST USE THE FUDGEFACTOR FOR NOW..
	JOIN (SELECT LISTFACTOR FROM GNC_FUTURELISTFACTOR (NOLOCK)) GNC ON 1 = 1	--GNC FUDGEFACTOR FOR INCREASING LISTPRICE IN FUTURE YEARS (SET @ 1.06 [6% INCREASE])
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = FPS.DIVISIONNUMBER 
	LEFT JOIN IMITEM ITM (NOLOCK) ON	ITM.ITEMCODE = RIGHT('00'+LEFT(TRIM(FPS.PSITEMNUMBER),12),12) 
									AND ITM.R_WAREHOUSE = WH.ROWID 
									AND ITM.STATUS = 'A' 
									AND ITM.RECORDTYPE = 'R' 
	LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
WHERE FPS.TARGETCOMPLETEDATE IS NOT NULL 
AND ISNULL(FPS.TOTALCROPQTY, 0) + ISNULL(FPS.SHIFTQTY, 0) + ISNULL(FPS.PROPSTOCKQTY, 0) > 0

