/* RUNTIME: 2:05-3:01
--46 DRIVE AROUND ONHAND
SELECT *
FROM VW_RPT_DRIVE_AROUND (NOLOCK)
WHERE RECORDTYPE <> 'P'
and itemcode in ('000152.070.1','000156.070.1')
and warehouseid = '10'
and lotcode = '23.S1'
--and si_LTS > 0
--AND ITEMCODE = '001094.030.1'
--AND ITEMCODE = '000749.031.1'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_DRIVE_AROUND]
AS
SELECT
	CO.COMPANYID,
	TRIM(CO.NAME) AS COMPANYNAME,
	ITM.RECORDTYPE, 
	TRIM(WH.IDENTITYID) AS WAREHOUSEID,
	TRIM(WH.NAME) AS WAREHOUSENAME,
	ITM.USERDEFINEDCODE_1 AS GENUSCODE,
	GEN.DESCRIPTION_1 AS GENUSNAME,
	TRIM(ITM.ITEMCODE) AS ITEMCODE,
	(SELECT TRIM(ITMDP.PROFILECODE) FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	ITM.REFERENCE_2 AS BOTANICALNAME,
	TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUPCODE,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	(SELECT CNT.CONTAINERSORT FROM IMCONTAINER CNT (NOLOCK) WHERE CNT.ROWID = ITM.R_CONTAINERCODE) AS CONTAINERSORT,
	TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,
	ITM.USERDEFINEDCODE_18 AS HZ,
	ITM.USERDEFINEDREFERENCE_3 AS INTERCOPO, --ADDED PER ELLEN 8/8/2024 DT
	LEFT(VLOT.LOTCODE,2) + 2000 AS SALEYEAR,
	TRIM(VLOT.LOTCODE) AS LOTCODE,
	VLOT.OVERSELLPERCENTAGE,
  --USING CALCULATED FIELDS: CODE FOUND IN DBO.FNIM_GETUSERCALCULATEDFIELD() Argos Function
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_1', VLOT.ROWID, ITM.ROWID) AS si_LTS,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_2', VLOT.ROWID, ITM.ROWID) AS s_LTS,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_3', VLOT.ROWID, ITM.ROWID) AS ai_LTS,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_4', VLOT.ROWID, ITM.ROWID) AS a_LTS,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_9', VLOT.ROWID, ITM.ROWID) AS SEASON_SUPPLY,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_7', VLOT.ROWID, ITM.ROWID) AS SEASON_DEMAND,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_6', VLOT.ROWID, ITM.ROWID) AS SEASON_OH,
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_5', VLOT.ROWID, ITM.ROWID) AS SEASON_AVAILABLE,
	VLOT.ON_HAND,
	VLOT.IN_RECEIVING,
	VLOT.OUT_SHIPPED,
	VLOT.OUT_UNAVAILABLE,
	VLOT.AVAILABLE,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	VLOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
	VLOT.USERDEFINEDDATE_1 AS HOLDSTOPBEGINDATE,
	VLOT.USERDEFINEDDATE_2 AS HOLDSTOPENDDATE,
	VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
	VLOT.USERDEFINEDREFERENCE_7 AS SALESNOTE, 
	DBO.FN_SALESNOTE(ITM.ROWID,VLOT.ROWID, NULL) AS FNSALESNOTE,
	VLOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE, 
	VLOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1,
	VLOT.USERDEFINEDREFERENCE_2 AS PULLTAGNOTE2,
	ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
	ITM.SALEMAXQUANTITY AS MAXORDERQUANTITY, 
	TRIM(ITM.SPECIFICATIONCODE) AS SPECIFICATIONCODE 

FROM --(SELECT DBO.FN_SALEYEAR(NULL)%100 AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW
	OMREVIEWMASTERCODES MC (NOLOCK)
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
	--LEFT JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
	LEFT OUTER JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.ROWID = MC.R_LOT AND VLOT.R_ITEM = ITM.ROWID
	LEFT OUTER JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
	JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
	LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1	AND GEN.CODETYPE = '11'	--GENUSNAME
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'--NOT LIKE 'TAG%'
