/* WOT: 0:20 (20,009 ROWS) 
--SQL_WEEKLY_GOALS 
--	THIS VERSION OF SQL_TRENDS DOES NOT CUT-OFF AT CURRENTDATE BUT EXTENDS AN ADDITIONAL WEEK 
--	DESIGNED EXCLUSIVELY FOR BILLING_REP_GOALS_WEEK WHICH DESIRES TO SEE NEXT WEEKS GOALS 

SELECT * 
FROM VW_RPT_SQL_WEEKLY_GOALS (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 

CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_WEEKLY_GOALS] 
AS 

SELECT 
-------------------------- 
'R' AS RECORDTYPE, 
'SB' AS COMPANYID, 
X.SALEYEAR, 
X.PERIOD, 
X.WEEK, 
RIGHT('0'+TRIM(STR(X.PERIOD,2))+STR(X.WEEK,1),3) AS PERIODWEEK, 
(X.WEEK+(X.PERIOD-1)*4) AS WEEKCOUNT, 
DATEPART(DW,X.TRANSACTIONDATE) AS DAYOFWEEK, 
--CALCULATE THE DATE FOR THE WEEK ENDING: 
DBO.FN_YEAR2DATE(NULL)+28*(X.PERIOD-1)+7*(X.WEEK-1)+6 AS WEEKENDDATE, 
-------------------------- 
X.TRANSACTIONDATE, 
X.WAREHOUSEID, 
X.WAREHOUSENAME, 
NULLIF(X.NATIONALACCOUNT, 'N') AS NATIONALACCOUNT, 
X.SALESREPID, 
X.SALESREPNAME, 
X.CURRAMOUNT, 
X.GOALAMOUNT 
FROM	( 
		SELECT	SALEYEAR, 
				SEASON, 
				PERIOD, 
				WEEK, 
				CAST(CURRTRANSDATE AS DATE) AS TRANSACTIONDATE, 
				WAREHOUSEID, 
				WAREHOUSENAME, 
				SALESREPID, 
				SALESREPNAME, 
				NATIONALACCOUNT, 
				SUM (CURRAMOUNT) AS CURRAMOUNT, 
				SUM (GOALAMOUNT) AS GOALAMOUNT 
        FROM	( 
				SELECT	C.*, 
						C.TRANSACTIONDATE AS CURRTRANSDATE, 
						C.AMOUNT AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS C (NOLOCK) 
				WHERE	C.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		C.AMOUNT <> 0 
				UNION ALL 
				SELECT	G.*, 
						G.TRANSACTIONDATE AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						G.AMOUNT AS GOALAMOUNT 
				FROM	VW_RPT_SQL_GOALS G (NOLOCK) 
				WHERE	G.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		G.AMOUNT <> 0 
				UNION ALL 
				--CURRENT YEAR DATA FROM ePLANT: 
				SELECT	EC.*, 
						EC.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(EC.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_1 EC (NOLOCK) 
				WHERE	EC.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		EC.AMOUNT <> 0 
				) U 
		WHERE U.REPORTGROUP < 4 
		GROUP BY 
				U.SALEYEAR, 
				U.SEASON, 
				U.PERIOD, 
				U.WEEK, 
				CAST(CURRTRANSDATE AS DATE), 
				U.WAREHOUSEID, 
				U.WAREHOUSENAME, 
				U.SALESREPID, 
				U.SALESREPNAME, 
				U.NATIONALACCOUNT 
		) X 
