/* RUNTIME: 33:38 (SPLITTING THIS REPORT INTO IT'S OWN VIEW)
--46 DRIVE AROUND MASTERCODE (ELLEN'S VERSION)
SELECT *
FROM VW_RPT_DRIVE_AROUND_MC (NOLOCK)
WHERE RECORDTYPE <> 'P'
and warehouseid = '10'	--RUNTIME IN TEST: 24:29 (28,130) WAS 55:32 (28,130)
--and itemcode = '000507.021.1'
--AND ITEMCODE = '001094.030.1'
--AND ITEMCODE = '000749.031.1'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_DRIVE_AROUND_MC]
AS
SELECT 
	*,
	PTRAVAILABLE + PTRREVIEWED AS PTRONHAND, 
	(PTRAVAILABLE + PTRREVIEWED) * LISTPRICE AS EXT_PTRONHAND
FROM 
	(	SELECT
			CO.COMPANYID,
			TRIM(CO.NAME) AS COMPANYNAME,
			ITM.RECORDTYPE,
			-----------------------------------
			TRIM(WH.IDENTITYID) AS WAREHOUSEID,
			TRIM(WH.NAME) AS WAREHOUSENAME,
			TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUPCODE,
			ITM.USERDEFINEDCODE_1 AS GENUSCODE,
			GEN.DESCRIPTION_1 AS GENUSNAME,
			(	SELECT TRIM(ITMDP.PROFILECODE) 
				FROM IMITEMDP ITMDP (NOLOCK) 
				WHERE ITMDP.ROWID = ITM.R_PROFILE
				) AS VARIETYCODE,
			(	SELECT CNT.CONTAINERSORT 
				FROM IMCONTAINER CNT (NOLOCK) 
				WHERE CNT.ROWID = ITM.R_CONTAINERCODE
				) AS CONTAINERSORT,
			--ITEM FIELDS:
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.REFERENCE_2 AS BOTANICALNAME,
			ITM.REFERENCE_3 AS REVERSECOMMON,
			ITM.REFERENCE_5 AS SORTNAMEVARIETY,
			TRIM(ITM.CLASSCODE) AS CONTSIZE,
			TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,
			ITM.USERDEFINEDQUANTITY_1 AS LARGEPTRQTY, 
			ITM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY,
			ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
			ITM.USERDEFINEDCODE_18 AS HZ,
			ITM.USERDEFINEDREFERENCE_3 AS INTERCOPO, --ADDED PER ELLEN 8/8/2024 DT
			ITM.SALEMAXQUANTITY AS MAXORDERQUANTITY, 
			TRIM(ITM.SPECIFICATIONCODE) AS SPECIFICATIONCODE,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			DBO.FN_SALESNOTE(ITM.ROWID,VLOT.ROWID, NULL) AS FNSALESNOTE,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_1', VLOT.ROWID, ITM.ROWID) AS si_LTS,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_2', VLOT.ROWID, ITM.ROWID) AS s_LTS,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_3', VLOT.ROWID, ITM.ROWID) AS ai_LTS,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_4', VLOT.ROWID, ITM.ROWID) AS a_LTS,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_9', VLOT.ROWID, ITM.ROWID) AS SEASON_SUPPLY,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_7', VLOT.ROWID, ITM.ROWID) AS SEASON_DEMAND,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_6', VLOT.ROWID, ITM.ROWID) AS SEASON_OH,
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_5', VLOT.ROWID, ITM.ROWID) AS SEASON_AVAILABLE,
			--LOT FIELDS:
			LEFT(VLOT.LOTCODE,2) + 2000 AS SALEYEAR,
			TRIM(VLOT.LOTCODE) AS LOTCODE,
			VLOT.OVERSELLPERCENTAGE,
			VLOT.ON_HAND,
			VLOT.IN_RECEIVING,
			VLOT.OUT_SHIPPED,
			VLOT.OUT_UNAVAILABLE,
			VLOT.AVAILABLE,
			VLOT.USERDEFINEDCODE_5 AS SUSPEND,
			VLOT.USERDEFINEDREFERENCE_3 AS SUSPENDTO,
			VLOT.USERDEFINEDCODE_4 AS SPECIALPULLER,
			VLOT.USERDEFINEDCODE_10 AS SEASON,
			VLOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
			VLOT.USERDEFINEDDATE_1 AS HOLDSTOPBEGINDATE,
			VLOT.USERDEFINEDDATE_2 AS HOLDSTOPENDDATE,
			VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
			VLOT.USERDEFINEDDATE_4 AS HSREASONBEGIN,
			VLOT.USERDEFINEDREFERENCE_7 AS SALESNOTE, 
			VLOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE, 
			VLOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1,
			VLOT.USERDEFINEDREFERENCE_2 AS PULLTAGNOTE2,
			--LOCATION FIELDS:
			LOC.SUBCLASSCODE AS GROWER,
			TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE, 
			SUBSTRING(LOC.LOCATIONCODE,1,1) AS BLOCKALPHA,
			SUBSTRING(LOC.LOCATIONCODE,3,2) AS BLOCKNUMBER,
			SUBSTRING(LOC.LOCATIONCODE,6,3) AS BAY,
			--MC ATTRIBUTES:
			DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'PRIORITY') AS PRIORITY,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigCust') AS DesigCust,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigItem') AS DesigItem,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'DesigLoc') AS DesigLoc,
			DBO.FN_MCATTRIBUTES(MC.ROWID,'Location Note') AS LOCATIONNOTE, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LocNoteDate') AS LOCATIONNOTEDATE, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LocationPTN1') AS LOCATIONPTN1, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LocationPTN2') AS LOCATIONPTN2, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'PriSetBy') AS PRISETBY, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'PriUpdate') AS PRIUPDATED, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'BypassLoc') AS BYPASSLOC, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'LocHold') AS LOCHOLD, 
			ISNULL(MC.STATUS,'A') AS MCSTATUS,	--IS MASTERCODE ACTIVE OR NOT
			ISNULL(MC.PRODUCTIONQUANTITY,0) AS PTRAVAILABLE, 
			--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'AVAILABLE') AS NUMERIC) AS PTRAVAILABLE,		--SPECIAL ATTRIBUTE
			DBO.FN_MCATTRIBUTES_IA(MC.ROWID,'IN SHIPPING') AS PTRINSHIPPING,	--SPECIAL ATTRIBUTE
			DBO.FN_MCATTRIBUTES_IA(MC.ROWID,'PTR REVIEWED') AS PTRREVIEWED--,	--SPECIAL ATTRIBUTE
			--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'IN SHIPPING') AS NUMERIC) AS PTRINSHIPPING,	--SPECIAL ATTRIBUTE
			--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'PTR REVIEWED') AS NUMERIC) AS PTRREVIEWED--,	--SPECIAL ATTRIBUTE
			--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'ONHAND') AS NUMERIC) AS PTRONHAND,			--SPECIAL ATTRIBUTE
			--CAST(DBO.FN_MCATTRIBUTES(MC.ROWID,'ONHAND') AS NUMERIC) * DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS EXT_PTRONHAND

		FROM --(SELECT DBO.FN_SALEYEAR(NULL)%100 AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW
			OMREVIEWMASTERCODES MC (NOLOCK)
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
			LEFT OUTER JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.ROWID = MC.R_LOT
			LEFT OUTER JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1	AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'--NOT LIKE 'TAG%'
	) X