/*
--VIP REPORT					--START4-VIP PLUS EPLANT VOLUME

-------------------------------------------------------------------------------------------------------------------------------------- 
--NOTE:																																-- 
--	LISTATNET AND MERCHATNET ARE NETPRICED TOTALS THAT ARE BELOW THE EARNED PERCENT DISCOUNT RATE ONLY.								-- 
--	THEREFORE VIP3OFFINVOICE ISN'T THE TOTAL OFF-INVOICE AMOUNT, JUST THE PORTION THAT WAS BELOW THE EARNED PERCENT DISCOUNT RATE.	-- 
--	SUBSEQUENTLY, EARNEDVIP3LESSCREDITS IS A RECALCULATION OF THOSE ITEMS AT THE EARNED PERCENT THEN REDUCED BY MERCHCREDITS.		-- 
--	SO IT ISN'T THE TOTAL OFF-INVOICE AMOUNT FOR THE YEAR EITHER. THIS KEEPS IT AN APPLES TO APPLES COMPARISON FOR LOSTVIP3AMOUNT.	-- 
-------------------------------------------------------------------------------------------------------------------------------------- 
--	FORGETTING THIS FACT CAUSED ME CONFUSION WHEN VALIDATING THE DATA SINCE I WAS EXPECTING LISTATNET FOR ALL DISCOUNTED ITEMS.		-- 
-------------------------------------------------------------------------------------------------------------------------------------- 

SELECT * 
FROM VW_RPT_VIPREPORT (NOLOCK) 
WHERE COMPANYID = 'SB'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_VIPREPORT]
AS
SELECT
	*, 
	IIF	(	NONNETMERCH > MERCHCREDITS,												--DON'T WANT TO SEE NEGATIVE CREDIT AMOUNTS 
			ROUND(	(NONNETMERCH - MERCHCREDITS) * EARNEDPERCENT,2),				--VIP2 MERCHCREDITS ARE NONNET SO SUBTRACT THEM BEFORE APPLYING DISCOUNT. 
			NULL) AS VIP2AMOUNT, 
	(LISTATNET - MERCHATNET) AS VIP3OFFINVOICE, 
	(LISTATNET * EARNEDPERCENT - MERCHCREDITS) AS EARNEDVIP3LESSCREDITS,			--VIP3 MERCHCREDITS ARE NETPRICED SO SUBTRACT THEM AFTER APPLYING DISCOUNT. 
	IIF (	(LISTATNET * EARNEDPERCENT - MERCHCREDITS) > (LISTATNET - MERCHATNET),	--DON'T WANT TO SEE NEGATIVE LOST CREDIT AMOUNTS 
			(LISTATNET * EARNEDPERCENT - MERCHCREDITS) - (LISTATNET - MERCHATNET), 
			NULL) AS LOSTVIP3AMOUNT
FROM	(
		SELECT 
			COMPANYID, 
			--CONSROWID, 
			---------- 
			CREDITMANAGERID, 
			CREDITMANAGERNAME, 
			RESPONSIBILITY, 
			SALEYEAR, 
			SALESREPID, 
			SALESREPNAME, 
			GROUPID, 
			CONSIGNEEID, 
			CONSIGNEENAME, 
			WAREHOUSEID, 
			DISCOUNTTYPE, 
			DISCOUNTTYPEDESC, 
			COMBINEFORVIP, 
			VOLUME, 
			EARNEDPERCENT, 
			NULLIF(ISNULL(NONNETMERCH,0)	+ ISNULL(eNONNETMERCH,0),0)	AS NONNETMERCH,		--COMBINE INSIGHT W/EPLANT AND SET TO NULL IF ZERO. 
			(ISNULL(MERCHCREDITS,0)			+ ISNULL(eMERCHCREDITS,0))	AS MERCHCREDITS,	--COMBINE INSIGHT W/EPLANT 
			NULLIF(ISNULL(LISTATNET,0)		+ ISNULL(eLISTATNET,0),0)	AS LISTATNET,		--COMBINE INSIGHT W/EPLANT AND SET TO NULL IF ZERO. 
			NULLIF(ISNULL(MERCHATNET,0)		+ ISNULL(eMERCHATNET,0),0)	AS MERCHATNET		--COMBINE INSIGHT W/EPLANT AND SET TO NULL IF ZERO. 
		FROM	( 
				--CALCULATE TOTALS 
				SELECT 
					*, 
					(	SELECT SUM(OD.UNITPRICE*OD.QUANTITYSHIPPED) 
						FROM OMTRANSACTIONHEADER OH (NOLOCK) 
						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
						JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
						JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
						WHERE OH.R_SHIPPER = X.CONSROWID												--FIND THE CONSIGNEE RECORDS 
						AND X.DISCOUNTTYPE = '2'														--DISCOUNT TYPE IS 2 - VIP END OF YEAR 
						AND OH.RECORDTYPE = 'Z'															--COMMITTED RECORDS ONLY 
						AND OH.TRANSACTIONTYPE = 'I'													--ORDERS ONLY 
						AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = X.SALEYEAR								--FOR APPROPRIATE SALEYEAR 
						AND WH.IDENTITYID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND OD.QUANTITYSHIPPED > 0														--NON-ZERO SHIPPED QUANTITIES 
						AND ROUND(OD.UNITPRICE,2) = DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)	--WHERE ROUNDED(MERCH,2) IS @ FULL LISTPRICE 
						AND ITM.SUBCLASSCODE <> '2'														--ELIMINATE QUALITY 2 RECORDS 
						) AS NONNETMERCH, 
					--eNONNETMERCH: 
					(	SELECT SUM(VIP.NONNETMERCH) 
						FROM GNC_VIPDETAILS VIP (NOLOCK) 
						WHERE VIP.CONSIGNEEID = X.CONSIGNEEID											--FIND THE CONSIGNEE RECORDS 
						AND VIP.DISCOUNTTYPE = '2'														--DISCOUNT TYPE IS 2 - VIP END OF YEAR 
						AND VIP.SALEYEAR = X.SALEYEAR													--FOR APPROPRIATE SALEYEAR 
						AND VIP.WAREHOUSEID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND VIP.NONNETMERCH > 0															--NON-ZERO RECORDS 
						) AS eNONNETMERCH,
					(	SELECT ISNULL(SUM(OD.UNITPRICE*OD.QUANTITYSHIPPED),0) 
						FROM OMTRANSACTIONHEADER OH (NOLOCK) 
						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
						JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
						WHERE OH.R_SHIPPER = X.CONSROWID												--FIND THE CONSIGNEE RECORDS 
						AND OH.RECORDTYPE = 'Z'															--COMMITTED RECORDS ONLY 
						AND OH.TRANSACTIONTYPE <> 'I'													--CREDITS/ADJUSTMENTS ONLY 
						AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = X.SALEYEAR								--FOR APPROPRIATE SALEYEAR 
						AND WH.IDENTITYID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						) AS MERCHCREDITS, 
					--eMERCHCREDITS: 
					(	SELECT SUM(VIP.MERCHCREDITS) 
						FROM GNC_VIPDETAILS VIP (NOLOCK) 
						WHERE VIP.CONSIGNEEID = X.CONSIGNEEID											--FIND THE CONSIGNEE RECORDS 
						AND VIP.SALEYEAR = X.SALEYEAR													--FOR APPROPRIATE SALEYEAR 
						AND VIP.WAREHOUSEID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND VIP.MERCHCREDITS > 0														--NON-ZERO RECORDS 
						) AS eMERCHCREDITS, 
					(	SELECT SUM(DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)*OD.QUANTITYSHIPPED) 
						FROM OMTRANSACTIONHEADER OH (NOLOCK) 
						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
						JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
						JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
						WHERE OH.R_SHIPPER = X.CONSROWID												--FIND THE CONSIGNEE RECORDS 
						AND X.DISCOUNTTYPE = '3'														--DISCOUNT TYPE IS 3 - VIP OFF INVOICE TOTAL 
						AND OH.RECORDTYPE = 'Z'															--COMMITTED RECORDS ONLY 
						AND OH.TRANSACTIONTYPE = 'I'													--ORDERS ONLY 
						AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = X.SALEYEAR								--FOR APPROPRIATE SALEYEAR 
						AND WH.IDENTITYID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND OD.QUANTITYSHIPPED > 0														--NON-ZERO SHIPPED QUANTITIES 
						AND ROUND(OD.UNITPRICE,2) < DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)	--WHERE ROUNDED(MERCH,2) IS LESS THAN LIST 
						AND ((DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL) - OD.UNITPRICE) 
							/ DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)) < X.EARNEDPERCENT		--AND UNITPRICE REDUCED LESS THAN VIP EARNED 
						) AS LISTATNET, 
					--eLISTATNET: 
					(	SELECT SUM(VIP.LISTATNET) 
						FROM GNC_VIPDETAILS VIP (NOLOCK) 
						WHERE VIP.CONSIGNEEID = X.CONSIGNEEID											--FIND THE CONSIGNEE RECORDS 
						AND VIP.DISCOUNTTYPE = '3'														--DISCOUNT TYPE IS 3 - VIP OFF INVOICE TOTAL 
						AND VIP.SALEYEAR = X.SALEYEAR													--FOR APPROPRIATE SALEYEAR 
						AND VIP.WAREHOUSEID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND VIP.LISTATNET > 0															--NON-ZERO RECORDS 
						AND VIP.NETDISCOUNT < X.EARNEDPERCENT											--AND UNITPRICE REDUCED LESS THAN VIP EARNED 
						) AS eLISTATNET, 
					(	SELECT SUM(OD.UNITPRICE*OD.QUANTITYSHIPPED) 
						FROM OMTRANSACTIONHEADER OH (NOLOCK) 
						JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
						JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
						JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
						WHERE OH.R_SHIPPER = X.CONSROWID												--FIND THE CONSIGNEE RECORDS 
						AND X.DISCOUNTTYPE = '3'														--DISCOUNT TYPE IS 3 - VIP OFF INVOICE TOTAL 
						AND OH.RECORDTYPE = 'Z'															--COMMITTED RECORDS ONLY 
						AND OH.TRANSACTIONTYPE = 'I'													--ORDERS ONLY 
						AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = X.SALEYEAR								--FOR APPROPRIATE SALEYEAR 
						AND WH.IDENTITYID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND OD.QUANTITYSHIPPED > 0														--NON-ZERO SHIPPED QUANTITIES 
						AND ROUND(OD.UNITPRICE,2) < DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)	--WHERE ROUNDED(MERCH,2) IS LESS THAN LIST 
						AND ((DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL) - OD.UNITPRICE) 
							/ DBO.FN_LISTPRICE(ITM.ROWID, OH.INVOICEDATE, NULL)) < X.EARNEDPERCENT		--AND UNITPRICE REDUCED LESS THAN VIP EARNED 
						) AS MERCHATNET, 
					--eMERCHATNET: 
					(	SELECT SUM(VIP.MERCHATNET) 
						FROM GNC_VIPDETAILS VIP (NOLOCK) 
						WHERE VIP.CONSIGNEEID = X.CONSIGNEEID											--FIND THE CONSIGNEE RECORDS 
						AND VIP.DISCOUNTTYPE = '3'														--DISCOUNT TYPE IS 3 - VIP OFF INVOICE TOTAL 
						AND VIP.SALEYEAR = X.SALEYEAR													--FOR APPROPRIATE SALEYEAR 
						AND VIP.WAREHOUSEID = X.WAREHOUSEID												--FOR APPROPRIATE WAREHOUSEID 
						AND VIP.MERCHATNET > 0															--NON-ZERO RECORDS 
						AND VIP.NETDISCOUNT < X.EARNEDPERCENT											--AND UNITPRICE REDUCED LESS THAN VIP EARNED 
						) AS eMERCHATNET 
				FROM	( 
						--EAR: CALCULATE EARNEDPERCENT 
						SELECT 
							EAR.*, 
							(	SELECT MAX(DP.DISCOUNTPERCENT) 
								FROM GNC_VIPDISCOUNTPROGRAM DP (NOLOCK) 
								WHERE DP.VIPCODE = EAR.DISCOUNTTYPE 
								AND DP.THRESHOLDAMOUNT <= EAR.VOLUME 
								) AS EARNEDPERCENT 
						FROM	( 
								--SUM VOLUME OF UNION:
								SELECT 
									COMPANYID, 
									CONSROWID,
									---------- 
									CREDITMANAGERID, 
									CREDITMANAGERNAME, 
									RESPONSIBILITY, 
									SALEYEAR, 
									SALESREPID, 
									SALESREPNAME, 
									GROUPID, 
									CONSIGNEEID, 
									CONSIGNEENAME, 
									WAREHOUSEID, 
									DISCOUNTTYPE, 
									DISCOUNTTYPEDESC, 
									COMBINEFORVIP, 
									SUM(VOLUME) AS VOLUME
								FROM	(
										--INSIGHT VOLUME 
										SELECT 
											COMPANYID, 
											CONSROWID, 
											---------- 
											'INSIGHT' AS DATASET, 
											CREDITMANAGERID, 
											CREDITMANAGERNAME, 
											RESPONSIBILITY, 
											SALEYEAR, 
											SALESREPID, 
											SALESREPNAME, 
											GROUPID, 
											CONSIGNEEID, 
											CONSIGNEENAME, 
											WAREHOUSEID, 
											DISCOUNTTYPE, 
											DISCOUNTTYPEDESC, 
											COMBINEFORVIP, 
											IIF(ISNULL(COMBINEFORVIP,'')='Y', 
												--CALCULATE VOLUME AT GROUPID LEVEL: [CURRENT DATA SHOWS THE SAME RESULTS EITHER WAY, BUT THAT COULD CHANGE?] 
												(	SELECT SUM(DBO.FN_ORDERVALUE(OH.ROWID, 'UNITPRICE')) 
													FROM OMTRANSACTIONHEADER OH (NOLOCK) 
													JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
													WHERE CUST.IDGROUP = CUSTIDGROUP						--VOLUME BY GROUPID 
													AND OH.RECORDTYPE = 'Z'									--COMMITTED RECORDS ONLY 
													AND OH.TRANSACTIONTYPE = 'I'							--ORDERS ONLY 
													AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = SALEYEAR			--FOR APPROPRIATE SALEYEAR 
													), 
												--CALCULATE VOLUME AT CUSTOMER LEVEL: [CURRENT DATA SHOWS THE SAME RESULTS EITHER WAY, BUT THAT COULD CHANGE?] 
												(	SELECT SUM(DBO.FN_ORDERVALUE(OH.ROWID, 'UNITPRICE')) 
													FROM OMTRANSACTIONHEADER OH (NOLOCK) 
													WHERE OH.R_CUSTOMER = CUSTROWID							--VOLUME BY CUSTOMERID 
													AND OH.RECORDTYPE = 'Z'									--COMMITTED RECORDS ONLY 
													AND OH.TRANSACTIONTYPE = 'I'							--ORDERS ONLY 
													AND DBO.FN_SALEYEAR(OH.INVOICEDATE) = SALEYEAR			--FOR APPROPRIATE SALEYEAR 
													) 
												) AS VOLUME 
										FROM	( 
												--PRELOAD ACTIVE INSIGHT CUSTOMER/CONSIGNEE DATA FROM OMTRANSACTIONHEADER RECORDS:
												SELECT DISTINCT 
													CONS.COMPANYID, 
													CUST.IDGROUP AS CUSTIDGROUP, 
													CUST.ROWID AS CUSTROWID, 
													CONS.ROWID AS CONSROWID, 
													-------------------------------------------- 
													CRMGR.IDENTITYID AS CREDITMANAGERID, 
													CRMGR.NAME AS CREDITMANAGERNAME, 
													CRMGR.REFERENCE1 AS RESPONSIBILITY, 
													DBO.FN_SALEYEAR(OH.INVOICEDATE) AS SALEYEAR, 
													PART.IDENTITYID AS SALESREPID, 
													PART.NAME AS SALESREPNAME, 
													CUST.IDGROUP AS GROUPID, 
													GRP.DESCRIPTION_1 AS GROUPNAME, 
													CUST.IDENTITYID AS CUSTOMERID, 
													CUST.NAME AS CUSTOMERNAME, 
													CONS.IDENTITYID AS CONSIGNEEID, 
													CONS.NAME AS CONSIGNEENAME, 
													WH.IDENTITYID AS WAREHOUSEID, 
													ICUST.USERDEFINEDCODE_1 AS DISCOUNTTYPE, 
													TYP.DESCRIPTION_1 AS DISCOUNTTYPEDESC, 
													ICUST.USERDEFINEDCODE_11 AS COMBINEFORVIP 
												FROM OMTRANSACTIONHEADER OH (NOLOCK) 
												--OVERLOAD WAREHOUSEID WITH ALL WAREHOUSES: 
												JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID IN ('10','20','40','60') 
												--JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
												JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
												JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
												JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
												JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
												JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
												JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = CONS.COMPANYID
												LEFT JOIN IDMASTER CRMGR (NOLOCK) ON CRMGR.ROWID = CUST.R_CONTACT 
												LEFT JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'				--CUSTOMERGROUPNAME 
												LEFT JOIN IDCODES TYP (NOLOCK) ON TYP.CODE = ICUST.USERDEFINEDCODE_1 AND TYP.CODETYPE = '07'	--DISCOUNTTYPEDESCRIPTION 
												WHERE OH.RECORDTYPE = 'Z' 
												AND OH.TRANSACTIONTYPE = 'I' 
												) PRE 
										WHERE PRE.DISCOUNTTYPE IN (2,3) 

										UNION ALL

										--EPLANT VOLUME
										SELECT 
											CONS.COMPANYID, 
											CONS.ROWID AS CONSROWID, 
											---------- 
											'EPLANT' AS DATASET, 
											CRMGR.IDENTITYID AS CREDITMANAGERID, 
											CRMGR.NAME AS CREDITMANAGERNAME, 
											RESPONSIBILITY, 
											SALEYEAR, 
											PART.IDENTITYID AS SALESREPID, 
											PART.NAME AS SALESREPNAME, 
											GROUPID, 
											CONSIGNEEID, 
											CONSIGNEENAME, 
											WAREHOUSEID, 
											eVOL.DISCOUNTTYPE, 
											TYP.DESCRIPTION_1 AS DISCOUNTTYPEDESC, 
											ICUST.USERDEFINEDCODE_11 AS COMBINEFORVIP, 
											VOLUME 
										FROM GNC_VIPCUSTVOLUME eVOL (NOLOCK) 
										JOIN IDMASTER CONS (NOLOCK) ON CONS.IDENTITYID = eVOL.CONSIGNEEID
										JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CONS.ROWID
										JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID
										JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT
										JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = CONS.COMPANYID
										LEFT JOIN IDMASTER CRMGR (NOLOCK) ON CRMGR.ROWID = CONS.R_CONTACT 
										LEFT JOIN IDCODES TYP (NOLOCK) ON TYP.CODE = eVOL.DISCOUNTTYPE AND TYP.CODETYPE = '07'	--DISCOUNTTYPEDESCRIPTION 
										WHERE eVOL.DISCOUNTTYPE IN (2,3)
										) U
								GROUP BY
									COMPANYID, 
									CONSROWID,
									---------- 
									CREDITMANAGERID, 
									CREDITMANAGERNAME, 
									RESPONSIBILITY, 
									SALEYEAR, 
									SALESREPID, 
									SALESREPNAME, 
									GROUPID, 
									CONSIGNEEID, 
									CONSIGNEENAME, 
									WAREHOUSEID, 
									DISCOUNTTYPE, 
									DISCOUNTTYPEDESC, 
									COMBINEFORVIP 
								) EAR 
						) X 
				) Y
		) Z
WHERE ISNULL(EARNEDPERCENT,0) > 0 
AND	(
		(DISCOUNTTYPE = '2' AND NONNETMERCH > 0)						--ELIMINATE BLANK DISCOUNT TYPE 2 RECORDS 
	OR	(DISCOUNTTYPE = '3' AND (LISTATNET > 0 OR MERCHCREDITS > 0))	--ELIMINATE BLANK DISCOUNT TYPE 3 RECORDS 
	)
--ORDER BY 
--	RESPONSIBILITY, 
--	SALEYEAR, 
--	SALESREPID, 
--	SALESREPNAME, 
--	DISCOUNTTYPE, 
--	GROUPID, 
--	CONSIGNEEID, 
--	WAREHOUSEID 
