/* RT= 0:29 (25,312 ROWS) 
--SQL_BILLING_CUST_TYPE 
SELECT * 
FROM VW_RPT_SQL_BILLING_CUST_TYPE (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_BILLING_CUST_TYPE] 
AS 
SELECT 
IIF(X.SALEYEAR = DBO.FN_DATE2YEAR(NULL),'Y', NULL) AS ISCURRYEAR, 
IIF(X.PERIOD = DBO.FN_DATE2PERIOD(NULL),'Y', NULL) AS ISCURRPERIOD, 
'R' AS RECORDTYPE, 
'SB' AS COMPANYID, 
'Greenleaf Nursery Company' AS COMPANYNAME, 
X.SALEYEAR, 
X.PERIOD, 
-------------------------- 
X.TRANSACTIONDATE, 
X.REPORTGROUP, 
X.WAREHOUSEID, 
ISNULL(X.NATIONALACCOUNT, 'N') AS NATIONALACCOUNT, 
X.CUSTOMERTYPE, 
X.CUSTOMERTYPEDESC, 
--X.CUSTOMERNUMBER, 
--X.CUSTOMERNAME, 
X.CURRAMOUNT, 
X.PREVAMOUNT
FROM 
		( 
		SELECT	DBO.FN_DATE2YEAR(CAST(CURRTRANSDATE AS DATE)) AS SALEYEAR, 
				PERIOD, 
				CAST(CURRTRANSDATE AS DATE) AS TRANSACTIONDATE, 
				REPORTGROUP, 
				WAREHOUSEID, 
				NATIONALACCOUNT, 
				CUSTOMERTYPE, 
				CUSTOMERTYPEDESC, 
				--CUSTOMERNUMBER, 
				--CUSTOMERNAME, 
				SUM (CURRAMOUNT) AS CURRAMOUNT, 
				SUM (PREVAMOUNT) AS PREVAMOUNT 
        FROM	( 
				--CURRENT YEAR DATA FROM INSIGHT: 
				SELECT	C.*, 
						C.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(C.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS C (NOLOCK) 
				WHERE	C.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		C.REPORTGROUP IN (1,3)--< 4 
				AND		C.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM INSIGHT: 
				SELECT	L.*, 
						DBO.FN_DATE4NEXTYEAR(L.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(L.AMOUNT,0) AS PREVAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS L (NOLOCK) 
				WHERE	L.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		L.REPORTGROUP IN (1,3)--< 4 
				AND		L.AMOUNT <> 0 
				UNION ALL 
				--CURRENT YEAR DATA FROM ePLANT: 
				SELECT	EC.*, 
						EC.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(EC.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT 
				FROM	VW_RPT_SQL_1 EC (NOLOCK) 
				WHERE	EC.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		EC.REPORTGROUP IN (1,3)--< 4 
				AND		EC.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM ePLANT: 
				SELECT	EL.*, 
						DBO.FN_DATE4NEXTYEAR(EL.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(EL.AMOUNT,0) AS PREVAMOUNT 
				FROM	VW_RPT_SQL_1 EL (NOLOCK) 
				WHERE	EL.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		EL.REPORTGROUP IN (1,3)--< 4 
				AND		EL.AMOUNT <> 0 
				) U 
		GROUP BY 
				U.SALEYEAR, 
				U.PERIOD, 
				--CURRTRANSDATE, 
				CAST(CURRTRANSDATE AS DATE), 
				U.REPORTGROUP, 
				U.WAREHOUSEID, 
				U.NATIONALACCOUNT, 
				U.CUSTOMERTYPE, 
				U.CUSTOMERTYPEDESC--, 
				--U.CUSTOMERNUMBER, 
				--U.CUSTOMERNAME 
		) X 
