/* GP_LABORGROUP_PRODUCTION_6YEAR
--RT:5:15 @ 52,871
--RT:7:22 @ 52,872 --WITH 3 YEARS ePLANT DATA ADDED
--GP LaborGrp Prod6Yr-Det EXCEL
--GP LaborGrp Prod6Yr-Sum EXCEL

SELECT 
* 
FROM VW_RPT_GP_LABORGROUP_PRODUCTION_6YEAR (NOLOCK)
--MACRO-------------
WHERE WAREHOUSEID = '10' 
--AND LABORGROUP = 'Growing'
--AND JOBCODE = '1000' 
ORDER BY COMPANYID, WAREHOUSEID, LABORGROUP, JOBCODE, DEPARTMENT, CHECKDATE--, ISYTD 
*/
--SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS THRUDATE, 		--THIS RETURNS THE MOST RECENT SATURDAY'S DATE. IMPORTANT FOR THIS REPORT!
--GETDATE() + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) - DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) AS DATE4PRIORYEAR. IMPORTANT CALCULATION FOR THIS REPORT!
--(SELECT BASE.VOLUME FROM IMCONTAINER BASE (NOLOCK) WHERE CONTAINERCODE = '030') IS WHERE I GET THE 615.99 FROM

CREATE OR ALTER VIEW [dbo].[VW_RPT_GP_LABORGROUP_PRODUCTION_6YEAR] 
AS 
SELECT DBO.FN_DATE2YEAR(THRUDATE) AS THRUYEAR, DBO.FN_DATE2PERIOD(THRUDATE) AS THRUPERIOD, DBO.FN_DATE2WEEK(THRUDATE) AS THRUWEEK, *
FROM (
	SELECT 
		Y.COMPANYID, 
		Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		SUM(Y.Y1_52W_HOURS) AS Y1_52W_HOURS, 
		MAX(Y.Y1_52W_UNITS) AS Y1_52W_UNITS, 
		MAX(Y.Y1_52W_EQUIVUNITS) AS Y1_52W_EQUIVUNITS, 
		SUM(Y.Y2_52W_HOURS) AS Y2_52W_HOURS, 
		MAX(Y.Y2_52W_UNITS) AS Y2_52W_UNITS, 
		MAX(Y.Y2_52W_EQUIVUNITS) AS Y2_52W_EQUIVUNITS, 
		SUM(Y.Y3_52W_HOURS) AS Y3_52W_HOURS, 
		MAX(Y.Y3_52W_UNITS) AS Y3_52W_UNITS, 
		MAX(Y.Y3_52W_EQUIVUNITS) AS Y3_52W_EQUIVUNITS, 
		SUM(Y.Y4_52W_HOURS) AS Y4_52W_HOURS, 
		MAX(Y.Y4_52W_UNITS) AS Y4_52W_UNITS, 
		MAX(Y.Y4_52W_EQUIVUNITS) AS Y4_52W_EQUIVUNITS, 
		SUM(Y.Y5_52W_HOURS) AS Y5_52W_HOURS, 
		MAX(Y.Y5_52W_UNITS) AS Y5_52W_UNITS, 
		MAX(Y.Y5_52W_EQUIVUNITS) AS Y5_52W_EQUIVUNITS, 
		SUM(Y.Y6_52W_HOURS) AS Y6_52W_HOURS, 
		MAX(Y.Y6_52W_UNITS) AS Y6_52W_UNITS, 
		MAX(Y.Y6_52W_EQUIVUNITS) AS Y6_52W_EQUIVUNITS, 
		Y.PRTYPE, Y.PRCODE 
	FROM ( 
			SELECT 
				WH.COMPANYID, 
				WH.IDENTITYID AS WAREHOUSEID, 
				WH.NAME AS WAREHOUSENAME, 
				X.DEPRTMNT AS DEPARTMENT, 
				X.DEPTDESC AS DEPARTMENTDESC, 
				--IIF(LEFT(X.JOBDESC, 7) = 'Project', 'Maintenance', LG.LABORGROUP) AS LABORGROUP,	--NOT WANTED IN PRODUCTION VERSION 
				--IIF(LEFT(X.JOBDESC, 7) = 'Project', '57***', X.JOBTITLE) AS JOBCODE,				--NOT WANTED IN PRODUCTION VERSION 
				LG.LABORGROUP, 
				X.JOBTITLE AS JOBCODE, 
				X.JOBDESC AS JOBCODEDESC, 
				GETDATE()-(DATEPART(DW,GETDATE())%7) AS THRUDATE, 
				--DATEPART(YEAR, DATEADD(MONTH,4,X.CHECKDATE)) AS FISCALYEAR, 
				X.CHECKDATE, 
				X.Y1_52W_HOURS, X.Y1_52W_UNITS, X.Y1_52W_EQUIVUNITS, 
				X.Y2_52W_HOURS, X.Y2_52W_UNITS, X.Y2_52W_EQUIVUNITS, 
				X.Y3_52W_HOURS, X.Y3_52W_UNITS, X.Y3_52W_EQUIVUNITS, 
				X.Y4_52W_HOURS, X.Y4_52W_UNITS, X.Y4_52W_EQUIVUNITS, 
				X.Y5_52W_HOURS, X.Y5_52W_UNITS, X.Y5_52W_EQUIVUNITS, 
				X.Y6_52W_HOURS, X.Y6_52W_UNITS, X.Y6_52W_EQUIVUNITS, 
				X.PYRLRTYP AS PRTYPE, 
				X.PAYROLCD AS PRCODE 
			FROM ( 
					--CURRENT 52WEEK TOTALS		RT:426,373 @ 3:35
					SELECT 
						YR1.CHEKDATE AS CHECKDATE, 
						YR1.UNTSTOPY AS Y1_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -((7*52)-1)				--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -((7*52)-1)				--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							), 0) AS Y1_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -((7*52)-1)				--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -((7*52)-1)				--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							), 0) AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days YR1 (NOLOCK) 
					--GET 52 WEEK'S DATA
					WHERE CHEKDATE >= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -((7*52)-1)				--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND YR1.UNTSTOPY > 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR2.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						YR2.UNTSTOPY AS Y2_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y2_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days YR2 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*52)-1)										--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR2.UNTSTOPY > 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR3.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						YR3.UNTSTOPY AS Y3_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y3_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR3 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*52)-1)										--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR3.UNTSTOPY > 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR4.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						YR4.UNTSTOPY AS Y4_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y4_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR4 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*52)-1)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR4.UNTSTOPY > 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR5.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						YR5.UNTSTOPY AS Y5_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y5_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR5 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*52)-1)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR5.UNTSTOPY > 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR6.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						YR6.UNTSTOPY AS Y6_52W_HOURS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y6_52W_UNITS, 
						ISNULL(
						(	SELECT SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM IMTRANSACTIONHEADER TH (NOLOCK) 
							JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND (
								TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
								OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							AND WH.IDENTITYID = WAREHOUSE 
							AND TH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND TH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) 
						+ ISNULL( 
						(	SELECT SUM(ISNULL(PRD.RECEIVEDQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM PORECEIPTSHEADER PRH (NOLOCK)
							JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
							AND WH.IDENTITYID = WAREHOUSE 
							AND PRH.COMMITDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -((7*52)-1)										--RANGE: 52 WEEKS
							AND PRH.COMMITDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							), 0) AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR6 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*52)-1)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR6.UNTSTOPY > 0
-----------------------------------------------------------------------------------------------------------------------------------------------------
--ePLANT HISTORICAL DATA SECTION:
-----------------------------------------------------------------------------------------------------------------------------------------------------

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR4H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 /*YR4H.UNTSTOPY*/ AS Y4_52W_HOURS, 
						--ISNULL( 
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
						--	), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y4_52W_UNITS, 
						--ISNULL( 
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
						--	), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR4H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR4H.UNTSTOPY != 0

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR5H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 /*YR5H.UNTSTOPY*/ AS Y5_52W_HOURS, 
						--ISNULL(
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
						--	), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y5_52W_UNITS, 
						--ISNULL(
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
						--	), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR5H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR5H.UNTSTOPY != 0

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR6H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 /*YR6H.UNTSTOPY*/ AS Y6_52W_HOURS, 
--						ISNULL(
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							--), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y6_52W_UNITS, 
						--ISNULL(
						(	SELECT SUM(ISNULL(HIST.ADJUSTMENTQUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							--FROM GNC_ITEM_TRANSACTION_ARCHIVE HIST (NOLOCK) 
							--FROM [ORACLE]..[ROL].[ITEM_TRANSACTION] HIST (NOLOCK) 
							FROM GNC_ITEM_TRANSACTION_FULL HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.DIVISIONNUMBER
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
							AND (
								HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
								OR (HIST.TRANSACTIONTYPE = 'MI' AND HIST.ADJUSTMENTQUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
								)
							--AND HIST.TRANSACTIONREASONCODE IN ('02','07','61') --(CODE IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
						--	), 0) 
						--+ ISNULL( 
						--(
						--	SELECT SUM(ISNULL(IPD.QUANTITYORDERED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
						--	FROM [ORACLE]..[ROL].[IP_ORDER_HEADER] IPH (NOLOCK) 
						--	JOIN [ORACLE]..[ROL].[IP_ORDER_DETAIL] IPD (NOLOCK) ON IPD.INVENTORYPURCHASENUMBER = IPH.INVENTORYPURCHASENUMBER AND IPD.IPRELEASENUMBER = IPH.IPRELEASENUMBER
						--	JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = IPH.DIVISIONNUMBER
						--	JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IPD.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID 
						--	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
						--	WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART') 
						--	AND WH.IDENTITYID = WAREHOUSE 
						--	AND IPH.UNLOADDATE >= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							) -((7*52)-1)										--RANGE: 52 WEEKS
						--	AND IPH.UNLOADDATE <= (	GETDATE() -											--TODAY
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
						--							DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
						--							(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
						--							)
						--	), 0
						) AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR6H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR6H.UNTSTOPY != 0

			-----------------------------------------
			) X 
			JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = WAREHOUSE 
			--LEFT 	--UNCOMMENT THIS LINE TO INCLUDE 'Projects' LABORGRP IN THE REPORT.	--NOT WANTED IN PRODUCTION VERSION 
			JOIN GNC_LABORGROUPSBYGP_JOBCODE LG (NOLOCK) ON LG.JOBCODE = X.JOBTITLE
			WHERE ISNULL(LG.BENCHMARK,'PRODUCTION') = 'PRODUCTION'
	) Y
	WHERE Y.LABORGROUP IS NOT NULL
	GROUP BY 
		Y.COMPANYID, Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		Y.PRTYPE, Y.PRCODE 
) Z
