/*
--91 LEFT TO SELL PRODUCTION
--91 LEFT TO SELL PRODUCTION EXCEL
--RUNTIME- 1:28 (5043 REC)

SELECT *
FROM VW_RPT_LEFT_TO_SELL_PRODUCTION (NOLOCK)
WHERE (F1_LTS <> 0 
OR F2_LTS <> 0 
OR S1_LTS <> 0 
OR S2_LTS <> 0 
OR U1_LTS <> 0 
OR U2_LTS <> 0 
OR U3_LTS <> 0 
OR X_LTS <> 0 
OR Y_LTS <> 0) 
--WHERE F1_LTS + F2_LTS + S1_LTS + S2_LTS + U1_LTS + U2_LTS + U3_LTS + X_LTS + Y_LTS <> 0 
-------------------------------------------
AND ITEMCODE = '000310.010.1'
AND ITEMCODE IN ('000758.010.1','008040.250.1','008070.250.1','008120.030.1')
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_LEFT_TO_SELL_PRODUCTION]
AS
SELECT
			CO.COMPANYID,
			TRIM(CO.NAME) AS COMPANYNAME,
			ITM.RECORDTYPE,
			TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
			TRIM(WH.NAME) AS WAREHOUSENAME,
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			CNT.PRINTEDCONTAINERCODE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.USERDEFINEDCODE_2 AS BRAND,
			ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
			ITM.USERDEFINEDCODE_18 AS HZ,
			TRIM(PC.PRODUCTCATEGORYCODE) AS PLANTGROUP,
			ITM.REFERENCE_5 AS SORTNAMEVARIETY,
			CNT.CONTAINERSORT,
			TRIM(ITM.SUBCLASSCODE) AS QUALITY,
			ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
			--GEN.DESCRIPTION_1 AS GENUSNAME, 
			--ITM.USERDEFINEDREFERENCE_2 AS GRADEMEASURE,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.F1'
				) AS F1_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.F2'
				) AS F2_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.S1'
				) AS S1_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.S2'
				) AS S2_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.U1'
				) AS U1_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.U2'
				) AS U2_HS,
			(	SELECT DBO.FN_HOLDSTOP_OVERRIDE(ITM.ROWID,VLOT.ROWID)--USERDEFINEDCODE_3
				FROM	VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE	VLOT.R_ITEM = ITM.ROWID
				AND		VLOT.LOTCODE = TRIM(STR(DBO.FN_SALEYEAR(NULL)%100)) + '.U3'
				) AS U3_HS,
			--{NULL} LOTYEAR FORCES LTS TO CY+PY ROLLUP: 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F1%',NULL) AS F1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F2%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F2%',NULL) AS F2_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S1%',NULL) AS S1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S2%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S2%',NULL) AS S2_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U1%',NULL) AS U1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U2%',NULL) AS U2_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U3%',NULL) AS U3_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'X%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'X%',NULL) AS X_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'Y%',NULL,NULL)	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'Y%',NULL) AS Y_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F1%',NULL) AS F1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F2%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F2%',NULL) AS F2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S1%',NULL) AS S1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S2%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S2%',NULL) AS S2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U1%',NULL) AS U1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U2%',NULL) AS U2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3%',NULL,'I')	- DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U3%',NULL) AS U3_iLTS 
FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY
--LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE =  '11' --GENUS
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'
