/* 
--SUSPEND MISMATCH REPORT
SELECT *
FROM VW_RPT_SUSPEND_MISMATCH (NOLOCK)
WHERE COMPANYID = 'SB'
and warehouseid = '20' 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_SUSPEND_MISMATCH]
AS
SELECT * 
FROM ( 
		SELECT CO.COMPANYID, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ITM.ITEMCODE, ITM.REFERENCE_1 AS COMMONNAME, LOT.LOTCODE, LOC.LOCATIONCODE, 
			DBO.FN_MCATTRIBUTES(MC.ROWID, 'SUSPEND') AS MCSUSPEND, 
			LOT.USERDEFINEDCODE_5 AS LOT_UDC5
		FROM 
		OMREVIEWMASTERCODES MC (NOLOCK) 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
		JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
	) X
WHERE ISNULL(MCSUSPEND,'') != ISNULL(LOT_UDC5,'')
--ORDER BY WAREHOUSEID, ITEMCODE, LOTCODE, LOCATIONCODE
