/*
--HOLDS ON ORDERS	--NEW EMAIL REPORT
SELECT * 
FROM VW_RPT_HOLDS_ON_ORDERS (NOLOCK)
WHERE 1=1
ORDER BY 
COMPANYID, SALESREPID, WAREHOUSEID, CONSIGNEENAME, TRANSACTIONNUMBER, ITEMCODE 

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_HOLDS_ON_ORDERS]
AS
SELECT 
OM.COMPANYID, OM.COMPANYNAME, 
CAST (GETDATE()-(4*7) AS DATE) AS FROMDATE,
CAST (GETDATE()+(2*7) AS DATE) AS THRUDATE,
OM.WAREHOUSEID, OM.WAREHOUSENAME, 
OM.SALESREPID, OM.SALESREPNAME, 
OM.REQUESTDATE, OM.REQUESTDATETYPE, 
OM.FMTRIPNUMBER, OM.FMPUSTOPNUMBER, 
OM.RECORDTYPE, OM.STEP, OM.STEPDESC, 
OM.NATLACCT, OM.INVENTORYREVIEW, 
OM.CONSIGNEEIDENTITYID, OM.CONSIGNEENAME, 
OM.TRANSACTIONNUMBER, OM.PURCHASEORDERNUMBER, 
OM.ITEMCODE, OM.COMMONNAME, 
OM.HOLDSTOPCODE, 
--OM.HOLDSTOPREASON, 
TRIM(OM.HOLDSTOPCODE) + ':  ' + ISNULL(OM.HOLDSTOPREASON,'') AS HOLDSTOPREASON, 
OM.PICKNOTE, 
IIF(OM.PICKNOTE LIKE '%H/O%', 'Y', 'N') AS ISHOLDOVERRIDE, 
OM.QUANTITYATSTAGE,
OM.EXTUNITPRICE, OM.EXTLANDEDPRICE 
FROM VW_RPT_OM_VERSION_MASTER OM (NOLOCK) 
WHERE OM.RECORDTYPE = 'R' 
AND OM.HOLDSTOPCODE IN ('H','S') 
AND OM.STEP IN ('WAITING', 'SHIPPABLE') 
AND OM.REQUESTDATE BETWEEN GETDATE()-(4*7) AND GETDATE()+(2*7) 
AND OM.QUANTITYATSTAGE != 0
AND OM.SALESREPID NOT IN ('S01','S99')



