/*
--Inv by Item-Inquiry Page Tagno

SELECT * 
FROM VW_RPT_INVENTORY_BY_ITEM_INQUIRY_SETNO 
WHERE 1=1

--AND SETNO = 'MC-23044'	--report must be limited by either setno or tripno in order for it to finish!
*/

CREATE OR ALTER VIEW [dbo].[VW_RPT_INVENTORY_BY_ITEM_INQUIRY_SETNO] 
AS 
--WIDEOPEN RT=>1:11:34 @ 84,049,348 rows
SELECT 
OH.SETNO, OH.FMTRIPNUMBER AS TRIPNO, RPT.*
FROM VW_RPT_INVENTORY_BY_ITEM_INQUIRY RPT (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = RPT.ROWID 
JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
--WHERE OH.SETNO = 'je-14663'	--LIMITED RT=>1:06 @5,701 ROWS

