/* 
--110 PLANTING PROGRESS EXCEL 
SELECT *, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 
and psid ='2148'--between '3478' and '3479'

--110 PLANTING PROGRESS BY PS LINE 
SELECT *, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 

--110 PLANTING PROGRESS BY ITEM 
SELECT *, 
TRIM(ISNULL(PLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'')+'|'+PSPRINTEDCONTAINERCODE AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 
and psitemnumber = '1175.030.1' and targetplantingdate between '2021/10/01' and '2021/11/01' 

--110 PLANTING PROGRESS BY DATE 
select * from (
SELECT *, 
TARGETPLANTINGDATE AS SORT1, 
PSPRINTEDCONTAINERCODE AS SORT2, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'')+'|'+ISNULL(PSID,'') AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 
and warehouseid = '10'
and scheduleyear = '23'
and udc_b = 'S Drill Shift'
) x
order by 
sort1, sort2, sort3, actualplanteddate


--110 PLANTING PROGRESS SUMMARY 
SELECT *, 
IIF(WAREHOUSEID='20',PSPRINTEDCONTAINERCODE,CONVERT(CHAR,TARGETPLANTINGDATE,111)) AS SORT1, 
IIF(WAREHOUSEID='20',CONVERT(CHAR,TARGETPLANTINGDATE,111),PSPRINTEDCONTAINERCODE) AS SORT2, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'')+'|'+ISNULL(PSID,'') AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 
--
and warehouseid = '10' and scheduleyear = '23' and udc_b like 'F Jap Maple%'

--110 PLANTING PROGRESS EXCEPTIONS 
SELECT *, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
PSPRINTEDCONTAINERCODE AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE TARGETPRICE IS NULL OR EXCEPTIONTEXT IS NOT NULL 

--110 PLANTING PROGRESS UNDER only --removing from the menu so they use PLANTING PROGRESS UNDERPLANTED instead.
SELECT *, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE TOTALPLANTEDQTY < TARGETPLANTINGQTY 
AND TOTALPLANTEDQTY <> 0 

--110 PLANTING PROGRESS UNDERPLANTED 
SELECT *, 
--IIF(TOTALPLANTEDQTY < TARGETPLANTINGQTY 
-- AND TOTALPLANTEDQTY <> 0, 'Y', NULL) AS ISUNDERPLANTED, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 

--110 PLANTING PROGRESS OVERPLANTED 
SELECT *, 
TRIM(ISNULL(PSPLANTGROUP,'0'))+'|'+ISNULL(PSSORTNAMEVARIETY,'') AS SORT1, 
TRIM(CONVERT(CHAR,TARGETPLANTINGDATE,111))+'|'+UDC_A AS SORT2, 
PSID AS SORT3 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE TOTALPLANTEDQTY > TARGETPLANTINGQTY 

*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_PLANTING_PROGRESS] 
AS 
SELECT	--7,768 RECORDS 
	--Items NOTSETUP return a NULL for TOTALPLANTEDQTY giving inaccurate flag statuses...now fixed with ISNULL() 
	IIF(ISNULL(U.TOTALPLANTEDQTY,0) < PS.TARGETPLANTINGQTY, 
		IIF(ISNULL(U.TOTALPLANTEDQTY,0) = 0, 'N', 'P'), 
		'Y') AS ISPLANTED_YPN, 
	IIF(ISNULL(U.TOTALPLANTEDQTY,0) < PS.TARGETPLANTINGQTY, 
		IIF(ISNULL(U.TOTALPLANTEDQTY,0) = 0, 'Zeros', 'Unders'), 
		'Finals') AS ISPLANTED_TEXT, 
	PS.COMPANYID, 
	PS.RECORDTYPE, 
	PS.EXCEPTIONTEXT,
	PS.SCHEDULEYEAR,
	PS.PSID,
	PS.PLANTINGSCHEDULELINE AS PSLINE,
	PS.PSITEMNUMBER,
	PS.PSCOMMONNAME,
	PS.PSPLANTGROUP,
	PS.PSSORTNAMEVARIETY,
	PS.PSPRINTEDCONTAINERCODE,
	PS.PLANTINGBLOCKNOTES,
	PS.PSSOURCE,
	PS.UDC_A,
	PS.UDC_B,
	PS.TARGETPLANTINGDATE,
	PS.TARGETPLANTINGQTY,
	PS.TARGETPRICE,
	PS.WAREHOUSEID,
	--U.*
	U.ACTUALWHID, 
	U.WAREHOUSENAME, 
	U.SALEYEAR, 
	U.ITEMCODE, 
	U.LOTCODE, 
	U.BEDSIZE, 
	U.EXPOSURE, 
	U.COMMONNAME, 
	U.SORTNAMEVARIETY, 
	U.PRINTEDCONTAINERCODE, 
	U.PLANTGROUP, 
	U.GENUSCODE, 
	U.GENUSNAME, 
	U.TRANSCODE, 
	U.TRANSACTIONREASONCODE_OLD, 
	U.TRANSACTIONREASONCODE, 
	U.PLANTINGSCHEDULELINE, 
	U.PLANTINGTEXT, 
	U.SOURCE, 
	U.LOCATIONCODE, 
	U.INSERTUSER, 
	U.ACTUALPLANTEDDATE, 
	ISNULL(U.ACTUALPLANTEDQTY,0) AS ACTUALPLANTEDQTY, 
	U.TOTALPLANTEDQTY, 
	ISNULL(U.LISTPRICE,0) AS LISTPRICE 
FROM	VW_RPT_GNC_PLANTINGSCHEDULE PS (NOLOCK) 
		LEFT JOIN (
		--INSIGHT DATA	--2146 RECORDS
		--IMTRANSACTION DATA
		SELECT 
			TRIM(WH.IDENTITYID) AS ACTUALWHID,--AS WAREHOUSEID, 
			TRIM(WH.NAME) AS WAREHOUSENAME, 
			TH.FISCALYEAR AS SALEYEAR, 
			TRIM(ITM.ITEMCODE) AS ITEMCODE, 
			TRIM(LOT.LOTCODE) AS LOTCODE, 
			'[SOURCE???]' AS BEDSIZE, 
			ITM.USERDEFINEDCODE_7 AS EXPOSURE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
			ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
			GEN.DESCRIPTION_1 AS GENUSNAME, 
			TD.USERDEFINEDCODE_1 AS TRANSCODE, 
			TH.REFERENCE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
			LEFT(TRIM(TD.USERDEFINEDCODE_1),8) AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
			TD.USERDEFINEDREFERENCE_1 AS PLANTINGSCHEDULELINE, 
			TD.USERDEFINEDREFERENCE_2 AS PLANTINGTEXT, 
			TRIM(TD.USERDEFINEDCODE_2) AS SOURCE, 
			LOC.LOCATIONCODE,	--QUESTIONING THIS 
			TH.CREATIONUSERID AS INSERTUSER, 
			TD.USERDEFINEDDATE_1 AS ACTUALPLANTEDDATE, 
			ISNULL(TD.QUANTITY,0) AS ACTUALPLANTEDQTY, 
			(	SELECT SUM(ISNULL(TD2.QUANTITY,0)) FROM IMTRANSACTIONHEADER TH2 (NOLOCK) 
				JOIN IMTRANSACTIONDETAIL TD2 (NOLOCK) ON TD2.R_TRANSACTIONHEADER = TH2.ROWID 
				JOIN IDMASTER WH2 (NOLOCK) ON WH2.ROWID = TD2.R_WAREHOUSE 
				WHERE WH2.IDENTITYID = WH.IDENTITYID 
				AND TD2.USERDEFINEDREFERENCE_1 = TD.USERDEFINEDREFERENCE_1 
				AND TD2.USERDEFINEDCODE_1 IN ('Plant','Planting','Shift-in','Shift.IN','Specialty','Receipt-IM')	--new codes to filter with per Ellen 7/17/23
				--AND TH2.REFERENCE IN ('02','07','25','26','60','61') 
				AND TD2.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS PLANTING DATE
				) AS TOTALPLANTEDQTY, 
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE 

		FROM IMTRANSACTIONHEADER TH (NOLOCK) 
		JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
		JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT 
		JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = TD.ROWID 
		JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION 
		WHERE TD.USERDEFINEDCODE_1 IN ('Plant','Planting','Shift-in','Shift.IN','Specialty','Receipt-IM')	--new codes to filter with per Ellen 7/17/23
		--TH.REFERENCE IN ('02','07','25','26','60','61') 
		--AND TD.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS DEFINED AS PLANTING DATE (IS THIS ELIMINATING NON-STARTED ITEMS THAT HARRISON COOK WAS COMPLAINING ABOUT?) 

		UNION ALL----------------49,470 RECORDS--------------------------------------------------------------------

		--PORECEIPTS DATA
		SELECT 
			TRIM(WH.IDENTITYID) AS ACTUALWHID,--AS WAREHOUSEID, 
			TRIM(WH.NAME) AS WAREHOUSENAME, 
			POH.FISCALYEAR AS SALEYEAR, 
			TRIM(ITM.ITEMCODE) AS ITEMCODE, 
			TRIM(LOT.LOTCODE) AS LOTCODE, 
			'[SOURCE???]' AS BEDSIZE, 
			ITM.USERDEFINEDCODE_7 AS EXPOSURE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
			ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
			GEN.DESCRIPTION_1 AS GENUSNAME, 
			POD.USERDEFINEDCODE_1 AS TRANSCODE, 
			POH.REFERENCENUMBER AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE --guessing a fieldname for this new table pull
			'PORecpt' AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
			POD.USERDEFINEDREFERENCE_1 AS PLANTINGSCHEDULELINE, 
			POD.USERDEFINEDREFERENCE_3 AS PLANTINGTEXT,  --guessing a fieldname for this new table pull (substitute for USERDEFINEDREFERENCE_2)
			TRIM(POD.USERDEFINEDCODE_2) AS SOURCE, 
			LOC.LOCATIONCODE,	--QUESTIONING THIS 
			POH.CREATIONUSERID AS INSERTUSER, 
			--POD.DATEEXPECTED AS ACTUALPLANTEDDATE,  --guessing a fieldname for this new table pull (substitute for plantingdate)
			POH.USERDEFINEDDATE_2 AS ACTUALPLANTEDDATE, --FINALLY GIVEN THE CORRECT DATE FOR THIS. 01/17/24 DT
			ISNULL(POD.RECEIVEDQUANTITY,0) AS ACTUALPLANTEDQTY, --guessing a fieldname for this new table pull (substitute for quantity)
			(	SELECT SUM(ISNULL(POD2.RECEIVEDQUANTITY,0)) FROM PORECEIPTSHEADER POH2 (NOLOCK) 
				JOIN PORECEIPTSDETAIL POD2 (NOLOCK) ON POD2.R_RECEIPTSHEADER = POH2.ROWID 
				JOIN IDMASTER WH2 (NOLOCK) ON WH2.ROWID = POD2.R_WAREHOUSE 
				WHERE WH2.IDENTITYID = WH.IDENTITYID 
				AND POD2.USERDEFINEDREFERENCE_1 = POD.USERDEFINEDREFERENCE_1 
				AND POH2.RECORDTYPE = 'Z' 
				AND POD2.DATEEXPECTED IS NOT NULL 
				) AS TOTALPLANTEDQTY, 
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE 

		FROM PORECEIPTSHEADER POH (NOLOCK) 
		JOIN PORECEIPTSDETAIL POD (NOLOCK) ON POD.R_RECEIPTSHEADER = POH.ROWID 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = POD.R_WAREHOUSE 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = POD.R_ITEM 
		JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = POD.R_LOT 
		JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = POD.ROWID 
		JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION 
		WHERE POH.RECORDTYPE = 'Z'--TH.REFERENCE IN ('02','07','25','26','60','61') 
		--AND POD2.DATEEXPECTED IS NOT NULL Substituting for:--AND TD.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS DEFINED AS PLANTING DATE (IS THIS ELIMINATING NON-STARTED ITEMS THAT HARRISON COOK WAS COMPLAINING ABOUT?) 

/* COMMENTING OUT EPLANT SECTION-----
		UNION ALL----------------49,470 RECORDS--------------------------------------------------------------------

		--ePLANT DATA	--47,324 RECORDS
		SELECT 
			TRIM(WH.IDENTITYID) AS ACTUALWHID,--AS WAREHOUSEID,
			TRIM(WH.NAME) AS WAREHOUSENAME,
			IT.SALEYEAR,
			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			'ePLANT' AS LOTCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
			'[SOURCE???]' AS BEDSIZE,
			ITM.USERDEFINEDCODE_7 AS EXPOSURE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.REFERENCE_5 AS SORTNAMEVARIETY,
			TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
			ITM.USERDEFINEDCODE_1 AS GENUSCODE,
			GEN.DESCRIPTION_1 AS GENUSNAME,
			'ePLANT' AS TRANSCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
			IT.TRANSACTIONREASONCODE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
			NULL AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
			IT.PLANTINGSCHEDULELINE,
			IT.PLANTINGTEXT,
			NULL AS SOURCE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
			IT.TOLOCATION AS LOCATIONCODE, 
			IT.INSERTUSER,
			IT.ACTUALPLANTEDDATE, 
			--FORMAT(CONVERT(DATE,IT.ACTUALPLANTEDDATE),'yyyy/MM/dd') AS ACTUALPLANTEDDATE,
			IT.ADJUSTMENTQUANTITY AS ACTUALPLANTEDQTY, 
			(	SELECT SUM(ISNULL(IT2.ADJUSTMENTQUANTITY,0)) FROM GNC_ITEM_TRANSACTION_ARCHIVE IT2 (NOLOCK)
				WHERE IT2.DIVISIONNUMBER = IT.DIVISIONNUMBER
				AND IT2.PLANTINGSCHEDULELINE = IT.PLANTINGSCHEDULELINE
				AND IT2.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
				AND IT2.INSERTDATE IS NOT NULL
				) AS TOTALPLANTEDQTY,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE

		FROM GNC_ITEM_TRANSACTION_ARCHIVE IT (NOLOCK)
		JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = TRIM(STR(IT.DIVISIONNUMBER))
		--JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE
		JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IT.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID
		--JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM
		JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE IT.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
*/
		) U ON	PS.WAREHOUSEID = U.ACTUALWHID--U.WAREHOUSEID
			AND PS.PLANTINGSCHEDULELINE = U.PLANTINGSCHEDULELINE
----------------------------------------------------------------------------------




/* FIRST ATTEMPT AT REFACTORING FAILED...
SELECT *
FROM (
	-------------------------- 
	-- INSIGHT DATA SECTION -- 
	-------------------------- 
	SELECT 
		ITM.RECORDTYPE, 
		CO.COMPANYID, 
		CO.NAME AS COMPANYNAME, 
		TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
		TRIM(WH.NAME) AS WAREHOUSENAME, 
		IIF(PSI.REFERENCE_1 IS NULL, IIF(PS.PSITEMNUMBER IS NULL, '(ITEM NOT SPECIFIED)', '(VARIETY/ITEM NOT SETUP)'), NULL) AS EXCEPTIONTEXT, 
		TH.FISCALYEAR AS SALEYEAR, 
		PS.SCHEDULEYEAR, 
		TRIM(REPLACE(PS.PLANTINGSCHEDULELINE,',','')) AS PSID, 
		TRIM(PS.PSITEMNUMBER) AS PSITEMNUMBER, 
		PSI.REFERENCE_1 AS PSCOMMONNAME, 
		PSP.PRODUCTCATEGORYCODE AS PSPLANTGROUP, 
		PSI.REFERENCE_5 AS PSSORTNAMEVARIETY, 
		PSC.PRINTEDCONTAINERCODE AS PSPRINTEDCONTAINERCODE, 
		TRIM(ITM.ITEMCODE) AS ITEMCODE, 
		TRIM(LOT.LOTCODE) AS LOTCODE, 
		'[SOURCE???]' AS BEDSIZE, 
		ITM.USERDEFINEDCODE_7 AS EXPOSURE, 
		ITM.REFERENCE_1 AS COMMONNAME, 
		ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
		TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
		PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
		ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
		GEN.DESCRIPTION_1 AS GENUSNAME, 
		TD.USERDEFINEDCODE_1 AS TRANSCODE, 
		TH.REFERENCE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
		TD.USERDEFINEDCODE_1 AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
		TD.USERDEFINEDREFERENCE_1 AS PLANTINGSCHEDULELINE, 
		TD.USERDEFINEDREFERENCE_2 AS PLANTINGTEXT, 
		PS.PLANTINGBLOCKNOTES, 
		TRIM(PS.SOURCE) AS PSSOURCE, 
		TRIM(TD.USERDEFINEDCODE_2) AS SOURCE, 
		PS.UDC_A, 
		ISNULL(PS.UDC_B,' ') AS UDC_B, 
		LOC.LOCATIONCODE,	--QUESTIONING THIS 
		TH.CREATIONUSERID AS INSERTUSER, 
		TRIM(CONVERT(CHAR,TD.USERDEFINEDDATE_1,111)) AS ACTUALPLANTEDDATE, 
		TD.QUANTITY AS ACTUALPLANTEDQTY, 
		TH.REFERENCE AS TESTDATA, 
		(	SELECT SUM(ISNULL(TD2.QUANTITY,0)) FROM IMTRANSACTIONHEADER TH2 (NOLOCK) 
			JOIN IMTRANSACTIONDETAIL TD2 (NOLOCK) ON TD2.R_TRANSACTIONHEADER = TH2.ROWID 
			JOIN IDMASTER WH2 (NOLOCK) ON WH2.ROWID = TD2.R_WAREHOUSE 
			WHERE WH2.IDENTITYID = WH.IDENTITYID 
			AND TD2.USERDEFINEDREFERENCE_1 = TD.USERDEFINEDREFERENCE_1 
			AND TH2.REFERENCE IN ('02','07','25','26','60','61') 
			AND TD2.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS PLANTING DATE
			) AS TOTALPLANTEDQTY, 
		TRIM(CONVERT(CHAR,PS.TARGETPLANTINGDATE,111)) AS TARGETPLANTINGDATE, 
		PS.TARGETPLANTINGQTY, 
		DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
		DBO.FN_LISTPRICE(PSI.ROWID,NULL,NULL) AS TARGETPRICE 

	FROM GNC_PLANTINGSCHEDULE PS (NOLOCK) 
		LEFT JOIN IDMASTER PSW (NOLOCK) ON PSW.IDENTITYID = PS.DIVISIONNUMBER 
		LEFT JOIN IMITEM PSI (NOLOCK) ON PSI.ITEMCODE = '00'+PS.PSITEMNUMBER AND PSI.R_WAREHOUSE = PSW.ROWID AND PSI.STATUS = 'A' 
		LEFT JOIN IMPRODUCTCATEGORY PSP (NOLOCK) ON PSP.ROWID = PSI.R_PRODUCTCATEGORY 
		LEFT JOIN IMCONTAINER PSC (NOLOCK) ON PSC.ROWID = PSI.R_CONTAINERCODE 
		---------------------------------------------------------------------
		LEFT JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON	TD.USERDEFINEDREFERENCE_1 = TRIM(PS.SCHEDULEYEAR)+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','') 
													--AND TD.USERDEFINEDDATE_1 IS NOT NULL 
		LEFT JOIN IMTRANSACTIONHEADER TH (NOLOCK) ON	TH.ROWID = TD.R_TRANSACTIONHEADER 
													--AND TH.REFERENCE IN ('02','07','25','26','60','61')
		--LEFT JOIN IMTRANSACTIONHEADER TH (NOLOCK) ON TH.USERDEFINEDREFERENCE_1 = TRIM(PS.SCHEDULEYEAR)+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','')
		--LEFT JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
		LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
		LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
		LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT 
		LEFT JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = TD.ROWID 
		LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION 
		WHERE (TH.REFERENCE IS NULL OR TH.REFERENCE IN ('02','07','25','26','60','61'))

	UNION ALL 

	-------------------------- 
	-- ePLANT DATA SECTION  -- 
	-- WILL GO AWAY AUG 2021--<---THERE ARE SY2022 RECORDS IN HERE SO IT MIGHT BE AWHILE BEFORE THIS REALLY GOES AWAY 
	-------------------------- 
	SELECT 
		ITM.RECORDTYPE,
		CO.COMPANYID,
		CO.NAME AS COMPANYNAME,
		TRIM(WH.IDENTITYID) AS WAREHOUSEID,
		TRIM(WH.NAME) AS WAREHOUSENAME,
		IIF(PSI.REFERENCE_1 IS NULL, IIF(PS.PSITEMNUMBER IS NULL, '(ITEM NOT SPECIFIED)', '(VARIETY/ITEM NOT SETUP)'), NULL) AS EXCEPTIONTEXT,
		IT.SALEYEAR,
		PS.SCHEDULEYEAR,
		TRIM(REPLACE(PS.PLANTINGSCHEDULELINE,',','')) AS PSID,
		TRIM(PS.PSITEMNUMBER) AS PSITEMNUMBER,
		PSI.REFERENCE_1 AS PSCOMMONNAME,
		PSP.PRODUCTCATEGORYCODE AS PSPLANTGROUP,
		PSI.REFERENCE_5 AS PSSORTNAMEVARIETY,
		PSC.PRINTEDCONTAINERCODE AS PSPRINTEDCONTAINERCODE,
		TRIM(ITM.ITEMCODE) AS ITEMCODE,
		'ePLANT' AS LOTCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
		'[SOURCE???]' AS BEDSIZE,
		ITM.USERDEFINEDCODE_7 AS EXPOSURE,
		ITM.REFERENCE_1 AS COMMONNAME,
		ITM.REFERENCE_5 AS SORTNAMEVARIETY,
		TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
		PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
		ITM.USERDEFINEDCODE_1 AS GENUSCODE,
		GEN.DESCRIPTION_1 AS GENUSNAME,
		'ePLANT' AS TRANSCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
		IT.TRANSACTIONREASONCODE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
		NULL AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
		IT.PLANTINGSCHEDULELINE,
		IT.PLANTINGTEXT,
		PS.PLANTINGBLOCKNOTES,
		TRIM(PS.SOURCE) AS PSSOURCE,
		NULL AS SOURCE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
		PS.UDC_A, 
		ISNULL(PS.UDC_B,' ') AS UDC_B,
		IT.TOLOCATION AS LOCATIONCODE, 
		IT.INSERTUSER,
		FORMAT(CONVERT(DATE,IT.ACTUALPLANTEDDATE),'yyyy/MM/dd') AS ACTUALPLANTEDDATE,
		IT.ADJUSTMENTQUANTITY AS ACTUALPLANTEDQTY, 
		IT.TRANSACTIONREASONCODE AS TESTDATA, 
		(	SELECT SUM(ISNULL(IT2.ADJUSTMENTQUANTITY,0)) FROM GNC_ITEM_TRANSACTION_ARCHIVE IT2 (NOLOCK)
			WHERE IT2.DIVISIONNUMBER = IT.DIVISIONNUMBER
			AND IT2.PLANTINGSCHEDULELINE = IT.PLANTINGSCHEDULELINE
			AND IT2.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
			AND IT2.INSERTDATE IS NOT NULL
			) AS TOTALPLANTEDQTY,
		TRIM(CONVERT(CHAR,PS.TARGETPLANTINGDATE,111)) AS TARGETPLANTINGDATE,
		PS.TARGETPLANTINGQTY,
		DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
		DBO.FN_LISTPRICE(PSI.ROWID,NULL,NULL) AS TARGETPRICE

	FROM GNC_PLANTINGSCHEDULE PS (NOLOCK) 
		LEFT JOIN IDMASTER PSW (NOLOCK) ON PSW.IDENTITYID = PS.DIVISIONNUMBER 
		LEFT JOIN IMITEM PSI (NOLOCK) ON PSI.ITEMCODE = '00'+PS.PSITEMNUMBER AND PSI.R_WAREHOUSE = PSW.ROWID AND PSI.STATUS = 'A' 
		LEFT JOIN IMPRODUCTCATEGORY PSP (NOLOCK) ON PSP.ROWID = PSI.R_PRODUCTCATEGORY 
		LEFT JOIN IMCONTAINER PSC (NOLOCK) ON PSC.ROWID = PSI.R_CONTAINERCODE 
		---------------------------------------------------------------------
		LEFT JOIN GNC_ITEM_TRANSACTION_ARCHIVE IT (NOLOCK) ON	IT.PLANTINGSCHEDULELINE = TRIM(PS.SCHEDULEYEAR)+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','') 
														--AND IT.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = TRIM(STR(IT.DIVISIONNUMBER))
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IT.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID
		LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
		LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE (IT.TRANSACTIONREASONCODE IS NULL OR IT.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61'))
	) U
WHERE TARGETPLANTINGQTY > 0 
AND TARGETPLANTINGDATE IS NOT NULL 
*/




/* OLD CODE BEFORE TOTALLY REFACTORING EVERYTHING...
-------------------------- 
-- INSIGHT DATA SECTION -- 
-------------------------- 
SELECT 
ITM.RECORDTYPE, 
CO.COMPANYID, 
CO.NAME AS COMPANYNAME, 
TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
TRIM(WH.NAME) AS WAREHOUSENAME, 
IIF(PSI.REFERENCE_1 IS NULL, IIF(PS.PSITEMNUMBER IS NULL, '(ITEM NOT SPECIFIED)', '(VARIETY/ITEM NOT SETUP)'), NULL) AS EXCEPTIONTEXT, 
TH.FISCALYEAR AS SALEYEAR, 
PS.SCHEDULEYEAR, 
TRIM(REPLACE(PS.PLANTINGSCHEDULELINE,',','')) AS PSID, 
TRIM(PS.PSITEMNUMBER) AS PSITEMNUMBER, 
PSI.REFERENCE_1 AS PSCOMMONNAME, 
PSP.PRODUCTCATEGORYCODE AS PSPLANTGROUP, 
PSI.REFERENCE_5 AS PSSORTNAMEVARIETY, 
PSC.PRINTEDCONTAINERCODE AS PSPRINTEDCONTAINERCODE, 
TRIM(ITM.ITEMCODE) AS ITEMCODE, 
TRIM(LOT.LOTCODE) AS LOTCODE, 
'[SOURCE???]' AS BEDSIZE, 
ITM.USERDEFINEDCODE_7 AS EXPOSURE, 
ITM.REFERENCE_1 AS COMMONNAME, 
ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
GEN.DESCRIPTION_1 AS GENUSNAME, 
TD.USERDEFINEDCODE_1 AS TRANSCODE, 
TH.REFERENCE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
TD.USERDEFINEDCODE_1 AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
TD.USERDEFINEDREFERENCE_1 AS PLANTINGSCHEDULELINE, 
TD.USERDEFINEDREFERENCE_2 AS PLANTINGTEXT, 
PS.PLANTINGBLOCKNOTES, 
TRIM(PS.SOURCE) AS PSSOURCE, 
TRIM(TD.USERDEFINEDCODE_2) AS SOURCE, 
PS.UDC_A, 
ISNULL(PS.UDC_B,' ') AS UDC_B, 
LOC.LOCATIONCODE,	--QUESTIONING THIS 
TH.CREATIONUSERID AS INSERTUSER, 
TRIM(CONVERT(CHAR,TD.USERDEFINEDDATE_1,111)) AS ACTUALPLANTEDDATE, 
TD.QUANTITY AS ACTUALPLANTEDQTY, 
(	SELECT SUM(TD2.QUANTITY) FROM IMTRANSACTIONHEADER TH2 (NOLOCK) 
	JOIN IMTRANSACTIONDETAIL TD2 (NOLOCK) ON TD2.R_TRANSACTIONHEADER = TH2.ROWID 
	JOIN IDMASTER WH2 (NOLOCK) ON WH2.ROWID = TD2.R_WAREHOUSE 
	WHERE WH2.IDENTITYID = WH.IDENTITYID 
	AND TD2.USERDEFINEDREFERENCE_1 = TD.USERDEFINEDREFERENCE_1 
	AND TH2.REFERENCE IN ('02','07','25','26','60','61') 
	AND TD2.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS PLANTING DATE
	) AS TOTALPLANTEDQTY, 
TRIM(CONVERT(CHAR,PS.TARGETPLANTINGDATE,111)) AS TARGETPLANTINGDATE, 
PS.TARGETPLANTINGQTY, 
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
DBO.FN_LISTPRICE(PSI.ROWID,NULL,NULL) AS TARGETPRICE 

FROM IMTRANSACTIONHEADER TH (NOLOCK) 
JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT 

JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_TRANSACTIONDETAIL = TD.ROWID 
JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = TL.R_LOCATION 

JOIN GNC_PLANTINGSCHEDULE PS (NOLOCK) ON PS.DIVISIONNUMBER = WH.IDENTITYID AND TRIM(PS.SCHEDULEYEAR)+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','') = TD.USERDEFINEDREFERENCE_1 
LEFT JOIN IMITEM PSI (NOLOCK) ON PSI.ITEMCODE = '00'+PS.PSITEMNUMBER AND PSI.R_WAREHOUSE = WH.ROWID AND PSI.STATUS = 'A' 
LEFT JOIN IMPRODUCTCATEGORY PSP (NOLOCK) ON PSP.ROWID = PSI.R_PRODUCTCATEGORY 
LEFT JOIN IMCONTAINER PSC (NOLOCK) ON PSC.ROWID = PSI.R_CONTAINERCODE 

WHERE TH.REFERENCE IN ('02','07','25','26','60','61') 
AND PS.TARGETPLANTINGQTY > 0 
AND PS.TARGETPLANTINGDATE IS NOT NULL 
--AND TD.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS DEFINED AS PLANTING DATE (IS THIS ELIMINATING NON-STARTED ITEMS THAT HARRISON COOK WAS COMPLAINING ABOUT?) 

UNION ALL 

-------------------------- 
-- ePLANT DATA SECTION  -- 
-- WILL GO AWAY AUG 2021--<---THERE ARE SY2022 RECORDS IN HERE SO IT MIGHT BE AWHILE BEFORE THIS REALLY GOES AWAY 
-------------------------- 
SELECT 
ITM.RECORDTYPE,
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
TRIM(WH.IDENTITYID) AS WAREHOUSEID,
TRIM(WH.NAME) AS WAREHOUSENAME,
IIF(PSI.REFERENCE_1 IS NULL, IIF(PS.PSITEMNUMBER IS NULL, '(ITEM NOT SPECIFIED)', '(VARIETY/ITEM NOT SETUP)'), NULL) AS EXCEPTIONTEXT,
IT.SALEYEAR,
PS.SCHEDULEYEAR,
TRIM(REPLACE(PS.PLANTINGSCHEDULELINE,',','')) AS PSID,
TRIM(PS.PSITEMNUMBER) AS PSITEMNUMBER,
PSI.REFERENCE_1 AS PSCOMMONNAME,
PSP.PRODUCTCATEGORYCODE AS PSPLANTGROUP,
PSI.REFERENCE_5 AS PSSORTNAMEVARIETY,
PSC.PRINTEDCONTAINERCODE AS PSPRINTEDCONTAINERCODE,
TRIM(ITM.ITEMCODE) AS ITEMCODE,
'ePLANT' AS LOTCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
'[SOURCE???]' AS BEDSIZE,
ITM.USERDEFINEDCODE_7 AS EXPOSURE,
ITM.REFERENCE_1 AS COMMONNAME,
ITM.REFERENCE_5 AS SORTNAMEVARIETY,
TRIM(CNT.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
ITM.USERDEFINEDCODE_1 AS GENUSCODE,
GEN.DESCRIPTION_1 AS GENUSNAME,
'ePLANT' AS TRANSCODE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
IT.TRANSACTIONREASONCODE AS TRANSACTIONREASONCODE_OLD, --OLD TRANSACTIONREASONCODE SOURCE
NULL AS TRANSACTIONREASONCODE, --USERS CHANGED THEIR MINDS ABOUT TRANSACTIONREASONCODE SOURCE.
IT.TRANSACTIONREASONCODE,
IT.PLANTINGSCHEDULELINE,
IT.PLANTINGTEXT,
PS.PLANTINGBLOCKNOTES,
TRIM(PS.SOURCE) AS PSSOURCE,
NULL AS SOURCE,	--NOT IN EPLANT SOURCE TABLE: GNC_ITEM_TRANSACTION
PS.UDC_A, 
ISNULL(PS.UDC_B,' ') AS UDC_B,
IT.TOLOCATION AS LOCATIONCODE, 
IT.INSERTUSER,
FORMAT(CONVERT(DATE,IT.ACTUALPLANTEDDATE),'yyyy/MM/dd') AS ACTUALPLANTEDDATE,
IT.ADJUSTMENTQUANTITY AS ACTUALPLANTEDQTY,
(	SELECT SUM(IT2.ADJUSTMENTQUANTITY) FROM GNC_ITEM_TRANSACTION_ARCHIVE IT2 (NOLOCK)
	WHERE IT2.DIVISIONNUMBER = IT.DIVISIONNUMBER
	AND IT2.PLANTINGSCHEDULELINE = IT.PLANTINGSCHEDULELINE
	AND IT2.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
	AND IT2.INSERTDATE IS NOT NULL
	) AS TOTALPLANTEDQTY,
TRIM(CONVERT(CHAR,PS.TARGETPLANTINGDATE,111)) AS TARGETPLANTINGDATE,
PS.TARGETPLANTINGQTY,
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
DBO.FN_LISTPRICE(PSI.ROWID,NULL,NULL) AS TARGETPRICE

FROM GNC_ITEM_TRANSACTION_ARCHIVE IT (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = TRIM(STR(IT.DIVISIONNUMBER))
--JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = IT.ITEMNUMBER AND ITM.R_WAREHOUSE = WH.ROWID
--JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
LEFT JOIN GNC_PLANTINGSCHEDULE PS (NOLOCK) ON PS.DIVISIONNUMBER = WH.IDENTITYID AND TRIM(STR(PS.SCHEDULEYEAR))+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','') = IT.PLANTINGSCHEDULELINE--TD.USERDEFINEDREFERENCE_1
LEFT JOIN IMITEM PSI (NOLOCK) ON PSI.ITEMCODE = '00'+PS.PSITEMNUMBER AND PSI.R_WAREHOUSE = WH.ROWID AND PSI.STATUS = 'A'
LEFT JOIN IMPRODUCTCATEGORY PSP (NOLOCK) ON PSP.ROWID = PSI.R_PRODUCTCATEGORY
LEFT JOIN IMCONTAINER PSC (NOLOCK) ON PSC.ROWID = PSI.R_CONTAINERCODE

WHERE IT.TRANSACTIONREASONCODE IN ('02','07','25','26','60','61')
AND PS.TARGETPLANTINGQTY > 0
AND PS.TARGETPLANTINGDATE IS NOT NULL
*/