/* RUNTIME: 3:44 
--BILLING_CUST_TYPE 
SELECT * 
FROM VW_RPT_BILLING_CUST_TYPE (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_BILLING_CUST_TYPE] 
AS 
SELECT 	IIF(NATIONALACCOUNT = 'Y', 'Major', IIF(NATIONALACCOUNT = 'N', 'Independent', 'Unknown')) AS ACCTTYPE, 
		U.*
FROM	(
		---------------------------------- 
		-- THIS IS THE DIVISIONAL DATASET -- 
		---------------------------------- 
		SELECT 
		'Y' AS ISDIVISIONAL, 
		NULL AS ISCONSOLIDATED, 
		D.ISCURRYEAR, 
		D.RECORDTYPE, 
		D.COMPANYID, 
		D.COMPANYNAME, 
		D.SALEYEAR, 
		D.PERIOD, 
		D.TRANSACTIONDATE, 
		D.REPORTGROUP, 
		D.WAREHOUSEID AS WAREHOUSEID, 
		--UNIFYING WAREHOUSENAME USING INSIGHT DATA: 
		(	SELECT TRIM(WH.NAME) 
			FROM IDMASTER WH (NOLOCK) 
			WHERE WH.IDENTITYID = D.WAREHOUSEID 
			) AS WAREHOUSENAME, 
		ISNULL(D.NATIONALACCOUNT,'N') AS NATIONALACCOUNT, 
		D.CUSTOMERTYPE, 
		D.CUSTOMERTYPEDESC, 
		D.CURRAMOUNT, 
		D.PREVAMOUNT 
		FROM VW_RPT_SQL_BILLING_CUST_TYPE D (NOLOCK) 
		WHERE D.TRANSACTIONDATE <= GETDATE() 

UNION ALL

		---------------------------------- 
		-- THIS IS THE CONSOLIDATED DATASET -- 
		---------------------------------- 
		SELECT 
		NULL AS ISDIVISIONAL, 
		'Y' AS ISCONSOLIDATED, 
		C.ISCURRYEAR, 
		C.RECORDTYPE, 
		C.COMPANYID, 
		C.COMPANYNAME, 
		C.SALEYEAR, 
		C.PERIOD, 
		C.TRANSACTIONDATE, 
		C.REPORTGROUP, 
		NULL AS WAREHOUSEID,	--CONSOLDIATED TOTALS:
		'Consolidated' AS WAREHOUSENAME,
		ISNULL(C.NATIONALACCOUNT,'N') AS NATIONALACCOUNT, 
		C.CUSTOMERTYPE, 
		C.CUSTOMERTYPEDESC, 
		C.CURRAMOUNT, 
		C.PREVAMOUNT 
		FROM VW_RPT_SQL_BILLING_CUST_TYPE C (NOLOCK) 
		WHERE C.TRANSACTIONDATE <= GETDATE() 
		) U