/* WOT: 2:15 (65,157 ROWS) 
--SQL_BILLING_GOALS 
SELECT * 
FROM VW_RPT_SQL_BILLING_GOALS (NOLOCK) 
WHERE COMPANYID = 'SB' 
AND ISCURRYEAR = 'Y' 
AND ISCURRPERIOD = 'Y'	-->RT= 2:17 (3,828 ROWS) RECORD SEASON RT= 7:57 (3,930 ROWS)
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_BILLING_GOALS] 
AS 
SELECT 
IIF(X.SALEYEAR = DBO.FN_DATE2YEAR(NULL),'Y', NULL) AS ISCURRYEAR, 
IIF(X.PERIOD = DBO.FN_DATE2PERIOD(NULL),'Y', NULL) AS ISCURRPERIOD, 
'R' AS RECORDTYPE, 
'SB' AS COMPANYID, 
X.SALEYEAR, 
X.PERIOD, 
-------------------------- 
X.TRANSACTIONDATE, 
S.REPORTNET, 
S.REPORTGROSS, 
S.REPORTGROUP, 
S.REPORTLINE, 
S.REPORTNETDESC, 
S.REPORTGROSSDESC, 
S.REPORTGROUPDESC, 
S.REPORTLINEDESC, 
X.WAREHOUSEID, 
ISNULL(X.NATIONALACCOUNT, 'N') AS NATIONALACCOUNT, 
X.SALESREPID, 
X.SALESREPNAME, 
X.CURRAMOUNT, 
IIF(X.WAREHOUSEID='10', X.CURRAMOUNT, 0) AS CURRAMOUNT10, 
IIF(X.WAREHOUSEID='20', X.CURRAMOUNT, 0) AS CURRAMOUNT20, 
IIF(X.WAREHOUSEID='40', X.CURRAMOUNT, 0) AS CURRAMOUNT40, 
IIF(X.WAREHOUSEID='60', X.CURRAMOUNT, 0) AS CURRAMOUNT60, 
X.GOALAMOUNT, 
IIF(X.WAREHOUSEID='10', X.GOALAMOUNT, 0) AS GOALAMOUNT10, 
IIF(X.WAREHOUSEID='20', X.GOALAMOUNT, 0) AS GOALAMOUNT20, 
IIF(X.WAREHOUSEID='40', X.GOALAMOUNT, 0) AS GOALAMOUNT40, 
IIF(X.WAREHOUSEID='60', X.GOALAMOUNT, 0) AS GOALAMOUNT60 
FROM	VW_RPT_SQL_STRUCTURE S (NOLOCK), 
		( 
		SELECT	DBO.FN_DATE2YEAR(CAST(CURRTRANSDATE AS DATE)) AS SALEYEAR, 
				PERIOD, 
				CAST(CURRTRANSDATE AS DATE) AS TRANSACTIONDATE, 
				REPORTGROUP, 
				REPORTLINE, 
				WAREHOUSEID, 
				TRIM(SALESREPID) AS SALESREPID, 
				TRIM(SALESREPNAME) AS SALESREPNAME, 
				NATIONALACCOUNT, 
				SUM (CURRAMOUNT) AS CURRAMOUNT, 
				SUM (GOALAMOUNT) AS GOALAMOUNT 
        FROM	( 
				--CURRENT YEAR DATA FROM INSIGHT: 
				SELECT	C.*, 
						C.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(C.AMOUNT,0) AS CURRAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS C (NOLOCK) 
				WHERE	C.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		C.AMOUNT <> 0 
				UNION ALL 
				--GOAL DATA FROM INSIGHT: 
				SELECT	G.*, 
						G.TRANSACTIONDATE AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(G.AMOUNT,0) AS GOALAMOUNT 
				FROM	VW_RPT_SQL_GOALS G (NOLOCK) 
				WHERE	G.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		G.AMOUNT <> 0 
				UNION ALL 
				--CURRENT YEAR DATA FROM ePLANT: 
				SELECT	EC.*, 
						EC.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(EC.AMOUNT,0) AS CURRAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_1 EC (NOLOCK) 
				WHERE	EC.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		EC.AMOUNT <> 0 
				) U 
		GROUP BY 
				U.SALEYEAR, 
				U.PERIOD, 
				CAST(CURRTRANSDATE AS DATE), 
				U.REPORTGROUP, 
				U.REPORTLINE, 
				U.WAREHOUSEID, 
				U.SALESREPID, 
				U.SALESREPNAME, 
				U.NATIONALACCOUNT 
		) X 
WHERE	S.REPORTLINE = X.REPORTLINE 
