/* RUNTIME- 1:56 
--73 Crop Value by Lot Report [NEW VERSION FOR STEVE COPPEDGE] 
-- 
--	SOLDCROP NOW CALCULATED AS (DEMANDROLLUP + [CURRENTYEAR]SHIPPEDBYCYCLE) 
--	SALEABLECROP NOW CALCULATED AS (SUPPLYROLLUP + [CURRENTYEAR]SHIPPEDBYCYCLE) 
--	SHIPPEDBYCYCLE IS FOR CURRENTYEAR SHIPMENTS ONLY SO 
--		PY CALCULATIONS ARE SIMPLY THE SUPPLYROLLUP QUANTITY. 
-- 

SELECT * 
FROM VW_RPT_CROP_VALUE_LOT (NOLOCK) 
WHERE X_SUPPLY + Y_SUPPLY + Z_SUPPLY + FSU_SALEABLE + FSU_SUPPLY_HS <> 0 
---------------------------------- 
--AND ITEMCODE = '001993.031.1' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_CROP_VALUE_LOT] 
AS 
SELECT	--WO-RUNTIME- 2:12 
	*, 
	--SHIPPEDBYCYCLE TOTALS
	(F1SHIPPED + F2SHIPPED + F3SHIPPED) AS FSHIPPED, 
	(S1SHIPPED + S2SHIPPED + S3SHIPPED) AS SSHIPPED, 
	(U1SHIPPED + U2SHIPPED + U3SHIPPED) AS USHIPPED, 

	--SALEABLECROP QUANTITIES = (SUPPLY + [CURRENTYEAR]SHIPPEDBYCYCLE) 
	(F1_SUPPLY + F1SHIPPED) AS F1_SALEABLE, 
	(F2_SUPPLY + F2SHIPPED) AS F2_SALEABLE, 
	(F3_SUPPLY + F3SHIPPED) AS F3_SALEABLE, 
	(S1_SUPPLY + S1SHIPPED) AS S1_SALEABLE, 
	(S2_SUPPLY + S2SHIPPED) AS S2_SALEABLE, 
	(S3_SUPPLY + S3SHIPPED) AS S3_SALEABLE, 
	(U1_SUPPLY + U1SHIPPED) AS U1_SALEABLE, 
	(U2_SUPPLY + U2SHIPPED) AS U2_SALEABLE, 
	(U3_SUPPLY + U3SHIPPED) AS U3_SALEABLE, 
	(	(F1_SUPPLY + F2_SUPPLY + F3_SUPPLY) + 
		(S1_SUPPLY + S2_SUPPLY + S3_SUPPLY) + 
		(U1_SUPPLY + U2_SUPPLY + U3_SUPPLY) +	--EXCLUDING U3 IS UP IN THE AIR STILL 
--		(U1_SUPPLY + U2_SUPPLY) +				--IF WE DECIDE TO EXCLUDE U3 USE THESE CALCULATIONS 
		(F1SHIPPED + F2SHIPPED + F3SHIPPED) + 
		(S1SHIPPED + S2SHIPPED + S3SHIPPED) + 
		(U1SHIPPED + U2SHIPPED + U3SHIPPED)		--EXCLUDING U3 IS UP IN THE AIR STILL 
--		(U1SHIPPED + U2SHIPPED)					--IF WE DECIDE TO EXCLUDE U3 USE THESE CALCULATIONS 
		) AS FSU_SALEABLE, 
	(	(X_SUPPLY + Y_SUPPLY + Z_SUPPLY) + 
		(F1_SUPPLY + F2_SUPPLY + F3_SUPPLY) + 
		(S1_SUPPLY + S2_SUPPLY + S3_SUPPLY) + 
		(U1_SUPPLY + U2_SUPPLY + U3_SUPPLY) + 
		(F1SHIPPED + F2SHIPPED + F3SHIPPED) + 
		(S1SHIPPED + S2SHIPPED + S3SHIPPED) + 
		(U1SHIPPED + U2SHIPPED + U3SHIPPED) 
		) AS GRAND_TOTAL, 

	--SALEABLECROP VALUES = LISTPRICE * (SUPPLY + [CURRENTYEAR]SHIPPEDBYCYCLE) 
	LISTPRICE * (F1_SUPPLY + F1SHIPPED) AS F1_SALEABLE_VALUE, 
	LISTPRICE * (F2_SUPPLY + F2SHIPPED) AS F2_SALEABLE_VALUE, 
	LISTPRICE * (F3_SUPPLY + F3SHIPPED) AS F3_SALEABLE_VALUE, 
	LISTPRICE * (S1_SUPPLY + S1SHIPPED) AS S1_SALEABLE_VALUE, 
	LISTPRICE * (S2_SUPPLY + S2SHIPPED) AS S2_SALEABLE_VALUE, 
	LISTPRICE * (S3_SUPPLY + S3SHIPPED) AS S3_SALEABLE_VALUE, 
	LISTPRICE * (U1_SUPPLY + U1SHIPPED) AS U1_SALEABLE_VALUE, 
	LISTPRICE * (U2_SUPPLY + U2SHIPPED) AS U2_SALEABLE_VALUE, 
	LISTPRICE * (U3_SUPPLY + U3SHIPPED) AS U3_SALEABLE_VALUE, 
	LISTPRICE * ( 
				(F1_SUPPLY + F2_SUPPLY + F3_SUPPLY) + 
				(S1_SUPPLY + S2_SUPPLY + S3_SUPPLY) + 
				(U1_SUPPLY + U2_SUPPLY + U3_SUPPLY) +	--EXCLUDING U3 IS UP IN THE AIR STILL 
--				(U1_SUPPLY + U2_SUPPLY) +				--IF WE DECIDE TO EXCLUDE U3 USE THESE CALCULATIONS 
				(F1SHIPPED + F2SHIPPED + F3SHIPPED) + 
				(S1SHIPPED + S2SHIPPED + S3SHIPPED) + 
				(U1SHIPPED + U2SHIPPED + U3SHIPPED)		--EXCLUDING U3 IS UP IN THE AIR STILL 
--				(U1SHIPPED + U2SHIPPED)					--IF WE DECIDE TO EXCLUDE U3 USE THESE CALCULATIONS 
				) AS FSU_SALEABLE_VALUE, 
	LISTPRICE * ( 
				(X_SUPPLY + Y_SUPPLY + Z_SUPPLY) + 
				(F1_SUPPLY + F2_SUPPLY + F3_SUPPLY) + 
				(S1_SUPPLY + S2_SUPPLY + S3_SUPPLY) + 
				(U1_SUPPLY + U2_SUPPLY + U3_SUPPLY) + 
				(F1SHIPPED + F2SHIPPED + F3SHIPPED) + 
				(S1SHIPPED + S2SHIPPED + S3SHIPPED) + 
				(U1SHIPPED + U2SHIPPED + U3SHIPPED) 
				) AS GRAND_TOTAL_VALUE 
FROM	( 

		SELECT	--WO-RUNTIME- 1:57 
			*, 
			--SHIPPEDBYCYCLE QUANTITIES FOR CURRENTYEAR ONLY: 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'F1%') AS F1SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'F2%') AS F2SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'F3%') AS F3SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'S1%') AS S1SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'S2%') AS S2SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'S3%') AS S3SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'U1%') AS U1SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'U2%') AS U2SHIPPED, 
			DBO.FN_SHIPPEDBYCYCLE(ITMROWID,CY,'U3%') AS U3SHIPPED, 
			--SUPPLY LOT QUANTITIES ON HOLD, SHOW FLAG ON REPORT IF NON-ZERO QUANTITIES EXIST. 
			(F1_SUPPLY_HS + F2_SUPPLY_HS + F3_SUPPLY_HS + S1_SUPPLY_HS + S2_SUPPLY_HS + S3_SUPPLY_HS + U1_SUPPLY_HS + U2_SUPPLY_HS + U3_SUPPLY_HS) AS FSU_SUPPLY_HS, 
			--SUPPLY VALUES = LISTPRICE * SUPPLY 
			LISTPRICE * X_SUPPLY AS X_SUPPLY_VALUE, 
			LISTPRICE * Y_SUPPLY AS Y_SUPPLY_VALUE, 
			LISTPRICE * Z_SUPPLY AS Z_SUPPLY_VALUE 
		FROM	(--SELECT DBO.FN_SALEYEAR(NULL)%100 AS CURR) YR, --ATTACH YR.CURR TO BE USED AS A FIELD INSIDE THIS VIEW 
				SELECT	--WO-RUNTIME- 1:13 
					DBO.FN_SALEYEAR(NULL)%100 AS CY, 
					ITM.ROWID AS ITMROWID, 
					---------------------- 
					CO.COMPANYID, 
					TRIM(CO.NAME) AS COMPANYNAME, 
					TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
					TRIM(WH.NAME) AS WAREHOUSENAME, 
					TRIM(ITM.SUBCLASSCODE) AS QUALITY, 
					LEFT(PC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE, 
					ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
					(	SELECT CNT.CONTAINERSORT 
						FROM IMCONTAINER CNT (NOLOCK) 
						WHERE CNT.ROWID = ITM.R_CONTAINERCODE 
						) AS CONTAINERSORT, 
					----------- 
					--LINEONE-- 
					----------- 
					TRIM(ITM.ITEMCODE) AS ITEMCODE, 
					ITM.REFERENCE_1 AS COMMONNAME, 
					DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE, 
					--SUPPLY QUANTITIES: 
					--{NULL} LOTYEAR FORCES SUPPLY TO CY+PY ROLLUP: 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'X%',NULL,NULL) AS X_SUPPLY,	--CULLS 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'Y%',NULL,NULL) AS Y_SUPPLY,	--SHIFT 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'Z%',NULL,NULL) AS Z_SUPPLY,	--PROP 
					--PREVIOUS YEAR SALEABLECROP QUANTITIES (NO SHIPPEDBYCYCLE QUANTITIES NEEDED): 
					--{NULL} LOTYEAR FORCES SUPPLY TO CY+PY ROLLUP: 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1%',NULL,NULL) AS F1_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F2%',NULL,NULL) AS F2_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F3%',NULL,NULL) AS F3_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1%',NULL,NULL) AS S1_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S2%',NULL,NULL) AS S2_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S3%',NULL,NULL) AS S3_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1%',NULL,NULL) AS U1_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2%',NULL,NULL) AS U2_SUPPLY, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3%',NULL,NULL) AS U3_SUPPLY, 
					----------- 
					--LINETWO-- 
					----------- 
					--SUPPLY LOT QUANTITIES ON HOLD, SHOW FLAG ON REPORT IF NON-ZERO QUANTITIES EXIST. 
					--{NULL} LOTYEAR FORCES SUPPLY_HS TO CY+PY ROLLUP: 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1%','H',NULL) AS F1_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F2%','H',NULL) AS F2_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F3%','H',NULL) AS F3_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1%','H',NULL) AS S1_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S2%','H',NULL) AS S2_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S3%','H',NULL) AS S3_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1%','H',NULL) AS U1_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2%','H',NULL) AS U2_SUPPLY_HS, 
					DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3%','H',NULL) AS U3_SUPPLY_HS 
				FROM 
					IMITEM ITM (NOLOCK) 
					JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
					JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY 
					JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID 
				WHERE ITM.RECORDTYPE = 'R' 
				AND WH.IDENTITYID IN ('10', '20', '40', '60') 
				) T 
		) X 
