/* GP_LABORGROUP_SHIPPING_6YEAR
--RT:3:50 @ 44,059
--GP LaborGrp Ship6Yr-Det EXCEL
--GP LaborGrp Ship6Yr-Sum EXCEL

--MODIFICATION:
					AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
					--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')


SELECT 
* 
FROM VW_RPT_GP_LABORGROUP_SHIPPING_6YEAR (NOLOCK)
--WHERE JOBCODE = '4301'
--MACRO-------------
WHERE WAREHOUSEID = '10' 
--AND LABORGROUP = 'Growing'
AND JOBCODE = '4301' 
ORDER BY COMPANYID, WAREHOUSEID, LABORGROUP, JOBCODE, DEPARTMENT, CHECKDATE--, ISYTD 
*/
--SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS THRUDATE, 		--THIS RETURNS THE MOST RECENT SATURDAY'S DATE. IMPORTANT FOR THIS REPORT!
--GETDATE() + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) - DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) AS DATE4PRIORYEAR. IMPORTANT CALCULATION FOR THIS REPORT!
--(SELECT BASE.VOLUME FROM IMCONTAINER BASE (NOLOCK) WHERE CONTAINERCODE = '030') IS WHERE I GET THE 615.99 FROM

CREATE OR ALTER VIEW [dbo].[VW_RPT_GP_LABORGROUP_SHIPPING_6YEAR] 
AS 
SELECT DBO.FN_DATE2YEAR(THRUDATE) AS THRUYEAR, DBO.FN_DATE2PERIOD(THRUDATE) AS THRUPERIOD, DBO.FN_DATE2WEEK(THRUDATE) AS THRUWEEK, *
FROM (
	SELECT 
		Y.COMPANYID, 
		Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		SUM(Y.Y1_52W_HOURS) AS Y1_52W_HOURS, 
		MAX(Y.Y1_52W_UNITS) AS Y1_52W_UNITS, 
		MAX(Y.Y1_52W_EQUIVUNITS) AS Y1_52W_EQUIVUNITS, 
		SUM(Y.Y2_52W_HOURS) AS Y2_52W_HOURS, 
		MAX(Y.Y2_52W_UNITS) AS Y2_52W_UNITS, 
		MAX(Y.Y2_52W_EQUIVUNITS) AS Y2_52W_EQUIVUNITS, 
		SUM(Y.Y3_52W_HOURS) AS Y3_52W_HOURS, 
		MAX(Y.Y3_52W_UNITS) AS Y3_52W_UNITS, 
		MAX(Y.Y3_52W_EQUIVUNITS) AS Y3_52W_EQUIVUNITS, 
		SUM(Y.Y4_52W_HOURS) AS Y4_52W_HOURS, 
		MAX(Y.Y4_52W_UNITS) AS Y4_52W_UNITS, 
		MAX(Y.Y4_52W_EQUIVUNITS) AS Y4_52W_EQUIVUNITS, 
		SUM(Y.Y5_52W_HOURS) AS Y5_52W_HOURS, 
		MAX(Y.Y5_52W_UNITS) AS Y5_52W_UNITS, 
		MAX(Y.Y5_52W_EQUIVUNITS) AS Y5_52W_EQUIVUNITS, 
		SUM(Y.Y6_52W_HOURS) AS Y6_52W_HOURS, 
		MAX(Y.Y6_52W_UNITS) AS Y6_52W_UNITS, 
		MAX(Y.Y6_52W_EQUIVUNITS) AS Y6_52W_EQUIVUNITS, 
		Y.PRTYPE, Y.PRCODE 
	FROM ( 
			SELECT 
				WH.COMPANYID, 
				WH.IDENTITYID AS WAREHOUSEID, 
				WH.NAME AS WAREHOUSENAME, 
				X.DEPRTMNT AS DEPARTMENT, 
				X.DEPTDESC AS DEPARTMENTDESC, 
				IIF(LEFT(X.JOBDESC, 7) = 'Project', 'Maintenance', LG.LABORGROUP) AS LABORGROUP, 
				IIF(LEFT(X.JOBDESC, 7) = 'Project', '57***', X.JOBTITLE) AS JOBCODE, 
				X.JOBDESC AS JOBCODEDESC, 
				GETDATE()-(DATEPART(DW,GETDATE())%7) AS THRUDATE, 
				--DATEPART(YEAR, DATEADD(MONTH,4,X.CHECKDATE)) AS FISCALYEAR, 
				X.CHECKDATE, 
				X.Y1_52W_HOURS, X.Y1_52W_UNITS, X.Y1_52W_EQUIVUNITS, 
				X.Y2_52W_HOURS, X.Y2_52W_UNITS, X.Y2_52W_EQUIVUNITS, 
				X.Y3_52W_HOURS, X.Y3_52W_UNITS, X.Y3_52W_EQUIVUNITS, 
				X.Y4_52W_HOURS, X.Y4_52W_UNITS, X.Y4_52W_EQUIVUNITS, 
				X.Y5_52W_HOURS, X.Y5_52W_UNITS, X.Y5_52W_EQUIVUNITS, 
				X.Y6_52W_HOURS, X.Y6_52W_UNITS, X.Y6_52W_EQUIVUNITS, 
				X.PYRLRTYP AS PRTYPE, 
				X.PAYROLCD AS PRCODE 
			FROM ( 
					--CURRENT 52WEEK TOTALS		RT:426,373 @ 3:35
					SELECT 
						YR1.CHEKDATE AS CHECKDATE, 
						YR1.UNTSTOPY AS Y1_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -(7*52)					--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS Y1_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -(7*52)					--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days YR1 (NOLOCK) 
					--GET 52 WEEK'S DATA
					WHERE CHEKDATE >= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -(7*52)					--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND YR1.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR2.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						YR2.UNTSTOPY AS Y2_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y2_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days YR2 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR2.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR3.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						YR3.UNTSTOPY AS Y3_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y3_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEAR2
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR3 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-2) -	--PLUS START-OF-PREVIOUS2YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR3.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR4.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						YR4.UNTSTOPY AS Y4_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y4_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR4 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR4.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR5.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						YR5.UNTSTOPY AS Y5_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y5_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR5 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR5.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR6.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						YR6.UNTSTOPY AS Y6_52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y6_52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR6 (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR6.UNTSTOPY != 0
-----------------------------------------------------------------------------------------------------------------------------------------------------
--ePLANT HISTORICAL DATA SECTION:
-----------------------------------------------------------------------------------------------------------------------------------------------------

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR4H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 /*YR4H.UNTSTOPY*/ AS Y4_52W_HOURS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y4_52W_UNITS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR4H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-3) -	--PLUS START-OF-PREVIOUS3YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR4H.UNTSTOPY != 0

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR5H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 /*YR5H.UNTSTOPY*/ AS Y5_52W_HOURS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y5_52W_UNITS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y5_52W_EQUIVUNITS, 
						0 AS Y6_52W_HOURS, 
						0 AS Y6_52W_UNITS, 
						0 AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR5H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-4) -	--PLUS START-OF-PREVIOUS4YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR5H.UNTSTOPY != 0

					UNION ALL 

					--ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT ePLANT 
					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(YR6H.CHEKDATE) AS CHECKDATE, 
						0 AS Y1_52W_HOURS, 
						0 AS Y1_52W_UNITS, 
						0 AS Y1_52W_EQUIVUNITS, 
						0 AS Y2_52W_HOURS, 
						0 AS Y2_52W_UNITS, 
						0 AS Y2_52W_EQUIVUNITS, 
						0 AS Y3_52W_HOURS, 
						0 AS Y3_52W_UNITS, 
						0 AS Y3_52W_EQUIVUNITS, 
						0 AS Y4_52W_HOURS, 
						0 AS Y4_52W_UNITS, 
						0 AS Y4_52W_EQUIVUNITS, 
						0 AS Y5_52W_HOURS, 
						0 AS Y5_52W_UNITS, 
						0 AS Y5_52W_EQUIVUNITS, 
						0 /*YR6H.UNTSTOPY*/ AS Y6_52W_HOURS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y6_52W_UNITS, 
						(	SELECT SUM(ISNULL(HIST.SHIPPEDQTY,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM GNC_SHIPPED_HISTORY_ARCHIVE HIST (NOLOCK) 
							JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = HIST.WAREHOUSEID
							JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = HIST.ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
							WHERE CNT.SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							AND WH.IDENTITYID = WAREHOUSE 
							AND HIST.TRANSACTIONDATE >= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															) -(7*52)											--RANGE: 52 WEEKS
							AND HIST.TRANSACTIONDATE <= (	GETDATE() -											--TODAY
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
															DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
															(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
															)
							) AS Y6_52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor YR6H (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-5) -	--PLUS START-OF-PREVIOUS5YEARS
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND YR6H.UNTSTOPY != 0

			-----------------------------------------
			) X 
			JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = WAREHOUSE 
			LEFT 	--UNCOMMENT THIS LINE TO INCLUDE 'Projects' LABORGRP IN THE REPORT.
			JOIN GNC_LABORGROUPSBYGP_JOBCODE LG (NOLOCK) ON LG.JOBCODE = X.JOBTITLE
			WHERE ISNULL(LG.BENCHMARK,'SHIPPING') = 'SHIPPING'
	) Y
	WHERE Y.LABORGROUP IS NOT NULL
	GROUP BY 
		Y.COMPANYID, Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		Y.PRTYPE, Y.PRCODE 
) Z
