/*	Not being used? Using VW_HIREDTRUCKPAYMENTVIEW right now instead
--65 HIRED TRUCK PAYMENTS
SELECT
*
FROM VW_RPT_HIRED_TRUCK_PAYMENTS (NOLOCK)
WHERE VW_RPT_HIRED_TRUCK_PAYMENTS.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_HIRED_TRUCK_PAYMENTS]
AS
SELECT
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
WH.IDENTITYID AS WAREHOUSE,
WH.NAME AS WAREHOUSENAME,
HDR.RECORDTYPE,
HDR.TRIPNO,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) WHERE SP.R_SOURCEID = HDR.ROWID) AS AMOUNT,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'DROP-PAY' WHERE SP.R_SOURCEID = HDR.ROWID) AS DROPPAY,
(SELECT MAX(PART.IDENTITYID) FROM IDMASTER PART (NOLOCK) JOIN SPOPENITEMS SP (NOLOCK) ON SP.R_IDENTITY = PART.ROWID WHERE SP.R_SOURCEID = HDR.ROWID) AS DRIVERID,
(SELECT SUM(OBJ.WEIGHTORDERED) FROM FMDISPATCHOBJECT OBJ (NOLOCK) JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID WHERE  DET.R_TRIPHEADER = HDR.ROWID) AS TOTALWEIGHTORDERED,
(SELECT SUM(OBJ.CUBESORDERED) FROM FMDISPATCHOBJECT OBJ (NOLOCK) JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID WHERE  DET.R_TRIPHEADER = HDR.ROWID) AS TOTALCUBESORDERED,
OBJ.WEIGHTORDERED,
OBJ.CUBESORDERED,
DET.DELSTOPNO,
DEST.NAME AS DESTINATION,
DESTADD.ADDRESS_1,
DESTADD.ADDRESS_2,
DESTADD.CITY,
DESTADD.STATE,
DESTADD.ZIP,
DESTADD.COUNTRY,
DESTADD.TELEPHONE_1,
OBJ.TRACKINGNUMBER,
HDR.PLANSTART,
PART.IDENTITYID,
CARR.NAME AS DRIVERNAME,
HDR.EQUIPMENT,
ISNULL(HDR.MILESLOADED,0)+ISNULL(HDR.MILESUNLOADED,0) AS MILES
FROM FMTRIPHEADER HDR (NOLOCK)
LEFT OUTER JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_TRIPHEADER = HDR.ROWID
LEFT OUTER JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DET.R_FMDISPATCHOBJECT
LEFT OUTER JOIN IDMASTER DEST (NOLOCK) ON DEST.ROWID = DET.R_DESTINATIONID 
LEFT OUTER JOIN IDTYPESLINKS IDTL (NOLOCK) ON IDTL.R_IDENTITY = DEST.ROWID AND IDTL.IDTYPE = '02'
LEFT OUTER JOIN IDADDRESS DESTADD (NOLOCK) ON DESTADD.ROWID = IDTL.R_ADDRESS
LEFT OUTER JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = HDR.R_ORIGIN
LEFT OUTER JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
LEFT OUTER JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OBJ.R_SHIPPER
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
--WHERE HDR.RECORDTYPE <> 'P'
