/*  
--VW_RPT_GNC_PLANTINGSCHEDULE 
SELECT * 
FROM VW_RPT_GNC_PLANTINGSCHEDULE (NOLOCK) 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_GNC_PLANTINGSCHEDULE] 
AS 
--IMPORT DATA 
	SELECT 
		WH.COMPANYID, 
		'R' AS RECORDTYPE, 
		WH.IDENTITYID AS WAREHOUSEID, 
		TRIM(STR(PS.SCHEDULEYEAR))+'.'+REPLACE(PS.PLANTINGSCHEDULELINE,',','') AS PLANTINGSCHEDULELINE, 
		---------------------------------
		IIF(ITM.REFERENCE_1 IS NULL, IIF(PS.PSITEMNUMBER IS NULL, '(ITEM NOT SPECIFIED)', '(VARIETY/ITEM NOT SETUP)'), NULL) AS EXCEPTIONTEXT, 
		PS.SCHEDULEYEAR, 
		TRIM(REPLACE(PS.PLANTINGSCHEDULELINE,',','')) AS PSID, 
		TRIM(PS.PSITEMNUMBER) AS PSITEMNUMBER, 
		ITM.REFERENCE_1 AS PSCOMMONNAME, 
		PGC.PRODUCTCATEGORYCODE AS PSPLANTGROUP, 
		ITM.REFERENCE_5 AS PSSORTNAMEVARIETY, 
		CNT.PRINTEDCONTAINERCODE AS PSPRINTEDCONTAINERCODE, 
		PS.PLANTINGBLOCKNOTES, 
		TRIM(PS.SOURCE) AS PSSOURCE, 
		PS.UDC_A, 
		ISNULL(PS.UDC_B,' ') AS UDC_B, 
		PS.TARGETPLANTINGDATE, 
		--TRIM(CONVERT(CHAR,PS.TARGETPLANTINGDATE,111)) AS TARGETPLANTINGDATE, 
		PS.TARGETPLANTINGQTY, 
		DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS TARGETPRICE 

FROM GNC_PLANTINGSCHEDULE PS (NOLOCK) 
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = PS.DIVISIONNUMBER 
	LEFT JOIN IMITEM ITM (NOLOCK) ON	ITM.ITEMCODE = RIGHT('00'+LEFT(TRIM(PS.PSITEMNUMBER),12),12) --They can't be consistent so I have to manage both now.
	--LEFT JOIN IMITEM ITM (NOLOCK) ON	ITM.ITEMCODE = PS.PSITEMNUMBER --users started adding 00 then complained about the report.
									AND ITM.R_WAREHOUSE = WH.ROWID 
									AND ITM.STATUS = 'A' 
									AND ITM.RECORDTYPE = 'R' 
	LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
	LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
WHERE PS.TARGETPLANTINGQTY > 0 
AND PS.TARGETPLANTINGDATE IS NOT NULL 

