--147 WORKING MANIFEST
--148 WORKING MANIFEST WITH ETA
/*
SELECT *
FROM VW_RPT_WORKING_MANIFEST (NOLOCK)
WHERE RECORDTYPE <> 'P' AND ordernumber = '40-62975'--TRIPNO = 'T14066'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_WORKING_MANIFEST]
AS
SELECT 
	HDR.RECORDTYPE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	S.IDENTITYID AS SHIPPERCODE,
	S.NAME AS SHIPPERNAME,
	TRIPNO,
	PLANSTART,
	ACTUALSTART,
	DO.TRACKINGNUMBER,
	HDR.STATUS,
	HDR.EQUIPMENT AS TRUCKTYPE, 
	M.IDENTITYID AS CARRIERCODE,
	M.NAME AS CARRIERNAME,
	HDR.USERDEFINEDCODE_2 AS DOCKNUMBER,
	HDR.MILESUNLOADED, 
	HDR.MILESLOADED ,
	HDR.MILESUNLOADED + HDR.MILESLOADED  AS TOTALTRIPMILES,
	TR.DESCRIPTION AS GNCTRAILERNO,--REPLACES: TR.EQUIPMENTID AS GNCTRAILERNO,
	TK.DESCRIPTION  AS GNCTRUCKNO,
	HDR.TRUCKREFERENCE AS CONTRACTTRUCKNO,
	HDR.TRAILERREFERENCE AS CONTRACTTRAILERNO,
	DR.NAME AS GNCDRIVER,--REPLACES: DR.IDENTITYID AS GNCDRIVER,
	HDR.DRIVERREFERENCE, 
	HDR.USERDEFINEDREFERENCE_1 AS CONTRACTDRIVER,
	HDR.USERDEFINEDREFERENCE_2 AS DRIVERPHONE,
	(	SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RATE/MILE') AS TOTALLOADEDMILES,
	ISNULL((SELECT TOP 1 ISNULL(SPOPENITEMS.RATE,0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RATE/MILE'),0) AS RATEPERMILE,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RATE/MILE') AS EXTRATE,
	(	SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RTMILES') AS TOTALRTMILES,
	ISNULL((SELECT TOP 1 ISNULL(SPOPENITEMS.RATE,0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RTMILES'),0) AS RTNRATEPERMILE,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='RTMILES') AS EXTRTMILES,
	(	SELECT ISNULL(SUM(ISNULL(BASIS,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='FSMILES') AS FSMILES,
	(	SELECT TOP 1 ISNULL(SPOPENITEMS.RATE,0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='FSMILES') AS FSMILESRATE,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='FSMILES') AS EXTFSMILES,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='DROPPAY') AS STOPPAY,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='DHFEE') AS DHFEE,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID AND FC.CHARGECODE ='ADJUST') AS COSTADJUSTMENT,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
		LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
		WHERE SPOPENITEMS.R_SOURCEID = HDR.ROWID ) AS FREIGHTEXPENSE,
	(	SELECT ISNULL(SUM(ISNULL(AMOUNT,0) ),0) FROM SPOPENITEMS (NOLOCK)
		WHERE SPOPENITEMS.TRANSACTIONNUMBER = HDR.TRIPNO 
		AND SPOPENITEMS.STATUS='Z' AND SPOPENITEMS.TRANSACTIONTYPE IN ('A','P')) AS ADVANCE,
	CONVERT(VARCHAR(255),HDR.COMMENT) AS SPECIALINSTRUCTIONS,
	DTL.DELSTOPNO AS STOPNUMBER, 
	--STOPNOTES CHANGING FROM DTL.COMMENT TO DTL.UDR4 + UDR5:
	--NULLIF(ISNULL(TRIM(REPLACE(SUBSTRING(DTL.COMMENT,1,50),CHAR(13)+CHAR(10),'')),'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,'  ') AS STOPNOTES, 
	NULLIF(ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,' ') AS STOPNOTES, 
	IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
(	SELECT TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') )
	FROM IDSYNONYMS ALTSHIP (NOLOCK) 
	WHERE ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO
	) AS ALTSHIPTELEPHONE_1, 
	CV.CONSIGNEEIDENTITYID AS CONSIGNEECODE, 
	CV.CONSIGNEENAME AS CONSIGNEENAME,
	CV.CONSIGNEEADDRESS_1 AS CONSINGEEADDRESS1,
	CV.CONSIGNEEADDRESS_2 AS CONSINGEEADDRESS2,
	CV.CONSIGNEECITY AS CITY,
	CV.CONSIGNEESTATE AS STATE,
	CV.CONSIGNEEZIP AS ZIP, 
	CV.CONSIGNEETELEPHONE_1 AS PHONE,
	ISNULL(DO.WEIGHTORDERED,0) AS WEIGHT,
	ISNULL(DO.CUBESORDERED,0) AS VOLUME, 
	OH.TRANSACTIONNUMBER AS ORDERNUMBER,
	OH.PURCHASEORDERNUMBER AS PONUMBER,
	DTL.SCHEDULEDDELARRIVALDT AS ETADATE,
	(	SELECT TOP 1 C.IDENTITYID  FROM IDMASTER (NOLOCK)
		LEFT JOIN IDRELATIONSHIPLINKS RL (NOLOCK) ON RL.R_IDMASTER  = OH.R_SHIPPER AND RL.IDMASTERTYPE ='02' AND RL.IDMEMBERTYPE ='22'
		LEFT JOIN IDMASTER C (NOLOCK) ON C.ROWID = RL.R_IDMEMBER  
		LEFT JOIN IDCONTACTS CON (NOLOCK) ON CON.R_IDENTITY = C.ROWID AND CON.USERDEFINEDCODE_1 ='Shipping 1') AS SHIPCONTACT,
	(	SELECT TOP 1 LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,LEN(ACONT.TELEPHONE_1)-LEN(LEFT(ACONT.TELEPHONE_1,8)))  FROM IDMASTER (NOLOCK)
		LEFT JOIN IDRELATIONSHIPLINKS RL (NOLOCK) ON RL.R_IDMASTER = OH.R_SHIPPER AND RL.IDMASTERTYPE ='02' AND RL.IDMEMBERTYPE ='22'
		LEFT JOIN IDMASTER C (NOLOCK) ON C.ROWID = RL.R_IDMEMBER
		LEFT JOIN IDCONTACTS CON (NOLOCK) ON CON.R_IDENTITY = C.ROWID AND CON.USERDEFINEDCODE_1 ='Shipping 1'
		LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = C.ROWID) AS SHIPCONTACTPHONE, 
	(	SELECT TOP 1 ACONT.EMAILADDRESS_1 FROM IDMASTER (NOLOCK)
		LEFT JOIN IDRELATIONSHIPLINKS RL (NOLOCK) ON RL.R_IDMASTER = OH.R_SHIPPER AND RL.IDMASTERTYPE ='02' AND RL.IDMEMBERTYPE ='22'
		LEFT JOIN IDMASTER C (NOLOCK) ON C.ROWID = RL.R_IDMEMBER
		LEFT JOIN IDCONTACTS CON (NOLOCK) ON CON.R_IDENTITY = C.ROWID AND CON.USERDEFINEDCODE_1 ='Shipping 1'
		LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = C.ROWID) AS SHIPCONTACTEMAIL, 
	(	SELECT TOP 1 CON.USERDEFINEDCOMMENT  FROM IDMASTER (NOLOCK)
		LEFT JOIN IDRELATIONSHIPLINKS RL (NOLOCK) ON RL.R_IDMASTER = OH.R_SHIPPER AND RL.IDMASTERTYPE ='02' AND RL.IDMEMBERTYPE ='22'
		LEFT JOIN IDMASTER C (NOLOCK) ON C.ROWID = RL.R_IDMEMBER  
		LEFT JOIN IDCONTACTS CON (NOLOCK) ON CON.R_IDENTITY = C.ROWID AND CON.USERDEFINEDCODE_1 ='Shipping 1') AS SHIPCONTACTEMAILSTREAM

--,
--ISNULL(SO.RATE,0) AS RATE,ISNULL(SO.AMOUNT,0) AS AMOUNT,FC.DESCRIPTION

FROM FMTRIPHEADER HDR (NOLOCK)
LEFT JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER =HDR.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID =DTL.R_FMDISPATCHOBJECT 
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = DO.R_SOURCEID 
LEFT JOIN IDMASTER M (NOLOCK) ON M.ROWID = HDR.R_CARRIER
LEFT JOIN IDMASTER S (NOLOCK) ON S.ROWID = HDR.R_ORIGIN
LEFT JOIN IDMASTER DR (NOLOCK) ON DR.ROWID = HDR.R_DRIVER 
LEFT JOIN IDEQUIPMENT TR (NOLOCK) ON TR.ROWID=HDR.R_TRAILER
LEFT JOIN IDEQUIPMENT TK (NOLOCK) ON TK.ROWID=HDR.R_TRUCK
LEFT JOIN VW_IDCONSIGNEEVIEW CV (NOLOCK) ON CV.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID

WHERE HDR.RECORDTYPE <>'P'
