/* GP_LABORGROUP_SHIPPING_ANALYSIS
--RT:1:22 @ 13,451
--GP LaborGrp ShipAnal-Det EXCEL
--GP LaborGrp ShipAnal-Sum EXCEL

--MODIFICATION:
					AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
					--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')


SELECT 
* 
FROM VW_RPT_GP_LABORGROUP_SHIPPING_ANALYSIS (NOLOCK)
--WHERE JOBCODE = '4301'
--MACRO-------------
WHERE WAREHOUSEID = '10' 
--AND LABORGROUP = 'Growing'
AND JOBCODE = '4301' 
ORDER BY COMPANYID, WAREHOUSEID, LABORGROUP, JOBCODE, DEPARTMENT, CHECKDATE--, ISYTD 
*/
--SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS THRUDATE, 		--THIS RETURNS THE MOST RECENT SATURDAY'S DATE. IMPORTANT FOR THIS REPORT!
--GETDATE() + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) - DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) AS DATE4PRIORYEAR. IMPORTANT CALCULATION FOR THIS REPORT!
--(SELECT BASE.VOLUME FROM IMCONTAINER BASE (NOLOCK) WHERE CONTAINERCODE = '030') IS WHERE I GET THE 615.99 FROM

CREATE OR ALTER VIEW [dbo].[VW_RPT_GP_LABORGROUP_SHIPPING_ANALYSIS] 
AS 
SELECT DBO.FN_DATE2PERIOD(THRUDATE) AS THRUPERIOD, DBO.FN_DATE2WEEK(THRUDATE) AS THRUWEEK, *
FROM (
	SELECT 
		Y.COMPANYID, 
		Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		SUM(Y.CW_HOURS) AS CURR_WEEK_HOURS, 
		MAX(Y.CW_UNITS) AS CURR_WEEK_UNITS, 
		MAX(Y.CW_EQUIVUNITS) AS CURR_WEEK_EQUIVUNITS, 
		SUM(Y.PW_HOURS) AS PREV_WEEK_HOURS, 
		MAX(Y.PW_UNITS) AS PREV_WEEK_UNITS, 
		MAX(Y.PW_EQUIVUNITS) AS PREV_WEEK_EQUIVUNITS, 
		SUM(Y.C4W_HOURS) AS CURR_4WEEK_HOURS, 
		MAX(Y.C4W_UNITS) AS CURR_4WEEK_UNITS, 
		MAX(Y.C4W_EQUIVUNITS) AS CURR_4WEEK_EQUIVUNITS, 
		SUM(Y.P4W_HOURS) AS PREV_4WEEK_HOURS, 
		MAX(Y.P4W_UNITS) AS PREV_4WEEK_UNITS, 
		MAX(Y.P4W_EQUIVUNITS) AS PREV_4WEEK_EQUIVUNITS, 
		SUM(Y.CY_HOURS) AS CURR_YTD_HOURS, 
		MAX(Y.CY_UNITS) AS CURR_YTD_UNITS, 
		MAX(Y.CY_EQUIVUNITS) AS CURR_YTD_EQUIVUNITS, 
		SUM(Y.PY_HOURS) AS PREV_YTD_HOURS, 
		MAX(Y.PY_UNITS) AS PREV_YTD_UNITS, 
		MAX(Y.PY_EQUIVUNITS) AS PREV_YTD_EQUIVUNITS, 
		SUM(Y.C52W_HOURS) AS CURR_52W_HOURS, 
		MAX(Y.C52W_UNITS) AS CURR_52W_UNITS, 
		MAX(Y.C52W_EQUIVUNITS) AS CURR_52W_EQUIVUNITS, 
		SUM(Y.P52W_HOURS) AS PREV_52W_HOURS, 
		MAX(Y.P52W_UNITS) AS PREV_52W_UNITS, 
		MAX(Y.P52W_EQUIVUNITS) AS PREV_52W_EQUIVUNITS, 
		Y.PRTYPE, Y.PRCODE 
	FROM ( 
			SELECT 
				WH.COMPANYID, 
				WH.IDENTITYID AS WAREHOUSEID, 
				WH.NAME AS WAREHOUSENAME, 
				X.DEPRTMNT AS DEPARTMENT, 
				X.DEPTDESC AS DEPARTMENTDESC, 
				IIF(LEFT(X.JOBDESC, 7) = 'Project', 'Maintenance', LG.LABORGROUP) AS LABORGROUP, 
				IIF(LEFT(X.JOBDESC, 7) = 'Project', '57***', X.JOBTITLE) AS JOBCODE, 
				X.JOBDESC AS JOBCODEDESC, 
				GETDATE()-(DATEPART(DW,GETDATE())%7) AS THRUDATE, 
				--DATEPART(YEAR, DATEADD(MONTH,4,X.CHECKDATE)) AS FISCALYEAR, 
				X.CHECKDATE, 
				X.CW_HOURS, X.CW_UNITS, X.CW_EQUIVUNITS, 
				X.PW_HOURS, X.PW_UNITS, X.PW_EQUIVUNITS, 
				X.C4W_HOURS, X.C4W_UNITS, X.C4W_EQUIVUNITS, 
				X.P4W_HOURS, X.P4W_UNITS, X.P4W_EQUIVUNITS, 
				X.CY_HOURS, X.CY_UNITS, X.CY_EQUIVUNITS, 
				X.PY_HOURS, X.PY_UNITS, X.PY_EQUIVUNITS, 
				X.C52W_HOURS, X.C52W_UNITS, X.C52W_EQUIVUNITS, 
				X.P52W_HOURS, X.P52W_UNITS, X.P52W_EQUIVUNITS, 
				X.PYRLRTYP AS PRTYPE, 
				X.PAYROLCD AS PRCODE 
			FROM ( 
					--CURRENT WEEKLY TOTALS	RT:????? @ 1:08
					SELECT 
						CW.CHEKDATE AS CHECKDATE, 
						CW.UNTSTOPY AS CW_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												) -6						--RANGE: 1 WEEK
							AND OH.INVOICEDATE <= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												)
							) AS CW_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												) -6						--RANGE: 1 WEEK
							AND OH.INVOICEDATE <= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												)
							) AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].[PROD].[DBO].[v_GNC_ProjectReportByDeptWithContractLabor800days] CW (NOLOCK) 
					--GET 1 WEEK'S DATA
					WHERE CHEKDATE >= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -6						--RANGE: 1 WEEK
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND CW.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS WEEKLY TOTALS	RT:164K @ 1:23
					SELECT 
						DBO.FN_DATE4NEXTYEAR(PW.CHEKDATE) AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						PW.UNTSTOPY AS PW_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												) -6												--RANGE: 1 WEEK
							AND OH.INVOICEDATE <= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												)
							) AS PW_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												) -6												--RANGE: 1 WEEK
							AND OH.INVOICEDATE <= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												)
							) AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].[PROD].[DBO].[v_GNC_ProjectReportByDeptWithContractLabor800days] PW (NOLOCK) 
					--GET 1 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -6												--RANGE: 1 WEEK
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND PW.UNTSTOPY != 0

					UNION ALL 

		------------------------------------------------------
					--CURRENT 4WEEK TOTALS	RT:????? @ 1:08
					SELECT 
						C4W.CHEKDATE AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						C4W.UNTSTOPY AS C4W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												) -((7*4)-1)				--RANGE: 4 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												)
							) AS C4W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												) -((7*4)-1)				--RANGE: 4 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -				--TODAY
												(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
												)
							) AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].[PROD].[DBO].[v_GNC_ProjectReportByDeptWithContractLabor800days] C4W (NOLOCK) 
					--GET 4WEEK DATA
					WHERE CHEKDATE >= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -((7*4)-1)				--RANGE: 4 WEEKS
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND C4W.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 4WEEK TOTALS	RT:164K @ 1:23
					SELECT 
						DBO.FN_DATE4NEXTYEAR(P4W.CHEKDATE) AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						P4W.UNTSTOPY AS P4W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												) -((7*4)-1)										--RANGE: 4 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												)
							) AS P4W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												) -((7*4)-1)										--RANGE: 4 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -										--TODAY
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
												DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
												(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
												)
							) AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].[PROD].[DBO].[v_GNC_ProjectReportByDeptWithContractLabor800days] P4W (NOLOCK) 
					--GET 4WEEK DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -((7*4)-1)										--RANGE: 4 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND P4W.UNTSTOPY != 0

					UNION ALL 

		------------------------------------------------------
					--CURRENT YTD TOTALS	RT:261,942 @ 1:54
					SELECT 
						CY.CHEKDATE AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						CY.UNTSTOPY AS CY_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE()))		--START-OF-CURRENTYEAR
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS CY_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE()))		--START-OF-CURRENTYEAR
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days CY (NOLOCK) 
					--GET 1 YEAR'S DATA
					WHERE CHEKDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE()))		--START-OF-CURRENTYEAR
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND CY.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS YTD TOTALS	RT:328,862 @ 2:52
					SELECT 
						DBO.FN_DATE4NEXTYEAR(PY.CHEKDATE) AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						PY.UNTSTOPY AS PY_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1)		--START-OF-PREVIOUSYEAR
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS PY_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1)		--START-OF-PREVIOUSYEAR
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days PY (NOLOCK) 
					--GET 1 YEAR'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1)		--START-OF-PREVIOUSYEAR
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND PY.UNTSTOPY != 0

					UNION ALL 

					--CURRENT 52WEEK TOTALS		RT:426,373 @ 3:35
					SELECT 
						C52W.CHEKDATE AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						C52W.UNTSTOPY AS C52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -(7*52)					--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS C52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													) -(7*52)					--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -					--TODAY
													(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
													)
							) AS C52W_EQUIVUNITS, 
						0 AS P52W_HOURS, 
						0 AS P52W_UNITS, 
						0 AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days C52W (NOLOCK) 
					--GET 52 WEEK'S DATA
					WHERE CHEKDATE >= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										) -(7*52)					--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -					--TODAY
										(DATEPART(DW,GETDATE())%7)	--PREV SATURDAY
										)
					AND C52W.UNTSTOPY != 0

					UNION ALL 

					--PREVIOUS 52WEEK TOTALS	RT:493,293 @ 4:39
					SELECT 
						DBO.FN_DATE4NEXTYEAR(P52W.CHEKDATE) AS CHECKDATE, 
						0 AS CW_HOURS, 
						0 AS CW_UNITS, 
						0 AS CW_EQUIVUNITS, 
						0 AS PW_HOURS, 
						0 AS PW_UNITS, 
						0 AS PW_EQUIVUNITS, 
						0 AS C4W_HOURS, 
						0 AS C4W_UNITS, 
						0 AS C4W_EQUIVUNITS, 
						0 AS P4W_HOURS, 
						0 AS P4W_UNITS, 
						0 AS P4W_EQUIVUNITS, 
						0 AS CY_HOURS, 
						0 AS CY_UNITS, 
						0 AS CY_EQUIVUNITS, 
						0 AS PY_HOURS, 
						0 AS PY_UNITS, 
						0 AS PY_EQUIVUNITS, 
						0 AS C52W_HOURS, 
						0 AS C52W_UNITS, 
						0 AS C52W_EQUIVUNITS, 
						P52W.UNTSTOPY AS P52W_HOURS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS P52W_UNITS, 
						(	SELECT SUM(ISNULL(OD.QUANTITYSHIPPED,0)*(ISNULL(CNT.VOLUME,.01)/615.99))
							FROM OMTRANSACTIONHEADER OH (NOLOCK) 
							JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
							JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
							WHERE OH.RECORDTYPE='Z' AND OH.TRANSACTIONTYPE='I' 
							AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 
							AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART','LINER') --Add LINER Class this report only per DJ - 5/8/24 DT
							--AND SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
							AND WH.IDENTITYID = WAREHOUSE 
							AND OH.INVOICEDATE >= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													) -(7*52)											--RANGE: 52 WEEKS
							AND OH.INVOICEDATE <= (	GETDATE() -											--TODAY
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
													DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
													(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
													)
							) AS P52W_EQUIVUNITS, 
						* 
					FROM [GNCGPDB\GP2018].PROD.DBO.v_GNC_ProjectReportByDeptWithContractLabor800days P52W (NOLOCK) 
					--GET 52 WEEK'S DATA (FROM LASTYEAR'S EQUIVALENT CALENDAR)
					WHERE CHEKDATE >= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										) -(7*52)											--RANGE: 52 WEEKS
					AND CHEKDATE <= (	GETDATE() -											--TODAY
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) +		--LESS START-OF-CURRENTYEAR
										DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) -	--PLUS START-OF-PREVIOUSYEAR
										(DATEPART(DW,GETDATE())%7)							--PREV SATURDAY
										)
					AND P52W.UNTSTOPY != 0

			-----------------------------------------
			) X 
			JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = WAREHOUSE 
			LEFT 	--UNCOMMENT THIS LINE TO INCLUDE 'Projects' LABORGRP IN THE REPORT.
			JOIN GNC_LABORGROUPSBYGP_JOBCODE LG (NOLOCK) ON LG.JOBCODE = X.JOBTITLE
			WHERE ISNULL(LG.BENCHMARK,'SHIPPING') = 'SHIPPING'
	) Y
	WHERE Y.LABORGROUP IS NOT NULL 
	
	GROUP BY 
		Y.COMPANYID, Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		Y.PRTYPE, Y.PRCODE 
) Z
