/*
--PTRVSAI WITH MORE DETAIL
--SCRIPT BY LUCAS
SELECT * FROM VW_RPT_PTR_OUTOFBALANCE (NOLOCK)
WHERE RECORDTYPE <> 'P' 
AND WHID = '10' 
----AND ITEM IN ('003360.030.2', '005918.050.1', '006589.050.1', '008190.070.1')
--004493.010.1
--005670.021.1
--006589.050.1
--008585.050.1
--003279.030.1
ORDER BY WHID, ITEM, LOT, LOCATION, ROWID

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_PTR_OUTOFBALANCE]
AS
SELECT U.* 
FROM	(
		SELECT 
			--MC.RECORDTYPE,
			--MC.ROWID, 
			'MC' AS RECORDTYPE,
			ITM.DESCRIPTION_1 AS SHORTCOMMONNAME,
			(WH.IDENTITYID) AS WHID, 
			(ITM.ITEMCODE) ITEM, 
			(LOT.LOTCODE) LOT, 
			(WHLOC.IDENTITYID) AS WHLOCID, 
			(LOC.LOCATIONCODE) LOCATION, 
			DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
			DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem') AS DESIGITEM,
			DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust') AS DESIGCUST,
			DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc') AS DESIGLOC,
			ISNULL(MC.PRODUCTIONQUANTITY,0) AS PTR_ONHAND_PRODUCTIONQUANTITYONLY, 
			ISNULL(MCT.PTRREVIEWED,0) AS PTRREVIEWED_COMMITTED_ONLY,
			ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0))
						FROM IMLOCATIONQUANTITYSUMMARY AS LQS (NOLOCK)
						WHERE LQS.R_ITEM = MC.R_ITEM 
						AND LQS.R_LOT = MC.R_LOT 
						AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
					),0 ) - (ISNULL(MC.PRODUCTIONQUANTITY, 0) + ISNULL(MCT.PTRREVIEWED, 0)) 
				AS VARIANCE_INSIGHT_MINUS_TOTAL_OF_PRODQTY_PLUS_COMMITTED,
			ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0))
						FROM IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK)
						WHERE LQS.R_ITEM = MC.R_ITEM 
						AND LQS.R_LOT = MC.R_LOT 
						AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
					),0 ) AS ABECAS_ONHAND
		FROM OMREVIEWMASTERCODES MC (NOLOCK)
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
		JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		JOIN IDMASTER WHLOC (NOLOCK) ON WHLOC.ROWID = LOC.R_WAREHOUSE
		LEFT JOIN (	--CALC PTRREVIEWED
					SELECT 
						SUM(ISNULL(IA.COMMITTEDQUANTITY, 0)) AS PTRREVIEWED, 
						IA.R_MASTERCODE 
					FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
					JOIN OMTRANSACTIONDETAIL AS OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
					JOIN OMTRANSACTIONHEADER AS OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
					WHERE ISNULL(OH.RECORDTYPE, 'Z') != 'Z' 
					GROUP BY IA.R_MASTERCODE
					) AS MCT ON MCT.R_MASTERCODE = MC.ROWID 
		WHERE MC.RECORDTYPE <> 'P'
		AND (	SELECT SUM(ISNULL(imc.PRODUCTIONQUANTITY,0)) 
				FROM OMREVIEWMASTERCODES AS IMC (NOLOCK)
				WHERE imc.R_LOT = MC.R_LOT 
				AND imc.R_ITEM = MC.R_ITEM 
				AND imc.R_LOCATION = MC.R_LOCATION
			) <>	ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0))
								FROM IMLOCATIONQUANTITYSUMMARY AS LQS (NOLOCK)
								WHERE LQS.R_ITEM = MC.R_ITEM 
								AND LQS.R_LOT = MC.R_LOT 
								AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
							),0)
		AND	'' + TRIM(WH.IDENTITYID) + TRIM(ITM.ITEMCODE) + TRIM(LOT.LOTCODE)
			IN (	
				SELECT	'' + TRIM(X.WHID) + TRIM(X.ITEM) + TRIM(X.LOT)
				FROM 
					(	
					SELECT 
						(WH.IDENTITYID) AS WHID, 
						(ITM.ITEMCODE) ITEM, 
						(LOT.LOTCODE) LOT, 
						(WHLOC.IDENTITYID) AS WHLOCID, 
						(LOC.LOCATIONCODE) LOCATION, 
						SUM(ISNULL(MC.PRODUCTIONQUANTITY,0)) + SUM(ISNULL(MCT.PTRREVIEWED,0)) AS PTR_ONHAND,
						ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0)) 
									FROM IMLOCATIONQUANTITYSUMMARY AS LQS (NOLOCK)
									WHERE LQS.R_ITEM = MC.R_ITEM 
									AND LQS.R_LOT = MC.R_LOT 
									AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
								),0) AS ABECAS_ONHAND
					FROM OMREVIEWMASTERCODES MC (NOLOCK)
					JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
					JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT
					JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
					JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
					JOIN IDMASTER WHLOC (NOLOCK) ON WHLOC.ROWID = LOC.R_WAREHOUSE
					LEFT JOIN	(	--CALC PTRREVIEWED
									SELECT 
										SUM(ISNULL(IA.COMMITTEDQUANTITY, 0)) AS PTRREVIEWED, 
										IA.R_MASTERCODE 
									FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
									JOIN OMTRANSACTIONDETAIL AS OD (NOLOCK) ON OD.ROWID = IA.R_TRANSACTIONDETAIL
									JOIN OMTRANSACTIONHEADER AS OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER
									WHERE ISNULL(OH.RECORDTYPE, 'Z') != 'Z' 
									GROUP BY IA.R_MASTERCODE
								) AS MCT ON MCT.R_MASTERCODE = MC.ROWID 
					GROUP BY	WH.IDENTITYID, 
								ITM.ITEMCODE, 
								LOT.LOTCODE, 
								LOC.LOCATIONCODE, 
								MC.R_ITEM, 
								MC.R_LOT, 
								WHLOC.IDENTITYID, 
								MC.R_LOCATION
					HAVING 
						SUM(ISNULL(MC.PRODUCTIONQUANTITY,0)) + SUM(ISNULL(MCT.PTRREVIEWED,0)) 
						<>	ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0)) 
										FROM IMLOCATIONQUANTITYSUMMARY AS LQS (NOLOCK)
										WHERE LQS.R_ITEM = MC.R_ITEM 
										AND LQS.R_LOT = MC.R_LOT 
										AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
									),0)
					) AS X 
				) 

		UNION 

		--This picks up any Insight locations that are not in the Mastercodes table:
		SELECT 
			--'!' AS RECORDTYPE,
			--LQS.ROWID AS ROWID, 
			'LQS' AS RECORDTYPE,
			ITM.DESCRIPTION_1 AS SHORTCOMMONNAME,
			(WH.IDENTITYID) AS WHID, 
			(ITM.ITEMCODE) ITEM, 
			(LOT.LOTCODE) LOT, 
			(WHLOC.IDENTITYID) AS WHLOCID, 
			(LOC.LOCATIONCODE) LOCATION, 
			NULL AS SOURCE, --DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
			NULL AS DESIGITEM, --DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem') AS DESIGITEM,
			NULL AS DESIGCUST, --DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust') AS DESIGCUST,
			NULL AS DESIGLOC, --DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc') AS DESIGLOC,
			NULL AS PTR_ONHAND_PRODUCTIONQUANTITYONLY, --ISNULL(MC.PRODUCTIONQUANTITY,0) AS PTR_ONHAND_PRODUCTIONQUANTITYONLY, 
			NULL AS PTRREVIEWED_COMMITTED_ONLY, --ISNULL(MCT.PTRREVIEWED,0) AS PTRREVIEWED_COMMITTED_ONLY,
			ISNULL(LQS.ON_HAND, 0) AS VARIANCE_INSIGHT_MINUS_TOTAL_OF_PRODQTY_PLUS_COMMITTED,
			ISNULL(LQS.ON_HAND, 0) AS ABECAS_ONHAND

		FROM IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK)
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = LQS.R_ITEM
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = LQS.R_LOT
		JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = LQS.R_LOCATION
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		JOIN IDMASTER WHLOC (NOLOCK) ON WHLOC.ROWID = LOC.R_WAREHOUSE
		WHERE --ISNULL(LQS.ON_HAND, 0) != 0 AND	--incase users want zero onhand suppressed - DT 4/9/24
			'' + TRIM(WH.IDENTITYID) + TRIM(ITM.ITEMCODE) + TRIM(LOT.LOTCODE) + TRIM(LOC.LOCATIONCODE) 
			NOT IN (		
					(	SELECT	'' + TRIM(X.WHID) + TRIM(X.ITEM) + TRIM(X.LOT) + TRIM(X.LOCATION) 
						FROM 
							(	
							SELECT 
								(WH.IDENTITYID) AS WHID, 
								(ITM.ITEMCODE) ITEM, 
								(LOT.LOTCODE) LOT, 
								(WHLOC.IDENTITYID) AS WHLOCID, 
								(LOC.LOCATIONCODE) LOCATION--, 
								--SUM(ISNULL(MC.PRODUCTIONQUANTITY,0)) + SUM(ISNULL(MCT.PTRREVIEWED,0)) AS PTR_ONHAND,
								--ISNULL(	(	SELECT SUM(ISNULL(LQS.ON_HAND,0)) 
								--			FROM IMLOCATIONQUANTITYSUMMARY AS LQS (NOLOCK)
								--			WHERE LQS.R_ITEM = MC.R_ITEM 
								--			AND LQS.R_LOT = MC.R_LOT 
								--			AND (LQS.R_LOCATION = MC.R_LOCATION OR LQS.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
								--		),0) AS ABECAS_ONHAND
							FROM OMREVIEWMASTERCODES MC (NOLOCK)
							JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
							JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT
							JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION
							JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
							JOIN IDMASTER WHLOC (NOLOCK) ON WHLOC.ROWID = LOC.R_WAREHOUSE
							) X
						)
					)
) U
------------------------------------------------------------------------------------------------------------------------------------------
/*	PREVIOUS CODE SOURCE:
SELECT 
	MC.RECORDTYPE,
	MC.ROWID, 
	IM.DESCRIPTION_1 AS SHORTCOMMONNAME,
	(	SELECT TOP 1 RTRIM(IDENTITYID) 
		FROM IDMASTER (NOLOCK) 
		WHERE ROWID = IM.R_WAREHOUSE
		) WH,
	RTRIM(ITEMCODE) ITEM, 
	RTRIM(LOTCODE) LOT, 
	(	SELECT TOP 1 RTRIM(IDENTITYID) 
		FROM IDMASTER (NOLOCK) 
		WHERE ROWID = LC.R_WAREHOUSE
		) WHLOC,
	RTRIM(LOCATIONCODE) LOCATION, 
	DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
	DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem') AS DESIGITEM,
	DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust') AS DESIGCUST,
	DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc') AS DESIGLOC,
	ISNULL(PRODUCTIONQUANTITY,0) AS PTR_ONHAND_PRODUCTIONQUANTITYONLY, 
	ISNULL(PTRREVIEWED,0) PTRREVIEWED_COMMITTED_ONLY,
	ISNULL(
	--(	SELECT TOP 1 ISNULL(SM.ON_HAND,0)
	(	SELECT SUM(ISNULL(SM.ON_HAND,0))
		FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK)
		WHERE SM.R_ITEM = MC.R_ITEM 
		AND SM.R_LOT = MC.R_LOT 
		--AND SM.R_LOCATION = MC.R_LOCATION
		AND (SM.R_LOCATION = MC.R_LOCATION OR SM.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
		),0)-(ISNULL(PRODUCTIONQUANTITY,0) + ISNULL(PTRREVIEWED,0)) 
		AS VARIANCE_INSIGHT_MINUS_TOTAL_OF_PRODQTY_PLUS_COMMITTED,
	ISNULL(
	--(	SELECT TOP 1 ISNULL(SM.ON_HAND,0)
	(	SELECT SUM(ISNULL(SM.ON_HAND,0))
		FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK)
		WHERE SM.R_ITEM = MC.R_ITEM 
		AND SM.R_LOT = MC.R_LOT 
		--AND SM.R_LOCATION = MC.R_LOCATION
		AND (SM.R_LOCATION = MC.R_LOCATION OR SM.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
		),0) AS ABECAS_ONHAND
FROM OMREVIEWMASTERCODES MC (NOLOCK)
JOIN IMITEM IM (NOLOCK) ON IM.ROWID = MC.R_ITEM
JOIN IMLOT IL (NOLOCK) ON IL.ROWID = MC.R_LOT 
JOIN IMLOCATION LC (NOLOCK) ON LC.ROWID = MC.R_LOCATION
LEFT JOIN (
			SELECT 
				SUM(ISNULL(COMMITTEDQUANTITY, 0)) PTRREVIEWED, 
				R_MASTERCODE 
			FROM OMREVIEWINVENTORYASSIGNMENT I (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL AS D (NOLOCK) ON D.ROWID = I.R_TRANSACTIONDETAIL
			JOIN OMTRANSACTIONHEADER AS H (NOLOCK) ON H.ROWID = D.R_TRANSACTIONHEADER
			WHERE ISNULL(H.RECORDTYPE, 'Z') != 'Z' 
			GROUP BY R_MASTERCODE
			) AS MCT ON MCT.R_MASTERCODE = MC.ROWID 
WHERE
	(	SELECT SUM(ISNULL(PRODUCTIONQUANTITY,0)) 
		FROM OMREVIEWMASTERCODES AS IMC (NOLOCK)
		WHERE R_LOT = MC.R_LOT 
		AND R_ITEM = MC.R_ITEM 
		AND R_LOCATION = MC.R_LOCATION)
	<> 
	ISNULL(
	--(	SELECT TOP 1 ISNULL(SM.ON_HAND,0)
	(	SELECT SUM(ISNULL(SM.ON_HAND,0))
		FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK)
		WHERE SM.R_ITEM = MC.R_ITEM 
		AND SM.R_LOT = MC.R_LOT 
		--AND SM.R_LOCATION = MC.R_LOCATION
		AND (SM.R_LOCATION = MC.R_LOCATION OR SM.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
		),0)
AND	''+	(	SELECT TOP 1 RTRIM(IDENTITYID) 
			FROM IDMASTER (NOLOCK) 
			WHERE ROWID = IM.R_WAREHOUSE
			)+RTRIM(ITEMCODE)+RTRIM(LOTCODE) 
			IN (	
				--START {IN BLOCK}
				SELECT	''+WH+ITEM+LOT
				FROM 
					(	
					--START {PTRVSAI BLOCK}
					SELECT 
						(	SELECT TOP 1 RTRIM(IDENTITYID) 
							FROM IDMASTER (NOLOCK) 
							WHERE ROWID = IM.R_WAREHOUSE
							) WH,
						RTRIM(ITEMCODE) ITEM, 
						RTRIM(LOTCODE) LOT, 
						(	SELECT TOP 1 RTRIM(IDENTITYID) 
							FROM IDMASTER (NOLOCK) 
							WHERE ROWID = LC.R_WAREHOUSE
							) WHLOC,
						RTRIM(LOCATIONCODE) LOCATION, 
						SUM(ISNULL(PRODUCTIONQUANTITY,0)) + SUM(ISNULL(PTRREVIEWED,0)) AS PTR_ONHAND,
						ISNULL(
						(	SELECT SUM(ISNULL(SM.ON_HAND,0)) 
							FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK)
							WHERE SM.R_ITEM = MC.R_ITEM 
							AND SM.R_LOT = MC.R_LOT 
							--AND SM.R_LOCATION = MC.R_LOCATION
							AND (SM.R_LOCATION = MC.R_LOCATION OR SM.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
							),0) AS ABECAS_ONHAND
					FROM OMREVIEWMASTERCODES MC (NOLOCK)
					JOIN IMITEM IM (NOLOCK) ON IM.ROWID = MC.R_ITEM
					JOIN IMLOT IL (NOLOCK) ON IL.ROWID = MC.R_LOT
					JOIN IMLOCATION LC (NOLOCK) ON LC.ROWID = MC.R_LOCATION
					LEFT JOIN (	SELECT 
									SUM(ISNULL(COMMITTEDQUANTITY, 0)) PTRREVIEWED, 
									R_MASTERCODE 
								FROM OMREVIEWINVENTORYASSIGNMENT I (NOLOCK) 
								JOIN OMTRANSACTIONDETAIL AS D (NOLOCK) ON D.ROWID = I.R_TRANSACTIONDETAIL
								JOIN OMTRANSACTIONHEADER AS H (NOLOCK) ON H.ROWID = D.R_TRANSACTIONHEADER
								WHERE ISNULL(H.RECORDTYPE, 'Z') != 'Z' 
								GROUP BY R_MASTERCODE
								) AS MCT ON MCT.R_MASTERCODE = MC.ROWID 
					GROUP BY	IM.R_WAREHOUSE, 
								ITEMCODE, 
								LOTCODE, 
								LOCATIONCODE, 
								MC.R_ITEM, 
								MC.R_LOT, 
								LC.R_WAREHOUSE, 
								MC.R_LOCATION
					HAVING 
						SUM(ISNULL(PRODUCTIONQUANTITY,0)) + SUM(ISNULL(PTRREVIEWED,0)) 
						<> 
						ISNULL(
						(	SELECT SUM(ISNULL(SM.ON_HAND,0)) 
							FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK)
							WHERE SM.R_ITEM = MC.R_ITEM 
							AND SM.R_LOT = MC.R_LOT 
							--AND SM.R_LOCATION = MC.R_LOCATION
							AND (SM.R_LOCATION = MC.R_LOCATION OR SM.R_LOCATION IS NULL)	--INCLUDE SUMMARY RECORDS WITH BLANK LOCATIONS
							),0)
					) AS PTRVSAI	
					--ORDER BY WH, ITEM, LOT, WHLOC, [LOCATION]
					--END {PTRVSAI BLOCK}
				) 
				--END {IN BLOCK}

--ORDER BY WH, ITEM, LOT, LOCATION, ROWID
*/
------------------------------------------------------------------------------------------------------------------------------------------
/*

ITEMS THAT ELLEN BELIEVES THAT SHOULD BE ON THE OUT OF BALANCE REPORT BUT ARE NOT
ITEMS THAT ELLEN BELIEVES THAT SHOULD BE ON THE OUT OF BALANCE REPORT BUT ARE NOT
ITEMS THAT ELLEN BELIEVES THAT SHOULD BE ON THE OUT OF BALANCE REPORT BUT ARE NOT
ITEMS THAT ELLEN BELIEVES THAT SHOULD BE ON THE OUT OF BALANCE REPORT BUT ARE NOT

--test query for insight data:
SELECT SM.R_LOCATION, 
ITM.DESCRIPTION_1 AS SHORTCOMMONNAME, 
WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE, 
SM.ON_HAND 
FROM IMLOCATIONQUANTITYSUMMARY SM (NOLOCK) 
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = SM.R_ITEM 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = SM.R_LOT 
LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = SM.R_LOCATION 
WHERE WH.IDENTITYID = '10' 
AND ITM.ITEMCODE IN ('003360.030.2', '005918.050.1', '006589.050.1', '008190.070.1') 
ORDER BY WH.IDENTITYID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE 
--test query for mastercode data:
SELECT MC.R_LOCATION, 
ITM.DESCRIPTION_1 AS SHORTCOMMONNAME, 
WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE, 
DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem') AS DESIGITEM,
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust') AS DESIGCUST,
DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc') AS DESIGLOC,
(	SELECT SUM(ISNULL(PRODUCTIONQUANTITY,0)) 
	FROM OMREVIEWMASTERCODES AS IMC (NOLOCK) 
	WHERE R_ITEM = MC.R_ITEM AND R_LOT = MC.R_LOT AND R_LOCATION = MC.R_LOCATION 
	) AS PRODUCTIONQUANTITY, 
(	SELECT SUM(ISNULL(COMMITTEDQUANTITY, 0)) 
	FROM OMREVIEWINVENTORYASSIGNMENT I (NOLOCK) 
	JOIN OMTRANSACTIONDETAIL AS D (NOLOCK) ON D.ROWID = I.R_TRANSACTIONDETAIL 
	JOIN OMTRANSACTIONHEADER AS H (NOLOCK) ON H.ROWID = D.R_TRANSACTIONHEADER 
	WHERE ISNULL(H.RECORDTYPE, 'Z') != 'Z' 	AND I.R_MASTERCODE = MC.ROWID 
	GROUP BY R_MASTERCODE 
	) AS PTRREVIEWED 
FROM OMREVIEWMASTERCODES MC (NOLOCK)	-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>MASTERCODES 
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION 
WHERE WH.IDENTITYID = '10' 
AND ITM.ITEMCODE IN ('003360.030.2', '005918.050.1', '006589.050.1', '008190.070.1') 
ORDER BY WH.IDENTITYID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE 
*/
