/*
--67 HOLD STOP
SELECT *, 
SUPPLY - DEMAND AS LTS
FROM VW_RPT_HOLD_STOP (NOLOCK)
WHERE NETAVAILABLE <> 0
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_HOLD_STOP]
AS
SELECT
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	ITM.RECORDTYPE,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME,
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
	SUBSTRING(PGC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	CNT.CONTAINERSORT,
	ITM.ITEMCODE,
	(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
	CNT.CONTAINERCODE,
	ITM.SUBCLASSCODE AS QUALITYCODE,
	CNT.PRINTEDCONTAINERCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	VLOT.LOTCODE,
	LEFT(VLOT.LOTCODE,2) AS LOTYEAR,
	SUBSTRING(VLOT.LOTCODE,4,4) AS LOTSEASON,
	VLOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
	VLOT.USERDEFINEDDATE_1 AS HOLDSTOPSTARTDATE,
	VLOT.USERDEFINEDDATE_2 AS HOLDSTOPENDDATE,
	VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
	VLOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
	VLOT.USERDEFINEDDATE_6 AS SALESNOTESTARTDATE,
	VLOT.USERDEFINEDDATE_7 AS SALESNOTEENDDATE,
	DBO.FN_SALESNOTE(ITM.ROWID,VLOT.ROWID, NULL) AS FN_SALESNOTE,	--11 sec
	--DBO.FN_SALESNOTEREASON(ITM.ROWID,VLOT.ROWID, NULL) AS FN_SALESNOTEREASON,	--11 sec
	DBO.FN_SALESNOTEROLLUP(ITM.ROWID,NULL,NULL) AS FN_SALESNOTEROLLUP_FSU,
	--DBO.FN_SALESNOTEREASONROLLUP(ITM.ROWID,NULL,NULL) AS FN_SALESNOTEREASONROLLUP_FSU,
	DBO.FN_SUPPLY(ITM.ROWID,VLOT.ROWID,NULL) AS SUPPLY,	--11 sec
	DBO.FN_DEMAND(ITM.ROWID,VLOT.ROWID) AS DEMAND,		--11 sec
	VLOT.NETAVAILABLE,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,LEFT(VLOT.LOTCODE,2),NULL,NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,LEFT(VLOT.LOTCODE,2),NULL,NULL) AS FSU_LTS,
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,LEFT(VLOT.LOTCODE,2),NULL,'H',NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,LEFT(VLOT.LOTCODE,2),NULL,'H') AS FSU_HS

FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = VLOT.ROWID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
WHERE ITM.RECORDTYPE <> 'P' AND VLOT.NETAVAILABLE <> 0
--ORDER BY
--		WH.IDENTITYID, 
--		ITM.ITEMCODE,
--		VLOT.LOTCODE
