/*
--EDI PO CHANGES REPORT
------------------------------------------------------------------------------------------
--**NEED TO CREATE A FUNCTION THAT USES THIS VIEW TO TELL 855 MAP IF CHANGES WERE MADE**--
--THEN MODIFY THE 855 MAP TO SEND THIS INFO TO RURAL KING---------------------------------
------------------------------------------------------------------------------------------
SELECT 
* 
FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
WHERE DBO.FN_EDI_PO_CHANGES(TRANSACTIONNUMBER, LINENUMBER, NULL) > 0 
ORDER BY PO_RESERVENUMBER, PO_POTYPE, LINENUMBER 

--TEST SELECT:
SELECT * 
FROM VW_RPT_EDI_PO_CHANGES (NOLOCK) 
ORDER BY PO_RESERVENUMBER, PO_POTYPE, LINENUMBER 

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_EDI_PO_CHANGES]
AS
-------------------------------------------------------------------------------------------------
--ORDER DRIVES DATA MODEL
-------------------------------------------------------------------------------------------------
SELECT X.*,
IIF(PO_LINENUMBER IS NULL, 1, 0) AS CHG_LINE_ADD,									--LINE ADDED NOT ON THE PO
IIF(PO_LINENUMBER != ISNULL(LINENUMBER,0), 1, 0) AS CHG_LINE_DEL,					--LINE REMOVED FROM THE PO
IIF(ISNULL(PO_QUANTITYORDERED,0) != ISNULL(QUANTITYATSTAGE,0), 1, 0) AS CHG_QTY,	--QUANTITY CHANGED
IIF(ISNULL(PO_LANDEDPRICE,0) != ISNULL(ROUND(LANDEDPRICE,2),0), 1, 0) AS CHG_PRICE,			--PRICE CHANGED
IIF(ISNULL(PO_ALTERNATESKU,'') != ISNULL(ALTERNATESKU,''), 1,0) AS CHG_SKU			--SKU CHANGED
FROM (

		SELECT CO.COMPANYID, CO.NAME AS COMPANYNAME, POH.CREATIONDATETIME, 
		--OH.COMMITDATE, OH.TRANSACTIONDATE, OH.SHIPPINGDATE, 
		--POH.USERDEFINEDREFERENCE_19 AS SHIPNOTBEFORE, 
		--POH.USERDEFINEDREFERENCE_20 AS SHIPNOTAFTER, 
		--POH.USERDEFINEDREFERENCE_17 AS PO_VENDOR, 
		--WH.IDENTITYID AS WAREHOUSEID, CONS.IDGROUP, CONS.NAME AS CONSIGNEENAME, 
		------------------------
		POH.ROWID AS PO_ROWID, OH.ROWID, 
		POH.RECORDTYPE AS PO_RECORDTYPE, --REQUIRED FIELD FOR DBO.FN_EDI_PO_CHANGES TO WORK. 
		IIF(POH.RECORDTYPE = 'E', 'CHANGE', IIF(OH.TRANSACTIONNUMBER IS NULL, 'NEW', 'ORDER')) AS PO_POTYPE, 
		POH.TRANSACTIONNUMBER AS PO_RESERVENUMBER, OH.TRANSACTIONNUMBER, 
		--REPLACE(POH.TRANSACTIONNUMBER,'R','B') AS PO_RESERVENUMBER, OH.TRANSACTIONNUMBER, --TEMP PATCH FOR WORKFLOW QUESTION
		POH.STAGE AS PO_STAGE, OH.STAGE, 
		RIGHT('0000'+TRIM(POH.USERDEFINEDREFERENCE_19),4) AS PO_STORENUMBER, ICONS.USERDEFINEDREFERENCE_2 AS STORENUMBER, 
		POH.PURCHASEORDERNUMBER AS PO_PURCHASEORDERNUMBER, OH.PURCHASEORDERNUMBER, 
		CAST(POD.USERDEFINEDQUANTITY_9 AS INT) AS PO_LINENUMBER, OD.LINENUMBER, 
		--ADDED NEW UDQ_7 IN THE MAP, OLD DATA WILL USE QUANTITYORDERED
		ISNULL(POD.USERDEFINEDQUANTITY_7, POD.QUANTITYORDERED) AS PO_QUANTITYORDERED, 
		NULLIF(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0, ISNULL(OD.QUANTITYSHIPPED,0), ISNULL(OD.QUANTITYORDERED,0)),0) AS QUANTITYATSTAGE,
		POD.USERDEFINEDQUANTITY_8 AS PO_LANDEDPRICE, 
		------------------------------------------------------------------------------------
		--Zero FRTZONE amount denotes that FREIGHTRATEPERITEM should be treated as Zero too.
		NULLIF(ROUND(	ISNULL(OD.UNITPRICE,0) + 
						ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
						ISNULL(OD.TAGGINGCHARGEPERITEM,0) + 
						IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0))
					,2),0) AS LANDEDPRICE, 
--		NULLIF(ROUND(ISNULL(OD.UNITPRICE,0) + ISNULL(OD.HANDLINGCHARGEPERITEM,0) + ISNULL(OD.TAGGINGCHARGEPERITEM,0) + ISNULL(OD.FREIGHTRATEPERITEM,0),2),0) AS LANDEDPRICE, 
		------------------------------------------------------------------------------------
		--POD.R_ITEM AS PO_R_ITEM, OD.R_ITEM, 
		POD.USERDEFINEDREFERENCE_10 AS PO_ALTERNATESKU, PSD.ALTERNATESKU, 
		PPSH.PRICESCHEDULECODE AS PO_PRICESCHEDULECODE, PSH.PRICESCHEDULECODE, 
		PITM.ITEMCODE AS PO_ITEMCODE, ITM.ITEMCODE 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
		LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID 
		LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
		LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 

		LEFT JOIN OMTRANSACTIONHEADER POH (NOLOCK) ON POH.PURCHASEORDERNUMBER = OH.PURCHASEORDERNUMBER AND POH.RECORDTYPE IN('I', 'E')
		--LEFT JOIN OMTRANSACTIONHEADER POH (NOLOCK) ON REPLACE(POH.PURCHASEORDERNUMBER,'R','B') = OH.PURCHASEORDERNUMBER AND POH.RECORDTYPE IN('I', 'E')	--TEMP PATCH FOR WORKFLOW QUESTION
		LEFT JOIN OMTRANSACTIONDETAIL POD (NOLOCK) ON POD.R_TRANSACTIONHEADER = POH.ROWID AND POD.LINENUMBER = OD.LINENUMBER
		LEFT JOIN IMITEM PITM (NOLOCK) ON PITM.ROWID = POD.R_ITEM 
		LEFT JOIN IDMASTER PCONS (NOLOCK) ON PCONS.ROWID = POH.R_SHIPPER 
		LEFT JOIN IDCONSIGNEE PICONS (NOLOCK) ON PICONS.R_IDENTITY = POH.R_SHIPPER 
		LEFT JOIN IDMASTER PWH (NOLOCK) ON PWH.ROWID = POH.R_FMSHIPPER 
		LEFT JOIN IDCONSIGNEESHIPPERZONE PSZ (NOLOCK) ON PSZ.R_CONSIGNEE = PCONS.ROWID AND PSZ.R_SHIPPER = PWH.ROWID 
		LEFT JOIN IMPRICESCHEDULEHEADER PPSH (NOLOCK) ON PPSH.ROWID = ISNULL(PSZ.R_PRICESCHEDULE, PICONS.R_PRICESCHEDULE) 
		LEFT JOIN IMPRICESCHEDULEDETAIL PPSD (NOLOCK) ON PPSD.R_PRICESCHEDULEHEADER = PPSH.ROWID AND PPSD.R_ITEM = POD.R_ITEM AND PPSD.EXPIRATIONDATE >= GETDATE() 

		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
		WHERE OH.RECORDTYPE = 'R' 
		AND OH.TRANSACTIONTYPE = 'I'
		AND POH.PURCHASEORDERNUMBER IS NOT NULL
		--AND POH.PURCHASEORDERNUMBER = 'POB1X80156' 
	) X

--ORDER BY PO_RESERVENUMBER, LINENUMBER 


/*
-------------------------------------------------------------------------------------------------
--PO DRIVES DATA MODEL
-------------------------------------------------------------------------------------------------
SELECT X.*,
IIF(PO_LINENUMBER IS NULL, 1, 0) AS CHG_LINE_ADD, 
IIF(PO_LINENUMBER != ISNULL(LINENUMBER,0), 1, 0) AS CHG_LINE_DEL, 
IIF(ISNULL(PO_QUANTITYORDERED,0) != ISNULL(QUANTITYATSTAGE,0), 1, 0) AS CHG_QTY, 
IIF(ISNULL(PO_LANDEDPRICE,0) != ISNULL(LANDEDPRICE,0), 1, 0) AS CHG_PRICE, 
IIF(ISNULL(PO_ALTERNATESKU,'') != ISNULL(ALTERNATESKU,''), 1,0) AS CHG_SKU 
FROM (

		SELECT CO.COMPANYID, CO.NAME AS COMPANYNAME, 
		POH.ROWID AS PO_ROWID, OH.ROWID, 
		POH.RECORDTYPE AS PO_RECORDTYPE, --REQUIRED FIELD FOR DBO.FN_EDI_PO_CHANGES TO WORK. 
		IIF(POH.RECORDTYPE = 'E', 'CHANGE', IIF(OH.TRANSACTIONNUMBER IS NULL, 'NEW', 'RESERVE')) AS PO_POTYPE, 
		POH.TRANSACTIONNUMBER AS PO_RESERVENUMBER, OH.TRANSACTIONNUMBER, 
		POH.STAGE AS PO_STAGE, OH.STAGE, 
		RIGHT('0000'+TRIM(POH.USERDEFINEDREFERENCE_19),4) AS PO_STORENUMBER, ICONS.USERDEFINEDREFERENCE_2 AS STORENUMBER, 
		POH.PURCHASEORDERNUMBER AS PO_PURCHASEORDERNUMBER, OH.PURCHASEORDERNUMBER, 
		CAST(POD.USERDEFINEDQUANTITY_9 AS INT) AS PO_LINENUMBER, OD.LINENUMBER, 
		--ADDED NEW UDQ_7 IN THE MAP, OLD DATA WILL USE QUANTITYORDERED
		ISNULL(POD.USERDEFINEDQUANTITY_7, POD.QUANTITYORDERED) AS PO_QUANTITYORDERED, 
		NULLIF(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0, ISNULL(OD.QUANTITYSHIPPED,0), ISNULL(OD.QUANTITYORDERED,0)),0) AS QUANTITYATSTAGE,
		POD.USERDEFINEDQUANTITY_8 AS PO_LANDEDPRICE, 
		------------------------------------------------------------------------------------
		--Zero FRTZONE amount denotes that FREIGHTRATEPERITEM should be treated as Zero too.
		NULLIF(ROUND(	ISNULL(OD.UNITPRICE,0) + 
						ISNULL(OD.HANDLINGCHARGEPERITEM,0) + 
						ISNULL(OD.TAGGINGCHARGEPERITEM,0) + 
						IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0))
					,2),0) AS LANDEDPRICE, 
--		NULLIF(ROUND(ISNULL(OD.UNITPRICE,0) + ISNULL(OD.HANDLINGCHARGEPERITEM,0) + ISNULL(OD.TAGGINGCHARGEPERITEM,0) + ISNULL(OD.FREIGHTRATEPERITEM,0),2),0) AS LANDEDPRICE, 
		------------------------------------------------------------------------------------
		--POD.R_ITEM AS PO_R_ITEM, OD.R_ITEM, 
		POD.USERDEFINEDREFERENCE_10 AS PO_ALTERNATESKU, PSD.ALTERNATESKU, 
		PPSH.PRICESCHEDULECODE AS PO_PRICESCHEDULECODE, PSH.PRICESCHEDULECODE, 
		PITM.ITEMCODE AS PO_ITEMCODE, ITM.ITEMCODE 
		FROM OMTRANSACTIONHEADER POH (NOLOCK) 
		LEFT JOIN OMTRANSACTIONDETAIL POD (NOLOCK) ON POD.R_TRANSACTIONHEADER = POH.ROWID 
		LEFT JOIN IMITEM PITM (NOLOCK) ON PITM.ROWID = POD.R_ITEM 
		LEFT JOIN IDMASTER PCONS (NOLOCK) ON PCONS.ROWID = POH.R_SHIPPER 
		LEFT JOIN IDCONSIGNEE PICONS (NOLOCK) ON PICONS.R_IDENTITY = POH.R_SHIPPER 
		LEFT JOIN IDMASTER PWH (NOLOCK) ON PWH.ROWID = POH.R_FMSHIPPER 
		LEFT JOIN IDCONSIGNEESHIPPERZONE PSZ (NOLOCK) ON PSZ.R_CONSIGNEE = PCONS.ROWID AND PSZ.R_SHIPPER = PWH.ROWID 
		LEFT JOIN IMPRICESCHEDULEHEADER PPSH (NOLOCK) ON PPSH.ROWID = ISNULL(PSZ.R_PRICESCHEDULE, PICONS.R_PRICESCHEDULE) 
		LEFT JOIN IMPRICESCHEDULEDETAIL PPSD (NOLOCK) ON PPSD.R_PRICESCHEDULEHEADER = PPSH.ROWID AND PPSD.R_ITEM = POD.R_ITEM AND PPSD.EXPIRATIONDATE >= GETDATE() 

		LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.PURCHASEORDERNUMBER = POH.PURCHASEORDERNUMBER AND OH.RECORDTYPE = 'R' 
		LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID AND OD.LINENUMBER = POD.LINENUMBER
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
		LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID 
		LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
		LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 

		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = POH.COMPANYID
		WHERE POH.RECORDTYPE IN('I', 'E') 
		--AND POH.PURCHASEORDERNUMBER = 'POB1X80156' 
	) X
	--WHERE PO_RESERVENUMBER IN ('535-POB1X80156      ','535-POR1X80156      ') --TESTING WORKFLOW QUESTION
ORDER BY PO_RESERVENUMBER, LINENUMBER 

*/
