/*

LOGICALLY, THIS VIEW IS A HOT MESS....EVENTUALLY WOULD LIKE TO CIRCLE BACK TO THE VW_FREIGHT_PROFIT VIEW THAT I CREATED B4 ARGOS TOOK IT OVER.
THE 4 FREIGHT PROFIT REPORTS BELONG TOGETHER AS A UNIT, THIS SEPARATES THEM AND ISOLATES THE LOGIC. I JUST DON'T HAVE TIME RIGHT NOW.

--58 FREIGHT PROFIT BY STOP
SELECT
*
FROM VW_RPT_FREIGHTPROFIT_STOP (NOLOCK)
WHERE VW_RPT_FREIGHTPROFIT_STOP.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_FREIGHTPROFIT_STOP]
AS
SELECT CONVERT(DATE,TH.PLANSTART) AS TRIPDATE, 
TH.RECORDTYPE,
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
TH.TRIPNO AS TRIPNUMBER,
ISNULL(TH.EQUIPMENT,'') AS TRUCKTYPE,
TH.STATUS,
TH.ACTUALSTART,
WH.IDENTITYID AS SHIPPERCODE,
WH.NAME AS SHIPPERNAME,
ISNULL(TH.MILESLOADED,0) as LOADEDMILES,

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RATE/MILE') AS LOADEDMILESEXPENSE,

--LOADED RATE/MILE = LOADEDMILESEXPENSE/LOADEDMILES
(SELECT COUNT(KEYSEQUENCE) FROM FMTRIPDETAIL TD2 (NOLOCK) WHERE TD2.R_TRIPHEADER= TH.ROWID) AS STOPCOUNT, 

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='DROPPAY') AS TOTALSTOPPAY,

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='DHFEE') AS DEADHEADEXP,

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK)
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='FSMILES') AS FSCEXPENSE,

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='RTMILES') AS RETURNMILESEXP,

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID AND FC.CHARGECODE ='ADJUST') AS COSTADJUSTMENT, 

(SELECT ISNULL(SUM(ISNULL(TH2.MILESUNLOADED,0) + ISNULL(TH2.MILESLOADED,0)),0) 
FROM FMTRIPHEADER TH2 (NOLOCK) WHERE TH2.ROWID = TH.ROWID ) AS TOTALMILES, 

(SELECT ISNULL(SUM(ISNULL(SPOPENITEMS.AMOUNT,0)),0) FROM SPOPENITEMS (NOLOCK) 
LEFT JOIN IDFREIGHTCHARGES FC (NOLOCK) ON FC.ROWID= SPOPENITEMS.R_FREIGHTCHARGE 
WHERE SPOPENITEMS.R_SOURCEID = TH.ROWID ) AS TOTALFREIGHTEXPENSE,

(SELECT ISNULL(SUM(ISNULL(F.AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=F.R_TRANSACTIONHEADER
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_SOURCEID= OH.ROWID
LEFT JOIN FMTRIPDETAIL TD2 (NOLOCK) ON TD2.R_FMDISPATCHOBJECT = DO.ROWID AND TD2.R_TRIPHEADER = TH.ROWID
LEFT JOIN FMTRIPHEADER TH2 (NOLOCK) ON TH2.ROWID  = TD2.R_TRIPHEADER 
WHERE TH2.ROWID=TH.ROWID) AS TOTALFREIGHTREVENUE,

--FREIGHTPROFIT = FREIGHTREVENUEV - FREIGHTEXPENSE
(SELECT TOP 1 VCONS.CONSIGNEECITY FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = VCONS.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL TD2 (NOLOCK) ON TD2.R_FMDISPATCHOBJECT = DO.ROWID AND TD2.R_TRIPHEADER = TH.ROWID
ORDER BY TD2.DELSTOPNO DESC) AS DESTINATIONCITY,

(SELECT TOP 1 VCONS.CONSIGNEESTATE FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.R_CONSIGNEE = VCONS.CONSIGNEEMASTERROWID
LEFT JOIN FMTRIPDETAIL TD2 (NOLOCK) ON TD2.R_FMDISPATCHOBJECT = DO.ROWID AND TD2.R_TRIPHEADER = TH.ROWID
ORDER BY TD2.DELSTOPNO DESC) AS LASTSTATE,

ISNULL(TD.DELSTOPNO,0) AS STOPNUMBER,
ISNULL(VCONS.CONSIGNEEIDENTITYID,'') AS CUSTOMER,
ISNULL(VCONS.CONSIGNEENAME,'') AS CUSTOMERNAME,
ISNULL(VCONS.CONSIGNEECITY,'') AS CITY,
ISNULL(VCONS.CONSIGNEESTATE,'') AS STATE,

(SELECT ISNULL(SUM(ISNULL(F.AMOUNT,0)),0) FROM OMFREIGHT F (NOLOCK)
WHERE OH.ROWID=F.R_TRANSACTIONHEADER) AS FREIGHTREVENUE,

(SELECT ISNULL(SUM(ISNULL(DO.CUBESORDERED,0)),0) FROM FMDISPATCHOBJECT DO (NOLOCK)
LEFT JOIN FMTRIPDETAIL TD2 (NOLOCK) ON TD2.R_FMDISPATCHOBJECT = DO.ROWID
LEFT JOIN FMTRIPHEADER TH2 (NOLOCK) ON TH2.ROWID=TD2.R_TRIPHEADER
WHERE TH2.ROWID =TH.ROWID )AS TOTALVOLUME,

ISNULL(DO.CUBESORDERED,0)  AS VOLUME
-- FREIGHTEXPENSE = VOLUME / TOTALVOLUME) * TOTALFREIGHTEXPENSE
-- FREIGHTPROFIT = FREIGHTREVENUE - FREIGHTEXPENSE
FROM FMTRIPHEADER TH (NOLOCK)

LEFT JOIN FMTRIPDETAIL TD (NOLOCK) ON TD.R_TRIPHEADER = TH.ROWID 
LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID = TD.R_FMDISPATCHOBJECT 
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE 
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = DO.R_SOURCEID 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TH.R_ORIGIN
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = TH.COMPANYID

WHERE TH.RECORDTYPE <>'P' 
