/* RUNTIME: 13:30 
--BILLING_TRENDS 
SELECT *, 
NULL AS BREAKON, 
'Consolidated' AS BREAKONTEXT 
FROM VW_RPT_BILLING_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
--TEST FILTERS: 
--AND ISCURRYEAR = 'Y' 
--AND ISCURRPERIOD = 'Y' -->LATEST RUNTIME: 13:26
AND TRANSACTIONDATE BETWEEN '7/26/2020' AND '7/31/2021' -->LATEST RUNTIME: 1:25 (DATE RANGE IS BY FAR MORE EFFICIENT) 

--BILLING_TRENDS_M 
SELECT *, 
NATIONALACCOUNT AS BREAKON, 
IIF(NATIONALACCOUNT = 'Y', 'Major Accts', 'Independents') AS BREAKONTEXT 
FROM VW_RPT_BILLING_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
--TEST FILTERS: 
AND ISCURRYEAR = 'Y' 
AND ISCURRPERIOD = 'Y' 

--BILLING_TRENDS_S 
SELECT *, 
SALESREPID + NATIONALACCOUNT AS BREAKON, 
SALESREPID + ' - ' + SALESREPNAME + IIF(NATIONALACCOUNT = 'Y', '  (Major Accts)', '  (Independents)') AS BREAKONTEXT 
FROM VW_RPT_BILLING_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
--TEST FILTERS: 
AND ISCURRYEAR = 'Y' 
AND ISCURRPERIOD = 'Y' 

*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_BILLING_TRENDS] 
AS 
SELECT U.* 
FROM	( 
		---------------------------------- 
		-- THIS IS THE PERIODIC DATASET -- 
		---------------------------------- 
		SELECT 
		NULL AS ISYTD,		--PERIODTODATE 
		P.ISCURRYEAR, 
		P.ISCURRPERIOD, 
-------------------------- 
		P.RECORDTYPE, 
		P.COMPANYID, 
		P.SALEYEAR, 
		P.PERIOD, 
-------------------------- 
		P.TRANSACTIONDATE, 
		P.REPORTNET, 
		P.REPORTGROSS, 
		P.REPORTGROUP, 
		P.REPORTLINE, 
		P.REPORTNETDESC, 
		P.REPORTGROSSDESC, 
		P.REPORTGROUPDESC, 
		P.REPORTLINEDESC, 
		P.WAREHOUSEID, 
		--UNIFYING WAREHOUSENAME USING INSIGHT DATA: 
		(	SELECT WH.NAME 
			FROM IDMASTER WH (NOLOCK) 
			WHERE WH.IDENTITYID = P.WAREHOUSEID 
			) AS WAREHOUSENAME, 
		P.NATIONALACCOUNT, 
		P.SALESREPID, 
		P.SALESREPNAME, 
		P.CURRAMOUNT, 
		P.CURRAMOUNT10, 
		P.CURRAMOUNT20, 
		P.CURRAMOUNT40, 
		P.CURRAMOUNT60, 
		P.PREVAMOUNT, 
		P.PREVAMOUNT10, 
		P.PREVAMOUNT20, 
		P.PREVAMOUNT40, 
		P.PREVAMOUNT60 
		FROM VW_RPT_SQL_BILLING_TRENDS P (NOLOCK) 
		WHERE P.TRANSACTIONDATE <= GETDATE() 

		UNION ALL 

		-------------------------------- 
		-- THIS IS THE YEARLY DATASET -- 
		-------------------------------- 
		SELECT 
		'Y' AS ISYTD,		--YTD 
		Y.ISCURRYEAR, 
		'Y' AS ISCURRPERIOD, -- 'Y' FOR YTD TOTALS: 
-------------------------- 
		Y.RECORDTYPE, 
		Y.COMPANYID, 
		Y.SALEYEAR, 
		0 AS PERIOD,		--ZERO FOR YTD TOTALS: 
-------------------------- 
		Y.TRANSACTIONDATE, 
		Y.REPORTNET, 
		Y.REPORTGROSS, 
		Y.REPORTGROUP, 
		Y.REPORTLINE, 
		Y.REPORTNETDESC, 
		Y.REPORTGROSSDESC, 
		Y.REPORTGROUPDESC, 
		Y.REPORTLINEDESC, 
		Y.WAREHOUSEID, 
		--UNIFYING WAREHOUSENAME USING INSIGHT DATA: 
		(	SELECT WH.NAME 
			FROM IDMASTER WH (NOLOCK) 
			WHERE WH.IDENTITYID = Y.WAREHOUSEID 
			) AS WAREHOUSENAME, 
		Y.NATIONALACCOUNT, 
		Y.SALESREPID, 
		Y.SALESREPNAME, 
		Y.CURRAMOUNT, 
		Y.CURRAMOUNT10, 
		Y.CURRAMOUNT20, 
		Y.CURRAMOUNT40, 
		Y.CURRAMOUNT60, 
		Y.PREVAMOUNT, 
		Y.PREVAMOUNT10, 
		Y.PREVAMOUNT20, 
		Y.PREVAMOUNT40, 
		Y.PREVAMOUNT60 
		FROM VW_RPT_SQL_BILLING_TRENDS Y (NOLOCK) 
		WHERE Y.TRANSACTIONDATE <= GETDATE() 
		) U 
