/* RUNTIME: 2:51
--127 HIDDEN PRODUCT MANAGEMENT REPORT (REQUESTED BY DONNY JOHNSON)
SELECT * 
FROM VW_RPT_HIDDEN_PRODUCT_MGMT (NOLOCK) 
--WHERE RECORDTYPE = 'R' 
WHERE (A_AVAILABLE <> 0 OR A_LTS <> 0)
--AND WAREHOUSEID = '10'
--AND ITEMCODE = '004733.030.1'
order by warehouseid, plantgroupcode, sortnamevariety, containersort, qualitycode
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_HIDDEN_PRODUCT_MGMT]
AS
SELECT
	--CO.COMPANYID,
	--TRIM(CO.NAME) AS COMPANYNAME,
	--ITM.RECORDTYPE,
	TRIM(WH.IDENTITYID) AS WAREHOUSEID,
	TRIM(WH.NAME) AS WAREHOUSENAME,
	TRIM(ITM.ITEMCODE) AS ITEMCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	--ITM.REFERENCE_2 AS BOTANICALNAME,
	--CNT.PRINTEDCONTAINERCODE AS CONTSIZE,
	--CNT.CONTAINERCODE,
	--ITM.USERDEFINEDCODE_2 AS BRAND,
	--ITM.USERDEFINEDCODE_18 AS HZ,
	--ITM.SALEMAXQUANTITY,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUPCODE,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	CNT.CONTAINERSORT,
	TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,
	--GEN.DESCRIPTION_1 AS GENUSNAME,
--U3 FIELDS:
	(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.U3'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS U3_SEASONONHAND, 
	(	SELECT ISNULL(SUM(ISNULL(VLOT.NETAVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.U3'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS U3_SEASONNETAVAILABLE, 
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U3',NULL) AS U3_sLTS, 
	(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.U3'
		AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
		) AS U3_HS, 
--X FIELDS: [CULLS]
	(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.X'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS X_SEASONONHAND, 
	(	SELECT ISNULL(SUM(ISNULL(VLOT.NETAVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.X'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS X_SEASONNETAVAILABLE, 
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'X',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'X',NULL) AS X_sLTS, 
	(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.X'
		AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
		) AS X_HS, 
--Y FIELDS: [SHIFT?????]
	(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.Y'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS Y_SEASONONHAND, 
	(	SELECT ISNULL(SUM(ISNULL(VLOT.NETAVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.Y'
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS Y_SEASONNETAVAILABLE, 
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'Y',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'Y',NULL) AS Y_sLTS, 
	(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND VLOT.LOTCODE LIKE '%.Y'
		AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
		) AS Y_HS, 
--ALL HOLDSTOP LTS:
	DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'%',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'%',NULL) AS sLTS_H, 
	(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
		WHERE VLOT.R_ITEM = ITM.ROWID 
		AND CHARINDEX(SUBSTRING(VLOT.LOTCODE,4,1),'FSU')>0 
		AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
		) AS A_AVAILABLE, 
	DBO.FN_SUPPLYROLLUP(ITM.ROWID, DBO.FN_SALEYEAR(NULL)%100, NULL, NULL, NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID, DBO.FN_SALEYEAR(NULL)%100, NULL, NULL) AS A_LTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','F1',NULL) AS F1_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','F2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','F2',NULL) AS F2_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','S1',NULL) AS S1_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','S2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','S2',NULL) AS S2_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','U1',NULL) AS U1_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','U2',NULL) AS U2_iLTS, 
	--DBO.FN_SUPPLYROLLUP(ITM.ROWID,'CY','U3',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,'CY','U3',NULL) AS U3_iLTS, 
	--(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
	--	WHERE VLOT.R_ITEM = ITM.ROWID 
	--	AND VLOT.LOTCODE LIKE '%.X'
	--	AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
	--	) AS X_LOT_ONHAND, 
	--(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
	--	WHERE VLOT.R_ITEM = ITM.ROWID 
	--	AND VLOT.LOTCODE LIKE '%.Y'
	--	AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
	--	) AS Y_LOT_ONHAND, 
	--(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
	--	WHERE VLOT.R_ITEM = ITM.ROWID 
	--	AND VLOT.LOTCODE LIKE '%.Z'
	--	AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
	--	) AS Z_LOT_ONHAND 
	'EOL' AS EOL
FROM IMITEM ITM (NOLOCK) 
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
	JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
	LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1	AND GEN.CODETYPE = '11'	--GENUSNAME
WHERE ITM.RECORDTYPE = 'R' AND WH.IDENTITYID < '999'

