/* RUNTIME: 2:51
--127 SALES INVENTORY MANAGEMENT REPORT (REQUESTED BY JD JONES)
SELECT * 
FROM VW_RPT_SALES_INVENTORY_MGMT (NOLOCK) 
WHERE RECORDTYPE = 'R' 
AND WAREHOUSEID = '10'
--AND ITEMCODE = '004733.030.1'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_SALES_INVENTORY_MGMT]
AS
SELECT	
		X.F1_SEASONSUPPLY + X.S1_SEASONSUPPLY + X.U1_SEASONSUPPLY + X.U2_SEASONSUPPLY + X.U3_SEASONSUPPLY AS A_SUPPLY,
		IIF(F1_LTS < 0, (F1_LTS/IIF(F1_SEASONSUPPLY=0, F1_LTS, -1*F1_SEASONSUPPLY)), NULL) AS F1_PERCENTOVERSOLD,
		IIF(S1_LTS < 0, (S1_LTS/IIF(S1_SEASONSUPPLY=0, S1_LTS, -1*S1_SEASONSUPPLY)), NULL) AS S1_PERCENTOVERSOLD,
		IIF(U1_LTS < 0, (U1_LTS/IIF(U1_SEASONSUPPLY=0, U1_LTS, -1*U1_SEASONSUPPLY)), NULL) AS U1_PERCENTOVERSOLD,
		IIF(U2_LTS < 0, (U2_LTS/IIF(U2_SEASONSUPPLY=0, U2_LTS, -1*U2_SEASONSUPPLY)), NULL) AS U2_PERCENTOVERSOLD,
		IIF(U3_LTS < 0, (U3_LTS/IIF(U3_SEASONSUPPLY=0, U3_LTS, -1*U3_SEASONSUPPLY)), NULL) AS U3_PERCENTOVERSOLD,
		--IIF(F1_LTS < 0, (F1_LTS/IIF(F1_SEASONSUPPLY=0, F1_LTS, -1*F1_SEASONSUPPLY))*100, NULL) AS F1_PERCENTOVERSOLD,
		--IIF(S1_LTS < 0, (S1_LTS/IIF(S1_SEASONSUPPLY=0, S1_LTS, -1*S1_SEASONSUPPLY))*100, NULL) AS S1_PERCENTOVERSOLD,
		--IIF(U1_LTS < 0, (U1_LTS/IIF(U1_SEASONSUPPLY=0, U1_LTS, -1*U1_SEASONSUPPLY))*100, NULL) AS U1_PERCENTOVERSOLD,
		--IIF(U2_LTS < 0, (U2_LTS/IIF(U2_SEASONSUPPLY=0, U2_LTS, -1*U2_SEASONSUPPLY))*100, NULL) AS U2_PERCENTOVERSOLD,
		--IIF(U3_LTS < 0, (U3_LTS/IIF(U3_SEASONSUPPLY=0, U3_LTS, -1*U3_SEASONSUPPLY))*100, NULL) AS U3_PERCENTOVERSOLD,
		X.*
FROM	(
		SELECT
			CO.COMPANYID,
			TRIM(CO.NAME) AS COMPANYNAME,
			ITM.RECORDTYPE,
			TRIM(WH.IDENTITYID) AS WAREHOUSEID,
			TRIM(WH.NAME) AS WAREHOUSENAME,

			TRIM(ITM.ITEMCODE) AS ITEMCODE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.REFERENCE_2 AS BOTANICALNAME,
			CNT.PRINTEDCONTAINERCODE AS CONTSIZE,
			CNT.CONTAINERCODE,
			ITM.USERDEFINEDCODE_2 AS BRAND,
			ITM.USERDEFINEDCODE_18 AS HZ,
			ITM.SALEMAXQUANTITY,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUPCODE,
			ITM.REFERENCE_5 AS SORTNAMEVARIETY,
			CNT.CONTAINERSORT,
			TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,
			GEN.DESCRIPTION_1 AS GENUSNAME,
		--F1 FIELDS:
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F1',NULL) AS F1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1',NULL,NULL) AS F1_SEASONSUPPLY, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.F1'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS F1_SEASONAVAILABLE, 
		--F1_PERCENTOVERSOLD (SEASON ROLLUP)
			(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.F1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS F1_HS, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_4 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.F1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS F1_HOLDREASON, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_7 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.F1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS F1_SALESNOTE, 
			(	SELECT VLOT.OVERSELLPERCENTAGE FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.F1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS F1_LOTOVERSELLPERCENTAGE, 
		--S1 FIELDS:
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S1',NULL) AS S1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1',NULL,NULL) AS S1_SEASONSUPPLY, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.S1'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS S1_SEASONAVAILABLE, 
			--S1_PERCENTOVERSOLD (SEASON ROLLUP)
			(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.S1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS S1_HS, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_4 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.S1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS S1_HOLDREASON, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_7 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.S1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS S1_SALESNOTE, 
			(	SELECT VLOT.OVERSELLPERCENTAGE FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.S1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS S1_LOTOVERSELLPERCENTAGE, 
		--U1 FIELDS:
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U1',NULL) AS U1_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1',NULL,NULL) AS U1_SEASONSUPPLY, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U1'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS U1_SEASONAVAILABLE, 
			--U1_PERCENTOVERSOLD (SEASON ROLLUP)
			(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U1_HS, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_4 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U1_HOLDREASON, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_7 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U1_SALESNOTE, 
			(	SELECT VLOT.OVERSELLPERCENTAGE FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U1'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U1_LOTOVERSELLPERCENTAGE, 
		--U2 FIELDS:
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U2',NULL) AS U2_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2',NULL,NULL) AS U2_SEASONSUPPLY, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U2'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS U2_SEASONAVAILABLE, 
			--U2_PERCENTOVERSOLD (SEASON ROLLUP)
			(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U2'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U2_HS, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_4 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U2'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U2_HOLDREASON, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_7 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U2'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U2_SALESNOTE, 
			(	SELECT VLOT.OVERSELLPERCENTAGE FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U2'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U2_LOTOVERSELLPERCENTAGE, 
		--U3 FIELDS:
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3',NULL,NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U3',NULL) AS U3_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3',NULL,NULL) AS U3_SEASONSUPPLY, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U3'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS U3_SEASONAVAILABLE, 
			--U3_PERCENTOVERSOLD (SEASON ROLLUP)
			(	SELECT VLOT.USERDEFINEDCODE_3 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U3'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U3_HS, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_4 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U3'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U3_HOLDREASON, 
			(	SELECT VLOT.USERDEFINEDREFERENCE_7 FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U3'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U3_SALESNOTE, 
			(	SELECT VLOT.OVERSELLPERCENTAGE FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.U3'
				AND LEFT(VLOT.LOTCODE,2) = DBO.FN_SALEYEAR(NULL)%100
				) AS U3_LOTOVERSELLPERCENTAGE, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.AVAILABLE, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND CHARINDEX(SUBSTRING(VLOT.LOTCODE,4,1),'FSU')>0 
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS A_AVAILABLE, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID, DBO.FN_SALEYEAR(NULL)%100, NULL, NULL, NULL) - DBO.FN_DEMANDROLLUP(ITM.ROWID, DBO.FN_SALEYEAR(NULL)%100, NULL, NULL) AS A_LTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F1',NULL) AS F1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F2',NULL) AS F2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S1',NULL) AS S1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S2',NULL) AS S2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U1',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U1',NULL) AS U1_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U2',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U2',NULL) AS U2_iLTS, 
			DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U3',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U3',NULL) AS U3_iLTS, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.X'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS X_LOT_ONHAND, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.Y'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS Y_LOT_ONHAND, 
			(	SELECT ISNULL(SUM(ISNULL(VLOT.ON_HAND, 0)), 0) FROM VW_IMLOTVIEW2 VLOT (NOLOCK) 
				WHERE VLOT.R_ITEM = ITM.ROWID 
				AND VLOT.LOTCODE LIKE '%.Z'
				AND LEFT(VLOT.LOTCODE,2) <= DBO.FN_SALEYEAR(NULL)%100
				) AS Z_LOT_ONHAND 

		FROM IMITEM ITM (NOLOCK) 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1	AND GEN.CODETYPE = '11'	--GENUSNAME
		WHERE ITM.RECORDTYPE = 'R' AND WH.IDENTITYID < '999'
) X
