/*
--FEE CODE EXCEL

SELECT * 
FROM VW_RPT_FEECODE (NOLOCK) 
WHERE COMPANYID = 'SB' 
--
AND FEECODE = '004071'
ORDER BY
WAREHOUSEID,
GNC_ITEMSORT
*/
CREATE OR ALTER VIEW [dbo].[VW_RPT_FEECODE]
AS

SELECT
	--MISCELLANEOUS FIELDS:
	CO.COMPANYID,
	TRIM(CO.NAME) AS COMPANYNAME,
	ITM.RECORDTYPE,
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
	
	--NOT USED YET...
	IIF(VEND.IDENTITYID IS NOT NULL, 'Y', NULL) AS ISHOLDER,
	IIF(ITM.R_FEES IS NULL AND ITM.USERDEFINEDCODE_16 IS NOT NULL, 'Y', NULL) AS ISNEWLICENSE, --NO FEECODE, BUT LICPRIMARY DEFINED

	--FEEHEADER FIELDS: 
	TRIM(FH.MISCFEECODE) AS FEECODE, 

	--FEEDETAIL FIELDS: 
	FD.DESCRIPTION, 
	FD.CALCULATIONMETHOD AS CALCMETHOD, 
	(	SELECT FLAGDESCRIPTION 
		FROM ABFLAGFIELD (NOLOCK) 
		WHERE FLAGVALUE = FD.CALCULATIONMETHOD 
		AND TABLENAME = 'IMFEESDETAIL' 
		AND FIELDNAME = 'CALCULATIONMETHOD' 
		) AS CALCMETHODDESC, 
	FD.EFFECTIVESTARTDATE, 
	FD.METHOD, 
	(	SELECT FLAGDESCRIPTION 
		FROM ABFLAGFIELD (NOLOCK) 
		WHERE FLAGVALUE = FD.METHOD 
		AND TABLENAME = 'IMFEESDETAIL' 
		AND FIELDNAME = 'METHOD' 
		) AS METHODDESC, 
	FD.RATE, 
	TRIM(VEND.IDENTITYID) AS VENDORID, 
	TRIM(VEND.NAME) AS VENDORNAME, 
	FD.APPLYONDISCOUNTS AS APPLYDISCOUNT, 
	EXP.ACCOUNT AS EXPENSE, 
	REV.ACCOUNT AS REVENUE, 
	FD.WRITEAP, 

	--ITEM FIELDS: 
	ITMP.PROFILECODE AS PROFILE, 
	TRIM(ITM.ITEMCODE) AS ITEMNUMBER, 
	TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
	TRIM(WH.NAME) AS WAREHOUSENAME, 
	TRIM(ITM.USERDEFINEDCODE_16) AS LICPRIMARY, 
	TRIM(ITM.USERDEFINEDCODE_17) AS LICSECONDARY, 
	ITM.REFERENCE_1 AS COMMONNAME, 
	ITM.REFERENCE_2 AS BOTANICALNAME, 
	TRIM(ITM.CLASSCODE) AS CONTSIZE, 
	ITM.USERDEFINEDCODE_1 AS GENUS, 
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
	ITM.REFERENCE_5 AS CATALOGSORT, 
	CNT.CONTAINERSORT AS CONTSORT, 
	ITM.USERDEFINEDREFERENCE_1 AS PATENT, 
	ITM.USERDEFINEDCODE_2 AS BRAND, 
	ITM.USERDEFINEDCODE_13 AS BRANDTAGREQ, 
	ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ, 
	ITM.USERDEFINEDREFERENCE_2 AS SUBLICENSABLE, 
	ITM.USERDEFINEDCODE_6 AS PROPAGATION 
FROM IMFEESHEADER FH (NOLOCK)
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID 
	LEFT JOIN ACACCOUNT EXP (NOLOCK) ON EXP.ROWID = FD.R_EXPENSEGLACCOUNT 
	LEFT JOIN ACACCOUNT REV (NOLOCK) ON REV.ROWID = FD.R_REVENUEGLACCOUNT 
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 

	LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_FEES = FH.ROWID 
	LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
	LEFT JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = FH.COMPANYID 
WHERE FH.RECORDTYPE !='P' 
/*
FROM IMITEM ITM (NOLOCK) 
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	JOIN IMPRODUCTCATEGORY PGC (NOLOCK)ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID 
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
	LEFT JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES 
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID 
	LEFT JOIN ACACCOUNT EXP (NOLOCK) ON EXP.ROWID = FD.R_EXPENSEGLACCOUNT 
	LEFT JOIN ACACCOUNT REV (NOLOCK) ON REV.ROWID = FD.R_REVENUEGLACCOUNT 
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
	JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE 
	
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999' 
*/
