/*
--VW_RPT_FUTURECROP_VALUE_LOT

------------------------------------------------------------------
--NOTES
--
-- REWATCHING VIDEO - MATH COMPLICATION WITH SHIFT & PROP
-- ADD STEP TO SUBTRACT FPS-SHIFT-QTY FROM FPS-PARTIAL-ITEMTOTAL ON REPORT (QUESTION DOES THIS NUMBER GET PLACED IN THE FPSSHIFT FIELD?)
-- ADD STEP TO SUBTRACT FPS-PROP-QTY  FROM FPS-PARTIAL-ITEMTOTAL ON REPORT (QUESTION DOES THIS NUMBER GET PLACED IN THE FPSPROP FIELD?)
-- WILL PROBABLY GET CLARIFICATION FROM DJ ON THIS LATER..
--
-- IF LISTPRICE IS NULL FOR A CURRENT OR FUTURE YEAR, PRINT *NEW* INSTEAD.
--
--[X]  FIRST PASS, STITCH TOGETHER THE FIELDS
--[X]  SECOND PASS, CREATE A MAKESHIFT REPORT
--[X]  THIRD PASS, START MATH LOGIC PHASE ONE
--[X]  FOURTH PASS, ADD ONHAND BUCKETS THAT WILL BE NEEDED [COLUMN S/B CALLED INSIGHT QTY INSTEAD OF ONHAND]
--[X]  FIFTH PASS, APPLY ONHAND MATH LOGIC
--[ ]  SIXTH PASS, RECTIFY & REFINE THE REPORT
--[ ]  SEVENTH PASS, CIRCLE BACK AND ADDRESS FUTURE LISTPRICE

Same fields at RPTITEM Group level:
FUTURECOMPQTY IS SUM(TOTALCROPQTY * MULTCOMP)
FUTUREPARTQTY IS SUM(TOTALCROPQTY * MULTPART)
ACTUALCOMPQTY IS SUM(ACTUALPLANTINGQTY * MULTCOMP)
ACTUALPARTQTY IS SUM(ACTUALPLANTINGQTY * MULTPART)
ONHANDROLLUP IS ONHANDROLLUP

FIELDS FOUND ON MATH GYMNASTICS SPREADSHEET:
PSQTY		IS RPTITEM sum(FUTUREPARTQTY)
INSIGHTQTY	IS ONHANDROLLUP - RPTITEM sum(ACTUALPARTQTY)
TOT IN FSU	IS PSQTY + INSIGHTQTY

ASSORTMENTS OVER/UNDER SPECIAL CASE:
IF ITEMMATCH = 'N' THEN
OVER/UNDER	IS [INSIGHTQTY - (RPTITEM sum(FUTURECOMPQTY * ACTUALCOMPQTY / ASSORTEDPLANTTOTAL)]
ELSE
OVER/UNDER	IS [INSIGHTQTY - RPTITEM sum(FUTURECOMPQTY)] 

------------------------------------------------------------------
--Future Crop Schedule by Lot
SELECT * 
FROM VW_RPT_FUTURECROP_VALUE_LOT (NOLOCK) 
WHERE RECORDTYPE = 'R'
and scheduleyear = '2025'
and warehouseid = '20'
--AND RPTITEM = '004449.030.1'--'000909.030.1'
ORDER BY 
WAREHOUSEID, SCHEDULEYEAR, RPTSORTNAMEVARIETY, RPTItem--, SALESEASON 

-----------------------------------------------------------------
--SELECT * FROM VW_RPT_GNC_FUTURECROPPLANTINGSCHEDULE FPS (NOLOCK)
*/ 

CREATE OR ALTER VIEW [DBO].[VW_RPT_FUTURECROP_VALUE_LOT] 
AS 
SELECT 
	IT.COMPANYID, 
	IT.RECORDTYPE, 
	IT.WAREHOUSEID, 
	IT.SCHEDULEYEAR, 
	IT.RPTQUALITY, 
	IT.RPTPLANTGROUPCODE, 
	IT.RPTSORTNAMEVARIETY, 
	IT.RPTITEM, IT.RPTCOMMONNAME, 
	IT.LISTPRICE, 
	IT.TARGETPRICE, 
	IT.CY, IT.SY, 	
	------------------------
	MAX(ONHANDROLLUP) - SUM(ACTUALPLANTEDQTY*MULTPART) AS INSIGHT_QTY,
	MAX(ONHANDROLLUP) - SUM(ACTUALPLANTEDQTY*MULTPART) - 
		SUM(TOTALCROPQTY*MULTCOMP*
			IIF(ITEMSMATCH = 'N', ACTUALPLANTEDQTY/ASSORTEDPLANTTOTAL*MULTCOMP, 1)
			) AS OVER_UNDER, 
	SUM(TOTALCROPQTY * MULTPART) AS PS_QTY, 
	SUM(ONHAND_X ) + ONHANDROLLUP_X AS ONHAND_X, 
	SUM(ONHAND_Y ) + ONHANDROLLUP_Y AS ONHAND_Y, 
	SUM(ONHAND_Z ) + ONHANDROLLUP_Z AS ONHAND_Z, 
	SUM(ONHAND_F1) + ONHANDROLLUP_F1 AS ONHAND_F1, 
	SUM(ONHAND_F2) + ONHANDROLLUP_F2 AS ONHAND_F2, 
	SUM(ONHAND_F3) + ONHANDROLLUP_F3 AS ONHAND_F3, 
	SUM(ONHAND_S1) + ONHANDROLLUP_S1 AS ONHAND_S1, 
	SUM(ONHAND_S2) + ONHANDROLLUP_S2 AS ONHAND_S2, 
	SUM(ONHAND_S3) + ONHANDROLLUP_S3 AS ONHAND_S3, 
	SUM(ONHAND_U1) + ONHANDROLLUP_U1 AS ONHAND_U1, 
	SUM(ONHAND_U2) + ONHANDROLLUP_U2 AS ONHAND_U2, 
	SUM(ONHAND_U3) + ONHANDROLLUP_U3 AS ONHAND_U3, 
	SUM(ONHAND_F1 + ONHAND_F2 + ONHAND_F3 + 
		ONHAND_S1 + ONHAND_S2 + ONHAND_S3 + 
		ONHAND_U1 + ONHAND_U2 + ONHAND_U3) + 
		ONHANDROLLUP_F1 + ONHANDROLLUP_F2 + ONHANDROLLUP_F3 + 
		ONHANDROLLUP_S1 + ONHANDROLLUP_S2 + ONHANDROLLUP_S3 + 
		ONHANDROLLUP_U1 + ONHANDROLLUP_U2 + ONHANDROLLUP_U3 AS ONHAND_FSU, 
	SUM(ONHAND_X  + ONHAND_Y  + ONHAND_Z  + 
		ONHAND_F1 + ONHAND_F2 + ONHAND_F3 + 
		ONHAND_S1 + ONHAND_S2 + ONHAND_S3 + 
		ONHAND_U1 + ONHAND_U2 + ONHAND_U3) + 
		ONHANDROLLUP_X + ONHANDROLLUP_Y + ONHANDROLLUP_Z + 
		ONHANDROLLUP_F1 + ONHANDROLLUP_F2 + ONHANDROLLUP_F3 + 
		ONHANDROLLUP_S1 + ONHANDROLLUP_S2 + ONHANDROLLUP_S3 + 
		ONHANDROLLUP_U1 + ONHANDROLLUP_U2 + ONHANDROLLUP_U3 AS ONHAND_TOTAL, 
	SUM(ONHAND_X *IT.TARGETPRICE) + (ONHANDROLLUP_X *IT.TARGETPRICE) AS VALUE_X, 
	SUM(ONHAND_Y *IT.TARGETPRICE) + (ONHANDROLLUP_Y *IT.TARGETPRICE) AS VALUE_Y, 
	SUM(ONHAND_Z *IT.TARGETPRICE) + (ONHANDROLLUP_Z *IT.TARGETPRICE) AS VALUE_Z, 
	SUM(ONHAND_F1*IT.TARGETPRICE) + (ONHANDROLLUP_F1 *IT.TARGETPRICE) AS VALUE_F1, 
	SUM(ONHAND_F2*IT.TARGETPRICE) + (ONHANDROLLUP_F2 *IT.TARGETPRICE) AS VALUE_F2, 
	SUM(ONHAND_F3*IT.TARGETPRICE) + (ONHANDROLLUP_F3 *IT.TARGETPRICE) AS VALUE_F3, 
	SUM(ONHAND_S1*IT.TARGETPRICE) + (ONHANDROLLUP_S1 *IT.TARGETPRICE) AS VALUE_S1, 
	SUM(ONHAND_S2*IT.TARGETPRICE) + (ONHANDROLLUP_S2 *IT.TARGETPRICE) AS VALUE_S2, 
	SUM(ONHAND_S3*IT.TARGETPRICE) + (ONHANDROLLUP_S3 *IT.TARGETPRICE) AS VALUE_S3, 
	SUM(ONHAND_U1*IT.TARGETPRICE) + (ONHANDROLLUP_U1 *IT.TARGETPRICE) AS VALUE_U1, 
	SUM(ONHAND_U2*IT.TARGETPRICE) + (ONHANDROLLUP_U2 *IT.TARGETPRICE) AS VALUE_U2, 
	SUM(ONHAND_U3*IT.TARGETPRICE) + (ONHANDROLLUP_U3 *IT.TARGETPRICE) AS VALUE_U3, 
	(SUM(ONHAND_F1 + ONHAND_F2 + ONHAND_F3 + 
		 ONHAND_S1 + ONHAND_S2 + ONHAND_S3 + 
		 ONHAND_U1 + ONHAND_U2 + ONHAND_U3) + 
		 ONHANDROLLUP_F1 + ONHANDROLLUP_F2 + ONHANDROLLUP_F3 + 
		 ONHANDROLLUP_S1 + ONHANDROLLUP_S2 + ONHANDROLLUP_S3 + 
		 ONHANDROLLUP_U1 + ONHANDROLLUP_U2 + ONHANDROLLUP_U3)*IT.TARGETPRICE AS VALUE_FSU, 
	(SUM(ONHAND_X  + ONHAND_Y  + ONHAND_Z  + 
		 ONHAND_F1 + ONHAND_F2 + ONHAND_F3 + 
		 ONHAND_S1 + ONHAND_S2 + ONHAND_S3 + 
		 ONHAND_U1 + ONHAND_U2 + ONHAND_U3) + 
		 ONHANDROLLUP_X + ONHANDROLLUP_Y + ONHANDROLLUP_Z + 
		 ONHANDROLLUP_F1 + ONHANDROLLUP_F2 + ONHANDROLLUP_F3 + 
		 ONHANDROLLUP_S1 + ONHANDROLLUP_S2 + ONHANDROLLUP_S3 + 
		 ONHANDROLLUP_U1 + ONHANDROLLUP_U2 + ONHANDROLLUP_U3)*IT.TARGETPRICE AS VALUE_TOTAL 
FROM (
		SELECT O.*, 
			IIF(O.RPTSEASON='X', (O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_X, 
			IIF(O.RPTSEASON='Y', (O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_Y, 
			IIF(O.RPTSEASON='Z', (O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_Z, 
			IIF(O.RPTSEASON='F1',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_F1, 
			IIF(O.RPTSEASON='F2',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_F2, 
			IIF(O.RPTSEASON='F3',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_F3, 
			IIF(O.RPTSEASON='S1',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_S1, 
			IIF(O.RPTSEASON='S2',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_S2, 
			IIF(O.RPTSEASON='S3',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_S3, 
			IIF(O.RPTSEASON='U1',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_U1, 
			IIF(O.RPTSEASON='U2',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_U2, 
			IIF(O.RPTSEASON='U3',(O.TOTALCROPQTY*O.MULTPART) - (O.ACTUALPLANTEDQTY * O.MULTPART), 0) AS ONHAND_U3 
		FROM (

		SELECT	
			FPS.CY, FPS.SY, 
			FPS.COMPANYID, 
			FPS.RECORDTYPE, 
			FPS.WAREHOUSEID, 
			FPS.SCHEDULEYEAR, 
			FPS.PSID, T.PSID AS ACTUALPSID, 
			--ISNULL(T.PLANTINGSCHEDULELINE, FPS.PLANTINGSCHEDULELINE) AS RPTPSLINE, 
			FPS.PSITEMNUMBER, T.ITEMCODE, 
			ISNULL(T.ITEMCODE, FPS.PSITEMNUMBER) AS RPTITEM, 
			ISNULL(T.COMMONNAME, FPS.PSCOMMONNAME) AS RPTCOMMONNAME, 
			ISNULL(T.SORTNAMEVARIETY, FPS.PSSORTNAMEVARIETY) AS RPTSORTNAMEVARIETY, 
			ISNULL(T.QUALITY, FPS.QUALITY) AS RPTQUALITY, 
			ISNULL(T.PLANTGROUPCODE, FPS.PLANTGROUPCODE) AS RPTPLANTGROUPCODE, 
			------------------------
			TRIM(FPS.SALESEASON) AS SALESEASON, 
			TRIM(T.LOTSEASON) AS ACTUALSEASON, 
			TRIM(ISNULL(T.LOTSEASON, FPS.SALESEASON)) AS RPTSEASON, 
			ISNULL(FPS.TOTALCROPQTY, 0) AS TOTALCROPQTY, 
			ISNULL(FPS.TOTALCROPQTY, 0) - ISNULL(FPS.SHIFTQTY, 0) - ISNULL(FPS.PROPSTOCKQTY, 0) AS FSUCROPQTY, 
			ISNULL(FPS.SHIFTQTY, 0) AS SHIFTQTY,  
			ISNULL(FPS.PROPSTOCKQTY, 0) AS PROPSTOCKQTY,  

			--FPS.TARGETCOMPLETEDATE, 
			FPS.MULTCOMP, --USE: MULTCOMP * [QTY] TO SET [COMPLETEDQTY] 
			FPS.MULTPART, --USE: MULTPART * [QTY] TO SET [PARTIALQTY] 
			IIF(T.ITEMCODE IS NULL, '', IIF(FPS.PSITEMNUMBER = T.ITEMCODE, 'Y', 'N')) AS ITEMSMATCH, --MIGHT NEED FOR LOGIC LATER.. 
			ISNULL(T.ACTUALPLANTEDQTY,0) AS ACTUALPLANTEDQTY, 
			ISNULL(A.ASSORTEDPLANTTOTAL, 0) AS ASSORTEDPLANTTOTAL, 
			--A.ASSORTEDWHID, A.ASSORTEDSALEYEAR, A.ASSORTEDLOTSEASON, A.ASSORTEDPSID, 
			FPS.PROJECTCODE, 
			FPS.UPLOADDATE, 
			FPS.TARGETPRICE, 
			--WHEN THERE ARE NO PLANTINGS, USE LISTPRICE BASED OFF OF PSITEMNUMBER ROWID:
			ISNULL(DBO.FN_LISTPRICE(T.ITMROWID,NULL,NULL),DBO.FN_LISTPRICE(FPS.ITMROWID,NULL,NULL)) AS LISTPRICE, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'X', NULL),0 ) AS ONHANDROLLUP_X, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'Y', NULL),0 ) AS ONHANDROLLUP_Y, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'Z', NULL),0 ) AS ONHANDROLLUP_Z, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'F1', NULL),0 ) AS ONHANDROLLUP_F1, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'F2', NULL),0 ) AS ONHANDROLLUP_F2, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'F3', NULL),0 ) AS ONHANDROLLUP_F3, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'S1', NULL),0 ) AS ONHANDROLLUP_S1, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'S2', NULL),0 ) AS ONHANDROLLUP_S2, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'S3', NULL),0 ) AS ONHANDROLLUP_S3, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'U1', NULL),0 ) AS ONHANDROLLUP_U1, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'U2', NULL),0 ) AS ONHANDROLLUP_U2, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, 'U3', NULL),0 ) AS ONHANDROLLUP_U3, 
			--ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, TRIM(ISNULL(T.LOTSEASON, FPS.SALESEASON)), NULL),0 ) AS SEASONONHANDROLLUP, 
			ISNULL(DBO.FN_ONHANDROLLUP(ISNULL(T.ITMROWID, FPS.ITMROWID), FPS.SCHEDULEYEAR%100, '%', NULL),0 ) AS ONHANDROLLUP, 
			'EOL' AS EOL 
		FROM VW_RPT_GNC_FUTURECROPPLANTINGSCHEDULE FPS (NOLOCK) 
				--IMTRANSACTION DATA 
				--==================
				LEFT JOIN ( 
				--T: BY ITEM TOTALS
				SELECT 
					TRIM(WH.IDENTITYID) AS ACTUALWHID, 
					LOT.USERDEFINEDCODE_6 AS SALEYEAR, 
					LOT.USERDEFINEDCODE_10 AS LOTSEASON, 
					TRIM(ITM.ITEMCODE) AS ITEMCODE, 
					ITM.REFERENCE_1 AS COMMONNAME, 
					ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
					TRIM(ITM.SUBCLASSCODE) AS QUALITY, 
					LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE, 
					--TD.USERDEFINEDREFERENCE_1 AS PLANTINGSCHEDULELINE, 
					SUBSTRING(REPLACE(REPLACE(TD.USERDEFINEDREFERENCE_1,'-',''),'.',''),3,4) AS PSID, 
					SUM(ISNULL(TD.QUANTITY,0)) AS ACTUALPLANTEDQTY, 
					ITM.ROWID AS ITMROWID, 
					'EOL' AS EOL 

				FROM IMTRANSACTIONHEADER TH (NOLOCK) 
				JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
				JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
				JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
				JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT
				LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
				WHERE TD.USERDEFINEDCODE_1 IN ('Plant','Planting','Shift-in','Shift.IN','Specialty','Receipt-IM')	--new codes to filter with per Ellen 7/17/23 
				AND TD.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS PLANTING DATE 
				--AND TD.USERDEFINEDREFERENCE_1 = '24.1002'--'24.3769'--'24.4189'--TESTDATA-- 
				GROUP BY WH.IDENTITYID, LOT.USERDEFINEDCODE_6, LOT.USERDEFINEDCODE_10, ITM.ITEMCODE, ITM.REFERENCE_1, ITM.REFERENCE_5, ITM.SUBCLASSCODE, PGC.PRODUCTCATEGORYCODE, TD.USERDEFINEDREFERENCE_1, ITM.ROWID 
				) T ON	FPS.WAREHOUSEID = T.ACTUALWHID AND FPS.PSID = T.PSID AND FPS.SCHEDULEYEAR = T.SALEYEAR 
				--------------------
				LEFT JOIN ( 
				--A: BY ASSORTED ITEM TOTALS
				SELECT 
					LOT.USERDEFINEDCODE_6 AS ASSORTEDSALEYEAR, 
					LOT.USERDEFINEDCODE_10 AS ASSORTEDLOTSEASON, 
					TRIM(WH.IDENTITYID) AS ASSORTEDWHID, 
					SUBSTRING(REPLACE(REPLACE(TD.USERDEFINEDREFERENCE_1,'-',''),'.',''),3,4) AS ASSORTEDPSID, 
					SUM(ISNULL(TD.QUANTITY,0)) AS ASSORTEDPLANTTOTAL, 
					'EOL' AS EOL 
				FROM IMTRANSACTIONHEADER TH (NOLOCK) 
				JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
				JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
				JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = TD.R_LOT
				WHERE TD.USERDEFINEDCODE_1 IN ('Plant','Planting','Shift-in','Shift.IN','Specialty','Receipt-IM')	--new codes to filter with per Ellen 7/17/23 
				AND TD.USERDEFINEDDATE_1 IS NOT NULL	--UDC_1 IS PLANTING DATE 
				--AND TD.USERDEFINEDREFERENCE_1 = '24.1002'--'24.3769'--'24.4189'--TESTDATA-- 
				GROUP BY WH.IDENTITYID, LOT.USERDEFINEDCODE_6, LOT.USERDEFINEDCODE_10, TD.USERDEFINEDREFERENCE_1 
				) A ON	FPS.WAREHOUSEID = A.ASSORTEDWHID AND FPS.PSID = A.ASSORTEDPSID AND FPS.SCHEDULEYEAR = A.ASSORTEDSALEYEAR 
				--==================
		) O
) IT
GROUP BY 
	IT.COMPANYID, 
	IT.RECORDTYPE, 
	IT.WAREHOUSEID, 
	IT.SCHEDULEYEAR, 
	IT.RPTQUALITY, 
	IT.RPTPLANTGROUPCODE, 
	IT.RPTSORTNAMEVARIETY, 
	IT.RPTITEM, IT.RPTCOMMONNAME, 
	IT.LISTPRICE, 
	IT.TARGETPRICE, 
	IT.CY, IT.SY,
	IT.ONHANDROLLUP_X, IT.ONHANDROLLUP_Y, IT.ONHANDROLLUP_Z, 
	IT.ONHANDROLLUP_F1, IT.ONHANDROLLUP_F2, IT.ONHANDROLLUP_F3, 
	IT.ONHANDROLLUP_S1, IT.ONHANDROLLUP_S2, IT.ONHANDROLLUP_S3, 
	IT.ONHANDROLLUP_U1, IT.ONHANDROLLUP_U2, IT.ONHANDROLLUP_U3 
