/*
--WEBSITE AVAILABILITY DATA
SELECT
VW_RPT_WEBSITE_AVAILABILITY.*,
IIF (ILTS_CURR < 0, 0, ILTS_CURR) AS iLTS
FROM VW_RPT_WEBSITE_AVAILABILITY (NOLOCK)
WHERE ISNULL(HOLDSTOP,'') <> 'S'
AND ILTS_CURR <> 0
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_WEBSITE_AVAILABILITY]
AS
SELECT	ITM.REFERENCE_1,
ITM.RECORDTYPE,
CO.COMPANYID,
TRIM(CO.NAME) AS COMPANYNAME,

ITM.REFERENCE_5 AS VARIETYSORT,
CNT.CONTAINERCODE,
TRIM(VWH.SHIPPERCITY) AS WHCITY,
TRIM(VWH.SHIPPERIDENTITYID) AS WHCODE,
TRIM(VWH.SHIPPERSTATE) AS WHSTATE,
-- RETURN THE HOLDSTOPCODE OF THE CURRENT SEASON OF THE CURRENT YEAR - PER SC
(SELECT LOT.USERDEFINEDCODE_3
	FROM IMLOT LOT (NOLOCK) WHERE LOT.R_ITEM = ITM.ROWID
		AND LOT.LOTCODE = LEFT(SEA.SEASONCODE,3)+SUBSTRING(SEA.SEASONCODE,7,2) 
	) AS HOLDSTOP,
TRIM(ITM.ITEMCODE) AS ITEM,
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
CNT.PRINTEDCONTAINERCODE AS CONTAINERSIZE,
-- CURRENT SEASON INFLATED LTS ROLLUP OF CURRENT AND PREVIOUS YEAR QUANTITIES:
DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,SUBSTRING(SEA.SEASONCODE,7,1)+'%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,SUBSTRING(SEA.SEASONCODE,7,1)+'%',NULL) AS iLTS_CURR,
QUAL.DESCRIPTION_1 AS QUALITYDESC,
TRIM(ITM.SUBCLASSCODE) AS QUALITY,
NULL AS SALESNOTE,	--NOT NEEDED ON WEBSITE.
(SELECT TRIM(ITMDP.PROFILECODE) FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETY,
CNT.CONTAINERSORT,
ITM.USERDEFINEDCODE_2 AS BRAND,
TRIM(VWH.SHIPPERNAME) AS WHNAME,
--THIS IS THE OFFICIAL GNC SORTORDER FOR ITEMS:
PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT
FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN VW_IDSHIPPERVIEW VWH (NOLOCK) ON VWH.SHIPPERMASTERROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
JOIN IMCODES QUAL (NOLOCK) ON QUAL.CODE = ITM.SUBCLASSCODE AND QUAL.CODETYPE='02'
--ADDING A DAY BECAUSE WEBSITE IS UPDATED FOR THE NEXT MORNING WHICH MIGHT BE THE DAWN OF A NEW SEASON PER SC:
JOIN IMSEASONCODE SEA (NOLOCK) ON SUBSTRING(SEA.SEASONCODE,4,2) = VWH.SHIPPERIDENTITYID AND GETDATE()+1 BETWEEN SEA.STARTDATE AND SEA.ENDDATE
WHERE WH.IDENTITYID IN ('10', '20', '40')
AND LEFT(ITM.REFERENCE_1,3) NOT IN ('N/A','N/S','N/U','G/S','ASS')
AND LEFT(PGC.PRODUCTCATEGORYCODE,3) NOT IN ('430','530','900')
AND ITM.SUBCLASSCODE NOT IN (3,4)
AND ITM.RECORDTYPE <> 'P'

