/*
--WEBSITE VARIETY DATA
SELECT
VW_RPT_WEBSITE_VARIETY.*
FROM VW_RPT_WEBSITE_VARIETY (NOLOCK)
WHERE VW_RPT_WEBSITE_VARIETY.RECORDTYPE <> 'P'
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_WEBSITE_VARIETY]
AS
SELECT	'R' AS RECORDTYPE,
		'SB' AS COMPANYID,
		'GREENLEAF NURSERY COMPANY' AS COMPANYNAME,
		*
FROM	[GNCOKBI].[GREENLEAFAPPS].[DBO].[VW_FTPCLARITY]
----------------------------------------
		--[BOTANICALNAME],
		--[TAGDESCRIPTION],
		--[VARIETYSORT],
		--[COMMONNAME],
		--[EXPOSURECODE],
		--[EXPOSUREDESC],
		--[GENUS],
		--[HARDINESSZONE],
		--[HARDINESSZONEDESC],
		--[PHOTO],
		--[PLANTGROUPCODE],
		--[PLANTGROUPDESC],
		--[PLANTINGGUIDE],
		--RIGHT('000000'+TRIM([VARIETY]),6) AS VARIETY,
		--[REVERSECOMMONNAME],
		--[LONGDESC],
		--[PATENT],
		--[BRAND],
		--[BRANDDESC],
		--[HXW],
		--[SPACING],
		--[GROWTHRATE],
		--[BESTUSAGE],
		--[VARIETYBLOOMCOLOR],
		--[BLOOMTIME],
		--[SHORTFEATURE],
		--[SHORTFEATURE2],
		--[SHORTFEATURE3],
		--[SHORTFEATURE4],
		--[MOISTURE],
		--[PRUNINGTEXT],
		--[WATERINGTEXT],
		--[FERTILIZATIONTEXT],
		--IIF([WEBLISTING] IS NULL, 'NO', 'YES') AS WEBLISTING

/*
-- THIS IS WHAT I CAME UP WITH BEFORE JOANNE CREATED THE ABOVE VIEW USING LINKED SERVER DATA:
SELECT
ITM.RECORDTYPE,
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
TRIM(ITM.REFERENCE_2) + ' ' + ISNULL(ITM.USERDEFINEDREFERENCE_1,' ') AS BOTANICALNAME,
NULL AS CAREGUIDE,
ITM.REFERENCE_4 AS TAGDESCRIPTION,
ITM.REFERENCE_5 AS VARIETYSORT,
ITM.REFERENCE_1 AS COMMONNAME,
ITM.USERDEFINEDCODE_7 AS EXPOSURECODE,
XPO.DESCRIPTION_1 AS EXPOSUREDESC,
GEN.DESCRIPTION_1 AS GENUS,
NULL AS VARIETYNOTES,
ITM.USERDEFINEDCODE_18 AS HARDINESSZONE,
HAR.DESCRIPTION_1 AS HARDINESSZONEDESC,
NULL AS LANDSCAPEUSE,
'SOURCE' AS PLANTPHOTO,
LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUP,
PGC.DESCRIPTION AS PLANTGROUPDESC,
'SOURCE' AS PLANTINGGUIDE,
(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETY,
ITM.REFERENCE_3 AS REVERSECOMMONNAME,
ITM.USERDEFINEDCOMMENT_2 AS LONGDESCRIPTION,
ITM.USERDEFINEDREFERENCE_1 AS PATENT,
NULL AS BRAND,
NULL AS HXW,
NULL AS SPACING,
NULL AS GROWTHRATE,
NULL AS BESTUSAGE,
NULL AS VARIETYBLOOMCOLOR,
NULL AS BLOOMTIME,
NULL AS SHORTFEATURE,
NULL AS SHORTFEATURE2,
NULL AS SHORTFEATURE3,
NULL AS SHORTFEATURE4,
NULL AS MOISTURE,
NULL AS PRUNINGTEXT,
NULL AS WATERINGTEXT,
NULL AS FERTILIZINGTEXT,
ITM.USERDEFINEDCODE_20 AS WEBLISTING,
NULL AS ICONS
FROM IMITEM ITM (NOLOCK)
--JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
--LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
LEFT JOIN IMCODES XPO (NOLOCK) ON XPO.CODE = ITM.USERDEFINEDCODE_7 AND XPO.CODETYPE = '17'	--EXPOSUREDESCRIPTION
LEFT JOIN IMCODES HAR (NOLOCK) ON HAR.CODE = ITM.USERDEFINEDCODE_18 AND HAR.CODETYPE = 'C6'	--HARDINESSZONEDESCRIPTION
--WHERE WH.IDENTITYID < 'A'--IN ('10', '20', '40', '60')
*/
