/*
--YTDShippedByKeyRep-EXCEL
SELECT *
FROM VW_RPT_YTDSHIPPED_KEYREP (NOLOCK) 
WHERE COMPANYID = 'SB' 

441,863 records w/o keyreps -- 691,170 records with keyreps
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_YTDSHIPPED_KEYREP]
AS
SELECT 
	--KEYREP FIELDS--
	ISNULL(KREP.IDENTITYID,'') AS KEYREP,
	ISNULL(KREP.NAME,'') AS KEYREPNAME,
	VW.*
FROM VW_RPT_YTDSHIPPED VW (NOLOCK)
	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO THIS WILL CREATE DUPLICATE CUSTOMER RECORDS.
	LEFT JOIN IDRELATIONSHIPLINKS LKREP (NOLOCK) ON LKREP.R_IDMASTER = CUSTROWID AND LKREP.IDMEMBERTYPE = '14'
	LEFT JOIN IDMASTER KREP (NOLOCK) ON KREP.ROWID = LKREP.R_IDMEMBER 

