/*
--W/O RUNTIME 5:13 @135,146 ROWS	ELIMINATING TOO MANY RECORDS
--W/O RUNTIME 5:34 @139,575 ROWS	CORRECTED LOGIC

--ORDER TRACKING AVAILABILITY
SELECT * 
FROM VW_RPT_ORDER_TRACKING_AVAILIBILITY (NOLOCK) 
WHERE F1_iSUPPLY + S1_iSUPPLY + U1_iSUPPLY + U2_iSUPPLY + ISNULL(QTY_ON_ORDER,0) != 0 
--
AND WAREHOUSEID = '10'
ORDER BY WAREHOUSEID, GNC_ITEMSORT, SALESREPNAME 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_ORDER_TRACKING_AVAILIBILITY] 
AS 
SELECT 
	COMPANYID, COMPANYNAME, 
	NULLRECORD, 
	WAREHOUSEID, GNC_ITEMSORT, 
	ITEMCODE, COMMONNAME, 
	SALESREPID, SALESREPNAME, 
	CUSTOMERID, CUSTOMERNAME, 
	CONSIGNEEID, CONSIGNEENAME, 
	MAJORACCT, 
	LISTPRICE, 
	TRANSACTIONNUMBER, 
	RECORDTYPE, STAGE, STAGENAME, STEP, ITMSTATUS, 
	LOTCODE, 
	F1_iSUPPLY, F1_DEMAND, 
	IIF(F1_iSUPPLY < F1_DEMAND, 0, F1_iSUPPLY - F1_DEMAND) AS F1_iLTS,	--TURN NEGATIVE LTS INTO 0 PER LANDON - DT 02/19/24 
	S1_iSUPPLY, S1_DEMAND, 
	IIF(S1_iSUPPLY < S1_DEMAND, 0, S1_iSUPPLY - S1_DEMAND) AS S1_iLTS, 	--TURN NEGATIVE LTS INTO 0 PER LANDON - DT 02/19/24 
	U1_iSUPPLY, U1_DEMAND, 
	IIF(U1_iSUPPLY < U1_DEMAND, 0, U1_iSUPPLY - U1_DEMAND) AS U1_iLTS, 	--TURN NEGATIVE LTS INTO 0 PER LANDON - DT 02/19/24 
	U2_iSUPPLY, U2_DEMAND, 
	IIF(U2_iSUPPLY < U2_DEMAND, 0, U2_iSUPPLY - U2_DEMAND) AS U2_iLTS, 	--TURN NEGATIVE LTS INTO 0 PER LANDON - DT 02/19/24 
	QTY_ON_ORDER 
FROM (
		SELECT 
			COMPANYID, COMPANYNAME, 
			NULLRECORD, 
			WAREHOUSEID, GNC_ITEMSORT, 
			ITEMCODE, COMMONNAME, 
			SALESREPID, SALESREPNAME, 
			CUSTOMERID, CUSTOMERNAME, 
			CONSIGNEEID, CONSIGNEENAME, 
			MAJORACCT, 
			CAST (DBO.FN_LISTPRICE(ITMROWID,SHIPPINGDATE,NULL) AS MONEY) AS LISTPRICE, 
			TRANSACTIONNUMBER, 
			RECORDTYPE, STAGE, STAGENAME, STEP, ITMSTATUS, 
			LOTCODE, 
			DBO.FN_SUPPLYROLLUP(ITMROWID,NULL,'F1',NULL,'I') AS F1_iSUPPLY, 
			DBO.FN_DEMANDROLLUP(ITMROWID,NULL,'F1',NULL) AS F1_DEMAND, 
			DBO.FN_SUPPLYROLLUP(ITMROWID,NULL,'S1',NULL,'I') AS S1_iSUPPLY, 
			DBO.FN_DEMANDROLLUP(ITMROWID,NULL,'S1',NULL) AS S1_DEMAND, 
			DBO.FN_SUPPLYROLLUP(ITMROWID,NULL,'U1',NULL,'I') AS U1_iSUPPLY, 
			DBO.FN_DEMANDROLLUP(ITMROWID,NULL,'U1',NULL) AS U1_DEMAND, 
			DBO.FN_SUPPLYROLLUP(ITMROWID,NULL,'U2',NULL,'I') AS U2_iSUPPLY, 
			DBO.FN_DEMANDROLLUP(ITMROWID,NULL,'U2',NULL) AS U2_DEMAND, 
			IIF(STAGE IS NULL, NULL, CAST (QUANTITYATSTAGE AS INT)) AS QTY_ON_ORDER
		FROM (
				SELECT
				CO.COMPANYID, 
				CO.NAME AS COMPANYNAME, 
				'N' AS NULLRECORD, 
				ITM.ROWID AS ITMROWID, 
				OH.SHIPPINGDATE, 
				WH.IDENTITYID AS WAREHOUSEID, 
				TRIM(ITM.ITEMCODE) AS ITEMCODE, 
				ITM.REFERENCE_1 AS COMMONNAME, 
				PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,  
				PART.IDENTITYID AS SALESREPID, 
				PART.NAME AS SALESREPNAME, 
				CUST.IDENTITYID AS CUSTOMERID,	--ADD PER ERICA 8/8/24 - DT 
				CUST.NAME AS CUSTOMERNAME,		--ADD PER ERICA 8/8/24 - DT 
				CONS.IDENTITYID AS CONSIGNEEID, 
				CONS.NAME AS CONSIGNEENAME, 
				ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS MAJORACCT,	--ADD PER JD 3/14/24 - DT
				OH.TRANSACTIONNUMBER, 
				OH.RECORDTYPE, 
				OH.STAGE, 
				SUBSTRING(DBO.FN_STAGESORT(OH.STAGE,'OM'),4,18) AS STAGENAME, 
				OH.USERDEFINEDCODE_2 AS STEP, 
				ITM.STATUS AS ITMSTATUS, 
				LOT.LOTCODE, 
				IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QUANTITYATSTAGE 
				FROM OMTRANSACTIONHEADER OH (NOLOCK) 
				JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
				JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
				JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER --ADD PER JD 3/14/24 - DT
				JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
				JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1 
				JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
				JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
				JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT 
				JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
				JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
				JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
				WHERE OH.RECORDTYPE = 'R'				--ONLY OPEN ORDERS 
				AND OH.STAGE != 'L'					--IGNORE CANCELLED ORDERS 
				AND OH.USERDEFINEDCODE_2 IN ('RESERVE', 'SHIPPABLE', 'WAITING') 

				UNION ALL

				SELECT
				CO.COMPANYID, 
				CO.NAME AS COMPANYNAME, 
				'Y' AS NULLRECORD, 
				ITM.ROWID AS ITMROWID, 
				NULL AS SHIPPINGDATE, 
				WH.IDENTITYID AS WAREHOUSEID, 
				TRIM(ITM.ITEMCODE) AS ITEMCODE, 
				ITM.REFERENCE_1 AS COMMONNAME, 
				PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,  
				NULL AS SALESREPID, 
				NULL AS SALESREPNAME, 
				NULL AS CUSTOMERID, 
				NULL AS CUSTOMERNAME, 
				NULL AS CONSIGNEEID, 
				NULL AS CONSIGNEENAME, 
				NULL AS MAJORACCT, 
				NULL AS TRANSACTIONNUMBER, 
				NULL AS RECORDTYPE, 
				NULL AS STAGE, 
				NULL AS STAGENAME, 
				NULL AS STEP, 
				ITM.STATUS AS ITMSTATUS, 
				NULL AS LOTCODE, 
				NULL AS QUANTITYATSTAGE 
				FROM IMITEM ITM (NOLOCK) 
				JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
				JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
				JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
				JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
				WHERE ITM.STATUS = 'A'							--ONLY ACTIVE ITEMS
				AND WH.IDENTITYID IN ('10', '20', '40', '60')	--ONLY PRODUCTION WAREHOUSE ITEMS		
		) T	--DON'T CALCULATE LTS AND LISTPRICE UNTIL DATASET IS REDUCED AS MUCH AS POSSIBLE, FOR PERFORMANCE SAKE.
) X

--DO NOT INCLUDE IN THE VIEW:
--WHERE X.F1_iSUPPLY + X.S1_iSUPPLY + X.U1_iSUPPLY + X.U2_iSUPPLY + ISNULL(X.QTY_ON_ORDER,0) != 0	--IGNORE ANY ITEM WITHOUT LTS VALUES IN ANY OF THE FOUR SEASONS.
--AND X.WAREHOUSEID = '10' 

--LIST OF MISSING ITEMS EXPECTED TO BE INCLUDED:
--and x.itemcode in (
--'001699.050.1', '000744.020.1', '009401.031.1', '003311.070.2', '009086.250.1', 
--'003751.150.2', '003754.150.2', '003773.022.1', '006448.013.1', '002096.013.1', 
--'002050.030.1', '006264.030.1', '008673.030.1', '010607.020.1', '008516.011.1', 
--'002491.030.1', '000815.010.1', '007499.070.2', '005915.051.2', '010738.051.2', 
--'005919.051.2', '010656.051.1', '010344.051.2', '007501.051.2', '008103.051.1') 

----LIST OF ITEMS WITH OVERSELL%
--and x.itemcode in (
--'001884.011.1', '001337.031.1', '003085.030.1', '001929.031.1', '008027.051.1', 
--'003411.031.1', '004207.031.1', '004207.021.1', '006408.021.1', '006737.031.1', 
--'008866.031.1', '003311.030.1', '001530.030.1', '004320.010.1', '005273.031.1', 
--'006540.010.1', '006545.010.1', '006545.020.1', '006535.020.1', '006640.010.1', 
--'005667.051.1', '006905.010.1', '006905.020.1', '006940.010.1') 

--ORDER BY X.WAREHOUSEID, X.GNC_ITEMSORT, X.SALESREPNAME 
