---------------------------------------------------------------------------------------
--REMEMBER THAT THE PRE-EXISTING RECORDS HAVE ALREADY BEEN APPLIED TO SQL_1 IN ePLANT--
--FUTURE RECORDS AFTER GO-LIVE WILL NEED TO BE ADDED TO VW_RPT_SQL_TRENDS IN INSIGHT.--
---------------------------------------------------------------------------------------
--SELECT * FROM VW_RPT_SQL_ADJUSTMENTS (NOLOCK)
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_ADJUSTMENTS]
AS
--Adjustments
SELECT
LEFT(G.REPORTGROUPDESCRIPTION,1) AS REPORTGROUP,	--MIGHT NEED CAST TO INT
G.LINESORT AS REPORTLINE, 
G.REPORTLINEDESCRIPTION AS REPORTLINEDESC,
G.SALEYEAR, 
DBO.FN_PERIOD2SEASON(DBO.FN_DATE2PERIOD(CAST (G.TRANSACTIONDATE AS DATE))) AS SEASON, 
DBO.FN_DATE2PERIOD(CAST (G.TRANSACTIONDATE AS DATE)) AS PERIOD, 
DBO.FN_DATE2WEEK(CAST (G.TRANSACTIONDATE AS DATE)) AS WEEK, 
CAST (G.TRANSACTIONDATE AS DATE) AS TRANSACTIONDATE, 
G.DIVISIONNUMBER AS WAREHOUSEID, 
(SELECT NAME FROM IDMASTER (NOLOCK) WHERE IDENTITYID = TRIM(STR(G.DIVISIONNUMBER))) AS WAREHOUSENAME, 
'X' AS NATIONALACCOUNT,
'S00' AS SALESREPID,
'Adjustments' AS SALESREPNAME,
G.ADJUSTMENTTYPE AS CUSTOMERTYPE, 
G.REASON AS CUSTOMERTYPEDESC,	--MIGHT NEED TO FIND ACTUAL FIELD VALUE BASED UPON CUSTOMERTYPE (I DOUBT IT THOUGH)
0 AS CUSTOMERNUMBER, 
'X' AS CUSTOMERNAME, 
G.MONTH_THISYEAR AS AMOUNT
--G.MONTH_LASTYEAR
--G.YEAR_THISYEAR
--G.YEAR_LASTYEAR
FROM GNC_BILLING_SUM_ADJ G (NOLOCK)
WHERE G.STATUS = 'A' AND G.MONTH_THISYEAR <> 0

-----------------------------------------------------------
--THIS IS A COPY/PASTE FROM ePLANT/ORACLE VIEW: V_SQL_ADJ--
-----------------------------------------------------------
--CREATE OR REPLACE FORCE VIEW ROL.V_SQL_ADJ
--(REPORTGROUP, REPORTLINE, REPORTLINEDESC, SALEYEAR, DIVISIONNUMBER,
-- DIVISIONNAME, SALESREPIDCUST, SALESREPNAME, NATIONALACCOUNT, CUSTOMERTYPE,
-- CUSTOMERTYPEDESC, CUSTOMERNUMBER, CUSTOMERNAME, SYPERIOD, WEEK,
-- SEASON, TRANSACTIONDATE, MAJORACCTMGRCODE, MAJORACCTMGRDESC, AMOUNT)
--BEQUEATH DEFINER
--AS

--SELECT TO_NUMBER (REPORTGROUP) AS REPORTGROUP,
--       REPORTLINE,
--       (SELECT CODEDESCRIPTION
--          FROM CODE_ELEMENT
--         WHERE SORTSEQUENCE = REPORTLINE AND LISTID = 1094 AND STATUS = 'A')
--          AS REPORTLINEDESC,
--       SALEYEAR,
--       DIVISIONNUMBER,
--       (SELECT D.DIVISIONNAME
--          FROM DIVISION D
--         WHERE D.DIVISIONNUMBER = X.DIVISIONNUMBER)
--          AS DIVISIONNAME,
--       SALESREPIDCUST,
--       SALESREPNAME,
--       NATIONALACCOUNT,
--       CUSTOMERTYPE,
--       (SELECT SUBSTR (CE.CODEDESCRIPTION, 10, LENGTH (CE.CODEDESCRIPTION))
--          FROM CODE_ELEMENT CE
--         WHERE CE.CODE = CUSTOMERTYPE AND LISTID = 1009 AND STATUS = 'A')
--          AS CUSTOMERTYPEDESC,
--       CUSTOMERNUMBER,
--       CUSTOMERNAME,
--       SYPERIOD,
--       WEEK,
--       SEASON,
--       TRANSACTIONDATE,
--       MAJORACCTMGRCODE,
--       MAJORACCTMGRDESC,
--       AMOUNT
--  FROM (SELECT SUBSTR (REPORTGROUPDESCRIPTION, 1, 1) AS REPORTGROUP,
--               LINESORT AS REPORTLINE,
--               -- adjustmenttype AS x,
--               SALEYEAR,                                                --2010
--               DIVISIONNUMBER AS DIVISIONNUMBER,
--               0 AS SALESREPIDCUST,
--               'X' AS SALESREPNAME,
--               'X' AS NATIONALACCOUNT,
--               ADJUSTMENTTYPE AS CUSTOMERTYPE,
--               0 AS CUSTOMERNUMBER,
--               'X' AS CUSTOMERNAME,
--               FN_DATE2PERIOD (transactiondate) AS SYPERIOD,
--               FN_DATE2WEEK (transactiondate) AS WEEK,
--               FN_PERIOD2SEASON (FN_DATE2PERIOD (transactiondate)) AS SEASON,
--               TRANSACTIONDATE,
--               '' AS MAJORACCTMGRCODE,
--               '' AS MAJORACCTMGRDESC,
--               MONTH_THISYEAR AS AMOUNT
--          FROM BILLING_SUM_ADJ
--         WHERE     SALEYEAR = FN_GET_CURRENT_SALE_YEAR (SYSDATE) - 1
--               AND MONTH_THISYEAR <> 0 -- still look at THISYEAR amounts since looking at previous year records
--        UNION ALL
--        SELECT SUBSTR (REPORTGROUPDESCRIPTION, 1, 1) AS REPORTGROUP,
--               LINESORT AS REPORTLINE,
--               -- adjustmenttype AS x,
--               FN_GET_CURRENT_SALE_YEAR (SYSDATE) AS SALEYEAR,          --2011
--               DIVISIONNUMBER AS DIVISIONNUMBER,
--               0 AS SALESREPIDCUST,
--               'X' AS SALESREPNAME,
--               'X' AS NATIONALACCOUNT,
--               ADJUSTMENTTYPE AS CUSTOMERTYPE,
--               0 AS CUSTOMERNUMBER,
--               'X' AS CUSTOMERNAME,
--               FN_DATE2PERIOD (transactiondate) AS SYPERIOD,
--               FN_DATE2WEEK (transactiondate) AS WEEK,
--               FN_PERIOD2SEASON (FN_DATE2PERIOD (transactiondate)) AS SEASON,
--               TRANSACTIONDATE,
--               '',
--               '',
--               MONTH_THISYEAR AS AMOUNT
--          FROM BILLING_SUM_ADJ
--         WHERE     SALEYEAR = FN_GET_CURRENT_SALE_YEAR (SYSDATE)
--               AND MONTH_THISYEAR <> 0) X
