/*	TRIMMED
--83 Item Master EXCEL
SELECT
*
FROM VW_RPT_ITEM_MASTER (NOLOCK)
WHERE RECORDTYPE <> 'P'
and nextyr_listprice is not null
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_ITEM_MASTER]
AS
SELECT
ITM.RECORDTYPE,
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
TRIM(WH.IDENTITYID) AS WAREHOUSEID,
TRIM(WH.NAME) AS WAREHOUSENAME,
(SELECT TRIM(ITMDP.PROFILECODE) FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUP,
TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUPCODE,
TRIM(PGC.DESCRIPTION) AS PLANTGROUPDESC,
PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
TRIM(ITM.ITEMCODE) AS ITEMCODE,
ITM.ITEMTYPE,
ITM.ITEMSOURCEFLAG AS ITEMSOURCE,
(SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE TABLENAME = 'IMITEM' AND FIELDNAME = 'ITEMTYPE' AND FLAGVALUE = ITM.ITEMTYPE) AS ITEMTYPEDESC,
(SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE TABLENAME = 'IMITEM' AND FIELDNAME = 'ITEMSOURCEFLAG' AND FLAGVALUE = ITM.ITEMSOURCEFLAG) AS ITEMSOURCEDESC,
ITM.TAXSTATUS,
ITM.STATUS AS ITEMSTATUS,
TRIM(ITM.CLASSCODE) AS CONTSIZE, 
TRIM(ITM.SUBCLASSCODE) AS QUALITYCODE,

ITM.CREATIONDATETIME AS ITEMCREATIONDATE, 
ITM.CREATIONUSERID AS ITEMCREATIONUSER,
ITM.LASTUPDATEDATETIME AS ITEMLASTUPDATEDATE,
ITM.LASTUPDATEUSERID AS ITEMLASTUPDATEUSER,

ITM.REFERENCE_1 AS COMMONNAME,
TRIM(ITM.DESCRIPTION_1) AS SHORTCOMMONNAME,
ITM.REFERENCE_2 AS BOTANICALNAME,
TRIM(ITM.DESCRIPTION_2) AS ABBRBOTANICALNAME,
ITM.REFERENCE_3 AS REVERSECOMMONNAME,
ITM.REFERENCE_5 AS SORTNAMEVARIETY,
ITM.USERDEFINEDCODE_1 AS GENUSCODE,
GEN.DESCRIPTION_1 AS GENUSNAME,
ITM.USERDEFINEDCODE_18 AS HARDINESSZONE,
ITM.USERDEFINEDCODE_7 AS EXPOSURE,
ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
ITM.USERDEFINEDDATE_1 AS PATENTEXPIRES,
ITM.USERDEFINEDCODE_14 AS LEGALSTATUS,
ITM.USERDEFINEDDATE_2 AS LEGALDATE,
ITM.USERDEFINEDCODE_16 AS LIC_PRIMARY,	--I MAY NEED THE DESCRIPTION_1 FROM IMCODES?
ITM.USERDEFINEDCODE_17 AS LIC_SECONDARY,--I MAY NEED THE DESCRIPTION_1 FROM IMCODES?
ITM.USERDEFINEDREFERENCE_2 AS SUBLICENSABLE,
ITM.USERDEFINEDCODE_6 AS PROPDESC,
ITM.USERDEFINEDCODE_20 AS WEBLISTING,
CNT.CONTAINERCODE,
CNT.CONTAINERDESCRIPTION,
CNT.STATUS AS CONTAINERSTATUS,
CNT.PRINTEDCONTAINERCODE,
CNT.CONTAINERSORT,
CNT.SHIPPINGCLASSIFICATIONCODE,
CNT.FREIGHTCLASSCODE,
CNT.CLASSMINVOLUME,
ITM.USERDEFINEDCODE_2 AS BRAND,
ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
ITM.USERDEFINEDCODE_13 AS BRANDTAGREQ,
(SELECT TRIM(FH.MISCFEECODE) FROM IMFEESHEADER FH (NOLOCK) WHERE FH.ROWID = ITM.R_FEES) AS FEECODE,
ITM.SALEMAXQUANTITY AS MAXORDERQUANTITY,
ITM.ITEMSUPCCODE,
(SELECT TRIM(PCH.PRICECODE) FROM IMPRICECODESHEADER PCH (NOLOCK) WHERE PCH.ROWID = ITM.R_PRICETABLE) AS PRICECODE,
--ADDED FOR STEVE COPPEDGE 2/14/2022:
(	SELECT TOP 1 PCD.EFFECTIVEDATE FROM IMPRICECODESHEADER PCH (NOLOCK) 
	JOIN IMPRICECODESDETAIL PCD (NOLOCK) ON PCD.R_PRICECODEHEADER = PCH.ROWID 
	AND PCD.EFFECTIVEDATE <= GETDATE()
	WHERE PCH.ROWID = ITM.R_PRICETABLE
	ORDER BY PCD.EFFECTIVEDATE DESC
	) AS CURR_EFFECTIVEDATE, 
DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS CURR_LISTPRICE,
--DBO.FN_LISTPRICE(ITM.ROWID,NEXTYR.STARTDATE,NULL) AS NEXTYR_LISTPRICE,	-->WRONG METHOD
--PER STEVE COPPEDGE, NEXTYR_LISTPRICE MUST HAVE EFFECTIVEDATE GREATER THAN TODAY'S DATE:
--THIS IS A COPY OF THE GUTS OF FN_LISTPRICE() WITH REQUESTED MODIFICATIONS
(	SELECT ROUND(
	(	SELECT TOP 1 SUB.PRICELEVEL_A FROM IMPRICECODESSUBDETAIL SUB (NOLOCK)
		WHERE SUB.R_PRICECODEDETAIL = 
			(
			SELECT TOP 1 DTL.ROWID FROM IMPRICECODESDETAIL DTL (NOLOCK)
			WHERE DTL.R_PRICECODEHEADER = HDR.ROWID
			AND DTL.EFFECTIVEDATE > GETDATE()	-->MUST BE GREATER
			ORDER BY DTL.EFFECTIVEDATE DESC
			) 
	),4)
	FROM IMPRICECODESHEADER HDR (NOLOCK) WHERE HDR.ROWID = ITM.R_PRICETABLE
) AS NEXTYR_LISTPRICE,

--ADDED FOR STEVE COPPEDGE 2/14/2022:
(	SELECT TOP 1 PCD.EFFECTIVEDATE FROM IMPRICECODESHEADER PCH (NOLOCK) 
	JOIN IMPRICECODESDETAIL PCD (NOLOCK) ON PCD.R_PRICECODEHEADER = PCH.ROWID 
	AND PCD.EFFECTIVEDATE > GETDATE()
	WHERE PCH.ROWID = ITM.R_PRICETABLE
	ORDER BY PCD.EFFECTIVEDATE DESC
	) AS NEXTYR_EFFECTIVEDATE, 

--NEXTYR.STARTDATE AS NEXTYR_STARTDATE,	-->I DON'T THINK THIS FIELD IS NECESSARY ANYMORE.
ITM.ARTRADEDISCOUNTFLAG AS TRADEDISCOUNT, --AKA NETPRICED,
TRIM(ITM.SPECIFICATIONCODE) AS SPECIFICATIONCODE,
ITM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY,
ITM.USERDEFINEDCODE_19 AS WINGDINGUNITS,
ITM.USERDEFINEDCODE_8 AS FIELDTAGTYPE,
ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
ITM.USERDEFINEDQUANTITY_1 AS LARGEPTRQUANTITY,
ITM.USERDEFINEDCODE_11 AS GRADELABELCOLOR,
ITM.USERDEFINEDCODE_9 AS SHIPPROTECTION,
ITM.USERDEFINEDREFERENCE_3 AS INTERDIVPO,
ITM.PIECESPERUNITQUANTITY AS EQUIV_UNIT, 
ITM.PIECESPERUNITUOM AS EQUIV_UOM, 
ITM.UNITVOLUMEQUANTITY AS UNITVOLUME,
TRIM(ITM.UNITVOLUMEUOM) AS VOLUOM,
ITM.NETWEIGHTQUANTITY AS UNITWEIGHT,
TRIM(ITM.NETWEIGHTUOM) AS WTUOM,
(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE TABLENAME='IMITEM' 
	AND FIELDNAME='COSTBASISMETHODFLAG' AND FLAGVALUE=ITM.COSTBASISMETHODFLAG) AS COSTBASIS,
(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE TABLENAME='IMITEM' 
	AND FIELDNAME='ROUNDINGMETHOD' AND FLAGVALUE=ITM.ROUNDINGMETHOD) AS PRICEMETHOD,
ITM.ROUNDINGFACTOR AS PRICEFACTOR,
(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE TABLENAME='IMITEM' 
	AND FIELDNAME='PRICESOURCE' AND FLAGVALUE=ITM.PRICESOURCE) AS PRICESOURCE,
ITM.MINIMUMSALESQUANTITY AS MINSALEQTY,
ITM.SALEINCREMENTQUANTITY AS SALESMULTIPLE,
ITM.USERDEFINEDCOMMENT AS NOTES,
ITM.REFERENCE_4 AS TAGDESCRIPTION,
ITM.USERDEFINEDCOMMENT_2 AS LONGITEMDESCRIPTION
--Additional fields now removed
--WH.ROWID AS WAREHOUSE_ROWID,
--ITM.ROWID AS ITEM_ROWID,
--DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'F%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'F%',NULL) AS LTS_F,
--DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'S%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'S%',NULL) AS LTS_S,
--DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,'U%',NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,'U%',NULL) AS LTS_U,
--DBO.FN_SUPPLYROLLUP(ITM.ROWID,NULL,NULL,NULL,'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID,NULL,NULL,NULL) AS LTS_FSU,
/*
FROM (SELECT '08/01/'+STR(YEAR(DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(NULL)+1)),4) AS STARTDATE) NEXTYR, --ATTACH HARDCODED '8/1/'+NEXTSALEYEAR (USES FISCAL YEAR BEGIN DATE OF NEXT YEAR)
--CONSIDER USING REPORTYEAR CALENDAR ONLY IF EFFECTIVE DATES FOR LISTPRICING ALSO USES THE SAME CALENDAR APPROACH OR FIRST WEEK WILL RETURN WRONG DATA
--THIS BRINGS UP OTHER CONCERNS ABOUT INVOICING FIRST WEEK OF NEW YEAR THAT BEGINS BEFORE 8/1 STILL USING LASTYEAR PRICES SYSTEMWIDE.
--(SELECT DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(NULL)+1) AS STARTDATE) NEXTYR, --ATTACH NEXTYR.STARTDATE TO BE USED AS A FIELD INSIDE THIS VIEW (USES REPORTYEAR/PERIODWEEK CALENDAR)
*/
FROM 
IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
