/*
--38 CUSTOMER LISTING EXCEL
SELECT *
FROM VW_RPT_CUSTOMER_LISTING (NOLOCK)
WHERE RECORDTYPE <> 'P'
and customerid = '10040'--'10129'
--and mastercustomerid = 'MC10035'
*/
/*	testing Customer Listing by KeyRep EXCEL:
SELECT 
	CUST.RECORDTYPE,
	------------------------------
	--CUSTOMER FIELDS--
	(	SELECT MC.IDENTITYID FROM IDMASTER MC (NOLOCK) 
		WHERE MC.ROWID = DBO.FN_MASTERCUSTOMER(CUST.ROWID,NULL)
		) AS MASTERCUSTOMERID,
	TRIM(CUST.IDENTITYID) AS CUSTOMERID,
	TRIM(CUST.NAME) AS CUSTOMERNAME,
	TRIM(CUST.IDGROUP) AS CUSTOMERGROUP,
	--KEYREP FIELDS--
	ISNULL(KREP.IDENTITYID,'') AS KEYREP,
	ISNULL(KREP.NAME,'') AS KEYREPNAME
FROM IDMASTER AS CUST (NOLOCK)
	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO THIS WILL CREATE DUPLICATE CUSTOMER RECORDS.
	LEFT JOIN IDRELATIONSHIPLINKS LKREP (NOLOCK) ON LKREP.R_IDMASTER = CUST.ROWID AND LKREP.IDMEMBERTYPE = '14'
	LEFT JOIN IDMASTER KREP (NOLOCK) ON KREP.ROWID = LKREP.R_IDMEMBER 
WHERE CUST.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_CUSTOMER_LISTING]
AS
SELECT 
	CUST.ROWID AS CUSTROWID, 
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	CUST.RECORDTYPE,
	------------------------------
	--IDENTITY FIELDS--
	(	SELECT MC.IDENTITYID FROM IDMASTER MC (NOLOCK)
		WHERE MC.ROWID = DBO.FN_MASTERCUSTOMER(CUST.ROWID,NULL)
		) AS MASTERCUSTOMERID,
	TRIM(CUST.IDENTITYID) AS CUSTOMERID,
	TRIM(CUST.NAME) AS CUSTOMERNAME,
	TRIM(CUST.IDGROUP) AS CUSTOMERGROUP,
	GRP.DESCRIPTION_1 AS CUSTOMERGROUPNAME,
	ADDR.ADDRESS_1 AS CUSTOMERADDRESS_1,
	ADDR.ADDRESS_2 AS CUSTOMERADDRESS_2,
	TRIM(ADDR.CITY) AS CUSTOMERCITY,
	TRIM(ADDR.STATE) AS CUSTOMERSTATE,
	ADDR.ZIP AS CUSTOMERZIP,
	ADDR.COUNTY AS CUSTOMERCOUNTY,
	ADDR.COUNTRY AS CUSTOMERCOUNTRY,
	TRIM(CRMGR.IDENTITYID) AS CREDITMANAGERID, 
	TRIM(CRMGR.NAME) AS CREDITMANAGERNAME,
	--CUSTOMER FIELDS--
	ICUST.STATUS AS CUSTOMERSTATUS,
	CUST.REFERENCE2 AS SORTNAME,--VARIETY
	ICUST.OMREQUIREPO AS REQUIREPO,
	ICUST.USERDEFINEDCODE_7 AS EDIWOREQUIRED,
	ICUST.USERDEFINEDCODE_10 AS TOP10,
	ICUST.USERDEFINEDREFERENCE_3 AS MAILINGS,
	ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS MAJORACCT,
	ICUST.OMSENDEMAIL AS AUTOEMAIL_INV,
	(	SELECT COMMENT FROM IDSYNONYMS SYN (NOLOCK) 
		WHERE SYN.R_IDENTITY=CUST.ROWID AND SYN.USERDEFINEDCODE_1='INV'
		) AS SYNINVOICEEMAIL,
	TRIM(IDTERMS.TERMSCODE) AS TERMSCODE,
	IDTERMS.DESCRIPTION_1 AS TERMSDESCRIPTION,
	ICUST.USERDEFINEDREFERENCE_6 AS DELAYED_DUE_1, 
	ICUST.USERDEFINEDREFERENCE_7 AS DELAYED_DUE_2, 
	ICUST.RESALENUMBER AS TAX_EXEMPT_#,
	ICUST.USERDEFINEDDATE_2 AS TAX_EXEMPT_DATE,
	ICUST.USERDEFINEDCODE_11 AS COMBINE_FOR_VIP,
	ICUST.CUSTOMERPURCHASEDISCOUNT, 
	(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME = 'IDCUSTOMER' AND FIELDNAME = 'DISCOUNTTYPE' AND FLAGVALUE = ICUST.DISCOUNTTYPE
		) AS DISCOUNT_APPLIES,--GETTING DESCRIPTION FROM CODE
	ICUST.USERDEFINEDCODE_1 AS DISCOUNTTYPE,
	ICUST.USERDEFINEDCODE_5 AS MAJORCOMMTYPE,
	ICUST.USERDEFINEDCODE_6 AS GROUPAPPROVALREQUIRED,
	ISNULL(ICUST.USERDEFINEDCODE_9, 'N') AS EDICUSTOMER,
	ICUST.USERDEFINEDCODE_3 AS EDIROLLUP,
	ICUST.USERDEFINEDCODE_12 AS ACKVERSION,
	ICUST.USERDEFINEDCODE_13 AS DELVERSION,
	ICUST.USERDEFINEDCODE_14 AS INVVERSION,
	ACKVERSION.CODE AS ACKVERSIONCODE, ACKVERSION.DESCRIPTION_1 AS ACKVERSIONDESC, ACKVERSION.DESCRIPTION_2 AS ACKVERSIONSORT,
	DELVERSION.CODE AS DELVERSIONCODE, DELVERSION.DESCRIPTION_1 AS DELVERSIONDESC, DELVERSION.DESCRIPTION_2 AS DELVERSIONSORT,
	INVVERSION.CODE AS INVVERSIONCODE, INVVERSION.DESCRIPTION_1 AS INVVERSIONDESC, INVVERSION.DESCRIPTION_2 AS INVVERSIONSORT,
	(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME='IDCUSTOMER' AND FIELDNAME='CREDITSTATUSFLAG' AND FLAGVALUE=ICUST.CREDITSTATUSFLAG
		) AS CREDITSTATUS,
	ICUST.CREDITRATING,
	ICUST.CREDITLIMIT,

	ICUST.COMMENT AS CUST_NOTES,
	ICUST.CREDITCOMMENT AS CUST_CREDIT_NOTES,
	ICUST.USERDEFINEDCODE_4 AS SENDSTATEMENTS,

	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO IT IS NOT INCLUDED IN THE DATASET.
	--(	SELECT KREP.IDENTITYID 
	--	FROM IDRELATIONSHIPLINKS LKREP (NOLOCK)
	--	JOIN IDMASTER KREP ON KREP.ROWID = LKREP.R_IDMEMBER 
	--	WHERE LKREP.R_IDMASTER = CUST.ROWID 
	--	AND LKREP.IDMEMBERTYPE = '14'
	--) AS KEYREP,
	--(	SELECT KREP.NAME 
	--	FROM IDRELATIONSHIPLINKS LKREP (NOLOCK) 
	--	JOIN IDMASTER KREP ON KREP.ROWID = LKREP.R_IDMEMBER 
	--	WHERE LKREP.R_IDMASTER = CUST.ROWID 
	--	AND LKREP.IDMEMBERTYPE = '14'
	--) AS KEYREPNAME,

	--ALL CONTACT FIELDS BY CONTACT TYPE:
	TRIM(C1CONT.IDENTITYID) AS PRIMARYCONTACTID, 
	TRIM(C1CONT.NAME) AS PRIMARYCONTACTNAME, 
	C1ADDR.TELEPHONE_1 AS PRIMARYCONTACTPHONE, 
	C1ADDR.CELLPHONE_1 AS PRIMARYCONTACTCELL, 
	C1ADDR.FAX_1 AS PRIMARYCONTACTFAX, 
	C1ADDR.EMAILADDRESS_1 AS PRIMARYCONTACTEMAIL, 
	TRIM(C2CONT.IDENTITYID) AS SECONDARYCONTACTID, 
	TRIM(C2CONT.NAME) AS SECONDARYCONTACTNAME, 
	C2ADDR.TELEPHONE_1 AS SECONDARYCONTACTPHONE, 
	C2ADDR.CELLPHONE_1 AS SECONDARYCONTACTCELL, 
	C2ADDR.FAX_1 AS SECONDARYCONTACTFAX, 
	C2ADDR.EMAILADDRESS_1 AS SECONDARYCONTACTEMAIL, 
	TRIM(C3CONT.IDENTITYID) AS PRINCIPALCONTACTID, 
	TRIM(C3CONT.NAME) AS PRINCIPALCONTACTNAME, 
	C3ADDR.TELEPHONE_1 AS PRINCIPALCONTACTPHONE, 
	C3ADDR.CELLPHONE_1 AS PRINCIPALCONTACTCELL, 
	C3ADDR.FAX_1 AS PRINCIPALCONTACTFAX, 
	C3ADDR.EMAILADDRESS_1 AS PRINCIPALCONTACTEMAIL, 
	TRIM(C4CONT.IDENTITYID) AS BILLINGCONTACTID, 
	TRIM(C4CONT.NAME) AS BILLINGCONTACTNAME, 
	C4ADDR.TELEPHONE_1 AS BILLINGCONTACTPHONE, 
	C4ADDR.CELLPHONE_1 AS BILLINGCONTACTCELL, 
	C4ADDR.FAX_1 AS BILLINGCONTACTFAX, 
	C4ADDR.EMAILADDRESS_1 AS BILLINGCONTACTEMAIL--, 
----I DON'T HAVE ACCESS TO CONSIGNEE SO I'LL RETURN CUSTOMER C5 CONTACTS WHICH SHOULDN'T EXIST:
	--TRIM(C5CONT.IDENTITYID) AS SHIPPINGCONTACTID, 
	--TRIM(C5CONT.NAME) AS SHIPPINGCONTACTNAME, 
	--C5ADDR.TELEPHONE_1 AS SHIPPINGCONTACTPHONE, 
	--C5ADDR.CELLPHONE_1 AS SHIPPINGCONTACTCELL, 
	--C5ADDR.FAX_1 AS SHIPPINGCONTACTFAX, 
	--C5ADDR.EMAILADDRESS_1 AS SHIPPINGCONTACTEMAIL--, 
	----CONTACT FIELDS--	(C1 FOR CUSTOMERS):
	--TRIM(CCONT.IDENTITYID) AS CONTACTID,
	--TRIM(CCONT.NAME) AS CONTACTNAME,
	--ICONT.USERDEFINEDCODE_1 AS CONTACTROLE,
	--ACONT.ADDRESS_1 AS CONTACTADDRESS_1,
	--ACONT.ADDRESS_2 AS CONTACTADDRESS_2,
	--TRIM(ACONT.CITY) AS CONTACTCITY,
	--TRIM(ACONT.STATE) AS CONTACTSTATE,
	--ACONT.ZIP AS CONTACTZIP,
	--ACONT.COUNTRY AS CONTACTCOUNTRY,
	--ACONT.TELEPHONE_1 AS CONTACTTELEPHONE_1,
	--ACONT.CELLPHONE_1 AS CONTACTCELLPHONE_1,
	--ACONT.FAX_1 AS CONTACTFAX_1,
	--ACONT.EMAILADDRESS_1 AS CONTACTEMAILADDRESS_1

FROM IDMASTER AS CUST (NOLOCK)
LEFT JOIN IDTYPESLINKS TCUST (NOLOCK) ON TCUST.R_IDENTITY = CUST.ROWID AND TCUST.IDTYPE = '01'
LEFT JOIN IDADDRESS ADDR (NOLOCK) ON ADDR.ROWID = ISNULL(TCUST.R_ADDRESS, CUST.R_DEFAULTADDRESS)
LEFT JOIN IDMASTER CRMGR (NOLOCK) ON CRMGR.ROWID = CUST.R_CONTACT
LEFT JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'	--CUSTOMERGROUPNAME
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = CUST.COMPANYID
--CUSTOMER RECORDS: 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
LEFT JOIN IDTERMS (NOLOCK) ON IDTERMS.ROWID = ICUST.R_TERMS
LEFT JOIN IDCODES ACKVERSION (NOLOCK) ON ACKVERSION.CODE = ICUST.USERDEFINEDCODE_12 AND ACKVERSION.CODETYPE = '3C'
LEFT JOIN IDCODES DELVERSION (NOLOCK) ON DELVERSION.CODE = ICUST.USERDEFINEDCODE_13 AND DELVERSION.CODETYPE = '3D'
LEFT JOIN IDCODES INVVERSION (NOLOCK) ON INVVERSION.CODE = ICUST.USERDEFINEDCODE_14 AND INVVERSION.CODETYPE = '3E'
----CUSTOMER CONTACTS	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
--LEFT JOIN IDMASTER CCONT (NOLOCK) ON CCONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
--LEFT JOIN IDCONTACTS ICONT (NOLOCK) ON ICONT.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
--LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
--ALL CONTACTS BY CONTACT TYPE:	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
LEFT JOIN IDMASTER C1CONT (NOLOCK) ON C1CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
LEFT JOIN IDADDRESS C1ADDR (NOLOCK) ON C1ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
LEFT JOIN IDMASTER C2CONT (NOLOCK) ON C2CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C2')
LEFT JOIN IDADDRESS C2ADDR (NOLOCK) ON C2ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C2')
LEFT JOIN IDMASTER C3CONT (NOLOCK) ON C3CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C3')
LEFT JOIN IDADDRESS C3ADDR (NOLOCK) ON C3ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C3')
LEFT JOIN IDMASTER C4CONT (NOLOCK) ON C4CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C4')
LEFT JOIN IDADDRESS C4ADDR (NOLOCK) ON C4ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C4')
----I DON'T HAVE ACCESS TO CONSIGNEE SO I'LL RETURN CUSTOMER C5 CONTACTS WHICH SHOULDN'T EXIST:
--LEFT JOIN IDMASTER C5CONT (NOLOCK) ON C5CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C5')
--LEFT JOIN IDADDRESS C5ADDR (NOLOCK) ON C5ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C5')

WHERE CUST.RECORDTYPE <> 'P'


