/*
--71 Inventory Status - Quantity	RUNTIME 0:44
SELECT *
FROM VW_RPT_INVENTORY_STATUS_QUANTITY (NOLOCK)
WHERE BUCKETTOTAL <> 0

ORDER BY WAREHOUSEID, PLANTGROUP, SORTNAME, CONTAINERSORT, QUALITY
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVENTORY_STATUS_QUANTITY]
AS
SELECT	--NEW RUNTIME 0:44
	X.*,
	CS_SUPPLY+CS_DEMAND+U2_SUPPLY+FSU_SUPPLY+FSU_DEMAND AS BUCKETTOTAL,	--SUPPRESS IF ALL BUCKETS ARE ZERO
	X.CS_SUPPLY - X.FSU_DEMAND AS SHORT_SUPPLY,							--CURRENT SUPPLY SHORTFALL FOR REST OF YEAR DEMAND
	X.FSU_SUPPLY - X.CS_SUPPLY - X.U2_SUPPLY AS GAP_SUPPLY,				--ADDITIONAL SUPPLY AVAILABLE BETWEEN CURRENT SEASON AND U2 SEASON
	IIF(X.CURSEA='U2', NULL, X.U2_SUPPLY) AS SHOWU2_SUPPLY,				--U2 SUPPLY (SUPPRESS WHEN CURRENT SEASON IS U2)
	X.FSU_SUPPLY - X.FSU_DEMAND AS A_LTS,								--FSU LTS
	X.LISTPRICE * (X.FSU_SUPPLY - X.FSU_DEMAND) AS EXT_A_LTS			--EXTENDED FSU LTS
FROM	(
		SELECT
			CO.COMPANYID,
			CO.NAME AS COMPANYNAME,
			ITM.RECORDTYPE,
			WH.IDENTITYID AS WAREHOUSEID, 
			WH.NAME AS WAREHOUSENAME,
			LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE,
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
			ITM.REFERENCE_5 AS SORTNAME,--VARIETY,
			CNT.CONTAINERSORT,
			ITM.SUBCLASSCODE AS QUALITY,
			ITM.ITEMCODE,
			CNT.PRINTEDCONTAINERCODE AS CONTSIZE,
			ITM.REFERENCE_1 AS COMMONNAME,
			ITM.USERDEFINEDCODE_2 AS BRAND,
			ITM.USERDEFINEDCODE_18 AS HZ,
			SUBSTRING(SEA.SEASONCODE,7,2) AS CURSEA,
			LEFT(SEA.SEASONCODE,2) AS CURYR,
			DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
			DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(SEA.SEASONCODE,2), SUBSTRING(SEA.SEASONCODE,7,2), NULL, NULL) AS CS_SUPPLY,	--CURRENT SEASON SUPPLY
			DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(SEA.SEASONCODE,2), SUBSTRING(SEA.SEASONCODE,7,2), NULL) AS CS_DEMAND,		--CURRENT SEASON DEMAND
			DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(SEA.SEASONCODE,2), 'U2%', NULL, NULL) AS U2_SUPPLY,							--U2 SUPPLY
			DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(SEA.SEASONCODE,2), NULL, NULL, NULL) AS FSU_SUPPLY,							--FSU SUPPLY
			DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(SEA.SEASONCODE,2), NULL, NULL) AS FSU_DEMAND								--FSU DEMAND
		FROM IMITEM ITM (NOLOCK)
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
			JOIN IMSEASONCODE SEA (NOLOCK) ON SUBSTRING(SEA.SEASONCODE,4,2) = WH.IDENTITYID
			AND GETDATE() BETWEEN SEA.STARTDATE AND SEA.ENDDATE
		WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID < '999'
		) X
