/*
--EDI CUSTOMER SETUP REPORT
SELECT * 
FROM VW_RPT_EDI_CUSTOMER_SETUP (NOLOCK) 
--WHERE RECORDTYPE <> 'P' 
WHERE STATUS = 'A' 
ORDER BY ISTRADINGPARTNER DESC, GROUPSORT, IDSORT
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_EDI_CUSTOMER_SETUP]
AS
SELECT 
	CUST.RECORDTYPE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	(SELECT EDI.VENDOR FROM GNC_EDI_TRANSLATION EDI (NOLOCK) WHERE EDI.WAREHOUSEID = '10' AND EDI.IDGROUP = CUST.IDGROUP) AS WH10,
	(SELECT EDI.VENDOR FROM GNC_EDI_TRANSLATION EDI (NOLOCK) WHERE EDI.WAREHOUSEID = '20' AND EDI.IDGROUP = CUST.IDGROUP) AS WH20,
	(SELECT EDI.VENDOR FROM GNC_EDI_TRANSLATION EDI (NOLOCK) WHERE EDI.WAREHOUSEID = '40' AND EDI.IDGROUP = CUST.IDGROUP) AS WH40,
	(SELECT EDI.VENDOR FROM GNC_EDI_TRANSLATION EDI (NOLOCK) WHERE EDI.WAREHOUSEID = '99' AND EDI.IDGROUP = CUST.IDGROUP) AS WH99,
	IIF(LEFT(CUST.IDENTITYID,2)='MC','MC','') AS MC,
	TRIM(REPLACE(CUST.IDENTITYID,'MC','')) AS IDSORT,
	RIGHT('0000'+TRIM(CUST.IDGROUP),4) AS GROUPSORT,
	TRIM(CUST.IDENTITYID) AS CUSTOMERID, 
	TRIM(ISNULL(NULLIF(TRIM(CUST.NAME),''),'['+TRIM(CUST.REFERENCE2)+']')) AS CUSTOMERNAME, 
	TRIM(CUST.IDGROUP) AS IDGROUP, 
	ICUST.STATUS, 
	IIF(REPLACE(CUST.IDENTITYID,'MC','') LIKE '10%' 
		AND CUST.IDGROUP IS NOT NULL
		AND ICUST.STATUS = 'A'
		, 'Y', NULL) AS ISTRADINGPARTNER,
	IIF(LINK.IDTYPE='18','Y',NULL) AS ISSVCPROVIDER,
	ICUST.USERDEFINEDCODE_9 AS EDI_CUST, 
	VEND.IDENTITYID AS VENDORID,
	TRIM(VEND.IDSUBGROUP) AS IDSUBGROUP, 
	SUBSTRING(SVP.CONNECTIONDATA, PATINDEX('%MAILBOX=%', SVP.CONNECTIONDATA) + 8, PATINDEX('%MAILBOXLABEL=%', SVP.CONNECTIONDATA) - (PATINDEX('%MAILBOX=%', SVP.CONNECTIONDATA) + 9)) AS OUTBOXTEXT, 
	SUBSTRING(SVP.CONNECTIONDATA, PATINDEX('%TPINBOX=%', SVP.CONNECTIONDATA) + 8, PATINDEX('%TPINBOXLABEL=%', SVP.CONNECTIONDATA) - (PATINDEX('%TPINBOX=%', SVP.CONNECTIONDATA) + 9)) AS INBOXTEXT, 
	(SELECT COUNT(*) FROM IDMASTER CUSTC (NOLOCK) 
		JOIN IDCUSTOMER ICUSTC (NOLOCK) ON ICUSTC.R_IDENTITY = CUSTC.ROWID
		WHERE CUSTC.IDGROUP = CUST.IDGROUP) AS EDIGROUPCUSTOMERS,
	(SELECT COUNT(*) FROM IDMASTER CUSTC (NOLOCK) 
		WHERE CUSTC.IDGROUP = CUST.IDGROUP) AS EDIGROUPMEMBERS,
	--ISNULL(CUST.REFERENCE2, '['+TRIM(CUST.NAME)+']') AS REFERENCE2, 
	ICUST.USERDEFINEDCODE_3 AS EDI_ROLLUP, 
	ICUST.OMREQUIREPO,
	ICUST.USERDEFINEDCODE_7 AS WO#_REQUIRED, 
	ICUST.USERDEFINEDREFERENCE_14 AS WO#_1, 
	ICUST.USERDEFINEDREFERENCE_15 AS WO#_2, 
	ICUST.USERDEFINEDREFERENCE_16 AS WO#_3, 
	ICUST.USERDEFINEDREFERENCE_17 AS WO#_4
FROM IDMASTER CUST (NOLOCK)
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)
LEFT JOIN IDTYPESLINKS LINK (NOLOCK) ON LINK.IDTYPE = '18' AND LINK.R_IDENTITY = VEND.ROWID
LEFT JOIN COSERVICEPROVIDERS SVP (NOLOCK) ON SVP.R_IDENTITY = VEND.ROWID 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = CUST.COMPANYID
WHERE CUST.RECORDTYPE != 'P'
AND (ICUST.USERDEFINEDCODE_9 = 'Y' OR LEFT(VEND.IDENTITYID,3) = 'EDI')