/*	I DON'T THINK ANY REPORT USES THIS VIEW MIGHT BE USING ARGOS VIEWS: VW_DAILYSHIPPINGSHEDULEDETAILVIEW/VW_DAILYSHIPPINGSCHEDULEEXCELVIEW INSTEAD
This IS BEING USED by Daily Shipping Schedule reports.
--DAILY SHIPPING SCHEDULE (42, 43, 221?)
SELECT
*
FROM VW_RPT_DAILYSHIPSCHED (NOLOCK)
WHERE VW_RPT_DAILYSHIPSCHED.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_DAILYSHIPSCHED]
AS
SELECT X.* 
FROM (	--THIS IS THE DATASET FOR THE MAIN REPORT.
		SELECT 
		1 AS DATASET, NULL AS DATASORT,
		CO.COMPANYID,
		CO.NAME AS COMPANYNAME,
		HDR.RECORDTYPE,
		HDR.TRIPNO,
		HDR.PLANSTART, CAST (HDR.PLANSTART AS DATE) AS DATESORT, 
		HDR.ACTUALSTART,
		HDR.PLANFINISH,
		HDR.ACTUALFINISH,
		DO.TRACKINGNUMBER,
		HDR.STATUS,
		AB.FLAGDESCRIPTION AS STATUSDESCRIPTION,
		HDR.USERDEFINEDCODE_2 AS DOCKNUMBER,
		DTL.DELSTOPNO,
		VCONS.CONSIGNEEIDENTITYID,
		VCONS.CONSIGNEENAME,
		ISNULL(DO.WEIGHTORDERED,0) AS WEIGHTORDERED,
		ISNULL(DO.CUBESORDERED,0) AS VOLUME,
		VCONS.CONSIGNEECITY,
		VCONS.CONSIGNEESTATE,
		HDR.EQUIPMENT,
		CARR.IDENTITYID AS CARRIERCODE,
		CARR.NAME AS CARRIERNAME,
		PART.NAME SALESPERSONNAME,
		PART.IDENTITYID SALESPERSONCODE,
		OH.COMMENT AS ORDERSHIPPINGINSTR,
		HDR.COMMENT AS TRIPNOTE,
		VCONS.CONSIGNEECOMMENT,
		VCONS.CONSIGNEEMASTERCOMMENT,
		WH.IDENTITYID AS SHIPPERCODE,
		ICONS.USERDEFINEDCODE_11 AS QACODE,
		CASE WH.IDENTITYID
			WHEN 10 THEN ICONS.USERDEFINEDREFERENCE_8
			WHEN 20 THEN ICONS.USERDEFINEDREFERENCE_9
			WHEN 40 THEN ICONS.USERDEFINEDREFERENCE_10
			WHEN 60 THEN ICONS.USERDEFINEDREFERENCE_11
			ELSE NULL
		END AS LOADINSTRUCTIONS, 
		VCONS.CONSIGNEEUSERDEFINEDREF_7 AS CONSIGNEESHIPNOTE,
		VCONS.CONSIGNEEDIRECTIONS AS DRIVERDIRECTIONS, 
--		STOPNOTE Change:
--		DTL.COMMENT AS STOPNOTES,
		ISNULL(TRIM(SUBSTRING(DTL.COMMENT,1,50)),'') + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') AS STOPNOTES, 
		FORMAT((SELECT ISNULL(SUM(ISNULL(OD2.AMOUNT,0)),0) 
				FROM OMTRANSACTIONDETAIL OD2 (NOLOCK)
				WHERE OD2.R_TRANSACTIONHEADER=OH.ROWID),'0.00') AS ESTIMATEDLOADVALUES,
		FORMAT((SELECT ISNULL(SUM(ISNULL(FRT.AMOUNT,0)),0) 
				FROM OMFREIGHT FRT (NOLOCK)
				WHERE FRT.R_TRANSACTIONHEADER=OH.ROWID),'0.00') AS ESTIMATEDFREIGHTREVENUE
		FROM FMTRIPHEADER HDR (NOLOCK)
		LEFT JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
		LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID= DTL.R_FMDISPATCHOBJECT 
		LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=DO.R_SOURCEID
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY=DO.R_CONSIGNEE
		LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
		LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
		LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER
		LEFT JOIN ABFLAGFIELD AB (NOLOCK) ON AB.FLAGVALUE = HDR.STATUS AND AB.TABLENAME = 'FMTRIPHEADER' AND AB.FIELDNAME = 'STATUS'

	UNION ALL

		--THIS IS THE DATASET TO FEED THE SUB-REPORT AT BOTTOM OF PAGE.
		SELECT 
		2 AS DATASET, HDR.EQUIPMENT AS DATASORT,
		CO.COMPANYID,
		CO.NAME AS COMPANYNAME,
		HDR.RECORDTYPE,
		HDR.TRIPNO,
		HDR.PLANSTART, CAST (HDR.PLANSTART AS DATE) AS DATESORT, 
		HDR.ACTUALSTART,
		HDR.PLANFINISH,
		HDR.ACTUALFINISH,
		DO.TRACKINGNUMBER,
		HDR.STATUS,
		AB.FLAGDESCRIPTION AS STATUSDESCRIPTION,
		HDR.USERDEFINEDCODE_2 AS DOCKNUMBER,
		DTL.DELSTOPNO,
		VCONS.CONSIGNEEIDENTITYID,
		VCONS.CONSIGNEENAME,
		ISNULL(DO.WEIGHTORDERED,0) AS WEIGHTORDERED,
		ISNULL(DO.CUBESORDERED,0) AS VOLUME,
		VCONS.CONSIGNEECITY,
		VCONS.CONSIGNEESTATE,
		HDR.EQUIPMENT,
		CARR.IDENTITYID AS CARRIERCODE,
		CARR.NAME AS CARRIERNAME,
		PART.NAME SALESPERSONNAME,
		PART.IDENTITYID SALESPERSONCODE,
		OH.COMMENT AS ORDERSHIPPINGINSTR,
		HDR.COMMENT AS TRIPNOTE,
		VCONS.CONSIGNEECOMMENT,
		VCONS.CONSIGNEEMASTERCOMMENT,
		WH.IDENTITYID AS SHIPPERCODE,
		ICONS.USERDEFINEDCODE_11 AS QACODE,
		CASE WH.IDENTITYID
			WHEN 10 THEN ICONS.USERDEFINEDREFERENCE_8
			WHEN 20 THEN ICONS.USERDEFINEDREFERENCE_9
			WHEN 40 THEN ICONS.USERDEFINEDREFERENCE_10
			WHEN 60 THEN ICONS.USERDEFINEDREFERENCE_11
			ELSE NULL
		END AS LOADINTSTRUCTIONS,
		VCONS.CONSIGNEEUSERDEFINEDREF_7 AS CONSIGNEESHIPNOTE,
		VCONS.CONSIGNEEDIRECTIONS AS DRIVERDIRECTIONS, 
--		STOPNOTE Change:
--		DTL.COMMENT AS STOPNOTES,
		ISNULL(TRIM(SUBSTRING(DTL.COMMENT,1,50)),'') + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') AS STOPNOTES, 
		FORMAT((SELECT ISNULL(SUM(ISNULL(OD2.AMOUNT,0)),0) 
				FROM OMTRANSACTIONDETAIL OD2 (NOLOCK)
				WHERE OD2.R_TRANSACTIONHEADER=OH.ROWID),'0.00') AS ESTIMATEDLOADVALUES,
		FORMAT((SELECT ISNULL(SUM(ISNULL(FRT.AMOUNT,0)),0) 
				FROM OMFREIGHT FRT (NOLOCK)
				WHERE FRT.R_TRANSACTIONHEADER=OH.ROWID),'0.00') AS ESTIMATEDFREIGHTREVENUE
		FROM FMTRIPHEADER HDR (NOLOCK)
		LEFT JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
		LEFT JOIN FMDISPATCHOBJECT DO (NOLOCK) ON DO.ROWID= DTL.R_FMDISPATCHOBJECT 
		LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID=DO.R_SOURCEID
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY=DO.R_CONSIGNEE
		LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = DO.R_CONSIGNEE
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
		LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
		LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = DO.R_SHIPPER 
		LEFT JOIN ABFLAGFIELD AB (NOLOCK) ON AB.FLAGVALUE = HDR.STATUS AND AB.TABLENAME = 'FMTRIPHEADER' AND AB.FIELDNAME = 'STATUS'
) X
WHERE X.RECORDTYPE <> 'P'
