/*
--PO RECEIPT BY ITEM
SELECT * 
FROM VW_RPT_PORECEIPT (NOLOCK) 
WHERE RECORDTYPE <> 'P' 
ORDER BY PONUMBER, KEYSEQUENCE, INVOICENUMBER

WHEN COMPLETED, REMOVE VW_IPORDERREPRINTVIEW AND PO RECEIPT REPORT

*/
CREATE OR ALTER VIEW [dbo].[VW_RPT_PORECEIPT]
AS
SELECT 
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	RH.RECORDTYPE,
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
	--HEADER FIELDS:
	--ROW 1:
	TRIM(SHIPTO.IDENTITYID)  AS DIVISION,
	TRIM(SHIPTO.NAME) AS DIVISIONNAME,
	TRIM(VENDOR.IDENTITYID)  AS SHIPPINGDIVISION,
	TRIM(VENDOR.NAME) AS SHIPPINGDIVISIONNAME,
	(	SELECT RHDP.PROFILECODE 
		FROM PORECEIPTSHEADERDP RHDP (NOLOCK) 
		WHERE RHDP.ROWID = RH.R_PROFILE
		) AS PROFILECODE,
	RH.USERDEFINEDCODE_6 AS PREPOST,
	RH.USERDEFINEDCODE_5 AS SALESYEAR,

	--ROW 2:
	RH.USERDEFINEDDATE_2 AS PLANTINGDATE,
	RH.USERDEFINEDDATE_1 AS EXPECTEDDATE,
	RH.PONUMBER,
	--RECORD# [SOURCE?]
	RH.KEYSEQUENCE,
	RH.REFERENCENUMBER,

	--ROW 3:
	RH.INVOICENUMBER,
	RH.INVOICEDATE,
	RH.DATERECEIVED,
	RH.STATUS,
	(	SELECT FLAGDESCRIPTION 
		FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME = 'PORECEIPTSHEADER' 
		AND FIELDNAME = 'STATUS' 
		AND FLAGVALUE = RH.STATUS
		) AS STATUSDESC,

	--DETAIL FIELDS:
	RD.ORDEREDQUANTITY, 
	RD.RECEIVEDQUANTITY, 
	IIF(LOT.USERDEFINEDCODE_5='SUSPEND','Y',NULL) AS ISSUSPEND,
	ITM.ITEMCODE,
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUPCODE, 
	CNT.PRINTEDCONTAINERCODE AS CONTAINERSIZE, 
	LOT.USERDEFINEDCODE_3 AS HOLDSTOP,
	ITM.DESCRIPTION_1 AS SHORTCOMMONNAME,
	ITM.REFERENCE_1 AS COMMONNAME, 
	ITM.SPECIFICATIONCODE  AS INTERN_SPEC,
--RETURNS MORE THAN ONE VALUE SO "TOP 1" AND ORDER BY WAS ADDED 3/1/22 DT
	(	SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK)
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=MC.ROWID 
		ORDER BY VALUE
		) AS PRIORITY,
	LOT.LOTCODE,
	LOT.USERDEFINEDREFERENCE_4 AS HOLDREASON,
	LOT.USERDEFINEDDATE_4 AS HOLDREASONSTARTDATE,
	NULL AS DEFAULTLOCATION,	--NOT YET DEVELOPED
	RD.USERDEFINEDREFERENCE_1 AS PSLINE,
	RD.USERDEFINEDREFERENCE_2 AS TRANSTEXT,
	RD.USERDEFINEDREFERENCE_4 AS POCOMMENT,
	--CONCAT: LOC.SRC.DESIG_ICL
	NULLIF(
		ISNULL(TRIM(LOC.LOCATIONCODE),'')+'.'+
		ISNULL(RD.USERDEFINEDCODE_2,'')+'.'+
		ISNULL(RD.USERDEFINEDCODE_4,'')+'.'+
		ISNULL(RD.USERDEFINEDCODE_3,'')+'.'+
		ISNULL(RD.USERDEFINEDCODE_5,''),
		'....') AS RECEIVEDLOCATION, 
	ITM.PRICELEVELA
FROM PORECEIPTSHEADER RH (NOLOCK) 
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = RH.COMPANYID
LEFT JOIN PORECEIPTSDETAIL RD (NOLOCK) ON RD.R_RECEIPTSHEADER =RH.ROWID
LEFT JOIN IDMASTER VENDOR (NOLOCK) ON VENDOR.ROWID = RH.R_VENDOR 
LEFT JOIN IDMASTER SHIPTO (NOLOCK) ON SHIPTO.ROWID = RH.R_SHIPTO 
--ITEM LEVEL JOINS:
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = RD.R_ITEM
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
LEFT JOIN IMCONTAINER CNT ON CNT.ROWID = ITM.R_CONTAINERCODE 
--LOT/LOC LEVEL JOINS:
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = RD.R_LOT 
LEFT JOIN IMTRANSACTIONLOCATION T_LOC (NOLOCK) ON T_LOC.R_TRANSACTIONDETAIL= RD.ROWID
LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = T_LOC.R_LOCATION 
LEFT JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.R_ITEM = RD.R_ITEM AND MC.R_LOT = RD.R_LOT AND MC.R_LOCATION = LOC.ROWID
