/* TRIMMED
--112 Price Schedule Detail
--112 Price Schedule Detail EXCEL
SELECT * 
FROM VW_RPT_PRICE_SCHEDULE_DETAIL (NOLOCK) 
WHERE RECORDTYPE <> 'P'
AND PRICESCHEDULECODE LIKE '40Brehob%'--'20Abide%'
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_PRICE_SCHEDULE_DETAIL]
AS
SELECT
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	PSH.RECORDTYPE,
	PSH.STATUS,
	PSH.EFFECTIVESTARTDATE,
	PSH.DISCOUNTPRICE AS TRADEDISCOUNT,
	TRIM(PSH.PRICESCHEDULECODE) AS PRICESCHEDULECODE,
	PSH.DESCRIPTION PRICESCHEDULEDESC,
	PSH.COMMENT AS PRICESCHEDULECOMMENT,
	TRIM(WH.IDENTITYID) AS WAREHOUSEID,
	TRIM(WH.NAME) AS WAREHOUSENAME,
	--HEADER RECORDS:
	PSH.ALLOWUNSPECIFIED,
	PSH.DISCOUNTPERCENT,
	TRIM(ZONCOD.CODE) AS ZONECODE,
	ZONCOD.DESCRIPTION AS ZONEDESC,
	PSH.RETAILREQUIRED,
	PSH.SKUREQUIRED,
	PSH.USENPC,
	PSH.CHANGEPRICE,
	PSH.APPLYMINFREIGHT,
	--DETAIL RECORDS:
	TRIM(ITM.ITEMCODE) AS ITEMCODE,
	CNT.PRINTEDCONTAINERCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	DBO.FN_LISTPRICE(ITM.ROWID,PSH.EFFECTIVESTARTDATE,NULL) AS LISTPRICE,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS CURRLISTPRICE,
	PSD.DISCOUNTPRICE AS UNITPRICE, 
	ISNULL(PSD.HANDLINGCHARGE,0) AS HANDLINGCHARGE,
	ISNULL(PSD.OTHERCHARGE,0) AS TAGGINGCHARGE,
	PSD.DISCOUNTPRICE + ISNULL(PSD.HANDLINGCHARGE,0) + ISNULL(PSD.OTHERCHARGE,0) AS ITEMPRICE,
	PSD.FREIGHTCHARGE,
	PSD.DISCOUNTPRICE + ISNULL(PSD.HANDLINGCHARGE,0) + ISNULL(PSD.OTHERCHARGE,0) + ISNULL(PSD.FREIGHTCHARGE,0) AS LANDED,
	PSD.ALTERNATESKU,
	PSD.RETAILPRICE,
	ITM.ITEMSUPCCODE,
	--SPECIAL TREATMENT OF PSD.COMMENT BECAUSE IT IS A DATATYPE: TEXT FIELD:
	NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), '') AS OVERRIDEUPC,
	TRIM(ITM.REFERENCE_2) + ISNULL(' ' + ITM.USERDEFINEDREFERENCE_1,'') AS BOTANICALNAME,
	SUBSTRING(PGC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
	TRIM(PGC.PRODUCTCATEGORYCODE) AS PLANTGROUP,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	CNT.CONTAINERSORT AS CONTAINERSORT,
	TRIM(ITM.SUBCLASSCODE) AS QUALITY,
	ITM.SUBCLASSCODE+PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT AS GRADEITEMSORT
FROM IMPRICESCHEDULEHEADER PSH (NOLOCK)
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = PSH.COMPANYID
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PSH.R_SHIPPER
JOIN RTZONETABLECODES ZONCOD (NOLOCK) ON ZONCOD.ROWID = PSH.R_ZONE
JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PSD.R_ITEM
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
WHERE PSH.RECORDTYPE <> 'P'