/*	*--TEMPORARY PROD VERSION UNTIL OH.R_SYNONYMSALTSHIPTO EXISTS--*
--ALTSHIPTO ADDRESS VIEW (TO BE USED IN REPORTS)
SELECT * 
FROM VW_RPT_ALTSHIPTOADDRESS (NOLOCK)
WHERE TRANSACTIONNUMBER = '10-21354'
*/
CREATE OR ALTER VIEW [dbo].[VW_RPT_ALTSHIPTOADDRESS] 
AS 
SELECT 
	SYN.ROWID, 
	OH.ROWID AS R_TRANSACTIONHEADER, 
	OH.TRANSACTIONNUMBER, 
	SYN.MODULE, 
	SYN.IDTYPE, 
	SYN.NAME, 
	SYN.ADDRESS_1, 
	SYN.ADDRESS_2, 
	SYN.CITY, 
	SYN.STATE, 
	SYN.ZIP, 
	SYN.COUNTRY, 
	SYN.COMMENT, 
	SYN.USERDEFINEDCODE_1, 
	--BUILDING THE ADDRESSMEMO FIELD FOR ALTSHIPTO: CANNIBALIZED FROM VW_IDCUSTOMERVIEW: 
    CONVERT(VARCHAR(250), IsNull(SYN.Name, IsNull(ACONS.ALTERNATENAME, CONS.NAME))+ char(13)+char(10)+ 
        (CASE WHEN ((ISNULL(SYN.Address_1, '')='') AND (ISNULL(SYN.Address_2, '')='')) THEN '' 
                WHEN (ISNULL(SYN.Address_2, '')='')  AND (ISNULL(SYN.Address_1, '')<>'') THEN SYN.Address_1 + char(13)+char(10) 
                WHEN (ISNULL(SYN.Address_1, '')='')  AND (ISNULL(SYN.Address_2, '')<>'') THEN SYN.Address_2 + char(13)+char(10) 
                ELSE SYN.Address_1 + char(13)+char(10) + SYN.Address_2 + char(13)+char(10) 
            END) + 
            RTRIM(ISNULL(SYN.City,'')) +'    '+RTRIM(ISNULL(SYN.State,'')) +'   '+ ISNULL(SYN.Zip,'')) AS ADDRESSMEMO, 
	------- 
	CONS.IDENTITYID AS CONSIGNEEID, 
	CONS.NAME AS CONSIGNEENAME, 
	ACONS.ADDRESS_1 AS CONSIGNEEADDRESS_1, 
	ACONS.ADDRESS_2 AS CONSIGNEEADDRESS_2, 
	ACONS.CITY AS CONSIGNEECITY, 
	ACONS.STATE AS CONSIGNEESTATE, 
	ACONS.ZIP AS CONSIGNEEZIP, 
	ACONS.COUNTY AS CONSIGNEECOUNTY, 
	ACONS.COUNTRY AS CONSIGNEECOUNTRY, 
	ACONS.TELEPHONE_1 AS CONSIGNEEPHONE, 
	--BUILDING THE ADDRESSMEMO FIELD FOR ALTSHIPTO: CANNIBALIZED FROM VW_IDCUSTOMERVIEW: 
    CONVERT(VARCHAR(250), IsNull(ACONS.ALTERNATENAME, CONS.NAME)+ char(13)+char(10)+ 
        (CASE WHEN ((ISNULL(ACONS.Address_1, '')='') AND (ISNULL(ACONS.Address_2, '')='')) THEN '' 
                WHEN (ISNULL(ACONS.Address_2, '')='')  AND (ISNULL(ACONS.Address_1, '')<>'') THEN ACONS.Address_1 + char(13)+char(10) 
                WHEN (ISNULL(ACONS.Address_1, '')='')  AND (ISNULL(ACONS.Address_2, '')<>'') THEN ACONS.Address_2 + char(13)+char(10) 
                ELSE ACONS.Address_1 + char(13)+char(10) + ACONS.Address_2 + char(13)+char(10) 
            END) + 
            RTRIM(ISNULL(ACONS.City,'')) +'    '+RTRIM(ISNULL(ACONS.State,'')) +'   '+ ISNULL(ACONS.Zip,'')) AS CONSIGNEEADDRESSMEMO 
FROM IDSYNONYMS SYN (NOLOCK) 
--JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.R_SYNONYMSALTSHIPTO = SYN.ROWID 
JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.R_SHIPPER = SYN.R_IDENTITY AND SYN.USERDEFINEDCODE_1 IS NULL	--TEMP SUBSTITUTE FOR OH.R_SYNONYMSALTSHIPTO EXISTING IN PROD
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = SYN.R_IDENTITY 
JOIN IDADDRESS ACONS (NOLOCK) ON ACONS.ROWID = CONS.R_DEFAULTADDRESS 
