/*
--15 BILLINGS_2_WEEKLY_GOALS

SELECT
*
FROM VW_RPT_BILLINGS_2_WEEKLY_GOALS (NOLOCK)
WHERE VW_RPT_BILLINGS_2_WEEKLY_GOALS.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_BILLINGS_2_WEEKLY_GOALS]
AS
SELECT U.* 
FROM	(

		----------------------------------
		-- THIS IS THE DIVISIONAL (D) DATASET --
		----------------------------------
		SELECT 
		'Y' AS ISDIVISIONAL,
		NULL AS ISCONSOLIDATED,
		D.RECORDTYPE,
		D.COMPANYID,
		D.SALEYEAR,
		D.PERIOD,
		D.WEEK,
		D.WEEKCOUNT,
		D.WEEKENDDATE,
		D.TRANSACTIONDATE,
		D.WAREHOUSEID,
		D.WAREHOUSENAME,
		D.NATIONALACCOUNT,
		IIF(D.NATIONALACCOUNT = 'Y', 'Major Acct', 'Independent') AS ACCTTYPE,
		D.SALESREPID,
		D.SALESREPNAME,
		D.CURRAMOUNT,
		D.GOALAMOUNT
		FROM VW_RPT_SQL_WEEKLY_GOALS D (NOLOCK) --D IS NOW DIVISIONAL RECORDS

		UNION ALL

		--------------------------------
		-- THIS IS THE CONSOLIDATED (C) DATASET --
		--------------------------------
		SELECT 
		NULL AS ISDIVISIONAL,
		'Y' AS ISCONSOLIDATED,
		C.RECORDTYPE,
		C.COMPANYID,
		C.SALEYEAR,
		C.PERIOD,
		C.WEEK,
		C.WEEKCOUNT,
		C.WEEKENDDATE,
		C.TRANSACTIONDATE,
		NULL AS WAREHOUSEID,	--CONSOLDIATED TOTALS:
		'Consolidated' AS WAREHOUSENAME,
		C.NATIONALACCOUNT,
		IIF(C.NATIONALACCOUNT = 'Y', 'Major Acct', 'Independent') AS ACCTTYPE,
		C.SALESREPID,
		C.SALESREPNAME,
		C.CURRAMOUNT,
		C.GOALAMOUNT
		FROM VW_RPT_SQL_WEEKLY_GOALS C (NOLOCK) --C IS NOW CONSOLIDATED RECORDS
		
		) U
