/*
--EDI PO REPORT
-------------------------------------------------------------------------------------------------------------------
--**THIS IS THE SPEC THAT ARGOS WILL NEED TO START PHASE TWO AND SALES WILL NEED TO MANUALLY CREATE TEST ORDERS**--
--SHORE THIS UP DURING ORDER CREATION TESTING WITH SALES TEAM, THEN PUT PRESSURE ON ARGOS TO START PHASE TWO-------
-------------------------------------------------------------------------------------------------------------------

SELECT 
* 
FROM VW_RPT_EDI_PO_NEW (NOLOCK) 
WHERE COMPANYID = 'SB'
--AND IMPORTEDAS IS NULL
AND PO_POTYPE IN ('NEW', 'CHANGE') 
ORDER BY PO_RESERVENUMBER, PO_POTYPE, LINENUMBER 

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_EDI_PO_NEW]
AS

SELECT 	--DISTINCT 
	--ACONS.ADDRESS_1, ACONS.ADDRESS_2, ACONS.CITY, ACONS.STATE, ACONS.ZIP, ACONS.COUNTRY,
	CO.COMPANYID, CO.NAME AS COMPANYNAME, POH.CREATIONDATETIME, 
	--SPECIAL FLAG: DO WE STILL NEED TO SEND AN EMAIL TO USERS:
	ISNULL(IIF(POH.RECORDTYPE = 'E', POH.EDITRANSMITFLAG, IIF(OH.TRANSACTIONNUMBER IS NULL, POH.EDITRANSMITFLAG, OH.EDITRANSMITFLAG)),'N') AS EMAILSENTFLAG, 
	--VALIDATION CALCULATION FIELD: 

--IS ADDRESS ON PO DIFFERENT FROM EITHER ALTSHIP OR CONSIGNEE ADDRESS?:
	IIF(	ISNULL(POH.USERDEFINEDREFERENCE_15, ISNULL(OH.USERDEFINEDREFERENCE_15,'')) != ''	--PO SPECIFIED ADDRESS EXISTS
		OR	ISNULL(POH.USERDEFINEDREFERENCE_16, ISNULL(OH.USERDEFINEDREFERENCE_16,'')) != '',	--PO SPECIFIED CITYSTZIP EXISTS
		IIF(ALTSHIP.ROWID IS NOT NULL,		
			--ALTSHIP IS DEFINED, SEE IF IT MATCHES:
			IIF(	ISNULL(TRIM(ALTSHIP.ADDRESS_1),'')+'::'+ISNULL(TRIM(ALTSHIP.ADDRESS_2),'') != ISNULL(POH.USERDEFINEDREFERENCE_15, ISNULL(OH.USERDEFINEDREFERENCE_15,'')) --PO_ALT_ADDRESS 
				 OR ISNULL(TRIM(ALTSHIP.CITY),'')+', '+ISNULL(TRIM(ALTSHIP.STATE),'')+'  '+ISNULL(TRIM(ALTSHIP.ZIP),'')+'-'/*+ISNULL(TRIM(ALTSHIP.COUNTRY),'')*/ != ISNULL(POH.USERDEFINEDREFERENCE_16, ISNULL(OH.USERDEFINEDREFERENCE_16,'')), --PO_ALT_CITYSTZIP,
					'PO_ALTSHIPTO: ' + RIGHT('0000000-0000'+ISNULL(POH.USERDEFINEDREFERENCE_19,''),12) + ' AS: ' + ISNULL(POH.USERDEFINEDREFERENCE_15, ISNULL(OH.USERDEFINEDREFERENCE_15,'')) + '::' + ISNULL(POH.USERDEFINEDREFERENCE_16, ISNULL(OH.USERDEFINEDREFERENCE_16,''))+'/', '') 
			,''--ALTSHIP IS NOT DEFINED 
/*
			--SEE IF CONSIGNEE ADDRESS MATCHES: [STRIPPING OUT PERIODS FROM ADDRESS ]
			IIF(	ISNULL(TRIM(REPLACE(ACONS.ADDRESS_1,'.','')),'')+'::'+ISNULL(TRIM(REPLACE(ACONS.ADDRESS_2,'.','')),'') != ISNULL(REPLACE(POH.USERDEFINEDREFERENCE_15,'.',''), ISNULL(REPLACE(OH.USERDEFINEDREFERENCE_15,'.',''),'')) --PO_ALT_ADDRESS 
				 OR ISNULL(TRIM(ACONS.CITY),'')+', '+ISNULL(TRIM(ACONS.STATE),'')+'  '+ISNULL(TRIM(ACONS.ZIP),'')+'-'/*+ISNULL(TRIM(ACONS.COUNTRY),'')*/ != ISNULL(POH.USERDEFINEDREFERENCE_16, ISNULL(OH.USERDEFINEDREFERENCE_16,'')), --PO_ALT_CITYSTZIP,
					'PO_ADDRESS: ' + RIGHT('Store#'+ISNULL(POH.USERDEFINEDREFERENCE_19,''),12) + ' AS: ' + ISNULL(POH.USERDEFINEDREFERENCE_15, ISNULL(OH.USERDEFINEDREFERENCE_15,'')) + '::' + ISNULL(POH.USERDEFINEDREFERENCE_16, ISNULL(OH.USERDEFINEDREFERENCE_16,''))+'/', '') 
*/
		),'') + 

	IIF((	SELECT IIF((COUNT(DISTINCT CPSD.DISCOUNTPRICE) + 
						COUNT(DISTINCT CPSD.FREIGHTCHARGE) + 
						COUNT(DISTINCT CPSD.OTHERCHARGE) + 
						COUNT(DISTINCT CPSD.HANDLINGCHARGE))/4. > 1., 'Y', NULL) 
			FROM IMPRICESCHEDULEDETAIL CPSD (NOLOCK) 
			WHERE CPSD.R_PRICESCHEDULEHEADER = PSH.ROWID 
			AND CPSD.ALTERNATESKU = PSD.ALTERNATESKU 
			AND CPSD.EXPIRATIONDATE > POH.SHIPPINGDATE 
			AND ICUST.USERDEFINEDCODE_3 = 'Y' --ONLY IF SKUROLLUP IS REQUIRED BY THE CUSTOMER 
		) = 'Y',																				'SKU ROLLUP VIOLATION/',			'') + 
	IIF(ICUST.STATUS <> 'A',																	'INACTIVE CUSTOMER/',				'') + 
	IIF(ISNULL(ICUST.USERDEFINEDCODE_9,'') <> 'Y',												'NOT AN EDI CUSTOMER/',				'') + 
	IIF(ISNULL(ICONS.USERDEFINEDREFERENCE_2,'') <> RIGHT('0000'+POH.USERDEFINEDREFERENCE_19,4),	'STORE# NOT SETUP/',				'') + 
	IIF(ISNULL(ICONS.USERDEFINEDREFERENCE_6,'') <> ISNULL(POH.USERDEFINEDREFERENCE_20,''),		'GLN# NOT SETUP/',					'') + 
	IIF(ICUST.OMREQUIREPO = 'Y' AND POH.PURCHASEORDERNUMBER IS NULL,							'PO REQUIRED/',						'') + 
	IIF(ICUST.USERDEFINEDCODE_7 = 'Y' AND POH.USERDEFINEDREFERENCE_4 IS NULL,					'WORK ORDER# REQUIRED/',			'') + 
	IIF(PSH.SKUREQUIRED = 'Y' AND PSD.ALTERNATESKU IS NULL,										'SKU REQUIRED/',					'') + 
	IIF(ISNULL(PSD.ALTERNATESKU,'') <> ISNULL(POD.USERDEFINEDREFERENCE_10,''),					'SKU DIFFERENT FROM PO/',			'') + 
	--IIF(PSH.RETAILREQUIRED = 'Y' AND PSD.RETAILPRICE IS NULL,									'RETAIL REQUIRED/',					'') + 
	IIF(PSH.ALLOWUNSPECIFIED = 'N' AND PSD.ROWID IS NULL,										'UNSPECIFICED ITEM NOT ALLOWED',	'') 
		AS VIOLATION,													--> Special Import related field  

	IIF(POH.RECORDTYPE = 'E', 'CHANGE', IIF(OH.TRANSACTIONNUMBER IS NULL, 'NEW', 'ORDER')) AS PO_POTYPE, 
	POH.TRANSACTIONNUMBER AS PO_RESERVENUMBER, 
	OH.TRANSACTIONNUMBER AS IMPORTEDAS, 
	SUBSTRING(SEA.SEASONCODE,4,3) +	LEFT(SEA.SEASONCODE,3) + RIGHT(SEA.SEASONCODE,2) AS PROFILECODE, 
	ZONCOD.CODE AS ZONEOVERRIDE, 
	PSH.PRICESCHEDULECODE, 
	CUST.IDGROUP, 
	WH.IDENTITYID AS WAREHOUSEID, 
	CUST.IDENTITYID AS CUSTOMERID, 
	CUST.NAME AS CUSTOMERNAME, 
	CONS.IDENTITYID AS CONSIGNEEID, 
	CONS.NAME AS CONSIGNEENAME, 
	TRIM(ACONS.CITY) AS CONSIGNEECITY, 
	TRIM(ACONS.STATE) AS CONSIGNEESTATE, 
	POH.PURCHASEORDERNUMBER, 
	RIGHT('0000'+POH.USERDEFINEDREFERENCE_19,4) AS PO_STORENUMBER, 
	ICONS.USERDEFINEDREFERENCE_2 AS STORENUMBER, 
	POH.USERDEFINEDREFERENCE_20 AS PO_GLN#, 
	ICONS.USERDEFINEDREFERENCE_6 AS GLN#, 
	POH.USERDEFINEDREFERENCE_4 AS WORKORDER, 
	POH.USERDEFINEDDATE_19 AS SHIPNOTBEFOREDATE, 
	POH.USERDEFINEDDATE_20 AS SHIPNOTAFTERDATE, 
	ISNULL(POH.USERDEFINEDREFERENCE_3,'CORPORATE ORDER') AS ORDEREDBY, 
	--POH.TRANSACTIONDATE, -->INFORM ARGOS TO USE THE DATE OF THE IMPORT, DON'T INCLUDE THIS FIELD.
	POH.SHIPPINGDATE AS REQUESTDATE, --USING: SHIPNOTBEFOREDATE IN RURAL KING 850 MAP
	ISNULL(POH.USERDEFINEDCODE_1,'WEEK OF') AS REQUESTDATETYPE,	
	POD.USERDEFINEDQUANTITY_8 AS PO_LANDEDPRICE, 
	ROUND(PSD.LANDEDPRICE,2) AS PSDLANDEDPRICE, 
	ROUND(PSD.FREIGHTCHARGE,2) AS PSDFREIGHTCHARGE, 
	ROUND(PSD.DISCOUNTPRICE,2) AS PSDUNITPRICE,
	ROUND(PSD.HANDLINGCHARGE,2) AS PSDHANDLINGCHARGE, 
	ROUND(PSD.OTHERCHARGE,2) AS PSDOTHERCHARGE, 
-->ASSORTED ITEM PRICES:
	ROUND(ASSPSD.LANDEDPRICE,2) AS ASSORTEDLANDEDPRICE,
	ROUND(ASSPSD.FREIGHTCHARGE,2) AS ASSORTEDFREIGHTCHARGE, 
	ROUND(ASSPSD.DISCOUNTPRICE,2) AS ASSORTEDUNITPRICE,
	ROUND(ASSPSD.HANDLINGCHARGE,2) AS ASSORTEDHANDLINGCHARGE, 
	ROUND(ASSPSD.OTHERCHARGE,2) AS ASSORTEDOTHERCHARGE, 

	CAST(POD.USERDEFINEDQUANTITY_9 AS INT) AS PO_LINENUMBER, 
	POD.LINENUMBER, --INFORM ARGOS TO INCREMENT {previous} LINE# IF BLANK.
	POD.USERDEFINEDREFERENCE_10 AS PO_ALTERNATESKU, 
	PSD.ALTERNATESKU, 
	DBO.FN_FORMATUPC(PSH.ROWID, WH.ROWID, ITM.ROWID) AS UPCNO, 
	ITM.ITEMCODE, 
	ITM.REFERENCE_1 AS COMMONNAME, 
-->ASSORTED ITEM REFERENCES:
	DBO.FN_FORMATUPC(PSH.ROWID, WH.ROWID, ASSITM.ROWID) AS ASSORTEDUPCNO,
	ASSITM.ITEMCODE AS ASSORTEDITEM,
	ASSITM.REFERENCE_1 AS ASSORTEDCOMMONNAME,

	POD.USERDEFINEDQUANTITY_7 AS PO_QUANTITYORDERED, 
	POD.QUANTITYORDERED, 
	NULLIF(TRIM(CONVERT(VARCHAR(256),POD.COMMENT)),'') AS PICKNOTE, 
	NULLIF(TRIM(CONVERT(VARCHAR(256),POD.USERDEFINEDCOMMENT)),'') AS TAGDEPTNOTE, 
	NULLIF(TRIM(CONVERT(VARCHAR(256),POH.COMMENT)),'') AS ORDERSHIPPINGINSTRUCTIONS
FROM OMTRANSACTIONHEADER POH (NOLOCK) 
JOIN OMTRANSACTIONDETAIL POD (NOLOCK) ON POD.R_TRANSACTIONHEADER = POH.ROWID 
LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.PURCHASEORDERNUMBER = POH.PURCHASEORDERNUMBER AND OH.RECORDTYPE NOT IN ('I', 'E') AND OH.TRANSACTIONTYPE = 'I' 

JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = POH.R_FMSHIPPER 
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = POD.R_ITEM 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = POH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = POH.R_CUSTOMER 

JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = POH.R_SHIPPER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
JOIN IDTYPESLINKS TCONS (NOLOCK) ON TCONS.R_IDENTITY = CONS.ROWID AND TCONS.IDTYPE = '02'
JOIN IDADDRESS ACONS (NOLOCK) ON ACONS.ROWID = ISNULL(TCONS.R_ADDRESS, CONS.R_DEFAULTADDRESS)
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = ISNULL(POH.R_SYNONYMSALTSHIPTO, OH.R_SYNONYMSALTSHIPTO)

LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE)
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = POD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
LEFT JOIN RTZONETABLECODES ZONCOD (NOLOCK) ON ZONCOD.ROWID = ISNULL(ISNULL(POH.R_ZONEFREIGHTRATEOVERRIDE, PSH.R_ZONE), SZ.R_ZONE)
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = POH.COMPANYID
JOIN IMSEASONCODE SEA (NOLOCK) ON SUBSTRING(SEA.SEASONCODE,4,2) = WH.IDENTITYID AND POH.SHIPPINGDATE BETWEEN SEA.STARTDATE AND SEA.ENDDATE
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.LOTCODE = SUBSTRING(SEA.SEASONCODE,4,3)+RIGHT(SEA.SEASONCODE,2)
JOIN GNC_EDI_TRANSLATION GET (NOLOCK) ON ISNULL(GET.VENDOR, '') = ISNULL(POH.USERDEFINEDREFERENCE_17, '') AND ISNULL(GET.DEPT, '') = ISNULL(POH.USERDEFINEDREFERENCE_18, '')

LEFT JOIN IMPRICESCHEDULEDETAIL ASSPSD (NOLOCK) ON ASSPSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND ASSPSD.ALTERNATESKU = POD.USERDEFINEDREFERENCE_10 AND ASSPSD.EXPIRATIONDATE >= GETDATE()
LEFT JOIN IMITEM ASSITM (NOLOCK) ON ASSITM.ROWID = ASSPSD.R_ITEM
WHERE	POH.RECORDTYPE IN ('I', 'E')--INCLUDE POS AND CHANGE POS
AND		ISNULL(OH.RECORDTYPE,'') != 'Z'		--EXCLUDE ATTACHED ORDERS THAT ARE COMMITTED 
AND		ISNULL(OH.STAGE,'') != 'L'				--EXCLUDE ATTACHED ORDERS THAT ARE CANCELLED 
/* 
Notes for JoAnne:
TABLENAME			UDFIELD					DATATYPE	NAME/DESCRIPTION
-------------------	-----------------------	---------	-----------------
OMTRANSACTIONHEADER	USERDEFINEDDATE_19		DATETIME	SHIPNOTBEFORE	
OMTRANSACTIONHEADER	USERDEFINEDDATE_20		DATETIME	SHIPNOTAFTER	
OMTRANSACTIONHEADER	USERDEFINEDREFERENCE_17	CHAR(9)		PO_VENDOR			
OMTRANSACTIONHEADER	USERDEFINEDREFERENCE_18	CHAR(5)		PO_DEPT				
OMTRANSACTIONHEADER	USERDEFINEDREFERENCE_19	CHAR(4)		PO_STORENUMBER		
OMTRANSACTIONHEADER	USERDEFINEDREFERENCE_20	CHAR(13)	PO_GLN				
--OMTRANSACTIONHEADER	USERDEFINEDQUANTITY_20				IMPORTHEADER	--DECIDED NOT TO USE
OMTRANSACTIONDETAIL	USERDEFINEDREFERENCE_10	CHAR(15)	PO_SKU				
OMTRANSACTIONDETAIL USERDEFINEDQUANTITY_7	NUMBER		PO_QUANTITY 		
OMTRANSACTIONDETAIL	USERDEFINEDQUANTITY_8	NUMBER		PO_LANDEDPRICE		
OMTRANSACTIONDETAIL	USERDEFINEDQUANTITY_9	INT			PO_LINENUMBER		
--OMTRANSACTIONDETAIL	USERDEFINEDQUANTITY_10				IMPORTDETAIL	--DECIDED NOT TO USE

RURAL KING MAPPED VALUES:
POVALUES			OH/OD FIELDS									REFERENCE
----------------	--------------------------------------------	-----------------
@PONUMBER,			POH.PURCHASEORDERNUMBER	
@PODATE,			POH.TRANSACTIONDATE		
@REQUESTDATE,		POH.SHIPPINGDATE			
--@CANCELDATE,		POH.CANCELDATE				
@NOTBEFOREDATE,		POH.USERDEFINEDDATE_19					
--@NOTAFTERDATE,	POH.USERDEFINEDDATE_20					
@COMMENTS,			POH.COMMENT				
@EXTRACOMMENTS,		POH.USERDEFINEDCOMMENT		
@VENDOR				POH.USERDEFINEDREFERENCE_17 AS PO_VENDOR		GET.VENDOR
--@DEPT				POH.USERDEFINEDREFERENCE_18 AS PO_DEPT			GET.DEPT
@STORENUMBER,		POH.USERDEFINEDREFERENCE_19 AS PO_STORENUMBER	ICONS.UDR_2
-->>>>>>			POH.USERDEFINEDREFERENCE_15	PO_ALT_ADDRESS		ALTERNATE ADDRESS
-->>>>>>			POH.USERDEFINEDREFERENCE_16 PO_ALT_CITYSTZIP	ALTERNATE CITYSTZIP
--@GLN,				POH.USERDEFINEDREFERENCE_20 AS PO_GLN			ICONS.UDR_6
@LINENUMBER,		POD.USERDEFINEDQUANTITY_9 AS PO_LINENUMBER		POD.LINENUMBER
@LINENUMBER,		POD.LINENUMBER
@QTYORDERED,		POD.USERDEFINEDQUANTITY_7 AS PO_QUANTITY, 		
@LANDEDPRICE,		POD.USERDEFINEDQUANTITY_8 AS PO_LANDEDPRICE		
@SKU,				POD.USERDEFINEDREFERENCE_10 AS PO_SKU			PSD.ALTERNATESKU
*/
