/*
--CREDITREASON BY DATE EXCEL(NEW REPORT REQUESTED BY SHELLY CERNY)
--CREDITDEBIT DETAIL EXCEL(NEW REPORT REQUESTED BY ERICA WASHINGTON)
--96 CREDITDEBIT DETAIL LISTING
--97 CREDITDEBIT (MULTIPLE VERSIONS - THIS IS BASED ON INVOICE VERSION:M7)
SELECT
VW_RPT_CREDITDEBIT.*
FROM VW_RPT_CREDITDEBIT (NOLOCK)
--Needed by Insight to run report from the OMScreens:(CREDITDEBIT IS NOT AN OPTION ON THE OMScreens BUT I ADDED IT ANYWAY)
JOIN OMTRANSACTIONHEADER (NOLOCK) ON OMTRANSACTIONHEADER.ROWID = VW_RPT_CREDITDEBIT.OHROWID
WHERE VW_RPT_CREDITDEBIT.ISCREDITDEBIT = 'Y'


INVOICE VERSIONS:
SELECT C.CODE,C.DESCRIPTION_1,C.DESCRIPTION_2,COMMENT FROM IDCODES C WHERE C.CODETYPE='3E' ORDER BY CAST(C.CODE AS INT)
#	Description							Sort			Steve's Msg
-------------------------------------------------------------------------------------------------------------------------
1	List Merch Frt/Oth Tot Ext			PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
2	No List Merch Frt/Oth Tot Ext		PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
3	List Landed Ext						PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
4	No List Landed Ext					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
5	List Merch ExtMerch					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_CREDITDEBIT]
AS
SELECT *,
(	SELECT DESCRIPTION_1 FROM OMCODES (NOLOCK) WHERE CODETYPE ='12' AND CODE = CREDITREASON
) AS CREDITREASONDESC, 
(	SELECT ISNULL(AH.TRANSACTIONDUEDATE, VW_RPT_OM_VERSION_MASTER.TRANSACTIONDUEDATE)
	FROM AROPENITEMHEADER AH (NOLOCK) 
	WHERE AH.R_SOURCEID = OHROWID AND AH.SOURCETABLENAME = 'OMTRANSACTIONHEADER'
) AS DELAYEDDUEDATE,
IIF(ISNULL(ORDERTOTAL,ISNULL(FRTTOTAL,0)) < 0, 'DEBIT', 'CREDIT') AS CUST_CREDITDEBITTEXT,
-1 * EXTUNITPRICE AS CUST_EXTUNITPRICE,
-1 * EXTLANDEDPRICE AS CUST_EXTLANDEDPRICE,
-1 * FRTZONE AS CUST_FRTZONE,
-1 * MINIMUMFREIGHT_ADJ AS CUST_MINIMUMFREIGHT_ADJ,
-1 * FRTADJ AS CUST_FRTADJ,
-1 * FRTFLAT AS CUST_FRTFLAT,
-1 * FRTHDL AS CUST_FRTHDL,
-1 * FRTFSC AS CUST_FRTFSC,
-1 * FRTTOTAL AS CUST_FRTTOTAL,
-1 * ORDERLISTPRICE AS CUST_ORDERLISTPRICE,
-1 * ORDERUNITPRICE AS CUST_ORDERUNITPRICE,
-1 * ORDERHANDLINGCHARGE AS CUST_ORDERHANDLINGCHARGE,
-1 * ORDERTAGGINGCHARGE AS CUST_ORDERTAGGINGCHARGE,
-1 * ORDERSALESTAX AS CUST_ORDERSALESTAX,
-1 * ORDERTOTAL AS CUST_ORDERTOTAL

FROM VW_RPT_OM_VERSION_MASTER (NOLOCK) 
WHERE ISCREDITDEBIT = 'Y' 



