--LAST UPDATE: CASTING TRANSACTIONDATE[DATETIME] AS DATE -- DT 5/10/22

/*
SELECT DBO.FN_DATE4NEXTYEAR(TRANSACTIONDATE) AS CURRTRANSDATE,
* FROM VW_RPT_SQL_1 (NOLOCK)
WHERE SALEYEAR = 2020
AND	WAREHOUSEID = 40
AND REPORTGROUP = 2
AND REPORTLINE = 3
AND DBO.FN_DATE4NEXTYEAR(TRANSACTIONDATE) BETWEEN '2020-07-26' AND '2020-11-30'
AND SALESREPID = 'S00'
*/

--SELECT * FROM VW_RPT_SQL_1 (NOLOCK)	--RUNTIME- 0.03
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_1]
AS
--ePLANT SQL DATA
SELECT
--IIF(REPORTGROUP = 6, 4, REPORTGROUP) AS REPORTGROUP,	--OVERLOAD REPORTGROUP 6 AS 4 (FREIGHT REPORTLINES 10 AND 13)
CASE REPORTLINE
	WHEN 10 THEN 4	--OVERLOAD REPORTLINE 10 AS REPORTGROUP 4 (SOME FREIGHT(10) COMES IN AS GROUP 6)
	WHEN 13	THEN 4	--OVERLOAD REPORTLINE 13 AS REPORTGROUP 4 (SOME MISC FRT(13) COMES IN AS GROUP 6)
	WHEN 14	THEN 5	--OVERLOAD REPORTLINE 14 AS REPORTGROUP 5 (INTER-CO GROSS(14) COMES IN AS GROUP 4)
	WHEN 15	THEN 5	--OVERLOAD REPORTLINE 15 AS REPORTGROUP 5 (INTER-CO NET(15) COMES IN AS GROUP 4)
	ELSE REPORTGROUP
END AS REPORTGROUP,
CASE REPORTLINE
	WHEN 16 THEN 4	--OVERLOAD REPORTLINE 16 AS 4 (VIP CREDITS)
	WHEN 5	THEN 6	--UNIFY (% DISCOUNTS) >> DISCOUNTS
	WHEN 7	THEN 6	--UNIFY (VOLUME PRICING) >> DISCOUNTS
	WHEN 9	THEN 6	--UNIFY (SPECIAL QUOTES) >> DISCOUNTS
	WHEN 13	THEN 10	--UNIFY (MISCELLANEOUS) >> FREIGHT
	ELSE REPORTLINE
END AS REPORTLINE,
REPORTLINEDESC,
CAST (SALEYEAR AS INT) AS SALEYEAR, 
SEASON, 
SYPERIOD AS PERIOD, 
WEEK, 
TRANSACTIONDATE, 
--CAST(TRANSACTIONDATE AS DATE) AS TRANSACTIONDATE, 
CAST (DIVISIONNUMBER AS CHAR(12)) AS WAREHOUSEID, 
DIVISIONNAME AS WAREHOUSENAME, 
CAST (NATIONALACCOUNT AS VARCHAR(10)) AS NATIONALACCOUNT,
--PART.IDENTITYID AS SALESREPID,
--PART.NAME AS SALESREPNAME,
ISNULL(PART.IDENTITYID, 'S00') AS SALESREPID,
ISNULL(PART.NAME, 'Adjustments') AS SALESREPNAME,
CUSTOMERTYPE, 
CUSTOMERTYPEDESC, 
CAST (CUSTOMERNUMBER AS VARCHAR(12)) AS CUSTOMERNUMBER, 
CUSTOMERNAME, 
AMOUNT
FROM SQL_1_NEW (NOLOCK) 
LEFT JOIN IDMASTER PART (NOLOCK) ON TRIM(PART.IDENTITYID) = 'S'+ RIGHT('0'+TRIM(STR(SALESREPIDCUST)),2) 
WHERE SALEYEAR > 2019
