/*
--75 Invoice Listing by Date
--75 Invoice Listing by Date-Major
--INVOICE TOTALS BY CUSTOMER	--FOR RADEAN
SELECT * 
FROM VW_RPT_INVLISTBYDATE (NOLOCK)
WHERE COMPANYID = 'SB' 
AND ALTSHIPFLAG = 'Y'
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_INVLISTBYDATE]
AS
SELECT
	OH.RECORDTYPE AS RECORDTYPE,
	OH.STAGE AS STAGE,
	SUBSTRING(DBO.FN_STAGESORT(OH.STAGE,'OM'),4,18) AS STAGENAME,
	OH.USERDEFINEDCODE_2 AS STEP,
	(SELECT OMCODES.DESCRIPTION_1 FROM OMCODES (NOLOCK) WHERE CODETYPE = '03' AND OMCODES.CODE = OH.USERDEFINEDCODE_2) AS STEPDESC,
	OH.REVIEWSTAGE AS OHREVIEWSTAGE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	TRIM(WH.IDENTITYID) AS WAREHOUSEID,
	WH.NAME AS WAREHOUSENAME,
	TRIM(PART.IDENTITYID) AS SALESREP,
	PART.NAME AS SALESREPNAME,
	TRIM(ICONS.USERDEFINEDCODE_12) AS TERRITORYCODE,
	IDC.DESCRIPTION_1 AS TERRITORYDESC,
	TRIM(ICONS.USERDEFINEDCODE_12) + ' (' + TRIM(IDC.DESCRIPTION_1) + ')' AS TERRITORYLABEL,
	TRIM(VCUST.CUSTOMERIDGROUP) AS CUSTOMERIDGROUP,
	(SELECT DESCRIPTION_1 FROM IDCODES (NOLOCK) WHERE CODETYPE = 'Z7' AND CODE = VCUST.CUSTOMERIDGROUP) AS CUSTOMERGROUPNAME,
	ISNULL(VCUST.CUSTOMERUSERDEFINEDCODE_8,'N') AS MAJORACCT,
	IIF(VCUST.CUSTOMERUSERDEFINEDCODE_8='Y','Major Acct','Independent') AS MAJORACCTLABEL,
	VCUST.CUSTOMERIDENTITYID,
	VCUST.CUSTOMERNAME, 
	VCUST.CUSTOMERADDRESSMEMO,
	VCUST.CUSTOMERADDRESS_1,
	VCUST.CUSTOMERCITY,
	VCUST.CUSTOMERSTATE,
	VCUST.CUSTOMERZIP,
	IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
	VCONS.CONSIGNEEIDENTITYID,
	TRIM(VCONS.CONSIGNEENAME) AS CONSIGNEENAME,
ISNULL(	--BUILD ALTSHIPADDRESSMEMO CANNIBALIZED FROM VW_IDCONSIGNEEVIEW:
		CONVERT(VARCHAR(250), TRIM(ALTSHIP.NAME) + CHAR(13) + CHAR(10) + 
				(CASE	WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')=''	THEN '' 
						WHEN ISNULL(ALTSHIP.ADDRESS_2, '')='' AND ISNULL(ALTSHIP.ADDRESS_1, '')<>''	THEN ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) 
						WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')<>''	THEN ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
						ELSE ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) + ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
						END 
				) + RTRIM(ALTSHIP.CITY) + '    ' + RTRIM(ALTSHIP.STATE) + '   ' + ALTSHIP.ZIP ),
		VCONS.CONSIGNEEADDRESSMEMO
	) AS CONSIGNEEADDRESSMEMO, 
ISNULL(ALTSHIP.ADDRESS_1, VCONS.CONSIGNEEADDRESS_1) AS CONSIGNEEADDRESS_1,
ISNULL(ALTSHIP.ADDRESS_2, VCONS.CONSIGNEEADDRESS_2) AS CONSIGNEEADDRESS_2,
ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY) AS CONSIGNEECITY, 
ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) AS CONSIGNEESTATE, 
ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP) AS CONSIGNEEZIP, 
TRIM(ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY)) + ', ' + ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) AS CONSIGNEECITYSTATE, 
ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPPHONE 
		NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
	) AS CONSIGNEETELEPHONE_1,
	OH.TRANSACTIONNUMBER,
	OH.INVOICEDATE,
	OH.SHIPPINGDATE AS REQUESTDATE,
	OH.USERDEFINEDCODE_1 AS REQUESTDATETYPE,
	--JUST INCASE CREDITS/DEBITS ARE INCLUDED, REVERSE THE SIGN:
	IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
		DBO.FN_ORDERVALUE(OH.ROWID, 'UNITPRICE') * -1,
		DBO.FN_ORDERVALUE(OH.ROWID, 'UNITPRICE') 
		)AS ORDERUNITPRICE,
	IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
		DBO.FN_ORDERVALUE(OH.ROWID, 'ITEMPRICE') * -1, 
		DBO.FN_ORDERVALUE(OH.ROWID, 'ITEMPRICE')
		) AS ORDERITEMPRICE,
	IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
		DBO.FN_ORDERVALUE(OH.ROWID, NULL) * -1,
		DBO.FN_ORDERVALUE(OH.ROWID, NULL) 
		)AS ORDERTOTAL
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
LEFT JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
LEFT JOIN IDCODES IDC (NOLOCK) ON IDC.CODETYPE = '3M' AND IDC.CODE = ICONS.USERDEFINEDCODE_12 --TERRITORY
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
WHERE OH.RECORDTYPE = 'Z'


UNION ALL

------------------------------------
-- ePLANT INVOICE LISTING SECTION --
------------------------------------
SELECT
	'Z' AS RECORDTYPE,
	'C' AS STAGE,
	SUBSTRING(DBO.FN_STAGESORT('C','OM'),4,18) AS STAGENAME,
	'COMPLETE' AS STEP,
	(SELECT OMCODES.DESCRIPTION_1 FROM OMCODES (NOLOCK) WHERE CODETYPE = '03' AND OMCODES.CODE = 'COMPLETE') AS STEPDESC,
	'ePlant Invoice' AS OHREVIEWSTAGE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	TRIM(CAST (INV.DIVISIONNUMBER AS VARCHAR)) AS WAREHOUSEID,	--	WH.IDENTITYID AS WAREHOUSEID,
	WH.NAME AS WAREHOUSENAME,
	'S'+RIGHT('00'+TRIM(CAST (INV.SALESREPID AS VARCHAR)),2) AS SALESREP,	--	PART.IDENTITYID AS SALESREP,
	ISNULL(PART.NAME,'['+INV.SALESREPNAME+']') AS SALESREPNAME,
	TRIM(CAST(INV.TERRITORYCODE AS VARCHAR)) AS TERRITORYCODE,	--	ICONS.USERDEFINEDCODE_12 AS TERRITORYCODE,
	INV.TERRITORYDESCRIPTION AS TERRITORYDESC,	--	IDC.DESCRIPTION_1 AS TERRITORYDESC,
	TRIM(CAST(INV.TERRITORYCODE AS VARCHAR)) + ' (' + INV.TERRITORYDESCRIPTION + ')' AS TERRITORYLABEL,	--	TRIM(ICONS.USERDEFINEDCODE_12) + ' (' + TRIM(IDC.DESCRIPTION_1) + ')' AS TERRITORYLABEL,
	TRIM(CAST (INV.GROUPNUMBER AS VARCHAR)) AS CUSTOMERIDGROUP,	--	VCUST.CUSTOMERIDGROUP,
	INV.GROUPNAME AS CUSTOMERGROUPNAME,	--	(SELECT DESCRIPTION_1 FROM IDCODES (NOLOCK) WHERE CODETYPE = 'Z7' AND CODE = VCUST.CUSTOMERIDGROUP) AS CUSTOMERGROUPNAME,
	ISNULL(INV.NATIONALACCOUNT,'N') AS MAJORACCT,	--	NULLIF(VCUST.CUSTOMERUSERDEFINEDCODE_8,'N') AS MAJORACCT,
	IIF(INV.NATIONALACCOUNT='Y','Major Acct','Independent') AS MAJORACCTLABEL,
	TRIM(CAST (INV.CUSTOMERNUMBER AS VARCHAR)) AS CUSTOMERIDENTITYID,	--	VCUST.CUSTOMERIDENTITYID,
	INV.CUSTOMERNAME,	--	VCUST.CUSTOMERNAME, 
	NULL AS CUSTOMERADDRESSMEMO,	--	VCUST.CUSTOMERADDRESSMEMO,
	NULL AS CUSTOMERADDRESS_1,	--	VCUST.CUSTOMERADDRESS_1,
	NULL AS CUSTOMERCITY,	--	VCUST.CUSTOMERCITY,
	NULL AS CUSTOMERSTATE,	--	VCUST.CUSTOMERSTATE,
	NULL AS CUSTOMERZIP,	--	VCUST.CUSTOMERZIP,
	'N' AS ALTSHIPFLAG, 
	TRIM(CAST (INV.CUSTOMERNUMBER AS VARCHAR)) AS CONSIGNEEIDENTITYID,	--	VCONS.CONSIGNEEIDENTITYID,
	INV.CUSTOMERNAME AS CONSIGNEENAME,	--	VCONS.CONSIGNEENAME,
	--BUILD ALTSHIPADDRESSMEMO CANNIBALIZED FROM VW_IDCONSIGNEEVIEW:
	CONVERT(VARCHAR(250), TRIM(INV.CUSTOMERNAME) + CHAR(13) + CHAR(10) + 
			(CASE	WHEN ISNULL(INV.ADDRESS_1, '')='' AND ISNULL(INV.ADDRESS_2, '')=''	THEN '' 
					WHEN ISNULL(INV.ADDRESS_2, '')='' AND ISNULL(INV.ADDRESS_1, '')<>''	THEN INV.ADDRESS_1 + CHAR(13) + CHAR(10) 
					WHEN ISNULL(INV.ADDRESS_1, '')='' AND ISNULL(INV.ADDRESS_2, '')<>''	THEN INV.ADDRESS_2 + CHAR(13) + CHAR(10) 
					ELSE INV.ADDRESS_1 + CHAR(13) + CHAR(10) + INV.ADDRESS_2 + CHAR(13) + CHAR(10) 
					END 
			) + RTRIM(INV.CITY) + '    ' + RTRIM(INV.STATE) + '   ' + INV.ZIP 
		) AS CONSIGNEEADDRESSMEMO, 
	INV.ADDRESS_1 AS CONSIGNEEADDRESS_1, 
	NULL AS CONSIGNEEADDRESS_2, 
	INV.CITY AS CONSIGNEECITY, 
	INV.STATE AS CONSIGNEESTATE, 
	CAST (INV.ZIP AS VARCHAR) AS CONSIGNEEZIP, 
	TRIM(INV.CITY) + ', ' + TRIM(INV.STATE) AS CONSIGNEECITYSTATE, 
	NULL AS CONSIGNEETELEPHONE_1, 
	INV.INVOICENUMBER AS TRANSACTIONNUMBER,
	INV.DATEINVOICED AS INVOICEDATE,	--	OH.INVOICEDATE,
	INV.REQUESTDATE,	--	OH.SHIPPINGDATE AS REQUESTDATE,
	INV.REQUESTDATETYPE,	--	OH.USERDEFINEDCODE_1 AS REQUESTDATETYPE,
	INV.ORDERUNITPRICE,	--	DBO.FN_ORDERVALUE(OH.ROWID,'UNITPRICE') AS ORDERUNITPRICE,
	INV.MERCHANDISETOTAL AS ORDERITEMPRICE,	--	DBO.FN_ORDERVALUE(OH.ROWID,'ITEMPRICE') AS ORDERITEMPRICE,
	INV.ORDERVALUE AS ORDERTOTAL	--	DBO.FN_ORDERVALUE(OH.ROWID,NULL) AS ORDERTOTAL

--FROM GNC_INVOICELIST_2021 INV (NOLOCK)	--ePlant 06/18/21 orders were never invoiced, Draft Invoices created on 7/1/21
FROM GNC_INVOICELIST_2021_JUN18 INV (NOLOCK)	--ePlant 06/18/21 orders were never invoiced, AR Records exist for them as 6/18/21

LEFT JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERIDENTITYID = TRIM(CAST (INV.CUSTOMERNUMBER AS VARCHAR))	--VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER
--LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER
--LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
--LEFT JOIN IDCODES IDC (NOLOCK) ON IDC.CODETYPE = '3M' AND IDC.CODE = ICONS.USERDEFINEDCODE_12 --TERRITORY
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = TRIM(CAST (INV.DIVISIONNUMBER AS VARCHAR))	--WH.ROWID = OH.R_FMSHIPPER
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
LEFT JOIN IDMASTER PART (NOLOCK) ON	PART.IDENTITYID = 'S'+RIGHT('00'+TRIM(CAST (INV.SALESREPID AS VARCHAR)),2)	--PART.ROWID = OH.R_SALESPERSON_1
