/*
--126 ROYALTY RATES REPORT
--Needs conversation with Steve Coppedge and Vicki Lake
--Distinct Fee list: Mktg Fee, SubLicense, Admin Fee, License Fee1, License Fee2,LH Fee
SELECT
VW_RPT_ROYALTY_RATE.*
FROM VW_RPT_ROYALTY_RATE (NOLOCK)
WHERE VW_RPT_ROYALTY_RATE.RECORDTYPE <> 'P'
AND (VW_RPT_ROYALTY_RATE.ISNEWLICENSE = 'Y'
OR VW_RPT_ROYALTY_RATE.INTERDIVFEE+VW_RPT_ROYALTY_RATE.SUBLICENSEFEE+VW_RPT_ROYALTY_RATE.LICENSEFEE>0)
*/
CREATE OR ALTER VIEW [dbo].[VW_RPT_ROYALTY_RATE]
AS

--INTERDIV SECTION--
SELECT	
	--ADDING FIELD FOR LANDON:
	IIF(VEND.IDENTITYID IS NOT NULL, 'Y', NULL) AS ISHOLDER,
	IIF(ITM.R_FEES IS NULL AND ITM.USERDEFINEDCODE_16 IS NOT NULL, 'Y', NULL) AS ISNEWLICENSE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME, 
	ITMP.PROFILECODE AS VARIETY,
	ITMP.DESCRIPTION AS VARIETYDESCRIPTION,
	ITM.RECORDTYPE,
	ITM.ITEMCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	CNT.PRINTEDCONTAINERCODE,
	VEND.IDENTITYID AS HOLDERID,
	VEND.NAME AS HOLDERNAME,
	ITM.USERDEFINEDCODE_16 AS LICENSEPRIMARY,	--IMCODETYPE 'C4'
	ITM.USERDEFINEDCODE_17 AS LICENSESECONDARY,	--IMCODETYPE 'C5'
	(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDER,
	(SELECT C5.DESCRIPTION_1 FROM IMCODES C5 (NOLOCK) WHERE C5.CODE = ITM.USERDEFINEDCODE_17 AND C5.CODETYPE = 'C5') AS LICSECONDARYHOLDER,
	ISNULL(FD.RATE,0) AS INTERDIVFEE,
	0 AS SUBLICENSEFEE,
	0 AS LICENSEFEE,
	ITM.USERDEFINEDCODE_2 AS BRAND
FROM IMITEM ITM (NOLOCK)
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	LEFT JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'INTERDIV%'
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR
	JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID NOT LIKE 'TAG%'	--AND ITM.ITEMCODE LIKE '000090%'
--AND FD.RATE IS NOT NULL

UNION ALL

--SUBLICENSE SECTION--
SELECT	
	--ADDING FIELD FOR LANDON:
	IIF(VEND.IDENTITYID IS NOT NULL, 'Y', NULL) AS ISHOLDER,
	IIF(ITM.R_FEES IS NULL AND ITM.USERDEFINEDCODE_16 IS NOT NULL, 'Y', NULL) AS ISNEWLICENSE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME, 
	ITMP.PROFILECODE AS VARIETY,
	ITMP.DESCRIPTION AS VARIETYDESCRIPTION,
	ITM.RECORDTYPE,
	ITM.ITEMCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	CNT.PRINTEDCONTAINERCODE,
	VEND.IDENTITYID AS HOLDERID,
	VEND.NAME AS HOLDERNAME,
	ITM.USERDEFINEDCODE_16 AS LICENSEPRIMARY,	--IMCODETYPE 'C4'
	ITM.USERDEFINEDCODE_17 AS LICENSESECONDARY,	--IMCODETYPE 'C5'
	(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDER,
	(SELECT C5.DESCRIPTION_1 FROM IMCODES C5 (NOLOCK) WHERE C5.CODE = ITM.USERDEFINEDCODE_17 AND C5.CODETYPE = 'C5') AS LICSECONDARYHOLDER,
	0 AS INTERDIVFEE,
	ISNULL(FD.RATE,0) AS SUBLICENSEFEE,
	0 AS LICENSEFEE,
	ITM.USERDEFINEDCODE_2 AS BRAND
FROM IMITEM ITM (NOLOCK)
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	LEFT JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'SUB%'
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR
	JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID NOT LIKE 'TAG%'	--AND ITM.ITEMCODE LIKE '000090%'
--AND FD.RATE IS NOT NULL

UNION ALL

--LICENSE SECTION--
SELECT	
	--ADDING FIELD FOR LANDON:
	IIF(VEND.IDENTITYID IS NOT NULL, 'Y', NULL) AS ISHOLDER,
	IIF(ITM.R_FEES IS NULL AND ITM.USERDEFINEDCODE_16 IS NOT NULL, 'Y', NULL) AS ISNEWLICENSE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME, 
	ITMP.PROFILECODE AS VARIETY,
	ITMP.DESCRIPTION AS VARIETYDESCRIPTION,
	ITM.RECORDTYPE,
	ITM.ITEMCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	CNT.PRINTEDCONTAINERCODE,
	VEND.IDENTITYID AS HOLDERID,
	VEND.NAME AS HOLDERNAME,
	ITM.USERDEFINEDCODE_16 AS LICENSEPRIMARY,	--IMCODETYPE 'C4'
	ITM.USERDEFINEDCODE_17 AS LICENSESECONDARY,	--IMCODETYPE 'C5'
	(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDER,
	(SELECT C5.DESCRIPTION_1 FROM IMCODES C5 (NOLOCK) WHERE C5.CODE = ITM.USERDEFINEDCODE_17 AND C5.CODETYPE = 'C5') AS LICSECONDARYHOLDER,
	0 AS INTERDIVFEE,
	0 AS SUBLICENSEFEE,
	ISNULL(FD.RATE,0) AS LICENSEFEE,
	ITM.USERDEFINEDCODE_2 AS BRAND
FROM IMITEM ITM (NOLOCK)
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	LEFT JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID AND FD.DESCRIPTION LIKE 'LICENSE%'
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR
	JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE
WHERE ITM.RECORDTYPE <> 'P' AND WH.IDENTITYID NOT LIKE 'TAG%'	--AND ITM.ITEMCODE LIKE '000090%'
--AND FD.RATE IS NOT NULL

--------------------------------------------------------------------------------------------------------------
-- PROTOTYPE DATASET FOR NEW REPORT CONCEPT MIGHT CREATE A REPORT LAYOUT FOR DISCUSSION IN UPCOMING MEETING --
--------------------------------------------------------------------------------------------------------------
/*
SELECT
	ITM.RECORDTYPE,
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	WH.IDENTITYID AS WAREHOUSEID,
	WH.NAME AS WAREHOUSENAME,
	VEND.IDENTITYID AS HOLDERID,
	VEND.NAME AS HOLDERNAME,
	ITM.USERDEFINEDCODE_16 AS LICENSEPRIMARY,	--IMCODETYPE 'C4'
	ITM.USERDEFINEDCODE_17 AS LICENSESECONDARY,	--IMCODETYPE 'C5'
	(SELECT C4.DESCRIPTION_1 FROM IMCODES C4 (NOLOCK) WHERE C4.CODE = ITM.USERDEFINEDCODE_16 AND C4.CODETYPE = 'C4') AS LICPRIMARYHOLDER,
	(SELECT C5.DESCRIPTION_1 FROM IMCODES C5 (NOLOCK) WHERE C5.CODE = ITM.USERDEFINEDCODE_17 AND C5.CODETYPE = 'C5') AS LICSECONDARYHOLDER,
	ITMP.PROFILECODE AS VARIETY,
	ITMP.DESCRIPTION VARIETYDESCRIPTION,
	ITM.ITEMCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	CNT.PRINTEDCONTAINERCODE,
	'SOURCE?' AS SUB,
	ITM.USERDEFINEDCODE_2 AS BRAND,
	FH.MISCFEECODE,
	FH.STATUS AS FEESTATUS,
	FD.DESCRIPTION AS FEEDESCRIPTION,
	FD.CALCULATIONMETHOD AS CALCMETHOD,
	(SELECT	FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) WHERE FLAGVALUE = FD.CALCULATIONMETHOD AND TABLENAME = 'IMFEESDETAIL' AND FIELDNAME = 'CALCULATIONMETHOD') AS CALCMETHODDESC,
	FD.EFFECTIVESTARTDATE,
	FD.RATE,
	FD.APPLYONDISCOUNTS,
	(SELECT AC.ACCOUNT FROM ACACCOUNT AC (NOLOCK) WHERE AC.ROWID = FD.R_EXPENSEGLACCOUNT) AS EXPENSEACCOUNT,
	(SELECT AC.ACCOUNT FROM ACACCOUNT AC (NOLOCK) WHERE AC.ROWID = FD.R_REVENUEGLACCOUNT) AS REVENUEGLACCOUNT,
	FD.WRITEAP
FROM IMITEM ITM (NOLOCK)
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
	LEFT JOIN IMFEESHEADER FH (NOLOCK) ON FH.ROWID = ITM.R_FEES
	LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID --AND FD.DESCRIPTION LIKE 'LICENSE%'
	LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR
	JOIN IMITEMDP ITMP (NOLOCK) ON ITMP.ROWID = ITM.R_PROFILE
WHERE ITM.R_FEES = FH.ROWID
AND WH.IDENTITYID NOT LIKE 'TAG%'
*/
--SELECTION CRITERIA: MAY BE TRICKY FOR THOSE UNFAMILIAR WITH THE VARIATIONS.
--BELOW ARE FIELDS THAT ARE CRITICAL DEPENDING UPON WHAT YOU ARE SEEKING:
--PROFILE
--LICENSOR
--WH
--VENDOR
--ITEM
--EFF DATES
--FEE CODE
--FEE BEGINS WITH S

--NOTE: THERE ARE INSTANCES WHERE IN ONE FEE CODE WE ARE PAYING MORE THAN ONE VENDOR FOR THE LICENSE FEE 1.

--SUBTOTAL TRICKY?
