/*
--PO ORDER
SELECT * 
FROM VW_RPT_POORDER (NOLOCK) 
WHERE RECORDTYPE <> 'P' 
--and itemcode = '000450.030.1'
*/
CREATE OR ALTER VIEW [dbo].[VW_RPT_POORDER]
AS
SELECT 
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	PH.RECORDTYPE,
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
	TRIM(SHIPTO.IDENTITYID) AS DIVISION,
	TRIM(SHIPTO.NAME) AS DIVISIONNAME,
	TRIM(VENDOR.IDENTITYID) AS VENDOR,
	TRIM(VENDOR.NAME) AS VENDORNAME,
	PH.PONUMBER AS PONUMBER,
	LOT.LOTCODE,
	PD.USERDEFINEDREFERENCE_1 AS PRODSCHLINE#,
	PD.USERDEFINEDREFERENCE_4 AS POLINECOMMENTS,
	PH.USERDEFINEDCODE_5 AS SALESYEAR,
	PH.USERDEFINEDCODE_1 AS SOURCE, 
	--PH.USERDEFINEDCODE_6 AS [CROPPRE-POST],
	PH.USERDEFINEDCODE_6 AS PREPOST,
	ITM.ITEMCODE,
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUPCODE, 
	ITM.REFERENCE_1 AS COMMONNAME,
	CNT.PRINTEDCONTAINERCODE AS CONTAINERSIZE,
	ITM.USERDEFINEDCODE_1 AS GENUS,
	(	SELECT PROFILECODE 
		FROM POORDERHEADERDP (NOLOCK) 
		WHERE ROWID = PH.R_PROFILE
		) AS PROFILECODE,
	LOT.USERDEFINEDCODE_3 AS HOLDSTOP,
	ISNULL(PD.ORDEREDQUANTITY,0) AS ORDERED,
	(	SELECT IN_ORDERED FROM VW_IMLOTINVENTORYSTATUS (NOLOCK) 
		WHERE R_LOT = LOT.ROWID
		) AS PENDINGRECEIPTS,
	ISNULL(PD.BACKORDERQUANTITY,0) AS BACKORDERED,
	(	SELECT ISNULL(SUM(ISNULL(RECEIVEDQUANTITY,0)),0) 
		FROM PORECEIPTSDETAIL (NOLOCK)
		WHERE R_POORDERDETAIL = PD.ROWID 
		AND RECORDTYPE <> 'Z'
		) AS INRECEIVING,
	(	SELECT ISNULL(SUM(ISNULL(RECEIVEDQUANTITY,0)),0) 
		FROM PORECEIPTSDETAIL (NOLOCK)
		WHERE R_POORDERDETAIL = PD.ROWID 
		AND RECORDTYPE = 'Z'
		) AS RECEIVED,
	(	SELECT ISNULL(SUM(ISNULL(RECEIVEDQUANTITY,0)),0) 
		FROM PORECEIPTSDETAIL (NOLOCK)
		WHERE R_POORDERDETAIL = PD.ROWID 
		) AS TOTALRECEIPTS,
	PH.STATUS,
	ISNULL(	 -- Partially Received is missing as an option so Null will default to it for now. per Ellen
	(	SELECT FLAGDESCRIPTION
		FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME = 'POORDERHEADER' 
		AND FIELDNAME = 'STATUS' 
		AND FLAGVALUE = PH.STATUS
		), 'Partially Received') AS STATUSDESC,
	(	SELECT TOP 1 ISNULL(USERDEFINEDREFERENCE_3 ,'') 
		FROM PORECEIPTSDETAIL (NOLOCK)
		WHERE R_POORDERDETAIL = PD.ROWID 
		) AS TRANSTEXT,
	--NEW FIELDS:
	--Add 'UserCalculated_6'	--Season OnHand: 
	DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_6', LOT.ROWID, ITM.ROWID) AS SEASON_OH,
	LOT.USERDEFINEDREFERENCE_4 AS HOLDREASON,
	LOT.USERDEFINEDDATE_4 AS REASONSTARTDATE,
	PD.USERDEFINEDREFERENCE_1 AS PSLINE
FROM POORDERHEADER PH (NOLOCK) 
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = PH.COMPANYID
LEFT JOIN POORDERDETAIL PD (NOLOCK) ON PD.R_PURCHASEORDERHEADER = PH.ROWID
LEFT JOIN IDMASTER VENDOR (NOLOCK) ON VENDOR.ROWID = PH.R_VENDOR 
LEFT JOIN IDMASTER SHIPTO (NOLOCK) ON SHIPTO.ROWID = PH.R_SHIPTO 
LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PD.R_ITEM 
LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = PD.R_LOT 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
