/*	DATA ERRORS: THESE HAVE TWO RELATIONSHIPLINKS SO THEY APPEAR TWICE IN THIS VIEW
		CONSIGNEEID:789427	'HEB 0233'
			SELECT * FROM IDRELATIONSHIPLINKS LCONS (NOLOCK) WHERE LCONS.R_IDMEMBER = 'C5C8B9D7-B31B-48E5-BAC0-33F4FD9FA647'
		CONSIGNEEID:829309	'Kroger #0577'
			SELECT * FROM IDRELATIONSHIPLINKS LCONS (NOLOCK) WHERE LCONS.R_IDMEMBER = '38CB88D5-68C8-4D9A-8930-948414E9127E'

--38 CONSIGNEE LISTING EXCEL
SELECT *
FROM VW_RPT_CONSIGNEE_LISTING (NOLOCK)
WHERE RECORDTYPE <> 'P'
--
AND CONSIGNEENAME = 'SiteOne Lds 172/R08 Alpharetta, GA'
and customergroup = '90'
and consigneeid = '57880'--'828385'
AND CUSTOMERGROUP <> CONSIGNEEGROUP
and CONSIGNEEid = '829309'--'789427'--'829162'--'10129'
ORDER BY CONSIGNEEID
*/	
/*	test Consignee Listing by KeyRep EXCEL:
SELECT 
	CUST.RECORDTYPE,
	------------------------------
	--CUSTOMER FIELDS--
	(	SELECT MC.IDENTITYID FROM IDMASTER MC (NOLOCK) 
		WHERE MC.ROWID = DBO.FN_MASTERCUSTOMER(CUST.ROWID,NULL)
		) AS MASTERCUSTOMERID,
	TRIM(CUST.IDENTITYID) AS CUSTOMERID,
	TRIM(CUST.NAME) AS CUSTOMERNAME,
	TRIM(CUST.IDGROUP) AS CUSTOMERGROUP,
	--CONSIGNEE FIELDS--
	TRIM(CONS.IDGROUP) AS CONSIGNEEGROUP,
	GRPCONS.DESCRIPTION_1 AS CONSIGNEEGROUPNAME,
	TRIM(CONS.IDENTITYID) AS CONSIGNEEID,
	TRIM(CONS.NAME) AS CONSIGNEENAME,

	--KEYREP FIELDS--
	ISNULL(KREP.IDENTITYID,'') AS KEYREP,
	ISNULL(KREP.NAME,'') AS KEYREPNAME
FROM IDMASTER CONS (NOLOCK)
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID
----WHAT CUST IS LINKED TO CONS? (REVERSE LOOKUP OF RELATIONSHIPS STARTING WITH CONSIGNEES SO NO CONSIGNEE DATA IS BLANK)
LEFT JOIN IDRELATIONSHIPLINKS LCONS (NOLOCK) ON LCONS.R_IDMEMBER = CONS.ROWID AND LCONS.IDMASTERTYPE = '01' AND LCONS.IDMEMBERTYPE = '02'
LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = ISNULL(LCONS.R_IDMASTER, ICONS.R_IDENTITY)	-- AND ADD THESE CUSTOMERS TO THE LIST
LEFT JOIN IDCODES GRPCONS (NOLOCK) ON GRPCONS.CODE = CONS.IDGROUP AND GRPCONS.CODETYPE = 'Z7'	--CONSIGNEEGROUPNAME
	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO THIS WILL CREATE DUPLICATE CUSTOMER RECORDS.
	LEFT JOIN IDRELATIONSHIPLINKS LKREP (NOLOCK) ON LKREP.R_IDMASTER = CUST.ROWID AND LKREP.IDMEMBERTYPE = '14'
	LEFT JOIN IDMASTER KREP (NOLOCK) ON KREP.ROWID = LKREP.R_IDMEMBER 
WHERE CUST.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_CONSIGNEE_LISTING]
AS
SELECT 
	CUST.ROWID AS CUSTROWID, 
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	CONS.RECORDTYPE,
	------------------------------
	--DON'S EDI FIELDS--
	--ICUST.USERDEFINEDCODE_9 AS EDICUST,
	--ICUST.USERDEFINEDCODE_3 AS EDIROLLUP,
	--ICUST.USERDEFINEDCODE_7 AS EDIWOREQ,
	--(SELECT IDENTITYID FROM IDMASTER (NOLOCK) WHERE ROWID = ICUST.USERDEFINEDREFERENCE_10) AS EDIVENDOR,

	--IDENTITY FIELDS--
	TRIM(CUST.IDENTITYID) AS CUSTOMERID,
	TRIM(CUST.NAME) AS CUSTOMERNAME,
	TRIM(CUST.IDGROUP) AS CUSTOMERGROUP,
	GRP.DESCRIPTION_1 AS CUSTOMERGROUPNAME,
	ACUST.ADDRESS_1 AS CUSTOMERADDRESS_1,
	ACUST.ADDRESS_2 AS CUSTOMERADDRESS_2,
	TRIM(ACUST.CITY) AS CUSTOMERCITY,
	TRIM(ACUST.STATE) AS CUSTOMERSTATE,
	ACUST.ZIP AS CUSTOMERZIP,
	ACUST.COUNTY AS CUSTOMERCOUNTY,
	ACUST.COUNTRY AS CUSTOMERCOUNTRY,
	TRIM(CRMGR.IDENTITYID) AS CREDITMANAGERID, 
	TRIM(CRMGR.NAME) AS CREDITMANAGERNAME,

	--CUSTOMER FIELDS--	ADDED PER STEVE COPPEDGE
	ICUST.STATUS AS CUSTOMERSTATUS,
	CUST.REFERENCE2 AS SORTNAME,--VARIETY
	ICUST.OMREQUIREPO AS REQUIREPO,
	ICUST.USERDEFINEDCODE_7 AS EDIWOREQUIRED,
	ICUST.USERDEFINEDCODE_10 AS TOP10,
	ICUST.USERDEFINEDREFERENCE_3 AS MAILINGS,
	ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS MAJORACCT,
	ICUST.OMSENDEMAIL AS AUTOEMAIL_INV,
	(	SELECT COMMENT FROM IDSYNONYMS SYN (NOLOCK) 
		WHERE SYN.R_IDENTITY=CUST.ROWID AND SYN.USERDEFINEDCODE_1='INV'
		) AS SYNINVOICEEMAIL,
	TRIM(IDTERMS.TERMSCODE) AS TERMSCODE,
	IDTERMS.DESCRIPTION_1 AS TERMSDESCRIPTION,
	ICUST.USERDEFINEDREFERENCE_6 AS DELAYED_DUE_1, 
	ICUST.USERDEFINEDREFERENCE_7 AS DELAYED_DUE_2, 
	ICUST.RESALENUMBER AS TAX_EXEMPT_#,
	ICUST.USERDEFINEDDATE_2 AS TAX_EXEMPT_DATE,
	ICUST.USERDEFINEDCODE_11 AS COMBINE_FOR_VIP,
	ICUST.CUSTOMERPURCHASEDISCOUNT, 
	(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME = 'IDCUSTOMER' AND FIELDNAME = 'DISCOUNTTYPE' AND FLAGVALUE = ICUST.DISCOUNTTYPE
		) AS DISCOUNT_APPLIES,--GETTING DESCRIPTION FROM CODE
	ICUST.USERDEFINEDCODE_1 AS DISCOUNTTYPE,
	ICUST.USERDEFINEDCODE_5 AS MAJORCOMMTYPE,
	ICUST.USERDEFINEDCODE_6 AS GROUPAPPROVALREQUIRED,
	ISNULL(ICUST.USERDEFINEDCODE_9, 'N') AS EDICUSTOMER,
	ICUST.USERDEFINEDCODE_3 AS EDIROLLUP,
	ICUST.USERDEFINEDCODE_12 AS ACKVERSION,
	ICUST.USERDEFINEDCODE_13 AS DELVERSION,
	ICUST.USERDEFINEDCODE_14 AS INVVERSION,
	ACKVERSION.CODE AS ACKVERSIONCODE, ACKVERSION.DESCRIPTION_1 AS ACKVERSIONDESC, ACKVERSION.DESCRIPTION_2 AS ACKVERSIONSORT,
	DELVERSION.CODE AS DELVERSIONCODE, DELVERSION.DESCRIPTION_1 AS DELVERSIONDESC, DELVERSION.DESCRIPTION_2 AS DELVERSIONSORT,
	INVVERSION.CODE AS INVVERSIONCODE, INVVERSION.DESCRIPTION_1 AS INVVERSIONDESC, INVVERSION.DESCRIPTION_2 AS INVVERSIONSORT,
	(	SELECT FLAGDESCRIPTION FROM ABFLAGFIELD (NOLOCK) 
		WHERE TABLENAME='IDCUSTOMER' AND FIELDNAME='CREDITSTATUSFLAG' AND FLAGVALUE=ICUST.CREDITSTATUSFLAG
		) AS CREDITSTATUS,
	ICUST.CREDITRATING,
	ICUST.CREDITLIMIT,

	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO IT IS NOT INCLUDED IN THE DATASET.
	--(	SELECT KREP.IDENTITYID 
	--	FROM IDRELATIONSHIPLINKS LKREP (NOLOCK)
	--	JOIN IDMASTER KREP ON KREP.ROWID = LKREP.R_IDMEMBER 
	--	WHERE LKREP.R_IDMASTER = CUST.ROWID 
	--	AND LKREP.IDMEMBERTYPE = '14'
	--) AS KEYREP,
	--(	SELECT KREP.NAME 
	--	FROM IDRELATIONSHIPLINKS LKREP (NOLOCK) 
	--	JOIN IDMASTER KREP ON KREP.ROWID = LKREP.R_IDMEMBER 
	--	WHERE LKREP.R_IDMASTER = CUST.ROWID 
	--	AND LKREP.IDMEMBERTYPE = '14'
	--) AS KEYREPNAME,


-------------------------------------------------------------------------------------------------

	--CONSIGNEE FIELDS--
	TRIM(CONS.IDGROUP) AS CONSIGNEEGROUP,
	GRPCONS.DESCRIPTION_1 AS CONSIGNEEGROUPNAME,
	TRIM(CONS.IDENTITYID) AS CONSIGNEEID,
	TRIM(CONS.NAME) AS CONSIGNEENAME,
	ACONS.ADDRESS_1 AS CONSIGNEEADDRESS_1,
	ACONS.ADDRESS_2 AS CONSIGNEEADDRESS_2,
	TRIM(ACONS.CITY) AS CONSIGNEECITY,
	TRIM(ACONS.STATE) AS CONSIGNEESTATE,
	ACONS.ZIP AS CONSIGNEEZIP,
	--ACONS.COUNTY AS CONSIGNEECOUNTY,
	ICONS.USERDEFINEDREFERENCE_3 CONSIGNEECOUNTY,
	ACONS.COUNTRY AS CONSIGNEECOUNTRY,
	TRIM(PART.IDENTITYID) AS SALESREPID,
	TRIM(PART.NAME) AS SALESREPNAME,
	ICONS.USERDEFINEDCODE_12 AS TERRITORYCODE,
	TERR.DESCRIPTION_1 AS TERRITORYDESC,
	CAST (ISNULL(ICONS.USERDEFINEDREFERENCE_20, 0) AS INT) AS CADiscPercent, --added per SC 12/15/22 
	ISNULL(ICONS.USERDEFINEDREFERENCE_18, 'N') AS CustMajorAcct,  --added per SC 12/15/22 
	ICONS.USERDEFINEDCODE_4 AS AUTOEMAILACK,
	(	SELECT COMMENT FROM IDSYNONYMS SYN (NOLOCK) 
		WHERE SYN.R_IDENTITY=CONS.ROWID AND SYN.USERDEFINEDCODE_1='ACK'
		) AS SYNEMAILACK,
	ICONS.USERDEFINEDCODE_3 AS CONSIGNEETYPE,
	ICONS.USERDEFINEDREFERENCE_2 AS STORENUMBER,
	ICONS.USERDEFINEDCODE_10 AS TAGCODE,
	ICONS.USERDEFINEDCODE_11 AS QACODE,
	ICONS.STATUS AS CONSIGNEESTATUS,
	(	SELECT TRIM(ZON.CODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '10'
		JOIN RTZONETABLECODES ZON (NOLOCK) ON ZON.ROWID = SZ.R_ZONE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS PHFREIGHTZONE,
	(	SELECT TRIM(ZON.CODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '20'
		JOIN RTZONETABLECODES ZON (NOLOCK) ON ZON.ROWID = SZ.R_ZONE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS TXFREIGHTZONE,
	(	SELECT TRIM(ZON.CODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '40'
		JOIN RTZONETABLECODES ZON (NOLOCK) ON ZON.ROWID = SZ.R_ZONE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS NCFREIGHTZONE,
	(	SELECT TRIM(PSH.PRICESCHEDULECODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '10'
		JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = SZ.R_PRICESCHEDULE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS PHPRICESCHEDULE,
	(	SELECT TRIM(PSH.PRICESCHEDULECODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '20'
		JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = SZ.R_PRICESCHEDULE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS TXPRICESCHEDULE,
	(	SELECT TRIM(PSH.PRICESCHEDULECODE) FROM IDCONSIGNEESHIPPERZONE SZ (NOLOCK) JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = '40'
		JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = SZ.R_PRICESCHEDULE
		WHERE SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
	) AS NCPRICESCHEDULE,
	(SELECT TAXCODE FROM IDTAXHEADER (NOLOCK) WHERE IDTAXHEADER.ROWID = ICONS.R_TAX) AS TAXCODE, 
	ICONS.USERDEFINEDREFERENCE_1 AS NSY_LIC_NO, 
	ICONS.USERDEFINEDREFERENCE_12 AS NSY_LIC_EXP, 
	ICONS.COMMENT AS GENERALLOADINSTR,
	ICONS.USERDEFINEDREFERENCE_8 AS OKLOADINST, --PERMSHIPINSPH,
	ICONS.USERDEFINEDREFERENCE_9 AS TXLOADINST, --PERMSHIPINSTX,
	ICONS.USERDEFINEDREFERENCE_10 AS NCLOADINST, --PERMSHIPINSNC,
	--ICONS.USERDEFINEDREFERENCE_11 AS FGLOADINST, --PERMSHIPINSFG,	--SC DID NOT WANT
	ICONS.DIRECTIONS AS DRIVERDIRECTIONS,
	ICONS.USERDEFINEDREFERENCE_7 AS CONSIGNEEDELIVERYNOTE,
	--ALL CONTACT FIELDS BY CONTACT TYPE:
	TRIM(C1CONT.IDENTITYID) AS PRIMARYCONTACTID, 
	TRIM(C1CONT.NAME) AS PRIMARYCONTACTNAME, 
	C1ADDR.TELEPHONE_1 AS PRIMARYCONTACTPHONE, 
	C1ADDR.CELLPHONE_1 AS PRIMARYCONTACTCELL, 
	C1ADDR.FAX_1 AS PRIMARYCONTACTFAX, 
	C1ADDR.EMAILADDRESS_1 AS PRIMARYCONTACTEMAIL, 
	TRIM(C2CONT.IDENTITYID) AS SECONDARYCONTACTID, 
	TRIM(C2CONT.NAME) AS SECONDARYCONTACTNAME, 
	C2ADDR.TELEPHONE_1 AS SECONDARYCONTACTPHONE, 
	C2ADDR.CELLPHONE_1 AS SECONDARYCONTACTCELL, 
	C2ADDR.FAX_1 AS SECONDARYCONTACTFAX, 
	C2ADDR.EMAILADDRESS_1 AS SECONDARYCONTACTEMAIL, 
	TRIM(C3CONT.IDENTITYID) AS PRINCIPALCONTACTID, 
	TRIM(C3CONT.NAME) AS PRINCIPALCONTACTNAME, 
	C3ADDR.TELEPHONE_1 AS PRINCIPALCONTACTPHONE, 
	C3ADDR.CELLPHONE_1 AS PRINCIPALCONTACTCELL, 
	C3ADDR.FAX_1 AS PRINCIPALCONTACTFAX, 
	C3ADDR.EMAILADDRESS_1 AS PRINCIPALCONTACTEMAIL, 
	TRIM(C4CONT.IDENTITYID) AS BILLINGCONTACTID, 
	TRIM(C4CONT.NAME) AS BILLINGCONTACTNAME, 
	C4ADDR.TELEPHONE_1 AS BILLINGCONTACTPHONE, 
	C4ADDR.CELLPHONE_1 AS BILLINGCONTACTCELL, 
	C4ADDR.FAX_1 AS BILLINGCONTACTFAX, 
	C4ADDR.EMAILADDRESS_1 AS BILLINGCONTACTEMAIL, 
	TRIM(C5CONT.IDENTITYID) AS SHIPPINGCONTACTID, 
	TRIM(C5CONT.NAME) AS SHIPPINGCONTACTNAME, 
	C5ADDR.TELEPHONE_1 AS SHIPPINGCONTACTPHONE, 
	C5ADDR.CELLPHONE_1 AS SHIPPINGCONTACTCELL, 
	C5ADDR.FAX_1 AS SHIPPINGCONTACTFAX, 
	C5ADDR.EMAILADDRESS_1 AS SHIPPINGCONTACTEMAIL, 
--NEW FIELD USED IN WORKING MANIFEST: LIST OF SHIPPING CONTACT INFO(USUALLY EMAIL ADDRESSES) 
	C5ICONT.USERDEFINEDCOMMENT AS SHIPPINGCONTACTCOMMENTSTRING 
--------------
	----CONTACT FIELDS--	(C5 FOR CUSTOMERS):
	--TRIM(CCONT.IDENTITYID) AS CONTACTID,
	--TRIM(CCONT.NAME) AS CONTACTNAME,
	--ICONT.USERDEFINEDCODE_1 AS CONTACTROLE,
	--ACONT.ADDRESS_1 AS CONTACTADDRESS_1,
	--ACONT.ADDRESS_2 AS CONTACTADDRESS_2,
	--TRIM(ACONT.CITY) AS CONTACTCITY,
	--TRIM(ACONT.STATE) AS CONTACTSTATE,
	--ACONT.ZIP AS CONTACTZIP,
	--ACONT.COUNTRY AS CONTACTCOUNTRY,
	--ACONT.TELEPHONE_1 AS CONTACTTELEPHONE_1,
	--ACONT.CELLPHONE_1 AS CONTACTCELLPHONE_1,
	--ACONT.FAX_1 AS CONTACTFAX_1,
	--ACONT.EMAILADDRESS_1 AS CONTACTEMAILADDRESS_1
FROM IDMASTER CONS (NOLOCK)
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID
JOIN IDTYPESLINKS TCONS (NOLOCK) ON TCONS.R_IDENTITY = CONS.ROWID AND TCONS.IDTYPE = '02'
JOIN IDADDRESS ACONS (NOLOCK) ON ACONS.ROWID = ISNULL(TCONS.R_ADDRESS, CONS.R_DEFAULTADDRESS)
----WHAT CUST IS LINKED TO CONS? (REVERSE LOOKUP OF RELATIONSHIPS STARTING WITH CONSIGNEES SO NO CONSIGNEE DATA IS BLANK)
LEFT JOIN IDRELATIONSHIPLINKS LCONS (NOLOCK) ON LCONS.R_IDMEMBER = CONS.ROWID AND LCONS.IDMASTERTYPE = '01' AND LCONS.IDMEMBERTYPE = '02'
LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = ISNULL(LCONS.R_IDMASTER, ICONS.R_IDENTITY)	-- AND ADD THESE CUSTOMERS TO THE LIST
LEFT JOIN IDTYPESLINKS TCUST (NOLOCK) ON TCUST.R_IDENTITY = CUST.ROWID AND TCUST.IDTYPE = '01'
LEFT JOIN IDADDRESS ACUST (NOLOCK) ON ACUST.ROWID = ISNULL(TCUST.R_ADDRESS, CUST.R_DEFAULTADDRESS)
LEFT JOIN IDMASTER CRMGR (NOLOCK) ON CRMGR.ROWID = CUST.R_CONTACT
LEFT JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'	--CUSTOMERGROUPNAME
LEFT JOIN IDCODES GRPCONS (NOLOCK) ON GRPCONS.CODE = CONS.IDGROUP AND GRPCONS.CODETYPE = 'Z7'	--CONSIGNEEGROUPNAME
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = CONS.COMPANYID
LEFT JOIN IDCODES TERR (NOLOCK) ON TERR.CODETYPE = '3M' AND TERR.CODE = ICONS.USERDEFINEDCODE_12 --TERRITORY
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT
--ADDITIONAL JOINS TO CUSTOMER DATA: (FIELDS ADDED PER STEVE COPPEDGE)
LEFT JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
LEFT JOIN IDTERMS (NOLOCK) ON IDTERMS.ROWID = ICUST.R_TERMS
LEFT JOIN IDCODES ACKVERSION (NOLOCK) ON ACKVERSION.CODE = ICUST.USERDEFINEDCODE_12 AND ACKVERSION.CODETYPE = '3C'
LEFT JOIN IDCODES DELVERSION (NOLOCK) ON DELVERSION.CODE = ICUST.USERDEFINEDCODE_13 AND DELVERSION.CODETYPE = '3D'
LEFT JOIN IDCODES INVVERSION (NOLOCK) ON INVVERSION.CODE = ICUST.USERDEFINEDCODE_14 AND INVVERSION.CODETYPE = '3E'
----CONSIGNEE CONTACTS	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
--LEFT JOIN IDMASTER CCONT (NOLOCK) ON CCONT.ROWID = DBO.FN_GETCONTACT(CONS.ROWID,'02','C5')
--LEFT JOIN IDCONTACTS ICONT (NOLOCK) ON ICONT.R_IDENTITY = DBO.FN_GETCONTACT(CONS.ROWID,'02','C5')
--LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(CONS.ROWID,'02','C5')
--ALL CONTACTS BY CONTACT TYPE:	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
LEFT JOIN IDMASTER C1CONT (NOLOCK) ON C1CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
LEFT JOIN IDADDRESS C1ADDR (NOLOCK) ON C1ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C1')
LEFT JOIN IDMASTER C2CONT (NOLOCK) ON C2CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C2')
LEFT JOIN IDADDRESS C2ADDR (NOLOCK) ON C2ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C2')
LEFT JOIN IDMASTER C3CONT (NOLOCK) ON C3CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C3')
LEFT JOIN IDADDRESS C3ADDR (NOLOCK) ON C3ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C3')
LEFT JOIN IDMASTER C4CONT (NOLOCK) ON C4CONT.ROWID = DBO.FN_GETCONTACT(CUST.ROWID,'01','C4')
LEFT JOIN IDADDRESS C4ADDR (NOLOCK) ON C4ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CUST.ROWID,'01','C4') -->FUNCTION BLOWS UP WHEN DUPLICATE CONTACTS ARE CREATED, SEE FUNCTION FOR TEMPORARY PATCH..
LEFT JOIN IDMASTER C5CONT (NOLOCK) ON C5CONT.ROWID = DBO.FN_GETCONTACT(CONS.ROWID,'02','C5')
LEFT JOIN IDADDRESS C5ADDR (NOLOCK) ON C5ADDR.R_IDENTITY = DBO.FN_GETCONTACT(CONS.ROWID,'02','C5')
LEFT JOIN IDCONTACTS C5ICONT (NOLOCK) ON C5ICONT.R_IDENTITY = C5CONT.ROWID --NEW FIELD USED IN WORKING MANIFEST: C5ICONT.USERDEFINEDCOMMENT LIST OF SHIPPING CONTACT INFO(USUALLY EMAIL ADDRESSES) 
WHERE CONS.RECORDTYPE <> 'P'

