/*
--192 OVERSELL PERCENTAGE
SELECT
VW_RPT_OVERSELL_PERCENTAGE.*
FROM VW_RPT_OVERSELL_PERCENTAGE (NOLOCK)
WHERE VW_RPT_OVERSELL_PERCENTAGE.RECORDTYPE <> 'P'
AND VW_RPT_OVERSELL_PERCENTAGE.OVERSELLPERCENTAGE<>0
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_OVERSELL_PERCENTAGE]
AS
SELECT
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	ITM.RECORDTYPE,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME,
	SUBSTRING(PC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
	PC.PRODUCTCATEGORYCODE AS PLANTGROUP,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	CNT.CONTAINERSORT,
	ITM.ITEMCODE,
	(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
	CNT.CONTAINERCODE,
	ITM.SUBCLASSCODE AS QUALITYCODE,
	CNT.PRINTEDCONTAINERCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	VLOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
	VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
	VLOT.LOTCODE,
	LEFT(VLOT.LOTCODE,2) AS LOTYEAR,
	SUBSTRING(VLOT.LOTCODE,4,2) AS LOTSEASON,
	ISNULL(LOT.OVERSELLPERCENTAGE, 0) AS OVERSELLPERCENTAGE,
	VLOT.ON_HAND,
	VLOT.IN_RECEIVING,
	VLOT.OUT_SHIPPED,
	VLOT.OUT_UNAVAILABLE,
	VLOT.AVAILABLE,

	VLOT.IN_ORDERED,
	VLOT.OUT_ORDERED,
	VLOT.IN_BACKORDER,
	VLOT.OUT_BACKORDER,
	VLOT.NETAVAILABLE,

	VLOT.IN_UNAVAILABLE,
	VLOT.IN_FUTURE,
	VLOT.OUT_FUTURE,
	DBO.FN_SUPPLY(ITM.ROWID,VLOT.ROWID,NULL) AS SUPPLY,
	DBO.FN_SUPPLY(ITM.ROWID,VLOT.ROWID, 'I') AS ISUPPLY,
	DBO.FN_DEMAND(ITM.ROWID,VLOT.ROWID) AS DEMAND,
	DBO.FN_SUPPLY(ITM.ROWID,VLOT.ROWID,NULL) - DBO.FN_DEMAND(ITM.ROWID,VLOT.ROWID) AS LTS,
	DBO.FN_SUPPLY(ITM.ROWID,VLOT.ROWID, 'I') - DBO.FN_DEMAND(ITM.ROWID,VLOT.ROWID) AS ILTS

FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = VLOT.ROWID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY

--ORDER BY
--		WH.IDENTITYID, 
--		ITM.ITEMCODE,
--		VLOT.LOTCODE
