/*
--55 FIELD MANIFEST
SELECT * FROM VW_RPT_FIELD_MANIFEST (NOLOCK)
WHERE RECORDTYPE <> 'P' AND TRIPNO > 'T08776'
ORDER BY WAREHOUSEID, TRIPNO, DELSTOPNO
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_FIELD_MANIFEST]
AS

--NEW CODE ELIMINATES FMDISPATCHOBJECTCONTENTS FROM THE VIEW WHICH WAS CAUSING ISSUES.

--CHRYSA	Chrysanthemum
SELECT *, 
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
	) AS MUMSTOPTOTAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 1
	) AS MUMSTOPCT,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 2
	) AS MUMSTOP6INCH,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 3
	) AS MUMSTOP1GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 4
	) AS MUMSTOP2GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 5
	) AS MUMSTOP3GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 6
	) AS MUMSTOP5GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 7
	) AS MUMSTOP7GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 8
	) AS MUMSTOP10GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 9
	) AS MUMSTOP15GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 10
	) AS MUMSTOP25GAL,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 11
	) AS MUMSTOPWHIP,
	(	SELECT SUM(IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0))) --QTYATSTAGE FOR ITEMS ON THIS STOP
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
		WHERE OH.TRANSACTIONNUMBER = TRACKINGNUMBER AND ITM.USERDEFINEDCODE_1 = 'CHRYSA'
		AND CHARINDEX(CNT.CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 0
	) AS MUMSTOPOTHER 

FROM (	
		SELECT *, 
			--PARSE ITEMCOUNTS INTO 10 DIFFERENT CONTAINERCLASS COLUMNS 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 1, QTYATSTAGE, 0) AS CNTCT, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 2, QTYATSTAGE, 0) AS CNT6INCH, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 3, QTYATSTAGE, 0) AS CNT1GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 4, QTYATSTAGE, 0) AS CNT2GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 5, QTYATSTAGE, 0) AS CNT3GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 6, QTYATSTAGE, 0) AS CNT5GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 7, QTYATSTAGE, 0) AS CNT7GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 8, QTYATSTAGE, 0) AS CNT10GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 9, QTYATSTAGE, 0) AS CNT15GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 10, QTYATSTAGE, 0) AS CNT25GAL, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 11, QTYATSTAGE, 0) AS CNTWHIP, 
			IIF(CHARINDEX(CONTAINERCLASS, '..CT QT #1 #2 #3 #5 #7 #10#15#25WH ')/3 = 0, QTYATSTAGE, 0) AS CNTOTHER 
		FROM ( 
				SELECT 
					OH.ROWID AS OMTRANSACTIONHEADERROWID, --ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
					OD.ROWID AS OMTRANSACTIONDETAILROWID, --ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
					CO.COMPANYID, 
					CO.NAME AS COMPANYNAME, 
					WH.IDENTITYID AS WAREHOUSEID, 
					WH.NAME AS WAREHOUSENAME, 
					HDR.RECORDTYPE, 
					(SELECT CARR.NAME FROM IDMASTER CARR (NOLOCK) WHERE CARR.ROWID = HDR.R_CARRIER) AS CARRIERNAME, 
					HDR.EQUIPMENT AS TRUCKTYPE, 
					HDR.PLANSTART AS TRIPSTART, 
					HDR.COMMENT AS TRIPNOTES, 
					--Replace Weight/Volume values with those in the Dispatch Object per DJ request - DT 06/29/21 
					--This was giving bad totals on 3/1/22 per DJ, switching back to Estimated extended values - DT 03/01/22 
					ISNULL(OBJ.WEIGHTORDERED,0) AS WEIGHT, 
					ISNULL(OBJ.CUBESORDERED,0) AS VOLUME, 
					ITM.NETWEIGHTQUANTITY * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS ESTIMATEDWEIGHT, 
					ITM.UNITVOLUMEQUANTITY * IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS ESTIMATEDVOLUME, 
					HDR.TRIPNO, 
					DTL.DELSTOPNO, 
					OBJ.TRACKINGNUMBER, ITM.ITEMCODE, 
					--After complaints that QA code is missing, I found that FIELD MANIFEST uses ICONS.UDC_11 
					-- and PULLTAGS uses the function. Which one do they want to use?????? 
					ICONS.USERDEFINEDCODE_11 AS QUALITYASSURANCECODE, 
					--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, NULL ,'QA CODE'), '') AS QACODE, 
					VCONS.ConsigneeIdentityID, 
					VCONS.ConsigneeName, 
					--WE ONLY CARE ABOUT THE ALTSHIP STATE:
					ISNULL(	(SELECT ALTSHIP.STATE FROM IDSYNONYMS ALTSHIP (NOLOCK) WHERE ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO), 
							VCONS.ConsigneeState
						) AS CONSIGNEESTATE, 
					VCONS.ConsigneeAddressMemo, 
					VCONS.ConsigneeAddress_1, 
					--RTRIM(VCONS.ConsigneeCity)+', '+VCONS.ConsigneeState+'  '+VCONS.ConsigneeZip AS CONSIGNEECITYSTATEZIP, 
					VCONS.ConsigneeTelephone_1, 

					--STOPNOTES CHANGING FROM DTL.COMMENT TO DTL.UDR4 + UDR5:
					--NULLIF(ISNULL(TRIM(REPLACE(SUBSTRING(DTL.COMMENT,1,50),CHAR(13)+CHAR(10),'')),'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,'  ') AS STOPNOTES, 
					NULLIF(ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,' ') AS STOPNOTES, 

					ICONS.COMMENT AS GENERALLOADINSTR, 
					(SELECT IIF(DATALENGTH(OH.COMMENT)<2,NULL,OH.COMMENT) FROM OMTRANSACTIONHEADER OH (NOLOCK) 
						WHERE OH.FMTRIPNUMBER = HDR.TRIPNO AND OH.TRANSACTIONNUMBER = OBJ.TRACKINGNUMBER) AS ORDERSHIPPINGINSTR, 
					CASE WH.IDENTITYID 
						WHEN 10 THEN ICONS.USERDEFINEDREFERENCE_8 
						WHEN 20 THEN ICONS.USERDEFINEDREFERENCE_9 
						WHEN 40 THEN ICONS.USERDEFINEDREFERENCE_10 
						WHEN 60 THEN ICONS.USERDEFINEDREFERENCE_11 
						ELSE NULL 
					END AS LOADINSTRUCTIONS,	--PERMSHIPNOTES, 
					CNT.CONTAINERCLASS, 
					IIF(CHARINDEX(OH.STAGE,'A;S;C')>0,ISNULL(OD.QUANTITYSHIPPED,0),ISNULL(OD.QUANTITYORDERED,0)) AS QTYATSTAGE, 
					OH.SETNO, 
					HDR.USERDEFINEDCODE_2 AS DOCK, 
					--ADDED REFERENCE FIELDS TO DETERMINE IF AN ITEM IS A MUM OR NOT:
					ITM.USERDEFINEDCODE_1 AS GENUSCODE,
					GEN.DESCRIPTION_1 AS GENUSNAME,
					NULL AS ADDONDATE --DON'T KNOW WHERE THIS LIVES. 
				FROM FMTRIPHEADER HDR (NOLOCK) 
				JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID 
				JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT 
				JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID			--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
				JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID	--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES 
				JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID 
				JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OBJ.R_SHIPPER 
				JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
				JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
				JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
				JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.ConsigneeMasterRowID = OBJ.R_CONSIGNEE 
				JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.ConsigneeMasterRowID 
			) X
	) Y
