/* WOT: 0:47 (62,522 ROWS) 
--SQL_BILLING_TRENDS 
SELECT * 
FROM VW_RPT_SQL_BILLING_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
AND ISCURRYEAR = 'Y' 
AND ISCURRPERIOD = 'Y'	-->RT= 0:47 (2,081 ROWS) 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_BILLING_TRENDS] 
AS 
SELECT 
IIF(X.SALEYEAR = DBO.FN_DATE2YEAR(NULL),'Y', NULL) AS ISCURRYEAR, 
IIF(X.PERIOD = DBO.FN_DATE2PERIOD(NULL),'Y', NULL) AS ISCURRPERIOD, 
'R' AS RECORDTYPE, 
'SB' AS COMPANYID, 
X.SALEYEAR, 
X.PERIOD, 
-------------------------- 
X.TRANSACTIONDATE, 
S.REPORTNET, 
S.REPORTGROSS, 
S.REPORTGROUP, 
S.REPORTLINE, 
S.REPORTNETDESC, 
S.REPORTGROSSDESC, 
S.REPORTGROUPDESC, 
S.REPORTLINEDESC, 
X.WAREHOUSEID, 
ISNULL(X.NATIONALACCOUNT, 'N') AS NATIONALACCOUNT, 
X.SALESREPID, 
X.SALESREPNAME, 
X.CURRAMOUNT, 
IIF(X.WAREHOUSEID='10', X.CURRAMOUNT, 0) AS CURRAMOUNT10, 
IIF(X.WAREHOUSEID='20', X.CURRAMOUNT, 0) AS CURRAMOUNT20, 
IIF(X.WAREHOUSEID='40', X.CURRAMOUNT, 0) AS CURRAMOUNT40, 
IIF(X.WAREHOUSEID='60', X.CURRAMOUNT, 0) AS CURRAMOUNT60, 
X.PREVAMOUNT, 
IIF(X.WAREHOUSEID='10', X.PREVAMOUNT, 0) AS PREVAMOUNT10, 
IIF(X.WAREHOUSEID='20', X.PREVAMOUNT, 0) AS PREVAMOUNT20, 
IIF(X.WAREHOUSEID='40', X.PREVAMOUNT, 0) AS PREVAMOUNT40, 
IIF(X.WAREHOUSEID='60', X.PREVAMOUNT, 0) AS PREVAMOUNT60
FROM	VW_RPT_SQL_STRUCTURE S (NOLOCK), 
		( 
		SELECT	DBO.FN_DATE2YEAR(CAST(CURRTRANSDATE AS DATE)) AS SALEYEAR, 
				PERIOD, 
				CAST(CURRTRANSDATE AS DATE) AS TRANSACTIONDATE, 
				REPORTGROUP, 
				REPORTLINE, 
				WAREHOUSEID, 
				TRIM(SALESREPID) AS SALESREPID, 
				TRIM(SALESREPNAME) AS SALESREPNAME, 
				NATIONALACCOUNT, 
				SUM (CURRAMOUNT) AS CURRAMOUNT, 
				SUM (PREVAMOUNT) AS PREVAMOUNT 
        FROM	( 
				--CURRENT YEAR DATA FROM INSIGHT: 
				SELECT	C.*, 
						C.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(C.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS C (NOLOCK) 
				WHERE	C.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		C.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM INSIGHT: 
				SELECT	L.*, 
						DBO.FN_DATE4NEXTYEAR(L.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(L.AMOUNT,0) AS PREVAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS L (NOLOCK) 
				WHERE	L.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		L.AMOUNT <> 0 
				UNION ALL 
				--CURRENT YEAR DATA FROM ePLANT: 
				SELECT	EC.*, 
						EC.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(EC.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT 
				FROM	VW_RPT_SQL_1 EC (NOLOCK) 
				WHERE	EC.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		EC.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM ePLANT: 
				SELECT	EL.*, 
						DBO.FN_DATE4NEXTYEAR(EL.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(EL.AMOUNT,0) AS PREVAMOUNT 
				FROM	VW_RPT_SQL_1 EL (NOLOCK) 
				WHERE	EL.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		EL.AMOUNT <> 0 
				) U 
		GROUP BY 
				U.SALEYEAR, 
				U.PERIOD, 
				CAST(CURRTRANSDATE AS DATE), 
				U.REPORTGROUP, 
				U.REPORTLINE, 
				U.WAREHOUSEID, 
				U.SALESREPID, 
				U.SALESREPNAME, 
				U.NATIONALACCOUNT 
		) X 
WHERE	S.REPORTLINE = X.REPORTLINE 
