/*
--PTR MISSINGFIELDS
SELECT * 
FROM VW_RPT_PTR_MISSINGFIELDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
-------------------------
ORDER BY COMPANYID, WAREHOUSEID, ITEMCODE, LOTCODE, ATTRIB DESC
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_PTR_MISSINGFIELDS]
AS
SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDCODE_5,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'SUSPEND' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_5,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_3,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'SUSPENDTO' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_3,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDCODE_4,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'SPECIAL PULLER' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_4,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_1,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'PULLTAGNOTE1' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_1,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_2,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'PULLTAGNOTE2' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_2,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDCODE_3,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'HOLD/STOP' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_3,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_4,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'HOLDREASONNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_4,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_6,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'INTERNALINVENTORYNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_6,'') AS VARCHAR(200))) 

UNION 

SELECT 
	CO.COMPANYID, WH.IDENTITYID AS WAREHOUSEID, ITM.ITEMCODE, LOT.LOTCODE, ITM.DESCRIPTION_1 AS SHORTCOMMON, ORA.NAME AS ATTRIB, 
	MCA.VALUE AS MC_VALUE, TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_7,'') AS VARCHAR(200))) AS ITEMLOT_VALUE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = ITM.COMPANYID
WHERE ORA.NAME = 'SALESNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST(ISNULL(LOT.USERDEFINEDREFERENCE_7,'') AS VARCHAR(200))) 

--ORDER BY CO.COMPANYID, WH.IDENTITYID, ITM.ITEMCODE, LOT.LOTCODE, ORA.NAME DESC


/*
LOT.USERDEFINEDCODE_5 AS SUSPEND, 
LOT.USERDEFINEDREFERENCE_3 AS SUSPENDTO, 
LOT.USERDEFINEDCODE_4 AS SPECIALPULLER, 
LOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1, 
LOT.USERDEFINEDREFERENCE_2 AS PULLTAGNOTE2, 
LOT.USERDEFINEDCODE_3 AS HOLDSTOP, 
LOT.USERDEFINEDREFERENCE_4 AS HOLDREASONNOTE, 
LOT.USERDEFINEDREFERENCE_6 AS INTERNALINVENTORYNOTE, 
LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE 
*/
--IN ('SUSPEND', 'SUSPENDTO', 'SPECIAL PULLER', 'PULLTAGNOTE1', 'PULLTAGNOTE2', 'HOLD/STOP', 'HOLDREASONNOTE', 'INTERNALINVENTORYNOTE', 'SALESNOTE')

/*
SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
MCA.VALUE AS MC_SUSPEND, LOT.USERDEFINEDCODE_5 AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'SUSPEND' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_5,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
MCA.VALUE AS MC_SUSPENDTO, LOT.USERDEFINEDREFERENCE_3 AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'SUSPENDTO' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_3,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
MCA.VALUE AS MC_SPECIALPULLER, LOT.USERDEFINEDCODE_4 AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'SPECIAL PULLER' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_4,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
MCA.VALUE AS MC_PULLTAGNOTE1, LOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'PULLTAGNOTE1' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_1,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
MCA.VALUE AS MC_PULLTAGNOTE2, LOT.USERDEFINEDREFERENCE_2 AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'PULLTAGNOTE2' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_2,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
MCA.VALUE AS MC_HOLDSTOP, LOT.USERDEFINEDCODE_3 AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'HOLD/STOP' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDCODE_3,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
MCA.VALUE AS MC_HOLDREASONNOTE, LOT.USERDEFINEDREFERENCE_4 AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'HOLDREASONNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_4,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
MCA.VALUE AS MC_INTERNALINVENTORYNOTE, LOT.USERDEFINEDREFERENCE_6 AS INTERNALINVENTORYNOTE, 
NULL AS MC_SALESNOTE, NULL AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'INTERNALINVENTORYNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_6,'') AS VARCHAR(200))) 

UNION

SELECT ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID AS WAREHOUSEID, 
NULL AS MC_SUSPEND, NULL AS SUSPEND, 
NULL AS MC_SUSPENDTO, NULL AS SUSPENDTO, 
NULL AS MC_SPECIALPULLER, NULL AS SPECIALPULLER, 
NULL AS MC_PULLTAGNOTE1, NULL AS PULLTAGNOTE1, 
NULL AS MC_PULLTAGNOTE2, NULL AS PULLTAGNOTE2, 
NULL AS MC_HOLDSTOP, NULL AS HOLDSTOP, 
NULL AS MC_HOLDREASONNOTE, NULL AS HOLDREASONNOTE, 
NULL AS MC_INTERNALINVENTORYNOTE, NULL AS INTERNALINVENTORYNOTE, 
MCA.VALUE AS MC_SALESNOTE, LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE 
FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
JOIN OMREVIEWATTRIBUTES ORA (NOLOCK) ON ORA.ROWID = MCA.R_ATTRIBUTE 
JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.ROWID = MCA.R_MASTERCODE 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM 
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = MC.R_LOT 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
WHERE ORA.NAME = 'SALESNOTE' 
AND TRIM(ISNULL(MCA.VALUE,'')) <> TRIM(CAST (ISNULL(LOT.USERDEFINEDREFERENCE_7,'') AS VARCHAR(200))) 
--IN ('SUSPEND', 'SUSPENDTO', 'SPECIAL PULLER', 'PULLTAGNOTE1', 'PULLTAGNOTE2', 'HOLD/STOP', 'HOLDREASONNOTE', 'INTERNALINVENTORYNOTE', 'SALESNOTE')

ORDER BY
ITM.ITEMCODE, LOT.LOTCODE, WH.IDENTITYID
*/