/*
WE ARE NOT USING THIS VIEW
WE ARE NOT USING THIS VIEW
WE ARE NOT USING THIS VIEW
--------------------------------
I DEVELOPED THIS VIEW AND STARTED CREATING THESE 4 REPORTS FROM IT, THEN IT WAS HANDED OVER TO ARGOS TO FINISH.
THEY CREATED ALL NEW VIEWS FOR EACH SEPARATE REPORT WHICH WILL BE HANDED BACK TO ME TO NORMALIZE AGAIN.
EVENTUALLY, IT COULD BE USEFUL TO RETURN TO MY ORIGINAL CONCEPT OF CREATING ONE VIEW FOR ALL 4 REPORTS.
I DON'T HAVE TIME FOR IT NOW....
--------------------------------
WE ARE NOT USING THIS VIEW
WE ARE NOT USING THIS VIEW
WE ARE NOT USING THIS VIEW

--58 FREIGHT PROFIT
SELECT
*
FROM VW_RPT_FREIGHT_PROFIT (NOLOCK)
WHERE VW_RPT_FREIGHT_PROFIT.RECORDTYPE <> 'P'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_FREIGHT_PROFIT]
AS
SELECT 
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
PART.IDENTITYID AS WAREHOUSE,
PART.NAME AS WAREHOUSENAME,
HDR.RECORDTYPE,
ISNULL(HDR.ACTUALSTART,HDR.PLANSTART) AS PLANSTART,
IIF	(DBO.FN_SALEYEAR(NULL) > DBO.FN_SALEYEAR(ISNULL(HDR.ACTUALSTART,HDR.PLANSTART)), 
	'PREVIOUS YEAR', 
	IIF	(DBO.FN_SALEYEAR(NULL)>DBO.FN_SALEYEAR(ISNULL(HDR.ACTUALSTART,HDR.PLANSTART)), 
		'THIS YEAR',
		'NEXT YEAR'
	)	) AS YEARTEXT,
IIF(DBO.FN_SALEYEAR(NULL) = DBO.FN_SALEYEAR(ISNULL(HDR.ACTUALSTART,HDR.PLANSTART)), '', NULL) AS ISTHISYEAR,
HDR.TRIPNO,
ISNULL(CARR.NAME, PART.NAME) AS CARRIERNAME, 
HDR.EQUIPMENT,
ISNULL(HDR.EQUIPMENT,'') AS TRUCKTYPE, --THIS NEEDS REVISITED
(SELECT SP.RATE FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'STLO-MILES' 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS RATEPERMILE,
ISNULL(HDR.MILESLOADED,0)+ISNULL(HDR.MILESUNLOADED,0) AS MILES,
(SELECT SUM(ISNULL(HDR.MILESLOADED,0)+ISNULL(HDR.MILESUNLOADED,0)) 
	FROM FMTRIPHEADER HDR (NOLOCK) 
	WHERE HDR.R_ORIGIN = PART.ROWID) AS WAREHOUSEMILES,
(SELECT COUNT(DISTINCT DET.R_DESTINATIONID) 
	FROM FMTRIPDETAIL DET (NOLOCK) 
	WHERE DET.R_TRIPHEADER IN 
	(SELECT HDR.ROWID 
		FROM FMTRIPHEADER HDR (NOLOCK) 
		WHERE HDR.R_ORIGIN = PART.ROWID)) AS WAREHOUSEDROPCOUNT,
(SELECT COUNT(DISTINCT DET.R_DESTINATIONID) 
	FROM FMTRIPDETAIL DET (NOLOCK) 
	WHERE DET.R_TRIPHEADER = HDR.ROWID) AS DROPCOUNT,
--DIVIDE DROPPAY BY DROPCOUNT - 1 TO GET DROPPAYPERDROP
(SELECT SUM(AMOUNT) 
	FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'DROP-PAY' 
	WHERE SP.R_SOURCEID = HDR.ROWID)
	/ 
	(SELECT IIF(COUNT(DISTINCT DET.R_DESTINATIONID) > 1, COUNT(DISTINCT DET.R_DESTINATIONID) - 1, 1)
		FROM FMTRIPDETAIL DET (NOLOCK) 
		WHERE DET.R_TRIPHEADER = HDR.ROWID)	AS DROPPAYPERDROP,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'DROP-PAY' 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS DROPPAY,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE NOT IN ('STLO-MILES', 'DROP-PAY') 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS COSTADJ,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) WHERE SP.R_SOURCEID = HDR.ROWID) AS FREIGHTEXPENSE,
(SELECT SUM(OD.AMOUNT) FROM OMTRANSACTIONDETAIL OD (NOLOCK) WHERE OD.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) AS LOADVALUE,
(SELECT SUM(FRT.AMOUNT) FROM OMFREIGHT FRT (NOLOCK) WHERE FRT.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) AS FREIGHTREVENUE,
(SELECT SUM(FRT.AMOUNT) FROM OMFREIGHT FRT (NOLOCK) WHERE FRT.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) 
	- (SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) WHERE SP.R_SOURCEID = HDR.ROWID)  AS FREIGHTPROFIT,
(SELECT TOP 1 VCONS.CONSIGNEECITY 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE 
	ORDER BY DET.DELSTOPNO DESC) AS LASTDROPCITY,
(SELECT TOP 1 VCONS.CONSIGNEESTATE 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE 
	ORDER BY DET.DELSTOPNO DESC) AS LASTDROPSTATE,
---------------------
--DROP DETAIL LINES--
---------------------
DET.DELSTOPNO,
(SELECT VCONS.ConsigneeName 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS CUSTOMERNAME,
(SELECT VCONS.ConsigneeUserDefinedCode_3 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS CUSTOMERTYPE,
(SELECT VCONS.ConsigneeUserDefinedCode_8 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS NATIONALACCT,
(SELECT IIF(VCONS.ConsigneeUserDefinedCode_8 IS NULL, 'INDEPENDENT', 'MAJOR') 
	FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) 
	WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS NATLACCTTEXT,
(SELECT SUM(OD.AMOUNT) FROM OMTRANSACTIONDETAIL OD (NOLOCK) WHERE OD.R_TRANSACTIONHEADER = OBJ.R_SOURCEID) AS DROPVALUE,
(SELECT SUM(OBJ.CUBESORDERED) 
	FROM FMDISPATCHOBJECT OBJ (NOLOCK) 
	JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID 
	WHERE  DET.R_TRIPHEADER = HDR.ROWID) AS LOADVOLUME,
OBJ.CUBESORDERED AS DROPVOLUME,
OBJ.CUBESORDERED / (SELECT IIF(SUM(OBJ.CUBESORDERED)=0, 1, SUM(OBJ.CUBESORDERED)) 
						FROM FMDISPATCHOBJECT OBJ (NOLOCK) 
						JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID 
						WHERE  DET.R_TRIPHEADER = HDR.ROWID
					) AS DROPVOLUMESHARE,
--DISTRIBUTE FREIGHTEXPENSE BY DROPVOLUMESHARE
(SELECT SUM(AMOUNT) 
	FROM SPOPENITEMS SP (NOLOCK) 
	WHERE SP.R_SOURCEID = HDR.ROWID) 
	* (OBJ.CUBESORDERED / 
		(SELECT IIF(SUM(OBJ.CUBESORDERED)=0, 1, SUM(OBJ.CUBESORDERED)) 
			FROM FMDISPATCHOBJECT OBJ (NOLOCK) 
			JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID 
			WHERE  DET.R_TRIPHEADER = HDR.ROWID
	   )) AS DROPFREIGHTEXPENSE,
(SELECT SUM(FRT.AMOUNT) FROM OMFREIGHT FRT (NOLOCK) WHERE FRT.R_TRANSACTIONHEADER = OBJ.R_SOURCEID) AS DROPFREIGHTREVENUE,
(SELECT SUM(FRT.AMOUNT) 
	FROM OMFREIGHT FRT (NOLOCK) 
	WHERE FRT.R_TRANSACTIONHEADER = OBJ.R_SOURCEID)
	-	(SELECT SUM(AMOUNT) 
			FROM SPOPENITEMS SP (NOLOCK) 
			WHERE SP.R_SOURCEID = HDR.ROWID) 
			* (OBJ.CUBESORDERED / 
				(SELECT IIF(SUM(OBJ.CUBESORDERED)=0, 1, SUM(OBJ.CUBESORDERED)) 
					FROM FMDISPATCHOBJECT OBJ (NOLOCK) 
					JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_FMDISPATCHOBJECT = OBJ.ROWID 
					WHERE  DET.R_TRIPHEADER = HDR.ROWID
			   )) AS DROPFREIGHTPROFIT,
(SELECT VCONS.CONSIGNEECITY FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS DROPCITY,
(SELECT VCONS.CONSIGNEESTATE FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK) WHERE VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE) AS DROPSTATE
FROM FMTRIPHEADER HDR (NOLOCK)
JOIN FMTRIPDETAIL DET (NOLOCK) ON DET.R_TRIPHEADER = HDR.ROWID
JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DET.R_FMDISPATCHOBJECT
LEFT OUTER JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = HDR.R_ORIGIN
LEFT OUTER JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID
WHERE HDR.RECORDTYPE <> 'P'
--ORDER BY PART.IDENTITYID, HDR.TRIPNO, DET.DELSTOPNO
------------------------------------------------------------------------
--ORIGINAL SCRIPT HAS BEEN REPLACED WITH SCRIPT ABOVE
------------------------------------------------------------------------
/*
SELECT
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
PART.IDENTITYID AS WAREHOUSE,
PART.NAME AS WAREHOUSENAME,
HDR.RECORDTYPE,
ISNULL(HDR.ACTUALSTART,HDR.PLANSTART) AS PLANSTART,
IIF	(DBO.FN_SALEYEAR(NULL) > DBO.FN_SALEYEAR(ISNULL(HDR.ACTUALSTART,HDR.PLANSTART)), 
	'PREVIOUS YEAR', 
	IIF	(DBO.FN_SALEYEAR(NULL)>DBO.FN_SALEYEAR(ISNULL(HDR.ACTUALSTART,HDR.PLANSTART)), 
		'THIS YEAR',
		'NEXT YEAR'
	)	) AS YEARTEXT,
HDR.TRIPNO,
(SELECT COUNT(DISTINCT DET.R_DESTINATIONID) 
	FROM FMTRIPDETAIL DET (NOLOCK) 
	WHERE DET.R_TRIPHEADER = HDR.ROWID) AS DROPCOUNT,
ISNULL(CARR.NAME, PART.NAME) AS CARRIERNAME, 
HDR.EQUIPMENT,
ISNULL(HDR.MILESLOADED,0)+ISNULL(HDR.MILESUNLOADED,0) AS MILES,
(SELECT SP.RATE FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'STLO-MILES' 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS RATE,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE = 'DROP-PAY' 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS DROPPAY,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) 
	JOIN IDFREIGHTCHARGES FCH (NOLOCK) ON FCH.ROWID = SP.R_FREIGHTCHARGE AND FCH.CHARGECODE NOT IN ('STLO-MILES', 'DROP-PAY') 
	WHERE SP.R_SOURCEID = HDR.ROWID) AS COSTADJ,
(SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) WHERE SP.R_SOURCEID = HDR.ROWID) AS AMOUNT,
(SELECT TOP 1 SETHDR.CHECKDATE
	FROM SPSETTLEMENTSHEADER SETHDR (NOLOCK) 
	JOIN SPSETTLEMENTSDETAIL SETDET (NOLOCK) ON SETDET.R_SETTLEMENTSHEADER = SETHDR.ROWID
	JOIN SPOPENITEMS OPN (NOLOCK) ON OPN.ROWID = SETDET.R_OPENITEM
	WHERE OPN.R_SOURCEID = HDR.ROWID
	ORDER BY SETHDR.CHECKDATE DESC) AS LASTCHECKDATE,
(SELECT SUM(AMOUNT) 
	FROM SPOPENITEMS OPN (NOLOCK) 
	WHERE OPN.REFERENCE = HDR.TRIPNO 
	AND OPN.RECORDTYPE IN ('U','Z')
	AND OPN.TRANSACTIONTYPE IN ('A','P')) AS ADVANCE,
(SELECT SUM(OD.AMOUNT) FROM OMTRANSACTIONDETAIL OD (NOLOCK) WHERE OD.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) AS LOADVALUE,
(SELECT SUM(FRT.AMOUNT) FROM OMFREIGHT FRT (NOLOCK) WHERE FRT.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) AS FREIGHTVALUE,
(SELECT SUM(FRT.AMOUNT) FROM OMFREIGHT FRT (NOLOCK) WHERE FRT.R_TRANSACTIONHEADER IN 
	(SELECT ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) WHERE OH.ROWID IN 
		(SELECT OBJ.R_SOURCEID FROM FMDISPATCHOBJECT OBJ (NOLOCK) WHERE OBJ.ROWID IN 
			(SELECT R_FMDISPATCHOBJECT FROM FMTRIPDETAIL DET (NOLOCK) WHERE DET.R_TRIPHEADER = HDR.ROWID)))) 
	- (SELECT SUM(AMOUNT) FROM SPOPENITEMS SP (NOLOCK) WHERE SP.R_SOURCEID = HDR.ROWID)  AS REVENUE,
(SELECT TOP 1 VCONS.CONSIGNEECITY 
	FROM FMTRIPDETAIL DET (NOLOCK) 
	LEFT OUTER JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DET.R_FMDISPATCHOBJECT
	LEFT OUTER JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE
	WHERE DET.R_TRIPHEADER = HDR.ROWID
	ORDER BY DET.DELSTOPNO DESC) AS LASTDROPCITY,
(SELECT TOP 1 VCONS.CONSIGNEESTATE 
	FROM FMTRIPDETAIL DET (NOLOCK) 
	LEFT OUTER JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DET.R_FMDISPATCHOBJECT
	LEFT OUTER JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE
	WHERE DET.R_TRIPHEADER = HDR.ROWID
	ORDER BY DET.DELSTOPNO DESC) AS LASTDROPSTATE

FROM FMTRIPHEADER HDR (NOLOCK)
LEFT OUTER JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = HDR.R_ORIGIN
LEFT OUTER JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID
WHERE HDR.RECORDTYPE <> 'P'
*/