/* WOT: 0:32 (72,489 ROWS) 
--SQL_BILLING_REP_TRENDS 
SELECT * 
FROM VW_RPT_SQL_BILLING_REP_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
AND ISCURRYEAR = 'Y' 
AND ISCURRPERIOD = 'Y'	-->RT= 0:33 (3,590 ROWS) 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_BILLING_REP_TRENDS] 
AS 
SELECT 
IIF(X.SALEYEAR = DBO.FN_DATE2YEAR(NULL),'Y', NULL) AS ISCURRYEAR, 
IIF(X.PERIOD = DBO.FN_DATE2PERIOD(NULL),'Y', NULL) AS ISCURRPERIOD, 
'R' AS RECORDTYPE, 
'SB' AS COMPANYID, 
X.SALEYEAR, 
X.PERIOD, 
-------------------------- 
X.TRANSACTIONDATE, 
X.REPORTGROUP, 
X.WAREHOUSEID, 
ISNULL(X.NATIONALACCOUNT, 'N') AS NATIONALACCOUNT, 
X.SALESREPID, 
X.SALESREPNAME, 
X.CURRAMOUNT, 
X.PREVAMOUNT, 
X.GOALAMOUNT 
FROM	( 
		SELECT	DBO.FN_DATE2YEAR(CAST(CURRTRANSDATE AS DATE)) AS SALEYEAR, 
				PERIOD, 
				CAST(CURRTRANSDATE AS DATE) AS TRANSACTIONDATE, 
				REPORTGROUP, 
				WAREHOUSEID, 
				TRIM(SALESREPID) AS SALESREPID, 
				TRIM(SALESREPNAME) AS SALESREPNAME, 
				NATIONALACCOUNT, 
				SUM (CURRAMOUNT) AS CURRAMOUNT, 
				SUM (PREVAMOUNT) AS PREVAMOUNT, 
				SUM (GOALAMOUNT) AS GOALAMOUNT 
        FROM	( 
				--CURRENT YEAR DATA FROM INSIGHT: 
				SELECT	C.*, 
						C.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(C.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS C (NOLOCK) 
				WHERE	C.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		C.REPORTGROUP < 4 
				AND		C.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM INSIGHT: 
				SELECT	L.*, 
						DBO.FN_DATE4NEXTYEAR(L.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(L.AMOUNT,0) AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_ACTUALS L (NOLOCK) 
				WHERE	L.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		L.REPORTGROUP < 4 
				AND		L.AMOUNT <> 0 
				UNION ALL 
				--GOAL DATA FROM INSIGHT: 
				SELECT	G.*, 
						G.TRANSACTIONDATE AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						ISNULL(G.AMOUNT,0) AS GOALAMOUNT 
				FROM	VW_RPT_SQL_GOALS G (NOLOCK) 
				WHERE	G.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		G.REPORTGROUP < 4 
				AND		G.AMOUNT <> 0 
				UNION ALL 
				--CURRENT YEAR DATA FROM ePLANT: 
				SELECT	EC.*, 
						EC.TRANSACTIONDATE AS CURRTRANSDATE, 
						ISNULL(EC.AMOUNT,0) AS CURRAMOUNT, 
						0 AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_1 EC (NOLOCK) 
				WHERE	EC.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-1 
				AND		EC.REPORTGROUP < 4 
				AND		EC.AMOUNT <> 0 
				UNION ALL 
				--LAST YEAR DATA FROM ePLANT: 
				SELECT	EL.*, 
						DBO.FN_DATE4NEXTYEAR(EL.TRANSACTIONDATE) AS CURRTRANSDATE, 
						0 AS CURRAMOUNT, 
						ISNULL(EL.AMOUNT,0) AS PREVAMOUNT, 
						0 AS GOALAMOUNT 
				FROM	VW_RPT_SQL_1 EL (NOLOCK) 
				WHERE	EL.SALEYEAR >= DBO.FN_DATE2YEAR(NULL)-2 
				AND		EL.REPORTGROUP < 4 
				AND		EL.AMOUNT <> 0 
				) U 
		GROUP BY 
				U.SALEYEAR, 
				U.PERIOD, 
				CAST(CURRTRANSDATE AS DATE), 
				U.REPORTGROUP, 
				U.WAREHOUSEID, 
				U.SALESREPID, 
				U.SALESREPNAME, 
				U.NATIONALACCOUNT 
		) X 
