/*
--47 DRIVERS ENVELOPE AND
--48 STOP LABEL
SELECT
*
FROM VW_RPT_DRIVERS_ENVELOPE (NOLOCK)
WHERE VW_RPT_DRIVERS_ENVELOPE.RECORDTYPE <> 'P'
and tripno = 'T14066'--'T02663'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_DRIVERS_ENVELOPE]
AS
SELECT
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
VWH.SHIPPERIDENTITYID AS WAREHOUSEID,
VWH.SHIPPERNAME AS WAREHOUSENAME,
--WAREHOUSEPHONE NEEDS TO BE FORMATTED:
ISNULL(
	NULLIF(LEFT(VWH.SHIPPERTELEPHONE_2,8)+'-'+RIGHT(VWH.SHIPPERTELEPHONE_2,4),'-'),
	LEFT(VWH.SHIPPERTELEPHONE_1,8)+'-'+RIGHT(VWH.SHIPPERTELEPHONE_1,4)
	) AS WAREHOUSEPHONE,
HDR.RECORDTYPE,
ISNULL(HDR.ACTUALSTART,HDR.PLANSTART) AS PLANSTART,
HDR.TRIPNO,
CARR.IDENTITYID AS CARRIERID,
CARR.NAME AS CARRIERNAME,

(SELECT COUNT(DISTINCT TD2.R_DESTINATIONID) 
	FROM FMTRIPDETAIL TD2 (NOLOCK) 
	WHERE TD2.R_TRIPHEADER = HDR.ROWID) AS STOPCOUNT,
DTL.DELSTOPNO AS STOPNO,
TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ) AS ALTSHIPTELEPHONE_1, 
VCONS.CONSIGNEENAME,
VCONS.CONSIGNEEADDRESSMEMO,
ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPCOMMENT READY TO PRINT 
		NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE READY TO PRINT 
	) AS CONSIGNEETELEPHONE_1, --OVERRIDE SHIPTOTELEPHONE WITH ALTSHIPCOMMENT IF IT EXISTS.
--VCONS.CONSIGNEETELEPHONE_1,
--NULLIF USED SO THAT IF PHONE IS MISSING THEN DON'T PRINT THE '-' EITHER:
NULLIF(LEFT(VCONS.CONSIGNEETELEPHONE_1,8)+'-'+RIGHT(VCONS.CONSIGNEETELEPHONE_1,4),'-') AS FORMATTEDCONSIGNEEPHONE,

CCONT.IDENTITYID AS CONTACTID,
CCONT.NAME AS CONTACTNAME,
ICONT.USERDEFINEDCODE_1 AS CONTACTROLE,
NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-') AS CONTACTTELEPHONE_1,

DTL.SCHEDULEDDELARRIVALDT,
DTL.COMMENT,
--STOPNOTES CHANGING FROM DTL.COMMENT TO DTL.UDR4 + UDR5:
--NULLIF(ISNULL(TRIM(REPLACE(SUBSTRING(DTL.COMMENT,1,50),CHAR(13)+CHAR(10),'')),'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,'  ') AS STOPNOTES 
NULLIF(ISNULL(DTL.USERDEFINEDREFERENCE_4,'') + ' ' + ISNULL(DTL.USERDEFINEDREFERENCE_5,'') ,' ') AS STOPNOTES 

FROM FMTRIPHEADER HDR (NOLOCK)
JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT
JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID 
LEFT JOIN IDMASTER CARR (NOLOCK) ON CARR.ROWID = HDR.R_CARRIER
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OBJ.R_CONSIGNEE--DTL.R_DESTINATIONID
LEFT JOIN VW_IDSHIPPERVIEW VWH (NOLOCK) ON VWH.SHIPPERMASTERROWID = HDR.R_ORIGIN
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = HDR.COMPANYID

--CONTACT DATA (usual issue with either too many or not enough records returning when dealing with contacts - switched over to DBO.FN_GETCONTACT below)
--LEFT JOIN IDRELATIONSHIPLINKS LCONT (NOLOCK) ON LCONT.R_IDMASTER = VCONS.CONSIGNEEMASTERROWID AND LCONT.IDMASTERTYPE = '02' AND LCONT.IDMEMBERTYPE = '22' 
--LEFT JOIN IDMASTER CCONT (NOLOCK) ON CCONT.ROWID = LCONT.R_IDMEMBER --AND LEFT(CCONT.IDENTITYID,2)='C5'
--left JOIN IDCONTACTS ICONT (NOLOCK) ON ICONT.R_IDENTITY = CCONT.ROWID AND ICONT.USERDEFINEDCODE_1 LIKE 'SHIPPING%'
--LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = CCONT.ROWID

--CONSIGNEE CONTACTS	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
LEFT JOIN IDMASTER CCONT (NOLOCK) ON CCONT.ROWID = DBO.FN_GETCONTACT(OH.R_SHIPPER,'02','C5')
LEFT JOIN IDCONTACTS ICONT (NOLOCK) ON ICONT.R_IDENTITY = DBO.FN_GETCONTACT(OH.R_SHIPPER,'02','C5')
LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(OH.R_SHIPPER,'02','C5')
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO 

WHERE HDR.RECORDTYPE <> 'P'
--and tripno = 'T02881'
