/* GP_LABORGROUP_PRODUCTION_39PERIOD
--RT:5:15 @ 52,871
--GP LaborGrp Prod39P-Det EXCEL
--GP LaborGrp Prod39P-Sum EXCEL

SELECT 
* 
FROM VW_RPT_GP_LABORGROUP_PRODUCTION_39PERIOD (NOLOCK)
--MACRO-------------
WHERE WAREHOUSEID = '10' 
--AND LABORGROUP = 'Growing'
--AND JOBCODE = '1000' 
ORDER BY COMPANYID, WAREHOUSEID, LABORGROUP, JOBCODE, DEPARTMENT, CHECKDATE--, ISYTD 
*/
--SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS THRUDATE, 		--THIS RETURNS THE MOST RECENT SATURDAY'S DATE. IMPORTANT FOR THIS REPORT!
--GETDATE() + DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())-1) - DBO.FN_YEAR2DATE(DBO.FN_DATE2YEAR(GETDATE())) AS DATE4PRIORYEAR. IMPORTANT CALCULATION FOR THIS REPORT!
--(SELECT BASE.VOLUME FROM IMCONTAINER BASE (NOLOCK) WHERE CONTAINERCODE = '030') IS WHERE I GET THE 615.99 FROM

CREATE OR ALTER VIEW [dbo].[VW_RPT_GP_LABORGROUP_PRODUCTION_39PERIOD] 
AS 
SELECT 
	TRIM(STR(THRUYEAR - ((00+1)/13))) + 'P' + TRIM(STR(IIF(00>=THRUPERIOD,13-ABS(00-THRUPERIOD)%13,THRUPERIOD-00))) AS B00, 
	TRIM(STR(THRUYEAR - ((01+1)/13))) + 'P' + TRIM(STR(IIF(01>=THRUPERIOD,13-ABS(01-THRUPERIOD)%13,THRUPERIOD-01))) AS B01, 
	TRIM(STR(THRUYEAR - ((02+1)/13))) + 'P' + TRIM(STR(IIF(02>=THRUPERIOD,13-ABS(02-THRUPERIOD)%13,THRUPERIOD-02))) AS B02, 
	TRIM(STR(THRUYEAR - ((03+1)/13))) + 'P' + TRIM(STR(IIF(03>=THRUPERIOD,13-ABS(03-THRUPERIOD)%13,THRUPERIOD-03))) AS B03, 
	TRIM(STR(THRUYEAR - ((04+1)/13))) + 'P' + TRIM(STR(IIF(04>=THRUPERIOD,13-ABS(04-THRUPERIOD)%13,THRUPERIOD-04))) AS B04, 
	TRIM(STR(THRUYEAR - ((05+1)/13))) + 'P' + TRIM(STR(IIF(05>=THRUPERIOD,13-ABS(05-THRUPERIOD)%13,THRUPERIOD-05))) AS B05, 
	TRIM(STR(THRUYEAR - ((06+1)/13))) + 'P' + TRIM(STR(IIF(06>=THRUPERIOD,13-ABS(06-THRUPERIOD)%13,THRUPERIOD-06))) AS B06, 
	TRIM(STR(THRUYEAR - ((07+1)/13))) + 'P' + TRIM(STR(IIF(07>=THRUPERIOD,13-ABS(07-THRUPERIOD)%13,THRUPERIOD-07))) AS B07, 
	TRIM(STR(THRUYEAR - ((08+1)/13))) + 'P' + TRIM(STR(IIF(08>=THRUPERIOD,13-ABS(08-THRUPERIOD)%13,THRUPERIOD-08))) AS B08, 
	TRIM(STR(THRUYEAR - ((09+1)/13))) + 'P' + TRIM(STR(IIF(09>=THRUPERIOD,13-ABS(09-THRUPERIOD)%13,THRUPERIOD-09))) AS B09, 
	TRIM(STR(THRUYEAR - ((10+1)/13))) + 'P' + TRIM(STR(IIF(10>=THRUPERIOD,13-ABS(10-THRUPERIOD)%13,THRUPERIOD-10))) AS B10, 
	TRIM(STR(THRUYEAR - ((11+1)/13))) + 'P' + TRIM(STR(IIF(11>=THRUPERIOD,13-ABS(11-THRUPERIOD)%13,THRUPERIOD-11))) AS B11, 
	TRIM(STR(THRUYEAR - ((12+1)/13))) + 'P' + TRIM(STR(IIF(12>=THRUPERIOD,13-ABS(12-THRUPERIOD)%13,THRUPERIOD-12))) AS B12, 
	TRIM(STR(THRUYEAR - ((13+1)/13))) + 'P' + TRIM(STR(IIF(13>=THRUPERIOD,13-ABS(13-THRUPERIOD)%13,THRUPERIOD-13))) AS B13, 
	TRIM(STR(THRUYEAR - ((14+1)/13))) + 'P' + TRIM(STR(IIF(14>=THRUPERIOD,13-ABS(14-THRUPERIOD)%13,THRUPERIOD-14))) AS B14, 
	TRIM(STR(THRUYEAR - ((15+1)/13))) + 'P' + TRIM(STR(IIF(15>=THRUPERIOD,13-ABS(15-THRUPERIOD)%13,THRUPERIOD-15))) AS B15, 
	TRIM(STR(THRUYEAR - ((16+1)/13))) + 'P' + TRIM(STR(IIF(16>=THRUPERIOD,13-ABS(16-THRUPERIOD)%13,THRUPERIOD-16))) AS B16, 
	TRIM(STR(THRUYEAR - ((17+1)/13))) + 'P' + TRIM(STR(IIF(17>=THRUPERIOD,13-ABS(17-THRUPERIOD)%13,THRUPERIOD-17))) AS B17, 
	TRIM(STR(THRUYEAR - ((18+1)/13))) + 'P' + TRIM(STR(IIF(18>=THRUPERIOD,13-ABS(18-THRUPERIOD)%13,THRUPERIOD-18))) AS B18, 
	TRIM(STR(THRUYEAR - ((19+1)/13))) + 'P' + TRIM(STR(IIF(19>=THRUPERIOD,13-ABS(19-THRUPERIOD)%13,THRUPERIOD-19))) AS B19, 
	TRIM(STR(THRUYEAR - ((20+1)/13))) + 'P' + TRIM(STR(IIF(20>=THRUPERIOD,13-ABS(20-THRUPERIOD)%13,THRUPERIOD-20))) AS B20, 
	TRIM(STR(THRUYEAR - ((21+1)/13))) + 'P' + TRIM(STR(IIF(21>=THRUPERIOD,13-ABS(21-THRUPERIOD)%13,THRUPERIOD-21))) AS B21, 
	TRIM(STR(THRUYEAR - ((22+1)/13))) + 'P' + TRIM(STR(IIF(22>=THRUPERIOD,13-ABS(22-THRUPERIOD)%13,THRUPERIOD-22))) AS B22, 
	TRIM(STR(THRUYEAR - ((23+1)/13))) + 'P' + TRIM(STR(IIF(23>=THRUPERIOD,13-ABS(23-THRUPERIOD)%13,THRUPERIOD-23))) AS B23, 
	TRIM(STR(THRUYEAR - ((24+1)/13))) + 'P' + TRIM(STR(IIF(24>=THRUPERIOD,13-ABS(24-THRUPERIOD)%13,THRUPERIOD-24))) AS B24, 
	TRIM(STR(THRUYEAR - ((25+1)/13))) + 'P' + TRIM(STR(IIF(25>=THRUPERIOD,13-ABS(25-THRUPERIOD)%13,THRUPERIOD-25))) AS B25, 
	TRIM(STR(THRUYEAR - ((26+1)/13))) + 'P' + TRIM(STR(IIF(26>=THRUPERIOD,13-ABS(26-THRUPERIOD)%13,THRUPERIOD-26))) AS B26, 
	TRIM(STR(THRUYEAR - ((27+1)/13))) + 'P' + TRIM(STR(IIF(27>=THRUPERIOD,13-ABS(27-THRUPERIOD)%13,THRUPERIOD-27))) AS B27, 
	TRIM(STR(THRUYEAR - ((28+1)/13))) + 'P' + TRIM(STR(IIF(28>=THRUPERIOD,13-ABS(28-THRUPERIOD)%13,THRUPERIOD-28))) AS B28, 
	TRIM(STR(THRUYEAR - ((29+1)/13))) + 'P' + TRIM(STR(IIF(29>=THRUPERIOD,13-ABS(29-THRUPERIOD)%13,THRUPERIOD-29))) AS B29, 
	TRIM(STR(THRUYEAR - ((30+1)/13))) + 'P' + TRIM(STR(IIF(30>=THRUPERIOD,13-ABS(30-THRUPERIOD)%13,THRUPERIOD-30))) AS B30, 
	TRIM(STR(THRUYEAR - ((31+1)/13))) + 'P' + TRIM(STR(IIF(31>=THRUPERIOD,13-ABS(31-THRUPERIOD)%13,THRUPERIOD-31))) AS B31, 
	TRIM(STR(THRUYEAR - ((32+1)/13))) + 'P' + TRIM(STR(IIF(32>=THRUPERIOD,13-ABS(32-THRUPERIOD)%13,THRUPERIOD-32))) AS B32, 
	TRIM(STR(THRUYEAR - ((33+1)/13))) + 'P' + TRIM(STR(IIF(33>=THRUPERIOD,13-ABS(33-THRUPERIOD)%13,THRUPERIOD-33))) AS B33, 
	TRIM(STR(THRUYEAR - ((34+1)/13))) + 'P' + TRIM(STR(IIF(34>=THRUPERIOD,13-ABS(34-THRUPERIOD)%13,THRUPERIOD-34))) AS B34, 
	TRIM(STR(THRUYEAR - ((35+1)/13))) + 'P' + TRIM(STR(IIF(35>=THRUPERIOD,13-ABS(35-THRUPERIOD)%13,THRUPERIOD-35))) AS B35, 
	TRIM(STR(THRUYEAR - ((36+1)/13))) + 'P' + TRIM(STR(IIF(36>=THRUPERIOD,13-ABS(36-THRUPERIOD)%13,THRUPERIOD-36))) AS B36, 
	TRIM(STR(THRUYEAR - ((37+1)/13))) + 'P' + TRIM(STR(IIF(37>=THRUPERIOD,13-ABS(37-THRUPERIOD)%13,THRUPERIOD-37))) AS B37, 
	TRIM(STR(THRUYEAR - ((38+1)/13))) + 'P' + TRIM(STR(IIF(38>=THRUPERIOD,13-ABS(38-THRUPERIOD)%13,THRUPERIOD-38))) AS B38, 
	*
FROM (
	SELECT DBO.FN_DATE2YEAR(THRUDATE) AS THRUYEAR, DBO.FN_DATE2PERIOD(THRUDATE) AS THRUPERIOD, DBO.FN_DATE2WEEK(THRUDATE) AS THRUWEEK, 
		Y.COMPANYID, 
		Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		Y.YEAR, 
		Y.PERIOD, 
		Y.BUCKET, 
		SUM(B00_HOURS)		AS B00_HOURS, 
		MAX(B00_UNITS)		AS B00_UNITS, 
		MAX(B00_EQUIVUNITS) AS B00_EQUIVUNITS, 
		SUM(B01_HOURS)		AS B01_HOURS, 
		MAX(B01_UNITS)		AS B01_UNITS, 
		MAX(B01_EQUIVUNITS) AS B01_EQUIVUNITS, 
		SUM(B02_HOURS)		AS B02_HOURS, 
		MAX(B02_UNITS)		AS B02_UNITS, 
		MAX(B02_EQUIVUNITS) AS B02_EQUIVUNITS, 
		SUM(B03_HOURS)		AS B03_HOURS, 
		MAX(B03_UNITS)		AS B03_UNITS, 
		MAX(B03_EQUIVUNITS) AS B03_EQUIVUNITS, 
		SUM(B04_HOURS)		AS B04_HOURS, 
		MAX(B04_UNITS)		AS B04_UNITS, 
		MAX(B04_EQUIVUNITS) AS B04_EQUIVUNITS, 
		SUM(B05_HOURS)		AS B05_HOURS, 
		MAX(B05_UNITS)		AS B05_UNITS, 
		MAX(B05_EQUIVUNITS) AS B05_EQUIVUNITS, 
		SUM(B06_HOURS)		AS B06_HOURS, 
		MAX(B06_UNITS)		AS B06_UNITS, 
		MAX(B06_EQUIVUNITS) AS B06_EQUIVUNITS, 
		SUM(B07_HOURS)		AS B07_HOURS, 
		MAX(B07_UNITS)		AS B07_UNITS, 
		MAX(B07_EQUIVUNITS) AS B07_EQUIVUNITS, 
		SUM(B08_HOURS)		AS B08_HOURS, 
		MAX(B08_UNITS)		AS B08_UNITS, 
		MAX(B08_EQUIVUNITS) AS B08_EQUIVUNITS, 
		SUM(B09_HOURS)		AS B09_HOURS, 
		MAX(B09_UNITS)		AS B09_UNITS, 
		MAX(B09_EQUIVUNITS) AS B09_EQUIVUNITS, 
		SUM(B10_HOURS)		AS B10_HOURS, 
		MAX(B10_UNITS)		AS B10_UNITS, 
		MAX(B10_EQUIVUNITS) AS B10_EQUIVUNITS, 
		SUM(B11_HOURS)		AS B11_HOURS, 
		MAX(B11_UNITS)		AS B11_UNITS, 
		MAX(B11_EQUIVUNITS) AS B11_EQUIVUNITS, 
		SUM(B12_HOURS)		AS B12_HOURS, 
		MAX(B12_UNITS)		AS B12_UNITS, 
		MAX(B12_EQUIVUNITS) AS B12_EQUIVUNITS, 
		SUM(B13_HOURS)		AS B13_HOURS, 
		MAX(B13_UNITS)		AS B13_UNITS, 
		MAX(B13_EQUIVUNITS) AS B13_EQUIVUNITS, 
		SUM(B14_HOURS)		AS B14_HOURS, 
		MAX(B14_UNITS)		AS B14_UNITS, 
		MAX(B14_EQUIVUNITS) AS B14_EQUIVUNITS, 
		SUM(B15_HOURS)		AS B15_HOURS, 
		MAX(B15_UNITS)		AS B15_UNITS, 
		MAX(B15_EQUIVUNITS) AS B15_EQUIVUNITS, 
		SUM(B16_HOURS)		AS B16_HOURS, 
		MAX(B16_UNITS)		AS B16_UNITS, 
		MAX(B16_EQUIVUNITS) AS B16_EQUIVUNITS, 
		SUM(B17_HOURS)		AS B17_HOURS, 
		MAX(B17_UNITS)		AS B17_UNITS, 
		MAX(B17_EQUIVUNITS) AS B17_EQUIVUNITS, 
		SUM(B18_HOURS)		AS B18_HOURS, 
		MAX(B18_UNITS)		AS B18_UNITS, 
		MAX(B18_EQUIVUNITS) AS B18_EQUIVUNITS, 
		SUM(B19_HOURS)		AS B19_HOURS, 
		MAX(B19_UNITS)		AS B19_UNITS, 
		MAX(B19_EQUIVUNITS) AS B19_EQUIVUNITS, 
		SUM(B20_HOURS)		AS B20_HOURS, 
		MAX(B20_UNITS)		AS B20_UNITS, 
		MAX(B20_EQUIVUNITS) AS B20_EQUIVUNITS, 
		SUM(B21_HOURS)		AS B21_HOURS, 
		MAX(B21_UNITS)		AS B21_UNITS, 
		MAX(B21_EQUIVUNITS) AS B21_EQUIVUNITS, 
		SUM(B22_HOURS)		AS B22_HOURS, 
		MAX(B22_UNITS)		AS B22_UNITS, 
		MAX(B22_EQUIVUNITS) AS B22_EQUIVUNITS, 
		SUM(B23_HOURS)		AS B23_HOURS, 
		MAX(B23_UNITS)		AS B23_UNITS, 
		MAX(B23_EQUIVUNITS) AS B23_EQUIVUNITS, 
		SUM(B24_HOURS)		AS B24_HOURS, 
		MAX(B24_UNITS)		AS B24_UNITS, 
		MAX(B24_EQUIVUNITS) AS B24_EQUIVUNITS, 
		SUM(B25_HOURS)		AS B25_HOURS, 
		MAX(B25_UNITS)		AS B25_UNITS, 
		MAX(B25_EQUIVUNITS) AS B25_EQUIVUNITS, 
		SUM(B26_HOURS)		AS B26_HOURS, 
		MAX(B26_UNITS)		AS B26_UNITS, 
		MAX(B26_EQUIVUNITS) AS B26_EQUIVUNITS, 
		SUM(B27_HOURS)		AS B27_HOURS, 
		MAX(B27_UNITS)		AS B27_UNITS, 
		MAX(B27_EQUIVUNITS) AS B27_EQUIVUNITS, 
		SUM(B28_HOURS)		AS B28_HOURS, 
		MAX(B28_UNITS)		AS B28_UNITS, 
		MAX(B28_EQUIVUNITS) AS B28_EQUIVUNITS, 
		SUM(B29_HOURS)		AS B29_HOURS, 
		MAX(B29_UNITS)		AS B29_UNITS, 
		MAX(B29_EQUIVUNITS) AS B29_EQUIVUNITS, 
		SUM(B30_HOURS)		AS B30_HOURS, 
		MAX(B30_UNITS)		AS B30_UNITS, 
		MAX(B30_EQUIVUNITS) AS B30_EQUIVUNITS, 
		SUM(B31_HOURS)		AS B31_HOURS, 
		MAX(B31_UNITS)		AS B31_UNITS, 
		MAX(B31_EQUIVUNITS) AS B31_EQUIVUNITS, 
		SUM(B32_HOURS)		AS B32_HOURS, 
		MAX(B32_UNITS)		AS B32_UNITS, 
		MAX(B32_EQUIVUNITS) AS B32_EQUIVUNITS, 
		SUM(B33_HOURS)		AS B33_HOURS, 
		MAX(B33_UNITS)		AS B33_UNITS, 
		MAX(B33_EQUIVUNITS) AS B33_EQUIVUNITS, 
		SUM(B34_HOURS)		AS B34_HOURS, 
		MAX(B34_UNITS)		AS B34_UNITS, 
		MAX(B34_EQUIVUNITS) AS B34_EQUIVUNITS, 
		SUM(B35_HOURS)		AS B35_HOURS, 
		MAX(B35_UNITS)		AS B35_UNITS, 
		MAX(B35_EQUIVUNITS) AS B35_EQUIVUNITS, 
		SUM(B36_HOURS)		AS B36_HOURS, 
		MAX(B36_UNITS)		AS B36_UNITS, 
		MAX(B36_EQUIVUNITS) AS B36_EQUIVUNITS, 
		SUM(B37_HOURS)		AS B37_HOURS, 
		MAX(B37_UNITS)		AS B37_UNITS, 
		MAX(B37_EQUIVUNITS) AS B37_EQUIVUNITS, 
		SUM(B38_HOURS)		AS B38_HOURS, 
		MAX(B38_UNITS)		AS B38_UNITS, 
		MAX(B38_EQUIVUNITS) AS B38_EQUIVUNITS, 
		Y.PRTYPE, Y.PRCODE 
	FROM ( 
			SELECT 
				WH.COMPANYID, 
				WH.IDENTITYID AS WAREHOUSEID, 
				WH.NAME AS WAREHOUSENAME, 
				X.DEPRTMNT AS DEPARTMENT, 
				X.DEPTDESC AS DEPARTMENTDESC, 
				--IIF(LEFT(X.JOBDESC, 7) = 'Project', 'Maintenance', LG.LABORGROUP) AS LABORGROUP,	--NOT WANTED IN PRODUCTION VERSION 
				--IIF(LEFT(X.JOBDESC, 7) = 'Project', '57***', X.JOBTITLE) AS JOBCODE,				--NOT WANTED IN PRODUCTION VERSION 
				LG.LABORGROUP, 
				X.JOBTITLE AS JOBCODE, 
				X.JOBDESC AS JOBCODEDESC, 
				X.THRUDATE, 
				--DATEPART(YEAR, DATEADD(MONTH,4,X.CHECKDATE)) AS FISCALYEAR, 
				X.CHECKDATE, 
				X.BUCKET, 
				X.YEAR, 
				X.PERIOD, 
				IIF(X.BUCKET = 00, X.HOURS, 0) AS B00_HOURS, 
				IIF(X.BUCKET = 00, X.UNITS, 0) AS B00_UNITS, 
				IIF(X.BUCKET = 00, X.EQUIVUNITS, 0) AS B00_EQUIVUNITS, 
				IIF(X.BUCKET = 01, X.HOURS, 0) AS B01_HOURS, 
				IIF(X.BUCKET = 01, X.UNITS, 0) AS B01_UNITS, 
				IIF(X.BUCKET = 01, X.EQUIVUNITS, 0) AS B01_EQUIVUNITS, 
				IIF(X.BUCKET = 02, X.HOURS, 0) AS B02_HOURS, 
				IIF(X.BUCKET = 02, X.UNITS, 0) AS B02_UNITS, 
				IIF(X.BUCKET = 02, X.EQUIVUNITS, 0) AS B02_EQUIVUNITS, 
				IIF(X.BUCKET = 03, X.HOURS, 0) AS B03_HOURS, 
				IIF(X.BUCKET = 03, X.UNITS, 0) AS B03_UNITS, 
				IIF(X.BUCKET = 03, X.EQUIVUNITS, 0) AS B03_EQUIVUNITS, 
				IIF(X.BUCKET = 04, X.HOURS, 0) AS B04_HOURS, 
				IIF(X.BUCKET = 04, X.UNITS, 0) AS B04_UNITS, 
				IIF(X.BUCKET = 04, X.EQUIVUNITS, 0) AS B04_EQUIVUNITS, 
				IIF(X.BUCKET = 05, X.HOURS, 0) AS B05_HOURS, 
				IIF(X.BUCKET = 05, X.UNITS, 0) AS B05_UNITS, 
				IIF(X.BUCKET = 05, X.EQUIVUNITS, 0) AS B05_EQUIVUNITS, 
				IIF(X.BUCKET = 06, X.HOURS, 0) AS B06_HOURS, 
				IIF(X.BUCKET = 06, X.UNITS, 0) AS B06_UNITS, 
				IIF(X.BUCKET = 06, X.EQUIVUNITS, 0) AS B06_EQUIVUNITS, 
				IIF(X.BUCKET = 07, X.HOURS, 0) AS B07_HOURS, 
				IIF(X.BUCKET = 07, X.UNITS, 0) AS B07_UNITS, 
				IIF(X.BUCKET = 07, X.EQUIVUNITS, 0) AS B07_EQUIVUNITS, 
				IIF(X.BUCKET = 08, X.HOURS, 0) AS B08_HOURS, 
				IIF(X.BUCKET = 08, X.UNITS, 0) AS B08_UNITS, 
				IIF(X.BUCKET = 08, X.EQUIVUNITS, 0) AS B08_EQUIVUNITS, 
				IIF(X.BUCKET = 09, X.HOURS, 0) AS B09_HOURS, 
				IIF(X.BUCKET = 09, X.UNITS, 0) AS B09_UNITS, 
				IIF(X.BUCKET = 09, X.EQUIVUNITS, 0) AS B09_EQUIVUNITS, 
				IIF(X.BUCKET = 10, X.HOURS, 0) AS B10_HOURS, 
				IIF(X.BUCKET = 10, X.UNITS, 0) AS B10_UNITS, 
				IIF(X.BUCKET = 10, X.EQUIVUNITS, 0) AS B10_EQUIVUNITS, 
				IIF(X.BUCKET = 11, X.HOURS, 0) AS B11_HOURS, 
				IIF(X.BUCKET = 11, X.UNITS, 0) AS B11_UNITS, 
				IIF(X.BUCKET = 11, X.EQUIVUNITS, 0) AS B11_EQUIVUNITS, 
				IIF(X.BUCKET = 12, X.HOURS, 0) AS B12_HOURS, 
				IIF(X.BUCKET = 12, X.UNITS, 0) AS B12_UNITS, 
				IIF(X.BUCKET = 12, X.EQUIVUNITS, 0) AS B12_EQUIVUNITS, 
				IIF(X.BUCKET = 13, X.HOURS, 0) AS B13_HOURS, 
				IIF(X.BUCKET = 13, X.UNITS, 0) AS B13_UNITS, 
				IIF(X.BUCKET = 13, X.EQUIVUNITS, 0) AS B13_EQUIVUNITS, 
				IIF(X.BUCKET = 14, X.HOURS, 0) AS B14_HOURS, 
				IIF(X.BUCKET = 14, X.UNITS, 0) AS B14_UNITS, 
				IIF(X.BUCKET = 14, X.EQUIVUNITS, 0) AS B14_EQUIVUNITS, 
				IIF(X.BUCKET = 15, X.HOURS, 0) AS B15_HOURS, 
				IIF(X.BUCKET = 15, X.UNITS, 0) AS B15_UNITS, 
				IIF(X.BUCKET = 15, X.EQUIVUNITS, 0) AS B15_EQUIVUNITS, 
				IIF(X.BUCKET = 16, X.HOURS, 0) AS B16_HOURS, 
				IIF(X.BUCKET = 16, X.UNITS, 0) AS B16_UNITS, 
				IIF(X.BUCKET = 16, X.EQUIVUNITS, 0) AS B16_EQUIVUNITS, 
				IIF(X.BUCKET = 17, X.HOURS, 0) AS B17_HOURS, 
				IIF(X.BUCKET = 17, X.UNITS, 0) AS B17_UNITS, 
				IIF(X.BUCKET = 17, X.EQUIVUNITS, 0) AS B17_EQUIVUNITS, 
				IIF(X.BUCKET = 18, X.HOURS, 0) AS B18_HOURS, 
				IIF(X.BUCKET = 18, X.UNITS, 0) AS B18_UNITS, 
				IIF(X.BUCKET = 18, X.EQUIVUNITS, 0) AS B18_EQUIVUNITS, 
				IIF(X.BUCKET = 19, X.HOURS, 0) AS B19_HOURS, 
				IIF(X.BUCKET = 19, X.UNITS, 0) AS B19_UNITS, 
				IIF(X.BUCKET = 19, X.EQUIVUNITS, 0) AS B19_EQUIVUNITS, 
				IIF(X.BUCKET = 20, X.HOURS, 0) AS B20_HOURS, 
				IIF(X.BUCKET = 20, X.UNITS, 0) AS B20_UNITS, 
				IIF(X.BUCKET = 20, X.EQUIVUNITS, 0) AS B20_EQUIVUNITS, 
				IIF(X.BUCKET = 21, X.HOURS, 0) AS B21_HOURS, 
				IIF(X.BUCKET = 21, X.UNITS, 0) AS B21_UNITS, 
				IIF(X.BUCKET = 21, X.EQUIVUNITS, 0) AS B21_EQUIVUNITS, 
				IIF(X.BUCKET = 22, X.HOURS, 0) AS B22_HOURS, 
				IIF(X.BUCKET = 22, X.UNITS, 0) AS B22_UNITS, 
				IIF(X.BUCKET = 22, X.EQUIVUNITS, 0) AS B22_EQUIVUNITS, 
				IIF(X.BUCKET = 23, X.HOURS, 0) AS B23_HOURS, 
				IIF(X.BUCKET = 23, X.UNITS, 0) AS B23_UNITS, 
				IIF(X.BUCKET = 23, X.EQUIVUNITS, 0) AS B23_EQUIVUNITS, 
				IIF(X.BUCKET = 24, X.HOURS, 0) AS B24_HOURS, 
				IIF(X.BUCKET = 24, X.UNITS, 0) AS B24_UNITS, 
				IIF(X.BUCKET = 24, X.EQUIVUNITS, 0) AS B24_EQUIVUNITS, 
				IIF(X.BUCKET = 25, X.HOURS, 0) AS B25_HOURS, 
				IIF(X.BUCKET = 25, X.UNITS, 0) AS B25_UNITS, 
				IIF(X.BUCKET = 25, X.EQUIVUNITS, 0) AS B25_EQUIVUNITS, 
				IIF(X.BUCKET = 26, X.HOURS, 0) AS B26_HOURS, 
				IIF(X.BUCKET = 26, X.UNITS, 0) AS B26_UNITS, 
				IIF(X.BUCKET = 26, X.EQUIVUNITS, 0) AS B26_EQUIVUNITS, 
				IIF(X.BUCKET = 27, X.HOURS, 0) AS B27_HOURS, 
				IIF(X.BUCKET = 27, X.UNITS, 0) AS B27_UNITS, 
				IIF(X.BUCKET = 27, X.EQUIVUNITS, 0) AS B27_EQUIVUNITS, 
				IIF(X.BUCKET = 28, X.HOURS, 0) AS B28_HOURS, 
				IIF(X.BUCKET = 28, X.UNITS, 0) AS B28_UNITS, 
				IIF(X.BUCKET = 28, X.EQUIVUNITS, 0) AS B28_EQUIVUNITS, 
				IIF(X.BUCKET = 29, X.HOURS, 0) AS B29_HOURS, 
				IIF(X.BUCKET = 29, X.UNITS, 0) AS B29_UNITS, 
				IIF(X.BUCKET = 29, X.EQUIVUNITS, 0) AS B29_EQUIVUNITS, 
				IIF(X.BUCKET = 30, X.HOURS, 0) AS B30_HOURS, 
				IIF(X.BUCKET = 30, X.UNITS, 0) AS B30_UNITS, 
				IIF(X.BUCKET = 30, X.EQUIVUNITS, 0) AS B30_EQUIVUNITS, 
				IIF(X.BUCKET = 31, X.HOURS, 0) AS B31_HOURS, 
				IIF(X.BUCKET = 31, X.UNITS, 0) AS B31_UNITS, 
				IIF(X.BUCKET = 31, X.EQUIVUNITS, 0) AS B31_EQUIVUNITS, 
				IIF(X.BUCKET = 32, X.HOURS, 0) AS B32_HOURS, 
				IIF(X.BUCKET = 32, X.UNITS, 0) AS B32_UNITS, 
				IIF(X.BUCKET = 32, X.EQUIVUNITS, 0) AS B32_EQUIVUNITS, 
				IIF(X.BUCKET = 33, X.HOURS, 0) AS B33_HOURS, 
				IIF(X.BUCKET = 33, X.UNITS, 0) AS B33_UNITS, 
				IIF(X.BUCKET = 33, X.EQUIVUNITS, 0) AS B33_EQUIVUNITS, 
				IIF(X.BUCKET = 34, X.HOURS, 0) AS B34_HOURS, 
				IIF(X.BUCKET = 34, X.UNITS, 0) AS B34_UNITS, 
				IIF(X.BUCKET = 34, X.EQUIVUNITS, 0) AS B34_EQUIVUNITS, 
				IIF(X.BUCKET = 35, X.HOURS, 0) AS B35_HOURS, 
				IIF(X.BUCKET = 35, X.UNITS, 0) AS B35_UNITS, 
				IIF(X.BUCKET = 35, X.EQUIVUNITS, 0) AS B35_EQUIVUNITS, 
				IIF(X.BUCKET = 36, X.HOURS, 0) AS B36_HOURS, 
				IIF(X.BUCKET = 36, X.UNITS, 0) AS B36_UNITS, 
				IIF(X.BUCKET = 36, X.EQUIVUNITS, 0) AS B36_EQUIVUNITS, 
				IIF(X.BUCKET = 37, X.HOURS, 0) AS B37_HOURS, 
				IIF(X.BUCKET = 37, X.UNITS, 0) AS B37_UNITS, 
				IIF(X.BUCKET = 37, X.EQUIVUNITS, 0) AS B37_EQUIVUNITS, 
				IIF(X.BUCKET = 38, X.HOURS, 0) AS B38_HOURS, 
				IIF(X.BUCKET = 38, X.UNITS, 0) AS B38_UNITS, 
				IIF(X.BUCKET = 38, X.EQUIVUNITS, 0) AS B38_EQUIVUNITS, 
				X.PYRLRTYP AS PRTYPE, 
				X.PAYROLCD AS PRCODE 
			FROM ( 
----------------------------------------
					SELECT 
						CHEKDATE AS CHECKDATE, 
						THRUDATE, YEAR, PERIOD, 
						UNITS, EQUIVUNITS, 
						(DBO.FN_DATE2YEAR(THRUDATE)-ISNULL(T.YEAR,DBO.FN_DATE2YEAR(CHEKDATE)))*13 + (DBO.FN_DATE2PERIOD(THRUDATE)-ISNULL(T.PERIOD,DBO.FN_DATE2PERIOD(CHEKDATE))) AS BUCKET, 
						UNTSTOPY AS HOURS, 
						GP.*
					FROM [GNCGPDB\GP2018].[PROD].[DBO].[V_GNC_PROJECTREPORTBYDEPTWITHCONTRACTLABOR] GP (NOLOCK)
					LEFT JOIN (	
								SELECT 
									WAREHOUSEID, YEAR, PERIOD, THRUDATE, --GETDATE() - (DATEPART(DW,GETDATE())%7) AS THRUDATE, 
									SUM(UNITS) AS UNITS, SUM(EQUIVUNITS) AS EQUIVUNITS
								FROM (
										SELECT 
											WH.IDENTITYID AS WAREHOUSEID, 	
											DBO.FN_DATE2YEAR(TH.COMMITDATE) AS YEAR, 
											DBO.FN_DATE2PERIOD(TH.COMMITDATE) AS PERIOD, 
											THRU.DATE AS THRUDATE, 
											SUM(ISNULL(TD.QUANTITY,0)) AS UNITS, 
											SUM(ISNULL(TD.QUANTITY,0)*(ISNULL(CNT.VOLUME,.01)/615.99)) AS EQUIVUNITS
										FROM IMTRANSACTIONHEADER TH (NOLOCK) 
										JOIN IMTRANSACTIONDETAIL TD (NOLOCK) ON TD.R_TRANSACTIONHEADER = TH.ROWID 
										JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = TD.R_WAREHOUSE 
										JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = TD.R_ITEM 
										JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
										JOIN (SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS DATE) THRU ON 1=1	--PREV SATURDAY
										WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
										AND (	TD.USERDEFINEDCODE_1 IN ('Plant','R&DforSale','Re-plant','Receipt-IM','Recount','Shift.IN')	--CODES TO FILTER PER DJ 10/20/23
												OR (TD.USERDEFINEDCODE_1 = 'Move' AND TD.QUANTITY > 0)	--ADDITIONAL CODE WHEN 'MOVE' IS POSITIVE PER DR 01/12/24
											)
										AND TH.COMMITDATE <= THRU.DATE
										GROUP BY WH.IDENTITYID, DBO.FN_DATE2YEAR(TH.COMMITDATE), DBO.FN_DATE2PERIOD(TH.COMMITDATE), THRU.DATE

										UNION ALL

										SELECT 
											WH.IDENTITYID AS WAREHOUSEID, 	
											DBO.FN_DATE2YEAR(PRH.COMMITDATE) AS YEAR, 
											DBO.FN_DATE2PERIOD(PRH.COMMITDATE) AS PERIOD, 
											THRU.DATE AS THRUDATE, 
											SUM(PRD.RECEIVEDQUANTITY) AS UNITS, 
											SUM(PRD.RECEIVEDQUANTITY*(ISNULL(CNT.VOLUME,.01)/615.99)) AS EQUIVUNITS
										FROM PORECEIPTSHEADER PRH (NOLOCK)
										JOIN PORECEIPTSDETAIL PRD (NOLOCK) ON PRD.R_RECEIPTSHEADER = PRH.ROWID
										JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = PRD.R_WAREHOUSE
										JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = PRD.R_ITEM
										JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
										JOIN (SELECT GETDATE() - (DATEPART(DW,GETDATE())%7) AS DATE) THRU ON 1=1	--PREV SATURDAY
										WHERE SHIPPINGCLASSIFICATIONCODE IN ('CONTAINER','QUART')
										AND PRH.RECEIPTTYPE = 'P'	--PO RECEIPT
										AND PRH.COMMITDATE <= THRU.DATE
										GROUP BY WH.IDENTITYID, DBO.FN_DATE2YEAR(PRH.COMMITDATE), DBO.FN_DATE2PERIOD(PRH.COMMITDATE), THRU.DATE
								) U 
								GROUP BY U.WAREHOUSEID, U.YEAR, U.PERIOD, U.THRUDATE  
					)T ON T.WAREHOUSEID = WAREHOUSE AND T.YEAR = DBO.FN_DATE2YEAR(CHEKDATE) AND T.PERIOD = DBO.FN_DATE2PERIOD(CHEKDATE) 
					WHERE UNTSTOPY > 0 
					AND CHEKDATE BETWEEN '06/25/2021' AND THRUDATE 
					--AND CHEKDATE <= GETDATE() - (DATEPART(DW,GETDATE())%7)	--PREV SATURDAY --THRUDATE
					--AND CHEKDATE > '06/25/2021'--'06/17/2021'
----------------------------------------
			) X 
			JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = WAREHOUSE 
			--LEFT 	--UNCOMMENT THIS LINE TO INCLUDE 'Projects' LABORGRP IN THE REPORT.	--NOT WANTED IN PRODUCTION VERSION 
			JOIN GNC_LABORGROUPSBYGP_JOBCODE LG (NOLOCK) ON LG.JOBCODE = X.JOBTITLE
			WHERE ISNULL(LG.BENCHMARK,'PRODUCTION') = 'PRODUCTION'
	) Y
	WHERE Y.LABORGROUP IS NOT NULL
	GROUP BY 
		Y.COMPANYID, Y.WAREHOUSEID, Y.WAREHOUSENAME, 
		Y.DEPARTMENT, Y.DEPARTMENTDESC, 
		Y.LABORGROUP, 
		Y.JOBCODE, Y.JOBCODEDESC, 
		Y.THRUDATE, 
		Y.CHECKDATE, 
		Y.YEAR, 
		Y.PERIOD, 
		Y.BUCKET, 
		Y.PRTYPE, Y.PRCODE 
) Z
