/* 
--QUANTITY SHIPPED 3 YEAR 
SELECT * 
FROM VW_RPT_QTY_SHIPPED_3YR (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_QTY_SHIPPED_3YR] 
AS 
SELECT 
	COMPANYID, 
	COMPANYNAME, 
	RECORDTYPE, 
	WAREHOUSEID, 
	SALESREPID, 
	--REVERSE LOOKUP CUSTOMERID FROM CONSIGNEEID RESULT: (RETURN CONSIGNEEID IF NO RELATIONSHIP FOUND)
	ISNULL(	(	SELECT	CUST.IDENTITYID 
				FROM IDMASTER CUST (NOLOCK) 
				JOIN IDRELATIONSHIPLINKS LINK (NOLOCK) 
					ON LINK.IDMASTERTYPE = '01' 
					AND LINK.IDMEMBERTYPE = '02' 
					AND LINK.R_IDMASTER = CUST.ROWID 
					AND LINK.R_IDMEMBER = (	SELECT CONS.ROWID 
											FROM IDMASTER CONS (NOLOCK) 
											JOIN IDTYPESLINKS LTYPE (NOLOCK) 
												ON LTYPE.R_IDENTITY = CONS.ROWID 
												AND LTYPE.IDTYPE = '02'
											WHERE CONS.IDENTITYID = X.CONSIGNEEID) 
			), X.CONSIGNEEID) AS CUSTOMERID, 
	CONSIGNEEID,
	REPORTYEAR, 
	REPORTPERIOD, 
	REPORTWEEK, 
	CAST(TRANSACTIONDATE AS DATE) AS TRANSACTIONDATE, 
	TRIM(ITEMCODE) AS ITEMCODE, 
	COMMONNAME, 
	SIZE, 
	SORTNAME, 
	GNC_ITEMSORT, 
	SUM(CURRSHIPPEDQTY) AS CURRSHIPPEDQTY, 
	SUM(CURREXTMERCH) AS CURREXTMERCH, 
	SUM(HIST1SHIPPEDQTY) AS HIST1SHIPPEDQTY, 
	SUM(HIST1EXTMERCH) AS HIST1EXTMERCH, 
	SUM(HIST2SHIPPEDQTY) AS HIST2SHIPPEDQTY, 
	SUM(HIST2EXTMERCH) AS HIST2EXTMERCH 
FROM ( 
		--INSIGHT DATASET: CURRENT 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			OH.RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			PART.IDENTITYID AS SALESREPID, 
			CONS.IDENTITYID AS CONSIGNEEID, 
			DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS REPORTYEAR, 
			DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS REPORTPERIOD, 
			DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS REPORTWEEK, 
			OH.INVOICEDATE AS TRANSACTIONDATE, 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.CLASSCODE AS SIZE, 
			ITM.REFERENCE_5 AS SORTNAME, 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
			OD.QUANTITYSHIPPED AS CURRSHIPPEDQTY, 
			ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0)) AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH, 
			0 AS HIST2SHIPPEDQTY, 
			0 AS HIST2EXTMERCH 
		FROM IMITEM ITM (NOLOCK) 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = ITM.ROWID 
			LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
			LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		WHERE OH.RECORDTYPE = 'Z' --COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 

		UNION ALL 

		--INSIGHT DATASET: HIST1 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			OH.RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			PART.IDENTITYID AS SALESREPID, 
			CONS.IDENTITYID AS CONSIGNEEID, 
			DBO.FN_DATE2YEAR(OH.INVOICEDATE) + 1 AS REPORTYEAR, 		--ADD ONE EQUIVALENT YEAR 
			DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS REPORTPERIOD,			--SHOULD BE THE EQUIVALENT PERIOD 
			DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS REPORTWEEK,				--SHOULD BE THE EQUIVALENT WEEK 
			DBO.FN_DATE4NEXTYEAR(OH.INVOICEDATE) AS TRANSACTIONDATE,	--ADD ONE EQUIVALENT YEAR 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.CLASSCODE AS SIZE, 
			ITM.REFERENCE_5 AS SORTNAME, 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			OD.QUANTITYSHIPPED AS HIST1SHIPPEDQTY, 
			ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0)) AS HIST1EXTMERCH, 
			0 AS HIST2SHIPPEDQTY, 
			0 AS HIST2EXTMERCH 
		FROM IMITEM ITM (NOLOCK) 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = ITM.ROWID 
			LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
			LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		WHERE OH.RECORDTYPE = 'Z' --COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 

		UNION ALL 

		--INSIGHT DATASET: HIST2 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			OH.RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			PART.IDENTITYID AS SALESREPID, 
			CONS.IDENTITYID AS CONSIGNEEID, 
			DBO.FN_DATE2YEAR(OH.INVOICEDATE) + 2 AS REPORTYEAR, 		--ADD TWO EQUIVALENT YEARS 
			DBO.FN_DATE2PERIOD(OH.INVOICEDATE) AS REPORTPERIOD,			--SHOULD BE THE EQUIVALENT PERIOD 
			DBO.FN_DATE2WEEK(OH.INVOICEDATE) AS REPORTWEEK,				--SHOULD BE THE EQUIVALENT WEEK 
			DBO.FN_DATE4NEXT2YEARS(OH.INVOICEDATE) AS TRANSACTIONDATE,	--ADD TWO EQUIVALENT YEARS 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.CLASSCODE AS SIZE, 
			ITM.REFERENCE_5 AS SORTNAME, 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH, 
			OD.QUANTITYSHIPPED AS HIST2SHIPPEDQTY, 
			ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0)) AS HIST2EXTMERCH 
		FROM IMITEM ITM (NOLOCK) 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = ITM.ROWID 
			LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
			LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		WHERE OH.RECORDTYPE = 'Z' --COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 

		UNION ALL 

		--ePLANT DATASET: CURRENT 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			'Z' AS RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ePLANT.SALESREPID, 
			ePLANT.CUSTOMERNUMBER AS CONSIGNEEID, 
			ePLANT.REPORTYEAR, 
			ePLANT.REPORTPERIOD, 
			ePLANT.REPORTWEEK, 
			ePLANT.TRANSACTIONDATE, 
			ISNULL(ITM.ITEMCODE, ePLANT.ITEMCODE) AS ITEMCODE, 
			ISNULL(ITM.REFERENCE_1, 'NOT FOUND IN INSIGHT') AS COMMONNAME, 
			ISNULL(ITM.CLASSCODE, 'NOT FOUND') AS SIZE, 
			ISNULL(ITM.REFERENCE_5, 'NOT FOUND IN INSIGHT') AS SORTNAME, 
			ISNULL(PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE, ePLANT.PLANTGROUPCODE+ePLANT.ITEMCODE+' NOT IN INSIGHT') AS GNC_ITEMSORT,
			ePLANT.SHIPPEDQTY AS CURRSHIPPEDQTY, 
			ePLANT.EXTMERCH AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH, 
			0 AS HIST2SHIPPEDQTY, 
			0 AS HIST2EXTMERCH 
		FROM GNC_SHIPPED_HISTORY ePLANT (NOLOCK)	--ePLANT HISTORY GOES BACK TO THE BEGINNING OF REPORTYEAR 2020 (07/28/2019) 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = ePLANT.WAREHOUSEID 
			LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID AND ITM.ITEMCODE = ePLANT.ITEMCODE 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 

		UNION ALL 

		--ePLANT DATASET: HIST1 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			'Z' AS RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ePLANT.SALESREPID, 
			ePLANT.CUSTOMERNUMBER AS CONSIGNEEID, 
			ePLANT.REPORTYEAR + 1 AS REPORTYEAR,								--ADD ONE EQUIVALENT YEAR 
			ePLANT.REPORTPERIOD,												--SHOULD BE THE EQUIVALENT PERIOD 
			ePLANT.REPORTWEEK,													--SHOULD BE THE EQUIVALENT WEEK 
			DBO.FN_DATE4NEXTYEAR(ePLANT.TRANSACTIONDATE) AS TRANSACTIONDATE,	--ADD ONE EQUIVALENT YEAR 
			ISNULL(ITM.ITEMCODE, ePLANT.ITEMCODE) AS ITEMCODE, 
			ISNULL(ITM.REFERENCE_1, 'NOT FOUND IN INSIGHT') AS COMMONNAME, 
			ISNULL(ITM.CLASSCODE, 'NOT FOUND') AS SIZE, 
			ISNULL(ITM.REFERENCE_5, 'NOT FOUND IN INSIGHT') AS SORTNAME, 
			ISNULL(PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE, ePLANT.PLANTGROUPCODE+ePLANT.ITEMCODE+' NOT IN INSIGHT') AS GNC_ITEMSORT,
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			ePLANT.SHIPPEDQTY AS HIST1SHIPPEDQTY, 
			ePLANT.EXTMERCH AS HIST1EXTMERCH, 
			0 AS HIST2SHIPPEDQTY, 
			0 AS HIST2EXTMERCH 
		FROM GNC_SHIPPED_HISTORY ePLANT (NOLOCK)	--ePLANT HISTORY GOES BACK TO THE BEGINNING OF REPORTYEAR 2020 (07/28/2019) 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = ePLANT.WAREHOUSEID 
			LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID AND ITM.ITEMCODE = ePLANT.ITEMCODE 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 

		UNION ALL 

		--ePLANT DATASET: HIST2 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			'Z' AS RECORDTYPE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ePLANT.SALESREPID, 
			ePLANT.CUSTOMERNUMBER AS CONSIGNEEID, 
			ePLANT.REPORTYEAR + 2 AS REPORTYEAR,								--ADD TWO EQUIVALENT YEARS 
			ePLANT.REPORTPERIOD,												--SHOULD BE THE EQUIVALENT PERIOD 
			ePLANT.REPORTWEEK,													--SHOULD BE THE EQUIVALENT WEEK 
			DBO.FN_DATE4NEXT2YEARS(ePLANT.TRANSACTIONDATE) AS TRANSACTIONDATE,	--ADD TWO EQUIVALENT YEARS 
			ISNULL(ITM.ITEMCODE, ePLANT.ITEMCODE) AS ITEMCODE, 
			ISNULL(ITM.REFERENCE_1, 'NOT FOUND IN INSIGHT') AS COMMONNAME, 
			ISNULL(ITM.CLASSCODE, 'NOT FOUND') AS SIZE, 
			ISNULL(ITM.REFERENCE_5, 'NOT FOUND IN INSIGHT') AS SORTNAME, 
			ISNULL(PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE, ePLANT.PLANTGROUPCODE+ePLANT.ITEMCODE+' NOT IN INSIGHT') AS GNC_ITEMSORT,
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH, 
			ePLANT.SHIPPEDQTY AS HIST2SHIPPEDQTY, 
			ePLANT.EXTMERCH AS HIST2EXTMERCH 
		FROM GNC_SHIPPED_HISTORY ePLANT (NOLOCK)	--ePLANT HISTORY GOES BACK TO THE BEGINNING OF REPORTYEAR 2020 (07/28/2019) 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = ePLANT.WAREHOUSEID 
			LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID AND ITM.ITEMCODE = ePLANT.ITEMCODE 
			LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
			LEFT JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
) X 
WHERE TRANSACTIONDATE <= GETDATE() 
GROUP BY 
	COMPANYID, 
	COMPANYNAME, 
	RECORDTYPE, 
	WAREHOUSEID, 
	SALESREPID, 
	CONSIGNEEID, 
	REPORTYEAR, 
	REPORTPERIOD, 
	REPORTWEEK, 
	CAST(TRANSACTIONDATE AS DATE), 
	ITEMCODE, 
	COMMONNAME, 
	SIZE, 
	SORTNAME, 
	GNC_ITEMSORT
