CREATE OR ALTER VIEW [DBO].[VW_RPT_SQL_STRUCTURE]
AS
SELECT
1 AS REPORTNET,
1 AS REPORTGROSS,
1 AS REPORTGROUP,
1 AS REPORTLINE,
'NET TOTALS' AS REPORTNETDESC,
NULL AS REPORTGROSSDESC,
'Gross Totals' AS REPORTGROUPDESC,
'Shipments' AS REPORTLINEDESC

UNION

SELECT
1 AS REPORTNET,
1 AS REPORTGROSS,
1 AS REPORTGROUP,
2 AS REPORTLINE,
'NET TOTALS' AS REPORTNETDESC,
NULL AS REPORTGROSSDESC,
'Gross Totals' AS REPORTGROUPDESC,
'Drive-Ins' AS REPORTLINEDESC

UNION

SELECT
1 AS REPORTNET,
2 AS REPORTGROSS,
2 AS REPORTGROUP,
3 AS REPORTLINE,
'NET TOTALS' AS REPORTNETDESC,
'Total Reduction' AS REPORTGROSSDESC,
'Total Credit/Debits' AS REPORTGROUPDESC,
'Credit & Debit Memos' AS REPORTLINEDESC

UNION

SELECT
1 AS REPORTNET,
2 AS REPORTGROSS,
2 AS REPORTGROUP,
4 AS REPORTLINE,
'NET TOTALS' AS REPORTNETDESC,
'Total Reduction' AS REPORTGROSSDESC,
'Total Credit/Debits' AS REPORTGROUPDESC,
'VIP Credit Memo' AS REPORTLINEDESC

UNION

SELECT	--ADDED TO INCLUDE '% DISCOUNT' AMOUNTS FROM ePLANT:
1 AS REPORTNET,							--
2 AS REPORTGROSS,						--
3 AS REPORTGROUP,						--
5 AS REPORTLINE,						--ePLANT: % DISCOUNTS
'NET TOTALS' AS REPORTNETDESC,			--
'Total Reduction' AS REPORTGROSSDESC,	--
NULL AS REPORTGROUPDESC,				--
'% Discounts' AS REPORTLINEDESC			--

UNION

SELECT	--THIS IS THE INSIGHT LANDING SPOT FOR ALL DISCOUNTS
1 AS REPORTNET,							--
2 AS REPORTGROSS,						--
3 AS REPORTGROUP,						--
6 AS REPORTLINE,						--ePLANT: CONTRACT PRICING
'NET TOTALS' AS REPORTNETDESC,			--
'Total Reduction' AS REPORTGROSSDESC,	--
NULL AS REPORTGROUPDESC,				--
'Discounts' AS REPORTLINEDESC			--

UNION

SELECT	--ADDED TO INCLUDE 'SPECIAL QUOTES' AMOUNTS FROM ePLANT:
1 AS REPORTNET,							--
2 AS REPORTGROSS,						--
3 AS REPORTGROUP,						--
9 AS REPORTLINE,						--ePLANT: SPECIAL QUOTES
'NET TOTALS' AS REPORTNETDESC,			--
'Total Reduction' AS REPORTGROSSDESC,	--
NULL AS REPORTGROUPDESC,				--
'Special Quotes' AS REPORTLINEDESC		--

UNION

SELECT
2 AS REPORTNET,
3 AS REPORTGROSS,
4 AS REPORTGROUP,
10 AS REPORTLINE,
NULL AS REPORTNETDESC,
'Total Freight' AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Freight' AS REPORTLINEDESC

UNION

SELECT
2 AS REPORTNET,
3 AS REPORTGROSS,
4 AS REPORTGROUP,
11 AS REPORTLINE,
NULL AS REPORTNETDESC,
'Total Freight' AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Handling' AS REPORTLINEDESC

UNION

SELECT
2 AS REPORTNET,
3 AS REPORTGROSS,
4 AS REPORTGROUP,
12 AS REPORTLINE,
NULL AS REPORTNETDESC,
'Total Freight' AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Service Chg' AS REPORTLINEDESC

UNION

SELECT	--ADDED TO INCLUDE 'MISCELLANEOUS' AMOUNTS FROM ePLANT:
2 AS REPORTNET,
3 AS REPORTGROSS,
4 AS REPORTGROUP,
13 AS REPORTLINE,					--ePLANT: MISCELLANEOUS (Freight)
NULL AS REPORTNETDESC,
'Total Freight' AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Miscellaneous' AS REPORTLINEDESC

UNION

SELECT
2 AS REPORTNET,
4 AS REPORTGROSS,
5 AS REPORTGROUP,
14 AS REPORTLINE,
NULL AS REPORTNETDESC,
NULL AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Inter-Company Gross' AS REPORTLINEDESC

UNION

SELECT
2 AS REPORTNET,
4 AS REPORTGROSS,
5 AS REPORTGROUP,
15 AS REPORTLINE,
NULL AS REPORTNETDESC,
NULL AS REPORTGROSSDESC,
NULL AS REPORTGROUPDESC,
'Inter-Company Net' AS REPORTLINEDESC
