/*
--139 TAKINGS (140,141)
--Takings by Customer
--Takings by Consignee
--Takings by Group
SELECT
VW_RPT_TAKINGS.*
FROM VW_RPT_TAKINGS (NOLOCK)
WHERE VW_RPT_TAKINGS.QUANTITYSHIPPED <> 0

--Takings by Price Schedule
SELECT
VW_RPT_TAKINGS.*
FROM VW_RPT_TAKINGS (NOLOCK)
WHERE VW_RPT_TAKINGS.QUANTITYSHIPPED <> 0
AND VW_RPT_TAKINGS.PRICESCHEDULECODE IS NOT NULL
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_TAKINGS]
AS
SELECT
CO.COMPANYID,
WH.IDENTITYID AS WAREHOUSEID,
WH.NAME AS WAREHOUSENAME,
PART.IDENTITYID AS SALESREPID,
PART.NAME AS SALESREPNAME,
VCUST.CUSTOMERIDGROUP,
(SELECT DESCRIPTION_1 FROM IDCODES (NOLOCK) WHERE CODETYPE = 'Z7' AND CODE = VCUST.CUSTOMERIDGROUP) AS CUSTOMERGROUPNAME,
VCUST.CUSTOMERIDENTITYID,
VCUST.CUSTOMERNAME,
VCUST.CUSTOMERADDRESSMEMO,
VCUST.CUSTOMERADDRESS_1,
VCUST.CUSTOMERCITY,
VCUST.CUSTOMERSTATE,
VCUST.CUSTOMERZIP,
VCUST.CUSTOMERTELEPHONE_1,
--TEDIOUS CODE TO BRING IN THE C1 CONTACTS TELEPHONE NUMBER OF THE CUSTOMER
(SELECT REPLACE(LEFT(VCONT.CONTACTSTELEPHONE_1,8)+'-'+RIGHT(VCONT.CONTACTSTELEPHONE_1,4),')',') ') FROM IDRELATIONSHIPLINKS LINK (NOLOCK)
	JOIN VW_IDCONTACTSVIEW VCONT (NOLOCK)
		ON	VCONT.CONTACTSMASTERROWID = LINK.R_IDMEMBER
		AND VCONT.CONTACTSUSERDEFINEDCODE_1 = 'Sales 1'
	WHERE LINK.R_IDMASTER = VCUST.CUSTOMERMASTERROWID
	AND LINK.IDMASTERTYPE='01'
	AND LINK.IDMEMBERTYPE = '22') AS SALESCONTACTPHONE,
VCONS.CONSIGNEEIDENTITYID,
VCONS.CONSIGNEENAME,
VCONS.CONSIGNEEADDRESSMEMO,
VCONS.CONSIGNEEADDRESS_1,
VCONS.CONSIGNEECITY,
VCONS.CONSIGNEESTATE,
VCONS.CONSIGNEEZIP,
VCONS.CONSIGNEETELEPHONE_1,
--TEDIOUS CODE TO BRING IN THE C5 CONTACTS TELEPHONE NUMBER OF THE CONSIGNEE
(SELECT REPLACE(LEFT(VCONT.CONTACTSTELEPHONE_1,8)+'-'+RIGHT(VCONT.CONTACTSTELEPHONE_1,4),')',') ') FROM IDRELATIONSHIPLINKS LINK (NOLOCK)
	JOIN VW_IDCONTACTSVIEW VCONT (NOLOCK)
		ON	VCONT.CONTACTSMASTERROWID = LINK.R_IDMEMBER
		AND VCONT.CONTACTSUSERDEFINEDCODE_1 = 'Shipping 1'
	WHERE LINK.R_IDMASTER = VCUST.CUSTOMERMASTERROWID
	AND LINK.IDMASTERTYPE='02'
	AND LINK.IDMEMBERTYPE = '22') AS SHIPPINGCONTACTPHONE,
PSH.PRICESCHEDULECODE, 
PSH.DESCRIPTION AS PRICESCHEDULEDESCRIPTION,
OH.RECORDTYPE,
OH.TRANSACTIONDATE,
OH.INVOICEDATE,
OH.SHIPPINGDATE,
PGC.PRODUCTCATEGORYCODE AS PLANTGROUPCODE,
ITM.REFERENCE_5 AS SORTNAMEVARIETY,
CNT.CONTAINERSORT,
PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT,
ITM.ITEMCODE, 
CNT.PRINTEDCONTAINERCODE,
ITM.DESCRIPTION_1,
ITM.SUBCLASSCODE AS QUALITY,
OD.QUANTITYSHIPPED, 
DBO.FN_FORMATUPC(PSH.ROWID, WH.ROWID, ITM.ROWID) AS FORMATTEDUPC 

FROM OMTRANSACTIONHEADER OH (NOLOCK)
LEFT OUTER JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
LEFT OUTER JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
LEFT OUTER JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
LEFT OUTER JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
LEFT OUTER JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
LEFT OUTER JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER
LEFT OUTER JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER
LEFT OUTER JOIN IDCONSIGNEESHIPPERZONE ICONSHIP (NOLOCK) ON ICONSHIP.R_CONSIGNEE = OH.R_SHIPPER AND ICONSHIP.R_SHIPPER = OH.R_FMSHIPPER
LEFT OUTER JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
--TEMPORARY JOINS
LEFT OUTER JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
LEFT OUTER JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(ICONSHIP.R_PRICESCHEDULE,ICONS.R_PRICESCHEDULE)
------------------------------
--LEFT JOIN IDCONSIGNEESHIPPERZONE SZ ON SZ.R_CONSIGNEE = VCONS.ConsigneeMasterRowID AND SZ.R_SHIPPER = WH.ROWID
--LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, VCONS.CONSIGNEER_PRICESCHEDULE)
--LEFT JOIN IMPRICESCHEDULEDETAIL PSD ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
--LEFT JOIN RTZONETABLECODES ZONCOD (NOLOCK) ON ZONCOD.ROWID = ISNULL(OH.R_ZONEFREIGHTRATEOVERRIDE,SZ.R_ZONE)
WHERE OH.RECORDTYPE = 'Z'
/*
WHERE OD.QUANTITYSHIPPED <> 0
ORDER BY
		WH.IDENTITYID,
		VCUST.CUSTOMERIDENTITYID,
		ITM.ITEMCODE, 
		CNT.PRINTEDCONTAINERCODE
*/