/* 
--#89 LOST SALES DETAIL 
--#89 LOST SALES SUMMARY (future)
--#89 LOST SALES BY CUST (future)
SELECT * 
FROM VW_RPT_LOST_SALES (NOLOCK) 
WHERE COMPANYID = 'SB'
and warehouseid = '10'
and profilecode = '10.22.S1'
--and transactionnumber = '10-25772'
------- 
ORDER BY SALEYEAR, WAREHOUSEID, GNC_ITEMSORT 
ORDER BY SALEYEAR, WAREHOUSEID, GROUPID, CUSTOMERID, CONSIGNEEID, GNC_ITEMSORT 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_LOST_SALES]
AS
SELECT 
	* 
FROM	( 
		SELECT 
			OH.COMPANYID, 
			OH.RECORDTYPE, 
			OH.TRANSACTIONTYPE, 
			OH.STAGE, 
			DBO.FN_STAGESORT(OH.STAGE, 'OM') AS STAGESORT, 
			OH.USERDEFINEDCODE_2 AS UDC_2, 
			DBO.FN_SALEYEAR(OH.SHIPPINGDATE) AS SALEYEAR, 
			-------	
			WH.IDENTITYID AS WAREHOUSEID, 
			WH.NAME AS WAREHOUSENAME, 
			------- 
			PART.IDENTITYID AS SALESREPID, 
			PART.NAME AS SALESREPNAME, 
			CUST.IDGROUP AS GROUPID, 
			GRP.DESCRIPTION_1 AS GROUPNAME, 
			CUST.IDENTITYID AS CUSTOMERID, 
			CUST.NAME AS CUSTOMERNAME, 
			CONS.IDENTITYID AS CONSIGNEEID, 
			CONS.NAME AS CONSIGNEENAME, 
			------- 
			OH.SHIPPINGDATE AS REQUESTDATE,
			OH.TRANSACTIONDATE,
			OH.INVOICEDATE,
			BD.LASTUPDATEDATETIME AS BE_LASTUPDATE,
			(SELECT PROFILECODE FROM OMTRANSACTIONDP (NOLOCK) WHERE ROWID = OH.R_PROFILE) AS PROFILECODE, 
			(SELECT LOT.LOTCODE FROM IMLOT LOT (NOLOCK) WHERE LOT.ROWID = OD.R_LOT) AS LOTCODE,
			OH.TRANSACTIONNUMBER, 
			------- 
			PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT, 
			PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			CNT.CONTAINERSORT, 
			ITM.SUBCLASSCODE AS QUALITY, 
			------- 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			CNT.PRINTEDCONTAINERCODE, 
			BD.QUANTITYORDERED AS BE_QUANTITYORDERED, 
			BD.QUANTITYALLOWED AS BE_QUANTITYALLOWED, 
			--OD.ORIGINALQUANTITYORDERED, 
			OD.QUANTITYORDERED, 
			OD.REVIEWEDSHIPPEDQUANTITY, 
			OD.CONFIRMEDSHIPPEDQUANTITY, 
			------- Future Evaluation, Pull Tag Review and Pick Confirm
			--OD.ORIGINALQUANTITYORDERED - OD.QUANTITYORDERED AS LOST@FUTURE_EVAL, 
			ISNULL(BD.QUANTITYORDERED, 0) - ISNULL(BD.QUANTITYALLOWED, 0) AS LOST@FUTURE_EVAL, 
			ISNULL(OD.QUANTITYORDERED, 0) - ISNULL(OD.REVIEWEDSHIPPEDQUANTITY, 0) AS LOST@PTR, 
			ISNULL(OD.REVIEWEDSHIPPEDQUANTITY, 0) - ISNULL(OD.CONFIRMEDSHIPPEDQUANTITY, 0) AS LOST@PICK_CONF 
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			LEFT OUTER JOIN DBO.OMBOOKINGEVALUATIONDETAIL (NOLOCK) BD ON BD.R_TRANSACTIONDETAIL = OD.ROWID
			LEFT OUTER JOIN DBO.OMBOOKINGEVALUATIONHEADER (NOLOCK) BH ON BH.ROWID = BD.R_BOOKINGEVALUATIONHEADER AND BH.STATUS = 'U'
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
--			LEFT OUTER JOIN DBO.IMLOT LOT ON LOT.ROWID = OD.R_LOT
			JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY 
			JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
			--LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
			JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
			JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
			JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
			JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ISNULL(OH.R_SALESPERSON_1, ICONS.R_PARTICIPANT) 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID 
			LEFT JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'				--CUSTOMERGROUPNAME 
			LEFT JOIN IDMASTER VIA (NOLOCK) ON VIA.ROWID = OH.R_SHIPVIA 
		WHERE OH.COMPANYID = 'SB' 
		--AND OH.RECORDTYPE='Z'								--COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I'							--ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC'		--EXCLUDING INTERCOMPANY ORDERS 
		AND ISNULL(VIA.NAME,'') <> 'Drive-In'				-- EXCLUDING DRIVE-INS 
		--AND OD.ORIGINALQUANTITYORDERED <> OD.QUANTITYORDERED 
		--AND OD.ORIGINALQUANTITYORDERED <> 0 
		) X 
--WHERE WAREHOUSEID = '10' 
--ORDER BY 
--SALEYEAR, 
--WAREHOUSEID, 
--GNC_ITEMSORT 
