/*
-- LEFT TO SHIP BY KEYREP
SELECT * 
FROM VW_RPT_LEFT_TO_SHIP_KEYREP (NOLOCK) 
WHERE KEYREPID IS NOT NULL 
and customerid = '54840'--'829045'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_LEFT_TO_SHIP_KEYREP]
AS
SELECT 
CO.COMPANYID,
(SELECT PROFILECODE FROM OMTRANSACTIONDP (NOLOCK) WHERE ROWID = OH.R_PROFILE) AS PROFILECODE, --ADDED PER SC 4/7/22 - DT
TRIM(CO.NAME) AS COMPANYNAME,
TRIM(WH.IDENTITYID) AS WAREHOUSEID, 
TRIM(WH.NAME) AS WAREHOUSENAME, 
TRIM(KPART.IDENTITYID) AS KEYREPID,
TRIM(KPART.NAME) AS KEYREPNAME,
TRIM(PART.IDENTITYID) AS SALESREP,
TRIM(PART.NAME) AS SALESREPNAME,
ICONS.USERDEFINEDCODE_12 AS TERRITORYCODE,
TER.DESCRIPTION_1 AS TERRITORYDESC,	
ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS NATLACCT,
OH.STAGE,
DBO.FN_STAGESORT(OH.STAGE,'OM') AS STAGESORT,
SUBSTRING(DBO.FN_STAGESORT(OH.STAGE,'OM'),4,18) AS STAGENAME,
OH.USERDEFINEDCODE_2 AS STEP,
DBO.FN_STEPSORT(OH.USERDEFINEDCODE_2) AS STEPSORT,
SUBSTRING(DBO.FN_STEPSORT(OH.USERDEFINEDCODE_2),4,9) AS STEPNAME,
OH.INVENTORYREVIEW,
OH.CREDITSTATUSREVIEW,
(SELECT AB.FLAGDESCRIPTION FROM ABFLAGFIELD AB (NOLOCK) WHERE AB.FLAGVALUE = OH.CREDITSTATUSREVIEW AND AB.FIELDNAME = 'CREDITSTATUSREVIEW') AS CREDITSTATUSREVIEWDESC,
OH.RECORDTYPE,
OH.SHIPPINGDATE AS TRANSACTIONDATE,	
DBO.FN_SALEYEAR(OH.SHIPPINGDATE) AS SALEYEAR,
CUST.IDENTITYID AS CUSTOMERID,
TRIM(CUST.NAME) AS CUSTOMERNAME,
IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
TRIM(VCONS.CONSIGNEEIDENTITYID) AS CONSIGNEEID, 
TRIM(VCONS.CONSIGNEENAME) AS CONSIGNEENAME, 
TRIM(ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY)) + ', ' + TRIM(ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE)) AS CONSIGNEECITYSTATE, 
TRIM(ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY)) AS CONSIGNEECITY, 
TRIM(ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE)) AS CONSIGNEESTATE, 
TRIM(ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP)) AS CONSIGNEEZIP, 
TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ) AS ALTSHIPTELEPHONE_1,	--ALTSHIPCOMMENT 
NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-') AS SHIPTOTELEPHONE_1,		--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
--CONTACT INFO NOW WORKS AS INTENDED:
CONT.IDENTITYID AS CONTACTID,
TRIM(CONT.NAME) AS CONTACTNAME,
ICONT.USERDEFINEDCODE_1 AS CONTACTROLE,
ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPCOMMENT READY TO PRINT 
		NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE READY TO PRINT 
	) AS CONTACTTELEPHONE_1, --OVERRIDE SHIPTOTELEPHONE WITH ALTSHIPCOMMENT IF IT EXISTS.

OH.USERDEFINEDREFERENCE_3 AS ORDEREDBY,
TRIM(TERM.TERMSCODE) AS TERMSCODE,

--TRIP RELATED INFORMATION:
TRIM(OH.FMTRIPNUMBER) AS FMTRIPNUMBER, 
TRIM(FH.TRIPNO)+'/'+ISNULL(TRIM(STR(FD.DELSTOPNO)),'') AS TRIPSTOPNO,
FH.PLANSTART AS TRIPDATE,	--SIMPLY GUESSING THAT THIS FIELD IS INTENDED.
--FH.PLANFINISH, 
--FD.SCHEDULEDDELDEPATUREDT, FD.SCHEDULEDDELARRIVALDT, 
--OBJ.SCHEDULEDDELDEPARTUREDT, OBJ.SCHEDULEDDELIVERYDT, 

--JUST INCASE CREDITS/DEBITS ARE INCLUDED, REVERSE THE SIGN:
IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
	DBO.FN_ORDERVALUE(OH.ROWID, 'ITEMPRICE') * -1, 
	DBO.FN_ORDERVALUE(OH.ROWID, 'ITEMPRICE')
	) AS TOTALITEMPRICE,
IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
	DBO.FN_ORDERVALUE(OH.ROWID, 'FREIGHT') * -1,
	DBO.FN_ORDERVALUE(OH.ROWID, 'FREIGHT') 
	)AS TOTALFREIGHT,
IIF(OH.TRANSACTIONTYPE IN ('C','J'), 
	DBO.FN_ORDERVALUE(OH.ROWID, NULL) * -1,
	DBO.FN_ORDERVALUE(OH.ROWID, NULL) 
	)AS ORDERTOTAL,
--REDUNDANT AND USES ARGOS FUNCTION WHICH DOESN'T USE NEW GNC BACKORDER/CANCEL LOGIC, USE MY FUNCTION (ABOVE) INSTEAD:
--[DBO].[FNOM_CALCULATETRANSTOTALS](OH.ROWID,'OUTTOTALAMOUNT') AS TOTALAMOUNT,

TRIM(OH.TRANSACTIONNUMBER) AS TRANSACTIONNUMBER,
OH.STATUS,
OH.SHIPPINGDATE AS REQUESTDATE,
OH.USERDEFINEDCODE_1 AS REQUESTDATETYPE,
[DBO].[FNOM_CALCULATETRANSTOTALS](OH.ROWID,'OUTNETWEIGHT') AS NETWEIGHT,
[DBO].[FNOM_CALCULATETRANSTOTALS](OH.ROWID,'OUTTOTALVOLUME') AS TOTCNTVOLUME,
ZON.CODE AS FREIGHTZONE,
ICONS.COMMENT AS GENERALLOADINSTR,
OH.COMMENT AS ORDERSHIPINSTR,
ICONS.USERDEFINEDREFERENCE_7 AS CONSDELNOTE
FROM OMTRANSACTIONHEADER OH (NOLOCK)
--------STARTED TO ADD OMTRANSACTIONDETAIL RECORDS BUT ABANDONED THE IDEA
--LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
--------
LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
--CUSTOMER DATA
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
LEFT JOIN IDTERMS TERM (NOLOCK) ON TERM.ROWID = ICUST.R_TERMS
--KEYREP DATA
LEFT JOIN IDRELATIONSHIPLINKS LCUST (NOLOCK) ON LCUST.R_IDMASTER = CUST.ROWID AND LCUST.IDMASTERTYPE = '01' AND LCUST.IDMEMBERTYPE = '14'
LEFT JOIN IDMASTER KPART (NOLOCK) ON KPART.ROWID = LCUST.R_IDMEMBER
--CONSIGNEE DATA
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER 
LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.CONSIGNEEMASTERROWID
LEFT JOIN IDCODES TER (NOLOCK) ON TER.CODE = ICONS.USERDEFINEDCODE_12 AND TER.CODETYPE = '3M' --TERRITORY

--CONTACT DATA	--USING NEW FUNCTION DBO.FN_GETCONTACT SO RECORDS DON'T DROP/ADD:
LEFT JOIN IDMASTER CONT (NOLOCK) ON CONT.ROWID = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
LEFT JOIN IDCONTACTS ICONT (NOLOCK) ON ICONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')

LEFT JOIN IDCONSIGNEESHIPPERZONE FRT (NOLOCK) ON FRT.R_CONSIGNEE = ICONS.R_IDENTITY AND FRT.R_SHIPPER = OH.R_FMSHIPPER
LEFT JOIN RTZONETABLECODES ZON (NOLOCK) ON ZON.ROWID = ISNULL(OH.R_ZONEFREIGHTRATEOVERRIDE, FRT.R_ZONE)

--TRIP HEADER/DETAIL DATA	--SHELLY WANTED "TRIP DATE" FIELD ADDED (WHICH DATE IS UNCLEAR)
LEFT JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.R_SOURCEID = OH.ROWID
LEFT JOIN FMTRIPDETAIL FD (NOLOCK) ON FD.R_FMDISPATCHOBJECT = OBJ.ROWID
LEFT JOIN FMTRIPHEADER FH (NOLOCK) ON FH.ROWID = FD.R_TRIPHEADER
WHERE	OH.RECORDTYPE = 'R'
AND		OH.TRANSACTIONTYPE = 'I' --EXCLUDE CREDITS/ADJUSTMENTS (C,J) PER STEVE COPPEDGE
AND		OH.STAGE <> 'L'	--ELIMINATE "CANCELLED" ORDERS.
------------------------------------------