/*
--68 Inventory by Item - Lot (This is similar to 119)
SELECT * 
FROM VW_RPT_INVENTORY_BY_ITEM_LOT (NOLOCK) 
WHERE MCSTATUS = 'B'
WHERE RECORDTYPE <> 'P' 
AND ITEMCODE = '001030.020.1'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVENTORY_BY_ITEM_LOT]
AS
SELECT
ISNULL(MC.STATUS,'A') AS MCSTATUS,	--IS MASTERCODE ACTIVE OR NOT
CO.COMPANYID,
CO.NAME AS COMPANYNAME,
ITM.RECORDTYPE,
WH.IDENTITYID AS WAREHOUSEID, 
WH.NAME AS WAREHOUSENAME,
PGC.PRODUCTCATEGORYCODE AS PLANTGROUPCODE,
ITM.USERDEFINEDCODE_1 AS GENUSCODE, 
GEN.DESCRIPTION_1 AS GENUSNAME,
ITM.USERDEFINEDCODE_10 AS PULLERRESP,
ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
ITM.USERDEFINEDCODE_11 AS GRADELABELCOLOR,
ITM.SPECIFICATIONCODE AS GRADEMEASUREMENT,
ITM.USERDEFINEDCODE_8 AS FIELDTAGTYPE,
VLOT.USERDEFINEDCODE_4 AS SPECIALPULLER,
VLOT.USERDEFINEDCODE_5 AS PULLTAGSUSPEND,
CNT.PRINTEDCONTAINERCODE,
--	--VLOT.USERDEFINEDDATE_2 AS FUTUREEVALUATIONDATE, --MOVED, WRONG
VLOT.USERDEFINEDCODE_3 AS HOLDSTOP,
--	--(CASE WHEN GETDATE() BETWEEN VLOT.USERDEFINEDDATE_4 AND VLOT.USERDEFINEDDATE_5 THEN VLOT.USERDEFINEDCODE_3 END) AS HOLDSTOP,
VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON, --APPEND TO SALESNOTE?
VLOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
VLOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE,
VLOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1,
ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
ITM.REFERENCE_1 AS COMMONNAME,
ITM.REFERENCE_3 AS REVERSECOMMONSORT,
ITM.REFERENCE_5 AS SORTNAMEVARIETY,
ITM.ITEMCODE,
(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
CNT.CONTAINERCODE,
ITM.SUBCLASSCODE AS QUALITYCODE,
VLOT.LOTCODE,
LEFT(VLOT.LOTCODE,2) + 2000 AS SALEYEAR,
SUBSTRING(VLOT.LOTCODE,4,2) AS SEASON,
LOC.LOCATIONCODE, 
--SUBSTRING(LOC.LOCATIONCODE,1,1) AS BLOCKALPHA,
--SUBSTRING(LOC.LOCATIONCODE,3,2) AS BLOCKNUMBER,
--SUBSTRING(LOC.LOCATIONCODE,6,3) AS BAY,
--	--SUBSTRING(LOC.LOCATIONCODE,10,2) AS SOURCE,
--	--LOC.PRIORITY AS LOCATIONPRIORITY, --IS THIS THE RIGHT FIELD?
--	--'' AS SPECIALDESIGNATOR, --FIND A SOURCE FOR THIS FIELD
ITM.USERDEFINEDQUANTITY_1 AS LARGEPTRQTY, 
DBO.FN_MCATTRIBUTES(MC.ROWID,'SOURCE') AS SOURCE,

NULLIF(
	ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigItem'),'')+'.'+
	ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigCust'),'')+'.'+
	ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID, 'DesigLoc'),''),
	'..') AS DesigICL,
--ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGCUST'),'') AS DESIGCUST,
--ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGITEM'),'') AS DESIGITEM,
--ISNULL(DBO.FN_MCATTRIBUTES(MC.ROWID,'DESIGLOC'),'') AS DESIGLOC,
DBO.FN_MCATTRIBUTES(MC.ROWID,'PRIORITY') AS PRIORITY,
DBO.FN_MCATTRIBUTES(MC.ROWID,'FUTURE EVAL') AS FUTUREEVAL,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCNOTEDATE') AS LOCNOTEDATE,
DBO.FN_MCATTRIBUTES(MC.ROWID,'LOCATION NOTE') AS LOCATIONNOTE,

--NEW SPECIAL ATTRIBUTE ADDED TO FN_MCATTRIBUTES: This is master code ‘Production Quantity’  +  PTR Review Qty
--Ellen might request in the future using this value as the ONHAND Qty for this report - 8/13/21 DT
DBO.FN_MCATTRIBUTES_IA(MC.ROWID,'ONHAND') AS ONHAND_LOC,
--CAST (DBO.FN_MCATTRIBUTES(MC.ROWID,'ONHAND') AS NUMERIC) AS ONHAND_LOC,

--VLOT.ON_HAND, VLOT.OUT_SHIPPED, VLOT.AVAILABLE, VLOT.NETAVAILABLE,	--THIS IS AT LOT LEVEL - DON'T USE
LQS.ON_HAND, LQS.OUT_SHIPPED, LQS.AVAILABLE, LQS.NETAVAILABLE,			--THIS IS AT LOCATION LEVEL
IIF(SUBSTRING(VLOT.LOTCODE, 3, 3) LIKE '%F1%', LQS.NETAVAILABLE, 0) AS FALL1,
IIF(SUBSTRING(VLOT.LOTCODE, 3, 3) LIKE '%S1%', LQS.NETAVAILABLE, 0) AS SPRING1,
IIF(SUBSTRING(VLOT.LOTCODE, 3, 3) LIKE '%U1%', LQS.NETAVAILABLE, 0) AS SUMMER1,
IIF(SUBSTRING(VLOT.LOTCODE, 3, 3) LIKE '%U2%', LQS.NETAVAILABLE, 0) AS SUMMER2,
IIF(SUBSTRING(VLOT.LOTCODE, 3, 3) LIKE '%U3%', LQS.NETAVAILABLE, 0) AS SUMMER3
FROM OMREVIEWMASTERCODES MC (NOLOCK)
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = MC.R_ITEM
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.ROWID = MC.R_LOT-- ON VLOT.R_ITEM = ITM.ROWID
JOIN IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) ON LQS.R_LOT = VLOT.ROWID AND LQS.R_LOCATION = MC.R_LOCATION
LEFT OUTER JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = MC.R_LOCATION-- LOC.ROWID = LQS.R_LOCATION
LEFT OUTER JOIN IMPRICECODESHEADER PCH (NOLOCK) ON PCH.ROWID = ITM.R_PRICETABLE
LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUS
--ELIMINATE INACTIVE MASTERCODES:
--WHERE ISNULL(MC.STATUS, 'A') <> 'I'


--FROM IMITEM ITM (NOLOCK)
--JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
--LEFT OUTER JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
--JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
--JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
--JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
--JOIN IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) ON LQS.R_LOT = VLOT.ROWID
--LEFT OUTER JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = LQS.R_LOCATION
--LEFT OUTER JOIN IMPRICECODESHEADER PCH (NOLOCK) ON PCH.ROWID = ITM.R_PRICETABLE
--LEFT OUTER JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUS
--WHERE ITM.RECORDTYPE = 'R' AND ITM.ITEMCODE = '001602.030.1'
