/* 
--PICK LIST EXCEL [NEW REPORT FOR HARRISON COOK] 

SELECT * 
FROM VW_RPT_PICKLIST (NOLOCK) 
WHERE COMPANYID = 'SB' 
---------------------------------- 
--AND WAREHOUSEID = '20' 
--AND PLANSTART = GETDATE()+1--'10/19/2021' 
--ORDER BY WAREHOUSEID, PLANSTART, GNC_ITEMSORT
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_PICKLIST] 
AS 
SELECT
	CO.COMPANYID, 
	TRIM(CO.NAME) AS COMPANYNAME, 
	WH.IDENTITYID AS WAREHOUSEID, 
	TRIM(WH.NAME) AS WAREHOUSENAME, 
	--TRIM(HDR.TRIPNO) AS TRIPNO, 
	--HDR.PLANSTART, 
	CAST (HDR.PLANSTART AS DATE) AS PLANSTART, 
	TRIM(ITM.ITEMCODE) AS ITEMCODE, 
	ITM.REFERENCE_1 AS COMMONNAME, 
	IL.OUT_SHIPPED AS OUT_SHIPPED, 
	TRIM(LOC.LOCATIONCODE) AS LOCATIONCODE, 
	PGC.PRODUCTCATEGORYCODE+ITM.REFERENCE_5+CNT.CONTAINERSORT+ITM.SUBCLASSCODE AS GNC_ITEMSORT 
FROM FMTRIPHEADER HDR (NOLOCK) 
	JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID 
	JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT 
	JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID 
	JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
	JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID 
	JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = IL.R_LOCATION 
	JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
	JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
	JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID 
WHERE IL.OUT_SHIPPED <> 0