/*
--131 ITEMLOT_NOTES		WAS SALES_NOTES
SELECT
VW_RPT_ITEMLOT_NOTES.*
FROM VW_RPT_ITEMLOT_NOTES (NOLOCK)
WHERE VW_RPT_ITEMLOT_NOTES.RECORDTYPE <> 'P'
AND VW_RPT_ITEMLOT_NOTES.ISNOTES IS NOT NULL
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_ITEMLOT_NOTES]
AS
SELECT
	CO.COMPANYID,
	CO.NAME AS COMPANYNAME,
	ITM.RECORDTYPE,
	WH.IDENTITYID AS WAREHOUSEID, 
	WH.NAME AS WAREHOUSENAME,
	LEFT(PGC.PRODUCTCATEGORYCODE,3) AS PLANTGROUPCODE,
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUP,
	ITM.REFERENCE_5 AS SORTNAMEVARIETY,
	CNT.CONTAINERSORT,
	ITM.SUBCLASSCODE AS QUALITYCODE,
	ITM.USERDEFINEDCODE_1 AS GENUSCODE,
	GEN.DESCRIPTION_1 AS GENUSNAME,
	ITM.ITEMCODE,
	(SELECT ITMDP.PROFILECODE FROM IMITEMDP ITMDP (NOLOCK) WHERE ITMDP.ROWID = ITM.R_PROFILE) AS VARIETYCODE,
	CNT.CONTAINERCODE,
	CNT.PRINTEDCONTAINERCODE,
	ITM.REFERENCE_1 AS COMMONNAME,
	ITM.REFERENCE_2 AS BOTANICALNAME,
	ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
	DBO.FN_LISTPRICE(ITM.ROWID,NULL,NULL) AS LISTPRICE,
	VLOT.LOTCODE,
	LEFT(VLOT.LOTCODE,2) AS LOTYEAR,
	TRIM(SUBSTRING(VLOT.LOTCODE,3,8)) AS LOTSEASON,
	--HOLDSTOP FIELDS:
	VLOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
	VLOT.USERDEFINEDDATE_1 AS HOLDSTOPSTARTDATE,
	VLOT.USERDEFINEDDATE_2 AS HOLDSTOPENDDATE,
	--HOLDSTOPREASON FIELDS:
	VLOT.USERDEFINEDREFERENCE_4 AS HOLDSTOPREASON,
	VLOT.USERDEFINEDDATE_4 AS HOLDSTOPREASONSTARTDATE,
	VLOT.USERDEFINEDDATE_5 AS HOLDSTOPREASONENDDATE,
	--INVENTORYNOTE FIELDS:
	VLOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE,
	VLOT.USERDEFINEDDATE_8 AS INVENTORYNOTESTARTDATE,
	VLOT.USERDEFINEDDATE_9 AS INVENTORYNOTEENDDATE,
	--SALESNOTE FIELDS:
	VLOT.USERDEFINEDREFERENCE_7 AS SALESNOTE,
	VLOT.USERDEFINEDDATE_6 AS SALESNOTESTARTDATE,
	VLOT.USERDEFINEDDATE_7 AS SALESNOTEENDDATE,
	--FILTER LOGIC:
	NULLIF(ISNULL(VLOT.USERDEFINEDCODE_3,'')+
	ISNULL(VLOT.USERDEFINEDREFERENCE_4,'')+
	ISNULL(VLOT.USERDEFINEDREFERENCE_6,'')+
	ISNULL(VLOT.USERDEFINEDREFERENCE_7,''),'') AS ISNOTES
FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID
JOIN VW_IMLOTVIEW2 VLOT (NOLOCK) ON VLOT.R_ITEM = ITM.ROWID
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = VLOT.ROWID
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
LEFT JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUS
	--NOT NEEDED, IT IS NOT AT THE LOT LEVEL, PER DJ
	--(SELECT TOP 1 LOC.LOCATIONCODE FROM IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) 
	--JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = LQS.R_LOCATION --AND LOC.PRIORITY < 10
	--WHERE LQS.R_ITEM = ITM.ROWID AND LQS.R_LOT = LOT.ROWID AND LQS.AVAILABLE > 0
	--ORDER BY LOC.PRIORITY) AS PRIORITYONELOCATION,
