/*
--Inventory by Item-Inquiry 
SELECT * 
FROM VW_RPT_INVENTORY_BY_ITEM_INQUIRY 
WHERE 1=1--LOTYEAR <= CY

--where itemcode like '000749.%' 
-- 
WHERE MCSTATUS = ''--SHIPPERCODE = '10' 
--AND ITEMCODE = '009553.020.1' 
--AND ITEMCODE = '008137.081.1' 
*/ 

CREATE OR ALTER VIEW [dbo].[VW_RPT_INVENTORY_BY_ITEM_INQUIRY] 
AS 
SELECT 
	DBO.FN_DATE2YEAR(GETDATE())%100 AS CY, 
	LEFT(LOTCODE,2) AS LOTYEAR, 
	ROWID, COMPANYID, SHIPPERCODE, 
	ITEMCODE, LEFT(ITEMCODE,10) AS ITEMTRIM, ALPHA, 
	PLANTGROUP, SORTNAMEVARIETY, CONTAINERSORT, 
	GENUS, SIZE, PULLERRESPONSIBILITY, 
	VARIETY, QUALITY, COMMONNAME, 
	BOTANICALNAME, BRAND_POT_TEXT, BRAND_POT_REQ, BRAND, 
	FIELDTAGCOLOR, GRADELABELCOLOR, 
	SPECIFICATION, QUALITYORDER, 
	SEASONYEAR, SPECPULLER, SUSPEND, SUSPEND_TO, 
	HSSTART, HS, HSREASON, 
	INVENTORYNOTE, SNSTART, SALESNOTE, 
	PENDINGRECEIPTS, BACKORDERRECEIPTS, INRECEIVING, 
	HSREASONSTART, HSREASONEND, 
	INSTART, INEND, 
	F1, S1, U1, 
	F2, S2, U2, 
	F3, S3, U3, 
	X, Y, Z, --LEFTTOSELL, 
	OVERSELLPERCENTAGE, 
	LOTCODE, LOCATIONCODE, SOURCE, 
	DESIGCUST, DESIGITEM, DESIGLOC, PRIORITY, 
	ONHAND, SHIPPINGQUANTITY, 
	FUTUREEVAL, LOCATIONNOTE, PRISETBY, 
	CAST (PRIUPDATE AS DATE) AS PRIUPDATE, 
	CAST (LOCNOTEDATE AS DATE) AS LOCNOTEDATE, 
	BYPASSLOCATION, LOCATIONPTN1, LOCATIONPTN2, 
	PTNOTE1, MCTYPE, MCSTATUS, SORT,
	(SELECT TOP 1 PULLTAGNO FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_MASTERCODE = MC_ROWID) AS TAGNO	--added to be able to sort by tagno per Ellen 9/11/24 DT

FROM
(
	SELECT mc.rowid as mc_rowid, --added to enable tagno sort.
		ITM.ROWID, ITM.COMPANYID, WH.IDENTITYID AS SHIPPERCODE, ITM.ITEMCODE, LOC.CLASSCODE AS ALPHA, 
		PC.PRODUCTCATEGORYCODE  AS PLANTGROUP, 
		ITM.REFERENCE_5 AS SORTNAMEVARIETY, CNT.CONTAINERSORT, 
		CI.DESCRIPTION_1 AS GENUS, LOT.CLASSCODE AS SIZE, 
		ITM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY, DP.PROFILECODE AS VARIETY, 
		ITM.SUBCLASSCODE AS QUALITY, ITM.REFERENCE_1 AS COMMONNAME, 
		ITM.DESCRIPTION_2 AS BOTANICALNAME, 
		IIF(LEFT(ITM.USERDEFINEDCODE_12, 4) = 'NONE', ITM.USERDEFINEDCODE_2, ITM.USERDEFINEDCODE_12) AS BRAND_POT_TEXT, 
		ITM.USERDEFINEDCODE_12 AS BRAND_POT_REQ, ITM.USERDEFINEDCODE_2 AS BRAND, 
		ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR, ITM.USERDEFINEDCODE_11 AS GRADELABELCOLOR, 
		ITM.SPECIFICATIONCODE AS SPECIFICATION, 
		CASE 
			WHEN ITM.SUBCLASSCODE ='1' THEN '1'
			WHEN ITM.SUBCLASSCODE ='2' THEN '2'
			WHEN ITM.SUBCLASSCODE ='3' THEN '3'
			WHEN ITM.SUBCLASSCODE ='4' THEN '4'
			WHEN ITM.SUBCLASSCODE ='0' THEN '5'
		END AS QUALITYORDER, 
		LOT.USERDEFINEDCODE_6 AS SEASONYEAR, 
		LOT.USERDEFINEDCODE_4 AS SPECPULLER, 
		CASE WHEN LOT.USERDEFINEDCODE_5 = 'SUSPEND' THEN 'Y' ELSE LOT.USERDEFINEDCODE_5 END AS SUSPEND, 
		LOT.USERDEFINEDREFERENCE_3 AS SUSPEND_TO, 
		LOT.USERDEFINEDDATE_1 AS HSSTART, LOT.USERDEFINEDCODE_3 AS HS, 
		LOT.USERDEFINEDREFERENCE_4 AS HSREASON, LOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE, 
		LOT.USERDEFINEDDATE_6 AS SNSTART, LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE, 
		LOT.IN_ORDERED AS PENDINGRECEIPTS, LOT.IN_BACKORDER AS BACKORDERRECEIPTS, 
		LOT.IN_RECEIVING AS INRECEIVING, 
		LOT.USERDEFINEDDATE_4 AS HSREASONSTART, LOT.USERDEFINEDDATE_5 AS HSREASONEND, 
		LOT.USERDEFINEDDATE_8 AS INSTART, LOT.USERDEFINEDDATE_9 AS INEND, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='F1' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS F1, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='S1' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS S1, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='U1' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS U1, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='F2' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS F2, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='S2' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS S2, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='U2' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS U2, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='F3' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS F3, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='S3' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS S3, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='U3' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS U3, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='X' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS X, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='Y' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS Y, 
		CASE	WHEN LOT.USERDEFINEDCODE_10 ='Z' 
				THEN DBO.FN_SUPPLYROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL, 'I') - DBO.FN_DEMANDROLLUP(ITM.ROWID, LEFT(LOT.LOTCODE,2), SUBSTRING(LOT.LOTCODE,4,2)+'%', NULL) 
				ELSE 0 
			END AS Z, 
		--CASE 
		--	WHEN LOT.USERDEFINEDCODE_10 ='F1' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='S1' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='U1' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='F2' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='S2' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='U2' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='F3' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='S3' THEN LOT.NETAVAILABLE
		--	WHEN LOT.USERDEFINEDCODE_10 ='U3' THEN LOT.NETAVAILABLE ELSE 0
		--END AS LEFTTOSELL, 
		LOT.OVERSELLPERCENTAGE, 
		LOT.LOTCODE, 
		LOC.LOCATIONCODE, 
		NULL AS SOURCE, 
		NULL AS DESIGCUST, 
		NULL AS DESIGITEM, 
		NULL AS DESIGLOC, 
		NULL AS PRIORITY, 
		NULL AS ONHAND, 
		NULL AS SHIPPINGQUANTITY, 
		NULL AS FUTUREEVAL, 
		NULL AS LOCATIONNOTE, 
		NULL AS PRISETBY, 
		NULL AS PRIUPDATE, 
		NULL AS LOCNOTEDATE, 
		NULL AS BYPASSLOCATION, 
		NULL AS LOCATIONPTN1, 
		NULL AS LOCATIONPTN2, 
		LOT.USERDEFINEDREFERENCE_1 AS PTNOTE1, 
		'LOT' AS MCTYPE, 
		ISNULL(MC.STATUS,'A') AS MCSTATUS, 
		 LOT.LOTCODE AS SORT 
	FROM IMITEM ITM
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	LEFT JOIN VW_IMLOTVIEW2 LOT (NOLOCK) ON LOT.R_ITEM= ITM.ROWID 
	LEFT JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.R_LOT=LOT.ROWID 
	LEFT JOIN IMITEMDP DP (NOLOCK) ON DP.ROWID = ITM.R_PROFILE 
	LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID=MC.R_LOCATION 
	LEFT JOIN IDCODES CD (NOLOCK) ON CD.CODE = LOC.CLASSCODE AND CD.CODETYPE='26' 
	LEFT JOIN IMCODES CI (NOLOCK) ON CI.CODE = ITM.USERDEFINEDCODE_1 AND CI.CODETYPE = '11' 
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
	LEFT JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID =ITM.R_PRODUCTCATEGORY 
	--Only include LOT records with inventory or H/S  - DT/Ellen 9/9/21 
	WHERE (LOT.ON_HAND <> 0 OR LOT.AVAILABLE <> 0 OR LOT.NETAVAILABLE <> 0 OR LOT.USERDEFINEDCODE_3 IS NOT NULL) 

	UNION ALL 

	SELECT  OMREVIEWMASTERCODES.rowid as mc_rowid, --added to enable tagno sort.
		ITM.ROWID, ITM.COMPANYID, WH.IDENTITYID AS SHIPPERCODE, ITM.ITEMCODE, LOC.CLASSCODE AS ALPHA, 
		PC.PRODUCTCATEGORYCODE  AS PLANTGROUP, 
		ITM.REFERENCE_5 AS SORTNAMEVARIETY, CNT.CONTAINERSORT, 
		CI.DESCRIPTION_1 AS GENUS, LOT.CLASSCODE AS SIZE, 
		ITM.USERDEFINEDCODE_10 AS PULLERRESPONSIBILITY, DP.PROFILECODE AS VARIETY, 
		ITM.SUBCLASSCODE AS QUALITY, ITM.REFERENCE_1 AS COMMONNAME, 
		ITM.DESCRIPTION_2 AS BOTANICALNAME, 
		IIF(LEFT(ITM.USERDEFINEDCODE_12, 4) = 'NONE', ITM.USERDEFINEDCODE_2, ITM.USERDEFINEDCODE_12) AS BRAND_POT_TEXT, 
		ITM.USERDEFINEDCODE_12 AS BRAND_POT_REQ, ITM.USERDEFINEDCODE_2 AS BRAND, 
		ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR, ITM.USERDEFINEDCODE_11 AS GRADELABELCOLOR, 
		ITM.SPECIFICATIONCODE AS SPECIFICATION, 
		CASE 
			WHEN ITM.SUBCLASSCODE ='1' THEN '1'
			WHEN ITM.SUBCLASSCODE ='2' THEN '2'
			WHEN ITM.SUBCLASSCODE ='3' THEN '3'
			WHEN ITM.SUBCLASSCODE ='4' THEN '4'
			WHEN ITM.SUBCLASSCODE ='0' THEN '5'
		END AS QUALITYORDER, 
		LOT.USERDEFINEDCODE_6 AS SEASONYEAR, 
		LOT.USERDEFINEDCODE_4 AS SPECPULLER, 
		CASE WHEN LOT.USERDEFINEDCODE_5 = 'SUSPEND' THEN 'Y' ELSE LOT.USERDEFINEDCODE_5 END AS SUSPEND, 
		LOT.USERDEFINEDREFERENCE_3 AS SUSPEND_TO, 
		LOT.USERDEFINEDDATE_1 AS HSSTART, LOT.USERDEFINEDCODE_3 AS HS, 
		LOT.USERDEFINEDREFERENCE_4 AS HSREASON, LOT.USERDEFINEDREFERENCE_6 AS INVENTORYNOTE, 
		LOT.USERDEFINEDDATE_6 AS SNSTART, LOT.USERDEFINEDREFERENCE_7 AS SALESNOTE, 
		LOT.IN_ORDERED AS PENDINGRECEIPTS, LOT.IN_BACKORDER AS BACKORDERRECEIPTS, 
		LOT.IN_RECEIVING AS INRECEIVING, 
		LOT.USERDEFINEDDATE_4 AS HSREASONSTART, LOT.USERDEFINEDDATE_5 AS HSREASONEND, 
		LOT.USERDEFINEDDATE_8 AS INSTART, LOT.USERDEFINEDDATE_9 AS INEND, 
		0 AS F1, 0 AS S1, 0 AS U1, 
		0 AS F2, 0 AS S2, 0 AS U2, 
		0 AS F3, 0 AS S3, 0 AS U3, 
		0 AS X , 0 AS Y , 0 AS Z , 
		--1 AS LEFTTOSELL, 
		LOT.OVERSELLPERCENTAGE, 
		LOT.LOTCODE, LOC.LOCATIONCODE, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='SOURCE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS SOURCE, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='DESIGCUST' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGCUST, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='DESIGITEM' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGITEM, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='DESIGLOC' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS DESIGLOC, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='PRIORITY' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS PRIORITY, 
		--Per ELLEN, ONHAND is ProductionQuantity + CommittedQuantity in OMREVIEWINVENTORYASSIGNMENT: - 8/13/21 DT 
		ISNULL(OMREVIEWMASTERCODES.PRODUCTIONQUANTITY,0) 
			+ ( ISNULL((SELECT SUM(ISNULL(IA.COMMITTEDQUANTITY,0)) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
				LEFT JOIN OMTRANSACTIONDETAIL D (NOLOCK) ON D.ROWID =IA.R_TRANSACTIONDETAIL 
				WHERE D.RECORDTYPE='R' AND IA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID),0) 
			) AS ONHAND, 
		ISNULL((SELECT SUM(ISNULL(IA.COMMITTEDQUANTITY,0)) FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) 
		LEFT JOIN OMTRANSACTIONDETAIL D (NOLOCK) ON D.ROWID =IA.R_TRANSACTIONDETAIL 
		WHERE D.RECORDTYPE='R' AND IA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID),0) AS SHIPPINGQUANTITY, 
		--AVAILABLE = ONHAND - SHIPPING 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='FUTURE EVAL' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS FUTUREEVAL, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='LOCATION NOTE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONNOTE, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='PRISETBY' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS PRISETBY, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='PRIUPDATE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS PRIUPDATE, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='LOCNOTEDATE' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCNOTEDATE, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='BYPASSLOC' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS BYPASSLOCATION, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='LOCATIONPTN1' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONPTN1, 
		ISNULL((SELECT TOP 1 VALUE FROM OMREVIEWMASTERCODEATTRIBUTES MCA (NOLOCK) 
		LEFT JOIN OMREVIEWATTRIBUTES A (NOLOCK) ON A.ROWID = MCA.R_ATTRIBUTE 
		WHERE A.NAME ='LOCATIONPTN2' AND MCA.R_MASTERCODE=OMREVIEWMASTERCODES.ROWID ),'') AS LOCATIONPTN2, 
		LOT.USERDEFINEDREFERENCE_1 AS PTNOTE1, 
		'MC' AS MCTYPE, 
		ISNULL(OMREVIEWMASTERCODES.STATUS,'A') AS MCSTATUS, 
		LOC.LOCATIONCODE AS SORT 
	FROM OMREVIEWMASTERCODES (NOLOCK) --IMITEM 
	JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OMREVIEWMASTERCODES.R_ITEM 
	JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE 
	JOIN VW_IMLOTVIEW2 LOT (NOLOCK) ON LOT.ROWID = OMREVIEWMASTERCODES.R_LOT  --ITEMITM.ROWID 
	--LEFT JOIN OMREVIEWMASTERCODES MC (NOLOCK) ON MC.R_LOT=LOT.ROWID 
	LEFT JOIN IMITEMDP DP (NOLOCK) ON DP.ROWID = ITM.R_PROFILE 
	LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID=OMREVIEWMASTERCODES.R_LOCATION 
	LEFT JOIN IDCODES CD (NOLOCK) ON CD.CODE = LOC.CLASSCODE AND CD.CODETYPE='26' 
	LEFT JOIN IMCODES CI (NOLOCK) ON CI.CODE = ITM.USERDEFINEDCODE_1 AND CI.CODETYPE='11' 
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
	LEFT JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID =ITM.R_PRODUCTCATEGORY 
) AS ITEMVIEW 
--ELIMINATE INACTIVE MASTERCODES: 
--WHERE ISNULL(MCSTATUS, 'A') <> 'I' 
--WHERE LEFTTOSELL <> 0 --This was eliminating too many lot records. DT/Ellen 9/9/21 


