/*
--FUTURE: VW_RPT_PLANTING_PROGRESS_SUMMARY 
--Planting Progress Summary Mgmt
SELECT * 
FROM VW_RPT_PLANTING_PROGRESS_SUMMARY (NOLOCK) 
WHERE 1=1 
--
and warehouseid = '10' 
and scheduleyear = '24'
and left(udc_b,7) = 'F COLOR'
*/

CREATE OR ALTER VIEW [DBO].[VW_RPT_PLANTING_PROGRESS_SUMMARY] 
AS 
SELECT 
	COMPANYID, 
	SCHEDULEYEAR, 
	WAREHOUSEID, 
	WAREHOUSENAME, 
	UDC_B, 
	TARGETPLANTINGDATE, 
	PSID, 
	TARGETPLANTINGQTY, 
	TARGETPLANTINGQTY*TARGETPRICE AS TARGETPLANTINGVALUE, 
	SUM(ACTUALPLANTEDQTY) AS ACTUALPLANTEDQTY, 
	SUM(ACTUALPLANTEDQTY*LISTPRICE) AS ACTUALPLANTEDVALUE 
FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
WHERE RECORDTYPE = 'R' 
GROUP BY
	COMPANYID, 
	SCHEDULEYEAR, 
	WAREHOUSEID, 
	WAREHOUSENAME, 
	UDC_B, 
	TARGETPLANTINGDATE, 
	PSID, 
	TARGETPLANTINGQTY, 
	TARGETPRICE 
	

/*
SELECT * 
FROM ( 
	SELECT 
		T.COMPANYID, 
		(T.SCHEDULEYEAR) AS SCHEDULEYEAR, 
		--MAX(T.PSID) AS PSID,
		--MAX(T.PLANTINGSCHEDULELINE) AS PSLINE,
		--MAX(T.PSITEMNUMBER) AS PSITEMNUMBER,
		--MAX(T.PSCOMMONNAME) AS PSCOMMONNAME,
		--MAX(T.PRINTEDCONTAINERCODE) AS PRINTEDCONTAINERCODE, 
		T.WAREHOUSEID, 
		MAX(T.WAREHOUSENAME) AS WAREHOUSENAME, 
		T.SORT1, T.SORT2, T.SORT3, 
		(T.UDC_B) AS UDC_B, 
		(T.TARGETPLANTINGDATE) AS TARGETPLANTINGDATE, 
		(T.PSPRINTEDCONTAINERCODE) AS PSPRINTEDCONTAINERCODE, 

		MAX(T.TARGETPLANTINGQTY) AS TARGETPLANTINGQTY, 
		SUM(T.ACTUALPLANTEDQTY) AS ACTUALPLANTEDQTY, 
		MAX(T.TARGETPLANTINGQTY*TARGETPRICE) AS TARGETPLANTINGVALUE, 
		SUM(T.ACTUALPLANTEDQTY*LISTPRICE) AS ACTUALPLANTEDVALUE 
	FROM ( 
		SELECT *, 
		UDC_B AS SORT1, CONVERT(CHAR,TARGETPLANTINGDATE,111) AS SORT2, PSPRINTEDCONTAINERCODE AS SORT3
		FROM VW_RPT_PLANTING_PROGRESS (NOLOCK) 
		WHERE RECORDTYPE = 'R' 
		) T 
		--WHERE RECORDTYPE = 'R' 
		GROUP BY 
			COMPANYID, 
			SCHEDULEYEAR, 
			WAREHOUSEID, --WAREHOUSENAME, 
			SORT1, SORT2, SORT3, 
			UDC_B, 
			TARGETPLANTINGDATE, 
			PSPRINTEDCONTAINERCODE 
) X 
--WHERE 1=1 
*/
