/*
--DISTRIBUTIONBYACCOUNT

SELECT
*
FROM VW_RPT_DISTRIBUTIONBYACCOUNT (NOLOCK)
WHERE RECORDTYPE = 'Z'
----------------------
AND ACCOUNT = '308' AND ISGLACCRUALYN = 'Y'
AND ACCOUNT = '440' AND DEPARTMENT = '10' AND CAST (COMMITDATE AS DATE) = '4/25/2024'
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_DISTRIBUTIONBYACCOUNT]
AS
SELECT 
IIF(ISNULL(ACACCOUNTING.GLACCRUALAMOUNT,0) <> 0, 'Y', 'N') AS ISGLACCRUALYN,
ACACCOUNTING.R_BATCH,
ACACCOUNTING.SOURCETABLENAME,
ACACCOUNTING.R_SOURCEID,
ACACCOUNTING.KEYSEQUENCE,
ACACCOUNTING.COMPANYID,
ACACCOUNTING.MODULE,
ACACCOUNTING.RECORDTYPE,
ACACCOUNTING.SOURCE,
ACACCOUNTING.TRANSACTIONDATE,
ACACCOUNTING.FISCALYEAR,
ACACCOUNTING.FISCALPERIOD,
ACACCOUNTING.COMMITDATE,
ACBATCH.KEYSEQUENCE AS P_BATCH,
ACACCOUNTING.GLCASHAMOUNT,
ACACCOUNTING.GLCASHQUANTITY,
ACACCOUNTING.GLACCRUALAMOUNT,
ACACCOUNTING.GLACCRUALQUANTITY,
ACACCOUNTING.TRANSACTIONTYPE,
ACACCOUNTING.TRANSACTIONNUMBER,
ACACCOUNTING.DESCRIPTION,
ID.IDENTITYID,
ID.NAME,
ID.IDGROUP,
ACACCOUNT.ACCOUNT,
ACACCOUNT.DESCRIPTION AS ACACCOUNTDESC,
ACDEPARTMENT.DEPARTMENT,
ACDEPARTMENT.DESCRIPTION AS ACDEPARTMENTDESC,
FAFUND.FUND,
FAFUND.DESCRIPTION AS FAFUNDDESC,
CAJOB.JOB,
CAJOB.DESCRIPTION AS CAJOBDESC,
CAACTIVITY.ACTIVITY,
CAACTIVITY.DESCRIPTION AS CAACTIVITYDESC
FROM ACACCOUNTING (NOLOCK)
   LEFT JOIN ACACCOUNT (NOLOCK) ON ACACCOUNTING.R_GLACCOUNT = ACACCOUNT.ROWID
   LEFT JOIN ACDEPARTMENT (NOLOCK) ON ACACCOUNTING.R_GLDEPARTMENT = ACDEPARTMENT.ROWID
   LEFT JOIN FAFUND (NOLOCK) ON ACACCOUNTING.R_GLFUND = FAFUND.ROWID
   LEFT JOIN CAJOB (NOLOCK) ON ACACCOUNTING.R_CAJOB = CAJOB.ROWID 
   LEFT JOIN CAACTIVITY (NOLOCK) ON ACACCOUNTING.R_CAACTIVITY = CAACTIVITY.ROWID
   LEFT JOIN IDMASTER ID (NOLOCK) ON ACACCOUNTING.R_IDENTITY = ID.ROWID 
   LEFT JOIN ACCURRENCY (NOLOCK) ON ACACCOUNT.R_FXCURRENCY = ACCURRENCY.ROWID
   LEFT JOIN ABCOMPANY (NOLOCK) ON ABCOMPANY.COMPANYID = ACACCOUNTING.COMPANYID
   LEFT JOIN ACBATCH (NOLOCK) ON ACACCOUNTING.R_BATCH = ACBATCH.ROWID
WHERE 
 (ISNULL(ACACCOUNTING.GLCASHAMOUNT,0) <> 0 OR ISNULL(ACACCOUNTING.GLACCRUALAMOUNT,0) <> 0)
 AND ACACCOUNTING.COMPANYID = 'SB'
 AND ACACCOUNTING.MODULE = 'AC'
 AND ACACCOUNTING.RECORDTYPE = 'Z'
