/*
--1 ACKNOWLEDGEMENT (MULTIPLE VERSIONS)
SELECT
VW_RPT_ACKNOWLEDGEMENT.*
FROM VW_RPT_ACKNOWLEDGEMENT (NOLOCK)
--Needed by Insight to run report from the OMScreens:
JOIN OMTRANSACTIONHEADER (NOLOCK) ON OMTRANSACTIONHEADER.ROWID = VW_RPT_ACKNOWLEDGEMENT.OHROWID
WHERE VW_RPT_ACKNOWLEDGEMENT.RECORDTYPE <> 'P'
and VW_RPT_ACKNOWLEDGEMENT.transactionnumber = '40-14382-1'
--'10-13718'--
--'40-14382-1'--'10-12876'--'20-15007'--'20-13691'--'20-14235'--'40-13479'

ACKNOWLEDGEMENT VERSIONS:
SELECT C.CODE,C.DESCRIPTION_1,C.DESCRIPTION_2,COMMENT FROM IDCODES C WHERE C.CODETYPE='3C' ORDER BY CAST(C.CODE AS INT)
#	Description							Sort			Steve's Msg
-------------------------------------------------------------------------------------------------------------------------
1	NoList All Prices					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS.
2	List All Prices						PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
3	NoList All Prices					SORT/SZ/Q		DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
4	List All Prices						SORT/SZ/Q		DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
5	NoList Landed Only					PGP/SORT/SZ/Q	DO NOT EDIT DESC1 OR DESC2. SPECIFIC TEXT IS USED IN THE REPORTS. 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_ACKNOWLEDGEMENT]
AS
SELECT *,
REQUESTDATETYPE + ' ' + CONVERT(VARCHAR(10),REQUESTDATE,101) AS REQUESTEDTEXT
FROM VW_RPT_OM_VERSION_MASTER (NOLOCK) 
WHERE RECORDTYPE <> 'P'--ISORDER = 'Y'
AND (ISNULL(QUANTITYATSTAGE,0) <> 0 OR ISNULL(QUANTITYBACKORDER,0) <> 0 /*OR ISNULL(QUANTITYCANCELLED,0) <> 0*/) --SUPPRESS ZERO LINES UNLESS THERE'S A BACKORDER QTY -PER TEAM

