/*
--VW_RPT_NEGATIVE_LOT_BO_RECEIVING		--(ITEMS WITH NEGATIVE INVENTORY IN_REC IN_BO OUT_BO)
	--DESCRIPTION:
	--LIST ALL NON-ZERO VALUES (OF IN_RECEVING, BO_RECEIVING[IN_BO] & OUT_BO) 
	--FOR ITEMS HAVING LOT-LOCATIONS WITH NEGATIVE VALUES 
	--FOR ANY OF THESE 3 INVENTORY BUCKETS:

SELECT * 
FROM VW_RPT_NEGATIVE_LOT_BO_RECEIVING (NOLOCK) 
WHERE 1=1 
ORDER BY ITEMCODE, WHID, LOTCODE, LOCATIONCODE 

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_NEGATIVE_LOT_BO_RECEIVING]
AS
SELECT * 
FROM (	SELECT ITM.COMPANYID, 
			WH.IDENTITYID AS WHID, ITM.ITEMCODE, ITM.DESCRIPTION_1 AS SHORTCOMMONNAME,
			LOT.LOTCODE, LOC.LOCATIONCODE, 
			LQS.IN_RECEIVING, LQS.IN_BACKORDER AS BO_RECEIVING, LQS.OUT_BACKORDER
		FROM IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = LQS.R_ITEM 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
		JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = LQS.R_LOT 
		left JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = LQS.R_LOCATION
		--INCLUDE ANY NON-ZERO RECORDS:
		WHERE (LQS.IN_RECEIVING <> 0 OR LQS.IN_BACKORDER <> 0 OR LQS.OUT_BACKORDER <> 0) 
	) X
WHERE X.ITEMCODE IN
		(	SELECT ITM.ITEMCODE
			FROM IMLOCATIONQUANTITYSUMMARY NEGLQS (NOLOCK) 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = NEGLQS.R_ITEM 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
			JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = NEGLQS.R_LOT 
			left JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = NEGLQS.R_LOCATION
			--INCLUDE ANY NEGATIVE RECORDS:
			WHERE (NEGLQS.IN_RECEIVING < 0 OR NEGLQS.IN_BACKORDER < 0 OR NEGLQS.OUT_BACKORDER < 0) 
		)
--ORDER BY X.ITEMCODE, X.WHID, X.LOTCODE, X.LOCATIONCODE

/*
---------------------------------------------------
--LIST NEGATIVE VALUES FOUND IN ITEM-LOT-LOCATIONS:
SELECT 
	WH.IDENTITYID AS WHID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE, 
	NEGLQS.IN_RECEIVING, NEGLQS.IN_BACKORDER AS BO_RECEIVING, NEGLQS.OUT_BACKORDER
FROM IMLOCATIONQUANTITYSUMMARY NEGLQS (NOLOCK) 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = NEGLQS.R_ITEM 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = NEGLQS.R_LOT 
left JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = NEGLQS.R_LOCATION
--INCLUDE ANY NEGATIVE RECORDS:
WHERE (NEGLQS.IN_RECEIVING < 0 OR NEGLQS.IN_BACKORDER < 0 OR NEGLQS.OUT_BACKORDER < 0) 
ORDER BY WH.IDENTITYID, ITM.ITEMCODE, LOT.LOTCODE, LOC.LOCATIONCODE
*/

