/* 
--WRITEOFF EXCEL 
SELECT * 
FROM VW_RPT_WRITEOFF (NOLOCK) 
WHERE PROFILECODE = 'WriteOff' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_WRITEOFF] 
AS 
SELECT 
CO.COMPANYID, 
CO.NAME AS COMPANYNAME, 
ADP.PROFILECODE, 
CUST.IDENTITYID AS CUSTOMERID, 
CUST.NAME AS CUSTOMERNAME, 
AH.DATERECEIVED, 
ACCT.ACCOUNT, 
DEPT.DEPARTMENT, 
APMT.AMOUNT 
FROM ARCASHRECEIPTSPAYMENTS APMT (NOLOCK) 
JOIN ARCASHRECEIPTSHEADER AH (NOLOCK) ON AH.ROWID = APMT.R_ARCASHRECEIPTSHEADER 
LEFT JOIN ACACCOUNT ACCT (NOLOCK) ON ACCT.ROWID = APMT.R_GLACCOUNT 
LEFT JOIN ACDEPARTMENT DEPT (NOLOCK) ON DEPT.ROWID = APMT.R_GLDEPARTMENT 
JOIN ARCASHRECEIPTSDP ADP (NOLOCK) ON ADP.ROWID = AH.R_PROFILE 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = AH.R_CUSTOMER 
JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = AH.COMPANYID 
WHERE ADP.PROFILECODE = 'WriteOff' 
--AND CUST.IDENTITYID = '825813' 

--ORDER BY 
--	CUST.IDENTITYID, 
--	ACCT.ACCOUNT, 
--	DEPT.DEPARTMENT 
