/*
--38+ CONSIGNEE LISTING BY KEYREP EXCEL
SELECT *
FROM VW_RPT_CONSIGNEE_LISTING_KEYREP (NOLOCK) 
WHERE 1=1 
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_CONSIGNEE_LISTING_KEYREP]
AS
SELECT 
	--KEYREP FIELDS--
	ISNULL(KREP.IDENTITYID,'') AS KEYREP,
	ISNULL(KREP.NAME,'') AS KEYREPNAME,
	VW.*
FROM VW_RPT_CONSIGNEE_LISTING VW (NOLOCK)
	--MULTIPLE KEYREPS WILL BE ASSIGNED, SO THIS WILL CREATE DUPLICATE CUSTOMER RECORDS.
	LEFT JOIN IDRELATIONSHIPLINKS LKREP (NOLOCK) ON LKREP.R_IDMASTER = CUSTROWID AND LKREP.IDMEMBERTYPE = '14'
	LEFT JOIN IDMASTER KREP (NOLOCK) ON KREP.ROWID = LKREP.R_IDMEMBER 

