------------------------------------------------------------------------------------------------------------------------------------------- 
--I HAD TO UNBREAK NATIONALACCOUNT FIELD TO EQUAL 'N' WHEN NULL FOR THIS REPORT ONLC. I DON'T LIKE THIS LOGIC BUT RIGHT NOW IS NECESSARC.-- 
------------------------------------------------------------------------------------------------------------------------------------------- 
/* RUNTIME: 0:52 
--BILLING_REP_TRENDS 
SELECT * 
FROM VW_RPT_BILLING_REP_TRENDS (NOLOCK) 
WHERE COMPANYID = 'SB' 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_BILLING_REP_TRENDS] 
AS 
SELECT U.* 
FROM	(

		---------------------------------- 
		-- THIS IS THE DIVISIONAL DATASET -- 
		---------------------------------- 
		SELECT 
		IIF(D.NATIONALACCOUNT = 'Y', '(Major Accts)', '(Independents)') AS ACCTTYPE, 
		'Y' AS ISDIVISIONAL, 
		NULL AS ISCONSOLIDATED, 
		D.ISCURRYEAR, 
		D.RECORDTYPE, 
		D.COMPANYID, 
		D.SALEYEAR, 
		D.PERIOD, 
		D.TRANSACTIONDATE, 
		D.REPORTGROUP, 
		D.WAREHOUSEID AS WAREHOUSEID, 
		--UNIFYING WAREHOUSENAME USING INSIGHT DATA: 
		(	SELECT WH.NAME 
			FROM IDMASTER WH (NOLOCK) 
			WHERE WH.IDENTITYID = D.WAREHOUSEID 
			) AS WAREHOUSENAME, 
		ISNULL(D.NATIONALACCOUNT,'N') AS NATIONALACCOUNT, 
		D.SALESREPID, 
		D.SALESREPNAME, 
		D.CURRAMOUNT, 
		D.PREVAMOUNT, 
		D.GOALAMOUNT 
		FROM VW_RPT_SQL_BILLING_REP_TRENDS D (NOLOCK) 
		WHERE D.TRANSACTIONDATE <= GETDATE() 

		UNION ALL

		--------------------------------
		-- THIS IS THE CONSOLIDATED DATASET --
		--------------------------------
		SELECT 
		IIF(C.NATIONALACCOUNT = 'Y', '(Major Accts)', '(Independents)') AS ACCTTYPE,
		NULL AS ISDIVISIONAL,
		'Y' AS ISCONSOLIDATED,
		C.ISCURRYEAR,
		C.RECORDTYPE,
		C.COMPANYID,
		C.SALEYEAR,
		C.PERIOD,
		C.TRANSACTIONDATE,
		C.REPORTGROUP,
		NULL AS WAREHOUSEID,	--CONSOLDIATED TOTALS:
		'Consolidated' AS WAREHOUSENAME,
		ISNULL(C.NATIONALACCOUNT,'N') AS NATIONALACCOUNT,
		C.SALESREPID,
		C.SALESREPNAME,
		C.CURRAMOUNT,
		C.PREVAMOUNT,
		C.GOALAMOUNT
		FROM VW_RPT_SQL_BILLING_REP_TRENDS C (NOLOCK) 
		WHERE C.TRANSACTIONDATE <= GETDATE()
		) U
