/*
--INVOICE DETAILS BY DATE EXCEL 
	(WAS QUERY: CUMALATIVEPURCHASESUMMARY; RAN FOR DAVE HUTSELL BY REQUEST)
SELECT * 
FROM VW_RPT_INVDETAILBYDATE (NOLOCK) 
WHERE RECORDTYPE = 'Z' 

*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_INVDETAILBYDATE]
AS
SELECT
COMPANYID,
COMPANYNAME,
RECORDTYPE,
WAREHOUSEID,
CUSTOMERNAME,
CUSTOMERIDENTITYID,
IDGROUP,
TRIM(SALESREPID) AS SALESREPID,
SALESREPNAME,
INVOICEDATE,
DBO.FN_DATE2PERIOD(INVOICEDATE) AS REPORTPERIOD,
DBO.FN_DATE2YEAR(INVOICEDATE) AS REPORTYEAR,
TRANSACTIONNUMBER,
TRIM(ITEMCODE) AS ITEMCODE,
COMMONNAME,
PLANTGROUPCODE,
SORTNAMEVARIETY,
QUANTITYSHIPPED,
UNITPRICE+TAGGINGCHARGEPERITEM+HANDLINGCHARGEPERITEM AS ITEMPRICE,
QUANTITYSHIPPED*(UNITPRICE+TAGGINGCHARGEPERITEM+HANDLINGCHARGEPERITEM) AS EXTTOTAL,
FREIGHTRATEPERITEM,
QUANTITYSHIPPED*FREIGHTRATEPERITEM AS EXTFREIGHT,
LISTPRICE

FROM VW_RPT_OM_VERSION_MASTER (NOLOCK)
WHERE RECORDTYPE = 'Z'
----------------------------
--AND WAREHOUSEID = '40'
--AND INVOICEDATE BETWEEN '2021/06/01' AND GETDATE()