/*
--55 CHECKER COPY-->CHECKER CANCELS
SELECT * 
FROM VW_RPT_CHECKER_CANCELS (NOLOCK) 
WHERE COMPANYID = 'SB'
--NO, THIS TAKES OUT TOO MUCH DATA--WHERE OUT_SHIPPED > 0 

and tripno = 'T08037'
--and itemcode = '001733.030.1'
AND (OHREVIEWSTAGE = 'Add-on' OR ODREVIEWSTAGE = 'Add-on')
--AND TRANSACTIONNUMBER = '40-13109'--'10-12431'--'40-11470-1'
--and itemcode = '005248.031.1'
--ORDER BY ITEMCODE
*/
CREATE OR ALTER VIEW [DBO].[VW_RPT_CHECKER_CANCELS]
AS
SELECT 	U.* 
FROM	(
		--THIS IS A PARTIAL COPY OF CHECKER_COPY THAT ONLY INCLUDES THE BACKORDER & CANCEL SECTIONS TO REDUCE RUNTIME--

		----------------------------------
		-- SECTION 2 - ONLY BACKORDERS  --
		--	WHERE NULLIF(ISNULL(QUANTITYBACKORDER,0),0) IS NOT NULL
		----------------------------------
		SELECT
		--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES:
		OH.ROWID AS OMTRANSACTIONHEADERROWID,
		OD.ROWID AS OMTRANSACTIONDETAILROWID,
		NULL AS ISSUBREPORT1,	--BREAKFIELD #3
		OH.RECORDTYPE AS RECORDTYPE,
		OH.STAGE AS STAGE,
		OH.STATUS AS STATUS,
		CO.COMPANYID,
		CO.NAME AS COMPANYNAME,
		WH.IDENTITYID AS WAREHOUSEID,
		WH.NAME AS WAREHOUSENAME,
		IIF(WH.IDENTITYID='40','Y',NULL) AS ISSUPPRESSLOGIC,
		CONVERT(DATE,HDR.PLANSTART) AS TRIPDATE, 
		HDR.TRIPNO,
		DTL.DELSTOPNO AS STOPNO,
		ISNULL((SELECT TOP 1 DESCRIPTION_1 
				FROM FMCODES (NOLOCK) 
				WHERE CODETYPE = '52' 
				AND CODE = HDR.USERDEFINEDCODE_2), '') AS DOCK,	--ADDED PER TEAM - DT 3/18/22 
		ISNULL((SELECT TOP 1 DESCRIPTION_1 
				FROM FMCODES (NOLOCK) 
				WHERE CODETYPE = '53' 
				AND CODE = HDR.USERDEFINEDCODE_3), '') AS TRIPATTNLINE,	--ADDED PER TEAM - DT 6/23/22 
		OH.TRANSACTIONNUMBER,
		RIGHT(TRIM(OH.TRANSACTIONNUMBER),3) AS ORD,
		OH.COMMENT AS ORDERSHIPPINGINSTR,
		IDTERMS.TERMSCODE,
		IDTERMS.DESCRIPTION_1 AS TERMSDESCRIPTION,
		VCUST.CUSTOMERIDENTITYID,
		VCUST.CUSTOMERNAME, 
		VCUST.CUSTOMERADDRESSMEMO,
		VCUST.CUSTOMERADDRESS_1,
		VCUST.CUSTOMERCITY + ', ' + VCUST.CUSTOMERSTATE + '  ' + VCUST.CUSTOMERZIP AS CUSTOMERCITYSTATEZIP,
		IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
		VCONS.CONSIGNEEIDENTITYID,
		VCONS.CONSIGNEENAME,
		ISNULL(	--BUILD ALTSHIPADDRESSMEMO CANNIBALIZED FROM VW_IDCONSIGNEEVIEW:
				CONVERT(VARCHAR(250), --TRIM(ALTSHIP.NAME) + CHAR(13) + CHAR(10) + 
						(CASE	WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')=''	THEN '' 
								WHEN ISNULL(ALTSHIP.ADDRESS_2, '')='' AND ISNULL(ALTSHIP.ADDRESS_1, '')<>''	THEN ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) 
								WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')<>''	THEN ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
								ELSE ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) + ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
								END 
						) + RTRIM(ALTSHIP.CITY) + '    ' + RTRIM(ALTSHIP.STATE) + '   ' + ALTSHIP.ZIP ),
				CONVERT(VARCHAR(250), --TRIM(VCONS.CONSIGNEENAME) + CHAR(13) + CHAR(10) + 
						(CASE	WHEN ISNULL(VCONS.CONSIGNEEADDRESS_1, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_2, '')=''	THEN '' 
								WHEN ISNULL(VCONS.CONSIGNEEADDRESS_2, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_1, '')<>''	THEN VCONS.CONSIGNEEADDRESS_1 + CHAR(13) + CHAR(10) 
								WHEN ISNULL(VCONS.CONSIGNEEADDRESS_1, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_2, '')<>''	THEN VCONS.CONSIGNEEADDRESS_2 + CHAR(13) + CHAR(10) 
								ELSE VCONS.CONSIGNEEADDRESS_1 + CHAR(13) + CHAR(10) + VCONS.CONSIGNEEADDRESS_2 + CHAR(13) + CHAR(10) 
								END 
						) + RTRIM(VCONS.CONSIGNEECITY) + '    ' + RTRIM(VCONS.CONSIGNEESTATE) + '   ' + VCONS.CONSIGNEEZIP )
			) AS CONSIGNEEADDRESSMEMO, 
		ISNULL(ALTSHIP.ADDRESS_1, VCONS.CONSIGNEEADDRESS_1) AS CONSIGNEEADDRESS_1,
		ISNULL(ALTSHIP.ADDRESS_2, VCONS.CONSIGNEEADDRESS_2) AS CONSIGNEEADDRESS_2,
		ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY) AS CONSIGNEECITY, 
		ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) AS CONSIGNEESTATE, 
		ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP) AS CONSIGNEEZIP, 
		ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY) + ', ' + ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) + '  ' + ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP) AS CONSIGNEECITYSTATEZIP, 
		ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPPHONE 
				NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
			) AS CONSIGNEETELEPHONE_1,
		OH.USERDEFINEDREFERENCE_3 AS ORDEREDBY,
		PART.IDENTITYID AS SALESREP,
		PART.NAME AS SALESREPNAME,
		ICONS.USERDEFINEDCODE_10 AS TAGCODE,
		TAG.DESCRIPTION_1 AS TAGCODEDESC,
		ICONS.USERDEFINEDCODE_11 AS QUALITYASSURANCECODE,
		PC.PRODUCTCATEGORYCODE AS PLANTGROUP,
		ITM.REFERENCE_5 AS SORTNAMEVARIETY,
		CNT.CONTAINERSORT,
		IL.OUT_SHIPPED,
		OD.QUANTITYORDERED,
		OD.QUANTITYSHIPPED,
		OD.QUANTITYBACKORDER,
		ISNULL(OD.QUANTITYORDERED,0)-ISNULL(OD.QUANTITYSHIPPED,0)-ISNULL(OD.QUANTITYBACKORDER,0) AS QUANTITYCANCELLED,
		'B' AS REVIEWBACKORDERFLAG,	--BREAKFIELD #1
		ITM.ITEMCODE AS BOCBREAK,	--BREAKFIELD #2
		'BACKORDERS' AS BOCTEXT,	
		ISNULL(OD.QUANTITYBACKORDER,0) AS QUANTITYATFLAG,
		OD.REVIEWBACKORDERREASON,
		OD.CONFIRMBACKORDERFLAG,
		OD.CONFIRMBACKORDERREASON,
		IIF(DATALENGTH(OD.USERDEFINEDCOMMENT) > 1,OD.USERDEFINEDCOMMENT,NULL) AS TAGDEPTNOTE,	--ADDED PER TEAM - T 3/18/22 

		CNT.PRINTEDCONTAINERCODE,
		ITM.ITEMCODE, 
		ITM.REFERENCE_1 AS COMMONNAME,
		ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
		ITM.SPECIFICATIONCODE,
		ISNULL(NULLIF(ITM.USERDEFINEDCODE_12,'NONE'),ITM.USERDEFINEDCODE_2) AS BRANDPOTOVERRIDE,
		ITM.USERDEFINEDCODE_2 AS BRAND,
		ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
		ITM.USERDEFINEDCODE_13 AS BRANDTAGREQ,
		--DBO.FN_SALESNOTE(ITM.ROWID,LOT.ROWID,NULL) AS FNSALESNOTE,	--NOT USED IN REPORT 
		ITM.USERDEFINEDREFERENCE_7 AS SALESNOTE,
		LOT.USERDEFINEDREFERENCE_4 AS HOLDREASON,
		LOT.USERDEFINEDDATE_4 AS HOLDREASONBEGINDATE,
		ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
		IIF(ITM.SUBCLASSCODE=2,'PROMO',NULL) AS PROMO,
		ITM.REFERENCE_3 AS REVERSECOMMONNAME,
		DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SOURCE') AS SOURCE,
		--CONCATENATE DESIGNATORS TO FIT ON PORTRAIT VERSION:
		NULLIF(
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigItem'),'')+'.'+
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigCust'),'')+'.'+
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigLoc'),''),
			'..') AS DesigICL,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote1'), LOT.USERDEFINEDREFERENCE_1) AS PULLTAGNOTE1,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote2'), LOT.USERDEFINEDREFERENCE_2) AS PULLTAGNOTE2,
		--NEW LOGIC BY ELLEN: PRINT LOCATIONPTNOTE IF AVAILABLE OTHERWISE PRINT PULLTAGNOTE:
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'LocationPTN1'), ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote1'), LOT.USERDEFINEDREFERENCE_1)) AS PULLTAGNOTE1,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'LocationPTN2'), ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote2'), LOT.USERDEFINEDREFERENCE_2)) AS PULLTAGNOTE2,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PickNote'), ISNULL(OD.COMMENT, '')) AS PICKNOTE,
		--IIF(ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Suspend'), LOT.USERDEFINEDCODE_5)='SUSPEND','Y',NULL) AS ISPULLTAGSUSPEND,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SuspendTo'), LOT.USERDEFINEDREFERENCE_3) AS PULLTAGSUSPENDTO,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Special Puller'), LOT.USERDEFINEDCODE_4) AS SPECIALPULLER,
		IIF(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Suspend') = 'SUSPEND','Y',NULL) AS ISPULLTAGSUSPEND,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SuspendTo'), '') AS PULLTAGSUSPENDTO,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Special Puller'), '') AS SPECIALPULLER,
		'NEEDED' AS PULLTAGMAINT,
		LOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
		LOT.LOTCODE,
		LOC.LOCATIONCODE,
		--PLAGIARIZING CODE FROM VW_PULLTAGREPORT
		(SELECT TOP 1 PULLTAGNO FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_IMTRANSACTIONLOCATION = IL.ROWID AND IA.R_TRANSACTIONDETAIL = OD.ROWID) AS TAGNO,
		--TAGBIN	--NEED SOURCE IN ORDER TO ADD FIELD.
		--PLAGIARIZING CODE FROM ARGOS' VW_TAGREPORTREPRINTVIEW:
		(SELECT TOP 1 TLOC.LOCATIONCODE FROM IMITEM TITM (NOLOCK) 
		LEFT JOIN IDMASTER TWH (NOLOCK) ON TWH.ROWID = TITM.R_WAREHOUSE 
		LEFT JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_ITEM=TITM.ROWID
		LEFT JOIN IMLOCATION TLOC (NOLOCK) ON TLOC.ROWID= TL.R_LOCATION
		WHERE TWH.IDENTITYID ='TAG_'+WH.IDENTITYID AND TITM.ITEMCODE=ITM.ITEMCODE ) AS BINNUMBER,
		ITM.USERDEFINEDCODE_11 AS GRADECOLOR,
		ISNULL(ITM.UNITVOLUMEQUANTITY,0) AS UNITVOLUMEQUANTITY,
		ISNULL(ITM.NETWEIGHTQUANTITY,0) AS NETWEIGHTQUANTITY,
		-----------------------------------------------------------------------------------------------------------
		OH.REVIEWSTAGE AS OHREVIEWSTAGE,
		OD.REVIEWSTAGE AS ODREVIEWSTAGE,
		IIF(OD.REVIEWSTAGE = 'ADD-ON','Add-on',NULL) AS ISADDONDETAIL,
		OH.SETNO
		FROM FMTRIPHEADER HDR (NOLOCK)
		JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
		JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT
		LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID
		LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
		LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
		LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = IL.R_LOCATION
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
		LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
		LEFT JOIN IDTERMS (NOLOCK) ON IDTERMS.ROWID = OH.R_TERMS
		LEFT JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER
		LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER 
		LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
		LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.ConsigneeMasterRowID
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
		LEFT JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY
		LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT
		LEFT JOIN IDCODES TAG (NOLOCK) ON TAG.CODETYPE = '81' AND TAG.CODE = ICONS.USERDEFINEDCODE_10
		--ONLY INCLUDE BACKORDERED ITEMS:
		WHERE NULLIF(ISNULL(QUANTITYBACKORDER,0),0) IS NOT NULL


		UNION ALL

		----------------------------------
		-- SECTION 3 - ONLY CANCELS     --
		--	WHERE ISNULL(OD.QUANTITYORDERED,0)-ISNULL(OD.QUANTITYSHIPPED,0)-ISNULL(OD.QUANTITYBACKORDER,0)>0
		----------------------------------
		SELECT
		--ADDED PER SAAD FOR INTEGRATION WITH INSIGHT PROCESSES:
		OH.ROWID AS OMTRANSACTIONHEADERROWID,
		OD.ROWID AS OMTRANSACTIONDETAILROWID,
		NULL AS ISSUBREPORT1,	--BREAKFIELD #2
		OH.RECORDTYPE AS RECORDTYPE,
		OH.STAGE AS STAGE,
		OH.STATUS AS STATUS,
		CO.COMPANYID,
		CO.NAME AS COMPANYNAME,
		WH.IDENTITYID AS WAREHOUSEID,
		WH.NAME AS WAREHOUSENAME,
		IIF(WH.IDENTITYID='40','Y',NULL) AS ISSUPPRESSLOGIC,
		CONVERT(DATE,HDR.PLANSTART) AS TRIPDATE, 
		HDR.TRIPNO,
		DTL.DELSTOPNO AS STOPNO,
		ISNULL((SELECT TOP 1 DESCRIPTION_1 
				FROM FMCODES (NOLOCK) 
				WHERE CODETYPE = '52' 
				AND CODE = HDR.USERDEFINEDCODE_2), '') AS DOCK,	--ADDED PER TEAM - T 3/18/22 
		ISNULL((SELECT TOP 1 DESCRIPTION_1 
				FROM FMCODES (NOLOCK) 
				WHERE CODETYPE = '53' 
				AND CODE = HDR.USERDEFINEDCODE_3), '') AS TRIPATTNLINE,	--ADDED PER TEAM - DT 6/23/22 
		OH.TRANSACTIONNUMBER,
		RIGHT(TRIM(OH.TRANSACTIONNUMBER),3) AS ORD,
		OH.COMMENT AS ORDERSHIPPINGINSTR,
		IDTERMS.TERMSCODE,
		IDTERMS.DESCRIPTION_1 AS TERMSDESCRIPTION,
		VCUST.CUSTOMERIDENTITYID,
		VCUST.CUSTOMERNAME, 
		VCUST.CUSTOMERADDRESSMEMO,
		VCUST.CUSTOMERADDRESS_1,
		VCUST.CUSTOMERCITY + ', ' + VCUST.CUSTOMERSTATE + '  ' + VCUST.CUSTOMERZIP AS CUSTOMERCITYSTATEZIP,
		IIF(OH.R_SYNONYMSALTSHIPTO IS NULL, 'N', 'Y') AS ALTSHIPFLAG, 
		VCONS.CONSIGNEEIDENTITYID,
		VCONS.CONSIGNEENAME,
		ISNULL(	--BUILD ALTSHIPADDRESSMEMO CANNIBALIZED FROM VW_IDCONSIGNEEVIEW:
				CONVERT(VARCHAR(250), TRIM(ALTSHIP.NAME) + CHAR(13) + CHAR(10) + 
						(CASE	WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')=''	THEN '' 
								WHEN ISNULL(ALTSHIP.ADDRESS_2, '')='' AND ISNULL(ALTSHIP.ADDRESS_1, '')<>''	THEN ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) 
								WHEN ISNULL(ALTSHIP.ADDRESS_1, '')='' AND ISNULL(ALTSHIP.ADDRESS_2, '')<>''	THEN ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
								ELSE ALTSHIP.ADDRESS_1 + CHAR(13) + CHAR(10) + ALTSHIP.ADDRESS_2 + CHAR(13) + CHAR(10) 
								END 
						) + RTRIM(ALTSHIP.CITY) + '    ' + RTRIM(ALTSHIP.STATE) + '   ' + ALTSHIP.ZIP ),
				CONVERT(VARCHAR(250), --TRIM(VCONS.CONSIGNEENAME) + CHAR(13) + CHAR(10) + 
						(CASE	WHEN ISNULL(VCONS.CONSIGNEEADDRESS_1, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_2, '')=''	THEN '' 
								WHEN ISNULL(VCONS.CONSIGNEEADDRESS_2, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_1, '')<>''	THEN VCONS.CONSIGNEEADDRESS_1 + CHAR(13) + CHAR(10) 
								WHEN ISNULL(VCONS.CONSIGNEEADDRESS_1, '')='' AND ISNULL(VCONS.CONSIGNEEADDRESS_2, '')<>''	THEN VCONS.CONSIGNEEADDRESS_2 + CHAR(13) + CHAR(10) 
								ELSE VCONS.CONSIGNEEADDRESS_1 + CHAR(13) + CHAR(10) + VCONS.CONSIGNEEADDRESS_2 + CHAR(13) + CHAR(10) 
								END 
						) + RTRIM(VCONS.CONSIGNEECITY) + '    ' + RTRIM(VCONS.CONSIGNEESTATE) + '   ' + VCONS.CONSIGNEEZIP )
			) AS CONSIGNEEADDRESSMEMO, 
		ISNULL(ALTSHIP.ADDRESS_1, VCONS.CONSIGNEEADDRESS_1) AS CONSIGNEEADDRESS_1,
		ISNULL(ALTSHIP.ADDRESS_2, VCONS.CONSIGNEEADDRESS_2) AS CONSIGNEEADDRESS_2,
		ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY) AS CONSIGNEECITY, 
		ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) AS CONSIGNEESTATE, 
		ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP) AS CONSIGNEEZIP, 
		ISNULL(ALTSHIP.CITY, VCONS.CONSIGNEECITY) + ', ' + ISNULL(ALTSHIP.STATE, VCONS.CONSIGNEESTATE) + '  ' + ISNULL(ALTSHIP.ZIP, VCONS.CONSIGNEEZIP) AS CONSIGNEECITYSTATEZIP, 
		ISNULL(	TRIM(REPLACE(SUBSTRING(ALTSHIP.COMMENT,1,200),CHAR(13)+CHAR(10), '') ),	--ALTSHIPPHONE 
				NULLIF(LEFT(ACONT.TELEPHONE_1,8)+'-'+RIGHT(ACONT.TELEPHONE_1,4),'-')	--SHIPTOTELEPHONE FOR THE MAIN CONSIGNEE 
			) AS CONSIGNEETELEPHONE_1,
		OH.USERDEFINEDREFERENCE_3 AS ORDEREDBY,
		PART.IDENTITYID AS SALESREP,
		PART.NAME AS SALESREPNAME,
		ICONS.USERDEFINEDCODE_10 AS TAGCODE,
		TAG.DESCRIPTION_1 AS TAGCODEDESC,
		ICONS.USERDEFINEDCODE_11 AS QUALITYASSURANCECODE,
		PC.PRODUCTCATEGORYCODE AS PLANTGROUP,
		ITM.REFERENCE_5 AS SORTNAMEVARIETY,
		CNT.CONTAINERSORT,
		IL.OUT_SHIPPED,
		OD.QUANTITYORDERED,
		OD.QUANTITYSHIPPED,
		OD.QUANTITYBACKORDER,
		ISNULL(OD.QUANTITYORDERED,0)-ISNULL(OD.QUANTITYSHIPPED,0)-ISNULL(OD.QUANTITYBACKORDER,0) AS QUANTITYCANCELLED,
		'C' AS REVIEWBACKORDERFLAG,	--BREAKFIELD #1
		ITM.ITEMCODE AS BOCBREAK,	--BREAKFIELD #2
		'CANCELS   ' AS BOCTEXT,	
		ISNULL(OD.QUANTITYORDERED,0)-ISNULL(OD.QUANTITYSHIPPED,0)-ISNULL(OD.QUANTITYBACKORDER,0) AS QUANTITYATFLAG,
		OD.REVIEWBACKORDERREASON,
		OD.CONFIRMBACKORDERFLAG,
		OD.CONFIRMBACKORDERREASON,
		IIF(DATALENGTH(OD.USERDEFINEDCOMMENT) > 1,OD.USERDEFINEDCOMMENT,NULL) AS TAGDEPTNOTE,	--ADDED PER TEAM - T 3/18/22 

		CNT.PRINTEDCONTAINERCODE,
		ITM.ITEMCODE, 
		ITM.REFERENCE_1 AS COMMONNAME,
		ITM.USERDEFINEDREFERENCE_1 AS PATENTNUMBER,
		ITM.SPECIFICATIONCODE,
		ISNULL(NULLIF(ITM.USERDEFINEDCODE_12,'NONE'),ITM.USERDEFINEDCODE_2) AS BRANDPOTOVERRIDE,
		ITM.USERDEFINEDCODE_2 AS BRAND,
		ITM.USERDEFINEDCODE_12 AS BRANDPOTREQ,
		ITM.USERDEFINEDCODE_13 AS BRANDTAGREQ,
		--DBO.FN_SALESNOTE(ITM.ROWID,LOT.ROWID,NULL) AS FNSALESNOTE,	--NOT USED IN REPORT 
		ITM.USERDEFINEDREFERENCE_7 AS SALESNOTE,
		LOT.USERDEFINEDREFERENCE_4 AS HOLDREASON,
		LOT.USERDEFINEDDATE_4 AS HOLDREASONBEGINDATE,
		ITM.USERDEFINEDCODE_15 AS FIELDTAGCOLOR,
		IIF(ITM.SUBCLASSCODE=2,'PROMO',NULL) AS PROMO,
		ITM.REFERENCE_3 AS REVERSECOMMONNAME,
		DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SOURCE') AS SOURCE,
		--DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigItem') AS DesigItem,
		--DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigCust') AS DesigCust,
		--DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigLoc') AS DesigLoc,
		--CONCATENATE DESIGNATORS TO FIT ON PORTRAIT VERSION:
		NULLIF(
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigItem'),'')+'.'+
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigCust'),'')+'.'+
			ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'DesigLoc'),''),
			'..') AS DesigICL,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote1'), LOT.USERDEFINEDREFERENCE_1) AS PULLTAGNOTE1,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote2'), LOT.USERDEFINEDREFERENCE_2) AS PULLTAGNOTE2,
		--NEW LOGIC BY ELLEN: PRINT LOCATIONPTNOTE IF AVAILABLE OTHERWISE PRINT PULLTAGNOTE:
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'LocationPTN1'), ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote1'), LOT.USERDEFINEDREFERENCE_1)) AS PULLTAGNOTE1,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'LocationPTN2'), ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PullTagNote2'), LOT.USERDEFINEDREFERENCE_2)) AS PULLTAGNOTE2,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'PickNote'), ISNULL(OD.COMMENT, '')) AS PICKNOTE,
		--IIF(ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Suspend'), LOT.USERDEFINEDCODE_5)='SUSPEND','Y',NULL) AS ISPULLTAGSUSPEND,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SuspendTo'), LOT.USERDEFINEDREFERENCE_3) AS PULLTAGSUSPENDTO,
		--ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Special Puller'), LOT.USERDEFINEDCODE_4) AS SPECIALPULLER,
		IIF(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Suspend') = 'SUSPEND','Y',NULL) AS ISPULLTAGSUSPEND,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'SuspendTo'), '') AS PULLTAGSUSPENDTO,
		ISNULL(DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Special Puller'), '') AS SPECIALPULLER,
		--LOT.USERDEFINEDREFERENCE_1 AS PULLTAGNOTE1,
		--LOT.USERDEFINEDREFERENCE_2 AS PULLTAGNOTE2,
		--IIF(DATALENGTH(OD.COMMENT)<2,NULL,OD.COMMENT) AS PICKNOTE, --APPARENTLY PTR CAN OVERRIDE THE PICKNOTE WHICH IS THE PRIMARY COMMENT FIELD THIS NEEDS ADDRESSED.
		--DBO.FN_OMATTRIBUTES(OD.ROWID, IL.ROWID, 'Pick Note') AS PTRPICKNOTE, --DOESN'T SHOW UP
		--LOT.USERDEFINEDCODE_5 AS PULLTAGSUSPEND,
		--IIF(LOT.USERDEFINEDCODE_5='SUSPEND','Y',NULL) AS ISPULLTAGSUSPEND,
		--LOT.USERDEFINEDREFERENCE_3 AS PULLTAGSUSPENDTO,
		'NEEDED' AS PULLTAGMAINT,
		LOT.USERDEFINEDCODE_3 AS HOLDSTOPCODE,
		LOT.LOTCODE,
		LOC.LOCATIONCODE,
		--PLAGIARIZING CODE FROM VW_PULLTAGREPORT
		(SELECT TOP 1 PULLTAGNO FROM OMREVIEWINVENTORYASSIGNMENT IA (NOLOCK) WHERE IA.R_IMTRANSACTIONLOCATION = IL.ROWID AND IA.R_TRANSACTIONDETAIL = OD.ROWID) AS TAGNO,
		--TAGBIN	--NEED SOURCE IN ORDER TO ADD FIELD.
		--PLAGIARIZING CODE FROM ARGOS' VW_TAGREPORTREPRINTVIEW:
		(SELECT TOP 1 TLOC.LOCATIONCODE FROM IMITEM TITM (NOLOCK) 
		LEFT JOIN IDMASTER TWH (NOLOCK) ON TWH.ROWID = TITM.R_WAREHOUSE 
		LEFT JOIN IMTRANSACTIONLOCATION TL (NOLOCK) ON TL.R_ITEM=TITM.ROWID
		LEFT JOIN IMLOCATION TLOC (NOLOCK) ON TLOC.ROWID= TL.R_LOCATION
		WHERE TWH.IDENTITYID ='TAG_'+WH.IDENTITYID AND TITM.ITEMCODE=ITM.ITEMCODE ) AS BINNUMBER,
		ITM.USERDEFINEDCODE_11 AS GRADECOLOR,
		ISNULL(ITM.UNITVOLUMEQUANTITY,0) AS UNITVOLUMEQUANTITY,
		ISNULL(ITM.NETWEIGHTQUANTITY,0) AS NETWEIGHTQUANTITY,
		-----------------------------------------------------------------------------------------------------------
		OH.REVIEWSTAGE AS OHREVIEWSTAGE,
		OD.REVIEWSTAGE AS ODREVIEWSTAGE,
		IIF(OD.REVIEWSTAGE = 'ADD-ON','Add-on',NULL) AS ISADDONDETAIL,
		OH.SETNO
		FROM FMTRIPHEADER HDR (NOLOCK)
		JOIN FMTRIPDETAIL DTL (NOLOCK) ON DTL.R_TRIPHEADER = HDR.ROWID
		JOIN FMDISPATCHOBJECT OBJ (NOLOCK) ON OBJ.ROWID = DTL.R_FMDISPATCHOBJECT
		LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OBJ.R_SOURCEID
		LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
		LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
		LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = IL.R_LOCATION
		LEFT JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = OH.COMPANYID
		LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
		LEFT JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = OH.R_SALESPERSON_1
		LEFT JOIN IDTERMS (NOLOCK) ON IDTERMS.ROWID = OH.R_TERMS
		LEFT JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER
		LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER 
		LEFT JOIN IDSYNONYMS ALTSHIP (NOLOCK) ON ALTSHIP.ROWID = OH.R_SYNONYMSALTSHIPTO	-->NEW ALTSHIPTOADDRESS PROJECT 3/31/23 DT 
		LEFT JOIN IDADDRESS ACONT (NOLOCK) ON ACONT.R_IDENTITY = DBO.FN_GETCONTACT(VCONS.ConsigneeMasterRowID,'02','C5')
		LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = VCONS.ConsigneeMasterRowID
		LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
		LEFT JOIN IMPRODUCTCATEGORY PC (NOLOCK) ON PC.ROWID = ITM.R_PRODUCTCATEGORY
		LEFT JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		LEFT JOIN IMLOT LOT (NOLOCK) ON LOT.ROWID = OD.R_LOT
		LEFT JOIN IDCODES TAG (NOLOCK) ON TAG.CODETYPE = '81' AND TAG.CODE = ICONS.USERDEFINEDCODE_10
		--ONLY INCLUDE CANCELLED ITEMS:
		WHERE ISNULL(OD.QUANTITYORDERED,0)-ISNULL(OD.QUANTITYSHIPPED,0)-ISNULL(OD.QUANTITYBACKORDER,0)>0
-----------------------------------------------------------------------------------------------------------
		) U
WHERE RECORDTYPE <> 'P' 
--WHICH OR IF? OH IS THE CHOICE
--WHERE CHARINDEX(U.OHREVIEWSTAGE,'PICKEDADD-ONPICK CONFIRMEDPRINTED')>0

