/* RUNTIME: 1:31
--QUANTITY SHIPPED VARIANCE YTD
--QUANTITY SHIPPED VARIANCE SORT - for Harry
SELECT * 
FROM VW_RPT_QTY_SHIPPED_VARIANCE (NOLOCK) 
WHERE COMPANYID = 'SB' 
-------------------------- 
--AND REPORTYEAR = '2021'	-->RUNTIME=1:51	(RPT=3:01) [+1:10] 
--AND REPORTYEAR = '2022'	-->RUNTIME=1:26	(RPT=2:34) [+1:08] 
--AND WAREHOUSEID = '10' AND REPORTYEAR = '2021'	-->RUNTIME=0:45	(RPT=1:23) [+0:38] 
--AND WAREHOUSEID = '10' AND REPORTYEAR = '2022'	-->RUNTIME=0:43	(RPT=1:19) [+0:36] 
*/ 
CREATE OR ALTER VIEW [DBO].[VW_RPT_QTY_SHIPPED_VARIANCE] 
AS 
SELECT 
	COMPANYID, 
	COMPANYNAME, 
	RECORDTYPE, 
	REPORTYEAR, 
	WAREHOUSEID, 
	ITEMCODE, 
	COMMONNAME, 
	SIZE, 
	SORTNAME, 
	SUM(CURRSHIPPEDQTY) AS CURRSHIPPEDQTY, 
	SUM(CURREXTMERCH) AS CURREXTMERCH, 
	SUM(HIST1SHIPPEDQTY) AS HIST1SHIPPEDQTY, 
	SUM(HIST1EXTMERCH) AS HIST1EXTMERCH, 
	SUM(CURRSHIPPEDQTY - HIST1SHIPPEDQTY) AS DIFFSHIPPEDQTY, 
	SUM(CURREXTMERCH - HIST1EXTMERCH) AS DIFFEXTMERCH 
FROM ( 
	SELECT U.* --ADD THIS LEVEL SO I CAN FILTER TRANSACTIONDATE THRU TODAYS DATE 
	FROM ( 
		--INSIGHT DATASET: CURRENT 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			OH.RECORDTYPE, 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.CLASSCODE AS SIZE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ITM.REFERENCE_5 AS SORTNAME, 
			OH.INVOICEDATE AS TRANSACTIONDATE, 
			DBO.FN_DATE2YEAR(OH.INVOICEDATE) AS REPORTYEAR, 
			OD.QUANTITYSHIPPED AS CURRSHIPPEDQTY, 
			ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0)) AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH 
		FROM IMITEM ITM (NOLOCK) 
			LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = ITM.ROWID 
			LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		WHERE OH.RECORDTYPE = 'Z' --COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 

		UNION ALL 

		--INSIGHT DATASET: HIST1 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			OH.RECORDTYPE, 
			ITM.ITEMCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.CLASSCODE AS SIZE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ITM.REFERENCE_5 AS SORTNAME, 
			DBO.FN_DATE4NEXTYEAR(OH.INVOICEDATE) AS TRANSACTIONDATE,	--ADD ONE EQUIVALENT YEAR 
			DBO.FN_DATE2YEAR(OH.INVOICEDATE) + 1 AS REPORTYEAR, 		--ADD ONE EQUIVALENT YEAR 
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			OD.QUANTITYSHIPPED AS HIST1SHIPPEDQTY, 
			ISNULL(OD.QUANTITYSHIPPED ,0) * (ISNULL(OD.UNITPRICE ,0)) AS HIST1EXTMERCH 
		FROM IMITEM ITM (NOLOCK) 
			LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_ITEM = ITM.ROWID 
			LEFT JOIN OMTRANSACTIONHEADER OH (NOLOCK) ON OH.ROWID = OD.R_TRANSACTIONHEADER 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
		WHERE OH.RECORDTYPE = 'Z' --COMMITTED RECORDS ONLY 
		AND OH.TRANSACTIONTYPE='I' --ORDERS/INVOICES ONLY 
		AND SUBSTRING(OH.TRANSACTIONNUMBER,1,2)<>'IC' --EXCLUDING INTERCOMPANY ORDERS 

		UNION ALL 

		--ePLANT DATASET: CURRENT 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			'Z' AS RECORDTYPE, 
			ISNULL(ITM.ITEMCODE, ePLANT.ITEMCODE) AS ITEMCODE, 
			ISNULL(ITM.REFERENCE_1, 'NOT FOUND IN INSIGHT') AS COMMONNAME, 
			ISNULL(ITM.CLASSCODE, 'NOT FOUND') AS SIZE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ISNULL(ITM.REFERENCE_5, 'NOT FOUND IN INSIGHT') AS SORTNAME, 
			ePLANT.TRANSACTIONDATE, 
			ePLANT.REPORTYEAR,
			ePLANT.SHIPPEDQTY AS CURRSHIPPEDQTY, 
			ePLANT.EXTMERCH AS CURREXTMERCH, 
			0 AS HIST1SHIPPEDQTY, 
			0 AS HIST1EXTMERCH 
		FROM GNC_SHIPPED_HISTORY ePLANT (NOLOCK)	--ePLANT HISTORY GOES BACK TO THE BEGINNING OF REPORTYEAR 2020 (07/28/2019) 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = ePLANT.WAREHOUSEID 
			LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID AND ITM.ITEMCODE = ePLANT.ITEMCODE 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 

		UNION ALL 

		--ePLANT DATASET: HIST1 
		SELECT 
			CO.COMPANYID, 
			CO.NAME AS COMPANYNAME, 
			'Z' AS RECORDTYPE, 
			ISNULL(ITM.ITEMCODE, ePLANT.ITEMCODE) AS ITEMCODE, 
			ISNULL(ITM.REFERENCE_1, 'NOT FOUND IN INSIGHT') AS COMMONNAME, 
			ISNULL(ITM.CLASSCODE, 'NOT FOUND') AS SIZE, 
			WH.IDENTITYID AS WAREHOUSEID, 
			ISNULL(ITM.REFERENCE_5, 'NOT FOUND IN INSIGHT') AS SORTNAME, 
			DBO.FN_DATE4NEXTYEAR(ePLANT.TRANSACTIONDATE) AS TRANSACTIONDATE,	--ADD ONE EQUIVALENT YEAR 
			ePLANT.REPORTYEAR + 1 AS REPORTYEAR,								--ADD ONE EQUIVALENT YEAR 
			0 AS CURRSHIPPEDQTY, 
			0 AS CURREXTMERCH, 
			ePLANT.SHIPPEDQTY AS HIST1SHIPPEDQTY, 
			ePLANT.EXTMERCH AS HIST1EXTMERCH 
		FROM GNC_SHIPPED_HISTORY ePLANT (NOLOCK)	--ePLANT HISTORY GOES BACK TO THE BEGINNING OF REPORTYEAR 2020 (07/28/2019) 
			LEFT JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = ePLANT.WAREHOUSEID 
			LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.R_WAREHOUSE = WH.ROWID AND ITM.ITEMCODE = ePLANT.ITEMCODE 
			JOIN ABCOMPANY CO (NOLOCK) ON CO.COMPANYID = WH.COMPANYID 
	) U 
	WHERE TRANSACTIONDATE <= GETDATE() 
) X 
GROUP BY 
	COMPANYID, 
	COMPANYNAME, 
	RECORDTYPE, 
	REPORTYEAR, 
	WAREHOUSEID, 
	ITEMCODE, 
	COMMONNAME, 
	SIZE, 
	SORTNAME 
