--AAA_EDI_STANDARDS

DECLARE 
@VERSIONID CHAR(10) = '4010',
@TRANSSETID CHAR(4) = '812',
--FOR USE OF FIRST QUERY ONLY:
@SEGMENT	VARCHAR(5)	= 'N101',--'BCD13',
@CODEVALUE	VARCHAR(6)	= '%'

--SELECT DBO.FN_EDI_CODE_DESCRIPTION(@SEGMENT,@CODEVALUE)
/*
SELECT DISTINCT 
TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE) AS SEGMENT, SEGD.DATAELEMENTNUM, ELEC.CODEVALUE, 
TRIM(SUBSTRING(ELEC.DESCRIPTION,1,200)) AS DESCRIPTION
FROM EDSEGMENTDETAIL SEGD (NOLOCK) 
JOIN EDELEMENTCODES ELEC (NOLOCK) ON ELEC.VERSIONID = SEGD.VERSIONID AND ELEC.DATAELEMENTNUM = SEGD.DATAELEMENTNUM
WHERE TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE) LIKE @SEGMENT
AND ELEC.CODEVALUE LIKE @CODEVALUE
ORDER BY TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE), ELEC.CODEVALUE
*/
SELECT 
SETH.VERSIONID, SETH.TRANSSETID, SETH.FUNCGROUPID, SETH.TRANSSETNAME, 
SETD.AREA, SETD.SEGMENTID, 
(SELECT TOP 1 SEGMENTNAME FROM EDSEGMENTHEAD WHERE VERSIONID= SEGD.VERSIONID AND SEGMENTID = SEGD.SEGMENTID) AS SEGMENTNAME, 
SETD.REQUIREMENT, SETD.NOTES, SETD.COMMENTS, SETD.MAXUSE, SETD.LOOPLEVEL, SETD.LOOPREPEAT, SETD.LOOPIDENTIFIER, 
TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE) AS SEGMENT, 
SEGD.DATAELEMENTNUM, SEGD.REQUIREMENT AS ELEMENTREQUIREMENT, SEGD.NOTES AS ELEMENTNOTES, SEGD.COMMENTS AS ELEMENTCOMMENTS, SEGD.SYNTAX AS ELEMENTSYNTAX
FROM EDSETHEAD SETH (NOLOCK)
JOIN EDSETDETAIL SETD (NOLOCK) ON SETD.VERSIONID = SETH.VERSIONID AND SETD.TRANSSETID = SETH.TRANSSETID
JOIN EDSEGMENTDETAIL SEGD (NOLOCK) ON SEGD.VERSIONID = SETH.VERSIONID AND SEGD.SEGMENTID = SETD.SEGMENTID
WHERE SETH.VERSIONID = @VERSIONID--'5010'
AND SETH.TRANSSETID = @TRANSSETID--'812'
ORDER BY SETH.VERSIONID, SETH.TRANSSETID, SETD.AREA, SETD.SEQUENCE, SEGD.SEQUENCE

SELECT
SETD.VERSIONID, SETD.TRANSSETID, 
TRIM(TRIM(SEGD.SEGMENTID) + SEGD.SEQUENCE) AS SEGMENT, 
SEGD.DATAELEMENTNUM, ELEC.CODEVALUE, ELEC.DESCRIPTION 
FROM EDSETDETAIL SETD (NOLOCK)
JOIN EDSEGMENTDETAIL SEGD (NOLOCK) ON SEGD.VERSIONID = SETD.VERSIONID AND SEGD.SEGMENTID = SETD.SEGMENTID
LEFT JOIN EDELEMENTCODES ELEC (NOLOCK) ON ELEC.VERSIONID = SEGD.VERSIONID AND ELEC.DATAELEMENTNUM = SEGD.DATAELEMENTNUM
WHERE SETD.VERSIONID = @VERSIONID--'5010' 
AND SETD.TRANSSETID = @TRANSSETID--'812'
ORDER BY SETD.VERSIONID, SETD.TRANSSETID, SETD.SEQUENCE, SEGD.SEQUENCE
