--AAA_EDI_IMPORT_SPEC
SELECT 
PSH.PRICESCHEDULECODE, PSD.ALTERNATESKU, PSD.FREIGHTCHARGE, PSD.LANDEDPRICE, PSD.LANDEDPRICE - PSD.HANDLINGCHARGE - PSD.OTHERCHARGE -PSD.FREIGHTCHARGE AS UNITPRICE, 
PSD.HANDLINGCHARGE, PSD.OTHERCHARGE, PSD.PRICE, PSD.DISCOUNTPRICE, OD.*, ITM.*
--* 
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = OH.R_SHIPPER AND SZ.R_SHIPPER = OH.R_FMSHIPPER--WH.ROWID
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = SZ.R_PRICESCHEDULE
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
WHERE OH.RECORDTYPE = 'I'
----------------------------------------------------------------------------------------------------
/*
COMPANYID = 'SB'																--LITERAL
MODULE = 'OM'																	--LITERAL
RECORDTYPE = 'R'																--LITERAL
R_PROFILE = (SELECT ROWID FROM OMTRANSACTIONDP WHERE PROFILECODE = '10.23.S1')	--[PROFILECODE]
R_CUSTOMER = (SELECT ROWID FROM IDMASTER WHERE IDENTITYID = '10535')			--[CUSTOMERID]
TRANSACTIONTYPE = 'I'															--LITERAL
TRANSACTIONDATE = '2023/1/2'													--[TRANSACTIONDATE]
PURCHASEORDERNUMBER = 'POB3X80156'												--[PURCHASEORDERNUMBER]
R_TERMS = (SELECT ROWID FROM IDTERMS WHERE TERMSCODE = 'N30')					--[TERMSCODE]
STATUS = 'O'																	--LITERAL
COMMENT =  (SELECT COMMENT FROM OMTRANSACTIONHEADER 
			WHERE PURCHASEORDERNUMBER = 'POB3X80156' AND RECORDTYPE = 'I')		--[PURCHASEORDERNUMBER]
R_SHIPPER = (SELECT ROWID FROM IDMASTER WHERE IDENTITYID = '829254')			--[CONSIGNEEID]
SHIPPINGDATE = '2023/1/2'														--[REQUESTDATE]
USERDEFINEDCODE_1 =																--[REQUESTDATETYPE]
USERDEFINEDREFERENCE_3 =														--[ORDEREDBY]
USERDEFINEDREFERENCE_5 = '535'													--[IDGROUP]
USERDEFINEDREFERENCE_6 {CUST MAJOR ACCT} ?NATIONAL ACCOUNT?????????????????????????????????????????????
USERDEFINEDREFERENCE_10 {EDI_VENDORID)????????????????????????????????????????????????????????????
USERDEFINEDQUANTITY_7 {PO-QUANTITYORDERED]
USERDEFINEDCOMMENT=(SELECT USERDEFINEDCOMMENT FROM OMTRANSACTIONHEADER 
					WHERE PURCHASEORDERNUMBER = 'POB3X80156' 
					AND RECORDTYPE = 'I')										--[PURCHASEORDERNUMBER]
STAGE = 'N'																		--LITERAL
R_FMSHIPPER = (SELECT ROWID FROM IDMASTER WHERE IDENTITYID = '10'				--[WAREHOUSEID]
TRANSACTIONORIGIN = 'E' OR 'R'? NOT SURE ABOUT THIS SETTING??????????????????????????????????????????
USERDEFINEDDATE_19 = '2023/1/2'													--[SHIPNOTBEFOREDATE]
USERDEFINEDDATE_20 = '2023/1/2'													--[SHIPNOTAFTERDATE]
USERDEFINEDREFERENCE_17 = '999990001'		PO_VENDOR									
USERDEFINEDREFERENCE_19 = RIGHT('0000'+TRIM('99'),4)	PO_STORENUMBER			--[STORENUMBER]
R_ZONEFREIGHTRATEOVERRIDE??????????????????????????????????????????????????????????????????????
*/

SELECT * FROM OMTRANSACTIONDETAIL WHERE R_TRANSACTIONHEADER IN (SELECT ROWID FROM OMTRANSACTIONHEADER WHERE RECORDTYPE = 'I')

-----------------------------------------------------------------------------------
/*
COMPANYID = 'SB'																--LITERAL
MODULE = 'OM'																	--LITERAL
RECORDTYPE = 'R'																--LITERAL
R_TRANSACTIONHEADER =	(SELECT ROWID FROM OMTRANSACTIONHEADER 
						WHERE PURCHASEORDERNUMBER = 'POB3X80156' 
						AND RECORDTYPE = 'I')
DETAILTYPE = 'I'
R_ITEM = (SELECT ROWID FROM IMITEM WHERE ITEMCODE = '001884.031.1' 
		AND R_WAREHOUSE = (SELECT ROWID FROM IDMASTER WHERE IDENTITYID = '10'))	--[ITEMCODE][WAREHOUSEID]
R_WAREHOUSE = (SELECT ROWID FROM IDMASTER WHERE IDENTITYID = '10')				--[WAREHOUSE]
R_PRODUCTCATEGORY = (SELECT R_PRODUCTCATEGORY 
					FROM IMITEM WHERE ITEMCODE = '001884.031.1')				--[ITEMCODE]
UNITOFMEASURE = 'EA'															--LITERAL
UNITPRICE =																		--[UNITPRICE]
AMOUNT = S/B UNITPRICE * QUANTITYORDERED?										--[UNITPRICE]*[QUANTITYORDERED]?
QUANTITYORDERED =																--[QUANTITYORDERED]
LINENUMBER =																	--[LINENUMBER]
USERDEFINEDQUANITY_7 =															--[PO_QUANTITYORDERED]
USERDEFINEDQUANITY_8 =															--[PO_LANDEDPRICE]
USERDEFINEDQUANITY_9 =															--[LINENUMBER]
USERDEFINEDREFERENCE_10 =														--[PO_ALTERNATESKU]
*/

