--EDI_812_LOOKUP

--EDI_812_LOOKUP

DECLARE
@BCD01 VARCHAR(8)	= '20230117',				
@BCD02 VARCHAR(22)	= '123456789',				
@BCD03 VARCHAR(2)	= 'T',						
@BCD04 VARCHAR(15)	= '20022',					
@BCD05 VARCHAR(1)	= 'C',						
@BCD07 VARCHAR(20)	= '10-45703',				
@BCD10 VARCHAR(50)	= 'POB1X80156',				
@BCD12 VARCHAR(2)	= 'RA',						
@BCD13 VARCHAR(3)	= 'PD',						
@BCD14 VARCHAR(50)	= 'DEAL99_0_01-01-2022',	
@N902 VARCHAR(50)	= '80156',				
@SAC01 VARCHAR(1)	= 'A',						
@SAC02 VARCHAR(4)	= '',--'H850',					
@SAC05 VARCHAR(15)	= '2783',					

@N102 VARCHAR(60)	= 'RURALKING #99',			
@N104 VARCHAR(20)	= '99',						
@N301 VARCHAR(35)	= '9525 COLLINSVILLE RD',	
@N401 VARCHAR(20)	= 'COLLINSVILLE',			
@N402 VARCHAR(2)	= 'IL',						
@N403 VARCHAR(10)	= '62234',					

@CDD01 VARCHAR(2)	= '01',						
@CDD02 VARCHAR(1)	= 'C',						
@CDD07 VARCHAR(10)	= '2',						
@CDD11 VARCHAR(17)	= '5.25',					
@CDD14 VARCHAR(264) = 'BECAUSE',				

@LIN01 VARCHAR(10)	= '1',						
@LIN03 VARCHAR(48)	= 'SKUNUMBER',				
@LIN05 VARCHAR(48)	= 'UPCNUMBER',				
@LIN07 VARCHAR(48)	= 'ITEMCODE',				

@N902ZZ VARCHAR(50)	= 'ALLOWANCE NOT GIVEN',	
@N903LI VARCHAR(45)	= 'COMMENTS',				

@SAC01INFO VARCHAR(1)	= 'A',					
@SAC02INFO VARCHAR(4)	= 'D240',				
@SAC05INFO VARCHAR(15)	= '2783',				
@SAC08INFO VARCHAR(9)	= '1.25',				
@SAC15INFO VARCHAR(80)	= 'FREIGHT'				

------------------------------------------
DECLARE 
		@ROWID			VARCHAR(38), 
		@EMAILSUBJECT	VARCHAR(1000), 
		@EMAILBODY		VARCHAR(MAX), 
--<EMAILBODY>CREDIT ADJUSTMENT #: 123456789<BR>
------------------------------------------<BR>
--CREATE/SEND<BR>
--DATE: 20230117<BR>
--INV#: 10-45703   PO#: POB1X80156<BR>
--CREDIT NOTE REQUEST-PROMO/DEAL#: DEAL99_0_01-01-2022<BR>
--VENDOR#: 999990001     STORE#: 0099<BR><BR>

--RURALKING #99<BR>
--9525 COLLINSVILLE RD<BR>
--COLLINSVILLE, IL  62234<BR><BR>

--LIN#:1   SKU:SKUNUMBER   ITEM#:ITEMCODE(UPC:UPCNUMBER)   QTY:2 @ $5.25   01-PRICING ERROR   BECAUSE   ALLOWANCE NOT GIVEN/COMMENTS<BR>
--D240: DOMESTIC FREIGHT (ALLOWANCE)  RATE: 1.25     $27.83<BR>
--TOTAL ADJUSTMENT AMOUNT: $200.22<BR><BR>

--</EmailBody>
-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
/*
DECLARE
@BCD01 VARCHAR(8)	= '20230117',				--CDADJUSTMENTDATE	FORMAT:YYYYMMDD
@BCD02 VARCHAR(22)	= '123456789',				--CDADJUSTMENTNUMBER
@BCD03 VARCHAR(2)	= 'T',						--TRANSACTIONHANDLINGCODE	(T=SEND810, H=FYIDONTSEND810)
@BCD04 VARCHAR(15)	= '20022',					--NETAMOUNT
@BCD05 VARCHAR(1)	= 'C',						--CDFLAGCODE	(C=CREDIT,D=DEBIT)
@BCD07 VARCHAR(20)	= '10-45703',				--INVOICENUMBER
@BCD10 VARCHAR(50)	= 'POB1X80156',				--PURCHASEORDERNUMBER
-->NEED TO LOOK INTO CREDITNOTEREQUEST ON THE 810 MAP
@BCD12 VARCHAR(2)	= 'RA',						--TRANSACTIONTYPECODE	(DR=DEBITMEMO, CR=CREDITMEMO, RA=CREDITNOTEREQEST)
@BCD13 VARCHAR(3)	= 'PD',						--REFERENCEIDQUALIFIER	(PD=PROMOTION/DEALNUMBER; 1X=CDAJUSTMENTNUMBER)
@BCD14 VARCHAR(50)	= 'DEAL99_0_01-01-2022',	--CDADJUSTMENTNUMBER/DEALNUMBER

@N902 VARCHAR(50)	= '999990001',				--PO_VENDOR

@SAC01 VARCHAR(1)	= 'A',						--A=ALLOWANCE, C=CHARGE
@SAC02 VARCHAR(4)	= '',--'H850',					--H850=TAX
@SAC05 VARCHAR(15)	= '2783',					--TOTAL TAX AMOUNT

@N102 VARCHAR(60)	= 'RURALKING #99',			--SHIPTONAME
@N104 VARCHAR(20)	= '99',						--STORENUMBER USE:RIGHT('00'+TRIM(@N104),4) TO MAKE IT MATCH INSIGHT
@N301 VARCHAR(35)	= '9525 COLLINSVILLE RD',	--SHIPTOADDRESS1
@N401 VARCHAR(20)	= 'COLLINSVILLE',			--SHIPTOCITY
@N402 VARCHAR(2)	= 'IL',						--SHIPTOSTATE
@N403 VARCHAR(10)	= '62234',					--SHIPTOZIP

@CDD01 VARCHAR(2)	= '01',						--ADJREASON	(01=PRICING ERROR, 06=QTY CONTESTED, 10=CNT CHARGE ERR, 11=RETURN/DAMAGE, 54 = FRT DEDUCT, 55= TAX DEDUCT, OTHER)
@CDD02 VARCHAR(1)	= 'C',						--CDFLAG	(C=CREDIT, D=DEBIT)
@CDD07 VARCHAR(10)	= '2',						--CDQTY
@CDD11 VARCHAR(17)	= '5.25',					--CDPRICE
@CDD14 VARCHAR(264) = 'BECAUSE',				--CDMESSAGE

@LIN01 VARCHAR(10)	= '1',						--PO_LINENUMBER
@LIN03 VARCHAR(48)	= 'SKUNUMBER',				--PO_ALTERNATESKU
@LIN05 VARCHAR(48)	= 'UPCNUMBER',				--UPCNO
@LIN07 VARCHAR(48)	= 'ITEMCODE',				--ITEMCODE

@N902ZZ VARCHAR(50)	= 'ALLOWANCE NOT GIVEN',	--DESCRIPTION
@N903LI VARCHAR(45)	= 'COMMENTS',				--COMMENTS

@SAC01INFO VARCHAR(1)	= 'A',					--A=ALLOWANCE, C=CHARGE
@SAC02INFO VARCHAR(4)	= 'D240',				--SERVICECODE	(D240=FREIGHT, OTHERS)
@SAC05INFO VARCHAR(15)	= '2783',				--SACAMOUNT
@SAC08INFO VARCHAR(9)	= '1.25',				--SACRATE
@SAC15INFO VARCHAR(80)	= 'FREIGHT'				--SACDESCRIPTION

------------------------------------------
DECLARE 
		@EMAILSUBJECT	VARCHAR(1000),
		@EMAILBODY		VARCHAR(MAX), 
		@CREDITDEBIT	VARCHAR(7),		--BCD05: C=CREDIT, D=DEBIT
		@SENDONTSEND	VARCHAR(20),	--BCD03: T=SEND, H=INFORMATION ONLY
		@CREDITNOTE		VARCHAR(20),	--BCD12: CR=CREDITMEMO, DR=DEBITMEMO, RA=CREDITNOTEREQUEST
		@TRANSTYPE		VARCHAR(20),	--BCD13:PD=PROMO/DEAL#, 1X=CDADJUSTMENT#
		@CDDREASON		VARCHAR(60),	--CDD01:01=PRICING ERROR, 06=QUANTITY CONTESTED, OTHER
		@SACINFOTYPE	VARCHAR(10),	--SAC01INFO: A=ALLOWANCE, C=CHARGE
		@SACINFOCODES	VARCHAR(60),	--SAC02INFO:
		@ROWID			VARCHAR(38)

SET @CREDITDEBIT =	CASE	WHEN @BCD05 = 'C' THEN 'CREDIT' 
							WHEN @BCD05 = 'D' THEN 'DEBIT' 
							ELSE 'err' END
SET @SENDONTSEND =	CASE	WHEN @BCD03 = 'T' THEN 'CREATE/SEND' 
							WHEN @BCD03 = 'H' THEN 'INFORMATIONAL ONLY' 
							ELSE 'err' END
SET @CREDITNOTE =	CASE	WHEN @BCD12 = 'CR' THEN 'CREDIT MEMO' 
							WHEN @BCD12 = 'DR' THEN 'DEBIT MEMO' 
							WHEN @BCD12 = 'RA' THEN 'CREDIT NOTE REQUEST' 
							ELSE 'err' END
SET @TRANSTYPE =	CASE	WHEN @BCD13 = 'PD' THEN 'PROMO/DEAL#: ' 
							WHEN @BCD13 = '1X' THEN 'CDADJUSTMENT#: ' 
							ELSE 'err' END
SET @CDDREASON =	CASE	WHEN @CDD01 = '01' THEN 'PRICING ERROR'
							WHEN @CDD01 = '06' THEN 'QUANTIY CONTESTED'
							WHEN @CDD01 = '10' THEN 'PALLET/CONTAINER CHARGE ERROR'
							WHEN @CDD01 = '11' THEN 'RETURNS - DAMAGE'
							WHEN @CDD01 = '54' THEN 'FREIGHT DEDUCTED'
							WHEN @CDD01 = '55' THEN 'TAX DEDUCTED'
							WHEN @CDD01 = '57' THEN 'VOLUME DISCOUNT TAKEN'
							WHEN @CDD01 = '79' THEN 'COOPERATIVE ADVERTISING'
							WHEN @CDD01 = '81' THEN 'CREDIT AS AGREED'
							WHEN @CDD01 = '82' THEN 'DEFECTIVE ALLOWANCE'
							WHEN @CDD01 = '88' THEN 'DUTY CHARGE VARIANCE'
							WHEN @CDD01 = '98' THEN 'LABOR CHARGES'
							WHEN @CDD01 = 'A3' THEN 'NEW STORE ALLOWANCE'
							WHEN @CDD01 = 'A5' THEN 'OVERAGE'
							WHEN @CDD01 = 'A8' THEN 'PROMOTIONAL ALLOWANCE'
							WHEN @CDD01 = 'B2' THEN 'REBATE'
							WHEN @CDD01 = 'B6' THEN 'REPAY DISCOUNT'
							WHEN @CDD01 = 'BE' THEN 'FIXTURE ALLOWANCE'
							WHEN @CDD01 = 'E5' THEN 'INVOICE PRICE PROTECTION'
							WHEN @CDD01 = 'E7' THEN 'GOODS AND SERVICES TAX DECREASED DUE TO BILLING ERROR'
							WHEN @CDD01 = 'GE' THEN 'SLOTTING CHARGE'
							WHEN @CDD01 = 'GA' THEN 'FREE GOODS'
							WHEN @CDD01 = 'IA' THEN 'INVOICE AMOUNT DOES NOT MATCH ACCOUNT ANALYSIS STATEMENT'
							WHEN @CDD01 = 'L7' THEN 'MISCELLANEOUS DEDUCTIONS'
							WHEN @CDD01 = 'L8' THEN 'MISCELLANEOUS CREDITS'
							WHEN @CDD01 = 'RB' THEN 'AGREED FREIGHT ALLOWANCE'
							WHEN @CDD01 = 'SF' THEN 'SHIPPING AND FREIGHT CHARGE'
							WHEN @CDD01 = 'WW' THEN 'OVERPAYMENT CREDIT'
							WHEN @CDD01 = 'ZZ' THEN 'MUTUALLY DEFINED'
							ELSE 'err' END
SET @SACINFOTYPE =	CASE	WHEN @SAC01INFO = 'A' THEN 'ALLOWANCE'
							WHEN @SAC01INFO = 'C' THEN 'CHARGE'
							ELSE 'err' END
SET @SACINFOCODES =	CASE	WHEN @SAC02INFO = 'F050' THEN 'MISCELLANEOUS'
							WHEN @SAC02INFO = 'H850' THEN 'TAXES'
							WHEN @SAC02INFO = 'F180' THEN 'PALLET SURCHARGES'
							WHEN @SAC02INFO = 'G821' THEN 'SHIPPING'
							WHEN @SAC02INFO = 'E890' THEN 'OCEAN FREIGHT'
							WHEN @SAC02INFO = 'A310' THEN 'AIR FREIGHT'
							WHEN @SAC02INFO = 'D240' THEN 'DOMESTIC FREIGHT'
							WHEN @SAC02INFO = 'C530' THEN 'DUTY CHARGE'
							WHEN @SAC02INFO = 'A122' THEN 'TARIFF'
							WHEN @SAC02INFO = 'I530' THEN 'VOLUME DISCOUNT'
							WHEN @SAC02INFO = 'F910' THEN 'QUARTERLY VOLUME REBATE'
							WHEN @SAC02INFO = 'G960' THEN 'SLOTTING ALLOWANCE'
							WHEN @SAC02INFO = 'D170' THEN 'FREE GOODS'
							WHEN @SAC02INFO = 'F970' THEN 'MONTHLY REBATE'
							WHEN @SAC02INFO = 'F680' THEN 'PRICING CORRECTION'
							WHEN @SAC02INFO = 'B720' THEN 'COOPERATIVE ADVERTISING'
							WHEN @SAC02INFO = 'F800' THEN 'PROMOTIONAL ALLOWANCE'
							WHEN @SAC02INFO = 'B210' THEN 'CO-OP CREDIT'
							WHEN @SAC02INFO = 'F810' THEN 'PROMOTIONAL DISCOUNT'
							WHEN @SAC02INFO = 'E190' THEN 'LABOR CHARGES'
							WHEN @SAC02INFO = 'E565' THEN 'MARKDOWN ALLOWANCE'
							WHEN @SAC02INFO = 'B950' THEN 'SHIPPING DAMAGES'
							WHEN @SAC02INFO = 'D350' THEN 'GOODS AND SERVICES CREDIT ALLOWANCES'
							WHEN @SAC02INFO = 'C000' THEN 'DEFECTIVE ALLOWANCE'
							WHEN @SAC02INFO = 'C010' THEN 'DEFICIT FREIGHT'
							WHEN @SAC02INFO = 'C750' THEN 'OVERPAYMENTS'
							WHEN @SAC02INFO = 'D890' THEN 'TRAINING'
							WHEN @SAC02INFO = 'I090' THEN 'TOOL CHARGE'
							WHEN @SAC02INFO = 'A570' THEN 'EXCESS FREIHT, NOT LANDABLE'
							WHEN @SAC02INFO = 'I590' THEN 'WARRANTIES'
							WHEN @SAC02INFO = 'B750' THEN 'CORE CHARGE'
							WHEN @SAC02INFO = 'IDCT' THEN 'IMPROPER DOCUMENTATION'
							ELSE 'err' END

SET @EMAILSUBJECT = '<EMAILSUBJECT>' + ISNULL(TRIM(@BCD02), 'missing') + ' (' + @CREDITDEBIT + ') ' + ISNULL(TRIM(@BCD07), 'missing') + ' CREDIT DEBIT ADJUSTMENT<BR>'

SET @EMAILBODY = '<EMAILBODY>' + 
@CREDITDEBIT + ' ADJUSTMENT #: ' + ISNULL(TRIM(@BCD02),'missing') + '<BR>' 
+ REPLICATE('-',40)+'<BR>' 
+ @SENDONTSEND + '<BR>' 
+ 'DATE: ' + ISNULL(TRIM(@BCD01), 'missing') + '<BR>' 
+ 'INV#: ' + ISNULL(TRIM(@BCD07), 'missing') + '   PO#: ' + ISNULL(TRIM(@BCD10), 'missing') + '<BR>' 
+ @CREDITNOTE + '-' + @TRANSTYPE + ISNULL(TRIM(@BCD14),'missing') + '<BR>' 
+ IIF(ISNULL(@SAC02,'')='', '','HEADER ADJUSTMENT: ' + @SAC02 + '(' + @SAC01 + ') = $' + LEFT(TRIM(@SAC05),LEN(TRIM(@SAC05))-2)+'.'+RIGHT(TRIM(@SAC05),2) + '<BR>')
+ 'VENDOR#: '+ISNULL(TRIM(@N902),'missing')+'     STORE#: '+ISNULL(RIGHT('00'+TRIM(@N104),4),'missing')+'<BR><BR>'
+ ISNULL(TRIM(@N102),'missing') + '<BR>' 
+ ISNULL(TRIM(@N301),'missing')+'<BR>' 
+ ISNULL(TRIM(@N401),'missing') + ', ' + ISNULL(TRIM(@N402),'missing') + '  ' + ISNULL(TRIM(@N403),'missing')+'<BR><BR>'
+'LIN#:'+TRIM(@LIN01)+'   SKU:'+TRIM(@LIN03)+'   ITEM#:'+TRIM(@LIN07)+'(UPC:'+TRIM(@LIN05)+')   QTY:'+TRIM(@CDD07)+' @ $'+TRIM(@CDD11)+'   '
+@CDD01 + '-' + @CDDREASON + '   ' + TRIM(@CDD14) + '   '+@N902ZZ + '/' + @N903LI + '<BR>'
+REPLICATE(' ',20)+TRIM(@SAC02INFO)+': '+ @SACINFOCODES + ' (' + @SACINFOTYPE + ')  RATE: '+ @SAC08INFO + '     $' + LEFT(TRIM(@SAC05INFO),LEN(TRIM(@SAC05INFO))-2)+'.'+RIGHT(TRIM(@SAC05INFO),2) + '<BR>'
+'TOTAL ADJUSTMENT AMOUNT: $'+ LEFT(TRIM(@BCD04),LEN(TRIM(@BCD04))-2)+'.'+RIGHT(TRIM(@BCD04),2) + '<BR><BR>'

Set @EmailSubject = @EmailSubject + '</EmailSubject>'
Set @EmailBody = @EmailBody + '</EmailBody>'

--select @EmailSubject, @EmailBody
--Populate ABERRORSHEADER
Set @RowId = NewId()
INSERT INTO ABERRORSHEADER (ROWID, COMPANYID, MODULE, RECORDTYPE, DESCRIPTION, COMMENT)
VALUES (@RowId, 'SB', 'OM', 'R', '812 EDI MESSAGE', @EmailSubject + @EmailBody)
*/
