--AAA_EDI_824_EMAIL

DECLARE
@BGN02  VARCHAR(30) = 'POB1X80156'	,	--DOCNUMBER
@BGN03  VARCHAR(8)  = '20230214'		,	--DOCDATE
@BGN04  VARCHAR(8)  = '1333'		,	--DOCTIME
@OTI01  VARCHAR(2)  = 'TR'			,	--TRANSCODE
@OTI02  VARCHAR(3)  = 'PR'			,	--TRANSTYPE
@OTI03  VARCHAR(30) = 'POB1X80156'	,	--TRANSNUMBER
@OTI08  VARCHAR(9)  = '1',	--GSCNTRLNO
@OTI09  VARCHAR(9)  = '0001',	--STCNTRLNO
@TED01  VARCHAR(3)  = '024',	--ERRTYPE
@TED02  VARCHAR(60) = 'DUPLICATE INVOICE',	--ERRMSG
@NTE02  VARCHAR(80) = 'BLAH BLAH BLAH'	--NOTEMSG

DECLARE 
	@EMAILSUBJECT	VARCHAR(1000),
	@EMAILBODY	VARCHAR(MAX), 
	@ROWID		UNIQUEIDENTIFIER, --VARCHAR(38), 
	@ST01 		VARCHAR(3), 
	@TRANSCODE	CHAR(34),
	@TRANSTYPE	VARCHAR(18)

SET @ST01 = 		'824'
SET @TRANSCODE=	(
	CASE	WHEN ISNULL(@OTI01,'') = 'TA' THEN ' TRANSACTION SET ACCEPT           ' 
			WHEN ISNULL(@OTI01,'') = 'TE' THEN ' TRANSACTION SET ACCEPT WITH ERROR' 
			WHEN ISNULL(@OTI01,'') = 'TR' THEN ' TRANSACTION SET REJECT           ' 
	ELSE 'err' END)
SET @TRANSTYPE=	(
	CASE	WHEN ISNULL(@OTI02,'') = 'IV' THEN ' SELLER INVOICE#: ' 
			WHEN ISNULL(@OTI02,'') = 'PO' THEN ' PO#: ' 
			WHEN ISNULL(@OTI02,'') = 'SI' THEN ' SHIPPER SID: ' 
			WHEN ISNULL(@OTI02,'') = 'PR' THEN ' PO# FROM 855: ' 
	ELSE 'err' END)

SET @EMAILSUBJECT = ('<EmailSubject>' + @ST01 + ' ERROR MESSAGE ' + '</EmailSubject>') 

SET @EMAILBODY = ('<EmailBody>' 
+ ISNULL(@BGN02,'') + ' - ' + ISNULL(@BGN03,'') + ' ' + ISNULL(@BGN04,'') + '<BR>' 
+ ISNULL(@OTI01,'') + @TRANSCODE + ' ' + ISNULL(@TRANSTYPE,'') + ISNULL(@OTI03,'') + ' GS#' + ISNULL(@OTI08,'') + ' ST#' + ISNULL(@OTI09,'') + '<BR>' 
+ ISNULL(@TED01,'') + ' ' + ISNULL(@TED02,'') + '<BR>' 
+ ISNULL(@NTE02,'') + '<BR><BR>' 
+ '</EmailBody>') 

--SELECT 'TEST' AS ROWID, @EMAILSUBJECT AS EMAILSUBJECT, @EMAILBODY AS EMAILBODY

--Populate ABERRORSHEADER 
Set @RowId = NewId() 
INSERT INTO ABERRORSHEADER (ROWID, COMPANYID, MODULE, RECORDTYPE, DESCRIPTION, COMMENT) 
VALUES (@RowId, 'SB', 'OM', 'R', 'EDI_824_EMAIL', @EmailSubject + @EmailBody) 



