--AAA_TA_TEMPPRODTime_SQL IMPSD TEMPORARY Email Multiple EDI Breaking Points check
/* BODY OF EMAIL:
Park Hill EDI Team:

Here is the list of items with issues that will impact EDI and cause failures to transmit for Park Hill orders.
Please correct these issues before the order is committed and invoiced.

El Campo EDI Team:

Here is the list of items with issues that will impact EDI and cause failures to transmit for El Campo orders.
Please correct these issues before the order is committed and invoiced.

Tarboro EDI Team:

Here is the list of items with issues that will impact EDI and cause failures to transmit for Tarboro orders.
Please correct these issues before the order is committed and invoiced.

Legend of Violations and their meanings:

Violation						Meaning/Action needed
----------------------------	----------------------------
SKU ROLLUP VIOLATION			This customer wants EDI transmitted with Quantities rolled-up by SKU
								Two or more items on this order with the same SKU have differences in their price buckets:
								(DISCOUNTPRICE/FREIGHTCHARGE/SERVICECHARGE/HANDLINGCHARGE)
								Price Schedule needs fixed and pricing needs to be verified on the order.

ORDER PRICES NOT UPDATED        Just fixing the Price Schedule isn't enough, the prices still need verified on the order.
*LINE REMOVED*                              We are getting a lot of errors coming through EDI because this step isn't being done.

PO REQUIRED						PO missing on a customer setup to require it.
								Add it to the order.

WORK ORDER# REQUIRED			WO# missing on a customer setup to require it. 
								(Please set WO# before moving stage to ASSIGNED) 
*LINE REMOVED*								- It will be too late if this violation appears and will need me to manually add it to the Original PO. 
*LINE REMOVED*								However, it is still important to add it to the order and I will need to know which WO# is being used. 

SKU REQUIRED					SKU missing from an item that requires it. 
								Add it to the item in the Price Schedule. 

RETAIL REQUIRED					Retail Price missing from an item that requires it. 
								Add it to the item in the Price Schedule. 

UNSPECIFIED SKU REQUIRED		Item not in the Price Schedule but still requires a SKU. 
								Must add this item to Price Schedule to provide required SKU. 

UNSPECIFIED RETAIL REQUIRED		Item not in the Price Schedule but still requires a Retail Price. 
								Must add this item to Price Schedule to provide required Retail Price. 

UNSPECIFIED ITEM NOT ALLOWED	This customer only accepts items on the Price Schedule, this item is not in the Price Schedule. 

MISSING GROUPAPPROVALCODE		This customer requires it, add to Order.

If additional people need to get these emails, let me know.


Don Taylor
EDI Support Tech
Greenleaf Nursery
Ph   #918-457-2267
Cell #918-822-1688

*/
SELECT * 
FROM (	
	SELECT 
		--ADDED 4 UPDATEDATETIME FIELDS FOR PARK HILL ONLY PER ERICA:
		ISNULL(OH.LASTUPDATEDATETIME,OH.CREATIONDATETIME) AS ORD_LASTCHG, 
		ISNULL(OD.LASTUPDATEDATETIME,OD.CREATIONDATETIME) AS ORD_DTL_LASTCHG, 
		ISNULL(PSH.LASTUPDATEDATETIME,PSH.CREATIONDATETIME) AS SCHED_LASTCHG, 
		ISNULL(PSD.LASTUPDATEDATETIME,PSD.CREATIONDATETIME) AS SCHEDDTL_LASTCHG, 
		WH.IDENTITYID AS WAREHOUSEID, 
		ICUST.USERDEFINEDCODE_9 AS EDICUST, 
		ISNULL(ICUST.USERDEFINEDCODE_8, 'N') AS NATLACCT,	--ADD PER ERICA 3/6/24 - DT
		CUST.IDGROUP, 
		REPLACE(GRP.DESCRIPTION_1,',','') AS GROUPNAME, 
		CONS.IDENTITYID AS CONSIGNEEID, 
		CONS.NAME AS CONSIGNEENAME, 
		OH.TRANSACTIONNUMBER, 
		OH.SHIPPINGDATE AS REQUESTDATE, 
		OH.RECORDTYPE, 
		SUBSTRING(DBO.FN_STAGESORT(OH.STAGE,'OM'),4,18) AS STAGE, 
		OH.USERDEFINEDCODE_2 AS STEP, 
		PSH.PRICESCHEDULECODE, 
		PSD.ALTERNATESKU AS SKU,
		IIF(PSH.ALLOWUNSPECIFIED != 'N' AND PSD.ROWID IS NULL,'Y', NULL) AS ISUNSPECIFIED, 
		ITM.ITEMCODE, 
		ITM.REFERENCE_1 AS COMMONNAME, 
		--VALIDATION CALCULATION FIELD: 
		--IIF(ICUST.STATUS <> 'A','INACTIVE CUSTOMER/', '') + 
		--IIF(ISNULL(ICUST.USERDEFINEDCODE_9,'') <> 'Y','NOT AN EDI CUSTOMER/', '') + 
		IIF((	SELECT IIF((COUNT(DISTINCT CPSD.DISCOUNTPRICE) + 
							COUNT(DISTINCT CPSD.FREIGHTCHARGE) + 
							COUNT(DISTINCT CPSD.OTHERCHARGE) + 
							COUNT(DISTINCT CPSD.HANDLINGCHARGE))/4. > 1., 'Y', NULL) 
				--FIND INCONSISTENT SKU PRICING IN PRICE SCHEDULE:
				FROM IMPRICESCHEDULEDETAIL CPSD (NOLOCK) 
				--ADD JOIN TO ONLY CONSIDER ITEMS THAT ARE ON THE ORDER WITH THE SAME ALTERNATESKU:
				JOIN OMTRANSACTIONDETAIL COD (NOLOCK) ON COD.R_TRANSACTIONHEADER = OH.ROWID AND COD.R_ITEM = CPSD.R_ITEM
				WHERE CPSD.R_PRICESCHEDULEHEADER = PSH.ROWID 
				AND CPSD.ALTERNATESKU = PSD.ALTERNATESKU 
				AND CPSD.EXPIRATIONDATE > OH.SHIPPINGDATE 
				AND ICUST.USERDEFINEDCODE_3 = 'Y' --ONLY IF SKUROLLUP IS REQUIRED BY THE CUSTOMER 
			) = 'Y','SKU ROLLUP VIOLATION/', '') + 

		--WAS BROKEN, NOW IT SHOULD WORK AGAIN.
		IIF((	SELECT IIF(ROUND(AVG(COD.UNITPRICE),2) != ROUND(PSD.DISCOUNTPRICE,2)
						OR ROUND(AVG(COD.FREIGHTRATEPERITEM),2) != ROUND(PSD.FREIGHTCHARGE,2)
						OR ROUND(AVG(COD.TAGGINGCHARGEPERITEM),2) != ROUND(PSD.OTHERCHARGE,2) 
						OR ROUND(AVG(COD.HANDLINGCHARGEPERITEM),2) != ROUND(PSD.HANDLINGCHARGE,2), 'Y',NULL) 
				FROM OMTRANSACTIONDETAIL COD (NOLOCK)
				WHERE COD.R_TRANSACTIONHEADER = OH.ROWID 
				and PSD.R_ITEM = COD.R_ITEM 
				AND ICUST.USERDEFINEDCODE_3 = 'Y'	--ONLY IF SKUROLLUP IS REQUIRED BY THE CUSTOMER 
				AND OH.STAGE != 'L'					--IF ORDER IS CANCELLED WE DON'T CARE
			) = 'Y','ORDER PRICES NOT UPDATED/', '') + 

		IIF(ICUST.OMREQUIREPO = 'Y' AND NULLIF(TRIM(OH.PURCHASEORDERNUMBER),'') IS NULL,'PO REQUIRED/', '') + 
		IIF(ICUST.USERDEFINEDCODE_7 = 'Y' AND OH.USERDEFINEDREFERENCE_4 IS NULL,'WORK ORDER# REQUIRED/', '') + 
		IIF(PSH.SKUREQUIRED = 'Y' AND NULLIF(TRIM(PSD.ALTERNATESKU),'') IS NULL AND PSD.ROWID IS NOT NULL,'SKU REQUIRED/', '') + 
		IIF(PSH.RETAILREQUIRED = 'Y' AND NULLIF(PSD.RETAILPRICE,0) IS NULL AND PSD.ROWID IS NOT NULL,'RETAIL REQUIRED/', '') + 
		IIF(PSH.SKUREQUIRED = 'Y' AND NULLIF(TRIM(PSD.ALTERNATESKU),'') IS NULL AND PSD.ROWID IS NULL,'UNSPECIFIED SKU REQUIRED/', '') + 
		IIF(PSH.RETAILREQUIRED = 'Y' AND NULLIF(PSD.RETAILPRICE,0) IS NULL AND PSD.ROWID IS NULL,'UNSPECIFIED RETAIL REQUIRED/', '') + 
IIF(ICUST.USERDEFINEDCODE_6 = 'Y' AND OH.USERDEFINEDREFERENCE_2 IS NULL,'MISSING GROUPAPPROVALCODE/' , '') + 
		IIF(PSH.ALLOWUNSPECIFIED = 'N' AND PSD.ROWID IS NULL,'UNSPECIFIED ITEM NOT ALLOWED', '') 
			AS VIOLATIONS, oh.COMMITDATE

	FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
		JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
		JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER AND ISNULL(ICUST.USERDEFINEDCODE_9,'N') = 'Y'	--IS EDI CUSTOMER 
		JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		LEFT JOIN IDCONSIGNEESHIPPERZONE CSZ (NOLOCK) ON CSZ.R_CONSIGNEE = CONS.ROWID AND CSZ.R_SHIPPER = WH.ROWID 
		LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(CSZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
		LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 
		LEFT JOIN IDCODES GRP (NOLOCK) ON GRP.CODE = CUST.IDGROUP AND GRP.CODETYPE = 'Z7'	--CUSTOMERGROUPNAME 
	WHERE OH.RECORDTYPE = 'R' AND OH.TRANSACTIONTYPE = 'I' 
	AND (	OH.STAGE IN ('A','S','C') OR 
			--WO# REQUIRED AND NOT AT RESERVE STEP (THESE ARE LOWES 855s THAT NEED WO#s BEFORE THEY ARE MOVED TO ASSIGNED OR CANCELED):
			(ICUST.USERDEFINEDCODE_7 = 'Y' AND OH.USERDEFINEDCODE_2 != 'RESERVE')	)
	) X
WHERE WAREHOUSEID IN ('10','20','40','60') AND NULLIF(VIOLATIONS, '') IS NOT NULL 
--AND X.NATLACCT = 'N'
--AND X.TRANSACTIONNUMBER in ('40-32354','40-32360')
ORDER BY WAREHOUSEID, RIGHT('0'+TRIM(IDGROUP),3), PRICESCHEDULECODE, SKU, ITEMCODE

