--AAA_EDI_OUTOFBALANCE 
SELECT 
TRIM(OH.PURCHASEORDERNUMBER+'-'+OH.TRANSACTIONNUMBER)+'.XLSX' AS FILENAME, 
OH.TRANSACTIONNUMBER AS ORDERNO, 
OH.PURCHASEORDERNUMBER AS PONUMBER, 
ITM.ITEMCODE, 
OD.QUANTITYSHIPPED, 
PSD.ALTERNATESKU AS SKU, 
'' AS X, 
ISNULL(OD.UNITPRICE,0) AS UNITPRICE, 
ISNULL(OD.HANDLINGCHARGEPERITEM,0)+ISNULL(OD.TAGGINGCHARGEPERITEM,0) AS HANDCH, 
OD.FREIGHTRATEPERITEM AS FREIGHT, 
OD.QUANTITYSHIPPED*(OD.UNITPRICE+OD.HANDLINGCHARGEPERITEM) AS MERCHAMT, 
------------------------------------------------------------------------------------
--Zero FRTZONE amount denotes that FREIGHTRATEPERITEM should be treated as Zero too.
OD.QUANTITYSHIPPED*IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0)) AS FRTAMT, 
------------------------------------------------------------------------------------
DBO.FN_ORDERVALUE(OH.ROWID,'ITEMPRICE') AS ORDMERCH, 
DBO.FN_ORDERVALUE(OH.ROWID,'FREIGHT') AS ORDFRT 

	FROM OMTRANSACTIONHEADER OH (NOLOCK) 
	LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) on OD.R_TRANSACTIONHEADER=OH.ROWID 
	LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
	LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
	LEFT JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER 
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OD.R_WAREHOUSE 
	LEFT JOIN IDCONSIGNEE CONS (NOLOCK) ON CONS.R_IDENTITY = OH.R_SHIPPER 
	LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID 
	LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = ISNULL(SZ.R_PRICESCHEDULE, CONS.R_PRICESCHEDULE) 
	AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 
--	WHERE OD.R_TRANSACTIONHEADER = @HEADERROWID AND ISNULL(ICUST.USERDEFINEDCODE_3,'') ='Y' 
WHERE OH.TRANSACTIONNUMBER = '10-82508' 
ORDER BY PSD.ALTERNATESKU 