SELECT '['+trim(ICONS.USERDEFINEDREFERENCE_2) as storenumber, OH.R_SYNONYMSALTSHIPTO, 
DP.PROFILECODE, --WH.IDENTITYID AS WHID, WH.NAME AS WHNAME, 
OH.TRANSACTIONNUMBER, 
--CUST.IDENTITYID AS CUSTID, CUST.NAME AS CUSTNAME, 
CONS.IDENTITYID AS CONSID, CONS.NAME AS CONSNAME, CONS.IDGROUP--, 
--TERMS.TERMSCODE, 
--OH.*--, OD.*  
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
--LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
LEFT JOIN OMTRANSACTIONDP DP (NOLOCK) ON DP.ROWID = OH.R_PROFILE 
LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
--LEFT JOIN IDTERMS TERMS (NOLOCK) ON TERMS.ROWID = OH.R_TERMS 
LEFT JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
LEFT JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 

WHERE OH.RECORDTYPE <>'P'--= 'I' 
and CUST.IDENTITYID = '10043'
AND (ICONS.USERDEFINEDREFERENCE_2 is null or ICONS.USERDEFINEDREFERENCE_2 = '0000')
-----------------------------------------------------------------------------------
/*
--GNC_BAK02_ACKTEXT(TRANSACTIONNUMBER) 

DECLARE @TRANSACTIONNUMBER CHAR(20) = '10-45703'

DECLARE @BAK02_ACKTEXT CHAR(2)
SELECT TOP 1 @BAK02_ACKTEXT = IIF(DBO.FN_EDI_PO_CHANGES(@TRANSACTIONNUMBER, NULL, 'O') > 0, 'AC', 'AD')
SELECT @BAK02_ACKTEXT AS BAK02_ACKTEXT
*/


-----------------------------------------------------------------------------------
/*
--GNC_PO_TRANSNUMBER(VENDOR,DEPT,PONUMBER) 
 
DECLARE @VENDORNUMBER CHAR(12) = '999990001' 
DECLARE @DEPTNUMBER CHAR(10) = NULL 
DECLARE @PONUMBER VARCHAR(20) = 'POB3X80156' 
 
DECLARE @TRANSACTIONNUMBER CHAR(20) 

SELECT TOP 1 @TRANSACTIONNUMBER = TRIM(EDI.IDGROUP)+'-'+TRIM(@PONUMBER) 

--SELECT TOP 1 @TRANSACTIONNUMBER = EDI.IDGROUP+'-'+@PONUMBER 

--SELECT EDI.IDGROUP, @VENDORNUMBER 
FROM GNC_EDI_TRANSLATION EDI (NOLOCK) 
WHERE ISNULL(EDI.VENDOR,'') = ISNULL(@VENDORNUMBER,'') 
AND ISNULL(EDI.DEPT,'') = ISNULL(@DEPTNUMBER,'') 

SELECT @TRANSACTIONNUMBER AS TRANSACTIONNUMBER 
*/


-----------------------------------------------------------------------------------
/*
--GNC_UNITPRICE(CO, CUST, VENDOR, STORE, ITEMCODE) 

DECLARE @COMPANYID CHAR(2) = 'SB' 
DECLARE @CUSTOMERID VARCHAR(38) = '{0a0f0783-db8b-4b59-ac48-4f5ec84b43b8}' 
DECLARE @VENDORNUMBER CHAR(12) = '801560001'
DECLARE @STORENUMBER VARCHAR(50) = '1' 
--DECLARE @ITEMCODE CHAR(20) = '001675.010.1' 
DECLARE @ITEMCODE CHAR(20) = '16750101' 

DECLARE @UNITPRICE VARCHAR(20)

SELECT TOP 1 @UNITPRICE = PSD.LANDEDPRICE - PSD.HANDLINGCHARGE - PSD.OTHERCHARGE - PSD.FREIGHTCHARGE
FROM IDMASTER CUST (NOLOCK) 
LEFT JOIN IDRELATIONSHIPLINKS LCUST (NOLOCK) ON LCUST.R_IDMASTER = CUST.ROWID 
		AND LCUST.IDMASTERTYPE = '01'  AND LCUST.IDMEMBERTYPE = '02' 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = LCUST.R_IDMEMBER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
JOIN GNC_EDI_TRANSLATION GET (NOLOCK) ON ISNULL(GET.VENDOR, '') = @VENDORNUMBER
JOIN IDMASTER WH (NOLOCK) ON WH.IDENTITYID = GET.WAREHOUSEID
--JOIN IMITEM ITM (NOLOCK) ON ITM.ITEMCODE = @ITEMCODE AND ITM.R_WAREHOUSE = WH.ROWID
--REMOVE THE PERIODS AND ADD THE LEADING ZEROS UNTIL RURAL KING CLEANS UP THEIR DATA:
JOIN IMITEM ITM (NOLOCK) ON REPLACE(ITM.ITEMCODE,'.','') = RIGHT('00'+REPLACE(TRIM(@ITEMCODE),'.',''),10) AND ITM.R_WAREHOUSE = WH.ROWID
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.ROWID AND SZ.R_SHIPPER = WH.ROWID
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE)
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = ITM.ROWID AND PSD.EXPIRATIONDATE >= GETDATE()
WHERE CONS.COMPANYID = @COMPANYID 
AND CUST.ROWID = CAST(@CUSTOMERID AS UNIQUEIDENTIFIER)
AND RIGHT('0000'+ICONS.USERDEFINEDREFERENCE_2,4) = RIGHT('0000'+@STORENUMBER,4) 

SELECT @UNITPRICE AS UNITPRICE
*/


-----------------------------------------------------------------------------------
/*
--GNC_ITEM_ROWID(VENDOR,ITEMCODE) 

DECLARE @VENDORNUMBER CHAR(12) = '801560001'
--DECLARE @ITEMCODE CHAR(20) = '001675.010.1' 
DECLARE @ITEMCODE CHAR(20) = '16750101' 

DECLARE @ITEM_ROWID UNIQUEIDENTIFIER 

SELECT TOP 1 @ITEM_ROWID = ITM.ROWID
FROM IMITEM ITM (NOLOCK)
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE
JOIN GNC_EDI_TRANSLATION EDI (NOLOCK) ON EDI.VENDOR = @VENDORNUMBER
--REMOVE THE PERIODS AND ADD THE LEADING ZEROS UNTIL RURAL KING CLEANS UP THEIR DATA:
WHERE REPLACE(ITM.ITEMCODE,'.','') = RIGHT('00'+REPLACE(TRIM(@ITEMCODE),'.',''),10) 
AND EDI.WAREHOUSEID = WH.IDENTITYID

SELECT @ITEM_ROWID AS ITEM_ROWID
*/


-----------------------------------------------------------------------------------
/*
--GNC_WAREHOUSE_ROWID(VENDOR) 

DECLARE @VENDORNUMBER CHAR(12) = '999990001' 

DECLARE @WAREHOUSE_ROWID UNIQUEIDENTIFIER

SELECT @WAREHOUSE_ROWID = WH.ROWID
FROM IDMASTER WH (NOLOCK)
JOIN GNC_EDI_TRANSLATION EDI (NOLOCK) ON EDI.WAREHOUSEID = WH.IDENTITYID
WHERE @VENDORNUMBER = EDI.VENDOR 

SELECT @WAREHOUSE_ROWID AS WAREHOUSE_ROWID 
*/


-----------------------------------------------------------------------------------
/*
--GNC_CONSIGNEE_ROWID(CO,CUST,STORE) 

DECLARE @COMPANYID CHAR(2) = 'SB' 
DECLARE @CUSTOMERID VARCHAR(38) = '{0a0f0783-db8b-4b59-ac48-4f5ec84b43b8}' 
DECLARE @STORENUMBER VARCHAR(50) = '99' 

DECLARE @CONSIGNEEROWID VARCHAR(38)--UNIQUEIDENTIFIER 

SELECT 
TOP 1 @CONSIGNEEROWID = CONS.ROWID 
FROM IDMASTER CUST (NOLOCK) 
LEFT JOIN IDRELATIONSHIPLINKS LCUST (NOLOCK) ON LCUST.R_IDMASTER = CUST.ROWID 
		AND LCUST.IDMASTERTYPE = '01'  AND LCUST.IDMEMBERTYPE = '02' 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = LCUST.R_IDMEMBER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
WHERE CONS.COMPANYID = @COMPANYID 
AND CUST.ROWID = CAST(@CUSTOMERID AS UNIQUEIDENTIFIER)
AND RIGHT('0000'+ICONS.USERDEFINEDREFERENCE_2,4) = RIGHT('0000'+@STORENUMBER,4) 

SELECT @CONSIGNEEROWID AS CONSIGNEEROWID
*/


-----------------------------------------------------------------------------------

/*--GNC_SALESREP_ROWID(CO,CUST,STORE) 

DECLARE @COMPANYID CHAR(2) = 'SB' 
DECLARE @CUSTOMERID VARCHAR(38) = '{0a0f0783-db8b-4b59-ac48-4f5ec84b43b8}' 
DECLARE @STORENUMBER VARCHAR(50) = '99' 

DECLARE @SALESREP_ROWID VARCHAR(38)--UNIQUEIDENTIFIER 

SELECT 
TOP 1 @SALESREP_ROWID = PART.ROWID 

FROM IDMASTER CUST (NOLOCK) 
LEFT JOIN IDRELATIONSHIPLINKS LCUST (NOLOCK) ON LCUST.R_IDMASTER = CUST.ROWID 
		AND LCUST.IDMASTERTYPE = '01'  AND LCUST.IDMEMBERTYPE = '02' 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = LCUST.R_IDMEMBER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = CONS.ROWID 
JOIN IDMASTER PART (NOLOCK) ON PART.ROWID = ICONS.R_PARTICIPANT 

WHERE CONS.COMPANYID = @COMPANYID 
AND CUST.ROWID = CAST(@CUSTOMERID AS UNIQUEIDENTIFIER)
AND RIGHT('0000'+ICONS.USERDEFINEDREFERENCE_2,4) = RIGHT('0000'+@STORENUMBER,4) 

SELECT @SALESREP_ROWID AS SALESREP_ROWID 
*/


-----------------------------------------------------------------------------------
/*
--GNC_TERMS_ROWID(CO,CUST) 

DECLARE @COMPANYID CHAR(2) = 'SB' 
DECLARE @CUSTOMERID VARCHAR(38) = '{0a0f0783-db8b-4b59-ac48-4f5ec84b43b8}' 

DECLARE @TERMSROWID VARCHAR(38)--UNIQUEIDENTIFIER 


SELECT TOP 1 @TERMSROWID = IDTERMS.ROWID 
FROM IDMASTER CUST (NOLOCK) 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
JOIN IDTERMS (NOLOCK) ON IDTERMS.ROWID = ICUST.R_TERMS 
WHERE CUST.COMPANYID = @COMPANYID 
AND CUST.ROWID = CAST(@CUSTOMERID AS UNIQUEIDENTIFIER)

SELECT @TERMSROWID AS TERMSROWID 
*/


-----------------------------------------------------------------------------------
/*
--GNC_RECORDTYPE(BEG01NEWCHANGE) 

DECLARE @BEG01NEWCHANGE CHAR(2) = '00'

DECLARE @PORECORDTYPE CHAR(1)
SELECT TOP 1 @PORECORDTYPE = IIF(@BEG01NEWCHANGE = '00', 'I', 'E')
SELECT @PORECORDTYPE AS PORECORDTYPE
*/


-----------------------------------------------------------------------------------
/*
--GNC_GROUPNUMBER(VENDOR) 

DECLARE @VENDORNUMBER CHAR(12) = '999990001' 

DECLARE @GROUPNUMBER CHAR(10) 

SELECT @GROUPNUMBER = EDI.IDGROUP
FROM GNC_EDI_TRANSLATION EDI (NOLOCK)
WHERE @VENDORNUMBER = EDI.VENDOR

SELECT @GROUPNUMBER AS GROUPNUMBER 
*/
