--Determine if EDI transaction is against a Legacy account or not:

--List of EDI Transactions:
SELECT 
OH.EDITRANSMITFLAG, 
OH.ROWID,
OH.TRANSACTIONNUMBER, 
CUST.IDENTITYID AS CUSTOMERID, 
CUST.NAME AS CUSTOMERNAME, 
ICUST.USERDEFINEDCODE_9 AS EDI_CUST, 
IIF(OH.USERDEFINEDREFERENCE_10 IS NOT NULL, VEND.NAME, 'NON-EDI') AS EDI_TRADINGPARTNER,
VEND.IDENTITYID AS VENDORID, 
VEND.IDSUBGROUP AS LEGACYCHECK 
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)--VEND.ROWID = OH.USERDEFINEDREFERENCE_10 
WHERE OH.RECORDTYPE = 'Z'
AND VEND.IDENTITYID = 'EDI35'
ORDER BY 
VEND.IDSUBGROUP, 
VEND.IDENTITYID, 
ICUST.USERDEFINEDCODE_9, 
CUST.IDENTITYID, 
OH.TRANSACTIONNUMBER

--List of EDI Trading Partners:
SELECT 
CUST.IDENTITYID AS CUSTOMERID, 
CUST.NAME AS CUSTOMERNAME, 
ICUST.USERDEFINEDCODE_9 AS EDI_CUST, 
VEND.IDENTITYID AS VENDORID, 
VEND.IDSUBGROUP AS LEGACYCHECK 
FROM IDMASTER CUST (NOLOCK)
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID
JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)
ORDER BY 
VEND.IDSUBGROUP, 
VEND.IDENTITYID, 
ICUST.USERDEFINEDCODE_9, 
CUST.IDENTITYID
