--EDI remove UDR10 values from nonEDI Customer
--This is what I did to remove the UDR10 values from SiteOne Orders that were created before it was setup as an EDI Customer.
--I don't want these orders to have this field assigned to specify that they were processed manually at the time.


--OH.USERDEFINEDREFERENCE_5 IS CUSTOMERGROUP STORED IN THE ORDER
--OH.USERDEFINEDREFERENCE_10 IS VENDOR ROWID STORED IN THE ORDER

--Before Update:
SELECT OH.USERDEFINEDREFERENCE_10, OH.USERDEFINEDREFERENCE_5, OH.EDITRANSMITFLAG, CUST.IDENTITYID, OH.RECORDTYPE, OH.STAGE, ICUST.USERDEFINEDCODE_9
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
WHERE OH.USERDEFINEDREFERENCE_10 IS NOT NULL
AND ISNULL(ICUST.USERDEFINEDCODE_9,'N') != 'Y'
AND CUST.IDGROUP = '43'

BEGIN TRAN
--Update script to remove UDR10:
UPDATE OMTRANSACTIONHEADER 
SET USERDEFINEDREFERENCE_10 = NULL
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
WHERE OH.USERDEFINEDREFERENCE_10 IS NOT NULL
AND ISNULL(ICUST.USERDEFINEDCODE_9,'N') != 'Y'
AND CUST.IDGROUP = '43'

--After Update:
SELECT OH.USERDEFINEDREFERENCE_10, OH.USERDEFINEDREFERENCE_5, OH.EDITRANSMITFLAG, CUST.IDENTITYID, OH.RECORDTYPE, OH.STAGE, ICUST.USERDEFINEDCODE_9
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
WHERE OH.USERDEFINEDREFERENCE_10 IS NOT NULL
AND ISNULL(ICUST.USERDEFINEDCODE_9,'N') != 'Y'
AND CUST.IDGROUP = '43'

--Task Agent script:
SELECT 
	OH.TRANSACTIONNUMBER, 
	OH.STAGE, 
	OH.RECORDTYPE, CUST.IDENTITYID AS CUSTOMERID, CUST.NAME AS CUSTOMERNAME, CUST.IDGROUP AS CUST_IDGROUP, 
	OH.USERDEFINEDREFERENCE_5 AS BAD_UDR5, CUST.IDGROUP AS NEW_UDR5, 
	OH.USERDEFINEDREFERENCE_10 AS BAD_UDR10, NEWVEND.ROWID AS NEW_UDR10, 
	VEND.IDENTITYID AS BAD_VENDID, NEWVEND.IDENTITYID AS NEW_VENDID 
FROM OMTRANSACTIONHEADER OH (NOLOCK)  
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = CUST.ROWID 
LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = OH.USERDEFINEDREFERENCE_10 
LEFT JOIN IDMASTER NEWVEND (NOLOCK) ON NEWVEND.IDENTITYID = 'EDI'+CUST.IDGROUP AND ISNULL(ICUST.USERDEFINEDCODE_9,'N') = 'Y' 
WHERE (	
		ISNULL(VEND.IDENTITYID,'') != ISNULL(NEWVEND.IDENTITYID,'')
		OR 
		ISNULL(OH.USERDEFINEDREFERENCE_5,'') <> ISNULL(CUST.IDGROUP,'')
	)
AND OH.RECORDTYPE = 'R' 
AND OH.STAGE != 'L' 

--COMMIT--
ROLLBACK TRAN
