--QUESTION: CAN I REVERSE ENGINEER A RURAL KING ORDER/INVOICE TO GENERATE A SAMPLE 850 DOCUMENT THAT ARGOS IS ASKING FOR?
--select oh.shippingdate, DBO.FN_DATE2YYYYMMDD(OH.SHIPPINGDATE) AS TEST from omtransactionheader oh (nolock)
/*
SELECT 
	OH.TRANSACTIONNUMBER, --OH.PURCHASEORDERNUMBER, 
	--OH.SHIPPINGDATE AS PODATE, ISNULL(OH.USERDEFINEDDATE_19,OH.SHIPPINGDATE) AS SHIPNOTBEFORE, ISNULL(OH.USERDEFINEDDATE_20,OH.SHIPPINGDATE) AS SHIPNOTAFTER, 
	--GET.VENDOR, ICONS.USERDEFINEDREFERENCE_2 AS PO_STORENUMBER, VCUST.CUSTOMERADDRESS_1, VCUST.CUSTOMERADDRESS_2, 
	--VCUST.CUSTOMERCITY, VCUST.CUSTOMERSTATE, VCUST.CUSTOMERZIP, VCUST.CUSTOMERCOUNTRY, OD.LINENUMBER, OD.QUANTITYORDERED, OD.UNITPRICE, PSD.ALTERNATESKU, 
	--LEFT(RIGHT('00'+ISNULL(NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), ''),ITM.ITEMSUPCCODE),12)+SPACE(12),12) AS UPC, DETAIL.LINECOUNT, 
	'ST*850*000000001~BEG*00*NE*'+TRIM(OH.PURCHASEORDERNUMBER)+'**'+DBO.FN_DATE2YYYYMMDD(OH.SHIPPINGDATE)+-- AS BEG, 
	'~DTM*037*'+DBO.FN_DATE2YYYYMMDD(ISNULL(OH.USERDEFINEDDATE_19,OH.SHIPPINGDATE))+-- AS DTM37, 
	'~DTM*038*'+DBO.FN_DATE2YYYYMMDD(ISNULL(OH.USERDEFINEDDATE_20,OH.SHIPPINGDATE))+-- AS DTM38, 
	'~N1*SF*GREENLEAF NURSERY COMPANY*92*'+TRIM(GET.VENDOR)+-- AS N1SF,	--PO_VENDOR
	'~N1*ST*'+TRIM(CONS.NAME)+'*92*'+ICONS.USERDEFINEDREFERENCE_2+'~'+-- AS N1ST,	--PO_STORENUMBER
	'N3*'+ISNULL(TRIM(VCUST.CUSTOMERADDRESS_1),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERADDRESS_2),'')+'~'+-- AS N3, 
	'N4*'+ISNULL(TRIM(VCUST.CUSTOMERCITY),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERSTATE),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERZIP),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERCOUNTRY),'')+'~' AS HDR,-- AS N4, 
	'PO1*'+CAST(OD.LINENUMBER AS VARCHAR)+'*'+CAST(OD.QUANTITYORDERED AS VARCHAR)+'*EA*'+CAST(OD.UNITPRICE AS VARCHAR)+'**IN*'+PSD.ALTERNATESKU+'***UP*'+
	LEFT(RIGHT('00'+ISNULL(NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), ''),ITM.ITEMSUPCCODE),12)+SPACE(12),12) AS DTL,-- AS PO1, 
	'~CTT*'+CAST(DETAIL.LINECOUNT AS VARCHAR)+'~SE*10*000000001~' AS CTT
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER 
JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = ICONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID 
LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 
LEFT JOIN	(	SELECT OD.R_TRANSACTIONHEADER, COUNT(*) AS LINECOUNT 
				FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
				WHERE ISNULL(OD.QUANTITYORDERED,0) > 0 
				GROUP BY OD.R_TRANSACTIONHEADER 
			) AS DETAIL ON DETAIL.R_TRANSACTIONHEADER = OH.ROWID 
JOIN GNC_EDI_TRANSLATION GET (NOLOCK) ON GET.WAREHOUSEID = WH.IDENTITYID AND GET.IDGROUP = CUST.IDGROUP
WHERE CUST.IDGROUP = '535' 
AND ISNULL(OD.QUANTITYORDERED,0) > 0 
ORDER BY OH.TRANSACTIONNUMBER, OD.LINENUMBER ASC 
*/
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------
DECLARE @ROWID UNIQUEIDENTIFIER	
SET @ROWID= (	SELECT OH.ROWID FROM OMTRANSACTIONHEADER OH (NOLOCK) 
				JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
				WHERE CUST.IDGROUP = '535' 
				AND OH.TRANSACTIONNUMBER = '10-31351'
			)	

SELECT OUTPUT 
FROM ( 
		--[HEADER]--
			SELECT 
				OH.TRANSACTIONNUMBER, 0 AS LINENUMBER,
				'ST*850*000000001~BEG*00*NE*'+TRIM(OH.PURCHASEORDERNUMBER)+'**'+DBO.FN_DATE2YYYYMMDD(OH.SHIPPINGDATE)+'~' 
				--'CUR*BY*USD~REF*IA*28897~'
				+'DTM*037*'+DBO.FN_DATE2YYYYMMDD(ISNULL(OH.USERDEFINEDDATE_19,OH.SHIPPINGDATE))+'~'	--SHIPNOTBEFORE 
				+'DTM*038*'+DBO.FN_DATE2YYYYMMDD(ISNULL(OH.USERDEFINEDDATE_20,OH.SHIPPINGDATE))+'~'	--SHIPNOTAFTER 
				+'N1*SF*GREENLEAF NURSERY COMPANY*92*'+TRIM(GET.VENDOR)+'~'							--PO_VENDOR 
				+'N1*ST*'+TRIM(CONS.NAME)+'*92*'+ICONS.USERDEFINEDREFERENCE_2+'~'					--PO_STORENUMBER 
				+'N3*'+ISNULL(TRIM(VCUST.CUSTOMERADDRESS_1),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERADDRESS_2),'')+'~' 
				+'N4*'+ISNULL(TRIM(VCUST.CUSTOMERCITY),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERSTATE),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERZIP),'')+'*'+ISNULL(TRIM(VCUST.CUSTOMERCOUNTRY),'')+'~'
				AS OUTPUT
			FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER 
			JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
			JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
			JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			JOIN GNC_EDI_TRANSLATION GET (NOLOCK) ON GET.WAREHOUSEID = WH.IDENTITYID AND GET.IDGROUP = CUST.IDGROUP
			WHERE CUST.IDGROUP = '535' AND OH.ROWID = @ROWID 
		UNION
		--[DETAIL]--
			SELECT 
				OH.TRANSACTIONNUMBER, OD.LINENUMBER, 
				'PO1*'+CAST(OD.LINENUMBER AS VARCHAR)+'*'+CAST(CAST(OD.QUANTITYORDERED AS INT) AS VARCHAR)+'*EA*'+CAST(CAST(OD.UNITPRICE AS DECIMAL(15,2)) AS VARCHAR)+'**IN*'+PSD.ALTERNATESKU+ 
				'***UP*'+LEFT(RIGHT('00'+ISNULL(NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), ''),ITM.ITEMSUPCCODE),12)+SPACE(12),12)+'~'
				--+'PID*F****'+ITM.DESCRIPTION_1+'~'
				AS OUTPUT
			FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
			JOIN VW_IDCUSTOMERVIEW VCUST (NOLOCK) ON VCUST.CUSTOMERMASTERROWID = OH.R_CUSTOMER 
			JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
			JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER
			JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER 
			JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER 
			LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = ICONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID 
			LEFT JOIN IMPRICESCHEDULEHEADER PSH (NOLOCK) ON PSH.ROWID = ISNULL(SZ.R_PRICESCHEDULE, ICONS.R_PRICESCHEDULE) 
			LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = PSH.ROWID AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE() 
			LEFT JOIN	(	SELECT OD.R_TRANSACTIONHEADER, COUNT(*) AS LINECOUNT 
							FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
							WHERE ISNULL(OD.QUANTITYSHIPPED,0) > 0 
							GROUP BY OD.R_TRANSACTIONHEADER 
						) AS DETAIL ON DETAIL.R_TRANSACTIONHEADER = OH.ROWID 
			JOIN GNC_EDI_TRANSLATION GET (NOLOCK) ON GET.WAREHOUSEID = WH.IDENTITYID AND GET.IDGROUP = CUST.IDGROUP
			WHERE CUST.IDGROUP = '535' AND OH.ROWID = @ROWID  
			AND ISNULL(OD.QUANTITYORDERED,0) > 0 
		UNION
		--[CTT]--
			SELECT 
				OH.TRANSACTIONNUMBER, DETAIL.LINECOUNT+1 AS LINENUMBER, 
				'CTT*'+CAST(DETAIL.LINECOUNT AS VARCHAR)+'~SE*10*000000001~'
				AS OUTPUT
			FROM OMTRANSACTIONHEADER OH (NOLOCK) 
			JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
			LEFT JOIN	(	SELECT OD.R_TRANSACTIONHEADER, COUNT(*) AS LINECOUNT 
							FROM OMTRANSACTIONDETAIL OD (NOLOCK) 
							WHERE ISNULL(OD.QUANTITYORDERED,0) > 0 
							GROUP BY OD.R_TRANSACTIONHEADER 
						) AS DETAIL ON DETAIL.R_TRANSACTIONHEADER = OH.ROWID 
			WHERE CUST.IDGROUP = '535'  AND OH.ROWID = @ROWID 
) U
ORDER BY U.TRANSACTIONNUMBER, U.LINENUMBER
