--EDI_STALLED RECORDS:	--sa @Rgos2020 
SELECT *
FROM (
SELECT	--810 STALLED DOCUMENTS: 
	'810' AS DOCTYPE, oh.USERDEFINEDCODE_10 AS SuppressEDIFlag, 
	(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) AS VENDOR, 
	ISNULL(	(SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
			 WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
			) ,'X12') AS EDIWHICH, 
	OH.TRANSACTIONNUMBER, 
	OH.EDITRANSMITFLAG, 
	OH.RECORDTYPE, 
	OH.STAGE, OH.USERDEFINEDCODE_2 AS STEP, 
	OH.INVENTORYREVIEW, 
	OH.INVOICEDATE, oh.COMMITDATE, 
	OH.LASTUPDATEDATETIME, 
	OH.PURCHASEORDERNUMBER, 
	OH.ROWID 
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
WHERE OH.TRANSACTIONTYPE = 'I' --AND OH.EDITRANSMITFLAG = 'Y' 
AND (	SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK) 
		WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
		LIKE 'EDI%' 
--810 SPECIFIC LOGIC: 
AND OH.RECORDTYPE = 'Z' 

UNION ALL

SELECT	--855 STALLED DOCUMENTS: 
	'855' AS DOCTYPE, oh.USERDEFINEDCODE_10 AS SuppressEDIFlag, 
	(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) AS VENDOR, 
	ISNULL(	(SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
			 WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
			) ,'X12') AS EDIWHICH, 
	OH.TRANSACTIONNUMBER, 
	OH.EDITRANSMITFLAG, 
	OH.RECORDTYPE, 
	OH.STAGE, OH.USERDEFINEDCODE_2 AS STEP, 
	OH.INVENTORYREVIEW, 
	OH.INVOICEDATE, oh.COMMITDATE, 
	OH.LASTUPDATEDATETIME, 
	OH.PURCHASEORDERNUMBER, 
	OH.ROWID  
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
WHERE OH.TRANSACTIONTYPE = 'I' --AND OH.EDITRANSMITFLAG = 'Y' 
AND (	SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK) 
		WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
		LIKE 'EDI%' 
--855 SPECIFIC LOGIC: 
AND (  /*OH.STAGE = 'L' OR */ --UNIQUE EDI_STALLED RECORDS LOGIC: [IF EDITRANSMITFLAG = 'N' THEN IT WAS NEVER SENT TO LOWES AND CANCEL DOESN'T NEED SENT EITHER]
		(  OH.STAGE IN ('A','S','C') AND ISNULL(OH.INVENTORYREVIEW,'') <> 'Y' ) 
	) 
	AND OH.R_CUSTOMER = (	SELECT R_IDENTITY 
							FROM IDCUSTOMER ICUST (NOLOCK) 
							WHERE ICUST.USERDEFINEDCODE_7 = 'Y') 
) U
WHERE EDITRANSMITFLAG <> 'Y'	-->THESE RECORDS HAVE NOT TRANSMITTED...THEY ARE STALLED
--WHERE EDITRANSMITFLAG = 'Y'	-->THESE RECORDS HAVE BEEN SENT
ORDER BY 
LASTUPDATEDATETIME DESC, 
INVOICEDATE DESC, 
DOCTYPE DESC, 
PURCHASEORDERNUMBER 
