--EDI_TA Queries:	--sa @Rgos2020 
------------------------------------------------------------------------------------------------------------ 
--TA QUERY Event: EDI Order Committed as Invoiced, Trigger: 810 
--DELETED.RECORDTYPE <> 'Z' AND	
SELECT (SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) )  AS VENDOR, INSERTED.TRANSACTIONNUMBER, INSERTED.TRANSACTIONTYPE, INSERTED.TRANSACTIONDATE, INSERTED.INVOICEDATE, INSERTED.RECORDTYPE, inserted.EDITRANSMITFLAG, 
inserted.printinvoice, INSERTED.SENDEMAIL, INSERTED.ROWID, INSERTED.USERDEFINEDREFERENCE_10, inserted.PURCHASEORDERNUMBER 
FROM OMTRANSACTIONHEADER INSERTED (NOLOCK) WHERE 
INSERTED.RECORDTYPE = 'Z' 		--ENABLED FOR TA SCRIPT 
--INSERTED.RECORDTYPE = 'R' 	--ENABLED FOR FINDING ORDERS TO TRIGGER 
--AND INSERTED.TRANSACTIONTYPE= 'I' 
AND (  INSERTED.R_CUSTOMER = 
       (  SELECT ROWID FROM IDMASTER CUST (NOLOCK) 
          WHERE CUST.ROWID = INSERTED.R_CUSTOMER 
          AND CUST.IDGROUP IN ('35','90') -->SOME CUSTOMERS REQUIRE INVOICE & CM/DM 810 DOCUMENTS
       )
    OR INSERTED.TRANSACTIONTYPE= 'I'  -->EVERYONE ELSE ONLY WANTS INVOICE 810 DOCUMENTS
    )
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
AND (  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	)  LIKE 'EDI%'
AND (  SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	)  = 'LEGACY'
AND INSERTED.R_CUSTOMER = 
    (  SELECT R_IDENTITY FROM IDCUSTOMER ICUST (NOLOCK) 
       WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER
       AND ISNULL(ICUST.USERDEFINEDCODE_9,'') = 'Y'--EDI CUSTOMERS ONLY
    )
--and inserted.EDITRANSMITFLAG <> 'Y' 
and CAST (inserted.invoicedate AS DATE) >'07-04-2024'-- >= '01-27-2022'-->= '09-02-2021' 
ORDER BY INSERTED.INVOICEDATE 
------------------------------------------------------------------------------------------------------------ 
--TA QUERY Event: ReverseEDI Order Stage changed, Trigger: 855 
--DELETED.STAGE <> INSERTED.STAGE AND 
SELECT inserted.userdefinedreference_5 as ohgroup, INSERTED.TRANSACTIONNUMBER, INSERTED.PURCHASEORDERNUMBER, INSERTED.LASTUPDATEDATETIME, INSERTED.EDITRANSMITFLAG, INSERTED.ROWID, INSERTED.USERDEFINEDREFERENCE_10, INSERTED.STAGE, INSERTED.INVENTORYREVIEW 
FROM OMTRANSACTIONHEADER INSERTED (NOLOCK) WHERE 
--(  (DELETED.STAGE != 'N' AND INSERTED.STAGE = 'L' ) OR 
(  INSERTED.STAGE = 'L'  OR 
   (  INSERTED.STAGE IN ('A','S','C') AND 
      ISNULL(INSERTED.INVENTORYREVIEW,'') <> 'Y' 
   ) 
) 
AND INSERTED.TRANSACTIONTYPE= 'I' 
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
AND (  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	)  LIKE 'EDI%' 
AND (  SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	)  = 'LEGACY'
AND INSERTED.R_CUSTOMER = 
    (  SELECT R_IDENTITY FROM IDCUSTOMER ICUST (NOLOCK) 
       WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER
       AND ISNULL(ICUST.USERDEFINEDCODE_7,'') = 'Y'--WORK ORDER REQUIRED CUSTOMERS ONLY
    ) 
AND INSERTED.R_CUSTOMER = 
    (  SELECT R_IDENTITY FROM IDCUSTOMER ICUST (NOLOCK) 
       WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER
       AND ISNULL(ICUST.USERDEFINEDCODE_9,'') = 'Y'--EDI CUSTOMERS ONLY
    )
--and inserted.EDITRANSMITFLAG <> 'Y' 
and CAST (inserted.LASTUPDATEDATETIME AS DATE) >'07-04-2024'-- >= '01-27-2022'-->= '09-02-2021' 
order by inserted.PURCHASEORDERNUMBER 
/* 
--------------------------------------------
--EDI_TA FILENAME LOGIC (added LEGACY logic inside this code if filenames get confused...but I think it only applies to ASCII naming so maybe not)
--------------------------------------------
-- Declare Current DateTimeStamp
DECLARE @DATETIMESTAMP VARCHAR(15)
SET @DATETIMESTAMP =	(	DATENAME(yyyy, GETDATE()) + 
							RIGHT('00' + TRIM(STR(DATEPART(mm, GETDATE()))), 2) + 
							DATENAME(dd, GETDATE()) + DATENAME(hh, GETDATE()) + 
							DATENAME(n, GETDATE()) + DATENAME(ss, GETDATE()) 
						)
SELECT * 
FROM (	SELECT 
		(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER)) AS VENDOR, 
		--(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = OH.USERDEFINEDREFERENCE_10) AS VENDOR, 
		TRANSACTIONNUMBER, 
		--RECORDTYPE, 
		--(SELECT IDGROUP FROM IDMASTER WHERE ROWID = R_CUSTOMER) AS IDGROUP, 
		--(SELECT USERDEFINEDCODE_7 FROM IDCUSTOMER WHERE R_IDENTITY = R_CUSTOMER) AS WO#REQ, 
		--OH.PURCHASEORDERNUMBER, 
		--IIF(OH.STAGE = 'L', 'CA', IIF(OH.EDITRANSMITFLAG = 'Y', 'CH', 'PO')) AS TRTYPE, 
		(	SELECT IIF(USERDEFINEDCODE_7 = 'Y' AND OH.RECORDTYPE <> 'Z', 
					'EDI855_' + (SELECT TRIM(IDGROUP) FROM IDMASTER WHERE ROWID = R_CUSTOMER) + '_' + 
								ISNULL(OH.PURCHASEORDERNUMBER,'?????') + 
								IIF(OH.STAGE='L', 'CA', IIF(OH.EDITRANSMITFLAG = 'Y', 'CH', 'PO')) + 
								'_' + @DATETIMESTAMP, 
					'EDI810_' + @DATETIMESTAMP) 
			FROM IDCUSTOMER WHERE R_IDENTITY = R_CUSTOMER 
		)	AS FNAME 
		FROM OMTRANSACTIONHEADER OH 
		WHERE OH.USERDEFINEDREFERENCE_10 IS NOT NULL 
		AND (  SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
			   WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
			) = 'LEGACY'

	 ) X 
ORDER BY VENDOR, TRANSACTIONNUMBER, FNAME 
*/