-------------------------------------------------------------------------------------------------------------------
-- This is the old script that they had loaded
-------------------------------------------------------------------------------------------------------------------
/*
DECLARE @HEADERROWID UNIQUEIDENTIFIER
DECLARE @ROWID UNIQUEIDENTIFIER
SELECT @HEADERROWID = ROWID FROM OMTRANSACTIONHEADER WHERE TRANSACTIONNUMBER LIKE '20-11493'
SET @ROWID = @HEADERROWID
DECLARE @HEADERROWID UNIQUEIDENTIFIER
DECLARE @ROWID UNIQUEIDENTIFIER

SELECT @HEADERROWID = ROWID FROM OMTRANSACTIONHEADER WHERE TRANSACTIONNUMBER LIKE '20-11493'
SET @ROWID = @HEADERROWID

SELECT 'HDR' as RecType,
RTRIM(M.IDGROUP) as IDGroup,
FORMAT(INVOICEDATE ,'yyyyMMdd')as INVDT,
RTRIM(TRANSACTIONNUMBER) as INVNO,
FORMAT(TRANSACTIONDATE ,'yyyyMMdd')as PODATE,
RTRIM(PURCHASEORDERNUMBER) as PO,
RTRIM(C.USERDEFINEDREFERENCE_2) as STORE,
RTRIM(A.CITY) AS CITY,
RTRIM(M.IDENTITYID) NAME,
RTRIM(A.STATE) AS STATE,
RTRIM(A.ZIP) AS ZIP,
RTRIM(SHIPPER.IDENTITYID) BRPL,
RTRIM(TRANSACTIONNUMBER) as ORDNO,
'' as LOADNO,
ISNULL(SUM(D.HANDLINGCHARGEPERITEM),0) HANDCH,
ISNULL(SUM(D.FREIGHTRATEPERITEM ),0) FRTCH,
ISNULL(SUM(D.UNITPRICE*(1-(D.DISCOUNTPERCENT/100))),0) TOTAMT
FROM OMTRANSACTIONDETAIL D
LEFT JOIN OMTRANSACTIONHEADER H on D.R_TRANSACTIONHEADER=H.ROWID
LEFT JOIN IDMASTER M ON M.ROWID = R_CUSTOMER
LEFT JOIN IDADDRESS A ON R_IDENTITY = M.ROWID
LEFT JOIN IDMASTER SHIPPER ON SHIPPER .ROWID = R_FMSHIPPER
LEFT JOIN IDCONSIGNEE C ON C.ROWID=R_CONSIGNEE
WHERE H.ROWID=@ROWID
GROUP BY M.IDGROUP,INVOICEDATE,PURCHASEORDERNUMBER,TRANSACTIONDATE,TRANSACTIONNUMBER,C.USERDEFINEDREFERENCE_2,A.CITY,M.IDENTITYID,A.STATE,A.ZIP,SHIPPER.IDENTITYID

SELECT  
'DTL' as RecType,
MAX(ISNULL(M.IDGROUP,'')) as IDGroup,
MAX(ISNULL(H.TRANSACTIONNUMBER,'')) as INVNO,
MAX(ISNULL(H.PURCHASEORDERNUMBER,''))as PO,
ISNULL(PSD.ALTERNATESKU,'') AS SKUCODE,
MAX(CONVERT(VARCHAR(10),PSD.COMMENT)) AS UPCNO,
MAX(ISNULL(D.UNITPRICE,0) *(1-(ISNULL(D.DISCOUNTPERCENT,0)/100))) AS PRICE,
SUM(ISNULL(D.QUANTITYSHIPPED,0)) AS QTYSH,
MAX(ISNULL(ISNULL(I.REFERENCE_1,'') + ISNULL(I.USERDEFINEDREFERENCE_1,''),'')) AS PLNAME,
MAX(ISNULL(H.TRANSACTIONNUMBER,''))as ORDNO,
MAX(ISNULL(D.HANDLINGCHARGEPERITEM,0)) as HANDCH,
MAX(ISNULL(D.FREIGHTRATEPERITEM ,0)) as FRTCH
FROM OMTRANSACTIONDETAIL D
LEFT JOIN OMTRANSACTIONHEADER H on D.R_TRANSACTIONHEADER=H.ROWID
LEFT JOIN IMITEM I ON I.ROWID = D.R_ITEM
LEFT JOIN IDMASTER M ON M.ROWID = H.R_CUSTOMER
LEFT JOIN IDCUSTOMER CUST ON CUST.R_IDENTITY = H.R_CUSTOMER
LEFT JOIN IDMASTER WH ON WH.ROWID = D.R_WAREHOUSE
LEFT JOIN IDCONSIGNEE C ON C.R_IDENTITY = H.R_SHIPPER
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ ON SZ.R_CONSIGNEE = C.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID
LEFT JOIN IMPRICESCHEDULEDETAIL PSD ON PSD.R_PRICESCHEDULEHEADER = ISNULL(SZ.R_PRICESCHEDULE, C.R_PRICESCHEDULE) 
AND PSD.R_ITEM = D.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
WHERE D.R_TRANSACTIONHEADER = @HeaderRowID AND ISNULL(CUST.USERDEFINEDCODE_3,'') ='Y'
GROUP BY PSD.ALTERNATESKU

UNION ALL

SELECT  'DTL' as RecType,
ISNULL(M.IDGROUP,'') as IDGroup,
TRANSACTIONNUMBER as INVNO,
PURCHASEORDERNUMBER as PO,
PSD.ALTERNATESKU AS SKUCODE,
CONVERT(VARCHAR(10),PSD.COMMENT) AS UPCNO,
D.UNITPRICE *(1-(D.DISCOUNTPERCENT/100)) PRICE,
D.QUANTITYSHIPPED QTYSH,
ISNULL(ISNULL(I.REFERENCE_1,'') + ISNULL(I.USERDEFINEDREFERENCE_1,''),'') PLNAME,
TRANSACTIONNUMBER as ORDNO,
ISNULL(D.HANDLINGCHARGEPERITEM,0) HANDCH,
ISNULL(D.FREIGHTRATEPERITEM ,0) FRTCH
FROM OMTRANSACTIONDETAIL D
LEFT JOIN OMTRANSACTIONHEADER H on D.R_TRANSACTIONHEADER=H.ROWID
LEFT JOIN IDMASTER M ON M.ROWID = H.R_CUSTOMER
LEFT JOIN IMITEM I ON I.ROWID = D.R_ITEM 
LEFT JOIN IDMASTER WH ON WH.ROWID = D.R_WAREHOUSE
LEFT JOIN IDCONSIGNEE C ON C.R_IDENTITY = H.R_SHIPPER
LEFT JOIN IDCONSIGNEESHIPPERZONE SZ ON SZ.R_CONSIGNEE = C.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID
LEFT JOIN IMPRICESCHEDULEDETAIL PSD ON PSD.R_PRICESCHEDULEHEADER = ISNULL(SZ.R_PRICESCHEDULE, C.R_PRICESCHEDULE) AND PSD.R_ITEM = D.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
LEFT JOIN IDCUSTOMER CUST ON CUST.R_IDENTITY = H.R_CUSTOMER
WHERE D.R_TRANSACTIONHEADER = @HeaderRowID AND ISNULL(CUST.USERDEFINEDCODE_3,'') <> 'Y'
*/