DECLARE @ROWID UNIQUEIDENTIFIER
DECLARE @HEADERROWID UNIQUEIDENTIFIER
SET @ROWID=
'23F21E63-E9B7-45A6-A2DC-8DE08B3B1DF6'	--10-92474	rejected: zipcode invalid? 
--'24E79AA3-E96F-4893-AD38-BB34C6128B69'	--40-92730	rejected: zipcode invalid? 
--'7FE902C3-CC70-4B45-8E79-5062C8D93EC9'
--'129AA819-4DB9-4485-8B02-10AA2C85C02F'
--'90676564-B811-4145-B9F4-7B56623F7A8C'--
--'0690A11A-EAE6-4E30-9FCE-18ABB1E018AB'
--'ED96F614-DBAB-4297-99F2-AF0A669EC9D6'	--10-18748-1 SqlException:  The conversion of the varchar value '008776250537' overflowed an int column.
--'029580E2-D220-434C-B244-A328F8726488'	--10-14837	example for first union query
--'6DBA9935-546B-4203-A11F-761D0A56972A'	--20-16564	example for second union query
--'F9AA8A6C-2A3C-44FC-ADA6-07E51C21546E'	--10-15699
--'B3693F0B-3503-4CD2-922B-6B08C593C21C'	--20-15550
--'C9560290-0379-486B-B250-1A6454A7504C'	--Example with HDR in the Reference_5 (SORTNAME) field
SET @HEADERROWID= @ROWID

--GNC_810_V2.1 (NOLOCK)
--HEADER RECORD:
SELECT 'HDR' AS RECTYPE,
--LEFT(ISNULL(CUST.IDGROUP,'')+SPACE(4),4) AS IDGROUP,
LEFT(ISNULL(OH.USERDEFINEDREFERENCE_5,'')+SPACE(4),4) AS IDGROUP,
FORMAT(OH.INVOICEDATE ,'yyyyMMdd') AS INVDT,
LEFT(ISNULL('Z.'+OH.TRANSACTIONNUMBER,'')+SPACE(19),19) AS INVNO,
FORMAT(OH.TRANSACTIONDATE ,'yyyyMMdd') AS PODATE,
LEFT(ISNULL(OH.PURCHASEORDERNUMBER,'')+SPACE(20),20) AS PO,
LEFT(ISNULL(VCONS.CONSIGNEEUSERDEFINEDREFERENCE_2,'')+SPACE(20),20) AS STORE,
LEFT(ISNULL(VCONS.CONSIGNEECITY,'')+SPACE(20),20) AS CITY,
LEFT(ISNULL(VCONS.CONSIGNEENAME,'')+SPACE(40),40) AS NAME,
LEFT(ISNULL(VCONS.CONSIGNEESTATE,'')+SPACE(2),2) AS STATE,
LEFT(ISNULL(VCONS.CONSIGNEEZIP,'')+SPACE(9),9) AS ZIP,
LEFT(ISNULL(WH.IDENTITYID,'')+SPACE(2),2) AS BRPL,
LEFT(ISNULL(OH.TRANSACTIONNUMBER,'')+SPACE(15),15) AS ORDNO,
LEFT(ISNULL(REPLACE(OH.FMTRIPNUMBER,'T',''),'')+SPACE(9),9) AS LOADNO,
STR(IIF(OH.TRANSACTIONTYPE='I',1,-1)*ISNULL(DBO.FN_ORDERVALUE(OH.ROWID,'HANDLING'),0.) + ISNULL(DBO.FN_ORDERVALUE(OH.ROWID,'TAGGING'),0.),14,2) AS HANDCH, 
STR(IIF(OH.TRANSACTIONTYPE='I',1,-1)*ISNULL(DBO.FN_ORDERVALUE(OH.ROWID,'FREIGHT'),0.),14,2) AS FREIGHT,
STR(IIF(OH.TRANSACTIONTYPE='I',1,-1)*ISNULL(DBO.FN_ORDERVALUE(OH.ROWID,'UNITPRICE'),0.),14,2) AS TOTAMT
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER
WHERE OH.ROWID=@ROWID
AND (	SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
		WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	) = 'LEGACY'


--DETAIL RECORD:
SELECT 
	X.RECTYPE, X.IDGROUP, X.INVNO, X.PO, X.SKUCODE, X.ITEMNO, X.UPCNO, X.PRICE, X.QTYSH, X.PLNAME, X.ORDNO, X.HANDCH, X.FRTCH 
FROM (
	SELECT ISNULL(CAST(PSD.ALTERNATESKU AS BIGINT),0) AS SORT,
	'DTL' AS RECTYPE,
--	MAX(LEFT(ISNULL(CUST.IDGROUP,'')+SPACE(4),4)) AS IDGROUP,
	MAX(LEFT(ISNULL(OH.USERDEFINEDREFERENCE_5,'')+SPACE(4),4)) AS IDGROUP,
	MAX(LEFT(ISNULL('Z.'+OH.TRANSACTIONNUMBER,'')+SPACE(19),19)) AS INVNO,
	MAX(LEFT(ISNULL(OH.PURCHASEORDERNUMBER,'')+SPACE(20),20)) AS PO,
	LEFT(ISNULL(PSD.ALTERNATESKU,'')+SPACE(25),25) AS SKUCODE,
	MAX(LEFT(ISNULL(ITM.ITEMCODE,'')+SPACE(12),12)) AS ITEMNO,
	MAX(LEFT(RIGHT('00'+ISNULL(NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), ''),ITM.ITEMSUPCCODE),12)+SPACE(12),12)) AS UPCNO,
	MAX(STR(OD.UNITPRICE,12,2)) AS PRICE,
	STR(SUM(IIF(OH.TRANSACTIONTYPE='I',1,-1)*ISNULL(OD.QUANTITYSHIPPED,0)),7,0) AS QTYSH,
	MAX(LEFT(ISNULL(REPLACE(ISNULL(ITM.REFERENCE_5,''),'HDR', 'H DR') +' '+ ISNULL(ITM.USERDEFINEDREFERENCE_1,''),'')+SPACE(40),40)) AS PLNAME,
	MAX(LEFT(ISNULL(OH.TRANSACTIONNUMBER,'')+SPACE(15),15)) AS ORDNO,
	MAX(STR(ISNULL(OD.HANDLINGCHARGEPERITEM,0) + ISNULL(OD.TAGGINGCHARGEPERITEM,0),12,2)) AS HANDCH,
	MAX(STR(IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0)),12,2)) AS FRTCH
	--MAX(STR(ISNULL(OD.FREIGHTRATEPERITEM ,0),12,2)) AS FRTCH
	FROM OMTRANSACTIONHEADER OH (NOLOCK) 
	LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) on OD.R_TRANSACTIONHEADER=OH.ROWID
	LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
	LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
	LEFT JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OD.R_WAREHOUSE
	LEFT JOIN IDCONSIGNEE CONS (NOLOCK) ON CONS.R_IDENTITY = OH.R_SHIPPER
	LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID
	LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = ISNULL(SZ.R_PRICESCHEDULE, CONS.R_PRICESCHEDULE) 
	AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
	WHERE OD.R_TRANSACTIONHEADER = @HEADERROWID 
	AND ISNULL(ICUST.USERDEFINEDCODE_3,'') ='Y'
	AND (	SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
		WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	) = 'LEGACY'
	GROUP BY PSD.ALTERNATESKU

	UNION ALL

	SELECT  OD.LINENUMBER AS SORT,
	'DTL' AS RECTYPE, 
--	LEFT(ISNULL(CUST.IDGROUP,'')+SPACE(4),4) AS IDGROUP,
	LEFT(ISNULL(OH.USERDEFINEDREFERENCE_5,'')+SPACE(4),4) AS IDGROUP,
	LEFT(ISNULL('Z.'+OH.TRANSACTIONNUMBER,'')+SPACE(19),19) AS INVNO,
	LEFT(ISNULL(OH.PURCHASEORDERNUMBER,'')+SPACE(20),20) AS PO,
	LEFT(ISNULL(PSD.ALTERNATESKU,'')+SPACE(25),25) AS SKUCODE,
	LEFT(ITM.ITEMCODE+SPACE(12),12) AS ITEMNO,
	LEFT(RIGHT('00'+ISNULL(NULLIF(TRIM(REPLACE(SUBSTRING(PSD.COMMENT,1,14),CHAR(13)+CHAR(10), '')), ''),ITM.ITEMSUPCCODE),12)+SPACE(12),12) AS UPCNO,
	STR(OD.UNITPRICE,12,2) AS PRICE,
	STR(IIF(OH.TRANSACTIONTYPE='I',1,-1)*OD.QUANTITYSHIPPED,7,0) AS QTYSH,
	LEFT(ISNULL(REPLACE(ISNULL(ITM.REFERENCE_5,''),'HDR', 'H DR') +' '+ ISNULL(ITM.USERDEFINEDREFERENCE_1,''),'')+SPACE(40),40) AS PLNAME,
	LEFT(ISNULL(OH.TRANSACTIONNUMBER,'')+SPACE(15),15) AS ORDNO,
	STR(ISNULL(OD.HANDLINGCHARGEPERITEM,0) + ISNULL(OD.TAGGINGCHARGEPERITEM,0),12,2) AS HANDCH,
	STR(IIF(ISNULL(DBO.FN_ORDERFREIGHT(OH.ROWID, 'FRTZONE'),0) = 0, 0, ISNULL(OD.FREIGHTRATEPERITEM, 0)),12,2) AS FRTCH
	--STR(ISNULL(OD.FREIGHTRATEPERITEM ,0),12,2) AS FRTCH
	FROM OMTRANSACTIONHEADER OH (NOLOCK) 
	LEFT JOIN OMTRANSACTIONDETAIL OD (NOLOCK) on OD.R_TRANSACTIONHEADER=OH.ROWID
	LEFT JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM
	LEFT JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
	LEFT JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY = OH.R_CUSTOMER
	LEFT JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OD.R_WAREHOUSE
	LEFT JOIN IDCONSIGNEE CONS (NOLOCK) ON CONS.R_IDENTITY = OH.R_SHIPPER
	LEFT JOIN IDCONSIGNEESHIPPERZONE SZ (NOLOCK) ON SZ.R_CONSIGNEE = CONS.R_IDENTITY AND SZ.R_SHIPPER = WH.ROWID
	LEFT JOIN IMPRICESCHEDULEDETAIL PSD (NOLOCK) ON PSD.R_PRICESCHEDULEHEADER = ISNULL(SZ.R_PRICESCHEDULE, CONS.R_PRICESCHEDULE) 
	AND PSD.R_ITEM = OD.R_ITEM AND PSD.EXPIRATIONDATE >= GETDATE()
	WHERE OD.R_TRANSACTIONHEADER = @HEADERROWID 
	AND ISNULL(ICUST.USERDEFINEDCODE_3,'') <> 'Y'
	AND (	SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
		WHERE IDMASTER.ROWID = CAST(OH.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
	) = 'LEGACY'
)X ORDER BY X.SORT


