--NONLEGACYTRIGGERS
--810 TA GENERATE TRIGGER:
--DELETED.RECORDTYPE <> 'Z' AND	
			SELECT RECORDTYPE, TRANSACTIONTYPE, 
			(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS VENDORID, 
			(SELECT IDSUBGROUP FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS LEGACYFLAG 
			FROM OMTRANSACTIONHEADER INSERTED (NOLOCK) WHERE 
INSERTED.RECORDTYPE = 'Z' 
--AND INSERTED.TRANSACTIONTYPE= 'I' 
AND (  INSERTED.R_CUSTOMER = 
       (  SELECT ROWID FROM IDMASTER CUST (NOLOCK) 
          WHERE CUST.ROWID = INSERTED.R_CUSTOMER 
          AND CUST.IDGROUP IN ('35','90') -->SOME CUSTOMERS REQUIRE INVOICE & CM/DM 810 DOCUMENTS
       )
    OR INSERTED.TRANSACTIONTYPE= 'I'  -->EVERYONE ELSE ONLY WANTS INVOICE 810 DOCUMENTS
    )
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
AND 
(  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
   WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
   LIKE 'EDI%'
AND
(  SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
   WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
   = 'LEGACY'

/*
			SELECT RECORDTYPE, TRANSACTIONTYPE, transactionnumber, userdefinedreference_10,
			(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS VENDORID, 
			(SELECT IDSUBGROUP FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS LEGACYFLAG 
			FROM OMTRANSACTIONHEADER INSERTED (NOLOCK) WHERE 

--XM X12 810 logic: 
--DELETED.RECORDTYPE <> 'Z' AND 
INSERTED.RECORDTYPE = 'Z'	-->WHEN TRANSACTION IS COMMITTED
AND (  INSERTED.R_CUSTOMER = 
       (  SELECT ROWID FROM IDMASTER CUST (NOLOCK) 
          WHERE CUST.ROWID = INSERTED.R_CUSTOMER 
          AND CUST.IDGROUP IN ('35','535') -->SOME CUSTOMERS REQUIRE INVOICE & CM/DM 810 DOCUMENTS
       )
    OR INSERTED.TRANSACTIONTYPE= 'I'  -->EVERYONE ELSE ONLY WANTS INVOICE 810 DOCUMENTS
    )
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
AND (  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
    )  LIKE 'EDI%' -->ENSURE THAT EDI-VENDORID EXISTS FOR CUSTOMER IDGROUP
AND (  SELECT ISNULL(IDMASTER.IDSUBGROUP,'') FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
    )  != 'LEGACY' -->ENSURE IDSUBGROUP FOR THIS EDI-VENDORID IS NOT A LEGACY EDI ACCOUNT
AND INSERTED.R_CUSTOMER = 
    (  SELECT R_IDENTITY FROM IDCUSTOMER ICUST (NOLOCK) 
       WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER
       AND ISNULL(ICUST.USERDEFINEDCODE_9,'') = 'Y' --EDI CUSTOMERS ONLY
    )
	and inserted.transactionnumber = '10-43577-1'
*/





--855 TA GENERATE TRIGGER:
----------------------------------------------------------------------------------------------------------------------
--	STAGE: N=PENDING, L=CANCELLED, A=ASSIGNED, S=SHIPPABLE, C=COMPLETED												--
--	INVENTORYREVIEW: Y=INREVIEW(DON'T SEND YET)																		--
--	USERDEFINEDREFERENCE_10 = EMBEDDED ROWID IN OMTR POINTING TO VENDOR IN IDMASTER: EDI{IDGROUP}					--
--	IDCUSTOMER.USERDEFINEDCODE_7: Y=WORKORDER REQUIRED(LOWES ONLY)<--This works with Legacy logic but not with XM.	--
----------------------------------------------------------------------------------------------------------------------
DELETED.STAGE <> INSERTED.STAGE AND
(  (DELETED.STAGE != 'N' AND INSERTED.STAGE = 'L' ) OR 
			--SELECT STAGE, TRANSACTIONTYPE, INVENTORYREVIEW, 
			--(SELECT USERDEFINEDCODE_7 FROM IDCUSTOMER ICUST (NOLOCK) WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER) AS WOREQ, 
			--(SELECT IDENTITYID FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS VENDORID, 
			--(SELECT IDSUBGROUP FROM IDMASTER WHERE ROWID = CAST(USERDEFINEDREFERENCE_10 AS uniqueidentifier)) AS LEGACYFLAG 
			--FROM OMTRANSACTIONHEADER INSERTED (NOLOCK) WHERE (
   (  INSERTED.STAGE IN ('A','S','C') AND 
      ISNULL(INSERTED.INVENTORYREVIEW,'') <> 'Y'
   )
) AND
INSERTED.TRANSACTIONTYPE= 'I' AND
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
INSERTED.R_CUSTOMER = 
(  SELECT R_IDENTITY FROM IDCUSTOMER (NOLOCK) 
   WHERE USERDEFINEDCODE_7 = 'Y') AND 
(  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
   WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
   LIKE 'EDI%' 
AND
(  SELECT IDMASTER.IDSUBGROUP FROM IDMASTER (NOLOCK)
   WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) ) 
   = 'LEGACY'

/*
--XM 855 logic to replace Legacy 855 logic above: 
DELETED.STAGE <> INSERTED.STAGE                        -->WHEN STAGE IS CHANGED
AND ((  INSERTED.STAGE IN ('A','S','C')                -->TO A,S OR C 
        AND ISNULL(INSERTED.INVENTORYREVIEW,'') <> 'Y' -->AND NOT IN INVENTORYREVIEW
     ) OR 
     (  DELETED.STAGE != 'N' AND INSERTED.STAGE = 'L'  -->OR FROM A,S,C TO CANCELLED
    ))
AND INSERTED.RECORDTYPE = 'R' --TO BE SAFE
AND INSERTED.TRANSACTIONTYPE= 'I'                      -->INVOICES ONLY
--Added Suppress EDI flag to prevent Rural King fines--
AND INSERTED.USERDEFINEDCODE_10 IS NULL -->Suppress EDI flag not set
AND INSERTED.R_CUSTOMER = 
    (   SELECT ROWID FROM IDMASTER CUST (NOLOCK) 
        WHERE CUST.ROWID = INSERTED.R_CUSTOMER 
        AND CUST.IDGROUP IN ('535') -->ONLY INCLUDE CUSTOMERS REQUIRING 855 DOCUMENTS
    )
AND (  SELECT IDMASTER.IDENTITYID FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
    )  LIKE 'EDI%' -->ENSURE THAT EDI-VENDORID EXISTS FOR CUSTOMER IDGROUP
AND (  SELECT ISNULL(IDMASTER.IDSUBGROUP,'') FROM IDMASTER (NOLOCK)
       WHERE IDMASTER.ROWID = CAST(INSERTED.USERDEFINEDREFERENCE_10 AS UNIQUEIDENTIFIER) 
    )  != 'LEGACY' -->ENSURE IDSUBGROUP FOR THIS EDI-VENDORID IS NOT A LEGACY EDI ACCOUNT
AND INSERTED.R_CUSTOMER = 
    (  SELECT R_IDENTITY FROM IDCUSTOMER ICUST (NOLOCK) 
       WHERE ICUST.R_IDENTITY = INSERTED.R_CUSTOMER
       AND ISNULL(ICUST.USERDEFINEDCODE_9,'') = 'Y' --EDI CUSTOMERS ONLY
    )
*/
