----SCRIPT-BackfillNewEDIOrdersWithEDIVendorID

--GATHER DATA BEFORE THE UPDATE FOR COMPARISON.
--CHANGE RECORD SELECTION OF CUST.IDGROUP
SELECT 
	OH.TRANSACTIONNUMBER, 
	OH.TRANSACTIONDATE, 
	OH.TRANSACTIONTYPE, 
	OH.RECORDTYPE, 
	OH.STAGE, 
	OH.USERDEFINEDCODE_2 AS STEP, 
	CUST.IDENTITYID, CUST.NAME, CUST.IDGROUP, 
	VEND.IDENTITYID AS VENDORID, 
	OH.USERDEFINEDREFERENCE_10 AS OMVENDORREFERENCE		
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY=CUST.ROWID
JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)
WHERE OH.RECORDTYPE = 'R' 
AND OH.TRANSACTIONTYPE = 'I' 
AND OH.STAGE != 'L' 
AND OH.USERDEFINEDREFERENCE_10 IS NULL 
AND ICUST.USERDEFINEDCODE_9 = 'Y'
--AND CUST.IDENTITYID = '10043' 
AND CUST.IDGROUP = '43'

--START THE UPDATE.
BEGIN TRAN
UPDATE OMTRANSACTIONHEADER 
SET USERDEFINEDREFERENCE_10 = CONVERT(CHAR(36),VEND.ROWID)
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY=CUST.ROWID
JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)
WHERE OH.RECORDTYPE = 'R' 
AND OH.TRANSACTIONTYPE = 'I' 
AND OH.STAGE != 'L' 
AND OH.USERDEFINEDREFERENCE_10 IS NULL 
AND ICUST.USERDEFINEDCODE_9 = 'Y'
--AND CUST.IDENTITYID = '10043' 
AND CUST.IDGROUP = '43'

--VERIFY THAT THE UPDATE WORKED CORRECTLY BEFORE COMMITTING.
SELECT 
	OH.TRANSACTIONNUMBER, 
	OH.TRANSACTIONDATE, 
	OH.TRANSACTIONTYPE, 
	OH.RECORDTYPE, 
	OH.STAGE, 
	OH.USERDEFINEDCODE_2 AS STEP, 
	CUST.IDENTITYID, CUST.NAME, CUST.IDGROUP, 
	VEND.IDENTITYID AS VENDORID, 
	OH.USERDEFINEDREFERENCE_10 AS OMVENDORREFERENCE		
FROM OMTRANSACTIONHEADER OH (NOLOCK)
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER
JOIN IDCUSTOMER ICUST (NOLOCK) ON ICUST.R_IDENTITY=CUST.ROWID
JOIN IDMASTER VEND (NOLOCK) ON VEND.IDENTITYID = 'EDI'+TRIM(CUST.IDGROUP)
WHERE OH.RECORDTYPE = 'R' 
AND OH.TRANSACTIONTYPE = 'I' 
AND OH.STAGE != 'L' 
--AND OH.USERDEFINEDREFERENCE_10 IS NULL --IT IS NO LONGER NULL NOW.
AND ICUST.USERDEFINEDCODE_9 = 'Y'
--AND CUST.IDENTITYID = '10043' 
AND CUST.IDGROUP = '43'

--UNDO THE UPDATE...OR COMMIT WHEN READY.
--COMMIT	--
ROLLBACK

