--Fee Listing for Steve Coppedge
SELECT 
FH.R_PROFILE, FHP.PROFILECODE, 
'x'+FH.MISCFEECODE as MISCFEECODE, FH.DESCRIPTION, FH.COMMENT, 
FD.METHOD, FD.RATE, FD.R_VENDOR, VEND.IDENTITYID, VEND.NAME, FD.DESCRIPTION, FD.EFFECTIVESTARTDATE,
FD.CALCULATIONMETHOD, FD.PRICELEVEL, EXP.ACCOUNT AS EXPACCT, REV.ACCOUNT AS REVACCT  
FROM IMFEESHEADER FH (NOLOCK) 
LEFT JOIN IMFEESDETAIL FD (NOLOCK) ON FD.R_FEESHEADER = FH.ROWID 
LEFT JOIN IMFEESDP FHP (NOLOCK) ON FHP.ROWID = FH.R_PROFILE 
LEFT JOIN IDMASTER VEND (NOLOCK) ON VEND.ROWID = FD.R_VENDOR 
LEFT JOIN ACACCOUNT EXP (NOLOCK) ON EXP.ROWID = FD.R_EXPENSEGLACCOUNT 
LEFT JOIN ACACCOUNT REV (NOLOCK) ON REV.ROWID = FD.R_REVENUEGLACCOUNT 

SELECT COUNT(*) AS FEECOUNT FROM (
SELECT DISTINCT FH.MISCFEECODE FROM IMFEESHEADER FH (NOLOCK)
--WHERE FH.MISCFEECODE LIKE '%.89'
) X

