SELECT 
	WH.IDENTITYID AS WHID, 
	ITM.ITEMCODE, 
	GEN.DESCRIPTION_1 AS GENUSNAME, 
	ITM.REFERENCE_1 AS COMMONNAME, 
	CNT.PRINTEDCONTAINERCODE,
	DBO.FN_LISTPRICE(ITM.ROWID, NULL, NULL) AS LISTPRICE, 
	LOT.USERDEFINEDCODE_3 AS HOLDSTOP, 
	LOT.LOTCODE, 
	LQS.AVAILABLE, LQS.ON_HAND, LQS.NETAVAILABLE, 
	ITM.SPECIFICATIONCODE AS ITEMSPEC, 
	LOT.USERDEFINEDREFERENCE_1 AS LOTSPEC, 
	PGC.PRODUCTCATEGORYCODE AS PLANTGROUP, 
	ITM.REFERENCE_5+CNT.CONTAINERSORT AS SORTNAME, 
	ITM.SUBCLASSCODE AS QUALITYCODE,
	ITM.USERDEFINEDCODE_2 AS BRAND 
FROM IMITEM ITM (NOLOCK) 
JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUS
JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
JOIN IMLOT LOT (NOLOCK) ON LOT.R_ITEM = ITM.ROWID 
JOIN IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) ON LQS.R_LOT = LOT.ROWID 
WHERE ITM.RECORDTYPE = 'R' 
AND WH.IDENTITYID = '40' 
--AND ITM.ITEMCODE = '010030.011.1' 
--AND LOT.USERDEFINEDCODE_6 > 2022
--AND LOT.LOTCODE LIKE '%.S1'
ORDER BY 
PGC.PRODUCTCATEGORYCODE, 
ITM.REFERENCE_5, 
CNT.CONTAINERSORT, 
ITM.SUBCLASSCODE, 
LOT.LOTCODE
