--RUNTIME- 0:05 
--si_LTS AND SEASON_OH BY ITEM_LOT_LOC 
SELECT 
	WAREHOUSEID, 
	ITEMCODE, 
	LOTCODE, 
	LOCATIONCODE, 
	si_LTS, 
	SEASON_OH
FROM	(
		SELECT 
			WH.IDENTITYID AS WAREHOUSEID, 
			ITM.ITEMCODE, 
			VLOT.USERDEFINEDCODE_10 AS LOTSEASON, 
			VLOT.USERDEFINEDCODE_6 AS LOTYEAR, 
			VLOT.LOTCODE, 
			LOC.LOCATIONCODE, 
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_1', VLOT.ROWID, ITM.ROWID) AS si_LTS, 
			DBO.FNIM_GETUSERCALCULATEDFIELD('UserCalculated_6', VLOT.ROWID, ITM.ROWID) AS SEASON_OH 
		FROM IMLOCATIONQUANTITYSUMMARY LQS (NOLOCK) 
			JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = LQS.R_ITEM 
			JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = ITM.R_WAREHOUSE 
			JOIN VW_IMLOTVIEW VLOT (NOLOCK) ON VLOT.ROWID = LQS.R_LOT 
			LEFT JOIN IMLOCATION LOC (NOLOCK) ON LOC.ROWID = LQS.R_LOCATION 
		WHERE ITM.RECORDTYPE = 'R' 
		--AND WH.IDENTITYID ='10' 
		AND VLOT.USERDEFINEDCODE_6 <= '2022'
		AND CHARINDEX(SUBSTRING(VLOT.LOTCODE,4,1),'FSU') > 0 
		) X 
WHERE (si_LTS <> 0 OR SEASON_OH <> 0)
ORDER BY 
WAREHOUSEID, 
ITEMCODE, 
LOTSEASON, 
LOTYEAR, 
LOCATIONCODE 
