/* TAGS SHIPPED FOR DEB */
SELECT * FROM (
		SELECT 
			WH.IDENTITYID AS WAREHOUSEID,
			WH.NAME AS WAREHOUSENAME, 
			OH.TRANSACTIONNUMBER, 
			DBO.FN_SALEYEAR(OH.INVOICEDATE) AS SALEYEAR, 
			OH.INVOICEDATE, 
			ICONS.USERDEFINEDCODE_10 AS TAGCODE,
			CODES.DESCRIPTION_1 AS TAGDESCRIPTION, 
			SUBSTRING(PGC.PRODUCTCATEGORYCODE,1,3) AS PLANTGROUPCODE,
			ITM.REFERENCE_5 AS SORTNAMEVARIETY, 
			CNT.CONTAINERSORT, 
			ITM.SUBCLASSCODE, 
			ITM.ITEMCODE, 
			CNT.CONTAINERCODE, 
			CNT.PRINTEDCONTAINERCODE, 
			ITM.REFERENCE_1 AS COMMONNAME, 
			ITM.REFERENCE_2 AS BOTANICALNAME, 
			ITM.USERDEFINEDCODE_1 AS GENUSCODE,
			GEN.DESCRIPTION_1 AS GENUSNAME,
			OD.QUANTITYSHIPPED--,	IL.OUT_SHIPPED
		FROM OMTRANSACTIONHEADER OH (NOLOCK) 
		JOIN OMTRANSACTIONDETAIL OD (NOLOCK) ON OD.R_TRANSACTIONHEADER = OH.ROWID 
				--THIS WILL INTRODUCE MULTIPLE RECORDS TO THE CURRENT DATASET, ELLEN WANTS THIS TO REPORT ON OUT_SHIPPED
				--NOT GONNA DO THIS, DON'T THINK IT IS IMPORTANT TO DEB.
				--LEFT JOIN IMTRANSACTIONLOCATION IL (NOLOCK) ON IL.R_TRANSACTIONDETAIL = OD.ROWID
		JOIN IDMASTER WH (NOLOCK) ON WH.ROWID = OH.R_FMSHIPPER
		JOIN IMITEM ITM (NOLOCK) ON ITM.ROWID = OD.R_ITEM 
		JOIN IMPRODUCTCATEGORY PGC (NOLOCK) ON PGC.ROWID = ITM.R_PRODUCTCATEGORY
		JOIN IMCONTAINER CNT (NOLOCK) ON CNT.ROWID = ITM.R_CONTAINERCODE
		JOIN IMCODES GEN (NOLOCK) ON GEN.CODE = ITM.USERDEFINEDCODE_1 AND GEN.CODETYPE = '11'	--GENUSNAME
		JOIN IDCONSIGNEE ICONS (NOLOCK) ON ICONS.R_IDENTITY = OH.R_SHIPPER
		JOIN IDCODES CODES (NOLOCK)  ON CODES.CODE = ICONS.USERDEFINEDCODE_10 AND CODES.CODETYPE='81'	--TAGDESCRIPTION
		WHERE OH.RECORDTYPE = 'Z' 
		AND OH.TRANSACTIONTYPE = 'I' 
		AND OD.QUANTITYSHIPPED !=0
		AND ICONS.USERDEFINEDCODE_10	--IN ('0001','0300','0301','0302','0305','0306','0701')
										IN ('0001','0006','0300','0301','0302','0305','0306','0701')
		--ORDER BY
		--	WH.IDENTITYID, -- AS WAREHOUSEID, 
		--	OH.INVOICEDATE, 
		--	ICONS.USERDEFINEDCODE_10, -- AS TAGCODE, 
		--	PGC.PRODUCTCATEGORYCODE, -- AS PLANTGROUPCODE, 
		--	ITM.REFERENCE_5, -- AS SORTNAMEVARIETY, 
		--	CNT.CONTAINERSORT, 
		--	ITM.SUBCLASSCODE 
) X
WHERE WAREHOUSEID = '10'
AND SALEYEAR = '2024'

ORDER BY
	WAREHOUSEID, 
	INVOICEDATE, 
	TAGCODE, 
	PLANTGROUPCODE, 
	SORTNAMEVARIETY, 
	CONTAINERSORT, 
	SUBCLASSCODE 
