--	#===============================================================================#
--	# WHAT:	FIND DUPLICATE SYNONYMS CAUSING THE CUSTOMERLISTING REPORT TO ERROR		#
--	# FOR:		STEPHANIE HOLMES													#
--	# ON:		2022/10/25															#
--	#===============================================================================#

SELECT 
	CUST.ROWID AS CUSTROWID, 
	CUST.IDENTITYID AS CUSTOMERID, 
	CUST.NAME AS CUSTOMERNAME, 
	SYN.*, 
	DUPCHK.CNT AS DUPCOUNT 
FROM IDMASTER CUST (NOLOCK) 
JOIN IDSYNONYMS SYN (NOLOCK) ON SYN.R_IDENTITY = CUST.ROWID 
JOIN	(	SELECT R_IDENTITY, IDTYPE, COUNT(*) CNT 
			FROM IDSYNONYMS (NOLOCK) 
			GROUP BY R_IDENTITY, IDTYPE 
		) AS DUPCHK ON DUPCHK.R_IDENTITY = SYN.R_IDENTITY 
WHERE DUPCHK.CNT > 1 
ORDER BY LASTUPDATEDATETIME DESC 

--FIND MISMATCHES BETWEEN INV AND WRONG IDTYPE 02>>>
SELECT * FROM IDSYNONYMS SYN (NOLOCK)
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = SYN.R_IDENTITY
WHERE USERDEFINEDCODE_1 = 'INV'
AND IDTYPE = '02' --CORRECT VALUE S/B '01' 
ORDER BY SYN.LASTUPDATEDATETIME DESC

--FIND MISMATCHES BETWEEN ACK AND WRONG IDTYPE 01>>>
SELECT * FROM IDSYNONYMS SYN (NOLOCK)
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = SYN.R_IDENTITY
WHERE USERDEFINEDCODE_1 = 'ACK'
AND IDTYPE = '01' --CORRECT VALUE S/B '02' 
ORDER BY SYN.LASTUPDATEDATETIME DESC
