--ListOfAlternateConsigneeNames
SELECT 
ConsigneeIdentityID,
ConsigneeName,
ConsigneeAlternateName
FROM VW_IDCONSIGNEEVIEW VCONS (NOLOCK)
--where vcons.ConsigneeAlternateName is null

--WHERE VCONS.CONSIGNEENAME != VCONS.CONSIGNEEALTERNATENAME

/*
SELECT 
OH.TRANSACTIONNUMBER,
CUST.IDENTITYID AS CUSTID, CUST.NAME AS CUSTNAME, 
CONS.IDENTITYID AS CONSID, CONS.NAME AS CONSNAME, 
VCONS.ConsigneeAlternateName
FROM OMTRANSACTIONHEADER OH (NOLOCK) 
JOIN IDMASTER CUST (NOLOCK) ON CUST.ROWID = OH.R_CUSTOMER 
JOIN IDMASTER CONS (NOLOCK) ON CONS.ROWID = OH.R_SHIPPER 
LEFT JOIN VW_IDCONSIGNEEVIEW VCONS (NOLOCK) ON VCONS.CONSIGNEEMASTERROWID = OH.R_SHIPPER 
WHERE CONS.NAME != VCONS.ConsigneeAlternateName 
OR OH.TRANSACTIONNUMBER = '10-30051'
--WHERE CONS.NAME != ISNULL(VCONS.ConsigneeAlternateName,'') 
--AND CUST.IDENTITYID = '61576'
--WHERE OH.TRANSACTIONNUMBER IN ('10-30051', '10-16582', '10-47502')
ORDER BY VCONS.ConsigneeAlternateName
*/